# INICIO

In [3]:
import os
import sys
import pandas as pd
import numpy as np
from datetime import datetime
import import_ipynb
from shared_functions import DataframeLoader, Shared
import import_ipynb
from libraries.calculosba_areacalculo import AreaCalculoSBA
from libraries.calculo_objetivos_cualitativos import calculo_cumplimiento_objetivos_cualitativos
from libraries.DataframesUtils import CalculoDataframes
base_dir = 'C:\\Users\\HP\\Documents\\Proyectos\\Liquidations-Incentives-Jupyter'
sub_direct = 'archivos-fuente-128 (1)'
folder_bbraun_source = os.path.join(base_dir, 'source', sub_direct)
folder_bbraun_output = os.path.join(base_dir, 'output')
print(folder_bbraun_source)

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\source\archivos-fuente-128 (1)

In [4]:
dataframe_loader = DataframeLoader(
    base_dir=base_dir,
    sub_direct=sub_direct
)
shared = Shared()
print(dataframe_loader.cargar_dataframes)

<bound method DataframeLoader.cargar_dataframes of <shared_functions.DataframeLoader object at 0x000001CBE2F67020>>

In [5]:
(
        df_resultado_detallado_previo,
        df_resultado_liquidaciones_previo,
        df_empleados,
        df_empleados_inactivos,
        df_tipos_empleados,
        df_clusters_empleado,
        df_zonas_empleado,
        df_salarios_variables,
        df_parrillas,
        df_venta_recaudo_real,
        df_venta_recaudo_presupuesto,
        df_venta_por_zona,
        df_recaudo_por_zona,
        df_rentabilidad,
        df_venta_otras_companias,
        df_recaudo_otras_companias,
        df_venta_recaudo_kams,
        df_rentabilidad_kam,
        df_venta_servicios_mtto,
        df_objetivos_cualitativos,
        df_kpi_calidad,
        df_incentivos_por_empleado,
        df_area_calculo_sba,
        df_factores_liquidacion,
        df_cluster_plan_real_recaudo,
        df_zona_plan_real_venta_ch,
        df_rentabilidad_zona,
        df_resultados_variables_cualitativas,
        df_zonas_clusters_empleado,
        df_centros_costos,
        df_empleados_centros_costos,
        df_centros_costos_grupos_productos_divisiones,
        df_parrillas_tipos_calculos,
        df_area_calculo_sba_centros_costos,
        df_renal_ambulatorio,
        df_TRM,
        codigos_ve_vc,
        _dataframes_entrada,
        fecha_liquidacion,
        meses_incentivos,
        OUTPUT_FOLDER
    ) = dataframe_loader.cargar_dataframes(base_dir, folder_bbraun_source)

In [6]:
# df_parrillas[df_parrillas['Variable'] == 'VentaFacturadaGrupoClientesKAMSSub']

In [7]:
df_cluster_plan_real_recaudo

    Cluster      Fecha          Real   Presupuesto
0         0 2025-01-01  3.466734e+09  4.004950e+09
1         0 2025-02-01  3.309305e+08  7.731713e+08
2         0 2025-03-01  1.270972e+09  9.372508e+08
3         0 2025-04-01  8.324854e+08  7.719309e+08
4         0 2025-05-01  7.292610e+08  8.718020e+08
..      ...        ...           ...           ...
247       9 2025-08-01  6.711453e+08  1.128725e+09
248       9 2025-09-01  6.870137e+08  1.137368e+09
249       9 2025-10-01  9.426040e+08  1.115119e+09
250       9 2025-11-01  6.470081e+08  1.140811e+09
251       9 2025-12-01  4.731448e+08  1.156505e+09

[252 rows x 4 columns]

In [8]:
df_zonas_clusters_empleado

    TipoEmpleado CodigoEmpleado  AreaCalculo    Zona Cluster
0             VE        5002697            5  Centro       0
1             VE        5002697            5  Centro       5
2             VE        5002697            5  Centro       7
3             VE        5002697            5  Centro      20
4             VE        5002697            5  Centro      21
..           ...            ...          ...     ...     ...
336           VE       37270929            7   Norte       0
337           VE       37270929            7   Norte      20
338           VE       37270929            7   Norte       7
339           VE       37270929            7   Norte      13
340           VE       37270929            7   Norte      14

[341 rows x 5 columns]

In [9]:
def unir_dataframes_por_columnas_comunes(df1, df2, how='inner'):
    """
    Une dos DataFrames basándose en sus columnas comunes con un tipo de unión especificado.
    
    Parámetros:
    - df1: Primer DataFrame.
    - df2: Segundo DataFrame.
    - how: Tipo de unión ('left', 'right', 'outer', 'inner'). Por defecto es 'inner'.
    
    Retorna:
    - DataFrame resultante de la unión.
    """
    # Encuentra las columnas comunes entre ambos DataFrames
    columnas_comunes = df1.columns.intersection(df2.columns)
    print(columnas_comunes)
    # Une los DataFrames basándose en las columnas comunes y el tipo de unión especificado
    df_unido = pd.merge(df1, df2, on=columnas_comunes.tolist(), how=how)
    
    return df_unido

In [10]:
columns_name_euros = ['RealCOP', 'PresupuestoCOP', 'PorcentajeCumplimientoCOP']
columns_name_list = ['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']
colums_name = columns_name_list + columns_name_euros
colums_name

['Contexto',
 'Variable',
 'Fecha',
 'Real',
 'Presupuesto',
 'PorcentajeCumplimiento',
 'RealCOP',
 'PresupuestoCOP',
 'PorcentajeCumplimientoCOP']

In [11]:
dataframe_loader.df_renal_ambulatorio

,CodigoEmpleado,TipoEmpleado,Fecha,PlanVentaTotal,PlanVentaCobradaRenal,RealVentaTotal,RealVentaCobradaRenal
0,70020733,VC,2025-01-01,0.000000e+00,3.603004e+09,0.000000e+00,3.414838e+09
1,70020733,VC,2025-02-01,0.000000e+00,4.015092e+08,0.000000e+00,2.318170e+08
2,70020733,VC,2025-03-01,1.010107e+08,4.371081e+08,4.898174e+07,3.250664e+08
3,70020733,VC,2025-04-01,1.010107e+08,4.114996e+08,1.168091e+08,6.926579e+08
4,70020733,VC,2025-05-01,1.443010e+07,4.588223e+08,2.900474e+07,3.876283e+08
5,70020733,VC,2025-06-01,1.154408e+08,4.840730e+08,8.478787e+08,2.029854e+08
6,70020733,VC,2025-07-01,2.597418e+08,4.605407e+08,1.653069e+08,3.115334e+08
7,70020733,VC,2025-08-01,2.700667e+08,4.988475e+08,3.039041e+08,3.243254e+08
8,70020733,VC,2025-09-01,1.971858e+08,5.410063e+08,1.199201e+08,1.176529e+09
9,70020733,VC,2025-10-01,1.292057e+09,6.049855e+08,6.530957e+07,3.391433e+08
10,70020733,VC,2025-11-01,2.071648e+08,7.456874e+08,1.566934e+07,2.417650e+08
11,70020733,VC,2025-12-01,1.607648e+08,7.821859e+08,2.764713e+09,5.990458e+09
12,70034174,VC,2025-01-01,1.213789e+08,3.603004e+09,2.454276e+07,3.414838e+09
13,70034174,VC,2025-02-01,1.213789e+08,4.015092e+08,4.674840e+07,2.318170e+08
14,70034174,VC,2025-03-01,1.416088e+08,4.371081e+08,6.440906e+07,3.250664e+08
15,70034174,VC,2025-04-01,1.416088e+08,4.114996e+08,7.236450e+07,6.926579e+08
16,70034174,VC,2025-05-01,1.618386e+08,4.588223e+08,8.410756e+07,3.876283e+08
17,70034174,VC,2025-06-01,1.618386e+08,4.840730e+08,4.493425e+07,2.029854e+08
18,70034174,VC,2025-07-01,3.641368e+08,4.605407e+08,1.203300e+08,3.115334e+08
19,70034174,VC,2025-08-01,1.102847e+09,4.988475e+08,1.280526e+09,3.243254e+08
20,70034174,VC,2025-09-01,3.596640e+08,5.410063e+08,2.766229e+08,1.176529e+09
21,70034174,VC,2025-10-01,1.468791e+09,6.049855e+08,2.446175e+08,3.391433e+08
22,70034174,VC,2025-11-01,3.751859e+08,7.456874e+08,2.122314e+09,2.417650e+08
23,70034174,VC,2025-12-01,1.858344e+08,7.821859e+08,1.390872e+09,5.990458e+09

In [12]:
# Traer áreas de cálculo y tipo de empleado de la maestra de empleados
empleados = df_empleados[['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo', 'FechaIngreso']].copy()
empleados_inactivos = df_empleados_inactivos[['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo', 'FechaIngreso']].copy()
total_empleados = pd.concat([empleados, empleados_inactivos])
total_empleados

    TipoEmpleado CodigoEmpleado  AreaCalculo FechaIngreso
0             VC        5004523            3   2023-10-01
1             MK        5016740           13   2023-07-01
2             VE        5004287            4   2013-05-17
3             VE        5002697            5   1997-06-10
4            AD2       52792592            2   2021-01-01
..           ...            ...          ...          ...
151          AD1       13874027           10   2020-05-01
152           VE      700020681            5   2022-05-01
153           VE        5005917            8   2017-04-01
154           VC        5036653            5   2020-04-01
155           VC        9990009            4   2025-07-01

[309 rows x 4 columns]

In [13]:
df_venta_recaudo_real.head()

,CodigoEmpleado,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Venta,Recaudo
0,1111117,BA,0,Norte,A45,Renal AMB,80,2025-12-01,6.526043e+08,6.526043e+08
1,1111117,BA,0,Suroccidente,A45,RENAL AMB,80,2025-08-01,2.173649e+05,2.957838e+05
2,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-11-01,1.478919e+05,0.000000e+00
3,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-12-01,0.000000e+00,2.173649e+05
4,1111122,HC,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,2.818770e+07,0.000000e+00

In [14]:
df_venta_recaudo_real['ZonaGeografica'] = df_venta_recaudo_real['ZonaGeografica'].str.replace(
    r'\b\w+\b', lambda x: x.group().title(), regex=True
)

df_venta_recaudo_presupuesto['ZonaGeografica'] = df_venta_recaudo_presupuesto['ZonaGeografica'].str.replace(
    r'\b\w+\b', lambda x: x.group().title(), regex=True
)

In [15]:
df_venta_recaudo_real.head()

,CodigoEmpleado,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Venta,Recaudo
0,1111117,BA,0,Norte,A45,Renal AMB,80,2025-12-01,6.526043e+08,6.526043e+08
1,1111117,BA,0,Suroccidente,A45,RENAL AMB,80,2025-08-01,2.173649e+05,2.957838e+05
2,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-11-01,1.478919e+05,0.000000e+00
3,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-12-01,0.000000e+00,2.173649e+05
4,1111122,HC,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,2.818770e+07,0.000000e+00

In [16]:
df_venta_recaudo_presupuesto.head()

,CodigoEmpleado,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Venta,Recaudo
0,1111117,BA,0,Norte,A45,Renal AMB,80,2025-12-01,0.0,0.0
1,1111117,BA,0,Suroccidente,A45,RENAL AMB,80,2025-08-01,0.0,0.0
2,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-11-01,0.0,0.0
3,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-12-01,0.0,0.0
4,1111122,HC,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,0.0,0.0

In [17]:
df_parrillas[df_parrillas['Variable'] == 'VentaFacturadaPortafolioRenalSub']

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
99,5003490,VentaFacturadaPortafolioRenalSub,5003490_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
221,50324561,VentaFacturadaPortafolioRenalSub,50324561_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
278,40927502,VentaFacturadaPortafolioRenalSub,40927502_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
407,70020733,VentaFacturadaPortafolioRenalSub,70020733_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
414,1111114,VentaFacturadaPortafolioRenalSub,1111114_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
437,70034174,VentaFacturadaPortafolioRenalSub,70034174_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
754,5003979,VentaFacturadaPortafolioRenalSub,5003979_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
1036,1120741903,VentaFacturadaPortafolioRenalSub,1120741903_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
1043,5036651,VentaFacturadaPortafolioRenalSub,5036651_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
1294,1111117,VentaFacturadaPortafolioRenalSub,1111117_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
1556,39099258,VentaFacturadaPortafolioRenalSub,39099258_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...
1714,5036653,VentaFacturadaPortafolioRenalSub,5036653_1,0.175,1,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...

In [18]:
df_area_calculo_sba[df_area_calculo_sba['TipoEmpleado'] == 'GD']

   TipoEmpleado  AreaCalculo  Consecutivo Division GrupoProducto  SBA
29           GD            1            1       AE           001  NaN
30           GD            1            1       AE           003  NaN
31           GD            1            1       AE           005  NaN
32           GD            1            1       AE           006  NaN
33           GD            1            1       AE           801  NaN
34           GD            1            1       AE           805  NaN
35           GD            1            1       AE           CEK  NaN
36           GD            1            1       AE           CEK   30
37           GD            1            1       AE           M06  NaN
38           GD            1            1       AE           M07  NaN
39           GD            1            1       AE           M08  NaN
40           GD            2            1       HC           610  NaN
41           GD            2            1       HC           620  NaN
42           GD            2            1       HC           630  NaN
43           GD            2            1       HC           640  NaN
44           GD            2            1       HC           680  NaN
45           GD            2            1       HC           681  NaN
46           GD            2            1       HC           CDK   03
47           GD            2            1       HC           CDK   12
48           GD            3            1       BA           660  NaN
49           GD            3            1       BA           902  NaN
50           GD            3            1       BA           A32  NaN
51           GD            3            1       BA           A33  NaN
52           GD            3            1       BA           A34  NaN
53           GD            3            1       BA           A35  NaN
54           GD            3            1       BA           A45  NaN

### Se validan los dataframes de entrada

In [19]:
# for df in _dataframes_entrada:
#     print(f'*** {df["name"]} ***')
#     print(' - Head:')
#     print(df['df'].head())
#     print('')

### Funciones útiles

In [20]:
# def sobreescribir_resultados_cualitativos(main, variable, columnas_extra, columnas_extra_merge, pre_merge_lambda=None):
#     print(columnas_extra, columnas_extra_merge)
#     resultados_cualitativos_variable = df_resultados_variables_cualitativas[columnas_extra + ['Variable', 'Fecha', 'PorcentajeCumplimiento']]
#     resultados_cualitativos_variable = resultados_cualitativos_variable[resultados_cualitativos_variable['Variable'] == variable]
#     if pre_merge_lambda:
#         resultados_cualitativos_variable = pre_merge_lambda(resultados_cualitativos_variable)
#     main_df = pd.merge(
#         left=main,
#         right=resultados_cualitativos_variable.rename(columns={'PorcentajeCumplimiento': 'PorcentajeCumplimientoPrecargado'}),
#         on=columnas_extra_merge+['Fecha', 'Variable'],
#         how='outer'
#     )
#     main_df['Real'] = np.where(
#         main_df['PorcentajeCumplimientoPrecargado'].isnull(),
#         main_df['Real'],
#         np.nan
#     )
#     main_df['Presupuesto'] = np.where(
#         main_df['PorcentajeCumplimientoPrecargado'].isnull(),
#         main_df['Presupuesto'],
#         np.nan
#     )
#     main_df['PorcentajeCumplimiento'] = np.where(
#         main_df['PorcentajeCumplimientoPrecargado'].isnull(),
#         main_df['PorcentajeCumplimiento'],
#         main_df['PorcentajeCumplimientoPrecargado']
#     )
#     main_df.drop(columns=['PorcentajeCumplimientoPrecargado'], inplace=True)

#     return main_df

In [21]:
# def f_calculo_centro_costo_variable(main , variable):
#     if 'CodigoCentroCosto' not in main.columns:
#         main = main.merge(
#             df_centros_costos_grupos_productos_divisiones.rename(columns={'ConsecutivoParrilla':'Consecutivo'}),
#             on=['Division', 'GrupoProducto'],
#             how='left'
#         )
#     main['Consecutivo'] = main['Consecutivo'].astype(str)
#     main['Consecutivo'] = main['Consecutivo'].str.replace('.0', '')
#     main['Contexto'] = main['CodigoEmpleado'] + '_' + main['Consecutivo']
#     cumplimiento_rentabilidad_grupo_clientes_cm2_sub
#     main['Real'] = main.groupby(['Contexto', 'GrupoProducto', 'Division', 'CodigoCentroCosto'])['Real'].transform(pd.Series.cumsum)
#     main['Presupuesto'] = main.groupby(['Contexto', 'GrupoProducto', 'Division', 'CodigoCentroCosto'])['Presupuesto'].transform(pd.Series.cumsum)
#     #     main['RealTotal'] = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real']].transform(pd.Series.sum)
#     #     main['Porcentaje Aplicado'] = main['Real'] / main['RealTotal']
#     main['Variable'] = variable
#     return main

In [22]:
# def f_calculo_centro_costo_variable_tipo_empleado(main, variable, tipo_empleado):    
#     main = main.merge(
#         df_centros_costos_grupos_productos_divisiones.rename(columns={'ConsecutivoParrilla':'Consecutivo'}),
#         on=['Division', 'GrupoProducto'],
#         how='left'
#     )
#     main['AreaCalculo'] = main['AreaCalculo'].astype(str)
#     main['Consecutivo'] = main['Consecutivo'].astype(str)
#     main['Contexto'] = tipo_empleado.lower() +'_'+ main['AreaCalculo'].str.cat(main['Consecutivo'],sep="_")
#     main = main.groupby(['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)    
#     main['Real'] = main.groupby(['Contexto', 'GrupoProducto', 'Division', 'CodigoCentroCosto'])['Real'].transform(pd.Series.cumsum)
#     main['Presupuesto'] = main.groupby(['Contexto', 'GrupoProducto', 'Division', 'CodigoCentroCosto'])['Presupuesto'].transform(pd.Series.cumsum)
#     main['Variable'] = variable
#     return main

In [23]:
# def validar_calculo_centro_costo(main, contexto, fecha):
    
#     real = main[
#         (main['Contexto'] == contexto) &
#         (main['Fecha'] == fecha)
#     ]['Real'].sum()
    
#     presupuesto = main[
#         (main['Contexto'] == contexto) &
#         (main['Fecha'] == fecha)
#     ]['Presupuesto'].sum()
    
#     return real, presupuesto

In [24]:
# def validar_calculo_centro_costo_division_sub(main, contexto, fecha):
    
#     real = main[
#         (main['Contexto'] == contexto) &
#         (main['Fecha'] == fecha)
#     ].groupby(['AreaCalculo', 'Consecutivo', 'Variable'])['Real'].transform(pd.Series.cumsum)
    
#     presupuesto = main[
#         (main['Contexto'] == contexto) &
#         (main['Fecha'] == fecha)
#     ].groupby(['AreaCalculo', 'Consecutivo', 'Variable'])['Presupuesto'].transform(pd.Series.cumsum)
    
#     return real, presupuesto

### Completamos el dataframe de SBAs y Áreas de cálculo

In [25]:
productos_venta = df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA']]
productos_presupuesto = df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA']]
productos = pd.concat([productos_venta, productos_presupuesto])
productos = productos.drop_duplicates()
productos

      Division GrupoProducto SBA
0           BA           A45  80
4           HC           620  36
14          AE           006  36
16          AE           001  30
24          AE           003  35
32          AE           005  33
36          AE           005  35
45          AE           801  32
53          AE           805  30
59          AE           M06  31
67          AE           M07  33
73          AE           M08  33
79          BA           A32  84
87          BA           A33  86
89          BA           A34  85
97          HC           680  03
112         AE           001  32
115         AE           001  33
171         AE           801  30
266         BA           660  81
269         BA           A45  81
275         HC           610  01
278         HC           610  02
302         HC           620  13
305         HC           620  15
308         HC           620  16
357         HC           630  08
360         HC           630  12
396         BA           660  80
1087        HC           CDK  12
1272        HC           630  03
1596        AE           801  33
1753        AE           M07  30
2288        AE           CEK  30
2643        AE           801  31
3327        AE           M06  30
4061        HC           640  03
6661        AE           CEK  35
6682        AE           M06  38
7008        BA           A45  89
9285        HC           630  19
11856       AE           M06  32
11862       AE           M06  33
15612       BA           A35  87
17460       AE           001  31

In [26]:
# TODO: Dejar de usar esta funcionalidad - utilizar la refactorizada

# productos_venta = df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA']]
# productos_presupuesto = df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA']]
# productos = pd.concat([productos_venta, productos_presupuesto])
# productos = productos.drop_duplicates()

##
_area_calculo_sba_notnull = df_area_calculo_sba[
    (df_area_calculo_sba['SBA'].notnull()) |
    (df_area_calculo_sba['SBA'] != '')
]
##
_area_calculo_sba_notnull

    TipoEmpleado  AreaCalculo  Consecutivo Division GrupoProducto    SBA
0             AD            1            1    BBMCO         BBMCO  BBMCO
1             AD            2            1    BBMCO         BBMCO  BBMCO
2             AD            3            1    BBMCO         BBMCO  BBMCO
3             AD            4            1    BBMCO         BBMCO  BBMCO
4            AD1            1            1    BBMCO         BBMCO  BBMCO
..           ...          ...          ...      ...           ...    ...
316           VE           12            2       AE           M06    NaN
317           VE           13            1       AE           003    NaN
318           VE           13            1       AE           CEK     30
319           VE           13            1       AE           CEK     35
320           VE           13            2       AE           801    NaN

[321 rows x 6 columns]

In [27]:
_area_calculo_sba_por_grupo = df_area_calculo_sba[
    (df_area_calculo_sba['GrupoProducto'].isnull()) |
    (df_area_calculo_sba['GrupoProducto'] == '')
]
_area_calculo_sba_por_grupo

    TipoEmpleado  AreaCalculo  Consecutivo Division GrupoProducto  SBA
20            GC            1            1       HC           NaN  NaN
21            GC            1            2       AE           NaN  NaN
22            GC            1            3       BA           NaN  NaN
23            GC            2            1       HC           NaN  NaN
24            GC            2            2       AE           NaN  NaN
25            GC            2            3       BA           NaN  NaN
26            GC            3            1       HC           NaN  NaN
27            GC            3            2       AE           NaN  NaN
28            GC            3            3       BA           NaN  NaN
147          KAM            4            1   GRPCLI           NaN  NaN
148           MK            1            1       HC           NaN  NaN
151           MK            1            2       AE           NaN  NaN
203           MK           11            1       HC           NaN  NaN
206           MK           11            2       AE           NaN  NaN
212           MK           12            1       HC           NaN  NaN
215           MK           12            2       AE           NaN  NaN
221           MK           13            1       HC           NaN  NaN
224           MK           13            2       AE           NaN  NaN
234          MK1            9            1    BBMCO           NaN  NaN
274           VC            5            4       AE           NaN  NaN

In [28]:
_area_calculo_sba_por_grupo = pd.merge(
    left=_area_calculo_sba_por_grupo[['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Division']],
    right=productos,
    on='Division',
    how='left'
)
_area_calculo_sba_por_grupo
##

    TipoEmpleado  AreaCalculo  Consecutivo Division GrupoProducto SBA
0             GC            1            1       HC           620  36
1             GC            1            1       HC           680  03
2             GC            1            1       HC           610  01
3             GC            1            1       HC           610  02
4             GC            1            1       HC           620  13
..           ...          ...          ...      ...           ...  ..
299           VC            5            4       AE           CEK  35
300           VC            5            4       AE           M06  38
301           VC            5            4       AE           M06  32
302           VC            5            4       AE           M06  33
303           VC            5            4       AE           001  31

[304 rows x 6 columns]

In [29]:
_area_calculo_sba_por_grupo[_area_calculo_sba_por_grupo['TipoEmpleado'] == 'GD']

Empty DataFrame
Columns: [TipoEmpleado, AreaCalculo, Consecutivo, Division, GrupoProducto, SBA]
Index: []

In [30]:

_area_calculo_sba_por_sba = df_area_calculo_sba[
    (
        (df_area_calculo_sba['SBA'].isnull()) |
        (df_area_calculo_sba['SBA'] == '')
    ) &
    (
        (df_area_calculo_sba['GrupoProducto'].notnull()) |
        (df_area_calculo_sba['GrupoProducto'] != '')
    )
]
_area_calculo_sba_por_sba = pd.merge(
    left=_area_calculo_sba_por_sba[['TipoEmpleado', 'AreaCalculo', 'GrupoProducto', 'Consecutivo', 'Division']],
    right=productos[['GrupoProducto', 'SBA']],
    on='GrupoProducto',
    how='left'
)

area_calculo_sba_completo = pd.concat([
    _area_calculo_sba_notnull,
    _area_calculo_sba_por_grupo,
    _area_calculo_sba_por_sba
])
area_calculo_sba_completo = area_calculo_sba_completo[['AreaCalculo', 'Consecutivo', 'Division', 'GrupoProducto', 'SBA', 'TipoEmpleado']]
area_calculo_sba_completo.fillna('', inplace=True)
area_calculo_sba_completo.drop_duplicates(inplace=True, subset=area_calculo_sba_completo.columns)
area_calculo_sba_completo

     AreaCalculo  Consecutivo Division GrupoProducto    SBA TipoEmpleado
0              1            1    BBMCO         BBMCO  BBMCO           AD
1              2            1    BBMCO         BBMCO  BBMCO           AD
2              3            1    BBMCO         BBMCO  BBMCO           AD
3              4            1    BBMCO         BBMCO  BBMCO           AD
4              1            1    BBMCO         BBMCO  BBMCO          AD1
..           ...          ...      ...           ...    ...          ...
301           13            1       AE           003     35           VE
302           13            2       AE           801     32           VE
303           13            2       AE           801     30           VE
304           13            2       AE           801     33           VE
305           13            2       AE           801     31           VE

[858 rows x 6 columns]

In [31]:
area_calculo_sba_completo[
    (area_calculo_sba_completo['TipoEmpleado'] == 'GD') &
    (area_calculo_sba_completo['AreaCalculo'] == 3) &
    (area_calculo_sba_completo['Consecutivo'] == 5)
]

Empty DataFrame
Columns: [AreaCalculo, Consecutivo, Division, GrupoProducto, SBA, TipoEmpleado]
Index: []

In [32]:
area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado'] == 'AD4']

    AreaCalculo  Consecutivo Division GrupoProducto    SBA TipoEmpleado
16            1            1    BBMCO         BBMCO  BBMCO          AD4
17            1            2    BBMEC         BBMEC  BBMEC          AD4
18            2            1    BBMCO         BBMCO  BBMCO          AD4

### Remplazar funcionalidad - Funcionalidad con Refactorización

In [33]:
c_area_calculo_sba = AreaCalculoSBA(dataframe_loader)
area_calculo_sba_completo = c_area_calculo_sba.get_area_calculo_sba_completo()
area_calculo_sba_completo

     AreaCalculo  Consecutivo Division GrupoProducto    SBA TipoEmpleado
0              1            1    BBMCO         BBMCO  BBMCO           AD
1              2            1    BBMCO         BBMCO  BBMCO           AD
2              3            1    BBMCO         BBMCO  BBMCO           AD
3              4            1    BBMCO         BBMCO  BBMCO           AD
4              1            1    BBMCO         BBMCO  BBMCO          AD1
..           ...          ...      ...           ...    ...          ...
301           13            1       AE           003     35           VE
302           13            2       AE           801     32           VE
303           13            2       AE           801     30           VE
304           13            2       AE           801     33           VE
305           13            2       AE           801     31           VE

[858 rows x 6 columns]

In [34]:
area_calculo_sba_completo[
    (area_calculo_sba_completo['TipoEmpleado'] == 'GD') &
    (area_calculo_sba_completo['AreaCalculo'] == 3) &
    (area_calculo_sba_completo['Consecutivo'] == 5)
]

Empty DataFrame
Columns: [AreaCalculo, Consecutivo, Division, GrupoProducto, SBA, TipoEmpleado]
Index: []

In [35]:
c_area_calculo_sba.get_area_calculo_sba_completo_by_tipo_empleado('VC')

     AreaCalculo  Consecutivo Division GrupoProducto SBA TipoEmpleado
236            3            1       AE           805               VC
237            3            1       AE           M06               VC
238            3            2       AE           005               VC
239            3            2       AE           M07               VC
240            3            2       AE           M08               VC
..           ...          ...      ...           ...  ..          ...
237            5            3       HC           630  08           VC
238            5            3       HC           630  12           VC
239            5            3       HC           630  03           VC
241            5            3       HC           640  03           VC
242            5            3       HC           680  03           VC

[125 rows x 6 columns]

# Se calculan los resultados para la maestra de resultados

## 1. Objetivos cualitativos (ObjetivosCualitativos)

In [36]:
df_objetivos_cualitativos[df_objetivos_cualitativos["CodigoEmpleado"]=='79539822']

         Fecha CodigoEmpleado  PorcentajeCumplimiento
142 2025-12-01       79539822                     1.2

In [37]:
def asignar_valor_porcentaje(tipo_empleado, area_calculo, fecha, porcentaje_cumplimiento):
    if not porcentaje_cumplimiento:
        if tipo_empleado in ['VC', 'VE', 'MK']:
            return 0.80
        elif tipo_empleado == "AD2":
            return 0.90
        else:
            return 0.88   
    return porcentaje_cumplimiento

porcentaje_objetivos = 0
cumplimiento_objetivos_cualitativos = pd.DataFrame()

cumplimiento_objetivos_cualitativos['CodigoEmpleado'] = df_empleados['CodigoEmpleado']
cumplimiento_objetivos_cualitativos['TipoEmpleado'] = df_empleados['TipoEmpleado']
cumplimiento_objetivos_cualitativos['merge'] = 1
##
fechas = pd.DataFrame(df_venta_recaudo_real['Fecha'].drop_duplicates())
fechas['merge'] = 1
##
cumplimiento_objetivos_cualitativos = cumplimiento_objetivos_cualitativos.merge(
    fechas,
    on='merge',
    how='left'
)
cumplimiento_objetivos_cualitativos.drop(columns='merge', inplace=True)

cumplimiento_objetivos_cualitativos = pd.merge(
    left=cumplimiento_objetivos_cualitativos,
    right=df_objetivos_cualitativos,
    on=['CodigoEmpleado', 'Fecha'],
    how='left'
)

In [38]:
cumplimiento_objetivos_cualitativos[cumplimiento_objetivos_cualitativos["CodigoEmpleado"]=='79539822']

    CodigoEmpleado TipoEmpleado      Fecha  PorcentajeCumplimiento
684       79539822          AD2 2025-12-01                     1.2
685       79539822          AD2 2025-08-01                     NaN
686       79539822          AD2 2025-11-01                     NaN
687       79539822          AD2 2025-09-01                     NaN
688       79539822          AD2 2025-10-01                     NaN
689       79539822          AD2 2025-05-01                     NaN
690       79539822          AD2 2025-04-01                     NaN
691       79539822          AD2 2025-07-01                     NaN
692       79539822          AD2 2025-03-01                     NaN
693       79539822          AD2 2025-02-01                     NaN
694       79539822          AD2 2025-01-01                     NaN
695       79539822          AD2 2025-06-01                     NaN

In [39]:
cumplimiento_objetivos_cualitativos['Variable'] = 'ObjetivosCualitativos'
cumplimiento_objetivos_cualitativos['PorcentajeCumplimiento'].fillna(porcentaje_objetivos, inplace=True)

cumplimiento_objetivos_cualitativos_por_empleado = cumplimiento_objetivos_cualitativos.merge(
    df_empleados[['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo', 'FechaIngreso']].drop(columns=["FechaIngreso"]),
    how="left",
    on=["CodigoEmpleado", "TipoEmpleado"]
)

cumplimiento_objetivos_cualitativos_por_empleado['PorcentajeCumplimiento'] = cumplimiento_objetivos_cualitativos_por_empleado[['TipoEmpleado', 'AreaCalculo', 'Fecha', 'PorcentajeCumplimiento']].apply(
    lambda row: asignar_valor_porcentaje(row['TipoEmpleado'], row['AreaCalculo'], row['Fecha'], row['PorcentajeCumplimiento']),
    axis=1
)
cumplimiento_objetivos_cualitativos_por_empleado.rename(columns={'CodigoEmpleado': 'Contexto'}, inplace=True)
cumplimiento_objetivos_cualitativos_por_empleado.drop(columns=['TipoEmpleado', 'AreaCalculo'], inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4291272641.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_objetivos_cualitativos['PorcentajeCumplimiento'].fillna(porcentaje_objetivos, inplace=True)

In [40]:
cumplimiento_objetivos_cualitativos_por_empleado

     Contexto      Fecha  PorcentajeCumplimiento               Variable
0     5004523 2025-12-01                     1.0  ObjetivosCualitativos
1     5004523 2025-08-01                     0.8  ObjetivosCualitativos
2     5004523 2025-11-01                     0.8  ObjetivosCualitativos
3     5004523 2025-09-01                     0.8  ObjetivosCualitativos
4     5004523 2025-10-01                     0.8  ObjetivosCualitativos
...       ...        ...                     ...                    ...
1831  5016782 2025-07-01                     0.8  ObjetivosCualitativos
1832  5016782 2025-03-01                     0.8  ObjetivosCualitativos
1833  5016782 2025-02-01                     0.8  ObjetivosCualitativos
1834  5016782 2025-01-01                     0.8  ObjetivosCualitativos
1835  5016782 2025-06-01                     0.8  ObjetivosCualitativos

[1836 rows x 4 columns]

In [41]:
cumplimiento_objetivos_cualitativos_por_empleado[cumplimiento_objetivos_cualitativos_por_empleado["Contexto"]=='79539822']

     Contexto      Fecha  PorcentajeCumplimiento               Variable
684  79539822 2025-12-01                     1.2  ObjetivosCualitativos
685  79539822 2025-08-01                     0.9  ObjetivosCualitativos
686  79539822 2025-11-01                     0.9  ObjetivosCualitativos
687  79539822 2025-09-01                     0.9  ObjetivosCualitativos
688  79539822 2025-10-01                     0.9  ObjetivosCualitativos
689  79539822 2025-05-01                     0.9  ObjetivosCualitativos
690  79539822 2025-04-01                     0.9  ObjetivosCualitativos
691  79539822 2025-07-01                     0.9  ObjetivosCualitativos
692  79539822 2025-03-01                     0.9  ObjetivosCualitativos
693  79539822 2025-02-01                     0.9  ObjetivosCualitativos
694  79539822 2025-01-01                     0.9  ObjetivosCualitativos
695  79539822 2025-06-01                     0.9  ObjetivosCualitativos

In [42]:
# for x in [ '1111117']:
  #  _x = cumplimiento_objetivos_cualitativos[
  #  cumplimiento_objetivos_cualitativos['Contexto'] == x
  #  ]
  #  print(x)
  #  print(_x)

In [43]:
df_parrillas[df_parrillas['Variable'] == 'ObjetivosCualitativos'].merge(
    df_empleados
)

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,AreaCalculo
0,5004523,ObjetivosCualitativos,5004523,0.15,0,Objetivos cualitativos,NaN,VC,36952327,sobeyda.acosta@bbraun.com,SOBEYDA DEL SOCORRO,ACOSTA PORTILLO,2500000.0,2023-10-01,NaT,3
1,5016740,ObjetivosCualitativos,5016740,0.20,0,Objetivos cualitativos,NaN,MK,1030591908,NaN,CARLOS ANDRES,ALARCON LOPEZ,668000.0,2023-07-01,NaT,13
2,5004287,ObjetivosCualitativos,5004287,0.15,0,Objetivos cualitativos,NaN,VE,1073600365,diana.alvarez@bbraun.com,DIANA MARCELA,ALVAREZ SALCEDO,2714000.0,2013-05-17,NaT,4
3,5002697,ObjetivosCualitativos,5002697,0.15,0,Objetivos cualitativos,NaN,VE,30302849,amparo.arango@bbraun.com,AMPARO,ARANGO TOBON,3504000.0,1997-06-10,NaT,5
4,52792592,ObjetivosCualitativos,52792592,0.40,0,Objetivos cualitativos,NaN,AD2,52792592,francy.arevalo@bbraun.com,FRANCY YURLEDY,AREVALO,500000.0,2021-01-01,NaT,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,70038624,ObjetivosCualitativos,70038624,0.15,0,Objetivos cualitativos,NaN,VC,1038413972,dahiana.velez@bbraun.com,DAHIANA ANDREA,VELEZ CASTAÑO,2500000.0,2025-05-01,NaT,4
149,70051944,ObjetivosCualitativos,70051944,0.15,0,Objetivos cualitativos,NaN,VC,37396309,jennifer.vera@bbraun.com,JENNIFER STIBALITZ,VERA SANDOVAL,2500000.0,2025-11-01,NaT,3
150,5016700,ObjetivosCualitativos,5016700,0.20,0,Objetivos cualitativos,NaN,MK,80857971,NaN,JUAN JOSE,ZAMORA MORANTES,474000.0,2023-07-01,NaT,12
151,5041312,ObjetivosCualitativos,5041312,0.15,0,Objetivos cualitativos,NaN,VE,40411853,lina_shirley.zapata@bbraun.com,LINA SHIRLEY,ZAPATA GUTIERREZ,2805000.0,2021-09-01,NaT,5
152,5016782,ObjetivosCualitativos,5016782,0.15,0,Objetivos cualitativos,NaN,VC,1152685303,elizabeth.zapata@bbraun.com,Elizabeth,Zapata Serna,2500000.0,2022-11-01,NaT,4

In [44]:
df_parrillas[
    (df_parrillas['Variable'] == 'ObjetivosCualitativos') &
    (df_parrillas['CodigoEmpleado'] == '1111117')
]

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
1290,1111117,ObjetivosCualitativos,1111117,0.15,0,Objetivos cualitativos,NaN

In [45]:
# cumplimiento_objetivos_cualitativos[
#    cumplimiento_objetivos_cualitativos['Contexto'] == '1111117'
# ]

## 1.1 KpiCalidad

In [46]:
cumplimiento_kpi_calidad = pd.DataFrame()
porcentaje_kpi_calidad = 0.94

cumplimiento_kpi_calidad['CodigoEmpleado'] = df_empleados['CodigoEmpleado']
cumplimiento_kpi_calidad['TipoEmpleado'] = df_empleados['TipoEmpleado']
cumplimiento_kpi_calidad['merge'] = 1
##
fechas = pd.DataFrame(df_venta_recaudo_real['Fecha'].drop_duplicates())
fechas['merge'] = 1
##
cumplimiento_kpi_calidad = cumplimiento_kpi_calidad.merge(
    fechas,
    on='merge',
    how='left'
)
cumplimiento_kpi_calidad.drop(columns='merge', inplace=True)

cumplimiento_kpi_calidad = pd.merge(
    left=cumplimiento_kpi_calidad,
    right=df_kpi_calidad,
    on=['CodigoEmpleado', 'Fecha'],
    how='left'
)
cumplimiento_kpi_calidad

     CodigoEmpleado TipoEmpleado      Fecha  PorcentajeCumplimiento
0           5004523           VC 2025-12-01                     NaN
1           5004523           VC 2025-08-01                     NaN
2           5004523           VC 2025-11-01                     NaN
3           5004523           VC 2025-09-01                     NaN
4           5004523           VC 2025-10-01                     NaN
...             ...          ...        ...                     ...
1831        5016782           VC 2025-07-01                     NaN
1832        5016782           VC 2025-03-01                     NaN
1833        5016782           VC 2025-02-01                     NaN
1834        5016782           VC 2025-01-01                     NaN
1835        5016782           VC 2025-06-01                     NaN

[1836 rows x 4 columns]

In [47]:
cumplimiento_kpi_calidad['Variable'] = 'KpiCalidad'
cumplimiento_kpi_calidad['PorcentajeCumplimiento'].fillna(porcentaje_kpi_calidad, inplace=True)
cumplimiento_kpi_calidad.rename(columns={'CodigoEmpleado': 'Contexto'}, inplace=True)
cumplimiento_kpi_calidad.drop(columns=['TipoEmpleado'], inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\896556264.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_kpi_calidad['PorcentajeCumplimiento'].fillna(porcentaje_kpi_calidad, inplace=True)

## 2. Objetivos de recaudo por zona (VentaCobradaZonaBraunCrossDivisional)
### TODO: Ahora el empleado tiene varias zonas

In [48]:
cumplimiento_recaudo_por_zona = df_recaudo_por_zona.copy()

cumplimiento_recaudo_por_zona['Real'] = cumplimiento_recaudo_por_zona.groupby(['Zona'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_zona['Presupuesto'] = cumplimiento_recaudo_por_zona.groupby(['Zona'])['Presupuesto'].transform(pd.Series.cumsum)

cumplimiento_recaudo_por_zona['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_zona['Real'] / cumplimiento_recaudo_por_zona['Presupuesto']
cumplimiento_recaudo_por_zona['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_zona['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_recaudo_por_zona['Variable'] = 'VentaCobradaZonaBraunCrossDivisional'
cumplimiento_recaudo_por_zona.rename(columns={'Zona': 'Contexto'}, inplace=True)

cumplimiento_recaudo_por_zona = cumplimiento_recaudo_por_zona[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_por_zona.head()

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 3. Objetivos de venta individuales (VentaFacturadaZonaCargoIndividual y VentaFacturadaZonaCargoIndividualSub)

In [49]:
# venta real con información
venta_recaudo_real_info = df_venta_recaudo_real.merge(
    df_empleados[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'FechaIngreso']],
    on='CodigoEmpleado',
    how='left'
).merge(
    area_calculo_sba_completo,
    on=['Division', 'GrupoProducto', 'SBA', 'TipoEmpleado', 'AreaCalculo'],
    how='left'
)

# venta presupuesto con información
venta_recaudo_presupuesto_info = df_venta_recaudo_presupuesto.merge(
    df_empleados[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'FechaIngreso']],
    on='CodigoEmpleado',
    how='left'
).merge(
    area_calculo_sba_completo,
    on=['Division', 'GrupoProducto', 'SBA', 'TipoEmpleado', 'AreaCalculo'],
    how='left'
)

In [50]:
_excepciones_venta_facturada = [
    # {
    #     'CodigoEmpleado': '5003527',
    #     'AreaCalculo': 7,
    #     'Consecutivo': 4,
    #     'FechaInicio': '2021-02-01',
    #     'FechaFin': '2021-06-01'
    # }
]

# venta real por empleado por area de calculo por fecha acumulada
venta_recaudo_real_empleado_sub = venta_recaudo_real_info[venta_recaudo_real_info['Fecha'] >= venta_recaudo_real_info['FechaIngreso']]

for excepcion in _excepciones_venta_facturada:
    venta_recaudo_real_empleado_sub = venta_recaudo_real_empleado_sub[
        (venta_recaudo_real_empleado_sub['CodigoEmpleado'] != excepcion['CodigoEmpleado']) |
        (venta_recaudo_real_empleado_sub['AreaCalculo'] != excepcion['AreaCalculo']) |
        (venta_recaudo_real_empleado_sub['Consecutivo'] != excepcion['Consecutivo']) |
        (venta_recaudo_real_empleado_sub['Fecha'] < excepcion['FechaInicio']) |
        (venta_recaudo_real_empleado_sub['Fecha'] > excepcion['FechaFin'])
    ]

venta_recaudo_real_empleado_sub_1 = venta_recaudo_real_empleado_sub.copy()[
    (venta_recaudo_real_empleado_sub['CodigoEmpleado'] == '5004563') &
    (venta_recaudo_real_empleado_sub['SBA'] == '84')
]
venta_recaudo_real_empleado_sub_1['CodigoEmpleado'] = '5005371'
venta_recaudo_real_empleado_sub_1['AreaCalculo'] = 14
venta_recaudo_real_empleado_sub_1['Consecutivo'] = 2

venta_recaudo_real_empleado_sub_2 = venta_recaudo_real_empleado_sub.copy()[
    (venta_recaudo_real_empleado_sub['CodigoEmpleado'] == '5004563') &
    (venta_recaudo_real_empleado_sub['SBA'] == '84')
]
venta_recaudo_real_empleado_sub_2['CodigoEmpleado'] = '5039251'
venta_recaudo_real_empleado_sub_2['AreaCalculo'] = 15
venta_recaudo_real_empleado_sub_2['Consecutivo'] = 2

venta_recaudo_real_empleado_sub_3 = venta_recaudo_real_empleado_sub.copy()[
    (venta_recaudo_real_empleado_sub['CodigoEmpleado'] == '5018231') & 
    (venta_recaudo_real_empleado_sub['Fecha'] >= '2021-08-01')
]
venta_recaudo_real_empleado_sub_3['CodigoEmpleado'] = '1128448666'
venta_recaudo_real_empleado_sub_3['AreaCalculo'] = 9


venta_recaudo_real_empleado_sub = pd.concat([
    venta_recaudo_real_empleado_sub,
    venta_recaudo_real_empleado_sub_1,
    venta_recaudo_real_empleado_sub_2,
    venta_recaudo_real_empleado_sub_3
])
venta_recaudo_real_empleado_sub = venta_recaudo_real_empleado_sub.groupby(['CodigoEmpleado', 'AreaCalculo',
                                                                           'Consecutivo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_recaudo_real_empleado_sub['Real'] = venta_recaudo_real_empleado_sub['Venta']
venta_recaudo_real_empleado_sub.drop(columns=['Venta'], inplace=True)
venta_recaudo_real_empleado = venta_recaudo_real_empleado_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Fecha'], as_index=False).agg({'Real': 'sum'})

# venta presupuesto por empleado por area de calculo por fecha acumulada
venta_recaudo_presupuesto_empleado_sub = venta_recaudo_presupuesto_info[venta_recaudo_presupuesto_info['Fecha'] >= venta_recaudo_presupuesto_info['FechaIngreso']]

for excepcion in _excepciones_venta_facturada:
    venta_recaudo_presupuesto_empleado_sub = venta_recaudo_presupuesto_empleado_sub[
        (venta_recaudo_presupuesto_empleado_sub['CodigoEmpleado'] != excepcion['CodigoEmpleado']) |
        (venta_recaudo_presupuesto_empleado_sub['AreaCalculo'] != excepcion['AreaCalculo']) |
        (venta_recaudo_presupuesto_empleado_sub['Consecutivo'] != excepcion['Consecutivo']) |
        (venta_recaudo_presupuesto_empleado_sub['Fecha'] < excepcion['FechaInicio']) |
        (venta_recaudo_presupuesto_empleado_sub['Fecha'] > excepcion['FechaFin'])
    ]

venta_recaudo_presupuesto_empleado_sub_1 = venta_recaudo_presupuesto_empleado_sub.copy()[
    (venta_recaudo_presupuesto_empleado_sub['CodigoEmpleado'] == '5004563') &
    (venta_recaudo_presupuesto_empleado_sub['SBA'] == '84')
]
venta_recaudo_presupuesto_empleado_sub_1['CodigoEmpleado'] = '5005371'
venta_recaudo_presupuesto_empleado_sub_1['AreaCalculo'] = 14
venta_recaudo_presupuesto_empleado_sub_1['Consecutivo'] = 2

venta_recaudo_presupuesto_empleado_sub_2 = venta_recaudo_presupuesto_empleado_sub.copy()[
    (venta_recaudo_presupuesto_empleado_sub['CodigoEmpleado'] == '5004563') &
    (venta_recaudo_presupuesto_empleado_sub['SBA'] == '84')
]
venta_recaudo_presupuesto_empleado_sub_2['CodigoEmpleado'] = '5039251'
venta_recaudo_presupuesto_empleado_sub_2['AreaCalculo'] = 15
venta_recaudo_presupuesto_empleado_sub_2['Consecutivo'] = 2

venta_recaudo_presupuesto_empleado_sub_3 = venta_recaudo_presupuesto_empleado_sub.copy()[
    (venta_recaudo_presupuesto_empleado_sub['CodigoEmpleado'] == '5018231') & 
    (venta_recaudo_presupuesto_empleado_sub['Fecha'] >= '2021-08-01')
]
venta_recaudo_presupuesto_empleado_sub_3['CodigoEmpleado'] = '1128448666'
venta_recaudo_presupuesto_empleado_sub_3['AreaCalculo'] = 9

venta_recaudo_presupuesto_empleado_sub = pd.concat([
    venta_recaudo_presupuesto_empleado_sub,
    venta_recaudo_presupuesto_empleado_sub_1,
    venta_recaudo_presupuesto_empleado_sub_2,
    venta_recaudo_presupuesto_empleado_sub_3
])
venta_recaudo_presupuesto_empleado_sub = venta_recaudo_presupuesto_empleado_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_recaudo_presupuesto_empleado_sub['Presupuesto'] = venta_recaudo_presupuesto_empleado_sub['Venta']
venta_recaudo_presupuesto_empleado_sub.drop(columns=['Venta'], inplace=True)
venta_recaudo_presupuesto_empleado = venta_recaudo_presupuesto_empleado_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Fecha'], as_index=False).agg({'Presupuesto': 'sum'})


## VentaFacturadaZonaCargoIndividual
cumplimiento_venta_individual = pd.merge(
    left=venta_recaudo_presupuesto_empleado,
    right=venta_recaudo_real_empleado,
    on=['CodigoEmpleado', 'AreaCalculo', 'Fecha'],
    how='outer'
)
cumplimiento_venta_individual['Presupuesto'].fillna(0.0, inplace=True)
cumplimiento_venta_individual['Real'].fillna(0.0, inplace=True)
cumplimiento_venta_individual['Presupuesto'] = cumplimiento_venta_individual.groupby(['CodigoEmpleado', 'AreaCalculo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_venta_individual['Real'] = cumplimiento_venta_individual.groupby(['CodigoEmpleado', 'AreaCalculo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_venta_individual['PorcentajeCumplimiento'] = cumplimiento_venta_individual['Real'] / cumplimiento_venta_individual['Presupuesto']
cumplimiento_venta_individual['PorcentajeCumplimiento'] = cumplimiento_venta_individual['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_venta_individual.rename(columns={'CodigoEmpleado': 'Contexto'}, inplace=True)
cumplimiento_venta_individual['Variable'] = 'VentaFacturadaZonaCargoIndividual'
cumplimiento_venta_individual = cumplimiento_venta_individual[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_venta_individual.head()

## VentaFacturadaZonaCargoIndividualSub
cumplimiento_venta_individual_sub = pd.merge(
    left=venta_recaudo_presupuesto_empleado_sub,
    right=venta_recaudo_real_empleado_sub,
    on=['CodigoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    how='outer'
)
cumplimiento_venta_individual_sub['Real'].fillna(0.0, inplace=True)
cumplimiento_venta_individual_sub['Presupuesto'].fillna(0.0, inplace=True)

cumplimiento_venta_individual_sub['Presupuesto'] = cumplimiento_venta_individual_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_venta_individual_sub['Real'] = cumplimiento_venta_individual_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_venta_individual_sub['PorcentajeCumplimiento'] = cumplimiento_venta_individual_sub['Real'] / cumplimiento_venta_individual_sub['Presupuesto']
cumplimiento_venta_individual_sub['PorcentajeCumplimiento'] = cumplimiento_venta_individual_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_venta_individual_sub['PorcentajeCumplimiento'].fillna(0.0, inplace=True)
cumplimiento_venta_individual_sub['Consecutivo'] = cumplimiento_venta_individual_sub['Consecutivo'].astype(int).astype('str')
cumplimiento_venta_individual_sub['Contexto'] = cumplimiento_venta_individual_sub['CodigoEmpleado'].str.cat(cumplimiento_venta_individual_sub['Consecutivo'],sep="_")
cumplimiento_venta_individual_sub['Variable'] = 'VentaFacturadaZonaCargoIndividualSub'

cumplimiento_venta_individual_sub = cumplimiento_venta_individual_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_venta_individual_sub.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4281463892.py:113: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_individual['Presupuesto'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4281463892.py:114: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_individual['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4281463892.py:132: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_individual_sub['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4281463892.py:133: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_individual_sub['Presupuesto'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4281463892.py:139: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_individual_sub['PorcentajeCumplimiento'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002699_2,VentaFacturadaZonaCargoIndividualSub,2025-03-01,0.0,0.0,0.0
1,5002699_2,VentaFacturadaZonaCargoIndividualSub,2025-04-01,46758900.0,0.0,inf
2,5002699_2,VentaFacturadaZonaCargoIndividualSub,2025-05-01,45386300.0,0.0,inf
3,5002699_2,VentaFacturadaZonaCargoIndividualSub,2025-07-01,47740800.0,0.0,inf
4,5002699_2,VentaFacturadaZonaCargoIndividualSub,2025-09-01,50144600.0,0.0,inf

## 4. Objetivos de recaudo individuales (VentasCobradaZonaCargoIndividual y VentasCobradaZonaCargoIndividualSub)

In [51]:
_excepciones_venta_recaudo = [
    # {
    #     'CodigoEmpleado': '5003527',
    #     'AreaCalculo': 7,
    #     'Consecutivo': 4,
    #     'FechaInicio': '2021-02-01',
    #     'FechaFin': '2021-06-01'
    # }
]

# recaudo real por empleado por area de calculo y consecutivo por fecha acumulada
venta_recaudo_real_empleado_sub = venta_recaudo_real_info[venta_recaudo_real_info['Fecha'] >= venta_recaudo_real_info['FechaIngreso']]

for excepcion in _excepciones_venta_recaudo:
    venta_recaudo_real_empleado_sub = venta_recaudo_real_empleado_sub[
        (venta_recaudo_real_empleado_sub['CodigoEmpleado'] != excepcion['CodigoEmpleado']) |
        (venta_recaudo_real_empleado_sub['AreaCalculo'] != excepcion['AreaCalculo']) |
        (venta_recaudo_real_empleado_sub['Consecutivo'] != excepcion['Consecutivo']) |
        (venta_recaudo_real_empleado_sub['Fecha'] < excepcion['FechaInicio']) |
        (venta_recaudo_real_empleado_sub['Fecha'] > excepcion['FechaFin'])
    ]

venta_recaudo_real_empleado_sub_1 = venta_recaudo_real_empleado_sub.copy()[
    (venta_recaudo_real_empleado_sub['CodigoEmpleado'] == '5004563') &
    (venta_recaudo_real_empleado_sub['SBA'] == '84')
]
venta_recaudo_real_empleado_sub_1['CodigoEmpleado'] = '5005371'
venta_recaudo_real_empleado_sub_1['AreaCalculo'] = 14
venta_recaudo_real_empleado_sub_1['Consecutivo'] = 2

venta_recaudo_real_empleado_sub_2 = venta_recaudo_real_empleado_sub.copy()[
    (venta_recaudo_real_empleado_sub['CodigoEmpleado'] == '5004563') &
    (venta_recaudo_real_empleado_sub['SBA'] == '84')
]
venta_recaudo_real_empleado_sub_2['CodigoEmpleado'] = '5039251'
venta_recaudo_real_empleado_sub_2['AreaCalculo'] = 15
venta_recaudo_real_empleado_sub_2['Consecutivo'] = 2

venta_recaudo_real_empleado_sub_3 = venta_recaudo_real_empleado_sub.copy()[
    (venta_recaudo_real_empleado_sub['CodigoEmpleado'] == '5018231') & 
    (venta_recaudo_real_empleado_sub['Fecha'] >= '2021-08-01')
]
venta_recaudo_real_empleado_sub_3['CodigoEmpleado'] = '1128448666'
venta_recaudo_real_empleado_sub_3['AreaCalculo'] = 9

venta_recaudo_real_empleado_sub = pd.concat([
    venta_recaudo_real_empleado_sub,
    venta_recaudo_real_empleado_sub_1,
    venta_recaudo_real_empleado_sub_2,
    venta_recaudo_real_empleado_sub_3
])

venta_recaudo_real_empleado_sub = venta_recaudo_real_empleado_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_real_empleado_sub['Real'] = venta_recaudo_real_empleado_sub['Recaudo']
venta_recaudo_real_empleado_sub.drop(columns=['Recaudo'], inplace=True)
venta_recaudo_real_empleado = venta_recaudo_real_empleado_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Fecha'], as_index=False).agg({'Real': 'sum'})

# recaudo presupuesto por empleado por area de calculo y consecutivo por fecha acumulada
venta_recaudo_presupuesto_empleado_sub = venta_recaudo_presupuesto_info[venta_recaudo_presupuesto_info['Fecha'] >= venta_recaudo_presupuesto_info['FechaIngreso']]

for excepcion in _excepciones_venta_recaudo:
    venta_recaudo_presupuesto_empleado_sub = venta_recaudo_presupuesto_empleado_sub[
        (venta_recaudo_presupuesto_empleado_sub['CodigoEmpleado'] != excepcion['CodigoEmpleado']) |
        (venta_recaudo_presupuesto_empleado_sub['AreaCalculo'] != excepcion['AreaCalculo']) |
        (venta_recaudo_presupuesto_empleado_sub['Consecutivo'] != excepcion['Consecutivo']) |
        (venta_recaudo_presupuesto_empleado_sub['Fecha'] < excepcion['FechaInicio']) |
        (venta_recaudo_presupuesto_empleado_sub['Fecha'] > excepcion['FechaFin'])
    ]

venta_recaudo_presupuesto_empleado_sub_1 = venta_recaudo_presupuesto_empleado_sub.copy()[
    (venta_recaudo_presupuesto_empleado_sub['CodigoEmpleado'] == '5004563') &
    (venta_recaudo_presupuesto_empleado_sub['SBA'] == '84')
]
venta_recaudo_presupuesto_empleado_sub_1['CodigoEmpleado'] = '5005371'
venta_recaudo_presupuesto_empleado_sub_1['AreaCalculo'] = 14
venta_recaudo_presupuesto_empleado_sub_1['Consecutivo'] = 2

venta_recaudo_presupuesto_empleado_sub_2 = venta_recaudo_presupuesto_empleado_sub.copy()[
    (venta_recaudo_presupuesto_empleado_sub['CodigoEmpleado'] == '5004563') &
    (venta_recaudo_presupuesto_empleado_sub['SBA'] == '84')
]
venta_recaudo_presupuesto_empleado_sub_2['CodigoEmpleado'] = '5039251'
venta_recaudo_presupuesto_empleado_sub_2['AreaCalculo'] = 15
venta_recaudo_presupuesto_empleado_sub_2['Consecutivo'] = 2

venta_recaudo_presupuesto_empleado_sub_3 = venta_recaudo_presupuesto_empleado_sub.copy()[
    (venta_recaudo_presupuesto_empleado_sub['CodigoEmpleado'] == '5018231') & 
    (venta_recaudo_presupuesto_empleado_sub['Fecha'] >= '2021-08-01')
]
venta_recaudo_presupuesto_empleado_sub_3['CodigoEmpleado'] = '1128448666'
venta_recaudo_presupuesto_empleado_sub_3['AreaCalculo'] = 9

venta_recaudo_presupuesto_empleado_sub = pd.concat([
    venta_recaudo_presupuesto_empleado_sub,
    venta_recaudo_presupuesto_empleado_sub_1,
    venta_recaudo_presupuesto_empleado_sub_2,
    venta_recaudo_presupuesto_empleado_sub_3
])

venta_recaudo_presupuesto_empleado_sub = venta_recaudo_presupuesto_empleado_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_presupuesto_empleado_sub['Presupuesto'] = venta_recaudo_presupuesto_empleado_sub['Recaudo']
venta_recaudo_presupuesto_empleado_sub.drop(columns=['Recaudo'], inplace=True)
venta_recaudo_presupuesto_empleado = venta_recaudo_presupuesto_empleado_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Fecha'], as_index=False).agg({'Presupuesto': 'sum'})

## VentasCobradaZonaCargoIndividual
cumplimiento_recaudo_individual = pd.merge(
    left=venta_recaudo_presupuesto_empleado,
    right=venta_recaudo_real_empleado,
    on=['CodigoEmpleado', 'AreaCalculo', 'Fecha'],
    how='outer'
)
cumplimiento_recaudo_individual['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_individual['Presupuesto'] = cumplimiento_recaudo_individual.groupby(['CodigoEmpleado', 'AreaCalculo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_individual['Real'] = cumplimiento_recaudo_individual.groupby(['CodigoEmpleado', 'AreaCalculo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_individual['PorcentajeCumplimiento'] = cumplimiento_recaudo_individual['Real'] / cumplimiento_recaudo_individual['Presupuesto']
cumplimiento_recaudo_individual['PorcentajeCumplimiento'] = cumplimiento_recaudo_individual['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_individual.rename(columns={'CodigoEmpleado': 'Contexto'}, inplace=True)
cumplimiento_recaudo_individual['Variable'] = 'VentasCobradaZonaCargoIndividual'
cumplimiento_recaudo_individual = cumplimiento_recaudo_individual[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_individual.head()


## VentasCobradaZonaCargoIndividualSub
cumplimiento_recaudo_individual_sub = pd.merge(
    left=venta_recaudo_presupuesto_empleado_sub,
    right=venta_recaudo_real_empleado_sub,
    on=['CodigoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    how='outer'
)
cumplimiento_recaudo_individual_sub['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_individual_sub['Presupuesto'].fillna(0.0, inplace=True)

_excepciones_recaudo_sub = []

for excepcion in _excepciones_recaudo_sub:
    cumplimiento_recaudo_individual_sub['Presupuesto'] = np.where(
        (
            (cumplimiento_recaudo_individual_sub['CodigoEmpleado'].isin(excepcion['Codigos'])) &
            (cumplimiento_recaudo_individual_sub['Consecutivo'] == excepcion['Consecutivo']) &
            # (cumplimiento_recaudo_individual_sub['Variable'] == 'VentasCobradaZonaCargoIndividualSub') &
            (cumplimiento_recaudo_individual_sub['Fecha'] >= excepcion['FechaInicial']) &
            (cumplimiento_recaudo_individual_sub['Fecha'] <= excepcion['FechaFinal'])
        ),
        excepcion['ValorPresupuesto'],
        cumplimiento_recaudo_individual_sub['Presupuesto']
    )
    cumplimiento_recaudo_individual_sub['Real'] = np.where(
        (
            (cumplimiento_recaudo_individual_sub['CodigoEmpleado'].isin(excepcion['Codigos'])) &
            (cumplimiento_recaudo_individual_sub['Consecutivo'] == excepcion['Consecutivo']) &
            # (cumplimiento_recaudo_individual_sub['Variable'] == 'VentasCobradaZonaCargoIndividualSub') &
            (cumplimiento_recaudo_individual_sub['Fecha'] >= excepcion['FechaInicial']) &
            (cumplimiento_recaudo_individual_sub['Fecha'] <= excepcion['FechaFinal'])
        ),
        excepcion['ValorReal'],
        cumplimiento_recaudo_individual_sub['Real']
    )


cumplimiento_recaudo_individual_sub['Presupuesto'] = cumplimiento_recaudo_individual_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_individual_sub['Real'] = cumplimiento_recaudo_individual_sub.groupby(['CodigoEmpleado', 'AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_individual_sub['PorcentajeCumplimiento'] = cumplimiento_recaudo_individual_sub['Real'] / cumplimiento_recaudo_individual_sub['Presupuesto']
cumplimiento_recaudo_individual_sub['PorcentajeCumplimiento'] = cumplimiento_recaudo_individual_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_individual_sub['PorcentajeCumplimiento'].fillna(0.0, inplace=True)
cumplimiento_recaudo_individual_sub['Consecutivo'] = cumplimiento_recaudo_individual_sub['Consecutivo'].astype(int).astype('str')
cumplimiento_recaudo_individual_sub['Contexto'] = cumplimiento_recaudo_individual_sub['CodigoEmpleado'].str.cat(cumplimiento_recaudo_individual_sub['Consecutivo'],sep="_")
cumplimiento_recaudo_individual_sub['Variable'] = 'VentasCobradaZonaCargoIndividualSub'
cumplimiento_recaudo_individual_sub = cumplimiento_recaudo_individual_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_individual_sub.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1929322237.py:112: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_individual['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1929322237.py:131: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_individual_sub['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1929322237.py:132: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_individual_sub['Presupuesto'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1929322237.py:165: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_individual_sub['PorcentajeCumplimiento'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002699_2,VentasCobradaZonaCargoIndividualSub,2025-03-01,2689800.0,0.0,inf
1,5002699_2,VentasCobradaZonaCargoIndividualSub,2025-04-01,4368600.0,0.0,inf
2,5002699_2,VentasCobradaZonaCargoIndividualSub,2025-05-01,48342200.0,0.0,inf
3,5002699_2,VentasCobradaZonaCargoIndividualSub,2025-07-01,50696700.0,0.0,inf
4,5002699_2,VentasCobradaZonaCargoIndividualSub,2025-09-01,50696700.0,0.0,inf

## 5. Objetivos de venta por área de cálculo (VentaFacturadaPorAreaCalculo y VentaFacturadaPorAreaCalculoSub)

In [52]:
area_calculo_sba_completo_ve7 = area_calculo_sba_completo[
    (area_calculo_sba_completo['TipoEmpleado'] == 'VE')&
    (area_calculo_sba_completo['AreaCalculo'] == 7)
][['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'GrupoProducto', 'SBA']]

In [53]:
resultados_venta_area_calculo_real = pd.merge(
    left=venta_recaudo_real_info[[
        'GrupoProducto', 
        'SBA', 
        'Fecha',
        'Venta'
    ]],
    right=area_calculo_sba_completo_ve7,
    on=['GrupoProducto', 'SBA']
)
resultados_venta_area_calculo_real_sub = resultados_venta_area_calculo_real.groupby(
    ['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    as_index=False
).agg({'Venta': 'sum'})
resultados_venta_area_calculo_real = resultados_venta_area_calculo_real.groupby(
    ['TipoEmpleado', 'AreaCalculo', 'Fecha'],
    as_index=False
).agg({'Venta': 'sum'})


resultados_venta_area_calculo_presupuesto = pd.merge(
    left=venta_recaudo_presupuesto_info[[
        'GrupoProducto', 
        'SBA', 
        'Fecha',
        'Venta'
    ]],
    right=area_calculo_sba_completo_ve7,
    on=['GrupoProducto', 'SBA']
)
resultados_venta_area_calculo_presupuesto_sub = resultados_venta_area_calculo_presupuesto.groupby(
    ['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    as_index=False
).agg({'Venta': 'sum'})
resultados_venta_area_calculo_presupuesto = resultados_venta_area_calculo_presupuesto.groupby(
    ['TipoEmpleado', 'AreaCalculo', 'Fecha'],
    as_index=False
).agg({'Venta': 'sum'})

## VentaFacturadaPorAreaCalculo
cumplimiento_venta_por_area_calculo = pd.merge(
    left=resultados_venta_area_calculo_presupuesto.rename(columns={'Venta': 'Presupuesto'}),
    right=resultados_venta_area_calculo_real.rename(columns={'Venta': 'Real'}),
    on=['TipoEmpleado', 'AreaCalculo', 'Fecha'],
    how='left'
)
cumplimiento_venta_por_area_calculo['Real'].fillna(0.0, inplace=True)

cumplimiento_venta_por_area_calculo['Variable'] = 'VentaFacturadaPorAreaCalculo'
cumplimiento_venta_por_area_calculo['Contexto'] = cumplimiento_venta_por_area_calculo['TipoEmpleado'].str.cat(cumplimiento_venta_por_area_calculo['AreaCalculo'].astype('str'),sep="_")
cumplimiento_venta_por_area_calculo['Real'] = cumplimiento_venta_por_area_calculo.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
cumplimiento_venta_por_area_calculo['Presupuesto'] = cumplimiento_venta_por_area_calculo.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_venta_por_area_calculo['PorcentajeCumplimiento'] = cumplimiento_venta_por_area_calculo['Real'] / cumplimiento_venta_por_area_calculo['Presupuesto']

cumplimiento_venta_por_area_calculo = cumplimiento_venta_por_area_calculo[[
    'Contexto',
    'Variable',
    'Fecha',
    'Real',
    'Presupuesto',
    'PorcentajeCumplimiento'
]]

cumplimiento_venta_por_area_calculo.head()

## VentaFacturadaPorAreaCalculoSub
cumplimiento_venta_por_area_calculo_sub = pd.merge(
    left=resultados_venta_area_calculo_presupuesto_sub.rename(columns={'Venta': 'Presupuesto'}),
    right=resultados_venta_area_calculo_real_sub.rename(columns={'Venta': 'Real'}),
    on=['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)
cumplimiento_venta_por_area_calculo_sub['Real'].fillna(0.0, inplace=True)


cumplimiento_venta_por_area_calculo_sub['Variable'] = 'VentaFacturadaPorAreaCalculoSub'
cumplimiento_venta_por_area_calculo_sub['Contexto'] = cumplimiento_venta_por_area_calculo_sub['TipoEmpleado'].str.cat(cumplimiento_venta_por_area_calculo_sub['AreaCalculo'].astype('str'),sep="_")
cumplimiento_venta_por_area_calculo_sub['Contexto'] = cumplimiento_venta_por_area_calculo_sub['Contexto'].str.cat(cumplimiento_venta_por_area_calculo_sub['Consecutivo'].astype('str'), sep='_')
cumplimiento_venta_por_area_calculo_sub['Real'] = cumplimiento_venta_por_area_calculo_sub.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
cumplimiento_venta_por_area_calculo_sub['Presupuesto'] = cumplimiento_venta_por_area_calculo_sub.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_venta_por_area_calculo_sub['PorcentajeCumplimiento'] = cumplimiento_venta_por_area_calculo_sub['Real'] / cumplimiento_venta_por_area_calculo_sub['Presupuesto']

cumplimiento_venta_por_area_calculo_sub = cumplimiento_venta_por_area_calculo_sub[[
    'Contexto',
    'Variable',
    'Fecha',
    'Real',
    'Presupuesto',
    'PorcentajeCumplimiento'
]]

cumplimiento_venta_por_area_calculo_sub.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3713195180.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_por_area_calculo['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3713195180.py:73: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_por_area_calculo_sub['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,VE_7_1,VentaFacturadaPorAreaCalculoSub,2025-01-01,-313779.00,6450480.0,-0.048644
1,VE_7_1,VentaFacturadaPorAreaCalculoSub,2025-02-01,2848912.73,17201280.0,0.165622
2,VE_7_1,VentaFacturadaPorAreaCalculoSub,2025-03-01,9169746.73,32252400.0,0.284312
3,VE_7_1,VentaFacturadaPorAreaCalculoSub,2025-04-01,13092348.72,49453680.0,0.264740
4,VE_7_1,VentaFacturadaPorAreaCalculoSub,2025-05-01,18061350.72,68805120.0,0.262500

## 6. Objetivos de recaudo por área de cálculo (VentasCobradaPorAreaCalculo y VentasCobradaPorAreaCalculoSub)

In [54]:
resultados_recaudo_area_calculo_real = pd.merge(
    left=venta_recaudo_real_info[[
        'GrupoProducto', 
        'SBA', 
        'Fecha',
        'Recaudo'
    ]],
    right=area_calculo_sba_completo_ve7,
    on=['GrupoProducto', 'SBA']
)
resultados_recaudo_area_calculo_real_sub = resultados_recaudo_area_calculo_real.groupby(
    ['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    as_index=False
).agg({'Recaudo': 'sum'})
resultados_recaudo_area_calculo_real = resultados_recaudo_area_calculo_real.groupby(
    ['TipoEmpleado', 'AreaCalculo', 'Fecha'],
    as_index=False
).agg({'Recaudo': 'sum'})


resultados_recaudo_area_calculo_presupuesto = pd.merge(
    left=venta_recaudo_presupuesto_info[[
        'GrupoProducto', 
        'SBA', 
        'Fecha',
        'Recaudo'
    ]],
    right=area_calculo_sba_completo_ve7,
    on=['GrupoProducto', 'SBA']
)
resultados_recaudo_area_calculo_presupuesto_sub = resultados_recaudo_area_calculo_presupuesto.groupby(
    ['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    as_index=False
).agg({'Recaudo': 'sum'})
resultados_recaudo_area_calculo_presupuesto = resultados_recaudo_area_calculo_presupuesto.groupby(
    ['TipoEmpleado', 'AreaCalculo', 'Fecha'],
    as_index=False
).agg({'Recaudo': 'sum'})

## VentasCobradaPorAreaCalculo
cumplimiento_recaudo_por_area_calculo = pd.merge(
    left=resultados_recaudo_area_calculo_presupuesto.rename(columns={'Recaudo': 'Presupuesto'}),
    right=resultados_recaudo_area_calculo_real.rename(columns={'Recaudo': 'Real'}),
    on=['TipoEmpleado', 'AreaCalculo', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_area_calculo['Real'].fillna(0.0, inplace=True)

cumplimiento_recaudo_por_area_calculo['Variable'] = 'VentasCobradaPorAreaCalculo'
cumplimiento_recaudo_por_area_calculo['Contexto'] = cumplimiento_recaudo_por_area_calculo['TipoEmpleado'].str.cat(cumplimiento_recaudo_por_area_calculo['AreaCalculo'].astype('str'),sep="_")
cumplimiento_recaudo_por_area_calculo['Real'] = cumplimiento_recaudo_por_area_calculo.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_area_calculo['Presupuesto'] = cumplimiento_recaudo_por_area_calculo.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_area_calculo['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_area_calculo['Real'] / cumplimiento_venta_por_area_calculo['Presupuesto']

cumplimiento_recaudo_por_area_calculo = cumplimiento_recaudo_por_area_calculo[[
    'Contexto',
    'Variable',
    'Fecha',
    'Real',
    'Presupuesto',
    'PorcentajeCumplimiento'
]]

## VentasCobradaPorAreaCalculoSub
cumplimiento_recaudo_por_area_calculo_sub = pd.merge(
    left=resultados_recaudo_area_calculo_presupuesto_sub.rename(columns={'Recaudo': 'Presupuesto'}),
    right=resultados_recaudo_area_calculo_real_sub.rename(columns={'Recaudo': 'Real'}),
    on=['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_area_calculo_sub['Real'].fillna(0.0, inplace=True)

cumplimiento_recaudo_por_area_calculo_sub['Variable'] = 'VentasCobradaPorAreaCalculoSub'
cumplimiento_recaudo_por_area_calculo_sub['Contexto'] = cumplimiento_recaudo_por_area_calculo_sub['TipoEmpleado'].str.cat(cumplimiento_recaudo_por_area_calculo_sub['AreaCalculo'].astype('str'),sep="_")
cumplimiento_recaudo_por_area_calculo_sub['Contexto'] = cumplimiento_recaudo_por_area_calculo_sub['Contexto'].str.cat(cumplimiento_recaudo_por_area_calculo_sub['Consecutivo'].astype('str'), sep='_')
cumplimiento_recaudo_por_area_calculo_sub['Real'] = cumplimiento_recaudo_por_area_calculo_sub.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_area_calculo_sub['Presupuesto'] = cumplimiento_recaudo_por_area_calculo_sub.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_area_calculo_sub['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_area_calculo_sub['Real'] / cumplimiento_recaudo_por_area_calculo_sub['Presupuesto']

cumplimiento_recaudo_por_area_calculo_sub = cumplimiento_recaudo_por_area_calculo_sub[[
    'Contexto',
    'Variable',
    'Fecha',
    'Real',
    'Presupuesto',
    'PorcentajeCumplimiento'
]]

cumplimiento_recaudo_por_area_calculo_sub.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2646839954.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_area_calculo['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2646839954.py:71: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_area_calculo_sub['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,VE_7_1,VentasCobradaPorAreaCalculoSub,2025-01-01,3119721.00,1.566633e+07,0.199135
1,VE_7_1,VentasCobradaPorAreaCalculoSub,2025-02-01,6432383.73,3.313137e+07,0.194148
2,VE_7_1,VentasCobradaPorAreaCalculoSub,2025-03-01,8657207.73,5.188235e+07,0.166862
3,VE_7_1,VentasCobradaPorAreaCalculoSub,2025-04-01,12998249.72,5.850520e+07,0.222173
4,VE_7_1,VentasCobradaPorAreaCalculoSub,2025-05-01,17245841.72,6.954327e+07,0.247987

## 7. Objetivos de recaudo a nivel país (VentaCobradaBraunPais)

In [55]:
df_venta_recaudo_real

,CodigoEmpleado,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Venta,Recaudo
0,1111117,BA,0,Norte,A45,Renal AMB,80,2025-12-01,6.526043e+08,6.526043e+08
1,1111117,BA,0,Suroccidente,A45,RENAL AMB,80,2025-08-01,2.173649e+05,2.957838e+05
2,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-11-01,1.478919e+05,0.000000e+00
3,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-12-01,0.000000e+00,2.173649e+05
4,1111122,HC,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,2.818770e+07,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
21857,9990014,BA,14,Norte,A34,HOSPITAL,85,2025-08-01,1.022240e+07,2.732760e+05
21858,9990014,BA,14,Norte,A34,Hospital Privado,85,2025-07-01,0.000000e+00,0.000000e+00
21859,9990014,BA,14,Norte,A34,Hospital Privado,85,2025-08-01,0.000000e+00,0.000000e+00
21860,9990014,BA,14,Norte,A34,No Definido,85,2025-07-01,0.000000e+00,0.000000e+00
21861,9990014,BA,14,Norte,A34,No Definido,85,2025-08-01,0.000000e+00,0.000000e+00

In [56]:
df_venta_recaudo_presupuesto

,CodigoEmpleado,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Venta,Recaudo
0,1111117,BA,0,Norte,A45,Renal AMB,80,2025-12-01,0.000000e+00,0.000000e+00
1,1111117,BA,0,Suroccidente,A45,RENAL AMB,80,2025-08-01,0.000000e+00,0.000000e+00
2,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-11-01,0.000000e+00,0.000000e+00
3,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-12-01,0.000000e+00,0.000000e+00
4,1111122,HC,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
22568,9990014,BA,14,Norte,A34,HOSPITAL,85,2025-08-01,0.000000e+00,0.000000e+00
22569,9990014,BA,14,Norte,A34,Hospital Privado,85,2025-07-01,5.474118e+06,4.428108e+06
22570,9990014,BA,14,Norte,A34,Hospital Privado,85,2025-08-01,1.094824e+07,1.012139e+07
22571,9990014,BA,14,Norte,A34,No Definido,85,2025-07-01,0.000000e+00,0.000000e+00
22572,9990014,BA,14,Norte,A34,No Definido,85,2025-08-01,0.000000e+00,0.000000e+00

In [57]:
# recaudo real pais
venta_recaudo_real_pais = df_venta_recaudo_real.groupby(['Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_real_pais['Real'] = venta_recaudo_real_pais['Recaudo']
venta_recaudo_real_pais.drop(columns=['Recaudo'], inplace=True)

# recaudo presupuesto pais
venta_recaudo_presupuesto_pais = df_venta_recaudo_presupuesto.groupby(['Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_presupuesto_pais['Presupuesto'] = venta_recaudo_presupuesto_pais['Recaudo']
venta_recaudo_presupuesto_pais.drop(columns=['Recaudo'], inplace=True)

##
cumplimiento_recaudo_nivel_pais = pd.merge(
    left=venta_recaudo_presupuesto_pais,
    right=venta_recaudo_real_pais,
    on=['Fecha'],
    how='left'
)

In [58]:
cumplimiento_recaudo_nivel_pais

        Fecha   Presupuesto          Real
0  2025-01-01  2.188562e+10  2.002784e+10
1  2025-02-01  1.789158e+10  1.671452e+10
2  2025-03-01  2.029253e+10  1.739708e+10
3  2025-04-01  1.866113e+10  2.090346e+10
4  2025-05-01  2.009649e+10  1.852567e+10
5  2025-06-01  2.107846e+10  1.679920e+10
6  2025-07-01  1.910203e+10  2.068241e+10
7  2025-08-01  2.304529e+10  1.596489e+10
8  2025-09-01  2.333666e+10  2.596777e+10
9  2025-10-01  2.261575e+10  1.914014e+10
10 2025-11-01  2.259982e+10  1.621715e+10
11 2025-12-01  2.334216e+10  2.750059e+10

In [59]:

cumplimiento_recaudo_nivel_pais['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_nivel_pais['Real'] = cumplimiento_recaudo_nivel_pais['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_nivel_pais['Presupuesto'] = cumplimiento_recaudo_nivel_pais['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_nivel_pais['PorcentajeCumplimiento'] = cumplimiento_recaudo_nivel_pais['Real'] / cumplimiento_recaudo_nivel_pais['Presupuesto']
cumplimiento_recaudo_nivel_pais['PorcentajeCumplimiento'] = cumplimiento_recaudo_nivel_pais['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_recaudo_nivel_pais['Contexto'] = 'Pais'
cumplimiento_recaudo_nivel_pais['Variable'] = 'VentaCobradaBraunPais'
cumplimiento_recaudo_nivel_pais = cumplimiento_recaudo_nivel_pais[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_nivel_pais.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1738100921.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_nivel_pais['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,Pais,VentaCobradaBraunPais,2025-01-01,2.002784e+10,2.188562e+10,0.92
1,Pais,VentaCobradaBraunPais,2025-02-01,3.674236e+10,3.977720e+10,0.92
2,Pais,VentaCobradaBraunPais,2025-03-01,5.413943e+10,6.006973e+10,0.90
3,Pais,VentaCobradaBraunPais,2025-04-01,7.504289e+10,7.873086e+10,0.95
4,Pais,VentaCobradaBraunPais,2025-05-01,9.356855e+10,9.882735e+10,0.95

In [60]:
venta_recaudo_presupuesto_pais

        Fecha   Presupuesto
0  2025-01-01  2.188562e+10
1  2025-02-01  1.789158e+10
2  2025-03-01  2.029253e+10
3  2025-04-01  1.866113e+10
4  2025-05-01  2.009649e+10
5  2025-06-01  2.107846e+10
6  2025-07-01  1.910203e+10
7  2025-08-01  2.304529e+10
8  2025-09-01  2.333666e+10
9  2025-10-01  2.261575e+10
10 2025-11-01  2.259982e+10
11 2025-12-01  2.334216e+10

## 8. Objetivos de recaudo por unidad de negocio (VentaCobradaUnidadNegocio y VentaCobradaUnidadNegocioSub)

### 8.1. Para GU (VentaFacturadaUnidadNegocio - VentaFacturadaUnidadNegocioSub y VentaCobradaUnidadNegocio - VentaCobradaUnidadNegocioSub)

In [61]:
area_calculo_sba_completo_gu = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='GU']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los GU
venta_recaudo_presupuesto_original_gu_real = area_calculo_sba_completo_gu.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los GU
venta_recaudo_presupuesto_original_gu_presupuesto = area_calculo_sba_completo_gu.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#### 8.2.1 VentaFacturadaUnidadNegocio - VentaFacturadaUnidadNegocioSub

In [62]:
venta_recaudo_presupuesto_original_gu_real

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,Fecha,Venta,Recaudo
0,2,1,AE,CEK,30,GU,2025-02-01,323000.0,0.0
1,2,1,AE,CEK,30,GU,2025-01-01,0.0,0.0
2,2,1,AE,CEK,30,GU,2025-02-01,0.0,0.0
3,2,1,AE,CEK,30,GU,2025-03-01,0.0,0.0
4,2,1,AE,CEK,30,GU,2025-04-01,0.0,0.0
...,...,...,...,...,...,...,...,...,...
48031,10,10,AE,805,30,GU,2025-07-01,0.0,0.0
48032,10,10,AE,805,30,GU,2025-07-01,28433986.0,13698900.0
48033,10,10,AE,805,30,GU,2025-08-01,21995830.0,6236252.0
48034,10,10,AE,805,30,GU,2025-07-01,0.0,0.0
48035,10,10,AE,805,30,GU,2025-08-01,0.0,0.0

In [63]:
venta_recaudo_presupuesto_original_gu_presupuesto

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,Fecha,Venta,Recaudo
0,2,1,AE,CEK,30,GU,2025-02-01,0.000000e+00,0.000000e+00
1,2,1,AE,CEK,30,GU,2025-01-01,3.479714e+04,4.871585e+04
2,2,1,AE,CEK,30,GU,2025-02-01,4.639619e+04,3.247723e+04
3,2,1,AE,CEK,30,GU,2025-03-01,4.639619e+04,3.247723e+04
4,2,1,AE,CEK,30,GU,2025-04-01,4.639619e+04,4.871585e+04
...,...,...,...,...,...,...,...,...,...
49537,10,10,AE,805,30,GU,2025-07-01,4.886941e+05,5.131272e+05
49538,10,10,AE,805,30,GU,2025-07-01,0.000000e+00,0.000000e+00
49539,10,10,AE,805,30,GU,2025-08-01,0.000000e+00,0.000000e+00
49540,10,10,AE,805,30,GU,2025-07-01,9.558481e+06,1.003637e+07
49541,10,10,AE,805,30,GU,2025-08-01,1.911696e+07,1.561214e+07

##### VentaFacturadaUnidadNegocio

In [64]:
venta_real_area_calculo_gu = venta_recaudo_presupuesto_original_gu_real.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_real_area_calculo_gu['Real'] = venta_real_area_calculo_gu['Venta']
venta_real_area_calculo_gu.drop(columns=['Venta'], inplace=True)

venta_presupuesto_area_calculo_gu = venta_recaudo_presupuesto_original_gu_presupuesto.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_presupuesto_area_calculo_gu['Presupuesto'] = venta_presupuesto_area_calculo_gu['Venta']
venta_presupuesto_area_calculo_gu.drop(columns=['Venta'], inplace=True)

cumplimiento_venta_por_unidad_negocio_gu = pd.merge(
    left=venta_presupuesto_area_calculo_gu,
    right=venta_real_area_calculo_gu,
    on=['AreaCalculo', 'Fecha'],
    how='left'
)
cumplimiento_venta_por_unidad_negocio_gu['Real'].fillna(0.0, inplace=True)
cumplimiento_venta_por_unidad_negocio_gu['Real'] = cumplimiento_venta_por_unidad_negocio_gu.groupby(['AreaCalculo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_venta_por_unidad_negocio_gu['Presupuesto'] = cumplimiento_venta_por_unidad_negocio_gu.groupby(['AreaCalculo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_venta_por_unidad_negocio_gu['PorcentajeCumplimiento'] = cumplimiento_venta_por_unidad_negocio_gu['Real'] / cumplimiento_venta_por_unidad_negocio_gu['Presupuesto']
cumplimiento_venta_por_unidad_negocio_gu['PorcentajeCumplimiento'] = cumplimiento_venta_por_unidad_negocio_gu['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_venta_por_unidad_negocio_gu['Variable'] = 'VentaFacturadaUnidadNegocio'

### Cálculo de resultados cualitativos precargados
cumplimiento_venta_por_unidad_negocio_gu = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_venta_por_unidad_negocio_gu,
    variable='VentaFacturadaUnidadNegocio',
    columnas_extra=['TipoEmpleado', 'AreaCalculo'], 
    columnas_extra_merge=['AreaCalculo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'GU']
)
###

cumplimiento_venta_por_unidad_negocio_gu['AreaCalculo'] = cumplimiento_venta_por_unidad_negocio_gu['AreaCalculo'].astype('str')
cumplimiento_venta_por_unidad_negocio_gu['Contexto'] = 'gu_' + cumplimiento_venta_por_unidad_negocio_gu['AreaCalculo']
cumplimiento_venta_por_unidad_negocio_gu = cumplimiento_venta_por_unidad_negocio_gu[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_venta_por_unidad_negocio_gu.head()

['TipoEmpleado', 'AreaCalculo'] ['AreaCalculo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\352598715.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_por_unidad_negocio_gu['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,gu_1,VentaFacturadaUnidadNegocio,2025-01-01,1.979432e+09,2.578945e+09,0.77
1,gu_1,VentaFacturadaUnidadNegocio,2025-02-01,4.865472e+09,6.104677e+09,0.80
2,gu_1,VentaFacturadaUnidadNegocio,2025-03-01,8.659600e+09,9.364135e+09,0.92
3,gu_1,VentaFacturadaUnidadNegocio,2025-04-01,1.240023e+10,1.280304e+10,0.97
4,gu_1,VentaFacturadaUnidadNegocio,2025-05-01,1.621809e+10,1.669651e+10,0.97

##### VentaFacturadaUnidadNegocioSub

In [65]:
venta_real_area_calculo_gu_sub = venta_recaudo_presupuesto_original_gu_real.groupby(['AreaCalculo', 'Consecutivo', 'Fecha', 'Division', 'GrupoProducto'], as_index=False).agg({'Venta': 'sum'})
venta_real_area_calculo_gu_sub['Real'] = venta_real_area_calculo_gu_sub['Venta']
venta_real_area_calculo_gu_sub.drop(columns=['Venta'], inplace=True)

venta_presupuesto_area_calculo_gu_sub = venta_recaudo_presupuesto_original_gu_presupuesto.groupby(['AreaCalculo', 'Consecutivo', 'Fecha', 'Division', 'GrupoProducto'], as_index=False).agg({'Venta': 'sum'})
venta_presupuesto_area_calculo_gu_sub['Presupuesto'] = venta_presupuesto_area_calculo_gu_sub['Venta']
venta_presupuesto_area_calculo_gu_sub.drop(columns=['Venta'], inplace=True)

cumplimiento_venta_por_unidad_negocio_gu_sub = pd.merge(
    left=venta_presupuesto_area_calculo_gu_sub,
    right=venta_real_area_calculo_gu_sub,
    on=['AreaCalculo', 'Consecutivo', 'Fecha', 'Division', 'GrupoProducto'],
    how='left'
)
cumplimiento_venta_por_unidad_negocio_gu_sub['Real'].fillna(0.0, inplace=True)
cumplimiento_venta_por_unidad_negocio_gu_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1362027751.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_por_unidad_negocio_gu_sub['Real'].fillna(0.0, inplace=True)

,AreaCalculo,Consecutivo,Fecha,Division,GrupoProducto,Presupuesto,Real
0,1,1,2025-01-01,AE,M07,7.334591e+08,4.828488e+08
1,1,1,2025-02-01,AE,M07,1.004717e+09,8.395189e+08
2,1,1,2025-03-01,AE,M07,9.261208e+08,9.126753e+08
3,1,1,2025-04-01,AE,M07,9.797235e+08,8.990508e+08
4,1,1,2025-05-01,AE,M07,1.108076e+09,9.679186e+08
...,...,...,...,...,...,...,...
655,11,10,2025-10-01,BA,A45,2.345524e+09,6.983301e+07
656,11,10,2025-11-01,BA,660,2.956716e+07,7.501493e+07
657,11,10,2025-11-01,BA,A45,3.170321e+08,1.935415e+09
658,11,10,2025-12-01,BA,660,2.956716e+07,3.915003e+07
659,11,10,2025-12-01,BA,A45,3.170321e+08,4.116435e+09

In [66]:
cumplimiento_venta_por_unidad_negocio_gu_sub_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_tipo_empleado(cumplimiento_venta_por_unidad_negocio_gu_sub, 'VentaFacturadaUnidadNegocioSub', 'GU')
)
cumplimiento_venta_por_unidad_negocio_gu_sub_centro_costo.head(20)

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:805: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,gu_10_1,2025-01-01,805,AE,323007290,9.937943e+07,2.904601e+08,VentaFacturadaUnidadNegocioSub
1,gu_10_1,2025-02-01,805,AE,323007290,4.726244e+08,6.777402e+08,VentaFacturadaUnidadNegocioSub
2,gu_10_1,2025-03-01,805,AE,323007290,9.635211e+08,1.065020e+09,VentaFacturadaUnidadNegocioSub
3,gu_10_1,2025-04-01,805,AE,323007290,1.196840e+09,1.452300e+09,VentaFacturadaUnidadNegocioSub
4,gu_10_1,2025-05-01,805,AE,323007290,1.611809e+09,1.839580e+09,VentaFacturadaUnidadNegocioSub
5,gu_10_1,2025-06-01,805,AE,323007290,2.024401e+09,2.226861e+09,VentaFacturadaUnidadNegocioSub
6,gu_10_1,2025-07-01,805,AE,323007290,2.343108e+09,2.614141e+09,VentaFacturadaUnidadNegocioSub
7,gu_10_1,2025-08-01,805,AE,323007290,3.165225e+09,3.001421e+09,VentaFacturadaUnidadNegocioSub
8,gu_10_1,2025-09-01,805,AE,323007290,4.345735e+09,3.437111e+09,VentaFacturadaUnidadNegocioSub
9,gu_10_1,2025-10-01,805,AE,323007290,4.876691e+09,3.872801e+09,VentaFacturadaUnidadNegocioSub
10,gu_10_1,2025-11-01,805,AE,323007290,5.498936e+09,4.356901e+09,VentaFacturadaUnidadNegocioSub
11,gu_10_1,2025-12-01,805,AE,323007290,6.531274e+09,4.841001e+09,VentaFacturadaUnidadNegocioSub
12,gu_10_10,2025-01-01,805,AE,323007290,9.937943e+07,2.904601e+08,VentaFacturadaUnidadNegocioSub
13,gu_10_10,2025-01-01,M06,AE,323007290,1.078736e+08,1.192954e+08,VentaFacturadaUnidadNegocioSub
14,gu_10_10,2025-02-01,805,AE,323007290,4.726244e+08,6.777402e+08,VentaFacturadaUnidadNegocioSub
15,gu_10_10,2025-02-01,M06,AE,323007290,5.255156e+08,2.953985e+08,VentaFacturadaUnidadNegocioSub
16,gu_10_10,2025-03-01,805,AE,323007290,9.635211e+08,1.065020e+09,VentaFacturadaUnidadNegocioSub
17,gu_10_10,2025-03-01,M06,AE,323007290,8.418894e+08,5.226294e+08,VentaFacturadaUnidadNegocioSub
18,gu_10_10,2025-04-01,805,AE,323007290,1.196840e+09,1.452300e+09,VentaFacturadaUnidadNegocioSub
19,gu_10_10,2025-04-01,M06,AE,323007290,8.883028e+08,7.498602e+08,VentaFacturadaUnidadNegocioSub

In [67]:
cumplimiento_venta_por_unidad_negocio_gu_sub = cumplimiento_venta_por_unidad_negocio_gu_sub.groupby(['AreaCalculo', 'Consecutivo', 'Fecha', 'Division'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
cumplimiento_venta_por_unidad_negocio_gu_sub['Real'] = cumplimiento_venta_por_unidad_negocio_gu_sub.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_venta_por_unidad_negocio_gu_sub['Presupuesto'] = cumplimiento_venta_por_unidad_negocio_gu_sub.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_venta_por_unidad_negocio_gu_sub['PorcentajeCumplimiento'] = cumplimiento_venta_por_unidad_negocio_gu_sub['Real'] / cumplimiento_venta_por_unidad_negocio_gu_sub['Presupuesto']
cumplimiento_venta_por_unidad_negocio_gu_sub['PorcentajeCumplimiento'] = cumplimiento_venta_por_unidad_negocio_gu_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_venta_por_unidad_negocio_gu_sub['Variable'] = 'VentaFacturadaUnidadNegocioSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_venta_por_unidad_negocio_gu_sub = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_venta_por_unidad_negocio_gu_sub,
    variable='VentaFacturadaUnidadNegocioSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'GU']
)
###

cumplimiento_venta_por_unidad_negocio_gu_sub['Consecutivo'] = cumplimiento_venta_por_unidad_negocio_gu_sub['Consecutivo'].astype('str')
cumplimiento_venta_por_unidad_negocio_gu_sub['AreaCalculo'] = cumplimiento_venta_por_unidad_negocio_gu_sub['AreaCalculo'].astype('str')
cumplimiento_venta_por_unidad_negocio_gu_sub['Contexto'] = 'gu_' + cumplimiento_venta_por_unidad_negocio_gu_sub['AreaCalculo'].str.cat(cumplimiento_venta_por_unidad_negocio_gu_sub['Consecutivo'],sep="_")
cumplimiento_venta_por_unidad_negocio_gu_sub = cumplimiento_venta_por_unidad_negocio_gu_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_venta_por_unidad_negocio_gu_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2823289929.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  cumplimiento_venta_por_unidad_negocio_gu_sub = cumplimiento_venta_por_unidad_negocio_gu_sub.groupby(['AreaCalculo', 'Consecutivo', 'Fecha', 'Division'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,gu_1_1,VentaFacturadaUnidadNegocioSub,2025-01-01,4.828488e+08,7.334591e+08,0.66
1,gu_1_1,VentaFacturadaUnidadNegocioSub,2025-02-01,1.322368e+09,1.738176e+09,0.76
2,gu_1_1,VentaFacturadaUnidadNegocioSub,2025-03-01,2.235043e+09,2.664297e+09,0.84
3,gu_1_1,VentaFacturadaUnidadNegocioSub,2025-04-01,3.134094e+09,3.644020e+09,0.86
4,gu_1_1,VentaFacturadaUnidadNegocioSub,2025-05-01,4.102012e+09,4.752096e+09,0.86
...,...,...,...,...,...,...
403,gu_11_10,VentaFacturadaUnidadNegocioSub,2025-08-01,1.948414e+09,2.079595e+09,0.94
404,gu_11_10,VentaFacturadaUnidadNegocioSub,2025-09-01,2.121150e+09,2.426195e+09,0.87
405,gu_11_10,VentaFacturadaUnidadNegocioSub,2025-10-01,2.213468e+09,4.982693e+09,0.44
406,gu_11_10,VentaFacturadaUnidadNegocioSub,2025-11-01,4.223898e+09,5.329292e+09,0.79
407,gu_11_10,VentaFacturadaUnidadNegocioSub,2025-12-01,8.379483e+09,5.675892e+09,1.48

In [68]:
cumplimiento_venta_por_unidad_negocio_gu_sub[
    (cumplimiento_venta_por_unidad_negocio_gu_sub['Fecha'] == '2025-03-01') &
    (cumplimiento_venta_por_unidad_negocio_gu_sub['Contexto'] == 'gu_10_3')
]

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
350,gu_10_3,VentaFacturadaUnidadNegocioSub,2025-03-01,0.0,0.0,NaN

#### 8.2.2 VentaCobradaUnidadNegocio - VentaCobradaUnidadNegocioSub

##### VentaCobradaUnidadNegocio

In [69]:
recaudo_real_area_calculo_gu = venta_recaudo_presupuesto_original_gu_real.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_area_calculo_gu['Real'] = recaudo_real_area_calculo_gu['Recaudo']
recaudo_real_area_calculo_gu.drop(columns=['Recaudo'], inplace=True)

recaudo_presupuesto_area_calculo_gu = venta_recaudo_presupuesto_original_gu_presupuesto.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_area_calculo_gu['Presupuesto'] = recaudo_presupuesto_area_calculo_gu['Recaudo']
recaudo_presupuesto_area_calculo_gu.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_unidad_negocio_gu = pd.merge(
    left=recaudo_presupuesto_area_calculo_gu,
    right=recaudo_real_area_calculo_gu,
    on=['AreaCalculo', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_unidad_negocio_gu['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_unidad_negocio_gu['Real'] = cumplimiento_recaudo_por_unidad_negocio_gu.groupby(['AreaCalculo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_unidad_negocio_gu['Presupuesto'] = cumplimiento_recaudo_por_unidad_negocio_gu.groupby(['AreaCalculo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_unidad_negocio_gu['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_unidad_negocio_gu['Real'] / cumplimiento_recaudo_por_unidad_negocio_gu['Presupuesto']
cumplimiento_recaudo_por_unidad_negocio_gu['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_unidad_negocio_gu['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_unidad_negocio_gu['Variable'] = 'VentaCobradaUnidadNegocio'

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_unidad_negocio_gu = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_unidad_negocio_gu,
    variable='VentaCobradaUnidadNegocio',
    columnas_extra=['TipoEmpleado', 'AreaCalculo'], 
    columnas_extra_merge=['AreaCalculo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'GU']
)
###

cumplimiento_recaudo_por_unidad_negocio_gu['AreaCalculo'] = cumplimiento_recaudo_por_unidad_negocio_gu['AreaCalculo'].astype('str')
cumplimiento_recaudo_por_unidad_negocio_gu['Contexto'] = 'gu_' + cumplimiento_recaudo_por_unidad_negocio_gu['AreaCalculo']
cumplimiento_recaudo_por_unidad_negocio_gu = cumplimiento_recaudo_por_unidad_negocio_gu[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_por_unidad_negocio_gu.head()

['TipoEmpleado', 'AreaCalculo'] ['AreaCalculo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1887950857.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_unidad_negocio_gu['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,gu_1,VentaCobradaUnidadNegocio,2025-01-01,3.233245e+09,2.074231e+09,1.56
1,gu_1,VentaCobradaUnidadNegocio,2025-02-01,5.186178e+09,4.143906e+09,1.25
2,gu_1,VentaCobradaUnidadNegocio,2025-03-01,7.500928e+09,6.626178e+09,1.13
3,gu_1,VentaCobradaUnidadNegocio,2025-04-01,1.098979e+10,9.515373e+09,1.15
4,gu_1,VentaCobradaUnidadNegocio,2025-05-01,1.342025e+10,1.322443e+10,1.01

##### VentaCobradaUnidadNegocioSub

In [70]:
recaudo_real_area_calculo_gu_sub = venta_recaudo_presupuesto_original_gu_real.groupby(['AreaCalculo', 'Consecutivo', 'Fecha', 'Division', 'GrupoProducto'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_area_calculo_gu_sub['Real'] = recaudo_real_area_calculo_gu_sub['Recaudo']
recaudo_real_area_calculo_gu_sub.drop(columns=['Recaudo'], inplace=True)

recaudo_presupuesto_area_calculo_gu_sub = venta_recaudo_presupuesto_original_gu_presupuesto.groupby(['AreaCalculo', 'Consecutivo', 'Fecha', 'Division', 'GrupoProducto'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_area_calculo_gu_sub['Presupuesto'] = recaudo_presupuesto_area_calculo_gu_sub['Recaudo']
recaudo_presupuesto_area_calculo_gu_sub.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_unidad_negocio_gu_sub = pd.merge(
    left=recaudo_presupuesto_area_calculo_gu_sub,
    right=recaudo_real_area_calculo_gu_sub,
    on=['AreaCalculo', 'Consecutivo', 'Fecha', 'Division', 'GrupoProducto'],
    how='left'
)
cumplimiento_recaudo_por_unidad_negocio_gu_sub['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_unidad_negocio_gu_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\146854322.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_unidad_negocio_gu_sub['Real'].fillna(0.0, inplace=True)

,AreaCalculo,Consecutivo,Fecha,Division,GrupoProducto,Presupuesto,Real
0,1,1,2025-01-01,AE,M07,5.886231e+08,8.601273e+08
1,1,1,2025-02-01,AE,M07,5.871951e+08,5.281511e+08
2,1,1,2025-03-01,AE,M07,7.040629e+08,6.754326e+08
3,1,1,2025-04-01,AE,M07,8.223588e+08,9.122830e+08
4,1,1,2025-05-01,AE,M07,1.055142e+09,5.453048e+08
...,...,...,...,...,...,...,...
655,11,10,2025-10-01,BA,A45,3.608876e+08,5.714674e+07
656,11,10,2025-11-01,BA,660,4.380621e+07,1.836179e+07
657,11,10,2025-11-01,BA,A45,4.767959e+08,3.288963e+07
658,11,10,2025-12-01,BA,660,4.639762e+07,4.217121e+07
659,11,10,2025-12-01,BA,A45,5.057730e+08,5.726536e+09

In [71]:
cumplimiento_recaudo_por_unidad_negocio_gu_sub_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_tipo_empleado(cumplimiento_recaudo_por_unidad_negocio_gu_sub, 'VentaCobradaUnidadNegocioSub', 'GU')
)
cumplimiento_recaudo_por_unidad_negocio_gu_sub_centro_costo.head(20)

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:805: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,gu_10_1,2025-01-01,805,AE,323007290,2.840348e+08,4.066429e+08,VentaCobradaUnidadNegocioSub
1,gu_10_1,2025-02-01,805,AE,323007290,7.442792e+08,6.777381e+08,VentaCobradaUnidadNegocioSub
2,gu_10_1,2025-03-01,805,AE,323007290,9.457599e+08,9.488333e+08,VentaCobradaUnidadNegocioSub
3,gu_10_1,2025-04-01,805,AE,323007290,1.318050e+09,1.355476e+09,VentaCobradaUnidadNegocioSub
4,gu_10_1,2025-05-01,805,AE,323007290,1.748260e+09,1.671754e+09,VentaCobradaUnidadNegocioSub
5,gu_10_1,2025-06-01,805,AE,323007290,2.024480e+09,2.033214e+09,VentaCobradaUnidadNegocioSub
6,gu_10_1,2025-07-01,805,AE,323007290,2.392181e+09,2.439857e+09,VentaCobradaUnidadNegocioSub
7,gu_10_1,2025-08-01,805,AE,323007290,2.728544e+09,2.756135e+09,VentaCobradaUnidadNegocioSub
8,gu_10_1,2025-09-01,805,AE,323007290,3.301814e+09,3.298325e+09,VentaCobradaUnidadNegocioSub
9,gu_10_1,2025-10-01,805,AE,323007290,3.617294e+09,3.704968e+09,VentaCobradaUnidadNegocioSub
10,gu_10_1,2025-11-01,805,AE,323007290,4.017916e+09,4.066429e+09,VentaCobradaUnidadNegocioSub
11,gu_10_1,2025-12-01,805,AE,323007290,4.861572e+09,4.518254e+09,VentaCobradaUnidadNegocioSub
12,gu_10_10,2025-01-01,805,AE,323007290,2.840348e+08,4.066429e+08,VentaCobradaUnidadNegocioSub
13,gu_10_10,2025-01-01,M06,AE,323007290,2.496215e+08,2.938102e+08,VentaCobradaUnidadNegocioSub
14,gu_10_10,2025-02-01,805,AE,323007290,7.442792e+08,6.777381e+08,VentaCobradaUnidadNegocioSub
15,gu_10_10,2025-02-01,M06,AE,323007290,4.281665e+08,5.060446e+08,VentaCobradaUnidadNegocioSub
16,gu_10_10,2025-03-01,805,AE,323007290,9.457599e+08,9.488333e+08,VentaCobradaUnidadNegocioSub
17,gu_10_10,2025-03-01,M06,AE,323007290,6.519979e+08,7.182789e+08,VentaCobradaUnidadNegocioSub
18,gu_10_10,2025-04-01,805,AE,323007290,1.318050e+09,1.355476e+09,VentaCobradaUnidadNegocioSub
19,gu_10_10,2025-04-01,M06,AE,323007290,9.043582e+08,8.893826e+08,VentaCobradaUnidadNegocioSub

In [72]:
cumplimiento_recaudo_por_unidad_negocio_gu_sub = cumplimiento_recaudo_por_unidad_negocio_gu_sub.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
cumplimiento_recaudo_por_unidad_negocio_gu_sub['Real'] = cumplimiento_recaudo_por_unidad_negocio_gu_sub.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_unidad_negocio_gu_sub['Presupuesto'] = cumplimiento_recaudo_por_unidad_negocio_gu_sub.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_unidad_negocio_gu_sub['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_unidad_negocio_gu_sub['Real'] / cumplimiento_recaudo_por_unidad_negocio_gu_sub['Presupuesto']
cumplimiento_recaudo_por_unidad_negocio_gu_sub['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_unidad_negocio_gu_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_unidad_negocio_gu_sub['Variable'] = 'VentaCobradaUnidadNegocioSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_unidad_negocio_gu_sub = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_unidad_negocio_gu_sub,
    variable='VentaCobradaUnidadNegocioSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'GU']
)
###

cumplimiento_recaudo_por_unidad_negocio_gu_sub['Consecutivo'] = cumplimiento_recaudo_por_unidad_negocio_gu_sub['Consecutivo'].astype('str')
cumplimiento_recaudo_por_unidad_negocio_gu_sub['AreaCalculo'] = cumplimiento_recaudo_por_unidad_negocio_gu_sub['AreaCalculo'].astype('str')
cumplimiento_recaudo_por_unidad_negocio_gu_sub['Contexto'] = 'gu_' + cumplimiento_recaudo_por_unidad_negocio_gu_sub['AreaCalculo'].str.cat(cumplimiento_recaudo_por_unidad_negocio_gu_sub['Consecutivo'],sep="_")
cumplimiento_recaudo_por_unidad_negocio_gu_sub = cumplimiento_recaudo_por_unidad_negocio_gu_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_por_unidad_negocio_gu_sub.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2397856148.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  cumplimiento_recaudo_por_unidad_negocio_gu_sub = cumplimiento_recaudo_por_unidad_negocio_gu_sub.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,gu_1_1,VentaCobradaUnidadNegocioSub,2025-01-01,8.601273e+08,5.886231e+08,1.46
1,gu_1_1,VentaCobradaUnidadNegocioSub,2025-02-01,1.388278e+09,1.175818e+09,1.18
2,gu_1_1,VentaCobradaUnidadNegocioSub,2025-03-01,2.063711e+09,1.879881e+09,1.10
3,gu_1_1,VentaCobradaUnidadNegocioSub,2025-04-01,2.975994e+09,2.702240e+09,1.10
4,gu_1_1,VentaCobradaUnidadNegocioSub,2025-05-01,3.521299e+09,3.757382e+09,0.94

In [73]:
cumplimiento_recaudo_por_unidad_negocio_gu_sub[
    (cumplimiento_recaudo_por_unidad_negocio_gu_sub['Fecha'] == '2023-01-01') &
     (cumplimiento_recaudo_por_unidad_negocio_gu_sub['Contexto'] == 'gu_8_3')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [74]:
cumplimiento_recaudo_por_unidad_negocio_gu_sub[
    (cumplimiento_recaudo_por_unidad_negocio_gu_sub['Fecha'] == '2023-01-01') &
     (cumplimiento_recaudo_por_unidad_negocio_gu_sub['Contexto'] == 'gu_1_1')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 8.2. Para MK (VentaFacturadaUnidadNegocio - VentaFacturadaUnidadNegocioSub y VentaCobradaUnidadNegocio - VentaCobradaUnidadNegocioSub)

In [75]:
area_calculo_sba_completo_mk = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='MK']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los MK
venta_recaudo_presupuesto_original_mk_real = area_calculo_sba_completo_mk.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los MK
venta_recaudo_presupuesto_original_mk_presupuesto = area_calculo_sba_completo_mk.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#### 8.2.1 VentaFacturadaUnidadNegocio - VentaFacturadaUnidadNegocioSub

##### VentaFacturadaUnidadNegocio

In [76]:
venta_real_area_calculo_mk = venta_recaudo_presupuesto_original_mk_real.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_real_area_calculo_mk['Real'] = venta_real_area_calculo_mk['Venta']
venta_real_area_calculo_mk.drop(columns=['Venta'], inplace=True)

venta_presupuesto_area_calculo_mk = venta_recaudo_presupuesto_original_mk_presupuesto.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_presupuesto_area_calculo_mk['Presupuesto'] = venta_presupuesto_area_calculo_mk['Venta']
venta_presupuesto_area_calculo_mk.drop(columns=['Venta'], inplace=True)

cumplimiento_venta_por_unidad_negocio_mk = pd.merge(
    left=venta_presupuesto_area_calculo_mk,
    right=venta_real_area_calculo_mk,
    on=['AreaCalculo', 'Fecha'],
    how='left'
)
cumplimiento_venta_por_unidad_negocio_mk['Real'].fillna(0.0, inplace=True)
cumplimiento_venta_por_unidad_negocio_mk['Real'] = cumplimiento_venta_por_unidad_negocio_mk.groupby(['AreaCalculo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_venta_por_unidad_negocio_mk['Presupuesto'] = cumplimiento_venta_por_unidad_negocio_mk.groupby(['AreaCalculo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_venta_por_unidad_negocio_mk['PorcentajeCumplimiento'] = cumplimiento_venta_por_unidad_negocio_mk['Real'] / cumplimiento_venta_por_unidad_negocio_mk['Presupuesto']
cumplimiento_venta_por_unidad_negocio_mk['PorcentajeCumplimiento'] = cumplimiento_venta_por_unidad_negocio_mk['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_venta_por_unidad_negocio_mk['Variable'] = 'VentaFacturadaUnidadNegocio'
#areas de calculo son unidades de negocio

### Cálculo de resultados cualitativos precargados
cumplimiento_venta_por_unidad_negocio_mk = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_venta_por_unidad_negocio_mk,
    variable='VentaFacturadaUnidadNegocio',
    columnas_extra=['TipoEmpleado', 'AreaCalculo'], 
    columnas_extra_merge=['AreaCalculo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'MK']
)
###

cumplimiento_venta_por_unidad_negocio_mk['AreaCalculo'] = cumplimiento_venta_por_unidad_negocio_mk['AreaCalculo'].astype('str')
cumplimiento_venta_por_unidad_negocio_mk['Contexto'] = 'mk_' + cumplimiento_venta_por_unidad_negocio_mk['AreaCalculo']
cumplimiento_venta_por_unidad_negocio_mk = cumplimiento_venta_por_unidad_negocio_mk[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_venta_por_unidad_negocio_mk.head()

['TipoEmpleado', 'AreaCalculo'] ['AreaCalculo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1564675196.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_por_unidad_negocio_mk['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,mk_1,VentaFacturadaUnidadNegocio,2025-01-01,8.348014e+09,1.415446e+10,0.59
1,mk_1,VentaFacturadaUnidadNegocio,2025-02-01,2.475093e+10,3.204157e+10,0.77
2,mk_1,VentaFacturadaUnidadNegocio,2025-03-01,4.202453e+10,5.207175e+10,0.81
3,mk_1,VentaFacturadaUnidadNegocio,2025-04-01,5.901977e+10,6.877612e+10,0.86
4,mk_1,VentaFacturadaUnidadNegocio,2025-05-01,8.029927e+10,8.957266e+10,0.90

##### VentaFacturadaUnidadNegocioSub

In [77]:
venta_real_area_calculo_mk_sub = venta_recaudo_presupuesto_original_mk_real.groupby(['AreaCalculo', 'Division', 'GrupoProducto','Consecutivo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_real_area_calculo_mk_sub['Real'] = venta_real_area_calculo_mk_sub['Venta']
venta_real_area_calculo_mk_sub.drop(columns=['Venta'], inplace=True)

venta_presupuesto_area_calculo_mk_sub = venta_recaudo_presupuesto_original_mk_presupuesto.groupby(['AreaCalculo', 'Division', 'GrupoProducto', 'Consecutivo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_presupuesto_area_calculo_mk_sub['Presupuesto'] = venta_presupuesto_area_calculo_mk_sub['Venta']
venta_presupuesto_area_calculo_mk_sub.drop(columns=['Venta'], inplace=True)

cumplimiento_venta_por_unidad_negocio_mk_sub = pd.merge(
    left=venta_presupuesto_area_calculo_mk_sub,
    right=venta_real_area_calculo_mk_sub,
    on=['AreaCalculo', 'Division', 'GrupoProducto' ,'Consecutivo', 'Fecha'],
    how='left'
)
cumplimiento_venta_por_unidad_negocio_mk_sub['Real'].fillna(0.0, inplace=True)
cumplimiento_venta_por_unidad_negocio_mk_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2152228957.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_venta_por_unidad_negocio_mk_sub['Real'].fillna(0.0, inplace=True)

,AreaCalculo,Division,GrupoProducto,Consecutivo,Fecha,Presupuesto,Real
0,1,AE,001,2,2025-01-01,5.391608e+08,1.781555e+08
1,1,AE,001,2,2025-02-01,7.190397e+08,6.725782e+08
2,1,AE,001,2,2025-03-01,7.188944e+08,8.261027e+08
3,1,AE,001,2,2025-04-01,7.187163e+08,3.132514e+08
4,1,AE,001,2,2025-05-01,7.187998e+08,2.112630e+08
...,...,...,...,...,...,...,...
1303,13,HC,CDK,1,2025-08-01,1.981867e+07,0.000000e+00
1304,13,HC,CDK,1,2025-09-01,2.144761e+07,3.400000e+05
1305,13,HC,CDK,1,2025-10-01,2.389100e+07,2.630000e+05
1306,13,HC,CDK,1,2025-11-01,2.986375e+07,4.067760e+05
1307,13,HC,CDK,1,2025-12-01,3.312162e+07,1.206328e+06

In [78]:
# def f_calculo_centro_costo_variable_tipo_empleado(main, variable, tipo_empleado):
# #     df_area_calculo_sba_centros_costos_tipo_empleado = (
# #         df_area_calculo_sba_centros_costos[df_area_calculo_sba_centros_costos['TipoEmpleado'] == tipo_empleado]
# #     )    
    
#     main = main.merge(
#         df_centros_costos_grupos_productos_divisiones.rename(columns={'ConsecutivoParrilla':'Consecutivo'}),
#         on=['Division', 'GrupoProducto'],
#         how='left'
#     )
#     main['AreaCalculo'] = main['AreaCalculo'].astype(str)
#     main['Consecutivo'] = main['Consecutivo'].astype(str)
#     main['Contexto'] = tipo_empleado.lower() +'_'+ main['AreaCalculo'].str.cat(main['Consecutivo'],sep="_")
#     main = main.groupby(['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
    
# #     main['Real'] = main.groupby(['Contexto', 'CentroCosto'])['Real'].transform(pd.Series.sum)
# #     main['Presupuesto'] = main.groupby(['Contexto', 'CentroCosto'])['Presupuesto'].transform(pd.Series.sum)
    
#     main['Real'] = main.groupby(['Contexto', 'GrupoProducto', 'Division', 'CodigoCentroCosto'])['Real'].transform(pd.Series.cumsum)
#     main['Presupuesto'] = main.groupby(['Contexto', 'GrupoProducto', 'Division', 'CodigoCentroCosto'])['Presupuesto'].transform(pd.Series.cumsum)
#     main['Variable'] = variable
#     return main

In [79]:
cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_tipo_empleado(cumplimiento_venta_por_unidad_negocio_mk_sub, 'VentaFacturadaUnidadNegocioSub', 'MK')
)
cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo.head()

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:805: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,mk_11_1,2025-01-01,610,HC,323015040,7.580025e+08,1.079057e+09,VentaFacturadaUnidadNegocioSub
1,mk_11_1,2025-01-01,620,HC,323015045,3.415963e+09,6.210553e+09,VentaFacturadaUnidadNegocioSub
2,mk_11_1,2025-01-01,630,HC,323015050,1.880039e+09,2.756291e+09,VentaFacturadaUnidadNegocioSub
3,mk_11_1,2025-01-01,640,HC,323015055,-3.137790e+05,6.450480e+06,VentaFacturadaUnidadNegocioSub
4,mk_11_1,2025-01-01,680,HC,323015055,2.664789e+08,4.592093e+08,VentaFacturadaUnidadNegocioSub

In [80]:
cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo.columns

Index(['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto',
       'Real', 'Presupuesto', 'Variable'],
      dtype='object')

In [81]:
 pd.DataFrame(cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo.columns, columns=['Columna']).to_excel("cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo_columns.xlsx")

In [82]:
cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo[
    (cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo['Contexto'] == 'mk_1_1') &
    (cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo['Fecha'] == '2023-01-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, GrupoProducto, Division, CodigoCentroCosto, Real, Presupuesto, Variable]
Index: []

In [83]:
dataframe_loader.validar_calculo_centro_costo(cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo, 'mk_1_1', '2023-01-01')

(0.0, 0.0)

In [84]:
cumplimiento_venta_por_unidad_negocio_mk_sub = cumplimiento_venta_por_unidad_negocio_mk_sub.groupby(
    ['AreaCalculo' ,'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
cumplimiento_venta_por_unidad_negocio_mk_sub['Real'] = cumplimiento_venta_por_unidad_negocio_mk_sub.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_venta_por_unidad_negocio_mk_sub['Presupuesto'] = cumplimiento_venta_por_unidad_negocio_mk_sub.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_venta_por_unidad_negocio_mk_sub['PorcentajeCumplimiento'] = cumplimiento_venta_por_unidad_negocio_mk_sub['Real'] / cumplimiento_venta_por_unidad_negocio_mk_sub['Presupuesto']
cumplimiento_venta_por_unidad_negocio_mk_sub['PorcentajeCumplimiento'] = cumplimiento_venta_por_unidad_negocio_mk_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_venta_por_unidad_negocio_mk_sub['Variable'] = 'VentaFacturadaUnidadNegocioSub'
#areas de calculo son unidades de negocio

### Cálculo de resultados cualitativos precargados
cumplimiento_venta_por_unidad_negocio_mk_sub = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_venta_por_unidad_negocio_mk_sub,
    variable='VentaFacturadaUnidadNegocioSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'MK']
)
###

cumplimiento_venta_por_unidad_negocio_mk_sub['Consecutivo'] = cumplimiento_venta_por_unidad_negocio_mk_sub['Consecutivo'].astype('str')
cumplimiento_venta_por_unidad_negocio_mk_sub['AreaCalculo'] = cumplimiento_venta_por_unidad_negocio_mk_sub['AreaCalculo'].astype('str')
cumplimiento_venta_por_unidad_negocio_mk_sub['Contexto'] = 'mk_' + cumplimiento_venta_por_unidad_negocio_mk_sub['AreaCalculo'].str.cat(cumplimiento_venta_por_unidad_negocio_mk_sub['Consecutivo'],sep="_")
cumplimiento_venta_por_unidad_negocio_mk_sub = cumplimiento_venta_por_unidad_negocio_mk_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_venta_por_unidad_negocio_mk_sub[
    (cumplimiento_venta_por_unidad_negocio_mk_sub['Contexto'] == 'mk_1_1')
]

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2779605923.py:2: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['AreaCalculo' ,'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-01-01,6.320170e+09,1.053002e+10,0.60
1,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-02-01,1.828696e+10,2.373706e+10,0.77
2,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-03-01,3.055086e+10,3.886306e+10,0.79
3,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-04-01,4.408188e+10,5.105676e+10,0.86
4,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-05-01,6.114383e+10,6.681502e+10,0.92
5,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-06-01,7.543283e+10,8.303865e+10,0.91
6,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-07-01,8.983765e+10,9.856748e+10,0.91
7,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-08-01,1.023506e+11,1.149217e+11,0.89
8,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-09-01,1.161054e+11,1.311605e+11,0.89
9,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-10-01,1.297584e+11,1.471943e+11,0.88
10,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-11-01,1.460295e+11,1.656389e+11,0.88
11,mk_1_1,VentaFacturadaUnidadNegocioSub,2025-12-01,1.653977e+11,1.862389e+11,0.89

#### 8.2.2 VentaCobradaUnidadNegocio - VentaCobradaUnidadNegocioSub

##### VentaCobradaUnidadNegocio

In [85]:
recaudo_real_area_calculo_mk = venta_recaudo_presupuesto_original_mk_real.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_area_calculo_mk['Real'] = recaudo_real_area_calculo_mk['Recaudo']
recaudo_real_area_calculo_mk.drop(columns=['Recaudo'], inplace=True)

recaudo_presupuesto_area_calculo_mk = venta_recaudo_presupuesto_original_mk_presupuesto.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_area_calculo_mk['Presupuesto'] = recaudo_presupuesto_area_calculo_mk['Recaudo']
recaudo_presupuesto_area_calculo_mk.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_unidad_negocio_mk = pd.merge(
    left=recaudo_presupuesto_area_calculo_mk,
    right=recaudo_real_area_calculo_mk,
    on=['AreaCalculo', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_unidad_negocio_mk['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_unidad_negocio_mk['Real'] = cumplimiento_recaudo_por_unidad_negocio_mk.groupby(['AreaCalculo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_unidad_negocio_mk['Presupuesto'] = cumplimiento_recaudo_por_unidad_negocio_mk.groupby(['AreaCalculo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_unidad_negocio_mk['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_unidad_negocio_mk['Real'] / cumplimiento_recaudo_por_unidad_negocio_mk['Presupuesto']
cumplimiento_recaudo_por_unidad_negocio_mk['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_unidad_negocio_mk['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_unidad_negocio_mk['Variable'] = 'VentaCobradaUnidadNegocio'
#areas de calculo son unidades de negocio

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_unidad_negocio_mk = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_unidad_negocio_mk,
    variable='VentaCobradaUnidadNegocio',
    columnas_extra=['TipoEmpleado', 'AreaCalculo'], 
    columnas_extra_merge=['AreaCalculo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'MK']
)
###

cumplimiento_recaudo_por_unidad_negocio_mk['AreaCalculo'] = cumplimiento_recaudo_por_unidad_negocio_mk['AreaCalculo'].astype('str')
cumplimiento_recaudo_por_unidad_negocio_mk['Contexto'] = 'mk_' + cumplimiento_recaudo_por_unidad_negocio_mk['AreaCalculo']
cumplimiento_recaudo_por_unidad_negocio_mk = cumplimiento_recaudo_por_unidad_negocio_mk[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_por_unidad_negocio_mk.head()

['TipoEmpleado', 'AreaCalculo'] ['AreaCalculo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\684831893.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_unidad_negocio_mk['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,mk_1,VentaCobradaUnidadNegocio,2025-01-01,1.946990e+10,2.119744e+10,0.92
1,mk_1,VentaCobradaUnidadNegocio,2025-02-01,3.553531e+10,3.834701e+10,0.93
2,mk_1,VentaCobradaUnidadNegocio,2025-03-01,5.198538e+10,5.796172e+10,0.90
3,mk_1,VentaCobradaUnidadNegocio,2025-04-01,7.184509e+10,7.589854e+10,0.95
4,mk_1,VentaCobradaUnidadNegocio,2025-05-01,8.974589e+10,9.531353e+10,0.94

##### VentaCobradaUnidadNegocioSub

In [86]:
recaudo_real_area_calculo_mk_sub = venta_recaudo_presupuesto_original_mk_real.groupby(['AreaCalculo', 'Division', 'GrupoProducto','Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_area_calculo_mk_sub['Real'] = recaudo_real_area_calculo_mk_sub['Recaudo']
recaudo_real_area_calculo_mk_sub.drop(columns=['Recaudo'], inplace=True)

recaudo_presupuesto_area_calculo_mk_sub = venta_recaudo_presupuesto_original_mk_presupuesto.groupby(['AreaCalculo', 'Division', 'GrupoProducto', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_area_calculo_mk_sub['Presupuesto'] = recaudo_presupuesto_area_calculo_mk_sub['Recaudo']
recaudo_presupuesto_area_calculo_mk_sub.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_unidad_negocio_mk_sub = pd.merge(
    left=recaudo_presupuesto_area_calculo_mk_sub,
    right=recaudo_real_area_calculo_mk_sub,
    on=['AreaCalculo', 'Consecutivo', 'Fecha', 'Division', 'GrupoProducto'],
    how='left'
)
cumplimiento_recaudo_por_unidad_negocio_mk_sub['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_unidad_negocio_mk_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2283138158.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_unidad_negocio_mk_sub['Real'].fillna(0.0, inplace=True)

,AreaCalculo,Division,GrupoProducto,Consecutivo,Fecha,Presupuesto,Real
0,1,AE,001,2,2025-01-01,7.543752e+08,3.574246e+08
1,1,AE,001,2,2025-02-01,5.032218e+08,5.624941e+08
2,1,AE,001,2,2025-03-01,5.032978e+08,3.211215e+08
3,1,AE,001,2,2025-04-01,7.546800e+08,4.399869e+08
4,1,AE,001,2,2025-05-01,5.873965e+08,3.501197e+08
...,...,...,...,...,...,...,...
1303,13,HC,CDK,1,2025-08-01,2.234171e+07,0.000000e+00
1304,13,HC,CDK,1,2025-09-01,2.087186e+07,2.800000e+06
1305,13,HC,CDK,1,2025-10-01,2.469347e+07,3.230000e+05
1306,13,HC,CDK,1,2025-11-01,2.145980e+07,0.000000e+00
1307,13,HC,CDK,1,2025-12-01,2.322362e+07,2.660000e+05

In [87]:
cumplimiento_recaudo_por_unidad_negocio_mk_sub_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_tipo_empleado(cumplimiento_recaudo_por_unidad_negocio_mk_sub, 'VentaCobradaUnidadNegocioSub', 'MK')
)
cumplimiento_recaudo_por_unidad_negocio_mk_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:805: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,mk_11_1,2025-01-01,610,HC,323015040,1.167113e+09,1.532369e+09,VentaCobradaUnidadNegocioSub
1,mk_11_1,2025-01-01,620,HC,323015045,6.764013e+09,7.211689e+09,VentaCobradaUnidadNegocioSub
2,mk_11_1,2025-01-01,630,HC,323015050,4.395557e+09,4.469108e+09,VentaCobradaUnidadNegocioSub
3,mk_11_1,2025-01-01,640,HC,323015055,3.119721e+06,1.566633e+07,VentaCobradaUnidadNegocioSub
4,mk_11_1,2025-01-01,680,HC,323015055,5.887839e+08,6.672801e+08,VentaCobradaUnidadNegocioSub
...,...,...,...,...,...,...,...,...
1303,mk_6_5,2025-08-01,001,AE,323007270,3.957676e+09,5.116238e+09,VentaCobradaUnidadNegocioSub
1304,mk_6_5,2025-09-01,001,AE,323007270,6.368331e+09,6.122223e+09,VentaCobradaUnidadNegocioSub
1305,mk_6_5,2025-10-01,001,AE,323007270,6.774478e+09,6.877131e+09,VentaCobradaUnidadNegocioSub
1306,mk_6_5,2025-11-01,001,AE,323007270,7.091999e+09,7.548322e+09,VentaCobradaUnidadNegocioSub
1307,mk_6_5,2025-12-01,001,AE,323007270,8.801747e+09,8.387024e+09,VentaCobradaUnidadNegocioSub

In [88]:
dataframe_loader.validar_calculo_centro_costo(cumplimiento_recaudo_por_unidad_negocio_mk_sub_centro_costo, 'mk_1_1', '2023-02-01')

(0.0, 0.0)

In [89]:
cumplimiento_recaudo_por_unidad_negocio_mk_sub = (
    cumplimiento_recaudo_por_unidad_negocio_mk_sub.groupby(
        ['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False
    )[['Real', 'Presupuesto']].apply(sum)
)
cumplimiento_recaudo_por_unidad_negocio_mk_sub['Real'] = cumplimiento_recaudo_por_unidad_negocio_mk_sub.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_unidad_negocio_mk_sub['Presupuesto'] = cumplimiento_recaudo_por_unidad_negocio_mk_sub.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_unidad_negocio_mk_sub['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_unidad_negocio_mk_sub['Real'] / cumplimiento_recaudo_por_unidad_negocio_mk_sub['Presupuesto']
cumplimiento_recaudo_por_unidad_negocio_mk_sub['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_unidad_negocio_mk_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_unidad_negocio_mk_sub['Variable'] = 'VentaCobradaUnidadNegocioSub'
#areas de calculo son unidades de negocio

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_unidad_negocio_mk_sub = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_unidad_negocio_mk_sub,
    variable='VentaCobradaUnidadNegocioSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'MK']
)
###

cumplimiento_recaudo_por_unidad_negocio_mk_sub['Consecutivo'] = cumplimiento_recaudo_por_unidad_negocio_mk_sub['Consecutivo'].astype('str')
cumplimiento_recaudo_por_unidad_negocio_mk_sub['AreaCalculo'] = cumplimiento_recaudo_por_unidad_negocio_mk_sub['AreaCalculo'].astype('str')
cumplimiento_recaudo_por_unidad_negocio_mk_sub['Contexto'] = 'mk_' + cumplimiento_recaudo_por_unidad_negocio_mk_sub['AreaCalculo'].str.cat(cumplimiento_recaudo_por_unidad_negocio_mk_sub['Consecutivo'],sep="_")
cumplimiento_recaudo_por_unidad_negocio_mk_sub = cumplimiento_recaudo_por_unidad_negocio_mk_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_por_unidad_negocio_mk_sub.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1703510272.py:4: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  )[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,mk_1_1,VentaCobradaUnidadNegocioSub,2025-01-01,1.291859e+10,1.392163e+10,0.93
1,mk_1_1,VentaCobradaUnidadNegocioSub,2025-02-01,2.556295e+10,2.752997e+10,0.93
2,mk_1_1,VentaCobradaUnidadNegocioSub,2025-03-01,3.850128e+10,4.321841e+10,0.89
3,mk_1_1,VentaCobradaUnidadNegocioSub,2025-04-01,5.364112e+10,5.674368e+10,0.95
4,mk_1_1,VentaCobradaUnidadNegocioSub,2025-05-01,6.790122e+10,7.132300e+10,0.95

## 9. Objetivos de rentabilidad por unidad de negocio (RentabilidadUnidadNegocioCM2 y RentabilidadUnidadNegocioCM3)

### 9.1. Para GU (RentabilidadUnidadNegocioCM2 y RentabilidadUnidadNegocioCM3)

In [90]:
rentabilidad_gu = df_rentabilidad.copy()
rentabilidad_gu['TipoEmpleado'] = 'GU'
rentabilidad_gu = rentabilidad_gu.merge(
    area_calculo_sba_completo[['TipoEmpleado', 'AreaCalculo', 'GrupoProducto', 'SBA']],
    on=['TipoEmpleado', 'GrupoProducto', 'SBA'],
    how='left'
)
rentabilidad_gu = rentabilidad_gu.groupby(
    ['TipoEmpleado', 'ClaseRentabilidad', 'Fecha', 'AreaCalculo'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})

rentabilidad_gu['PorcentajeCumplimiento'] = rentabilidad_gu['Real'] / rentabilidad_gu['Presupuesto']
rentabilidad_gu['PorcentajeCumplimiento'] = rentabilidad_gu['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
rentabilidad_gu.head()

,TipoEmpleado,ClaseRentabilidad,Fecha,AreaCalculo,Real,Presupuesto,PorcentajeCumplimiento
0,GU,CM2COGSP,2025-03-01,1.0,8.637442e+05,7.880646e+05,1.10
1,GU,CM2COGSP,2025-03-01,2.0,8.089282e+05,7.671570e+05,1.05
2,GU,CM2COGSP,2025-03-01,3.0,5.439780e+05,5.247297e+05,1.04
3,GU,CM2COGSP,2025-03-01,4.0,1.819882e+06,3.007628e+06,0.61
4,GU,CM2COGSP,2025-03-01,5.0,5.658264e+06,6.151396e+06,0.92

In [91]:
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu = rentabilidad_gu[
    rentabilidad_gu['ClaseRentabilidad'] == 'CMII']
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu.drop(columns='ClaseRentabilidad', inplace=True)

cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu['Variable'] = 'RentabilidadUnidadNegocioCM2'
### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu,
    variable='RentabilidadUnidadNegocioCM2',
    columnas_extra=['TipoEmpleado', 'AreaCalculo'],
    columnas_extra_merge=['TipoEmpleado', 'AreaCalculo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'GU']
)
###
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu['AreaCalculo'] = \
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu['AreaCalculo'].astype(int).astype('str')
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu['Contexto'] = 'gu_' + \
                                                                  cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu[
                                                                      'AreaCalculo']
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu = cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu[
    ['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu.head()

['TipoEmpleado', 'AreaCalculo'] ['TipoEmpleado', 'AreaCalculo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\10538928.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu.drop(columns='ClaseRentabilidad', inplace=True)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [92]:
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu = rentabilidad_gu[
    rentabilidad_gu['ClaseRentabilidad'] == 'CMIII']
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu.drop(columns='ClaseRentabilidad', inplace=True)

cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu['Variable'] = 'RentabilidadUnidadNegocioCM3'
### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu,
    variable='RentabilidadUnidadNegocioCM3',
    columnas_extra=['TipoEmpleado', 'AreaCalculo'],
    columnas_extra_merge=['TipoEmpleado', 'AreaCalculo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'GU']
)
###
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu['AreaCalculo'] = \
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu['AreaCalculo'].astype(int).astype('str')
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu['Contexto'] = 'gu_' + \
                                                                  cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu[
                                                                      'AreaCalculo']
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu = cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu[
    ['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu.head()

['TipoEmpleado', 'AreaCalculo'] ['TipoEmpleado', 'AreaCalculo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\90434115.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu.drop(columns='ClaseRentabilidad', inplace=True)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 9.2. Para MK (RentabilidadUnidadNegocioCM2 y RentabilidadUnidadNegocioCM3)

In [93]:
rentabilidad_mk = df_rentabilidad.copy()
rentabilidad_mk['TipoEmpleado'] = 'MK'
rentabilidad_mk = rentabilidad_mk.merge(
    area_calculo_sba_completo[['TipoEmpleado', 'AreaCalculo', 'GrupoProducto', 'SBA']],
    on=['TipoEmpleado', 'GrupoProducto', 'SBA'],
    how='left'
)
rentabilidad_mk = rentabilidad_mk.groupby(
    ['TipoEmpleado', 'ClaseRentabilidad', 'Fecha', 'AreaCalculo'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})

# rentabilidad_mk_sub['Presupuesto'] = rentabilidad_mk_sub.groupby(['ClaseRentabilidad', 'AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
# rentabilidad_mk_sub['Real'] = rentabilidad_mk_sub.groupby(['ClaseRentabilidad', 'AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
rentabilidad_mk['PorcentajeCumplimiento'] = rentabilidad_mk['Real']/rentabilidad_mk['Presupuesto']
rentabilidad_mk['PorcentajeCumplimiento'] = rentabilidad_mk['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk = rentabilidad_mk[rentabilidad_mk['ClaseRentabilidad']=='CMII']
cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk.drop(columns='ClaseRentabilidad', inplace=True)
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk = rentabilidad_mk[rentabilidad_mk['ClaseRentabilidad']=='CMIII']
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk.drop(columns='ClaseRentabilidad', inplace=True)

cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk['Variable'] = 'RentabilidadUnidadNegocioCM2'
### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk,
    variable='RentabilidadUnidadNegocioCM2',
    columnas_extra=['TipoEmpleado', 'AreaCalculo'], 
    columnas_extra_merge=['TipoEmpleado', 'AreaCalculo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'MK']
)
###
cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk['AreaCalculo'] = cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk['AreaCalculo'].astype(int).astype('str')
cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk['Contexto'] = 'mk_' + cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk['AreaCalculo']
cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk = cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk['Variable'] = 'RentabilidadUnidadNegocioCM3'
### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk,
    variable='RentabilidadUnidadNegocioCM3',
    columnas_extra=['TipoEmpleado', 'AreaCalculo'], 
    columnas_extra_merge=['TipoEmpleado', 'AreaCalculo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'MK']
)
###
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk['AreaCalculo'] = cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk['AreaCalculo'].astype(int).astype('str')
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk['Contexto'] = 'mk_' + cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk['AreaCalculo']
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk = cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk.head()

['TipoEmpleado', 'AreaCalculo'] ['TipoEmpleado', 'AreaCalculo']
['TipoEmpleado', 'AreaCalculo'] ['TipoEmpleado', 'AreaCalculo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3884681295.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk.drop(columns='ClaseRentabilidad', inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3884681295.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk.drop(columns='ClaseRentabilidad', inplace=True)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 10. Objetivos de rentabilidad por unidad de negocio (RentabilidadUnidadNegocioCM2Sub y RentabilidadUnidadNegocioCM3Sub)

### 10.1. Para GU (RentabilidadUnidadNegocioCM2Sub y RentabilidadUnidadNegocioCM3Sub)

In [94]:
# def f_calculo_centro_costo_variable_rentabilidad(main, variable, clase_rentabilidad, tipo_empleado):
#     main = main.merge(
#         df_centros_costos_grupos_productos_divisiones.rename(columns={'ConsecutivoParrilla':'Consecutivo'}),
#         on=['Division', 'GrupoProducto'],
#         how='left'
#     )
#     main['Consecutivo'] = main['Consecutivo'].astype(int).astype('str')
#     main['AreaCalculo'] = main['AreaCalculo'].astype(int).astype('str')
#     main['Contexto'] = tipo_empleado.lower()+'_' + main['AreaCalculo'] + '_' +main['Consecutivo']
#     main = main.groupby(
#         ['TipoEmpleado', 'ClaseRentabilidad', 'Fecha', 'AreaCalculo', 'Consecutivo', 'CodigoCentroCosto', 'Contexto'],
#         as_index=False
#     ).agg({'Real': 'sum', 'Presupuesto': 'sum'})
#     main = main[main['ClaseRentabilidad']==clase_rentabilidad]
#     main.drop(columns='ClaseRentabilidad', inplace=True)
#     main['Variable'] = variable
#     return main

# def calculo_porcentaje_cumplimiento(main, variable, tipo_empleado):

#     main = main.groupby(
#         ['TipoEmpleado', 'Fecha', 'AreaCalculo', 'Consecutivo', 'Variable'],
#         as_index=False
#     ).agg({'Real': 'sum', 'Presupuesto': 'sum'})
    
#     main['PorcentajeCumplimiento'] = (
#         main['Real']/
#         main['Presupuesto'])
#     main['PorcentajeCumplimiento'] = (
#         main['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
#     )
#     ### Cálculo de resultados cualitativos precargados
#     main = dataframe_loader.sobreescribir_resultados_cualitativos(
#         main=main,
#         variable=variable,
#         columnas_extra=['TipoEmpleado', 'AreaCalculo'], 
#         columnas_extra_merge=['TipoEmpleado', 'AreaCalculo'],
#         pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == tipo_empleado]
#     )
#     ###
#     main['Consecutivo'] = main['Consecutivo'].astype(int).astype('str')
#     main['AreaCalculo'] = main['AreaCalculo'].astype(int).astype('str')
    
#     main['Contexto'] = tipo_empleado.lower()+'_' + main['AreaCalculo'] + '_' +main['Consecutivo']
#     main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
#     return main

In [95]:
#Calculamos la rentabilidad para GU adicionando toda la info de area_calculo_sba_completo
rentabilidad_gu_sub = df_rentabilidad.copy()
rentabilidad_gu_sub['TipoEmpleado'] = 'GU'
rentabilidad_gu_sub = rentabilidad_gu_sub.merge(
    area_calculo_sba_completo[['TipoEmpleado', 'AreaCalculo', 'GrupoProducto', 'Division', 'Consecutivo', 'SBA']],
    on=['TipoEmpleado', 'GrupoProducto', 'SBA'],
    how='left'
)
rentabilidad_gu_sub = rentabilidad_gu_sub.groupby(
    ['TipoEmpleado', 'ClaseRentabilidad', 'Fecha', 'AreaCalculo', 'GrupoProducto', 'Division', 'Consecutivo'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})
rentabilidad_gu_sub

,TipoEmpleado,ClaseRentabilidad,Fecha,AreaCalculo,GrupoProducto,Division,Consecutivo,Real,Presupuesto
0,GU,CM2COGSP,2025-03-01,1.0,005,AE,2.0,4501.464672,14811.499208
1,GU,CM2COGSP,2025-03-01,1.0,005,AE,10.0,4501.464672,14811.499208
2,GU,CM2COGSP,2025-03-01,1.0,M07,AE,1.0,202576.228544,224715.082149
3,GU,CM2COGSP,2025-03-01,1.0,M07,AE,10.0,202576.228544,224715.082149
4,GU,CM2COGSP,2025-03-01,1.0,M08,AE,2.0,224794.428072,154505.737161
...,...,...,...,...,...,...,...,...,...
545,GU,CM2COGSP,2025-12-01,11.0,660,BA,2.0,13044.852391,-1202.908037
546,GU,CM2COGSP,2025-12-01,11.0,660,BA,10.0,14867.783907,1673.405736
547,GU,CM2COGSP,2025-12-01,11.0,A45,BA,1.0,302178.236730,72259.865957
548,GU,CM2COGSP,2025-12-01,11.0,A45,BA,2.0,26711.569993,-8291.473246
549,GU,CM2COGSP,2025-12-01,11.0,A45,BA,10.0,328889.806723,63968.392710

In [96]:
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_rentabilidad(rentabilidad_gu_sub, 'RentabilidadUnidadNegocioCM2Sub', 'CMII', 'GU')
)
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_centro_costo

Empty DataFrame
Columns: [TipoEmpleado, Fecha, AreaCalculo, Consecutivo, CodigoCentroCosto, Contexto, Real, Presupuesto, Variable]
Index: []

In [97]:
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_centro_costo[
    cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_centro_costo['Contexto'] == 'gu_2_3'
]

Empty DataFrame
Columns: [TipoEmpleado, Fecha, AreaCalculo, Consecutivo, CodigoCentroCosto, Contexto, Real, Presupuesto, Variable]
Index: []

In [98]:
dataframe_loader.validar_calculo_centro_costo(cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_centro_costo, 'gu_2_3', '2023-03-01')

(0.0, 0.0)

In [99]:
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_rentabilidad(rentabilidad_gu_sub, 'RentabilidadUnidadNegocioCM3Sub', 'CMIII', 'GU')
)
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu_centro_costo

Empty DataFrame
Columns: [TipoEmpleado, Fecha, AreaCalculo, Consecutivo, CodigoCentroCosto, Contexto, Real, Presupuesto, Variable]
Index: []

In [100]:
dataframe_loader.validar_calculo_centro_costo(cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu_centro_costo, 'gu_2_3', '2023-03-01')

(0.0, 0.0)

In [101]:
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_sub = (
    dataframe_loader.calculo_porcentaje_cumplimiento(cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_centro_costo, 'RentabilidadUnidadNegocioCM2Sub', 'GU')
)
cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_sub.head()

['TipoEmpleado', 'AreaCalculo'] ['TipoEmpleado', 'AreaCalculo']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [102]:
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu_sub = (
    dataframe_loader.calculo_porcentaje_cumplimiento(cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu_centro_costo, 'RentabilidadUnidadNegocioCM3Sub', 'GU')
)
cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu_sub.head()

['TipoEmpleado', 'AreaCalculo'] ['TipoEmpleado', 'AreaCalculo']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 10.2. Para MK (RentabilidadUnidadNegocioCM2Sub y RentabilidadUnidadNegocioCM3Sub)

In [103]:
#Calculamos la rentabilidad para MK adicionando toda la info de area_calculo_sba_completo
rentabilidad_mk_sub = df_rentabilidad.copy()
rentabilidad_mk_sub['TipoEmpleado'] = 'MK'
rentabilidad_mk_sub = rentabilidad_mk_sub.merge(
    area_calculo_sba_completo[['TipoEmpleado', 'AreaCalculo', 'GrupoProducto', 'Division', 'Consecutivo', 'SBA']],
    on=['TipoEmpleado', 'GrupoProducto', 'SBA'],
    how='left'
)
rentabilidad_mk_sub = rentabilidad_mk_sub.groupby(
    ['TipoEmpleado', 'ClaseRentabilidad', 'Fecha', 'AreaCalculo', 'GrupoProducto', 'Division','Consecutivo'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})
rentabilidad_mk_sub

,TipoEmpleado,ClaseRentabilidad,Fecha,AreaCalculo,GrupoProducto,Division,Consecutivo,Real,Presupuesto
0,MK,CM2COGSP,2025-03-01,1.0,001,AE,2.0,271989.022341,2.623649e+05
1,MK,CM2COGSP,2025-03-01,1.0,003,AE,2.0,268971.300064,1.869732e+05
2,MK,CM2COGSP,2025-03-01,1.0,005,AE,2.0,4501.464672,1.481150e+04
3,MK,CM2COGSP,2025-03-01,1.0,006,AE,2.0,17085.534920,2.584947e+04
4,MK,CM2COGSP,2025-03-01,1.0,610,HC,1.0,351909.423077,3.730089e+05
...,...,...,...,...,...,...,...,...,...
1085,MK,CM2COGSP,2025-12-01,13.0,CDK,HC,1.0,-45714.901730,2.314571e+04
1086,MK,CM2COGSP,2025-12-01,13.0,CEK,AE,2.0,237.215605,1.813254e+03
1087,MK,CM2COGSP,2025-12-01,13.0,M06,AE,2.0,715336.478661,5.186395e+05
1088,MK,CM2COGSP,2025-12-01,13.0,M07,AE,2.0,896887.985192,1.041157e+06
1089,MK,CM2COGSP,2025-12-01,13.0,M08,AE,2.0,924363.305449,7.159517e+05

In [104]:
cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_rentabilidad(rentabilidad_mk_sub, 'RentabilidadUnidadNegocioCM2Sub', 'CMII', 'MK')
)
cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk_centro_costo

Empty DataFrame
Columns: [TipoEmpleado, Fecha, AreaCalculo, Consecutivo, CodigoCentroCosto, Contexto, Real, Presupuesto, Variable]
Index: []

In [105]:
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_rentabilidad(rentabilidad_mk_sub, 'RentabilidadUnidadNegocioCM3Sub', 'CMIII', 'MK')
)
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk_centro_costo

Empty DataFrame
Columns: [TipoEmpleado, Fecha, AreaCalculo, Consecutivo, CodigoCentroCosto, Contexto, Real, Presupuesto, Variable]
Index: []

In [106]:
cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk_sub = (
    dataframe_loader.calculo_porcentaje_cumplimiento(cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk_centro_costo, 'RentabilidadUnidadNegocioCM2Sub', 'MK')
)
cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk_sub.head()

['TipoEmpleado', 'AreaCalculo'] ['TipoEmpleado', 'AreaCalculo']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [107]:
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk_sub = (
    dataframe_loader.calculo_porcentaje_cumplimiento(cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk_centro_costo, 'RentabilidadUnidadNegocioCM3Sub', 'MK')
)
cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk_sub.head()

['TipoEmpleado', 'AreaCalculo'] ['TipoEmpleado', 'AreaCalculo']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 11. Objetivos de recaudo por división (VentaCobradaDivision)

In [108]:
recaudo_real_por_division = df_venta_recaudo_real[['Division', 'Fecha', 'Recaudo']]
recaudo_real_por_division = recaudo_real_por_division.groupby(['Division', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_por_division['Real'] = recaudo_real_por_division['Recaudo']
recaudo_real_por_division.drop(columns=['Recaudo'], inplace=True)
recaudo_real_por_division

recaudo_presupuesto_por_division = df_venta_recaudo_presupuesto[['Division', 'Fecha', 'Recaudo']]
recaudo_presupuesto_por_division = recaudo_presupuesto_por_division.groupby(['Division', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_por_division['Presupuesto'] = recaudo_presupuesto_por_division['Recaudo']
recaudo_presupuesto_por_division.drop(columns=['Recaudo'], inplace=True)
recaudo_presupuesto_por_division

cumplimiento_recaudo_por_division = pd.merge(
    left=recaudo_presupuesto_por_division,
    right=recaudo_real_por_division,
    on=['Division', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_division['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_division['Real'] = cumplimiento_recaudo_por_division.groupby(['Division'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division['Presupuesto'] = cumplimiento_recaudo_por_division.groupby(['Division'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division['Real'] / cumplimiento_recaudo_por_division['Presupuesto']
cumplimiento_recaudo_por_division['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_recaudo_por_division['Contexto'] = cumplimiento_recaudo_por_division['Division']
cumplimiento_recaudo_por_division['Variable'] = 'VentaCobradaDivision'
cumplimiento_recaudo_por_division = cumplimiento_recaudo_por_division[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_recaudo_por_division.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3724790582.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_division['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,AE,VentaCobradaDivision,2025-01-01,3.286468e+09,3.853323e+09,0.85
1,AE,VentaCobradaDivision,2025-02-01,6.671904e+09,7.162054e+09,0.93
2,AE,VentaCobradaDivision,2025-03-01,9.981837e+09,1.084764e+10,0.92
3,AE,VentaCobradaDivision,2025-04-01,1.411992e+10,1.500686e+10,0.94
4,AE,VentaCobradaDivision,2025-05-01,1.762442e+10,1.955864e+10,0.90

## 12. Objetivos de recaudo por division con consecutivos (VentaCobradaDivisionSub)

In [109]:
area_calculo_sba_completo_renal_vc_gd = area_calculo_sba_completo[
    (
        (area_calculo_sba_completo['TipoEmpleado'] == 'VC') &
#         (area_calculo_sba_completo['Consecutivo'] == 1) &
        (area_calculo_sba_completo['AreaCalculo'] == 5) 
    ) 
#     |
#     (
#         (area_calculo_sba_completo['TipoEmpleado'] == 'GD') &
#         (area_calculo_sba_completo['Consecutivo'] == 5) &
#         (area_calculo_sba_completo['AreaCalculo'] == 3) 
#     )
]

area_calculo_sba_completo_renal_vc_gd

     AreaCalculo  Consecutivo Division GrupoProducto SBA TipoEmpleado
262            5            2       BA           A32               VC
263            5            2       BA           A33               VC
264            5            2       BA           A34               VC
265            5            3       HC           610               VC
266            5            3       HC           620               VC
267            5            3       HC           630               VC
268            5            3       HC           630  19           VC
269            5            3       HC           640               VC
270            5            3       HC           680               VC
271            5            3       HC           681               VC
272            5            3       HC           681  03           VC
273            5            3       HC           CDK  12           VC
274            5            4       AE                             VC
275            5            4       AE           001               VC
276            5            4       AE           003               VC
277            5            4       AE           005               VC
278            5            4       AE           006               VC
279            5            4       AE           801               VC
280            5            4       AE           805               VC
281            5            4       AE           CEK  30           VC
282            5            4       AE           CEK  35           VC
283            5            4       AE           M06               VC
284            5            4       AE           M07               VC
285            5            4       AE           M08               VC
281            5            4       AE           006  36           VC
282            5            4       AE           001  30           VC
283            5            4       AE           003  35           VC
284            5            4       AE           005  33           VC
285            5            4       AE           005  35           VC
286            5            4       AE           801  32           VC
287            5            4       AE           805  30           VC
288            5            4       AE           M06  31           VC
289            5            4       AE           M07  33           VC
290            5            4       AE           M08  33           VC
291            5            4       AE           001  32           VC
292            5            4       AE           001  33           VC
293            5            4       AE           801  30           VC
294            5            4       AE           801  33           VC
295            5            4       AE           M07  30           VC
297            5            4       AE           801  31           VC
298            5            4       AE           M06  30           VC
300            5            4       AE           M06  38           VC
301            5            4       AE           M06  32           VC
302            5            4       AE           M06  33           VC
303            5            4       AE           001  31           VC
228            5            2       BA           A32  84           VC
229            5            2       BA           A33  86           VC
230            5            2       BA           A34  85           VC
231            5            3       HC           610  01           VC
232            5            3       HC           610  02           VC
233            5            3       HC           620  36           VC
234            5            3       HC           620  13           VC
235            5            3       HC           620  15           VC
236            5            3       HC           620  16           VC
237            5            3       HC           630  08           VC
238            5            3       HC           630  12           VC
239            5            3       HC           630  03           VC
241            5            3       HC           640  03           VC
242            5            3       HC           680  03           VC

In [110]:
df_merged = area_calculo_sba_completo.merge(
    area_calculo_sba_completo_renal_vc_gd,
    how='left',
    indicator=True
).drop_duplicates()

area_calculo_sba_completo_without_renal = df_merged[df_merged['_merge'] == 'left_only']
area_calculo_sba_completo_without_renal

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,_merge
0,1,1,BBMCO,BBMCO,BBMCO,AD,left_only
1,2,1,BBMCO,BBMCO,BBMCO,AD,left_only
2,3,1,BBMCO,BBMCO,BBMCO,AD,left_only
3,4,1,BBMCO,BBMCO,BBMCO,AD,left_only
4,1,1,BBMCO,BBMCO,BBMCO,AD1,left_only
...,...,...,...,...,...,...,...
853,13,1,AE,003,35,VE,left_only
854,13,2,AE,801,32,VE,left_only
855,13,2,AE,801,30,VE,left_only
856,13,2,AE,801,33,VE,left_only
857,13,2,AE,801,31,VE,left_only

In [111]:
area_calculo_sba_completo_with_renal = df_merged[df_merged['_merge'] == 'both']
area_calculo_sba_completo_with_renal

     AreaCalculo  Consecutivo Division GrupoProducto SBA TipoEmpleado _merge
262            5            2       BA           A32               VC   both
263            5            2       BA           A33               VC   both
264            5            2       BA           A34               VC   both
265            5            3       HC           610               VC   both
266            5            3       HC           620               VC   both
267            5            3       HC           630               VC   both
268            5            3       HC           630  19           VC   both
269            5            3       HC           640               VC   both
270            5            3       HC           680               VC   both
271            5            3       HC           681               VC   both
272            5            3       HC           681  03           VC   both
273            5            3       HC           CDK  12           VC   both
274            5            4       AE                             VC   both
275            5            4       AE           001               VC   both
276            5            4       AE           003               VC   both
277            5            4       AE           005               VC   both
278            5            4       AE           006               VC   both
279            5            4       AE           801               VC   both
280            5            4       AE           805               VC   both
281            5            4       AE           CEK  30           VC   both
282            5            4       AE           CEK  35           VC   both
283            5            4       AE           M06               VC   both
284            5            4       AE           M07               VC   both
285            5            4       AE           M08               VC   both
588            5            4       AE           006  36           VC   both
589            5            4       AE           001  30           VC   both
590            5            4       AE           003  35           VC   both
591            5            4       AE           005  33           VC   both
592            5            4       AE           005  35           VC   both
593            5            4       AE           801  32           VC   both
594            5            4       AE           805  30           VC   both
595            5            4       AE           M06  31           VC   both
596            5            4       AE           M07  33           VC   both
597            5            4       AE           M08  33           VC   both
598            5            4       AE           001  32           VC   both
599            5            4       AE           001  33           VC   both
600            5            4       AE           801  30           VC   both
601            5            4       AE           801  33           VC   both
602            5            4       AE           M07  30           VC   both
603            5            4       AE           801  31           VC   both
604            5            4       AE           M06  30           VC   both
605            5            4       AE           M06  38           VC   both
606            5            4       AE           M06  32           VC   both
607            5            4       AE           M06  33           VC   both
608            5            4       AE           001  31           VC   both
805            5            2       BA           A32  84           VC   both
806            5            2       BA           A33  86           VC   both
807            5            2       BA           A34  85           VC   both
808            5            3       HC           610  01           VC   both
809            5            3       HC           610  02           VC   both
810            5            3       HC           620  36           VC   both
811            5            3       HC           620  13           VC   both
812            5            3       HC           620  15           VC   both
813            5            3       HC           620  16           VC   both
814            5            3       HC           630  08           VC   both
815            5            3       HC           630  12           VC   both
816            5            3       HC           630  03           VC   both
817            5            3       HC           640  03           VC   both
818            5            3       HC           680  03           VC   both

### 12.1. Para MK (VentaCobradaDivisionSub)

In [112]:
# def f_calculo_centro_costo_variable_division_sub(main, variable, tipo_empleado):
# #     df_area_calculo_sba_centros_costos_tipo_empleado = (
# #         df_area_calculo_sba_centros_costos[df_area_calculo_sba_centros_costos['TipoEmpleado'] == tipo_empleado]
# #     )    
    
#     main = main.merge(
#         df_centros_costos_grupos_productos_divisiones.rename(columns={'ConsecutivoParrilla':'Consecutivo'}),
#         on=['Division', 'GrupoProducto'],
#         how='left'
#     )
#     main['AreaCalculo'] = main['AreaCalculo'].astype(str)
#     main['Consecutivo'] = main['Consecutivo'].astype(str)
#     main['Contexto'] = tipo_empleado.lower() +'_'+ main['AreaCalculo'].str.cat(main['Consecutivo'],sep="_")
# #     main = main.groupby(['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
    
# #     main['Real'] = main.groupby(['Contexto', 'CentroCosto'])['Real'].transform(pd.Series.sum)
# #     main['Presupuesto'] = main.groupby(['Contexto', 'CentroCosto'])['PresupuesVentaCobradaBraunPaisto'].transform(pd.Series.sum)
    
#     main['Real'] = main.groupby(['Contexto', 'GrupoProducto', 'Division', 'CodigoCentroCosto'])['Real'].transform(pd.Series.cumsum)
#     main['Presupuesto'] = main.groupby(['Contexto', 'GrupoProducto', 'Division', 'CodigoCentroCosto'])['Presupuesto'].transform(pd.Series.cumsum)
#     main['Variable'] = variable
#     return main

In [113]:
cumplimiento_recaudo_por_division_sub_mk = pd.merge(
    left=recaudo_presupuesto_area_calculo_mk_sub,
    right=recaudo_real_area_calculo_mk_sub,
    on=['AreaCalculo', 'Consecutivo', 'Fecha', 'Division', 'GrupoProducto'],
    how='left'
)
cumplimiento_recaudo_por_division_sub_mk['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_division_sub_mk

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\829374068.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_division_sub_mk['Real'].fillna(0.0, inplace=True)

,AreaCalculo,Division,GrupoProducto,Consecutivo,Fecha,Presupuesto,Real
0,1,AE,001,2,2025-01-01,7.543752e+08,3.574246e+08
1,1,AE,001,2,2025-02-01,5.032218e+08,5.624941e+08
2,1,AE,001,2,2025-03-01,5.032978e+08,3.211215e+08
3,1,AE,001,2,2025-04-01,7.546800e+08,4.399869e+08
4,1,AE,001,2,2025-05-01,5.873965e+08,3.501197e+08
...,...,...,...,...,...,...,...
1303,13,HC,CDK,1,2025-08-01,2.234171e+07,0.000000e+00
1304,13,HC,CDK,1,2025-09-01,2.087186e+07,2.800000e+06
1305,13,HC,CDK,1,2025-10-01,2.469347e+07,3.230000e+05
1306,13,HC,CDK,1,2025-11-01,2.145980e+07,0.000000e+00
1307,13,HC,CDK,1,2025-12-01,2.322362e+07,2.660000e+05

In [114]:
cumplimiento_recaudo_por_division_sub_mk_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_division_sub(cumplimiento_recaudo_por_division_sub_mk, 'VentaCobradaDivisionSub', 'MK')
)
cumplimiento_recaudo_por_division_sub_mk_centro_costo

,AreaCalculo,Division,GrupoProducto,Consecutivo,Fecha,Presupuesto,Real,CodigoCentroCosto,Contexto,Variable
0,1,AE,001,2,2025-01-01,7.543752e+08,3.574246e+08,323007270,mk_1_2,VentaCobradaDivisionSub
1,1,AE,001,2,2025-02-01,1.257597e+09,9.199187e+08,323007270,mk_1_2,VentaCobradaDivisionSub
2,1,AE,001,2,2025-03-01,1.760895e+09,1.241040e+09,323007270,mk_1_2,VentaCobradaDivisionSub
3,1,AE,001,2,2025-04-01,2.515575e+09,1.681027e+09,323007270,mk_1_2,VentaCobradaDivisionSub
4,1,AE,001,2,2025-05-01,3.102971e+09,2.031147e+09,323007270,mk_1_2,VentaCobradaDivisionSub
...,...,...,...,...,...,...,...,...,...,...
1303,13,HC,CDK,1,2025-08-01,1.747220e+08,0.000000e+00,323015050,mk_13_1,VentaCobradaDivisionSub
1304,13,HC,CDK,1,2025-09-01,1.955939e+08,2.800000e+06,323015050,mk_13_1,VentaCobradaDivisionSub
1305,13,HC,CDK,1,2025-10-01,2.202873e+08,3.123000e+06,323015050,mk_13_1,VentaCobradaDivisionSub
1306,13,HC,CDK,1,2025-11-01,2.417471e+08,3.123000e+06,323015050,mk_13_1,VentaCobradaDivisionSub
1307,13,HC,CDK,1,2025-12-01,2.649708e+08,3.389000e+06,323015050,mk_13_1,VentaCobradaDivisionSub

In [115]:
cumplimiento_recaudo_por_division_sub_mk_centro_costo[
    (cumplimiento_recaudo_por_division_sub_mk_centro_costo['Contexto'] == 'mk_9_3') &
    (cumplimiento_recaudo_por_division_sub_mk_centro_costo['Fecha'] == '2023-09-01')
]

Empty DataFrame
Columns: [AreaCalculo, Division, GrupoProducto, Consecutivo, Fecha, Presupuesto, Real, CodigoCentroCosto, Contexto, Variable]
Index: []

In [116]:
cumplimiento_recaudo_por_division_sub_mk_centro_costo[
    (cumplimiento_recaudo_por_division_sub_mk_centro_costo['Contexto'] == 'mk_9_3') &
    (cumplimiento_recaudo_por_division_sub_mk_centro_costo['Fecha'] == '2023-01-01')
].groupby(['AreaCalculo', 'Consecutivo', 'Variable'])['Real'].transform(pd.Series.cumsum)

Series([], Name: Real, dtype: float64)

In [117]:
cumplimiento_recaudo_por_division_sub_mk_centro_costo[
    (cumplimiento_recaudo_por_division_sub_mk_centro_costo['Contexto'] == 'mk_1_2') &
    (cumplimiento_recaudo_por_division_sub_mk_centro_costo['Fecha'] == '2023-01-01')
].groupby(['AreaCalculo', 'Consecutivo', 'Variable'])['Presupuesto'].transform(pd.Series.cumsum)

Series([], Name: Presupuesto, dtype: float64)

In [118]:
dataframe_loader.validar_calculo_centro_costo_division_sub(cumplimiento_recaudo_por_division_sub_mk_centro_costo, 'mk_1_2', '2023-01-01')

(Series([], Name: Real, dtype: float64),
 Series([], Name: Presupuesto, dtype: float64))

In [119]:
dataframe_loader.validar_calculo_centro_costo(cumplimiento_recaudo_por_division_sub_mk_centro_costo, 'mk_9_3', '2023-01-01')

(0.0, 0.0)

In [120]:
cumplimiento_recaudo_por_division_sub_mk = cumplimiento_recaudo_por_division_sub_mk.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
cumplimiento_recaudo_por_division_sub_mk['Real'] = cumplimiento_recaudo_por_division_sub_mk.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_mk['Presupuesto'] = cumplimiento_recaudo_por_division_sub_mk.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_mk['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_mk['Real'] / cumplimiento_recaudo_por_division_sub_mk['Presupuesto']
cumplimiento_recaudo_por_division_sub_mk['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_mk['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_division_sub_mk['Variable'] = 'VentaCobradaDivisionSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_division_sub_mk = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_division_sub_mk,
    variable='VentaCobradaDivisionSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'MK'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_recaudo_por_division_sub_mk['Contexto'] = 'mk_' + cumplimiento_recaudo_por_division_sub_mk['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_por_division_sub_mk['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_por_division_sub_mk = cumplimiento_recaudo_por_division_sub_mk[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_por_division_sub_mk.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1428136897.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  cumplimiento_recaudo_por_division_sub_mk = cumplimiento_recaudo_por_division_sub_mk.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,mk_1_1,VentaCobradaDivisionSub,2025-01-01,1.291859e+10,1.392163e+10,0.93
1,mk_1_1,VentaCobradaDivisionSub,2025-02-01,2.556295e+10,2.752997e+10,0.93
2,mk_1_1,VentaCobradaDivisionSub,2025-03-01,3.850128e+10,4.321841e+10,0.89
3,mk_1_1,VentaCobradaDivisionSub,2025-04-01,5.364112e+10,5.674368e+10,0.95
4,mk_1_1,VentaCobradaDivisionSub,2025-05-01,6.790122e+10,7.132300e+10,0.95

In [121]:
cumplimiento_recaudo_por_division_sub_mk[
    (cumplimiento_recaudo_por_division_sub_mk['Contexto'] == 'mk_9_3') &
    (cumplimiento_recaudo_por_division_sub_mk['Fecha'] == '2023-01-01')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [122]:
cumplimiento_recaudo_por_division_sub_mk[
    (cumplimiento_recaudo_por_division_sub_mk['Contexto'] == 'mk_9_1') &
    (cumplimiento_recaudo_por_division_sub_mk['Fecha'] == '2023-01-01')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [123]:
cumplimiento_recaudo_por_division_sub_mk[
    (cumplimiento_recaudo_por_division_sub_mk['Contexto'] == 'mk_7_3') &
    (cumplimiento_recaudo_por_division_sub_mk['Fecha'] == '2023-01-01')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [124]:
cumplimiento_recaudo_por_division_sub_mk[
    (cumplimiento_recaudo_por_division_sub_mk['Contexto'].str.contains('mk_1_1')) &
    (cumplimiento_recaudo_por_division_sub_mk['Fecha'] == '2023-01-01')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [125]:
cumplimiento_recaudo_otras_companias_mk = pd.merge(
    left=area_calculo_sba_completo_mk,
    right=df_recaudo_otras_companias.rename(columns={'Compania': 'Division'}),
    on=['Division']
)
cumplimiento_recaudo_otras_companias_mk['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_mk['Real']/cumplimiento_recaudo_otras_companias_mk['Presupuesto']
cumplimiento_recaudo_otras_companias_mk['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_mk['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_otras_companias_mk['Variable'] = 'VentaCobradaDivisionSub'
cumplimiento_recaudo_otras_companias_mk['Contexto'] = 'mk_' + cumplimiento_recaudo_otras_companias_mk['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_otras_companias_mk['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_otras_companias_mk = cumplimiento_recaudo_otras_companias_mk[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_otras_companias_mk.head()

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 12.2. Para GD (VentaCobradaDivisionSub)

#### Cálculo sin Renal Ambulatorio

In [126]:
# area_calculo_sba_completo_gd = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='GD']
area_calculo_sba_completo_gd = area_calculo_sba_completo_without_renal[area_calculo_sba_completo_without_renal['TipoEmpleado']=='GD']
area_calculo_sba_completo_gd

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,_merge
29,1,1,AE,001,,GD,left_only
30,1,1,AE,003,,GD,left_only
31,1,1,AE,005,,GD,left_only
32,1,1,AE,006,,GD,left_only
33,1,1,AE,801,,GD,left_only
...,...,...,...,...,...,...,...
647,3,1,BA,A34,85,GD,left_only
648,3,1,BA,A35,87,GD,left_only
649,3,1,BA,A45,80,GD,left_only
650,3,1,BA,A45,81,GD,left_only
651,3,1,BA,A45,89,GD,left_only

In [127]:
#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los GD
venta_recaudo_presupuesto_original_gd_real = area_calculo_sba_completo_gd.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los GD
venta_recaudo_presupuesto_original_gd_presupuesto = area_calculo_sba_completo_gd.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

venta_recaudo_real_area_calculo_gd = venta_recaudo_presupuesto_original_gd_real.groupby(['AreaCalculo', 'Consecutivo', 'GrupoProducto', 'Division', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_real_area_calculo_gd['Real'] = venta_recaudo_real_area_calculo_gd['Recaudo']
venta_recaudo_real_area_calculo_gd.drop(columns=['Recaudo'], inplace=True)

venta_recaudo_presupuesto_area_calculo_gd = venta_recaudo_presupuesto_original_gd_presupuesto.groupby(['AreaCalculo', 'Consecutivo', 'GrupoProducto', 'Division', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_presupuesto_area_calculo_gd['Presupuesto'] = venta_recaudo_presupuesto_area_calculo_gd['Recaudo']
venta_recaudo_presupuesto_area_calculo_gd.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_division_sub_gd = pd.merge(
    left=venta_recaudo_presupuesto_area_calculo_gd,
    right=venta_recaudo_real_area_calculo_gd,
    on=['AreaCalculo', 'Consecutivo', 'GrupoProducto', 'Division', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_division_sub_gd

,AreaCalculo,Consecutivo,GrupoProducto,Division,Fecha,Presupuesto,Real
0,1,1,001,AE,2025-01-01,7.543752e+08,3.574246e+08
1,1,1,001,AE,2025-02-01,5.032218e+08,5.624941e+08
2,1,1,001,AE,2025-03-01,5.032978e+08,3.211215e+08
3,1,1,001,AE,2025-04-01,7.546800e+08,4.399869e+08
4,1,1,001,AE,2025-05-01,5.873965e+08,3.501197e+08
...,...,...,...,...,...,...,...
259,3,1,A45,BA,2025-08-01,2.668447e+08,7.526897e+07
260,3,1,A45,BA,2025-09-01,3.029335e+08,8.766827e+08
261,3,1,A45,BA,2025-10-01,3.608876e+08,5.714674e+07
262,3,1,A45,BA,2025-11-01,4.767959e+08,3.288963e+07
263,3,1,A45,BA,2025-12-01,5.057730e+08,5.726536e+09

In [128]:
cumplimiento_recaudo_por_division_sub_gd_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_division_sub(cumplimiento_recaudo_por_division_sub_gd, 'VentaCobradaDivisionSub', 'GD')
)
cumplimiento_recaudo_por_division_sub_gd_centro_costo

,AreaCalculo,Consecutivo,GrupoProducto,Division,Fecha,Presupuesto,Real,CodigoCentroCosto,Contexto,Variable
0,1,1,001,AE,2025-01-01,7.543752e+08,3.574246e+08,323007270,gd_1_1,VentaCobradaDivisionSub
1,1,1,001,AE,2025-02-01,1.257597e+09,9.199187e+08,323007270,gd_1_1,VentaCobradaDivisionSub
2,1,1,001,AE,2025-03-01,1.760895e+09,1.241040e+09,323007270,gd_1_1,VentaCobradaDivisionSub
3,1,1,001,AE,2025-04-01,2.515575e+09,1.681027e+09,323007270,gd_1_1,VentaCobradaDivisionSub
4,1,1,001,AE,2025-05-01,3.102971e+09,2.031147e+09,323007270,gd_1_1,VentaCobradaDivisionSub
...,...,...,...,...,...,...,...,...,...,...
259,3,1,A45,BA,2025-08-01,5.124669e+09,4.132125e+09,323007337,gd_3_1,VentaCobradaDivisionSub
260,3,1,A45,BA,2025-09-01,5.427603e+09,5.008807e+09,323007337,gd_3_1,VentaCobradaDivisionSub
261,3,1,A45,BA,2025-10-01,5.788491e+09,5.065954e+09,323007337,gd_3_1,VentaCobradaDivisionSub
262,3,1,A45,BA,2025-11-01,6.265286e+09,5.098844e+09,323007337,gd_3_1,VentaCobradaDivisionSub
263,3,1,A45,BA,2025-12-01,6.771059e+09,1.082538e+10,323007337,gd_3_1,VentaCobradaDivisionSub

In [129]:
cumplimiento_recaudo_por_division_sub_gd = cumplimiento_recaudo_por_division_sub_gd.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
cumplimiento_recaudo_por_division_sub_gd['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_division_sub_gd['Real'] = cumplimiento_recaudo_por_division_sub_gd.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_gd['Presupuesto'] = cumplimiento_recaudo_por_division_sub_gd.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_gd['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_gd['Real'] / cumplimiento_recaudo_por_division_sub_gd['Presupuesto']
cumplimiento_recaudo_por_division_sub_gd['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_gd['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_division_sub_gd['Variable'] = 'VentaCobradaDivisionSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_division_sub_gd = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_division_sub_gd,
    variable='VentaCobradaDivisionSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'GD'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_recaudo_por_division_sub_gd['Contexto'] = 'gd_' + cumplimiento_recaudo_por_division_sub_gd['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_por_division_sub_gd['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_por_division_sub_gd = cumplimiento_recaudo_por_division_sub_gd[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_recaudo_por_division_sub_gd

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\998700009.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  cumplimiento_recaudo_por_division_sub_gd = cumplimiento_recaudo_por_division_sub_gd.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\998700009.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_division_sub_gd['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,gd_1_1,VentaCobradaDivisionSub,2025-01-01,3.286468e+09,3.853323e+09,0.85
1,gd_1_1,VentaCobradaDivisionSub,2025-02-01,6.671904e+09,7.162054e+09,0.93
2,gd_1_1,VentaCobradaDivisionSub,2025-03-01,9.981837e+09,1.084764e+10,0.92
3,gd_1_1,VentaCobradaDivisionSub,2025-04-01,1.411992e+10,1.500686e+10,0.94
4,gd_1_1,VentaCobradaDivisionSub,2025-05-01,1.762442e+10,1.955864e+10,0.90
5,gd_1_1,VentaCobradaDivisionSub,2025-06-01,2.179921e+10,2.447362e+10,0.89
6,gd_1_1,VentaCobradaDivisionSub,2025-07-01,2.646950e+10,2.965432e+10,0.89
7,gd_1_1,VentaCobradaDivisionSub,2025-08-01,3.077775e+10,3.427203e+10,0.90
8,gd_1_1,VentaCobradaDivisionSub,2025-09-01,3.879063e+10,3.965757e+10,0.98
9,gd_1_1,VentaCobradaDivisionSub,2025-10-01,4.242338e+10,4.499215e+10,0.94
10,gd_1_1,VentaCobradaDivisionSub,2025-11-01,4.573681e+10,4.998581e+10,0.91
11,gd_1_1,VentaCobradaDivisionSub,2025-12-01,5.291875e+10,5.570592e+10,0.95
12,gd_2_1,VentaCobradaDivisionSub,2025-01-01,1.291859e+10,1.392163e+10,0.93
13,gd_2_1,VentaCobradaDivisionSub,2025-02-01,2.556295e+10,2.752997e+10,0.93
14,gd_2_1,VentaCobradaDivisionSub,2025-03-01,3.850128e+10,4.321841e+10,0.89
15,gd_2_1,VentaCobradaDivisionSub,2025-04-01,5.364112e+10,5.674368e+10,0.95
16,gd_2_1,VentaCobradaDivisionSub,2025-05-01,6.790122e+10,7.132300e+10,0.95
17,gd_2_1,VentaCobradaDivisionSub,2025-06-01,7.981162e+10,8.626182e+10,0.93
18,gd_2_1,VentaCobradaDivisionSub,2025-07-01,9.479664e+10,9.906560e+10,0.96
19,gd_2_1,VentaCobradaDivisionSub,2025-08-01,1.056580e+11,1.162685e+11,0.91
20,gd_2_1,VentaCobradaDivisionSub,2025-09-01,1.214694e+11,1.328964e+11,0.91
21,gd_2_1,VentaCobradaDivisionSub,2025-10-01,1.359210e+11,1.487993e+11,0.91
22,gd_2_1,VentaCobradaDivisionSub,2025-11-01,1.480051e+11,1.648716e+11,0.90
23,gd_2_1,VentaCobradaDivisionSub,2025-12-01,1.615097e+11,1.809283e+11,0.89
24,gd_3_1,VentaCobradaDivisionSub,2025-01-01,3.822781e+09,4.110669e+09,0.93
25,gd_3_1,VentaCobradaDivisionSub,2025-02-01,4.507497e+09,5.085179e+09,0.89
26,gd_3_1,VentaCobradaDivisionSub,2025-03-01,5.656312e+09,6.003690e+09,0.94
27,gd_3_1,VentaCobradaDivisionSub,2025-04-01,7.281850e+09,6.980327e+09,1.04
28,gd_3_1,VentaCobradaDivisionSub,2025-05-01,8.042917e+09,7.945719e+09,1.01
29,gd_3_1,VentaCobradaDivisionSub,2025-06-01,8.756932e+09,9.170365e+09,0.95
30,gd_3_1,VentaCobradaDivisionSub,2025-07-01,9.784031e+09,1.028792e+10,0.95
31,gd_3_1,VentaCobradaDivisionSub,2025-08-01,1.057927e+10,1.151257e+10,0.92
32,gd_3_1,VentaCobradaDivisionSub,2025-09-01,1.272285e+10,1.283578e+10,0.99
33,gd_3_1,VentaCobradaDivisionSub,2025-10-01,1.377856e+10,1.421407e+10,0.97
34,gd_3_1,VentaCobradaDivisionSub,2025-11-01,1.459824e+10,1.574790e+10,0.93
35,gd_3_1,VentaCobradaDivisionSub,2025-12-01,2.141227e+10,1.731330e+10,1.24

#### Cálculo con Renal Ambulatorio

In [130]:
area_calculo_sba_completo_gd_with_renal = area_calculo_sba_completo_with_renal[area_calculo_sba_completo_with_renal['TipoEmpleado']=='GD']
area_calculo_sba_completo_gd_with_renal

Empty DataFrame
Columns: [AreaCalculo, Consecutivo, Division, GrupoProducto, SBA, TipoEmpleado, _merge]
Index: []

In [131]:
df_renal_ambulatorio_gd = df_renal_ambulatorio[df_renal_ambulatorio['TipoEmpleado'] == 'GD']
df_renal_ambulatorio_gd

Empty DataFrame
Columns: [CodigoEmpleado, TipoEmpleado, Fecha, PlanVentaTotal, PlanVentaCobradaRenal, RealVentaTotal, RealVentaCobradaRenal]
Index: []

In [132]:
area_calculo_sba_completo_gd_with_renal

Empty DataFrame
Columns: [AreaCalculo, Consecutivo, Division, GrupoProducto, SBA, TipoEmpleado, _merge]
Index: []

In [133]:
renal_ambulatorio_gd = df_renal_ambulatorio_gd.merge(
    area_calculo_sba_completo_gd_with_renal,
    on=['TipoEmpleado'],
    how='left'
)
renal_ambulatorio_gd

Empty DataFrame
Columns: [CodigoEmpleado, TipoEmpleado, Fecha, PlanVentaTotal, PlanVentaCobradaRenal, RealVentaTotal, RealVentaCobradaRenal, AreaCalculo, Consecutivo, Division, GrupoProducto, SBA, _merge]
Index: []

In [134]:
# Calcular

main = renal_ambulatorio_gd.rename(columns={'PlanVentaCobradaRenal': 'Presupuesto', 'RealVentaCobradaRenal': 'Real'})

main['Contexto'] = 'gd_' + main['AreaCalculo'].astype('str').str.cat(main['Consecutivo'].astype('str'), sep="_")

# main['Contexto'] = main['CodigoEmpleado']

main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaDivisionSub'


#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real','Presupuesto', 'PorcentajeCumplimiento']]


cumplimiento_recaudo_por_division_sub_gd = pd.concat(
    [
        cumplimiento_recaudo_por_division_sub_gd.copy(),
        main.copy()
    ],
    ignore_index=True
)


main = None
cumplimiento_recaudo_por_division_sub_gd

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3903121203.py:9: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,gd_1_1,VentaCobradaDivisionSub,2025-01-01,3.286468e+09,3.853323e+09,0.85
1,gd_1_1,VentaCobradaDivisionSub,2025-02-01,6.671904e+09,7.162054e+09,0.93
2,gd_1_1,VentaCobradaDivisionSub,2025-03-01,9.981837e+09,1.084764e+10,0.92
3,gd_1_1,VentaCobradaDivisionSub,2025-04-01,1.411992e+10,1.500686e+10,0.94
4,gd_1_1,VentaCobradaDivisionSub,2025-05-01,1.762442e+10,1.955864e+10,0.90
5,gd_1_1,VentaCobradaDivisionSub,2025-06-01,2.179921e+10,2.447362e+10,0.89
6,gd_1_1,VentaCobradaDivisionSub,2025-07-01,2.646950e+10,2.965432e+10,0.89
7,gd_1_1,VentaCobradaDivisionSub,2025-08-01,3.077775e+10,3.427203e+10,0.90
8,gd_1_1,VentaCobradaDivisionSub,2025-09-01,3.879063e+10,3.965757e+10,0.98
9,gd_1_1,VentaCobradaDivisionSub,2025-10-01,4.242338e+10,4.499215e+10,0.94
10,gd_1_1,VentaCobradaDivisionSub,2025-11-01,4.573681e+10,4.998581e+10,0.91
11,gd_1_1,VentaCobradaDivisionSub,2025-12-01,5.291875e+10,5.570592e+10,0.95
12,gd_2_1,VentaCobradaDivisionSub,2025-01-01,1.291859e+10,1.392163e+10,0.93
13,gd_2_1,VentaCobradaDivisionSub,2025-02-01,2.556295e+10,2.752997e+10,0.93
14,gd_2_1,VentaCobradaDivisionSub,2025-03-01,3.850128e+10,4.321841e+10,0.89
15,gd_2_1,VentaCobradaDivisionSub,2025-04-01,5.364112e+10,5.674368e+10,0.95
16,gd_2_1,VentaCobradaDivisionSub,2025-05-01,6.790122e+10,7.132300e+10,0.95
17,gd_2_1,VentaCobradaDivisionSub,2025-06-01,7.981162e+10,8.626182e+10,0.93
18,gd_2_1,VentaCobradaDivisionSub,2025-07-01,9.479664e+10,9.906560e+10,0.96
19,gd_2_1,VentaCobradaDivisionSub,2025-08-01,1.056580e+11,1.162685e+11,0.91
20,gd_2_1,VentaCobradaDivisionSub,2025-09-01,1.214694e+11,1.328964e+11,0.91
21,gd_2_1,VentaCobradaDivisionSub,2025-10-01,1.359210e+11,1.487993e+11,0.91
22,gd_2_1,VentaCobradaDivisionSub,2025-11-01,1.480051e+11,1.648716e+11,0.90
23,gd_2_1,VentaCobradaDivisionSub,2025-12-01,1.615097e+11,1.809283e+11,0.89
24,gd_3_1,VentaCobradaDivisionSub,2025-01-01,3.822781e+09,4.110669e+09,0.93
25,gd_3_1,VentaCobradaDivisionSub,2025-02-01,4.507497e+09,5.085179e+09,0.89
26,gd_3_1,VentaCobradaDivisionSub,2025-03-01,5.656312e+09,6.003690e+09,0.94
27,gd_3_1,VentaCobradaDivisionSub,2025-04-01,7.281850e+09,6.980327e+09,1.04
28,gd_3_1,VentaCobradaDivisionSub,2025-05-01,8.042917e+09,7.945719e+09,1.01
29,gd_3_1,VentaCobradaDivisionSub,2025-06-01,8.756932e+09,9.170365e+09,0.95
30,gd_3_1,VentaCobradaDivisionSub,2025-07-01,9.784031e+09,1.028792e+10,0.95
31,gd_3_1,VentaCobradaDivisionSub,2025-08-01,1.057927e+10,1.151257e+10,0.92
32,gd_3_1,VentaCobradaDivisionSub,2025-09-01,1.272285e+10,1.283578e+10,0.99
33,gd_3_1,VentaCobradaDivisionSub,2025-10-01,1.377856e+10,1.421407e+10,0.97
34,gd_3_1,VentaCobradaDivisionSub,2025-11-01,1.459824e+10,1.574790e+10,0.93
35,gd_3_1,VentaCobradaDivisionSub,2025-12-01,2.141227e+10,1.731330e+10,1.24

### 12.2.1 Para GD (VentaFacturadaDivisionSub)

In [135]:
#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los GD
venta_facturada_presupuesto_original_gd_real = area_calculo_sba_completo_gd.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los GD
venta_facturada_presupuesto_original_gd_presupuesto = area_calculo_sba_completo_gd.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

venta_facturada_real_area_calculo_gd = venta_facturada_presupuesto_original_gd_real.groupby(['AreaCalculo', 'Consecutivo', 'GrupoProducto', 'Division', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_facturada_real_area_calculo_gd['Real'] = venta_facturada_real_area_calculo_gd['Venta']
venta_facturada_real_area_calculo_gd.drop(columns=['Venta'], inplace=True)

venta_facturada_presupuesto_area_calculo_gd = venta_facturada_presupuesto_original_gd_presupuesto.groupby(['AreaCalculo', 'Consecutivo', 'GrupoProducto', 'Division', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_facturada_presupuesto_area_calculo_gd['Presupuesto'] = venta_facturada_presupuesto_area_calculo_gd['Venta']
venta_facturada_presupuesto_area_calculo_gd.drop(columns=['Venta'], inplace=True)

cumplimiento_facturada_por_division_sub_gd = pd.merge(
    left=venta_facturada_presupuesto_area_calculo_gd,
    right=venta_facturada_real_area_calculo_gd,
    on=['AreaCalculo', 'Consecutivo', 'GrupoProducto', 'Division', 'Fecha'],
    how='left'
)
cumplimiento_facturada_por_division_sub_gd

,AreaCalculo,Consecutivo,GrupoProducto,Division,Fecha,Presupuesto,Real
0,1,1,001,AE,2025-01-01,5.391608e+08,1.781555e+08
1,1,1,001,AE,2025-02-01,7.190397e+08,6.725782e+08
2,1,1,001,AE,2025-03-01,7.188944e+08,8.261027e+08
3,1,1,001,AE,2025-04-01,7.187163e+08,3.132514e+08
4,1,1,001,AE,2025-05-01,7.187998e+08,2.112630e+08
...,...,...,...,...,...,...,...
259,3,1,A45,BA,2025-08-01,2.853289e+08,1.299656e+08
260,3,1,A45,BA,2025-09-01,3.170321e+08,1.078942e+08
261,3,1,A45,BA,2025-10-01,2.345524e+09,6.983301e+07
262,3,1,A45,BA,2025-11-01,3.170321e+08,1.935415e+09
263,3,1,A45,BA,2025-12-01,3.170321e+08,4.116435e+09

In [136]:
cumplimiento_facturada_por_division_sub_gd_centro_costo = (
    dataframe_loader.f_calculo_centro_costo_variable_division_sub(cumplimiento_facturada_por_division_sub_gd, 'VentaFacturadaDivisionSub', 'GD')
)
cumplimiento_facturada_por_division_sub_gd_centro_costo

,AreaCalculo,Consecutivo,GrupoProducto,Division,Fecha,Presupuesto,Real,CodigoCentroCosto,Contexto,Variable
0,1,1,001,AE,2025-01-01,5.391608e+08,1.781555e+08,323007270,gd_1_1,VentaFacturadaDivisionSub
1,1,1,001,AE,2025-02-01,1.258201e+09,8.507337e+08,323007270,gd_1_1,VentaFacturadaDivisionSub
2,1,1,001,AE,2025-03-01,1.977095e+09,1.676836e+09,323007270,gd_1_1,VentaFacturadaDivisionSub
3,1,1,001,AE,2025-04-01,2.695811e+09,1.990088e+09,323007270,gd_1_1,VentaFacturadaDivisionSub
4,1,1,001,AE,2025-05-01,3.414611e+09,2.201351e+09,323007270,gd_1_1,VentaFacturadaDivisionSub
...,...,...,...,...,...,...,...,...,...,...
259,3,1,A45,BA,2025-08-01,1.902193e+09,1.452145e+09,323007337,gd_3_1,VentaFacturadaDivisionSub
260,3,1,A45,BA,2025-09-01,2.219225e+09,1.560039e+09,323007337,gd_3_1,VentaFacturadaDivisionSub
261,3,1,A45,BA,2025-10-01,4.564748e+09,1.629872e+09,323007337,gd_3_1,VentaFacturadaDivisionSub
262,3,1,A45,BA,2025-11-01,4.881780e+09,3.565287e+09,323007337,gd_3_1,VentaFacturadaDivisionSub
263,3,1,A45,BA,2025-12-01,5.198813e+09,7.681721e+09,323007337,gd_3_1,VentaFacturadaDivisionSub

In [137]:
cumplimiento_facturada_por_division_sub_gd = cumplimiento_facturada_por_division_sub_gd.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
cumplimiento_facturada_por_division_sub_gd['Real'].fillna(0.0, inplace=True)
cumplimiento_facturada_por_division_sub_gd['Real'] = cumplimiento_facturada_por_division_sub_gd.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_facturada_por_division_sub_gd['Presupuesto'] = cumplimiento_facturada_por_division_sub_gd.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_facturada_por_division_sub_gd['PorcentajeCumplimiento'] = cumplimiento_facturada_por_division_sub_gd['Real'] / cumplimiento_facturada_por_division_sub_gd['Presupuesto']
cumplimiento_facturada_por_division_sub_gd['PorcentajeCumplimiento'] = cumplimiento_facturada_por_division_sub_gd['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_facturada_por_division_sub_gd['Variable'] = 'VentaFacturadaDivisionSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_facturada_por_division_sub_gd = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_facturada_por_division_sub_gd,
    variable='VentaCobradaDivisionSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'GD'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_facturada_por_division_sub_gd['Contexto'] = 'gd_' + cumplimiento_facturada_por_division_sub_gd['AreaCalculo'].astype('str').str.cat(cumplimiento_facturada_por_division_sub_gd['Consecutivo'].astype('str'), sep="_")
cumplimiento_facturada_por_division_sub_gd = cumplimiento_facturada_por_division_sub_gd[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_facturada_por_division_sub_gd

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2877296655.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  cumplimiento_facturada_por_division_sub_gd = cumplimiento_facturada_por_division_sub_gd.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2877296655.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_facturada_por_division_sub_gd['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,gd_1_1,VentaFacturadaDivisionSub,2025-01-01,1.990748e+09,3.416483e+09,0.58
1,gd_1_1,VentaFacturadaDivisionSub,2025-02-01,6.337019e+09,7.884560e+09,0.80
2,gd_1_1,VentaFacturadaDivisionSub,2025-03-01,1.123332e+10,1.255015e+10,0.90
3,gd_1_1,VentaFacturadaDivisionSub,2025-04-01,1.450837e+10,1.681820e+10,0.86
4,gd_1_1,VentaFacturadaDivisionSub,2025-05-01,1.856383e+10,2.157921e+10,0.86
5,gd_1_1,VentaFacturadaDivisionSub,2025-06-01,2.286273e+10,2.640335e+10,0.87
6,gd_1_1,VentaFacturadaDivisionSub,2025-07-01,2.874202e+10,3.319362e+10,0.87
7,gd_1_1,VentaFacturadaDivisionSub,2025-08-01,3.614296e+10,3.836558e+10,0.94
8,gd_1_1,VentaFacturadaDivisionSub,2025-09-01,4.076320e+10,4.332131e+10,0.94
9,gd_1_1,VentaFacturadaDivisionSub,2025-10-01,4.589136e+10,4.819050e+10,0.95
10,gd_1_1,VentaFacturadaDivisionSub,2025-11-01,4.993653e+10,5.360480e+10,0.93
11,gd_1_1,VentaFacturadaDivisionSub,2025-12-01,5.851357e+10,5.886926e+10,0.99
12,gd_2_1,VentaFacturadaDivisionSub,2025-01-01,6.320170e+09,1.053002e+10,0.60
13,gd_2_1,VentaFacturadaDivisionSub,2025-02-01,1.828696e+10,2.373706e+10,0.77
14,gd_2_1,VentaFacturadaDivisionSub,2025-03-01,3.055086e+10,3.886306e+10,0.79
15,gd_2_1,VentaFacturadaDivisionSub,2025-04-01,4.408188e+10,5.105676e+10,0.86
16,gd_2_1,VentaFacturadaDivisionSub,2025-05-01,6.114383e+10,6.681502e+10,0.92
17,gd_2_1,VentaFacturadaDivisionSub,2025-06-01,7.543283e+10,8.303865e+10,0.91
18,gd_2_1,VentaFacturadaDivisionSub,2025-07-01,8.983765e+10,9.856748e+10,0.91
19,gd_2_1,VentaFacturadaDivisionSub,2025-08-01,1.023506e+11,1.149217e+11,0.89
20,gd_2_1,VentaFacturadaDivisionSub,2025-09-01,1.161054e+11,1.311605e+11,0.89
21,gd_2_1,VentaFacturadaDivisionSub,2025-10-01,1.297584e+11,1.471943e+11,0.88
22,gd_2_1,VentaFacturadaDivisionSub,2025-11-01,1.460295e+11,1.656389e+11,0.88
23,gd_2_1,VentaFacturadaDivisionSub,2025-12-01,1.653977e+11,1.862389e+11,0.89
24,gd_3_1,VentaFacturadaDivisionSub,2025-01-01,2.657226e+08,8.209922e+08,0.32
25,gd_3_1,VentaFacturadaDivisionSub,2025-02-01,1.168345e+09,1.702112e+09,0.69
26,gd_3_1,VentaFacturadaDivisionSub,2025-03-01,1.953258e+09,2.840755e+09,0.69
27,gd_3_1,VentaFacturadaDivisionSub,2025-04-01,2.826198e+09,3.882762e+09,0.73
28,gd_3_1,VentaFacturadaDivisionSub,2025-05-01,3.854155e+09,5.066534e+09,0.76
29,gd_3_1,VentaFacturadaDivisionSub,2025-06-01,5.610251e+09,6.311307e+09,0.89
30,gd_3_1,VentaFacturadaDivisionSub,2025-07-01,6.790102e+09,7.606394e+09,0.89
31,gd_3_1,VentaFacturadaDivisionSub,2025-08-01,7.989532e+09,8.903881e+09,0.90
32,gd_3_1,VentaFacturadaDivisionSub,2025-09-01,8.919414e+09,1.026408e+10,0.87
33,gd_3_1,VentaFacturadaDivisionSub,2025-10-01,9.978181e+09,1.387548e+10,0.72
34,gd_3_1,VentaFacturadaDivisionSub,2025-11-01,1.306009e+10,1.527698e+10,0.85
35,gd_3_1,VentaFacturadaDivisionSub,2025-12-01,1.850531e+10,1.662642e+10,1.11

In [138]:
cumplimiento_facturada_otras_companias_gd = pd.merge(
    left=area_calculo_sba_completo_gd,
    right=df_recaudo_otras_companias.rename(columns={'Compania': 'Division'}),
    on=['Division']
)
cumplimiento_facturada_otras_companias_gd['PorcentajeCumplimiento'] = cumplimiento_facturada_otras_companias_gd['Real']/cumplimiento_facturada_otras_companias_gd['Presupuesto']
cumplimiento_facturada_otras_companias_gd['PorcentajeCumplimiento'] = cumplimiento_facturada_otras_companias_gd['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_facturada_otras_companias_gd['Contexto'] = 'gd_' + cumplimiento_facturada_otras_companias_gd['AreaCalculo'].astype('str').str.cat(cumplimiento_facturada_otras_companias_gd['Consecutivo'].astype('str'), sep="_")
cumplimiento_facturada_otras_companias_gd['Variable'] = 'VentaFacturadaDivisionSub'
cumplimiento_facturada_otras_companias_gd = cumplimiento_facturada_otras_companias_gd[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_facturada_otras_companias_gd.head()

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 12.3. Para AD (VentaCobradaDivisionSub)

In [139]:
area_calculo_sba_completo_ad = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los AD
venta_recaudo_presupuesto_original_ad_real = area_calculo_sba_completo_ad.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los AD
venta_recaudo_presupuesto_original_ad_presupuesto = area_calculo_sba_completo_ad.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

venta_recaudo_real_area_calculo_ad = venta_recaudo_presupuesto_original_ad_real.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_real_area_calculo_ad['Real'] = venta_recaudo_real_area_calculo_ad['Recaudo']
venta_recaudo_real_area_calculo_ad.drop(columns=['Recaudo'], inplace=True)

venta_recaudo_presupuesto_area_calculo_ad = venta_recaudo_presupuesto_original_ad_presupuesto.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_presupuesto_area_calculo_ad['Presupuesto'] = venta_recaudo_presupuesto_area_calculo_ad['Recaudo']
venta_recaudo_presupuesto_area_calculo_ad.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_division_sub_ad = pd.merge(
    left=venta_recaudo_presupuesto_area_calculo_ad,
    right=venta_recaudo_real_area_calculo_ad,
    on=['AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_division_sub_ad['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_division_sub_ad['Real'] = cumplimiento_recaudo_por_division_sub_ad.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad['Presupuesto'] = cumplimiento_recaudo_por_division_sub_ad.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad['Real'] / cumplimiento_recaudo_por_division_sub_ad['Presupuesto']
cumplimiento_recaudo_por_division_sub_ad['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_division_sub_ad['Variable'] = 'VentaCobradaDivisionSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_division_sub_ad = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_division_sub_ad,
    variable='VentaCobradaDivisionSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_recaudo_por_division_sub_ad['Contexto'] = 'ad_' + cumplimiento_recaudo_por_division_sub_ad['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_por_division_sub_ad['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_por_division_sub_ad = cumplimiento_recaudo_por_division_sub_ad[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_recaudo_por_division_sub_ad.head()

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3450279284.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_division_sub_ad['Real'].fillna(0.0, inplace=True)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [140]:
cumplimiento_recaudo_por_division_sub_ad[cumplimiento_recaudo_por_division_sub_ad['Contexto'] == 'ad_3_1']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [141]:
cumplimiento_recaudo_otras_companias_ad = pd.merge(
    left=area_calculo_sba_completo_ad,
    right=df_recaudo_otras_companias.rename(columns={'Compania': 'Division'}),
    on=['Division']
)
cumplimiento_recaudo_otras_companias_ad['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad['Real']/cumplimiento_recaudo_otras_companias_ad['Presupuesto']
cumplimiento_recaudo_otras_companias_ad['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_otras_companias_ad['Contexto'] = 'ad_' + cumplimiento_recaudo_otras_companias_ad['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_otras_companias_ad['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_otras_companias_ad['Variable'] = 'VentaCobradaDivisionSub'
cumplimiento_recaudo_otras_companias_ad = cumplimiento_recaudo_otras_companias_ad[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_otras_companias_ad

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 12.4. Para AD1 (VentaCobradaDivisionSub)

In [142]:
area_calculo_sba_completo_ad1 = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD1']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los AD1
venta_recaudo_presupuesto_original_ad1_real = area_calculo_sba_completo_ad1.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los AD1
venta_recaudo_presupuesto_original_ad1_presupuesto = area_calculo_sba_completo_ad1.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

venta_recaudo_real_area_calculo_ad1 = venta_recaudo_presupuesto_original_ad1_real.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_real_area_calculo_ad1['Real'] = venta_recaudo_real_area_calculo_ad1['Recaudo']
venta_recaudo_real_area_calculo_ad1.drop(columns=['Recaudo'], inplace=True)

venta_recaudo_presupuesto_area_calculo_ad1 = venta_recaudo_presupuesto_original_ad1_presupuesto.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_presupuesto_area_calculo_ad1['Presupuesto'] = venta_recaudo_presupuesto_area_calculo_ad1['Recaudo']
venta_recaudo_presupuesto_area_calculo_ad1.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_division_sub_ad1 = pd.merge(
    left=venta_recaudo_presupuesto_area_calculo_ad1,
    right=venta_recaudo_real_area_calculo_ad1,
    on=['AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_division_sub_ad1['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_division_sub_ad1['Real'] = cumplimiento_recaudo_por_division_sub_ad1.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad1['Presupuesto'] = cumplimiento_recaudo_por_division_sub_ad1.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad1['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad1['Real'] / cumplimiento_recaudo_por_division_sub_ad1['Presupuesto']
cumplimiento_recaudo_por_division_sub_ad1['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad1['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_division_sub_ad1['Variable'] = 'VentaCobradaDivisionSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_division_sub_ad1 = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_division_sub_ad1,
    variable='VentaCobradaDivisionSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD1'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_recaudo_por_division_sub_ad1['Contexto'] = 'ad1_' + cumplimiento_recaudo_por_division_sub_ad1['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_por_division_sub_ad1['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_por_division_sub_ad1 = cumplimiento_recaudo_por_division_sub_ad1[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_recaudo_por_division_sub_ad1.head()

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4183068488.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_division_sub_ad1['Real'].fillna(0.0, inplace=True)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [143]:
cumplimiento_recaudo_otras_companias_ad1 = pd.merge(
    left=area_calculo_sba_completo_ad1,
    right=df_recaudo_otras_companias.rename(columns={'Compania': 'Division'}),
    on=['Division']
)
cumplimiento_recaudo_otras_companias_ad1['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad1['Real']/cumplimiento_recaudo_otras_companias_ad1['Presupuesto']
cumplimiento_recaudo_otras_companias_ad1['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad1['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_otras_companias_ad1['Contexto'] = 'ad1_' + cumplimiento_recaudo_otras_companias_ad1['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_otras_companias_ad1['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_otras_companias_ad1['Variable'] = 'VentaCobradaDivisionSub'
cumplimiento_recaudo_otras_companias_ad1 = cumplimiento_recaudo_otras_companias_ad1[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_otras_companias_ad1

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 12.5. Para AD3 (VentaCobradaDivisionSub)

In [144]:
area_calculo_sba_completo_ad3 = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD3']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los AD3
venta_recaudo_presupuesto_original_ad3_real = area_calculo_sba_completo_ad3.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los AD3
venta_recaudo_presupuesto_original_ad3_presupuesto = area_calculo_sba_completo_ad3.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

venta_recaudo_real_area_calculo_ad3 = venta_recaudo_presupuesto_original_ad3_real.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_real_area_calculo_ad3['Real'] = venta_recaudo_real_area_calculo_ad3['Recaudo']
venta_recaudo_real_area_calculo_ad3.drop(columns=['Recaudo'], inplace=True)

venta_recaudo_presupuesto_area_calculo_ad3 = venta_recaudo_presupuesto_original_ad3_presupuesto.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_presupuesto_area_calculo_ad3['Presupuesto'] = venta_recaudo_presupuesto_area_calculo_ad3['Recaudo']
venta_recaudo_presupuesto_area_calculo_ad3.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_division_sub_ad3 = pd.merge(
    left=venta_recaudo_presupuesto_area_calculo_ad3,
    right=venta_recaudo_real_area_calculo_ad3,
    on=['AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_division_sub_ad3['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_division_sub_ad3['Real'] = cumplimiento_recaudo_por_division_sub_ad3.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad3['Presupuesto'] = cumplimiento_recaudo_por_division_sub_ad3.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad3['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad3['Real'] / cumplimiento_recaudo_por_division_sub_ad3['Presupuesto']
cumplimiento_recaudo_por_division_sub_ad3['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad3['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_division_sub_ad3['Variable'] = 'VentaCobradaDivisionSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_division_sub_ad3 = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_division_sub_ad3,
    variable='VentaCobradaDivisionSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD3'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_recaudo_por_division_sub_ad3['Contexto'] = 'ad3_' + cumplimiento_recaudo_por_division_sub_ad3['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_por_division_sub_ad3['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_por_division_sub_ad3 = cumplimiento_recaudo_por_division_sub_ad3[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_recaudo_por_division_sub_ad3.head()

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1694937637.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_division_sub_ad3['Real'].fillna(0.0, inplace=True)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [145]:
cumplimiento_recaudo_otras_companias_ad3 = pd.merge(
    left=area_calculo_sba_completo_ad3,
    right=df_recaudo_otras_companias.rename(columns={'Compania': 'Division'}),
    on=['Division']
)
cumplimiento_recaudo_otras_companias_ad3['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad3['Real']/cumplimiento_recaudo_otras_companias_ad3['Presupuesto']
cumplimiento_recaudo_otras_companias_ad3['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad3['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_otras_companias_ad3['Contexto'] = 'ad3_' + cumplimiento_recaudo_otras_companias_ad3['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_otras_companias_ad3['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_otras_companias_ad3['Variable'] = 'VentaCobradaDivisionSub'
cumplimiento_recaudo_otras_companias_ad3 = cumplimiento_recaudo_otras_companias_ad3[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_otras_companias_ad3

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 12.6. Para AD4 (VentaCobradaDivisionSub)

In [146]:
area_calculo_sba_completo_ad4 = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD4']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los AD4
venta_recaudo_presupuesto_original_ad4_real = area_calculo_sba_completo_ad4.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los AD4
venta_recaudo_presupuesto_original_ad4_presupuesto = area_calculo_sba_completo_ad4.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

venta_recaudo_real_area_calculo_ad4 = venta_recaudo_presupuesto_original_ad4_real.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_real_area_calculo_ad4['Real'] = venta_recaudo_real_area_calculo_ad4['Recaudo']
venta_recaudo_real_area_calculo_ad4.drop(columns=['Recaudo'], inplace=True)

venta_recaudo_presupuesto_area_calculo_ad4 = venta_recaudo_presupuesto_original_ad4_presupuesto.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_presupuesto_area_calculo_ad4['Presupuesto'] = venta_recaudo_presupuesto_area_calculo_ad4['Recaudo']
venta_recaudo_presupuesto_area_calculo_ad4.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_division_sub_ad4 = pd.merge(
    left=venta_recaudo_presupuesto_area_calculo_ad4,
    right=venta_recaudo_real_area_calculo_ad4,
    on=['AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_division_sub_ad4['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_division_sub_ad4['Real'] = cumplimiento_recaudo_por_division_sub_ad4.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad4['Presupuesto'] = cumplimiento_recaudo_por_division_sub_ad4.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad4['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad4['Real'] / cumplimiento_recaudo_por_division_sub_ad4['Presupuesto']
cumplimiento_recaudo_por_division_sub_ad4['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad4['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_division_sub_ad4['Variable'] = 'VentaCobradaDivisionSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_division_sub_ad4 = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_division_sub_ad4,
    variable='VentaCobradaDivisionSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD4'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_recaudo_por_division_sub_ad4['Contexto'] = 'ad4_' + cumplimiento_recaudo_por_division_sub_ad4['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_por_division_sub_ad4['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_por_division_sub_ad4 = cumplimiento_recaudo_por_division_sub_ad4[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_recaudo_por_division_sub_ad4.head()

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\301827481.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_division_sub_ad4['Real'].fillna(0.0, inplace=True)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [147]:
cumplimiento_recaudo_otras_companias_ad4 = pd.merge(
    left=area_calculo_sba_completo_ad4,
    right=df_recaudo_otras_companias.rename(columns={'Compania': 'Division'}),
    on=['Division']
)
cumplimiento_recaudo_otras_companias_ad4['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad4['Real']/cumplimiento_recaudo_otras_companias_ad4['Presupuesto']
cumplimiento_recaudo_otras_companias_ad4['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad4['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_otras_companias_ad4['Contexto'] = 'ad4_' + cumplimiento_recaudo_otras_companias_ad4['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_otras_companias_ad4['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_otras_companias_ad4['Variable'] = 'VentaCobradaDivisionSub'
cumplimiento_recaudo_otras_companias_ad4 = cumplimiento_recaudo_otras_companias_ad4[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_otras_companias_ad4

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 12.7. Para AD5 (VentaCobradaDivisionSub)

In [148]:
area_calculo_sba_completo_ad5 = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD5']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los AD5
venta_recaudo_presupuesto_original_ad5_real = area_calculo_sba_completo_ad5.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los AD5
venta_recaudo_presupuesto_original_ad5_presupuesto = area_calculo_sba_completo_ad5.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

venta_recaudo_real_area_calculo_ad5 = venta_recaudo_presupuesto_original_ad5_real.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_real_area_calculo_ad5['Real'] = venta_recaudo_real_area_calculo_ad5['Recaudo']
venta_recaudo_real_area_calculo_ad5.drop(columns=['Recaudo'], inplace=True)

venta_recaudo_presupuesto_area_calculo_ad5 = venta_recaudo_presupuesto_original_ad5_presupuesto.groupby(['AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
venta_recaudo_presupuesto_area_calculo_ad5['Presupuesto'] = venta_recaudo_presupuesto_area_calculo_ad5['Recaudo']
venta_recaudo_presupuesto_area_calculo_ad5.drop(columns=['Recaudo'], inplace=True)

cumplimiento_recaudo_por_division_sub_ad5 = pd.merge(
    left=venta_recaudo_presupuesto_area_calculo_ad5,
    right=venta_recaudo_real_area_calculo_ad5,
    on=['AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)
cumplimiento_recaudo_por_division_sub_ad5['Real'].fillna(0.0, inplace=True)
cumplimiento_recaudo_por_division_sub_ad5['Real'] = cumplimiento_recaudo_por_division_sub_ad5.groupby(['AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad5['Presupuesto'] = cumplimiento_recaudo_por_division_sub_ad5.groupby(['AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_recaudo_por_division_sub_ad5['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad5['Real'] / cumplimiento_recaudo_por_division_sub_ad5['Presupuesto']
cumplimiento_recaudo_por_division_sub_ad5['PorcentajeCumplimiento'] = cumplimiento_recaudo_por_division_sub_ad5['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_por_division_sub_ad5['Variable'] = 'VentaCobradaDivisionSub'

### Cálculo de resultados cualitativos precargados
cumplimiento_recaudo_por_division_sub_ad5 = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_recaudo_por_division_sub_ad5,
    variable='VentaCobradaDivisionSub',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD5'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_recaudo_por_division_sub_ad5['Contexto'] = 'ad5_' + cumplimiento_recaudo_por_division_sub_ad5['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_por_division_sub_ad5['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_por_division_sub_ad5 = cumplimiento_recaudo_por_division_sub_ad5[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_recaudo_por_division_sub_ad5.head()

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2432188086.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cumplimiento_recaudo_por_division_sub_ad5['Real'].fillna(0.0, inplace=True)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [149]:
cumplimiento_recaudo_otras_companias_ad5 = pd.merge(
    left=area_calculo_sba_completo_ad5,
    right=df_recaudo_otras_companias.rename(columns={'Compania': 'Division'}),
    on=['Division']
)
cumplimiento_recaudo_otras_companias_ad5['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad5['Real']/cumplimiento_recaudo_otras_companias_ad5['Presupuesto']
cumplimiento_recaudo_otras_companias_ad5['PorcentajeCumplimiento'] = cumplimiento_recaudo_otras_companias_ad5['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_recaudo_otras_companias_ad5['Contexto'] = 'ad5_' + cumplimiento_recaudo_otras_companias_ad5['AreaCalculo'].astype('str').str.cat(cumplimiento_recaudo_otras_companias_ad5['Consecutivo'].astype('str'), sep="_")
cumplimiento_recaudo_otras_companias_ad5['Variable'] = 'VentaCobradaDivisionSub'
cumplimiento_recaudo_otras_companias_ad5 = cumplimiento_recaudo_otras_companias_ad5[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_recaudo_otras_companias_ad5

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 13. Objetivos de rentabilidad CM5 a nivel país (RentabilidadBbraunPaisAntesDeImpuestos)

In [150]:
cumplimiento_rentabilidad_cm5_nivel_pais = df_rentabilidad[(df_rentabilidad['Compania']=='BBMCO')&(df_rentabilidad['ClaseRentabilidad']=='CMV')]

cumplimiento_rentabilidad_cm5_nivel_pais = cumplimiento_rentabilidad_cm5_nivel_pais.groupby(
    ['Fecha'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})

# cumplimiento_rentabilidad_cm5_nivel_pais['Presupuesto'] = cumplimiento_rentabilidad_cm5_nivel_pais['Presupuesto'].transform(pd.Series.cumsum)
# cumplimiento_rentabilidad_cm5_nivel_pais['Real'] = cumplimiento_rentabilidad_cm5_nivel_pais['Real'].transform(pd.Series.cumsum)

cumplimiento_rentabilidad_cm5_nivel_pais['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_cm5_nivel_pais['Real'] / cumplimiento_rentabilidad_cm5_nivel_pais['Presupuesto']
cumplimiento_rentabilidad_cm5_nivel_pais['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_cm5_nivel_pais['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_rentabilidad_cm5_nivel_pais['Contexto'] = 'CM5'
cumplimiento_rentabilidad_cm5_nivel_pais['Variable'] = 'RentabilidadBbraunPaisAntesDeImpuestos'

cumplimiento_rentabilidad_cm5_nivel_pais.head()

Empty DataFrame
Columns: [Fecha, Real, Presupuesto, PorcentajeCumplimiento, Contexto, Variable]
Index: []

## 14. Objetivos de rentabilidad CM3 por grupo clientes con consecutivos (RentabilidadDivisionGrupoClientesCM3Sub)

In [151]:
rentabilidad_division_cm3_gd = pd.merge(
    left=df_rentabilidad[(df_rentabilidad['ClaseRentabilidad']=='CMIII')],
    right=area_calculo_sba_completo_gd,
    on=['GrupoProducto', 'SBA'],
    how='left'
)
cumplimiento_rentabilidad_cm3_grupo_clientes_sub = rentabilidad_division_cm3_gd.groupby(
    ['Division', 'Consecutivo', 'Fecha'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})

cumplimiento_rentabilidad_cm3_grupo_clientes_sub['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_cm3_grupo_clientes_sub['Real']/cumplimiento_rentabilidad_cm3_grupo_clientes_sub['Presupuesto']
cumplimiento_rentabilidad_cm3_grupo_clientes_sub['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_cm3_grupo_clientes_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_rentabilidad_cm3_grupo_clientes_sub['Contexto'] = 'gd_' + cumplimiento_rentabilidad_cm3_grupo_clientes_sub['Division'].astype('str').str.cat(cumplimiento_rentabilidad_cm3_grupo_clientes_sub['Consecutivo'].astype('str'), sep="_")
cumplimiento_rentabilidad_cm3_grupo_clientes_sub['Variable'] = 'RentabilidadDivisionGrupoClientesCM3Sub'
cumplimiento_rentabilidad_cm3_grupo_clientes_sub = cumplimiento_rentabilidad_cm3_grupo_clientes_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_rentabilidad_cm3_grupo_clientes_sub

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 15. Objetivos de rentabilidad CM3 por grupo clientes (RentabilidadDivisionGrupoClientesCM3)

In [152]:
cumplimiento_rentabilidad_cm3_grupo_clientes = pd.merge(
    left=df_rentabilidad[(df_rentabilidad['ClaseRentabilidad']=='CMIII')],
    right=area_calculo_sba_completo_gd[['GrupoProducto', 'SBA', 'Division', 'AreaCalculo']].drop_duplicates(['GrupoProducto', 'SBA', 'AreaCalculo', 'Division']),
    on=['GrupoProducto', 'SBA'],
    how='left'
)

cumplimiento_rentabilidad_cm3_grupo_clientes = cumplimiento_rentabilidad_cm3_grupo_clientes.groupby(
    ['AreaCalculo', 'Division', 'Fecha'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})
cumplimiento_rentabilidad_cm3_grupo_clientes['AreaCalculo'] = cumplimiento_rentabilidad_cm3_grupo_clientes['AreaCalculo'].astype(int).astype(str)

cumplimiento_rentabilidad_cm3_grupo_clientes['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_cm3_grupo_clientes['Real']/cumplimiento_rentabilidad_cm3_grupo_clientes['Presupuesto']
cumplimiento_rentabilidad_cm3_grupo_clientes['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_cm3_grupo_clientes['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_rentabilidad_cm3_grupo_clientes['Contexto'] = 'gd_' + cumplimiento_rentabilidad_cm3_grupo_clientes['AreaCalculo'] + '_' + cumplimiento_rentabilidad_cm3_grupo_clientes['Division']
cumplimiento_rentabilidad_cm3_grupo_clientes['Variable'] = 'RentabilidadDivisionGrupoClientesCM3'
cumplimiento_rentabilidad_cm3_grupo_clientes = cumplimiento_rentabilidad_cm3_grupo_clientes[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_rentabilidad_cm3_grupo_clientes

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 16. Objetivos de rentabilidad por grupo clientes (RentabilidadGrupoClientesCM2)

In [153]:
df_rentabilidad_kam

Empty DataFrame
Columns: [Division, Fecha, Real, Presupuesto]
Index: []

In [154]:
area_calculo_sba_completo_kam = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado'] == 'KAM']

cumplimiento_rentabilidad_cm2_grupo_clientes = pd.merge(
    left=area_calculo_sba_completo_kam[['Division', 'AreaCalculo', 'Consecutivo']].drop_duplicates(),
    right=df_rentabilidad_kam,
    on='Division',
    how='left'
)
cumplimiento_rentabilidad_cm2_grupo_clientes

  Division  AreaCalculo  Consecutivo Fecha  Real  Presupuesto
0       HC            2            1   NaT   NaN          NaN
1       HC            2            2   NaT   NaN          NaN
2       HC            2            3   NaT   NaN          NaN
3       HC            2           10   NaT   NaN          NaN
4   GRPCLI            4            1   NaT   NaN          NaN

In [155]:

cumplimiento_rentabilidad_cm2_grupo_clientes['Presupuesto'] = cumplimiento_rentabilidad_cm2_grupo_clientes.groupby(['Division', 'AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_rentabilidad_cm2_grupo_clientes['Real'] = cumplimiento_rentabilidad_cm2_grupo_clientes.groupby(['Division', 'AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)

cumplimiento_rentabilidad_cm2_grupo_clientes['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_cm2_grupo_clientes['Real']/cumplimiento_rentabilidad_cm2_grupo_clientes['Presupuesto']
cumplimiento_rentabilidad_cm2_grupo_clientes['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_cm2_grupo_clientes['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_rentabilidad_cm2_grupo_clientes['Contexto'] = 'kam_' + cumplimiento_rentabilidad_cm2_grupo_clientes['AreaCalculo'].astype('str').str.cat(cumplimiento_rentabilidad_cm2_grupo_clientes['Consecutivo'].astype('str'), sep="_")
cumplimiento_rentabilidad_cm2_grupo_clientes['Variable'] = 'RentabilidadGrupoClientesCM2'
cumplimiento_rentabilidad_cm2_grupo_clientes = cumplimiento_rentabilidad_cm2_grupo_clientes[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_rentabilidad_cm2_grupo_clientes

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,kam_2_1,RentabilidadGrupoClientesCM2,NaT,NaN,NaN,NaN
1,kam_2_2,RentabilidadGrupoClientesCM2,NaT,NaN,NaN,NaN
2,kam_2_3,RentabilidadGrupoClientesCM2,NaT,NaN,NaN,NaN
3,kam_2_10,RentabilidadGrupoClientesCM2,NaT,NaN,NaN,NaN
4,kam_4_1,RentabilidadGrupoClientesCM2,NaT,NaN,NaN,NaN

## 16.1 RentabilidadGrupoClientesCM2Sub

In [156]:
area_calculo_sba_completo_kam

     AreaCalculo  Consecutivo Division GrupoProducto SBA TipoEmpleado
139            2            1       HC           630  08          KAM
140            2            2       HC           630  12          KAM
141            2            2       HC           CDK  12          KAM
142            2            3       HC           620  36          KAM
143            2           10       HC           620  36          KAM
144            2           10       HC           630  08          KAM
145            2           10       HC           630  12          KAM
146            2           10       HC           CDK  12          KAM
147            4            1   GRPCLI                            KAM

In [157]:
df_rentabilidad

,Compania,GrupoProducto,SBA,ClaseRentabilidad,Fecha,Real,Presupuesto
0,BBMCO,001,30,CM2COGSP,2025-03-01,2.466612e+05,2.619855e+05
1,BBMCO,001,30,CM2COGSP,2025-04-01,3.105949e+05,3.572529e+05
2,BBMCO,001,30,CM2COGSP,2025-05-01,3.359584e+05,4.525204e+05
3,BBMCO,001,30,CM2COGSP,2025-06-01,4.053510e+05,5.477878e+05
4,BBMCO,001,30,CM2COGSP,2025-07-01,5.318528e+05,6.430553e+05
...,...,...,...,...,...,...,...
473,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-08-01,3.049280e+06,2.347009e+06
474,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-09-01,2.453488e+06,2.763416e+06
475,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-10-01,3.299142e+06,3.188239e+06
476,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-11-01,3.819836e+06,3.654547e+06
477,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-12-01,3.819836e+06,3.654547e+06

In [158]:
area_calculo_sba_completo_kam = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado'] == 'KAM']

cumplimiento_rentabilidad_grupo_clientes_cm2_sub = pd.merge(
    left=area_calculo_sba_completo_kam.drop_duplicates(),
    right=df_rentabilidad,
    on=['GrupoProducto', 'SBA'],
    how='inner'
).merge(
    df_empleados
)
cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Contexto'] = cumplimiento_rentabilidad_grupo_clientes_cm2_sub['CodigoEmpleado'].str.lower().str.cat(cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Consecutivo'].astype(int).astype(str), sep="_")
# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Contexto'] = 'kam_' + cumplimiento_rentabilidad_grupo_clientes_cm2_sub['AreaCalculo'].astype('str').str.cat(cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Consecutivo'].astype('str'), sep="_")
cumplimiento_rentabilidad_grupo_clientes_cm2_sub

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,Compania,ClaseRentabilidad,Fecha,Real,Presupuesto,CodigoEmpleado,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,Contexto
0,2,1,HC,630,08,KAM,BBMCO,CM2COGSP,2025-03-01,4.337511e+05,379955.794633,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_1
1,2,1,HC,630,08,KAM,BBMCO,CM2COGSP,2025-04-01,5.535802e+05,494311.422144,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_1
2,2,1,HC,630,08,KAM,BBMCO,CM2COGSP,2025-05-01,7.292850e+05,649244.852966,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_1
3,2,1,HC,630,08,KAM,BBMCO,CM2COGSP,2025-06-01,8.825227e+05,822622.739837,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_1
4,2,1,HC,630,08,KAM,BBMCO,CM2COGSP,2025-07-01,1.084673e+06,984933.953079,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2,10,HC,CDK,12,KAM,BBMCO,CM2COGSP,2025-08-01,3.111574e+03,13910.569785,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_10
76,2,10,HC,CDK,12,KAM,BBMCO,CM2COGSP,2025-09-01,-4.739146e+03,15739.080622,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_10
77,2,10,HC,CDK,12,KAM,BBMCO,CM2COGSP,2025-10-01,-4.857893e+04,17775.902820,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_10
78,2,10,HC,CDK,12,KAM,BBMCO,CM2COGSP,2025-11-01,-4.404820e+04,20321.930567,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_10
79,2,10,HC,CDK,12,KAM,BBMCO,CM2COGSP,2025-12-01,-4.571490e+04,23145.706796,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293_10

In [159]:
cumplimiento_rentabilidad_grupo_clientes_cm2_sub = cumplimiento_rentabilidad_grupo_clientes_cm2_sub.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
cumplimiento_rentabilidad_grupo_clientes_cm2_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1987225761.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  cumplimiento_rentabilidad_grupo_clientes_cm2_sub = cumplimiento_rentabilidad_grupo_clientes_cm2_sub.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

      Contexto      Fecha          Real   Presupuesto
0    5004293_1 2025-03-01  4.337511e+05  3.799558e+05
1    5004293_1 2025-04-01  5.535802e+05  4.943114e+05
2    5004293_1 2025-05-01  7.292850e+05  6.492449e+05
3    5004293_1 2025-06-01  8.825227e+05  8.226227e+05
4    5004293_1 2025-07-01  1.084673e+06  9.849340e+05
5    5004293_1 2025-08-01  1.198151e+06  1.145401e+06
6    5004293_1 2025-09-01  1.328181e+06  1.316934e+06
7    5004293_1 2025-10-01  1.447888e+06  1.473712e+06
8    5004293_1 2025-11-01  1.623534e+06  1.650779e+06
9    5004293_1 2025-12-01  1.833582e+06  1.844446e+06
10  5004293_10 2025-03-01  1.180909e+06  1.719790e+06
11  5004293_10 2025-04-01  1.743443e+06  2.240002e+06
12  5004293_10 2025-05-01  2.346259e+06  2.935652e+06
13  5004293_10 2025-06-01  2.931523e+06  3.680284e+06
14  5004293_10 2025-07-01  3.697804e+06  4.378545e+06
15  5004293_10 2025-08-01  4.054263e+06  5.070883e+06
16  5004293_10 2025-09-01  4.650053e+06  5.810031e+06
17  5004293_10 2025-10-01  5.193444e+06  6.519221e+06
18  5004293_10 2025-11-01  5.964107e+06  7.319125e+06
19  5004293_10 2025-12-01  6.754396e+06  8.223484e+06
20   5004293_2 2025-03-01  1.878346e+05  7.930889e+05
21   5004293_2 2025-04-01  4.524466e+05  1.031885e+06
22   5004293_2 2025-05-01  6.519288e+05  1.354916e+06
23   5004293_2 2025-06-01  8.885294e+05  1.716078e+06
24   5004293_2 2025-07-01  1.318298e+06  2.054592e+06
25   5004293_2 2025-08-01  1.403780e+06  2.389028e+06
26   5004293_2 2025-09-01  1.654162e+06  2.746550e+06
27   5004293_2 2025-10-01  1.857517e+06  3.073684e+06
28   5004293_2 2025-11-01  2.199771e+06  3.443398e+06
29   5004293_2 2025-12-01  2.491013e+06  3.847811e+06
30   5004293_3 2025-03-01  5.593228e+05  5.467450e+05
31   5004293_3 2025-04-01  7.374159e+05  7.138059e+05
32   5004293_3 2025-05-01  9.650457e+05  9.314914e+05
33   5004293_3 2025-06-01  1.160471e+06  1.141583e+06
34   5004293_3 2025-07-01  1.294834e+06  1.339019e+06
35   5004293_3 2025-08-01  1.452332e+06  1.536455e+06
36   5004293_3 2025-09-01  1.667710e+06  1.746546e+06
37   5004293_3 2025-10-01  1.888039e+06  1.971826e+06
38   5004293_3 2025-11-01  2.140803e+06  2.224948e+06
39   5004293_3 2025-12-01  2.429800e+06  2.531227e+06

In [160]:
# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Presupuesto'] = cumplimiento_rentabilidad_grupo_clientes_cm2_sub.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Real'] = cumplimiento_rentabilidad_grupo_clientes_cm2_sub.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)

cumplimiento_rentabilidad_grupo_clientes_cm2_sub['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Real']/cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Presupuesto']
cumplimiento_rentabilidad_grupo_clientes_cm2_sub['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_grupo_clientes_cm2_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Variable'] = 'RentabilidadUnidadNegocioCM2COGSSUB'
# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Variable'] = 'RentabilidadGrupoClientesCM2Sub'
cumplimiento_rentabilidad_grupo_clientes_cm2_sub = cumplimiento_rentabilidad_grupo_clientes_cm2_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

cumplimiento_rentabilidad_grupo_clientes_cm2_sub

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,4.337511e+05,3.799558e+05,1.14
1,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-04-01,5.535802e+05,4.943114e+05,1.12
2,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-05-01,7.292850e+05,6.492449e+05,1.12
3,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-06-01,8.825227e+05,8.226227e+05,1.07
4,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-07-01,1.084673e+06,9.849340e+05,1.10
5,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-08-01,1.198151e+06,1.145401e+06,1.05
6,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-09-01,1.328181e+06,1.316934e+06,1.01
7,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-10-01,1.447888e+06,1.473712e+06,0.98
8,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-11-01,1.623534e+06,1.650779e+06,0.98
9,5004293_1,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,1.833582e+06,1.844446e+06,0.99
10,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,1.180909e+06,1.719790e+06,0.69
11,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-04-01,1.743443e+06,2.240002e+06,0.78
12,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-05-01,2.346259e+06,2.935652e+06,0.80
13,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-06-01,2.931523e+06,3.680284e+06,0.80
14,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-07-01,3.697804e+06,4.378545e+06,0.84
15,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-08-01,4.054263e+06,5.070883e+06,0.80
16,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-09-01,4.650053e+06,5.810031e+06,0.80
17,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-10-01,5.193444e+06,6.519221e+06,0.80
18,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-11-01,5.964107e+06,7.319125e+06,0.81
19,5004293_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,6.754396e+06,8.223484e+06,0.82
20,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,1.878346e+05,7.930889e+05,0.24
21,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-04-01,4.524466e+05,1.031885e+06,0.44
22,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-05-01,6.519288e+05,1.354916e+06,0.48
23,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-06-01,8.885294e+05,1.716078e+06,0.52
24,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-07-01,1.318298e+06,2.054592e+06,0.64
25,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-08-01,1.403780e+06,2.389028e+06,0.59
26,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-09-01,1.654162e+06,2.746550e+06,0.60
27,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-10-01,1.857517e+06,3.073684e+06,0.60
28,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-11-01,2.199771e+06,3.443398e+06,0.64
29,5004293_2,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,2.491013e+06,3.847811e+06,0.65
30,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,5.593228e+05,5.467450e+05,1.02
31,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-04-01,7.374159e+05,7.138059e+05,1.03
32,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-05-01,9.650457e+05,9.314914e+05,1.04
33,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-06-01,1.160471e+06,1.141583e+06,1.02
34,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-07-01,1.294834e+06,1.339019e+06,0.97
35,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-08-01,1.452332e+06,1.536455e+06,0.95
36,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-09-01,1.667710e+06,1.746546e+06,0.95
37,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-10-01,1.888039e+06,1.971826e+06,0.96
38,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-11-01,2.140803e+06,2.224948e+06,0.96
39,5004293_3,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,2.429800e+06,2.531227e+06,0.96

In [161]:
# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Contexto'] = 'kam_' + cumplimiento_rentabilidad_grupo_clientes_cm2_sub['AreaCalculo'].astype('str').str.cat(cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Consecutivo'].astype('str'), sep="_")
# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Presupuesto'] = cumplimiento_rentabilidad_grupo_clientes_cm2_sub.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Real'] = cumplimiento_rentabilidad_grupo_clientes_cm2_sub.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)

# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Real']/cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Presupuesto']
# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['PorcentajeCumplimiento'] = cumplimiento_rentabilidad_grupo_clientes_cm2_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

# cumplimiento_rentabilidad_grupo_clientes_cm2_sub['Variable'] = 'RentabilidadGrupoClientesCM2Sub'
# cumplimiento_rentabilidad_grupo_clientes_cm2_sub = cumplimiento_rentabilidad_grupo_clientes_cm2_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

# cumplimiento_rentabilidad_grupo_clientes_cm2_sub

In [162]:
df_parrillas[df_parrillas['Variable'] == 'RentabilidadGrupoClientesCM2Sub']

Empty DataFrame
Columns: [CodigoEmpleado, Variable, Contexto, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo]
Index: []

In [163]:
df_parrillas[
    (df_parrillas['Variable'] == 'RentabilidadUnidadNegocioCM2COGSSUB') &
    (df_parrillas['Contexto'].str.contains('5004293'))
]

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
1505,5004293,RentabilidadUnidadNegocioCM2COGSSUB,5004293_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,SBA08 12 36

## 17. Objetivos de rentabilidad antes de impuestos CM5 (TotalRentabilidadBraunAntesDeImpuestosCM5)

In [164]:
rentabilidad_antes_de_impuestos_cm5 = df_rentabilidad[(df_rentabilidad['ClaseRentabilidad']=='CMV')]
rentabilidad_antes_de_impuestos_cm5.rename(columns={'Compania': 'Division'}, inplace=True)
rentabilidad_antes_de_impuestos_cm5 = rentabilidad_antes_de_impuestos_cm5.groupby(
    ['Division', 'Fecha'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})

# rentabilidad_antes_de_impuestos_cm5['Presupuesto'] = rentabilidad_antes_de_impuestos_cm5.groupby(['Division'])['Presupuesto'].transform(pd.Series.cumsum)
# rentabilidad_antes_de_impuestos_cm5['Real'] = rentabilidad_antes_de_impuestos_cm5.groupby(['Division'])['Real'].transform(pd.Series.cumsum)
rentabilidad_antes_de_impuestos_cm5['PorcentajeCumplimiento'] = rentabilidad_antes_de_impuestos_cm5['Real'] / rentabilidad_antes_de_impuestos_cm5['Presupuesto']
rentabilidad_antes_de_impuestos_cm5['PorcentajeCumplimiento'] = rentabilidad_antes_de_impuestos_cm5['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
rentabilidad_antes_de_impuestos_cm5['Variable'] = 'TotalRentabilidadBraunAntesDeImpuestosCM5'

rentabilidad_antes_de_impuestos_cm5

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1697700680.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rentabilidad_antes_de_impuestos_cm5.rename(columns={'Compania': 'Division'}, inplace=True)

Empty DataFrame
Columns: [Division, Fecha, Real, Presupuesto, PorcentajeCumplimiento, Variable]
Index: []

### 17.1. Para AD (TotalRentabilidadBraunAntesDeImpuestosCM5)

In [165]:
cumplimiento_rentabilidad_cm5_ad = pd.merge(
    left=area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD'],
    right=rentabilidad_antes_de_impuestos_cm5,
    on=['Division'],
    how='left'
)

### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_cm5_ad = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_cm5_ad,
    variable='TotalRentabilidadBraunAntesDeImpuestosCM5',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_rentabilidad_cm5_ad['Contexto'] = 'ad_' + cumplimiento_rentabilidad_cm5_ad['AreaCalculo'].astype('str').str.cat(cumplimiento_rentabilidad_cm5_ad['Consecutivo'].astype('str'), sep="_")
cumplimiento_rentabilidad_cm5_ad = cumplimiento_rentabilidad_cm5_ad[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_rentabilidad_cm5_ad

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

  Contexto Variable Fecha  Real  Presupuesto  PorcentajeCumplimiento
0   ad_1_1      NaN   NaT   NaN          NaN                     NaN
1   ad_2_1      NaN   NaT   NaN          NaN                     NaN
2   ad_3_1      NaN   NaT   NaN          NaN                     NaN
3   ad_4_1      NaN   NaT   NaN          NaN                     NaN

### 17.2. Para AD1 (TotalRentabilidadBraunAntesDeImpuestosCM5)

In [166]:
cumplimiento_rentabilidad_cm5_ad1 = pd.merge(
    left=area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD1'],
    right=rentabilidad_antes_de_impuestos_cm5,
    on=['Division'],
    how='left'
)

### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_cm5_ad1 = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_cm5_ad1,
    variable='TotalRentabilidadBraunAntesDeImpuestosCM5',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD1'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_rentabilidad_cm5_ad1['Contexto'] = 'ad1_' + cumplimiento_rentabilidad_cm5_ad1['AreaCalculo'].astype('str').str.cat(cumplimiento_rentabilidad_cm5_ad1['Consecutivo'].astype('str'), sep="_")
cumplimiento_rentabilidad_cm5_ad1 = cumplimiento_rentabilidad_cm5_ad1[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_rentabilidad_cm5_ad1

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

   Contexto Variable Fecha  Real  Presupuesto  PorcentajeCumplimiento
0   ad1_1_1      NaN   NaT   NaN          NaN                     NaN
1   ad1_2_1      NaN   NaT   NaN          NaN                     NaN
2   ad1_3_1      NaN   NaT   NaN          NaN                     NaN
3   ad1_4_1      NaN   NaT   NaN          NaN                     NaN
4   ad1_5_1      NaN   NaT   NaN          NaN                     NaN
5  ad1_10_1      NaN   NaT   NaN          NaN                     NaN
6  ad1_11_1      NaN   NaT   NaN          NaN                     NaN

### 17.3. Para AD2 (TotalRentabilidadBraunAntesDeImpuestosCM5)

In [167]:
cumplimiento_rentabilidad_cm5_ad2 = pd.merge(
    left=area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD2'],
    right=rentabilidad_antes_de_impuestos_cm5,
    on=['Division'],
    how='left'
)

### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_cm5_ad2 = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_cm5_ad2,
    variable='TotalRentabilidadBraunAntesDeImpuestosCM5',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD2'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_rentabilidad_cm5_ad2['Contexto'] = 'ad2_' + cumplimiento_rentabilidad_cm5_ad2['AreaCalculo'].astype('str').str.cat(cumplimiento_rentabilidad_cm5_ad2['Consecutivo'].astype('str'), sep="_")
cumplimiento_rentabilidad_cm5_ad2 = cumplimiento_rentabilidad_cm5_ad2[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_rentabilidad_cm5_ad2

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

  Contexto Variable Fecha  Real  Presupuesto  PorcentajeCumplimiento
0  ad2_1_1      NaN   NaT   NaN          NaN                     NaN
1  ad2_2_1      NaN   NaT   NaN          NaN                     NaN

### 17.4. Para AD3 (TotalRentabilidadBraunAntesDeImpuestosCM5)

In [168]:
cumplimiento_rentabilidad_cm5_ad3 = pd.merge(
    left=area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD3'],
    right=rentabilidad_antes_de_impuestos_cm5,
    on=['Division'],
    how='left'
)

### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_cm5_ad3 = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_cm5_ad3,
    variable='TotalRentabilidadBraunAntesDeImpuestosCM5',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD3'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_rentabilidad_cm5_ad3['Contexto'] = 'ad3_' + cumplimiento_rentabilidad_cm5_ad3['AreaCalculo'].astype('str').str.cat(cumplimiento_rentabilidad_cm5_ad3['Consecutivo'].astype('str'), sep="_")
cumplimiento_rentabilidad_cm5_ad3 = cumplimiento_rentabilidad_cm5_ad3[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_rentabilidad_cm5_ad3

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

  Contexto Variable Fecha  Real  Presupuesto  PorcentajeCumplimiento
0  ad3_1_1      NaN   NaT   NaN          NaN                     NaN
1  ad3_2_1      NaN   NaT   NaN          NaN                     NaN
2  ad3_3_1      NaN   NaT   NaN          NaN                     NaN

### 17.5. Para AD4 (TotalRentabilidadBraunAntesDeImpuestosCM5)

In [169]:
cumplimiento_rentabilidad_cm5_ad4 = pd.merge(
    left=area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD4'],
    right=rentabilidad_antes_de_impuestos_cm5,
    on=['Division'],
    how='left'
)

### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_cm5_ad4 = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_cm5_ad4,
    variable='TotalRentabilidadBraunAntesDeImpuestosCM5',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD4'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_rentabilidad_cm5_ad4['Contexto'] = 'ad4_' + cumplimiento_rentabilidad_cm5_ad4['AreaCalculo'].astype('str').str.cat(cumplimiento_rentabilidad_cm5_ad4['Consecutivo'].astype('str'), sep="_")
cumplimiento_rentabilidad_cm5_ad4 = cumplimiento_rentabilidad_cm5_ad4[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_rentabilidad_cm5_ad4

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

  Contexto Variable Fecha  Real  Presupuesto  PorcentajeCumplimiento
0  ad4_1_1      NaN   NaT   NaN          NaN                     NaN
1  ad4_1_2      NaN   NaT   NaN          NaN                     NaN
2  ad4_2_1      NaN   NaT   NaN          NaN                     NaN

### 17.6. Para AD5 (TotalRentabilidadBraunAntesDeImpuestosCM5)

In [170]:
cumplimiento_rentabilidad_cm5_ad5 = pd.merge(
    left=area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD5'],
    right=rentabilidad_antes_de_impuestos_cm5,
    on=['Division'],
    how='left'
)

### Cálculo de resultados cualitativos precargados
cumplimiento_rentabilidad_cm5_ad5 = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=cumplimiento_rentabilidad_cm5_ad5,
    variable='TotalRentabilidadBraunAntesDeImpuestosCM5',
    columnas_extra=['TipoEmpleado', 'AreaCalculo', 'Consecutivo'], 
    columnas_extra_merge=['AreaCalculo', 'Consecutivo'],
    pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD5'].drop(columns=['TipoEmpleado'])
)
###

cumplimiento_rentabilidad_cm5_ad5['Contexto'] = 'ad5_' + cumplimiento_rentabilidad_cm5_ad5['AreaCalculo'].astype('str').str.cat(cumplimiento_rentabilidad_cm5_ad5['Consecutivo'].astype('str'), sep="_")
cumplimiento_rentabilidad_cm5_ad5 = cumplimiento_rentabilidad_cm5_ad5[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_rentabilidad_cm5_ad5

['TipoEmpleado', 'AreaCalculo', 'Consecutivo'] ['AreaCalculo', 'Consecutivo']

  Contexto Variable Fecha  Real  Presupuesto  PorcentajeCumplimiento
0  ad5_1_1      NaN   NaT   NaN          NaN                     NaN

## 18. Objetivos de venta facturada previo notas crédito TP (VentaFacturadaPrevioNotasCreditoTP)

In [171]:
cumplimiento_venta_previo_notas_credito_tp = pd.merge(
    left=area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='AD2'],
    right=df_venta_otras_companias.rename(columns={'Compania': 'Division'}),
    on=['Division'],
    how='left'
)

# cumplimiento_venta_previo_notas_credito_tp['Presupuesto'] = cumplimiento_venta_previo_notas_credito_tp.groupby(['Division', 'AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
# cumplimiento_venta_previo_notas_credito_tp['Real'] = cumplimiento_venta_previo_notas_credito_tp.groupby(['Division', 'AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)

cumplimiento_venta_previo_notas_credito_tp['PorcentajeCumplimiento'] = cumplimiento_venta_previo_notas_credito_tp['Real'] / cumplimiento_venta_previo_notas_credito_tp['Presupuesto']
cumplimiento_venta_previo_notas_credito_tp['PorcentajeCumplimiento'] = cumplimiento_venta_previo_notas_credito_tp['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

cumplimiento_venta_previo_notas_credito_tp['Variable'] = 'VentaFacturadaPrevioNotasCreditoTP'
cumplimiento_venta_previo_notas_credito_tp['Contexto'] = 'ad2_' + cumplimiento_venta_previo_notas_credito_tp['AreaCalculo'].astype('str').str.cat(cumplimiento_venta_previo_notas_credito_tp['Consecutivo'].astype('str'), sep="_")
cumplimiento_venta_previo_notas_credito_tp = cumplimiento_venta_previo_notas_credito_tp[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_venta_previo_notas_credito_tp

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,ad2_1_1,VentaFacturadaPrevioNotasCreditoTP,NaT,NaN,NaN,NaN
1,ad2_2_1,VentaFacturadaPrevioNotasCreditoTP,NaT,NaN,NaN,NaN

## 19. Venta de servicios Mtto (VentaServiciosMtto)

In [172]:
cumplimiento_venta_servicios_mtto = df_venta_servicios_mtto

cumplimiento_venta_servicios_mtto['Presupuesto'] = cumplimiento_venta_servicios_mtto['Presupuesto'].transform(pd.Series.cumsum)
cumplimiento_venta_servicios_mtto['Real'] = cumplimiento_venta_servicios_mtto['Real'].transform(pd.Series.cumsum)

cumplimiento_venta_servicios_mtto['PorcentajeCumplimiento'] = cumplimiento_venta_servicios_mtto['Real'] / cumplimiento_venta_servicios_mtto['Presupuesto']
cumplimiento_venta_servicios_mtto['PorcentajeCumplimiento'] = cumplimiento_venta_servicios_mtto['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
cumplimiento_venta_servicios_mtto['Variable'] = 'VentaServiciosMtto'
cumplimiento_venta_servicios_mtto['Contexto'] = 'VentaServiciosMtto'
cumplimiento_venta_servicios_mtto = cumplimiento_venta_servicios_mtto[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
cumplimiento_venta_servicios_mtto

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

# Nuevos rubros 2022

## 20. Venta Cobrada BBraun Cluster (UCI + OR) (VentaCobradaBraunCluster)

In [173]:
# print(main)
# main = df_cluster_plan_real_recaudo.copy()
# TODO Validar si se ignoran para TODOS los resultados

# Calcular

main = df_cluster_plan_real_recaudo.copy().merge(
    df_clusters_empleado
)

main['Contexto'] = main['CodigoEmpleado']
main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)

# Variable solo de VCs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main.reset_index(inplace=True)
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real'] / main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaBraunCluster'

main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

venta_cobrada_braun_cluster = main.copy()
main = None

venta_cobrada_braun_cluster

# Contexto: Cluster

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4229823471.py:12: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002699,VentaCobradaBraunCluster,2025-01-01,8.012804e+09,9.329831e+09,0.86
1,5002699,VentaCobradaBraunCluster,2025-02-01,1.801105e+10,1.791253e+10,1.01
2,5002699,VentaCobradaBraunCluster,2025-03-01,2.510013e+10,2.829002e+10,0.89
3,5002699,VentaCobradaBraunCluster,2025-04-01,3.618868e+10,3.750737e+10,0.96
4,5002699,VentaCobradaBraunCluster,2025-05-01,4.519463e+10,4.747490e+10,0.95
...,...,...,...,...,...,...
475,70055621,VentaCobradaBraunCluster,2025-08-01,5.061015e+09,5.345323e+09,0.95
476,70055621,VentaCobradaBraunCluster,2025-09-01,5.803587e+09,6.126909e+09,0.95
477,70055621,VentaCobradaBraunCluster,2025-10-01,6.773146e+09,6.895713e+09,0.98
478,70055621,VentaCobradaBraunCluster,2025-11-01,7.331314e+09,7.688716e+09,0.95
479,70055621,VentaCobradaBraunCluster,2025-12-01,8.018037e+09,8.493817e+09,0.94

In [174]:
venta_cobrada_braun_cluster[
    (venta_cobrada_braun_cluster['Contexto'] == '1111111')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 21. Venta Cobrada Portafolio Cluster (VentaCobradaPortafolioCluster)

In [175]:
df_clusters_empleado[
    (df_clusters_empleado['CodigoEmpleado'] == '5002899')
]

Empty DataFrame
Columns: [Cluster, CodigoEmpleado, TipoEmpleado, AreaCalculo]
Index: []

In [176]:
drop_cols = ['Venta', 'Division', 'ZonaGeografica', 'GrupoProducto', 'Canal', 'SBA']
real = df_venta_recaudo_real.copy().drop(columns=drop_cols)
ppto = df_venta_recaudo_presupuesto.copy().drop(columns=drop_cols)

# Sumamos los registros que tienen el mismo conexto para que exista un solo registro
ppto = ppto.groupby(['CodigoEmpleado', 'Cluster',  'Fecha'], as_index=False)[['Recaudo']].apply(sum)
real = real.groupby(['CodigoEmpleado', 'Cluster',  'Fecha'], as_index=False)[['Recaudo']].apply(sum)
# ppto.reset_index(inplace=True)
# real.reset_index(inplace=True)

main = ppto.rename(columns={'Recaudo': 'Presupuesto'}).merge(
    real.rename(columns={'Recaudo': 'Real'}),
    on=['CodigoEmpleado', 'Cluster','Fecha'],
    how='left'
)
main['Real'].fillna(0, inplace=True)


# Traer áreas de cálculo y tipo de empleado de la maestra de empleados
empleados = df_empleados[['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo', 'FechaIngreso']].copy()
main = main.merge(empleados, on=['CodigoEmpleado'], how='left')

main = main[main['Fecha'] >= main['FechaIngreso']]

main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\513243669.py:6: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ppto = ppto.groupby(['CodigoEmpleado', 'Cluster',  'Fecha'], as_index=False)[['Recaudo']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\513243669.py:7: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  real = real.groupby(['CodigoEmpleado', 'Cluster',  'Fecha'], as_index=False)[['Recaudo']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\513243669.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)

,CodigoEmpleado,Cluster,Fecha,Presupuesto,Real,TipoEmpleado,AreaCalculo,FechaIngreso
12,5002699,0,2025-03-01,0.000000e+00,2.689800e+06,VE,7.0,2021-09-01
13,5002699,0,2025-04-01,0.000000e+00,1.678800e+06,VE,7.0,2021-09-01
14,5002699,0,2025-05-01,0.000000e+00,4.397360e+07,VE,7.0,2021-09-01
15,5002699,0,2025-07-01,0.000000e+00,2.354500e+06,VE,7.0,2021-09-01
16,5002699,0,2025-09-01,0.000000e+00,0.000000e+00,VE,7.0,2021-09-01
...,...,...,...,...,...,...,...,...
670,70048318,1,2025-11-01,7.770273e+08,5.385358e+08,VC,3.0,2025-09-01
671,70048318,1,2025-12-01,8.739711e+08,8.524035e+08,VC,3.0,2025-09-01
672,70051944,14,2025-11-01,2.402648e+08,9.886381e+07,VC,3.0,2025-11-01
673,70051944,14,2025-12-01,2.714192e+08,1.731159e+08,VC,3.0,2025-11-01
677,70053308,9,2025-12-01,8.085298e+08,3.201911e+08,VC,4.0,2025-12-01

In [177]:
# Validación. Se eliminan presupuestos  = 0
main['Real'].fillna(0, inplace=True)
main['AreaCalculo'].fillna(0, inplace=True)
main = main[main.Presupuesto.notnull()]

# Calcular
main = main.groupby(['CodigoEmpleado', 'Cluster', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

### Agrupación a nivel de empleado por clusters
main = pd.merge(
    df_clusters_empleado[['CodigoEmpleado', 'Cluster']],
    main,
    on=['CodigoEmpleado', 'Cluster'],
    how='left'
)

main = main.groupby(['CodigoEmpleado', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main.reset_index(inplace=True)
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Real'] = main.groupby(['CodigoEmpleado'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado'])['Presupuesto'].transform(pd.Series.cumsum)
main.reset_index(inplace=True)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaPortafolioCluster'

### Cálculo de resultados cualitativos precargados
main = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=main,
    variable='VentaCobradaPortafolioCluster',
    columnas_extra=['CodigoEmpleado'],
    columnas_extra_merge=['CodigoEmpleado']
)
###

main['Contexto'] = main['CodigoEmpleado']
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]   
###


venta_cobrada_portafolio_cluster = main.copy()
main = None
venta_cobrada_portafolio_cluster

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\203011730.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\203011730.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['AreaCalculo'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\203011730.py:7: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Cluster', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\203011730.py:18: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

['CodigoEmpleado'] ['CodigoEmpleado']

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002790,VentaCobradaPortafolioCluster,2025-01-01,2.624441e+08,3.216864e+08,0.82
1,5002790,VentaCobradaPortafolioCluster,2025-02-01,5.641509e+08,6.201968e+08,0.91
2,5002790,VentaCobradaPortafolioCluster,2025-03-01,1.035903e+09,9.510580e+08,1.09
3,5002790,VentaCobradaPortafolioCluster,2025-04-01,1.488088e+09,1.295149e+09,1.15
4,5002790,VentaCobradaPortafolioCluster,2025-05-01,1.748899e+09,1.692543e+09,1.03
...,...,...,...,...,...,...
341,70048318,VentaCobradaPortafolioCluster,2025-11-01,1.830415e+09,2.389208e+09,0.77
342,70048318,VentaCobradaPortafolioCluster,2025-12-01,2.682819e+09,3.263179e+09,0.82
343,70051944,VentaCobradaPortafolioCluster,2025-11-01,9.886381e+07,2.402648e+08,0.41
344,70051944,VentaCobradaPortafolioCluster,2025-12-01,2.719797e+08,5.116839e+08,0.53
345,70053308,VentaCobradaPortafolioCluster,2025-12-01,3.201911e+08,8.085298e+08,0.40

In [178]:
venta_cobrada_portafolio_cluster[
    (venta_cobrada_portafolio_cluster['Contexto'] == '1111128')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 22. Venta Cobrada Portafolio Cluster sub (VentaCobradaPortafolioClusterSub)

In [179]:
# VentaRecaudoPresupuesto
# VentaRecaudoReal (recaudo)
# Cálculo de acuerdo a SBA
# Agrupar por División - Cluster - Grupo de Producto - SBA

drop_cols = ['Venta', 'Canal', 'ZonaGeografica']
area_calculo_sba = area_calculo_sba_completo_without_renal.copy()
real = df_venta_recaudo_real.copy().drop(columns=drop_cols)
ppto = df_venta_recaudo_presupuesto.copy().drop(columns=drop_cols)


# Sumamos los registros que tienen el mismo conexto para que exista un solo registro
ppto = ppto.groupby(['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Recaudo']].apply(sum)
real = real.groupby(['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Recaudo']].apply(sum)
# ppto.reset_index(inplace=True)
# real.reset_index(inplace=True)

main = pd.merge(
    ppto.rename(columns={'Recaudo': 'Presupuesto'}),
    real.rename(columns={'Recaudo': 'Real'}),
    on=['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'],
    how='left'
)
main['Real'].fillna(0, inplace=True)

main = main.merge(total_empleados, on=['CodigoEmpleado'], how='left')
main = main[main['Fecha'] >= main['FechaIngreso']]

# Traer Consecutivos
main = main.merge(
    area_calculo_sba,
    on=['AreaCalculo', 'Division', 'GrupoProducto', 'SBA', 'TipoEmpleado'],
    how='left'
)
main.dropna(subset=['Consecutivo'], inplace=True)
main = main[main.Presupuesto.notnull()]

### Agrupación a nivel de empleado por clusters
main = pd.merge(
    df_clusters_empleado[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Cluster']],
    main,
#     on=['CodigoEmpleado','TipoEmpleado', 'AreaCalculo', 'Cluster'],
    how='left'
)

main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2450203296.py:13: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ppto = ppto.groupby(['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Recaudo']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2450203296.py:14: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  real = real.groupby(['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Recaudo']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2450203296.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)

,CodigoEmpleado,TipoEmpleado,AreaCalculo,Cluster,Division,GrupoProducto,SBA,Fecha,Presupuesto,Real,FechaIngreso,Consecutivo,_merge
0,5004523,VC,3,6,AE,001,30,2025-01-01,9.509748e+06,26047694.15,2023-10-01,3.0,left_only
1,5004523,VC,3,6,AE,001,30,2025-02-01,6.339832e+06,14518558.00,2023-10-01,3.0,left_only
2,5004523,VC,3,6,AE,001,30,2025-03-01,6.339832e+06,0.00,2023-10-01,3.0,left_only
3,5004523,VC,3,6,AE,001,30,2025-04-01,9.509748e+06,80897900.00,2023-10-01,3.0,left_only
4,5004523,VC,3,6,AE,001,30,2025-05-01,7.396471e+06,0.00,2023-10-01,3.0,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4379,5016782,VC,4,14,HC,CDK,12,2025-08-01,1.396306e+07,0.00,2022-11-01,1.0,left_only
4380,5016782,VC,4,14,HC,CDK,12,2025-09-01,1.304444e+07,0.00,2022-11-01,1.0,left_only
4381,5016782,VC,4,14,HC,CDK,12,2025-10-01,1.543285e+07,0.00,2022-11-01,1.0,left_only
4382,5016782,VC,4,14,HC,CDK,12,2025-11-01,1.341188e+07,0.00,2022-11-01,1.0,left_only
4383,5016782,VC,4,14,HC,CDK,12,2025-12-01,1.451423e+07,0.00,2022-11-01,1.0,left_only

In [180]:
calculo_centro_costo_variable = main.merge(
    df_centros_costos_grupos_productos_divisiones.rename(columns={'ConsecutivoParrilla':'Consecutivo'}),
    on=['Division', 'GrupoProducto'],
    how='left'
)
calculo_centro_costo_variable = calculo_centro_costo_variable.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real']].apply(sum)
calculo_centro_costo_variable['Real'] = calculo_centro_costo_variable.groupby(['CodigoEmpleado', 'Consecutivo', 'GrupoProducto', 'Division', 'CodigoCentroCosto'])['Real'].transform(pd.Series.cumsum)
calculo_centro_costo_variable['RealTotal'] = calculo_centro_costo_variable.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real']].transform(pd.Series.sum)
calculo_centro_costo_variable['Porcentaje Aplicado'] = calculo_centro_costo_variable['Real'] / calculo_centro_costo_variable['RealTotal']
calculo_centro_costo_variable['Variable'] = 'VentaCobradaPortafolioClusterSub'
calculo_centro_costo_variable

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2365333215.py:6: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  calculo_centro_costo_variable = calculo_centro_costo_variable.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2365333215.py:8: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  calculo_centro_costo_variable['RealTotal'] = calculo_centro_costo_variable.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real']].transform(pd.Series.sum)

,CodigoEmpleado,Consecutivo,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,RealTotal,Porcentaje Aplicado,Variable
0,5002790,1.0,2025-01-01,805,AE,323007290,4.503000e+06,5.635590e+06,0.799029,VentaCobradaPortafolioClusterSub
1,5002790,1.0,2025-01-01,M06,AE,323007290,1.132590e+06,5.635590e+06,0.200971,VentaCobradaPortafolioClusterSub
2,5002790,1.0,2025-02-01,805,AE,323007290,6.754500e+06,8.601655e+06,0.785256,VentaCobradaPortafolioClusterSub
3,5002790,1.0,2025-02-01,M06,AE,323007290,1.847155e+06,8.601655e+06,0.214744,VentaCobradaPortafolioClusterSub
4,5002790,1.0,2025-03-01,805,AE,323007290,1.453458e+07,3.064646e+07,0.474266,VentaCobradaPortafolioClusterSub
...,...,...,...,...,...,...,...,...,...,...
2825,70053308,2.0,2025-12-01,620,HC,323015045,2.365264e+08,2.365264e+08,1.000000,VentaCobradaPortafolioClusterSub
2826,70053308,3.0,2025-12-01,680,HC,323015055,9.143000e+05,9.143000e+05,1.000000,VentaCobradaPortafolioClusterSub
2827,70053308,4.0,2025-12-01,610,HC,323015040,6.893062e+07,6.893062e+07,1.000000,VentaCobradaPortafolioClusterSub
2828,70053308,5.0,2025-12-01,660,BA,323007337,0.000000e+00,0.000000e+00,NaN,VentaCobradaPortafolioClusterSub
2829,70053308,5.0,2025-12-01,A45,BA,323007337,0.000000e+00,0.000000e+00,NaN,VentaCobradaPortafolioClusterSub

In [181]:
venta_cobrada_portafolio_cluster_sub_centro_costo = calculo_centro_costo_variable.copy()
venta_cobrada_portafolio_cluster_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main, 'VentaCobradaPortafolioClusterSub')
venta_cobrada_portafolio_cluster_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,5002790_1,2025-01-01,805,AE,323007290,4.503000e+06,6.135271e+06,VentaCobradaPortafolioClusterSub
1,5002790_1,2025-01-01,M06,AE,323007290,1.132590e+06,3.495176e+06,VentaCobradaPortafolioClusterSub
2,5002790_1,2025-02-01,805,AE,323007290,6.754500e+06,1.022545e+07,VentaCobradaPortafolioClusterSub
3,5002790_1,2025-02-01,M06,AE,323007290,1.847155e+06,6.037123e+06,VentaCobradaPortafolioClusterSub
4,5002790_1,2025-03-01,805,AE,323007290,1.453458e+07,1.431563e+07,VentaCobradaPortafolioClusterSub
...,...,...,...,...,...,...,...,...
2825,70053308_2,2025-12-01,620,HC,323015045,2.365264e+08,5.152412e+08,VentaCobradaPortafolioClusterSub
2826,70053308_3,2025-12-01,680,HC,323015055,9.143000e+05,6.414056e+07,VentaCobradaPortafolioClusterSub
2827,70053308_4,2025-12-01,610,HC,323015040,6.893062e+07,1.069660e+08,VentaCobradaPortafolioClusterSub
2828,70053308_5,2025-12-01,660,BA,323007337,0.000000e+00,7.129837e+05,VentaCobradaPortafolioClusterSub
2829,70053308_5,2025-12-01,A45,BA,323007337,0.000000e+00,9.279359e+06,VentaCobradaPortafolioClusterSub

In [182]:
main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Real'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real'] / main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaPortafolioClusterSub'

### Cálculo de resultados cualitativos precargados
main = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=main,
    variable='VentaCobradaPortafolioClusterSub',
    columnas_extra=['CodigoEmpleado', 'Consecutivo'],
    columnas_extra_merge=['CodigoEmpleado', 'Consecutivo']
)
###

main['Contexto'] = main['CodigoEmpleado'] + '_' + main['Consecutivo'].astype(int).astype('str')
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
###

venta_cobrada_portafolio_cluster_sub = main.copy()
main = None
venta_cobrada_portafolio_cluster_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2567566124.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

['CodigoEmpleado', 'Consecutivo'] ['CodigoEmpleado', 'Consecutivo']

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002790_1,VentaCobradaPortafolioClusterSub,2025-01-01,5.635590e+06,9.630447e+06,0.59
1,5002790_1,VentaCobradaPortafolioClusterSub,2025-02-01,8.601655e+06,1.626257e+07,0.53
2,5002790_1,VentaCobradaPortafolioClusterSub,2025-03-01,3.064646e+07,2.289470e+07,1.34
3,5002790_1,VentaCobradaPortafolioClusterSub,2025-04-01,6.084006e+07,3.093643e+07,1.97
4,5002790_1,VentaCobradaPortafolioClusterSub,2025-05-01,9.615206e+07,3.793251e+07,2.53
...,...,...,...,...,...,...
1678,70053308_1,VentaCobradaPortafolioClusterSub,2025-12-01,1.381976e+07,1.121896e+08,0.12
1679,70053308_2,VentaCobradaPortafolioClusterSub,2025-12-01,2.365264e+08,5.152412e+08,0.46
1680,70053308_3,VentaCobradaPortafolioClusterSub,2025-12-01,9.143000e+05,6.414056e+07,0.01
1681,70053308_4,VentaCobradaPortafolioClusterSub,2025-12-01,6.893062e+07,1.069660e+08,0.64
1682,70053308_5,VentaCobradaPortafolioClusterSub,2025-12-01,0.000000e+00,9.992343e+06,0.00

In [183]:
venta_cobrada_portafolio_cluster_sub[
    (venta_cobrada_portafolio_cluster_sub['Contexto'].str.contains('1111128')) & 
    (venta_cobrada_portafolio_cluster_sub['Fecha'] == '2023-12-01')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

### 22.1 Grupo Renal (Hospitalario + Ambulatorio)

In [184]:
area_calculo_sba_renal_drop_duplicates = area_calculo_sba_completo_with_renal[['AreaCalculo','Consecutivo','TipoEmpleado']].drop_duplicates(['AreaCalculo', 'Consecutivo'])
area_calculo_sba_renal_drop_duplicates

     AreaCalculo  Consecutivo TipoEmpleado
262            5            2           VC
265            5            3           VC
274            5            4           VC

In [185]:
area_calculo_sba_renal_vc_drop_duplicates = area_calculo_sba_renal_drop_duplicates[area_calculo_sba_renal_drop_duplicates['TipoEmpleado'] == 'VC']
area_calculo_sba_renal_vc_drop_duplicates

     AreaCalculo  Consecutivo TipoEmpleado
262            5            2           VC
265            5            3           VC
274            5            4           VC

In [186]:
# VentaRecaudoPresupuesto
# VentaRecaudoReal (recaudo)
# Cálculo de acuerdo a SBA
# Agrupar por División - Cluster - Grupo de Producto - SBA

df_renal_ambulatorio_vc = df_renal_ambulatorio[df_renal_ambulatorio['TipoEmpleado'] == 'VC']
df_renal_ambulatorio_vc

,CodigoEmpleado,TipoEmpleado,Fecha,PlanVentaTotal,PlanVentaCobradaRenal,RealVentaTotal,RealVentaCobradaRenal
0,70020733,VC,2025-01-01,0.000000e+00,3.603004e+09,0.000000e+00,3.414838e+09
1,70020733,VC,2025-02-01,0.000000e+00,4.015092e+08,0.000000e+00,2.318170e+08
2,70020733,VC,2025-03-01,1.010107e+08,4.371081e+08,4.898174e+07,3.250664e+08
3,70020733,VC,2025-04-01,1.010107e+08,4.114996e+08,1.168091e+08,6.926579e+08
4,70020733,VC,2025-05-01,1.443010e+07,4.588223e+08,2.900474e+07,3.876283e+08
5,70020733,VC,2025-06-01,1.154408e+08,4.840730e+08,8.478787e+08,2.029854e+08
6,70020733,VC,2025-07-01,2.597418e+08,4.605407e+08,1.653069e+08,3.115334e+08
7,70020733,VC,2025-08-01,2.700667e+08,4.988475e+08,3.039041e+08,3.243254e+08
8,70020733,VC,2025-09-01,1.971858e+08,5.410063e+08,1.199201e+08,1.176529e+09
9,70020733,VC,2025-10-01,1.292057e+09,6.049855e+08,6.530957e+07,3.391433e+08
10,70020733,VC,2025-11-01,2.071648e+08,7.456874e+08,1.566934e+07,2.417650e+08
11,70020733,VC,2025-12-01,1.607648e+08,7.821859e+08,2.764713e+09,5.990458e+09
12,70034174,VC,2025-01-01,1.213789e+08,3.603004e+09,2.454276e+07,3.414838e+09
13,70034174,VC,2025-02-01,1.213789e+08,4.015092e+08,4.674840e+07,2.318170e+08
14,70034174,VC,2025-03-01,1.416088e+08,4.371081e+08,6.440906e+07,3.250664e+08
15,70034174,VC,2025-04-01,1.416088e+08,4.114996e+08,7.236450e+07,6.926579e+08
16,70034174,VC,2025-05-01,1.618386e+08,4.588223e+08,8.410756e+07,3.876283e+08
17,70034174,VC,2025-06-01,1.618386e+08,4.840730e+08,4.493425e+07,2.029854e+08
18,70034174,VC,2025-07-01,3.641368e+08,4.605407e+08,1.203300e+08,3.115334e+08
19,70034174,VC,2025-08-01,1.102847e+09,4.988475e+08,1.280526e+09,3.243254e+08
20,70034174,VC,2025-09-01,3.596640e+08,5.410063e+08,2.766229e+08,1.176529e+09
21,70034174,VC,2025-10-01,1.468791e+09,6.049855e+08,2.446175e+08,3.391433e+08
22,70034174,VC,2025-11-01,3.751859e+08,7.456874e+08,2.122314e+09,2.417650e+08
23,70034174,VC,2025-12-01,1.858344e+08,7.821859e+08,1.390872e+09,5.990458e+09

In [187]:
# Calcular

main = df_renal_ambulatorio_vc.rename(columns={'PlanVentaCobradaRenal': 'Presupuesto', 'RealVentaCobradaRenal': 'Real'})
main = main.merge(
    area_calculo_sba_renal_vc_drop_duplicates,
    on=['TipoEmpleado'],
    how='left'
)
main

,CodigoEmpleado,TipoEmpleado,Fecha,PlanVentaTotal,Presupuesto,RealVentaTotal,Real,AreaCalculo,Consecutivo
0,70020733,VC,2025-01-01,0.000000e+00,3.603004e+09,0.000000e+00,3.414838e+09,5,2
1,70020733,VC,2025-01-01,0.000000e+00,3.603004e+09,0.000000e+00,3.414838e+09,5,3
2,70020733,VC,2025-01-01,0.000000e+00,3.603004e+09,0.000000e+00,3.414838e+09,5,4
3,70020733,VC,2025-02-01,0.000000e+00,4.015092e+08,0.000000e+00,2.318170e+08,5,2
4,70020733,VC,2025-02-01,0.000000e+00,4.015092e+08,0.000000e+00,2.318170e+08,5,3
...,...,...,...,...,...,...,...,...,...
67,70034174,VC,2025-11-01,3.751859e+08,7.456874e+08,2.122314e+09,2.417650e+08,5,3
68,70034174,VC,2025-11-01,3.751859e+08,7.456874e+08,2.122314e+09,2.417650e+08,5,4
69,70034174,VC,2025-12-01,1.858344e+08,7.821859e+08,1.390872e+09,5.990458e+09,5,2
70,70034174,VC,2025-12-01,1.858344e+08,7.821859e+08,1.390872e+09,5.990458e+09,5,3
71,70034174,VC,2025-12-01,1.858344e+08,7.821859e+08,1.390872e+09,5.990458e+09,5,4

In [188]:
main['Contexto'] = main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')

main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaPortafolioClusterSub'


#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real','Presupuesto', 'PorcentajeCumplimiento']]

venta_cobrada_portafolio_cluster_sub = pd.concat([
     venta_cobrada_portafolio_cluster_sub.copy(),
     main.copy()
   ], 
   ignore_index=True
 )
# venta_cobrada_portafolio_cluster_sub = main.copy()
main = None
venta_cobrada_portafolio_cluster_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1215801995.py:3: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002790_1,VentaCobradaPortafolioClusterSub,2025-01-01,5.635590e+06,9.630447e+06,0.59
1,5002790_1,VentaCobradaPortafolioClusterSub,2025-02-01,8.601655e+06,1.626257e+07,0.53
2,5002790_1,VentaCobradaPortafolioClusterSub,2025-03-01,3.064646e+07,2.289470e+07,1.34
3,5002790_1,VentaCobradaPortafolioClusterSub,2025-04-01,6.084006e+07,3.093643e+07,1.97
4,5002790_1,VentaCobradaPortafolioClusterSub,2025-05-01,9.615206e+07,3.793251e+07,2.53
...,...,...,...,...,...,...
1750,70034174_4,VentaCobradaPortafolioClusterSub,2025-08-01,5.890852e+09,6.755404e+09,0.87
1751,70034174_4,VentaCobradaPortafolioClusterSub,2025-09-01,7.067381e+09,7.296411e+09,0.97
1752,70034174_4,VentaCobradaPortafolioClusterSub,2025-10-01,7.406524e+09,7.901396e+09,0.94
1753,70034174_4,VentaCobradaPortafolioClusterSub,2025-11-01,7.648289e+09,8.647083e+09,0.88
1754,70034174_4,VentaCobradaPortafolioClusterSub,2025-12-01,1.363875e+10,9.429269e+09,1.45

## 23. Venta Facturada Portafolio Cluster (VentaFacturadaPortafolioCluster)

In [189]:
# VentaRecaudoPresupuesto
# VentaRecaudoReal (Venta)

# Merge de tablas
drop_cols = ['Recaudo', 'ZonaGeografica', 'Canal']
area_calculo_sba = area_calculo_sba_completo.copy()
real = df_venta_recaudo_real.copy().drop(columns=drop_cols)
ppto = df_venta_recaudo_presupuesto.copy().drop(columns=drop_cols)

# Sumamos los registros que tienen el mismo conexto para que exista un solo registro
ppto = ppto.groupby(['CodigoEmpleado', 'Cluster', 'Division', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Venta']].apply(sum)
real = real.groupby(['CodigoEmpleado', 'Cluster', 'Division', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Venta']].apply(sum)
ppto.reset_index(inplace=True)
real.reset_index(inplace=True)

main = ppto.rename(columns={'Venta': 'Presupuesto'}).merge(
    real.rename(columns={'Venta': 'Real'}),
    on=['CodigoEmpleado', 'Cluster', 'Division', 'GrupoProducto', 'SBA', 'Fecha'],
    how='left'
)
main['Real'].fillna(0, inplace=True)

# Traer áreas de cálculo y tipo de empleado de la maestra de empleados
empleados = df_empleados[['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo', 'FechaIngreso']].copy()
main = main.merge(empleados, on=['CodigoEmpleado'], how='left')

main = main[main['Fecha'] >= main['FechaIngreso']]

main = main.merge(
    area_calculo_sba,
    on=['AreaCalculo', 'Division', 'GrupoProducto', 'SBA', 'TipoEmpleado'],
    how='left'
)
main.dropna(subset=['Consecutivo'], inplace=True)
main = main[main.Presupuesto.notnull()]

main = main.groupby(['CodigoEmpleado', 'AreaCalculo', 'Cluster', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

# Validación. Se eliminan presupuestos  = 0
main['Real'].fillna(0, inplace=True)
main['AreaCalculo'].fillna(0, inplace=True)
main = main[main.Presupuesto.notnull()]

# Calcular
main = main.groupby(['CodigoEmpleado', 'Cluster', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

### Agrupación a nivel de empleado por clusters
main = pd.merge(
    df_clusters_empleado[['CodigoEmpleado', 'Cluster']],
    main,
    on=['CodigoEmpleado', 'Cluster'],
    how='left'
)

main = main.groupby(['CodigoEmpleado', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Real'] = main.groupby(['CodigoEmpleado'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaPortafolioCluster'
main['Contexto'] = main['CodigoEmpleado']
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]   
###


venta_facturada_portafolio_cluster = main.copy()
main = None
venta_facturada_portafolio_cluster

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3339067109.py:11: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ppto = ppto.groupby(['CodigoEmpleado', 'Cluster', 'Division', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3339067109.py:12: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  real = real.groupby(['CodigoEmpleado', 'Cluster', 'Division', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3339067109.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3339067109.py:37: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'AreaCalculo', 'Cluster', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3339067109.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3339067109.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['AreaCalculo'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3339067109.py:46: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Cluster', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3339067109.py:57: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002790,VentaFacturadaPortafolioCluster,2025-01-01,2.096626e+08,2.996496e+08,0.70
1,5002790,VentaFacturadaPortafolioCluster,2025-02-01,6.094085e+08,6.646988e+08,0.92
2,5002790,VentaFacturadaPortafolioCluster,2025-03-01,9.942805e+08,1.079828e+09,0.92
3,5002790,VentaFacturadaPortafolioCluster,2025-04-01,1.321016e+09,1.426956e+09,0.93
4,5002790,VentaFacturadaPortafolioCluster,2025-05-01,1.740225e+09,1.830167e+09,0.95
...,...,...,...,...,...,...
341,70048318,VentaFacturadaPortafolioCluster,2025-11-01,2.089264e+09,2.387163e+09,0.88
342,70048318,VentaFacturadaPortafolioCluster,2025-12-01,3.605953e+09,3.208797e+09,1.12
343,70051944,VentaFacturadaPortafolioCluster,2025-11-01,1.104266e+08,2.700918e+08,0.41
344,70051944,VentaFacturadaPortafolioCluster,2025-12-01,4.439280e+08,5.333994e+08,0.83
345,70053308,VentaFacturadaPortafolioCluster,2025-12-01,5.670514e+08,1.029214e+09,0.55

In [190]:
venta_facturada_portafolio_cluster[
    (venta_facturada_portafolio_cluster['Contexto'] == '1111115')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 24. Venta Facturada Portafolio Cluster sub (VentaFacturadaPortafolioClusterSub)

In [191]:
drop_cols = ['Recaudo', 'Canal', 'ZonaGeografica']
area_calculo_sba = area_calculo_sba_completo.copy()
real = df_venta_recaudo_real.copy().drop(columns=drop_cols)
ppto = df_venta_recaudo_presupuesto.copy().drop(columns=drop_cols)


# Sumamos los registros que tienen el mismo conexto para que exista un solo registro
ppto = ppto.groupby(['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Venta']].apply(sum)
real = real.groupby(['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Venta']].apply(sum)
ppto.reset_index(inplace=True)
real.reset_index(inplace=True)

main = pd.merge(
    ppto.rename(columns={'Venta': 'Presupuesto'}).drop(columns=['index']),
    real.rename(columns={'Venta': 'Real'}).drop(columns=['index']),
    on=['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'],
    how='left'
)
main['Real'].fillna(0, inplace=True)


# Traer áreas de cálculo y tipo de empleado de la maestra de empleados
empleados = df_empleados[['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo', 'FechaIngreso']].copy()
main = main.merge(empleados, on=['CodigoEmpleado'], how='left')

main = main[main['Fecha'] >= main['FechaIngreso']]

# Traer Consecutivos
main = main.merge(
    area_calculo_sba,
    on=['AreaCalculo', 'Division', 'GrupoProducto', 'SBA', 'TipoEmpleado'],
    how='left'
)
main.dropna(subset=['Consecutivo'], inplace=True)
main = main[main.Presupuesto.notnull()]
main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\397817390.py:8: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ppto = ppto.groupby(['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\397817390.py:9: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  real = real.groupby(['CodigoEmpleado','Division', 'Cluster', 'GrupoProducto', 'SBA', 'Fecha'], as_index=False)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\397817390.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)

,CodigoEmpleado,Division,Cluster,GrupoProducto,SBA,Fecha,Presupuesto,Real,TipoEmpleado,AreaCalculo,FechaIngreso,Consecutivo
0,5002699,HC,0,680,03,2025-03-01,0.000000e+00,0.00,VE,7.0,2021-09-01,2.0
1,5002699,HC,0,680,03,2025-04-01,0.000000e+00,46758900.00,VE,7.0,2021-09-01,2.0
2,5002699,HC,0,680,03,2025-05-01,0.000000e+00,-1372600.00,VE,7.0,2021-09-01,2.0
3,5002699,HC,0,680,03,2025-07-01,0.000000e+00,2354500.00,VE,7.0,2021-09-01,2.0
4,5002699,HC,0,680,03,2025-09-01,0.000000e+00,2403800.00,VE,7.0,2021-09-01,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5514,70053308,HC,9,620,36,2025-12-01,3.719191e+07,4624715.00,VC,4.0,2025-12-01,2.0
5515,70053308,HC,9,630,03,2025-12-01,1.292955e+06,0.00,VC,4.0,2025-12-01,1.0
5516,70053308,HC,9,630,08,2025-12-01,8.027078e+07,58490350.07,VC,4.0,2025-12-01,1.0
5517,70053308,HC,9,630,12,2025-12-01,6.439900e+07,42032685.00,VC,4.0,2025-12-01,1.0
5518,70053308,HC,9,680,03,2025-12-01,5.929643e+07,24073101.00,VC,4.0,2025-12-01,3.0

In [192]:
main_centro_costo = pd.merge(
    df_empleados_centros_costos,
    main,
    on=['CodigoEmpleado'],
    how='right'
)
main_centro_costo

,CodigoEmpleado,CodigoCentroCosto,PorcentajeAsignacion,Division,Cluster,GrupoProducto,SBA,Fecha,Presupuesto,Real,TipoEmpleado,AreaCalculo,FechaIngreso,Consecutivo
0,5002699,323015095,0.80,HC,0,680,03,2025-03-01,0.000000e+00,0.00,VE,7.0,2021-09-01,2.0
1,5002699,323015100,0.20,HC,0,680,03,2025-03-01,0.000000e+00,0.00,VE,7.0,2021-09-01,2.0
2,5002699,323015095,0.80,HC,0,680,03,2025-04-01,0.000000e+00,46758900.00,VE,7.0,2021-09-01,2.0
3,5002699,323015100,0.20,HC,0,680,03,2025-04-01,0.000000e+00,46758900.00,VE,7.0,2021-09-01,2.0
4,5002699,323015095,0.80,HC,0,680,03,2025-05-01,0.000000e+00,-1372600.00,VE,7.0,2021-09-01,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12678,70053308,323015075,0.95,HC,9,630,08,2025-12-01,8.027078e+07,58490350.07,VC,4.0,2025-12-01,1.0
12679,70053308,323007337,0.05,HC,9,630,12,2025-12-01,6.439900e+07,42032685.00,VC,4.0,2025-12-01,1.0
12680,70053308,323015075,0.95,HC,9,630,12,2025-12-01,6.439900e+07,42032685.00,VC,4.0,2025-12-01,1.0
12681,70053308,323007337,0.05,HC,9,680,03,2025-12-01,5.929643e+07,24073101.00,VC,4.0,2025-12-01,3.0
12682,70053308,323015075,0.95,HC,9,680,03,2025-12-01,5.929643e+07,24073101.00,VC,4.0,2025-12-01,3.0

In [193]:
venta_facturada_portafolio_cluster_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main_centro_costo, 'VentaFacturadaPortafolioClusterSub')
venta_facturada_portafolio_cluster_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,5002699_2,2025-03-01,680,HC,323015095,0.00,0.000000e+00,VentaFacturadaPortafolioClusterSub
1,5002699_2,2025-03-01,680,HC,323015100,0.00,0.000000e+00,VentaFacturadaPortafolioClusterSub
2,5002699_2,2025-04-01,680,HC,323015095,46758900.00,0.000000e+00,VentaFacturadaPortafolioClusterSub
3,5002699_2,2025-04-01,680,HC,323015100,46758900.00,0.000000e+00,VentaFacturadaPortafolioClusterSub
4,5002699_2,2025-05-01,680,HC,323015095,45386300.00,0.000000e+00,VentaFacturadaPortafolioClusterSub
...,...,...,...,...,...,...,...,...
8619,70053308_4,2025-12-01,610,HC,323015075,64354603.55,1.065996e+08,VentaFacturadaPortafolioClusterSub
8620,70053308_5,2025-12-01,660,BA,323007337,0.00,7.426914e+05,VentaFacturadaPortafolioClusterSub
8621,70053308_5,2025-12-01,660,BA,323015075,0.00,7.426914e+05,VentaFacturadaPortafolioClusterSub
8622,70053308_5,2025-12-01,A45,BA,323007337,0.00,6.889184e+06,VentaFacturadaPortafolioClusterSub
8623,70053308_5,2025-12-01,A45,BA,323015075,0.00,6.889184e+06,VentaFacturadaPortafolioClusterSub

In [194]:
main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Cluster', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)
main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1021174523.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Cluster', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,index,TipoEmpleado,AreaCalculo,Consecutivo,Cluster,Fecha,Real,Presupuesto
0,0,GC,1.0,2.0,2,2025-08-01,1.652678e+07,0.000000e+00
1,1,GD,2.0,1.0,0,2025-01-01,0.000000e+00,8.935692e+07
2,2,GD,2.0,1.0,0,2025-02-01,0.000000e+00,1.035478e+08
3,3,GD,2.0,1.0,0,2025-03-01,0.000000e+00,1.277524e+08
4,4,GD,2.0,1.0,0,2025-04-01,0.000000e+00,1.091358e+08
...,...,...,...,...,...,...,...,...
2055,2055,VE,11.0,1.0,22,2025-08-01,1.932286e+08,2.524500e+08
2056,2056,VE,11.0,1.0,22,2025-09-01,1.175621e+08,2.805000e+08
2057,2057,VE,11.0,1.0,22,2025-10-01,1.569184e+08,2.805000e+08
2058,2058,VE,11.0,1.0,22,2025-11-01,1.864203e+08,2.805000e+08
2059,2059,VE,11.0,1.0,22,2025-12-01,3.494745e+08,2.805000e+08

In [195]:
main[
    (main['TipoEmpleado'] == 'VC') &
    (main['AreaCalculo'] == 3)
]

,index,TipoEmpleado,AreaCalculo,Consecutivo,Cluster,Fecha,Real,Presupuesto
127,127,VC,3.0,1.0,1,2025-09-01,7.130878e+07,6.532052e+07
128,128,VC,3.0,1.0,1,2025-10-01,1.171379e+08,6.532052e+07
129,129,VC,3.0,1.0,1,2025-11-01,1.502935e+08,7.257835e+07
130,130,VC,3.0,1.0,1,2025-12-01,2.302742e+08,7.257835e+07
131,131,VC,3.0,1.0,10,2025-01-01,2.557755e+07,2.921423e+07
...,...,...,...,...,...,...,...,...
1118,1118,VC,3.0,6.0,9,2025-08-01,1.842156e+07,2.981961e+07
1119,1119,VC,3.0,6.0,9,2025-09-01,1.040161e+07,2.981961e+07
1120,1120,VC,3.0,6.0,9,2025-10-01,9.452560e+06,3.239138e+07
1121,1121,VC,3.0,6.0,9,2025-11-01,1.029379e+07,3.239138e+07
1122,1122,VC,3.0,6.0,9,2025-12-01,1.054988e+07,2.650632e+07

In [196]:
for x in ['1111135', '1111134']:
    _x = df_clusters_empleado[
        (df_clusters_empleado['CodigoEmpleado'] == x)
    ]
    print(_x)

Empty DataFrame
Columns: [Cluster, CodigoEmpleado, TipoEmpleado, AreaCalculo]
Index: []
Empty DataFrame
Columns: [Cluster, CodigoEmpleado, TipoEmpleado, AreaCalculo]
Index: []

In [197]:


### Agrupación a nivel de empleado por clusters
main = pd.merge(
    df_clusters_empleado[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Cluster']],
    main,
    on=['TipoEmpleado', 'AreaCalculo', 'Cluster'],
    how='left'
)

main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###
main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3511048580.py:9: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

      index CodigoEmpleado  Consecutivo      Fecha         Real   Presupuesto
0         0        5002790          1.0 2025-01-01   4040345.28  5.706280e+06
1         1        5002790          1.0 2025-02-01  23532490.00  7.829029e+06
2         2        5002790          1.0 2025-03-01  17065642.50  8.490994e+06
3         3        5002790          1.0 2025-04-01  29204376.37  8.490994e+06
4         4        5002790          1.0 2025-05-01  15644063.54  8.821976e+06
...     ...            ...          ...        ...          ...           ...
1801   1801       70055621          5.0 2025-08-01   6472000.00  3.437270e+07
1802   1802       70055621          5.0 2025-09-01  86270820.00  3.819189e+07
1803   1803       70055621          5.0 2025-10-01  12743200.00  3.570693e+08
1804   1804       70055621          5.0 2025-11-01         0.00  3.819189e+07
1805   1805       70055621          5.0 2025-12-01  50321627.00  3.819189e+07

[1806 rows x 6 columns]

In [198]:
main['Real'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaPortafolioClusterSub'
main['Contexto'] = main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]   
###


venta_facturada_portafolio_cluster_sub = main.copy()
main = None
venta_facturada_portafolio_cluster_sub

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002790_1,VentaFacturadaPortafolioClusterSub,2025-01-01,4.040345e+06,5.706280e+06,0.71
1,5002790_1,VentaFacturadaPortafolioClusterSub,2025-02-01,2.757284e+07,1.353531e+07,2.04
2,5002790_1,VentaFacturadaPortafolioClusterSub,2025-03-01,4.463848e+07,2.202630e+07,2.03
3,5002790_1,VentaFacturadaPortafolioClusterSub,2025-04-01,7.384285e+07,3.051730e+07,2.42
4,5002790_1,VentaFacturadaPortafolioClusterSub,2025-05-01,8.948692e+07,3.933927e+07,2.27
...,...,...,...,...,...,...
1801,70055621_5,VentaFacturadaPortafolioClusterSub,2025-08-01,3.644305e+08,2.291513e+08,1.59
1802,70055621_5,VentaFacturadaPortafolioClusterSub,2025-09-01,4.507013e+08,2.673432e+08,1.69
1803,70055621_5,VentaFacturadaPortafolioClusterSub,2025-10-01,4.634445e+08,6.244125e+08,0.74
1804,70055621_5,VentaFacturadaPortafolioClusterSub,2025-11-01,4.634445e+08,6.626044e+08,0.70
1805,70055621_5,VentaFacturadaPortafolioClusterSub,2025-12-01,5.137662e+08,7.007963e+08,0.73

In [199]:
venta_facturada_portafolio_cluster_sub[venta_facturada_portafolio_cluster_sub['Contexto'].str.contains('1111135')]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [200]:
df_empleados[df_empleados['CodigoEmpleado'] == '1111135']

Empty DataFrame
Columns: [TipoEmpleado, CodigoEmpleado, Identificacion, CorreoElectronico, Nombre, Apellidos, SalarioVariable, FechaIngreso, FechaRetiro, AreaCalculo]
Index: []

## 25. Venta cobrada y facturada portafolio (VentaCobradaPortafolioPais, VentaFacturadaPortafolioZonaSub, VentaCobradaPortafolioZona, VentaCobradaPortafolioClusterSub, VentaFacturadaPorfafolioCluster)

In [201]:
def pre_merge_venta_cobrada_zona_hospitalaria_sub(x):
    x['Consecutivo'] = x['Consecutivo'].astype('str')
    return x

### 25.1 Para VE

In [202]:
area_calculo_sba_completo_ve = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='VE']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los VE
venta_recaudo_presupuesto_original_ve_real = area_calculo_sba_completo_ve.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'ZonaGeografica', 'Cluster', 'Canal', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los VE
venta_recaudo_presupuesto_original_ve_presupuesto = area_calculo_sba_completo_ve.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'ZonaGeografica', 'Cluster', 'Canal', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#### 25.1.1 VentaCobradaPortafolioPais

In [203]:
recaudo_real_ve = venta_recaudo_presupuesto_original_ve_real.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_ve.rename(columns={'Recaudo': 'Real'}, inplace=True)

recaudo_presupuesto_ve = venta_recaudo_presupuesto_original_ve_presupuesto.groupby(['AreaCalculo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_ve.rename(columns={'Recaudo': 'Presupuesto'}, inplace=True)

main = pd.merge(
    left=recaudo_presupuesto_ve,
    right=recaudo_real_ve,
    on=['AreaCalculo', 'Fecha'],
    how='left'
)

# TODO Validar si los resultados anteriores a fecha de ingreso se ignoran para TODOS

main['Real'].fillna(0.0, inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Real'] = main.groupby(['AreaCalculo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['AreaCalculo'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = main['Real'] / main['Presupuesto']
main['PorcentajeCumplimiento'] = main['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

main['AreaCalculo'] = main['AreaCalculo'].astype('str')
main['Contexto'] = 'VE_' + main['AreaCalculo']
main['Variable'] = 'VentaCobradaPortafolioPais'
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

venta_cobrada_portafolio_pais_ve = main.copy()
main = None

venta_cobrada_portafolio_pais_ve

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\566236500.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,VE_1,VentaCobradaPortafolioPais,2025-01-01,1.616622e+09,1.037116e+09,1.56
1,VE_1,VentaCobradaPortafolioPais,2025-02-01,2.593089e+09,2.071953e+09,1.25
2,VE_1,VentaCobradaPortafolioPais,2025-03-01,3.750464e+09,3.313089e+09,1.13
3,VE_1,VentaCobradaPortafolioPais,2025-04-01,5.494897e+09,4.757687e+09,1.15
4,VE_1,VentaCobradaPortafolioPais,2025-05-01,6.710125e+09,6.612214e+09,1.01
...,...,...,...,...,...,...
139,VE_13,VentaCobradaPortafolioPais,2025-08-01,9.362099e+09,1.113746e+10,0.84
140,VE_13,VentaCobradaPortafolioPais,2025-09-01,1.171540e+10,1.254808e+10,0.93
141,VE_13,VentaCobradaPortafolioPais,2025-10-01,1.302475e+10,1.409964e+10,0.92
142,VE_13,VentaCobradaPortafolioPais,2025-11-01,1.393058e+10,1.544692e+10,0.90
143,VE_13,VentaCobradaPortafolioPais,2025-12-01,1.636932e+10,1.705661e+10,0.96

In [204]:
venta_cobrada_portafolio_pais_ve[
    (venta_cobrada_portafolio_pais_ve['Contexto'] == 'VE_4')
]

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
36,VE_4,VentaCobradaPortafolioPais,2025-01-01,5.328649e+09,5.725328e+09,0.93
37,VE_4,VentaCobradaPortafolioPais,2025-02-01,9.719334e+09,1.112971e+10,0.87
38,VE_4,VentaCobradaPortafolioPais,2025-03-01,1.486752e+10,1.682216e+10,0.88
39,VE_4,VentaCobradaPortafolioPais,2025-04-01,2.051346e+10,2.307384e+10,0.89
40,VE_4,VentaCobradaPortafolioPais,2025-05-01,2.623285e+10,2.940014e+10,0.89
41,VE_4,VentaCobradaPortafolioPais,2025-06-01,3.090480e+10,3.487449e+10,0.89
42,VE_4,VentaCobradaPortafolioPais,2025-07-01,3.642981e+10,3.979021e+10,0.92
43,VE_4,VentaCobradaPortafolioPais,2025-08-01,4.079197e+10,4.702124e+10,0.87
44,VE_4,VentaCobradaPortafolioPais,2025-09-01,4.694400e+10,5.379232e+10,0.87
45,VE_4,VentaCobradaPortafolioPais,2025-10-01,5.330031e+10,6.010725e+10,0.89
46,VE_4,VentaCobradaPortafolioPais,2025-11-01,5.784327e+10,6.640797e+10,0.87
47,VE_4,VentaCobradaPortafolioPais,2025-12-01,6.372284e+10,7.229788e+10,0.88

In [205]:
venta_cobrada_portafolio_pais_ve[
    (venta_cobrada_portafolio_pais_ve['Contexto'] == 'VE_7')
]

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
60,VE_7,VentaCobradaPortafolioPais,2025-01-01,1.759017e+09,2.215315e+09,0.79
61,VE_7,VentaCobradaPortafolioPais,2025-02-01,3.653215e+09,4.532188e+09,0.81
62,VE_7,VentaCobradaPortafolioPais,2025-03-01,5.665503e+09,7.106881e+09,0.80
63,VE_7,VentaCobradaPortafolioPais,2025-04-01,7.734683e+09,8.677150e+09,0.89
64,VE_7,VentaCobradaPortafolioPais,2025-05-01,1.009738e+10,1.058514e+10,0.95
65,VE_7,VentaCobradaPortafolioPais,2025-06-01,1.190666e+10,1.297341e+10,0.92
66,VE_7,VentaCobradaPortafolioPais,2025-07-01,1.444369e+10,1.515033e+10,0.95
67,VE_7,VentaCobradaPortafolioPais,2025-08-01,1.649220e+10,1.765910e+10,0.93
68,VE_7,VentaCobradaPortafolioPais,2025-09-01,1.969583e+10,2.034814e+10,0.97
69,VE_7,VentaCobradaPortafolioPais,2025-10-01,2.233073e+10,2.318744e+10,0.96
70,VE_7,VentaCobradaPortafolioPais,2025-11-01,2.448776e+10,2.691728e+10,0.91
71,VE_7,VentaCobradaPortafolioPais,2025-12-01,2.741906e+10,2.969355e+10,0.92

#### 25.1.2 VentaCobradaPortafolioZona

In [206]:
print(venta_recaudo_presupuesto_original_ve_real)

recaudo_real_zona_ve = venta_recaudo_presupuesto_original_ve_real.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_zona_ve.rename(columns={'Recaudo': 'Real'}, inplace=True)

recaudo_presupuesto_zona_ve = venta_recaudo_presupuesto_original_ve_presupuesto.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_zona_ve.rename(columns={'Recaudo': 'Presupuesto'}, inplace=True)

main = pd.merge(
    left=recaudo_presupuesto_zona_ve,
    right=recaudo_real_zona_ve,
    on=['ZonaGeografica', 'AreaCalculo', 'Fecha'],
    how='left'
)

main['Real'].fillna(0.0, inplace=True)

main['Real'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha'])['Real'].transform(pd.Series.sum)
main['Presupuesto'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha'])['Presupuesto'].transform(pd.Series.sum)

main['TipoEmpleado'] = 'VE'

### Agrupación a nivel de empleado por zonas
main = pd.merge(
    df_zonas_empleado[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Zona']].rename(columns={'Zona': 'ZonaGeografica'}),
    main,
    on=['TipoEmpleado', 'AreaCalculo', 'ZonaGeografica'],
    how='left'
)

main = pd.merge(
    main,
    df_empleados[['CodigoEmpleado', 'FechaIngreso']],
    on='CodigoEmpleado',
    how='left'
)
main = main[main['Fecha'] >= main['FechaIngreso']]

main = main.groupby(['CodigoEmpleado', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###


main['Real'] = main.groupby(['CodigoEmpleado'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaPortafolioZona'
main['Contexto'] = main['CodigoEmpleado']
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
###

venta_cobrada_portafolio_zona_ve = main.copy()
main = None

venta_cobrada_portafolio_zona_ve

       AreaCalculo  Consecutivo Division GrupoProducto SBA TipoEmpleado  \
0                2            1       AE           CEK  30           VE
1                2            1       AE           CEK  30           VE
2                2            1       AE           CEK  30           VE
3                2            1       AE           CEK  30           VE
4                2            1       AE           CEK  30           VE
...            ...          ...      ...           ...  ..          ...
26144           13            2       AE           801  33           VE
26145           13            2       AE           801  33           VE
26146           13            2       AE           801  33           VE
26147           13            2       AE           801  33           VE
26148           13            2       AE           801  31           VE

      ZonaGeografica Cluster                    Canal      Fecha       Venta  \
0       Suroccidente      12             Distribuidor 2025-02-01    323000.0
1             Centro       5         Hospital Público 2025-01-01         0.0
2             Centro       5         Hospital Público 2025-02-01         0.0
3             Centro       5         Hospital Público 2025-03-01         0.0
4             Centro       5         Hospital Público 2025-04-01         0.0
...              ...     ...                      ...        ...         ...
26144         Centro       7             Distribuidor 2025-11-01         0.0
26145         Centro       7             Distribuidor 2025-12-01         0.0
26146          Norte      15                 HOSPITAL 2025-02-01    300000.0
26147          Norte      15                 HOSPITAL 2025-03-01    -17850.0
26148         Centro       0  Televentas Distribuidor 2025-12-01  11344000.0

          Recaudo
0             0.0
1             0.0
2             0.0
3             0.0
4             0.0
...           ...
26144         0.0
26145         0.0
26146         0.0
26147    282150.0
26148  11344000.0

[26149 rows x 12 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2246871531.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2246871531.py:39: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002697,VentaCobradaPortafolioZona,2025-01-01,3.437280e+09,3.512007e+09,0.98
1,5002697,VentaCobradaPortafolioZona,2025-02-01,6.854343e+09,7.148647e+09,0.96
2,5002697,VentaCobradaPortafolioZona,2025-03-01,9.942302e+09,1.102280e+10,0.90
3,5002697,VentaCobradaPortafolioZona,2025-04-01,1.386146e+10,1.413477e+10,0.98
4,5002697,VentaCobradaPortafolioZona,2025-05-01,1.722807e+10,1.766088e+10,0.98
...,...,...,...,...,...,...
198,70034526,VentaCobradaPortafolioZona,2025-08-01,1.096560e+10,1.368841e+10,0.80
199,70034526,VentaCobradaPortafolioZona,2025-09-01,1.285616e+10,1.592386e+10,0.81
200,70034526,VentaCobradaPortafolioZona,2025-10-01,1.455372e+10,1.800791e+10,0.81
201,70034526,VentaCobradaPortafolioZona,2025-11-01,1.616655e+10,2.001898e+10,0.81
202,70034526,VentaCobradaPortafolioZona,2025-12-01,1.768431e+10,2.196493e+10,0.81

In [207]:
def _get_or_create_zona_cluster(empleado, cluster, zona):
    if not empleado or not (cluster or zona):
        return False
    return True

_get_or_create_zona_cluster(True, True, None)

True

#### 25.1.3 VentaFacturadaPortafolioZonaSub

In [208]:
venta_real_zona_consecutivo_ve = venta_recaudo_presupuesto_original_ve_real.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_real_zona_consecutivo_ve.rename(columns={'Venta': 'Real'}, inplace=True)

venta_presupuesto_zona_consecutivo_ve = venta_recaudo_presupuesto_original_ve_presupuesto.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_presupuesto_zona_consecutivo_ve.rename(columns={'Venta': 'Presupuesto'}, inplace=True)

main = pd.merge(
    left=venta_presupuesto_zona_consecutivo_ve,
    right=venta_real_zona_consecutivo_ve,
    on=['ZonaGeografica', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)

main['Real'].fillna(0.0, inplace=True)

main['Real'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'])['Real'].transform(pd.Series.sum)
main['Presupuesto'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'])['Presupuesto'].transform(pd.Series.sum)

main['Consecutivo'] = main['Consecutivo'].astype('str')
main['TipoEmpleado'] = 'VE'

### Agrupación a nivel de empleado por zonas
main = pd.merge(
    df_zonas_empleado[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Zona']].rename(columns={'Zona': 'ZonaGeografica'}),
    main,
    on=['TipoEmpleado', 'AreaCalculo', 'ZonaGeografica'],
    how='left'
)

main = pd.merge(
    main,
    df_empleados[['CodigoEmpleado', 'FechaIngreso']],
    on='CodigoEmpleado',
    how='left'
)
main = main[main['Fecha'] >= main['FechaIngreso']]

main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Real'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaPortafolioZonaSub'
main['Contexto'] = main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
###

venta_facturada_portafolio_zona_sub_ve = main.copy()
main = None

venta_facturada_portafolio_zona_sub_ve

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2683280001.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2683280001.py:38: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002697_1,VentaFacturadaPortafolioZonaSub,2025-01-01,7.002450e+08,1.089093e+09,0.64
1,5002697_1,VentaFacturadaPortafolioZonaSub,2025-02-01,1.693993e+09,2.591321e+09,0.65
2,5002697_1,VentaFacturadaPortafolioZonaSub,2025-03-01,2.677030e+09,3.675689e+09,0.73
3,5002697_1,VentaFacturadaPortafolioZonaSub,2025-04-01,3.684315e+09,4.798816e+09,0.77
4,5002697_1,VentaFacturadaPortafolioZonaSub,2025-05-01,5.116284e+09,6.262284e+09,0.82
...,...,...,...,...,...,...
604,70034526_3,VentaFacturadaPortafolioZonaSub,2025-08-01,1.876151e+09,2.308196e+09,0.81
605,70034526_3,VentaFacturadaPortafolioZonaSub,2025-09-01,2.281637e+09,2.589591e+09,0.88
606,70034526_3,VentaFacturadaPortafolioZonaSub,2025-10-01,2.577061e+09,2.893802e+09,0.89
607,70034526_3,VentaFacturadaPortafolioZonaSub,2025-11-01,2.955614e+09,3.300683e+09,0.90
608,70034526_3,VentaFacturadaPortafolioZonaSub,2025-12-01,3.468584e+09,3.582078e+09,0.97

#### 25.1.4 VentaCobradaPortafolioCluster

In [209]:
recaudo_real_cluster_ve = venta_recaudo_presupuesto_original_ve_real.groupby(['AreaCalculo', 'Cluster', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_cluster_ve.rename(columns={'Recaudo': 'Real'}, inplace=True)

recaudo_presupuesto_cluster_ve = venta_recaudo_presupuesto_original_ve_presupuesto.groupby(['AreaCalculo', 'Cluster', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_cluster_ve.rename(columns={'Recaudo': 'Presupuesto'}, inplace=True)

main = pd.merge(
    left=recaudo_presupuesto_cluster_ve,
    right=recaudo_real_cluster_ve,
    on=['Cluster', 'AreaCalculo', 'Fecha'],
    how='left'
)

main['Real'].fillna(0.0, inplace=True)

main['Real'] = main.groupby(['AreaCalculo', 'Cluster', 'Fecha'])['Real'].transform(pd.Series.sum)
main['Presupuesto'] = main.groupby(['AreaCalculo', 'Cluster', 'Fecha'])['Presupuesto'].transform(pd.Series.sum)

main['TipoEmpleado'] = 'VE'

### Agrupación a nivel de empleado por zonas
main = pd.merge(
    df_clusters_empleado[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Cluster']],
    main,
    on=['TipoEmpleado', 'AreaCalculo', 'Cluster'],
    how='left'
)
main = main.groupby(['CodigoEmpleado', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

main = pd.merge(
    left=main,
    right=df_empleados[['CodigoEmpleado', 'FechaIngreso']],
    on=['CodigoEmpleado'],
    how='left'
)
main = main[main['Fecha'] >= main['FechaIngreso']]
main.drop(columns=['FechaIngreso'], inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Real'] = main.groupby(['CodigoEmpleado'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaPortafolioCluster'

### Cálculo de resultados cualitativos precargados
main = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=main,
    variable='VentaCobradaPortafolioCluster',
    columnas_extra=['CodigoEmpleado'],
    columnas_extra_merge=['CodigoEmpleado']
)
###

main['Contexto'] = main['CodigoEmpleado']
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
###

venta_cobrada_portafolio_cluster_ve = main.copy()
main = None

venta_cobrada_portafolio_cluster_ve

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3980380891.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)

['CodigoEmpleado'] ['CodigoEmpleado']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3980380891.py:28: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002699,VentaCobradaPortafolioCluster,2025-01-01,8.835063e+08,1.141486e+09,0.77
1,5002699,VentaCobradaPortafolioCluster,2025-02-01,2.048806e+09,2.378671e+09,0.86
2,5002699,VentaCobradaPortafolioCluster,2025-03-01,2.787163e+09,3.681709e+09,0.76
3,5002699,VentaCobradaPortafolioCluster,2025-04-01,4.030792e+09,4.491659e+09,0.90
4,5002699,VentaCobradaPortafolioCluster,2025-05-01,5.066533e+09,5.475735e+09,0.93
5,5002699,VentaCobradaPortafolioCluster,2025-06-01,6.165841e+09,6.717530e+09,0.92
6,5002699,VentaCobradaPortafolioCluster,2025-07-01,7.511770e+09,7.847549e+09,0.96
7,5002699,VentaCobradaPortafolioCluster,2025-08-01,8.275694e+09,9.142323e+09,0.91
8,5002699,VentaCobradaPortafolioCluster,2025-09-01,9.742674e+09,1.053608e+10,0.92
9,5002699,VentaCobradaPortafolioCluster,2025-10-01,1.098381e+10,1.201751e+10,0.91
10,5002699,VentaCobradaPortafolioCluster,2025-11-01,1.191933e+10,1.394706e+10,0.85
11,5002699,VentaCobradaPortafolioCluster,2025-12-01,1.343553e+10,1.540034e+10,0.87
12,70021970,VentaCobradaPortafolioCluster,2025-01-01,1.406610e+08,1.391448e+08,1.01
13,70021970,VentaCobradaPortafolioCluster,2025-02-01,3.681077e+08,3.104000e+08,1.19
14,70021970,VentaCobradaPortafolioCluster,2025-03-01,6.775443e+08,5.512275e+08,1.23
15,70021970,VentaCobradaPortafolioCluster,2025-04-01,9.723805e+08,7.385379e+08,1.32
16,70021970,VentaCobradaPortafolioCluster,2025-05-01,1.068823e+09,8.830344e+08,1.21
17,70021970,VentaCobradaPortafolioCluster,2025-06-01,1.285036e+09,1.097103e+09,1.17
18,70021970,VentaCobradaPortafolioCluster,2025-07-01,1.466460e+09,1.337931e+09,1.10
19,70021970,VentaCobradaPortafolioCluster,2025-08-01,1.573920e+09,1.605517e+09,0.98
20,70021970,VentaCobradaPortafolioCluster,2025-09-01,1.849332e+09,1.899862e+09,0.97
21,70021970,VentaCobradaPortafolioCluster,2025-10-01,2.110328e+09,2.140690e+09,0.99
22,70021970,VentaCobradaPortafolioCluster,2025-11-01,2.231310e+09,2.408276e+09,0.93
23,70021970,VentaCobradaPortafolioCluster,2025-12-01,2.428017e+09,2.675862e+09,0.91
24,70029614,VentaCobradaPortafolioCluster,2025-01-01,1.406610e+08,1.391448e+08,1.01
25,70029614,VentaCobradaPortafolioCluster,2025-02-01,3.681077e+08,3.104000e+08,1.19
26,70029614,VentaCobradaPortafolioCluster,2025-03-01,6.775443e+08,5.512275e+08,1.23
27,70029614,VentaCobradaPortafolioCluster,2025-04-01,9.723805e+08,7.385379e+08,1.32
28,70029614,VentaCobradaPortafolioCluster,2025-05-01,1.068823e+09,8.830344e+08,1.21
29,70029614,VentaCobradaPortafolioCluster,2025-06-01,1.285036e+09,1.097103e+09,1.17
30,70029614,VentaCobradaPortafolioCluster,2025-07-01,1.466460e+09,1.337931e+09,1.10
31,70029614,VentaCobradaPortafolioCluster,2025-08-01,1.573920e+09,1.605517e+09,0.98
32,70029614,VentaCobradaPortafolioCluster,2025-09-01,1.849332e+09,1.899862e+09,0.97
33,70029614,VentaCobradaPortafolioCluster,2025-10-01,2.110328e+09,2.140690e+09,0.99
34,70029614,VentaCobradaPortafolioCluster,2025-11-01,2.231310e+09,2.408276e+09,0.93
35,70029614,VentaCobradaPortafolioCluster,2025-12-01,2.428017e+09,2.675862e+09,0.91
36,70032478,VentaCobradaPortafolioCluster,2025-01-01,1.542020e+06,5.220564e+06,0.30
37,70032478,VentaCobradaPortafolioCluster,2025-02-01,7.355030e+06,1.007461e+07,0.73
38,70032478,VentaCobradaPortafolioCluster,2025-03-01,1.624043e+07,1.417939e+07,1.15
39,70032478,VentaCobradaPortafolioCluster,2025-04-01,1.920360e+07,1.909305e+07,1.01
40,70032478,VentaCobradaPortafolioCluster,2025-05-01,2.611480e+07,2.400671e+07,1.09
41,70032478,VentaCobradaPortafolioCluster,2025-06-01,3.417584e+07,3.219614e+07,1.06
42,70032478,VentaCobradaPortafolioCluster,2025-07-01,3.777471e+07,3.792874e+07,1.00
43,70032478,VentaCobradaPortafolioCluster,2025-08-01,3.846511e+07,4.448029e+07,0.86
44,70032478,VentaCobradaPortafolioCluster,2025-09-01,5.369552e+07,5.103183e+07,1.05
45,70032478,VentaCobradaPortafolioCluster,2025-10-01,7.272908e+07,5.840232e+07,1.25
46,70032478,VentaCobradaPortafolioCluster,2025-11-01,7.837132e+07,6.577281e+07,1.19
47,70032478,VentaCobradaPortafolioCluster,2025-12-01,8.326937e+07,7.314330e+07,1.14

#### 25.1.5 VentaFacturadaPortafolioClusterSub

In [210]:
venta_real_cluster_consecutivo_ve = venta_recaudo_presupuesto_original_ve_real.groupby(['AreaCalculo', 'Cluster', 'Consecutivo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_real_cluster_consecutivo_ve.rename(columns={'Venta': 'Real'}, inplace=True)

venta_presupuesto_cluster_consecutivo_ve = venta_recaudo_presupuesto_original_ve_presupuesto.groupby(['AreaCalculo', 'Cluster', 'Consecutivo', 'Fecha'], as_index=False).agg({'Venta': 'sum'})
venta_presupuesto_cluster_consecutivo_ve.rename(columns={'Venta': 'Presupuesto'}, inplace=True)

main = pd.merge(
    left=venta_presupuesto_cluster_consecutivo_ve,
    right=venta_real_cluster_consecutivo_ve,
    on=['Cluster', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)

main['Real'].fillna(0.0, inplace=True)

main['Real'] = main.groupby(['AreaCalculo', 'Cluster', 'Consecutivo', 'Fecha'])['Real'].transform(pd.Series.sum)
main['Presupuesto'] = main.groupby(['AreaCalculo', 'Cluster', 'Consecutivo', 'Fecha'])['Presupuesto'].transform(pd.Series.sum)

main['Consecutivo'] = main['Consecutivo'].astype('str')
main['TipoEmpleado'] = 'VE'

### Agrupación a nivel de empleado por zonas
main = pd.merge(
    df_clusters_empleado[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Cluster']],
    main,
    on=['TipoEmpleado', 'AreaCalculo', 'Cluster'],
    how='left'
)

main = pd.merge(
    left=main,
    right=df_empleados[['CodigoEmpleado', 'FechaIngreso']],
    on=['CodigoEmpleado'],
    how='left'
)
main = main[main['Fecha'] >= main['FechaIngreso']]
main.drop(columns=['FechaIngreso'], inplace=True)

main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Real'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaPortafolioClusterSub'

### Cálculo de resultados cualitativos precargados
main = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=main,
    variable='VentaFacturadaPortafolioClusterSub',
    columnas_extra=['CodigoEmpleado', 'Consecutivo'],
    columnas_extra_merge=['CodigoEmpleado', 'Consecutivo']
)
###

main['Contexto'] = main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
###

venta_facturada_portafolio_cluster_sub_ve = main.copy()
main = None

venta_facturada_portafolio_cluster_sub_ve

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1312472633.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)

['CodigoEmpleado', 'Consecutivo'] ['CodigoEmpleado', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1312472633.py:39: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002699_1,VentaFacturadaPortafolioClusterSub,2025-01-01,1625571.00,2.534318e+06,0.64
1,5002699_1,VentaFacturadaPortafolioClusterSub,2025-02-01,3812902.73,6.758182e+06,0.56
2,5002699_1,VentaFacturadaPortafolioClusterSub,2025-03-01,8183016.73,1.267159e+07,0.65
3,5002699_1,VentaFacturadaPortafolioClusterSub,2025-04-01,10398738.72,1.942977e+07,0.54
4,5002699_1,VentaFacturadaPortafolioClusterSub,2025-05-01,12824940.72,2.703273e+07,0.47
...,...,...,...,...,...,...
74,70032478_2,VentaFacturadaPortafolioClusterSub,2025-08-01,1376200.00,0.000000e+00,inf
75,70032478_2,VentaFacturadaPortafolioClusterSub,2025-09-01,1907980.00,0.000000e+00,inf
76,70032478_2,VentaFacturadaPortafolioClusterSub,2025-10-01,2093740.00,0.000000e+00,inf
77,70032478_2,VentaFacturadaPortafolioClusterSub,2025-11-01,2233060.00,0.000000e+00,inf
78,70032478_2,VentaFacturadaPortafolioClusterSub,2025-12-01,3296620.00,0.000000e+00,inf

### 25.2 Para GC

In [211]:
area_calculo_sba_completo_gc = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='GC']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los GC
venta_recaudo_presupuesto_original_gc_real = area_calculo_sba_completo_gc.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'ZonaGeografica', 'Canal', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los GC
venta_recaudo_presupuesto_original_gc_presupuesto = area_calculo_sba_completo_gc.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'ZonaGeografica', 'Canal', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#### 25.2.1 VentaCobradaZonaHospitalarioSub

In [212]:
recaudo_real_zona_sub_ch_gc = venta_recaudo_presupuesto_original_gc_real.query('Canal=="Hospital" or Canal=="Distribuidor" or Canal=="Opl" or Canal=="Asegurador" or Canal=="Central De Mezcla"')
recaudo_real_zona_sub_ch_gc = recaudo_real_zona_sub_ch_gc.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_zona_sub_ch_gc.rename(columns={'Recaudo': 'Real'}, inplace=True)

recaudo_presupuesto_zona_sub_ch_gc = venta_recaudo_presupuesto_original_gc_presupuesto.query('Canal=="Hospital" or Canal=="Distribuidor" or Canal=="Opl" or Canal=="Asegurador" or Canal=="Central De Mezcla"')
recaudo_presupuesto_zona_sub_ch_gc = recaudo_presupuesto_zona_sub_ch_gc.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_zona_sub_ch_gc.rename(columns={'Recaudo': 'Presupuesto'}, inplace=True)

main = pd.merge(
    left=recaudo_presupuesto_zona_sub_ch_gc,
    right=recaudo_real_zona_sub_ch_gc,
    on=['ZonaGeografica', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)

main['Real'].fillna(0.0, inplace=True)

main['Real'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'])['Real'].transform(pd.Series.sum)
main['Presupuesto'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'])['Presupuesto'].transform(pd.Series.sum)

main['Consecutivo'] = main['Consecutivo'].astype('str')
main['TipoEmpleado'] = 'GC'

### Agrupación a nivel de empleado por zonas
main = pd.merge(
    df_zonas_empleado[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Zona']].rename(columns={'Zona': 'ZonaGeografica'}),
    main,
    on=['TipoEmpleado', 'AreaCalculo', 'ZonaGeografica'],
    how='left'
)
main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)
main['Real'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaZonaHospitalarioSub'
###

### Cálculo de resultados cualitativos precargados
main = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=main,
    variable='VentaCobradaZonaHospitalarioSub',
    columnas_extra=['CodigoEmpleado', 'Consecutivo'], 
    columnas_extra_merge=['CodigoEmpleado', 'Consecutivo'],
    pre_merge_lambda=pre_merge_venta_cobrada_zona_hospitalaria_sub
)
###

main['Contexto'] = main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]


venta_cobrada_zona_hospitalario_sub_gc = main.copy()
main = None
resultado_cualitativos_variable = None

venta_cobrada_zona_hospitalario_sub_gc

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1233320796.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)

['CodigoEmpleado', 'Consecutivo'] ['CodigoEmpleado', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1233320796.py:31: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002711_1,VentaCobradaZonaHospitalarioSub,2025-01-01,2.728419e+09,1.933902e+09,1.41
1,5002711_1,VentaCobradaZonaHospitalarioSub,2025-02-01,3.967417e+09,3.725453e+09,1.06
2,5002711_1,VentaCobradaZonaHospitalarioSub,2025-03-01,5.739001e+09,6.022608e+09,0.95
3,5002711_1,VentaCobradaZonaHospitalarioSub,2025-04-01,7.330999e+09,7.864786e+09,0.93
4,5002711_1,VentaCobradaZonaHospitalarioSub,2025-07-01,8.874322e+09,9.647957e+09,0.92
...,...,...,...,...,...,...
75,5005980_3,VentaCobradaZonaHospitalarioSub,2025-05-01,5.321071e+08,2.202827e+08,2.42
76,5005980_3,VentaCobradaZonaHospitalarioSub,2025-07-01,7.410536e+08,2.863853e+08,2.59
77,5005980_3,VentaCobradaZonaHospitalarioSub,2025-09-01,7.410536e+08,2.940323e+08,2.52
78,5005980_3,VentaCobradaZonaHospitalarioSub,2025-11-01,9.113490e+08,3.760797e+08,2.42
79,5005980_3,VentaCobradaZonaHospitalarioSub,2025-12-01,1.189334e+09,4.582935e+08,2.60

### 25.3 Para GD

In [213]:
area_calculo_sba_completo_gd = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado']=='GD']

#Se halla la informacion de la venta y recaudo real de los representantes de ventas de los GD
venta_recaudo_presupuesto_original_gd_real = area_calculo_sba_completo_gd.merge(
    df_venta_recaudo_real[['Division', 'GrupoProducto', 'SBA', 'ZonaGeografica', 'Canal', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#Se halla la informacion de la venta y recaudo presupuesto de los representantes de ventas de los GD
venta_recaudo_presupuesto_original_gd_presupuesto = area_calculo_sba_completo_gd.merge(
    df_venta_recaudo_presupuesto[['Division', 'GrupoProducto', 'SBA', 'ZonaGeografica', 'Canal', 'Fecha', 'Venta', 'Recaudo']],
    on=['Division', 'GrupoProducto', 'SBA']
)

#### 25.3.1 VentaCobradaZonaHospitalarioSub

In [214]:
recaudo_real_zona_sub_ch_gd = venta_recaudo_presupuesto_original_gd_real.query('Canal=="Hospital" or Canal=="Distribuidor" or Canal=="Opl" or Canal=="Asegurador" or Canal=="Central De Mezcla"')
recaudo_real_zona_sub_ch_gd = recaudo_real_zona_sub_ch_gd.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_zona_sub_ch_gd.rename(columns={'Recaudo': 'Real'}, inplace=True)

recaudo_presupuesto_zona_sub_ch_gd = venta_recaudo_presupuesto_original_gd_presupuesto.query('Canal=="Hospital" or Canal=="Distribuidor" or Canal=="Opl" or Canal=="Asegurador" or Canal=="Central De Mezcla"')
recaudo_presupuesto_zona_sub_ch_gd = recaudo_presupuesto_zona_sub_ch_gd.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_zona_sub_ch_gd.rename(columns={'Recaudo': 'Presupuesto'}, inplace=True)

main = pd.merge(
    left=recaudo_presupuesto_zona_sub_ch_gd,
    right=recaudo_real_zona_sub_ch_gd,
    on=['ZonaGeografica', 'AreaCalculo', 'Consecutivo', 'Fecha'],
    how='left'
)

main['Real'].fillna(0.0, inplace=True)

main['Real'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'])['Real'].transform(pd.Series.sum)
main['Presupuesto'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Consecutivo', 'Fecha'])['Presupuesto'].transform(pd.Series.sum)

main['Consecutivo'] = main['Consecutivo'].astype('str')
main['TipoEmpleado'] = 'GD'

### Agrupación a nivel de empleado por zonas
main = pd.merge(
    df_zonas_empleado[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Zona']].rename(columns={'Zona': 'ZonaGeografica'}),
    main,
    on=['TipoEmpleado', 'AreaCalculo', 'ZonaGeografica'],
    how='left'
)
main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)
main['Real'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['CodigoEmpleado', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaZonaHospitalarioSub'
###

### Cálculo de resultados cualitativos precargados
main = dataframe_loader.sobreescribir_resultados_cualitativos(
    main=main,
    variable='VentaCobradaZonaHospitalarioSub',
    columnas_extra=['CodigoEmpleado', 'Consecutivo'], 
    columnas_extra_merge=['CodigoEmpleado', 'Consecutivo'],
    pre_merge_lambda=pre_merge_venta_cobrada_zona_hospitalaria_sub
)
###

main['Contexto'] = main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

venta_cobrada_zona_hospitalario_sub_gd = main.copy()
main = None

venta_cobrada_zona_hospitalario_sub_gd

['CodigoEmpleado', 'Consecutivo'] ['CodigoEmpleado', 'Consecutivo']

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1348865350.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1348865350.py:31: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5016692_1,VentaCobradaZonaHospitalarioSub,2025-01-01,2.282858e+09,2.099690e+09,1.09
1,5016692_1,VentaCobradaZonaHospitalarioSub,2025-02-01,4.117458e+09,4.390816e+09,0.94
2,5016692_1,VentaCobradaZonaHospitalarioSub,2025-03-01,5.776716e+09,6.534117e+09,0.88
3,5016692_1,VentaCobradaZonaHospitalarioSub,2025-04-01,7.166714e+09,8.556866e+09,0.84
4,5016692_1,VentaCobradaZonaHospitalarioSub,2025-05-01,7.191522e+09,8.621794e+09,0.83
5,5016692_1,VentaCobradaZonaHospitalarioSub,2025-06-01,7.230569e+09,8.715992e+09,0.83
6,5016692_1,VentaCobradaZonaHospitalarioSub,2025-07-01,9.041542e+09,1.065138e+10,0.85
7,5016692_1,VentaCobradaZonaHospitalarioSub,2025-08-01,9.044822e+09,1.073800e+10,0.84
8,5016692_1,VentaCobradaZonaHospitalarioSub,2025-09-01,9.106108e+09,1.083863e+10,0.84
9,5016692_1,VentaCobradaZonaHospitalarioSub,2025-11-01,1.126345e+10,1.323665e+10,0.85
10,5016692_1,VentaCobradaZonaHospitalarioSub,2025-12-01,1.318232e+10,1.566229e+10,0.84
11,5036358_1,VentaCobradaZonaHospitalarioSub,2025-01-01,3.965570e+07,5.352536e+07,0.74
12,5036358_1,VentaCobradaZonaHospitalarioSub,2025-02-01,1.981788e+08,1.074917e+08,1.84
13,5036358_1,VentaCobradaZonaHospitalarioSub,2025-03-01,3.820845e+08,1.605473e+08,2.38
14,5036358_1,VentaCobradaZonaHospitalarioSub,2025-04-01,5.321071e+08,2.165288e+08,2.46
15,5036358_1,VentaCobradaZonaHospitalarioSub,2025-05-01,5.321071e+08,2.202827e+08,2.42
16,5036358_1,VentaCobradaZonaHospitalarioSub,2025-07-01,7.410536e+08,2.863853e+08,2.59
17,5036358_1,VentaCobradaZonaHospitalarioSub,2025-09-01,7.410536e+08,2.940323e+08,2.52
18,5036358_1,VentaCobradaZonaHospitalarioSub,2025-11-01,9.113490e+08,3.760797e+08,2.42
19,5036358_1,VentaCobradaZonaHospitalarioSub,2025-12-01,1.189334e+09,4.582935e+08,2.60
20,5041257_1,VentaCobradaZonaHospitalarioSub,2025-01-01,4.793437e+08,3.726662e+08,1.29
21,5041257_1,VentaCobradaZonaHospitalarioSub,2025-02-01,8.124626e+08,7.210830e+08,1.13
22,5041257_1,VentaCobradaZonaHospitalarioSub,2025-03-01,1.365347e+09,1.127450e+09,1.21
23,5041257_1,VentaCobradaZonaHospitalarioSub,2025-04-01,1.732374e+09,1.552205e+09,1.12
24,5041257_1,VentaCobradaZonaHospitalarioSub,2025-05-01,1.867970e+09,1.886571e+09,0.99
25,5041257_1,VentaCobradaZonaHospitalarioSub,2025-07-01,2.354831e+09,2.400003e+09,0.98
26,5041257_1,VentaCobradaZonaHospitalarioSub,2025-09-01,2.535469e+09,2.734266e+09,0.93
27,5041257_1,VentaCobradaZonaHospitalarioSub,2025-11-01,2.830829e+09,3.279034e+09,0.86
28,5041257_1,VentaCobradaZonaHospitalarioSub,2025-12-01,3.146826e+09,3.898034e+09,0.81


## 26. Venta Facturada Nacional Canal Hospitalario (VentaFacturadaPaisHospitalario)

In [215]:
# Preparar
main = df_zona_plan_real_venta_ch.copy()
main = main.drop(columns=['Zona'])

# Calcular
main = main.groupby(['Fecha'], as_index=True)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaPaisHospitalario'

# Formatear
main.reset_index(inplace=True)
main['Contexto']= 'BBMCO'
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

# Limpiar
venta_facturada_pais_ch = main.copy()
main = None
venta_facturada_pais_ch

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1187044790.py:6: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Fecha'], as_index=True)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 27. Venta Facturada Zona Hospitalario (VentaFacturadaZonaHospitalario)

In [216]:
# Preparar
main = df_zona_plan_real_venta_ch.copy()

# Calcular
main = main.groupby(['Fecha', 'Zona'], as_index=True)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Zona'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Zona'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaZonaHospitalario'

# Formatear
main.reset_index(inplace=True)
main.rename(columns={'Zona': 'Contexto'}, inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

# Limpiar
venta_facturada_zona_ch = main.copy()
main = None
venta_facturada_zona_ch

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4007591514.py:5: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Fecha', 'Zona'], as_index=True)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 28. Rentabilidad Zona Hospitalario CM2 (RentabilidadZonaHospitalarioCM2)

In [217]:
main = df_rentabilidad_zona.copy()

# Calcular
main = main.groupby(['Zona', 'Fecha'], as_index =False)[['Real', 'Presupuesto']].apply(sum)
main['PorcentajeCumplimiento'] = (main['Real'] / main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'RentabilidadZonaHospitalarioCM2'

#Formatear
main.reset_index(inplace=True)
main.rename(columns={'Zona': 'Contexto'}, inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

# Zona - Fecha - Rentabilidad

# No hay datos

rentabilidad_zona_hospitalario_cm2 =  main.copy()
main = None
rentabilidad_zona_hospitalario_cm2

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\966528830.py:4: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Zona', 'Fecha'], as_index =False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 29. Venta Facturada Braun País (VentaFacturadaBraunPais)

In [218]:
# VentaRecaudoReal (venta)
# VentaRecaudoPresupuesto (venta)

# Preparar
drop_cols = ['Recaudo', 'Division', 'Cluster','CodigoEmpleado', 'ZonaGeografica','GrupoProducto', 'Canal', 'SBA']
real = df_venta_recaudo_real.copy().drop(columns=drop_cols)
ppto = df_venta_recaudo_presupuesto.copy().drop(columns=drop_cols)

# Sumamos los registros que tienen el mismo conexto para que exista un solo registro
ppto = ppto.groupby(['Fecha'], as_index=True)[['Venta']].apply(sum)
real = real.groupby(['Fecha'], as_index=True)[['Venta']].apply(sum)
ppto.reset_index(inplace=True)
real.reset_index(inplace=True)

main = ppto.rename(columns={'Venta': 'Presupuesto'}).merge(
    real.rename(columns={'Venta': 'Real'}),
    on=['Fecha'],
    how='left'
)
main['Real'].fillna(0, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2569793874.py:10: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ppto = ppto.groupby(['Fecha'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2569793874.py:11: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  real = real.groupby(['Fecha'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2569793874.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)

In [219]:
main

        Fecha   Presupuesto          Real
0  2025-01-01  1.476750e+10  8.576640e+09
1  2025-02-01  1.855624e+10  1.721568e+10
2  2025-03-01  2.093023e+10  1.794512e+10
3  2025-04-01  1.750376e+10  1.767901e+10
4  2025-05-01  2.170303e+10  2.214536e+10
5  2025-06-01  2.229254e+10  2.034400e+10
6  2025-07-01  2.361420e+10  2.146396e+10
7  2025-08-01  2.282364e+10  2.111328e+10
8  2025-09-01  2.255476e+10  1.930499e+10
9  2025-10-01  2.451438e+10  1.983993e+10
10 2025-11-01  2.526043e+10  2.339816e+10
11 2025-12-01  2.721391e+10  3.339041e+10

In [220]:



# Calcular
main['Contexto']= 'BBMCO'
main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)

# main = convertir_a_euros(main)

main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaBraunPais'


#Formatear
main.reset_index(inplace=True)

main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]




venta_facturada_braun_pais = main.copy()
main = None
venta_facturada_braun_pais

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\655473392.py:3: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,BBMCO,VentaFacturadaBraunPais,2025-01-01,8.576640e+09,1.476750e+10,0.58
1,BBMCO,VentaFacturadaBraunPais,2025-02-01,2.579232e+10,3.332374e+10,0.77
2,BBMCO,VentaFacturadaBraunPais,2025-03-01,4.373744e+10,5.425397e+10,0.81
3,BBMCO,VentaFacturadaBraunPais,2025-04-01,6.141645e+10,7.175773e+10,0.86
4,BBMCO,VentaFacturadaBraunPais,2025-05-01,8.356181e+10,9.346076e+10,0.89
5,BBMCO,VentaFacturadaBraunPais,2025-06-01,1.039058e+11,1.157533e+11,0.90
6,BBMCO,VentaFacturadaBraunPais,2025-07-01,1.253698e+11,1.393675e+11,0.90
7,BBMCO,VentaFacturadaBraunPais,2025-08-01,1.464831e+11,1.621911e+11,0.90
8,BBMCO,VentaFacturadaBraunPais,2025-09-01,1.657880e+11,1.847459e+11,0.90
9,BBMCO,VentaFacturadaBraunPais,2025-10-01,1.856280e+11,2.092603e+11,0.89
10,BBMCO,VentaFacturadaBraunPais,2025-11-01,2.090261e+11,2.345207e+11,0.89
11,BBMCO,VentaFacturadaBraunPais,2025-12-01,2.424165e+11,2.617346e+11,0.93

## 30. Rentabilidad Compañía CM3 (RentabilidadCompaniaCM3)

In [221]:
# Rentabilidad Real / Presupuesto
# Filtar paras CM3 compañía BBMCO
# Totalizar nivel país

main = df_rentabilidad.copy()
main.query('Compania == "BBMCO" and ClaseRentabilidad == "CMIII"', inplace=True)
main.drop(columns=['GrupoProducto', 'SBA', 'ClaseRentabilidad'], inplace=True)
main = main.groupby(['Compania', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)

main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'RentabilidadCompaniaCM3'


#Formatear
main.reset_index(inplace=True)
main.rename(columns={'Compania':'Contexto'}, inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

rentabilidad_compania_cm3 = main.copy()
main= None
rentabilidad_compania_cm3

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3721143820.py:8: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Compania', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 31. Venta Facturada Grupo clientes (KAM) VentaFacturadaGrupoClientesKAMS

In [222]:
venta_recaudo_kams_kam = df_venta_recaudo_kams[df_venta_recaudo_kams['TipoEmpleado'] == 'KAM']
venta_recaudo_kams_kam

,TipoEmpleado,AreaCalculo,Consecutivo,Fecha,VentaReal,VentaPresupuesto,RecaudoReal,RecaudoPresupuesto
0,KAM,2,1,2025-01-01,4.840923e+08,6.371832e+08,7.544527e+08,1.033142e+09
1,KAM,2,1,2025-02-01,9.723599e+08,8.676537e+08,7.602080e+08,9.842100e+08
2,KAM,2,1,2025-03-01,1.176578e+09,1.287923e+09,1.318599e+09,1.028973e+09
3,KAM,2,1,2025-04-01,8.867300e+08,8.405395e+08,9.373446e+08,1.239575e+09
4,KAM,2,1,2025-05-01,1.230991e+09,1.138795e+09,1.107789e+09,1.215844e+09
...,...,...,...,...,...,...,...,...
67,KAM,3,3,2025-08-01,2.430877e+08,3.218854e+08,1.267355e+08,3.186406e+08
68,KAM,3,3,2025-09-01,1.171128e+08,3.413999e+08,3.217374e+08,3.444164e+08
69,KAM,3,3,2025-10-01,2.677661e+08,3.697163e+08,3.058855e+08,3.155831e+08
70,KAM,3,3,2025-11-01,2.434639e+08,3.473552e+08,1.344482e+08,3.362826e+08
71,KAM,3,3,2025-12-01,4.575161e+08,3.416811e+08,2.290615e+08,3.366020e+08

In [223]:
main = venta_recaudo_kams_kam.drop(columns=['RecaudoReal', 'RecaudoPresupuesto'])
main.rename(columns={'VentaReal': 'Real', 'VentaPresupuesto':'Presupuesto'}, inplace=True)

main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)

main.reset_index(inplace=True)
main['Real'] = main.groupby(['TipoEmpleado', 'AreaCalculo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['TipoEmpleado', 'AreaCalculo'])['Presupuesto'].transform(pd.Series.cumsum)

main['Contexto'] = main['TipoEmpleado'].str.lower() + '_' +  main['AreaCalculo'].astype(int).astype('str')
main['Variable'] = 'VentaFacturadaGrupoClientesKAMS'
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

venta_facturada_grupo_clientes_kams = main
main = None
venta_facturada_grupo_clientes_kams

# Contexto: TipoEmpleado_AreaCalculo

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2260948264.py:4: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,kam_2,VentaFacturadaGrupoClientesKAMS,2025-01-01,2.608490e+09,3.758721e+09,0.69
1,kam_2,VentaFacturadaGrupoClientesKAMS,2025-02-01,6.926967e+09,8.632438e+09,0.80
2,kam_2,VentaFacturadaGrupoClientesKAMS,2025-03-01,1.200932e+10,1.545205e+10,0.78
3,kam_2,VentaFacturadaGrupoClientesKAMS,2025-04-01,1.709590e+10,2.011921e+10,0.85
4,kam_2,VentaFacturadaGrupoClientesKAMS,2025-05-01,2.350354e+10,2.638348e+10,0.89
5,kam_2,VentaFacturadaGrupoClientesKAMS,2025-06-01,2.896717e+10,3.318396e+10,0.87
6,kam_2,VentaFacturadaGrupoClientesKAMS,2025-07-01,3.410439e+10,3.955976e+10,0.86
7,kam_2,VentaFacturadaGrupoClientesKAMS,2025-08-01,3.822938e+10,4.587415e+10,0.83
8,kam_2,VentaFacturadaGrupoClientesKAMS,2025-09-01,4.368561e+10,5.261838e+10,0.83
9,kam_2,VentaFacturadaGrupoClientesKAMS,2025-10-01,4.854238e+10,5.899095e+10,0.82
10,kam_2,VentaFacturadaGrupoClientesKAMS,2025-11-01,5.471074e+10,6.618304e+10,0.83
11,kam_2,VentaFacturadaGrupoClientesKAMS,2025-12-01,6.146638e+10,7.423050e+10,0.83
12,kam_3,VentaFacturadaGrupoClientesKAMS,2025-01-01,2.128682e+09,3.502935e+09,0.61
13,kam_3,VentaFacturadaGrupoClientesKAMS,2025-02-01,5.702855e+09,7.858002e+09,0.73
14,kam_3,VentaFacturadaGrupoClientesKAMS,2025-03-01,1.063537e+10,1.292239e+10,0.82
15,kam_3,VentaFacturadaGrupoClientesKAMS,2025-04-01,1.529728e+10,1.723703e+10,0.89
16,kam_3,VentaFacturadaGrupoClientesKAMS,2025-05-01,2.145701e+10,2.250296e+10,0.95
17,kam_3,VentaFacturadaGrupoClientesKAMS,2025-06-01,2.677100e+10,2.791884e+10,0.96
18,kam_3,VentaFacturadaGrupoClientesKAMS,2025-07-01,3.023909e+10,3.321014e+10,0.91
19,kam_3,VentaFacturadaGrupoClientesKAMS,2025-08-01,3.416108e+10,3.876942e+10,0.88
20,kam_3,VentaFacturadaGrupoClientesKAMS,2025-09-01,3.854188e+10,4.416768e+10,0.87
21,kam_3,VentaFacturadaGrupoClientesKAMS,2025-10-01,4.333491e+10,4.952238e+10,0.88
22,kam_3,VentaFacturadaGrupoClientesKAMS,2025-11-01,4.799311e+10,5.557908e+10,0.86
23,kam_3,VentaFacturadaGrupoClientesKAMS,2025-12-01,5.650614e+10,6.202371e+10,0.91

In [224]:
venta_facturada_grupo_clientes_kams[
    (venta_facturada_grupo_clientes_kams['Contexto'] == 'kam_2')
]

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,kam_2,VentaFacturadaGrupoClientesKAMS,2025-01-01,2.608490e+09,3.758721e+09,0.69
1,kam_2,VentaFacturadaGrupoClientesKAMS,2025-02-01,6.926967e+09,8.632438e+09,0.80
2,kam_2,VentaFacturadaGrupoClientesKAMS,2025-03-01,1.200932e+10,1.545205e+10,0.78
3,kam_2,VentaFacturadaGrupoClientesKAMS,2025-04-01,1.709590e+10,2.011921e+10,0.85
4,kam_2,VentaFacturadaGrupoClientesKAMS,2025-05-01,2.350354e+10,2.638348e+10,0.89
5,kam_2,VentaFacturadaGrupoClientesKAMS,2025-06-01,2.896717e+10,3.318396e+10,0.87
6,kam_2,VentaFacturadaGrupoClientesKAMS,2025-07-01,3.410439e+10,3.955976e+10,0.86
7,kam_2,VentaFacturadaGrupoClientesKAMS,2025-08-01,3.822938e+10,4.587415e+10,0.83
8,kam_2,VentaFacturadaGrupoClientesKAMS,2025-09-01,4.368561e+10,5.261838e+10,0.83
9,kam_2,VentaFacturadaGrupoClientesKAMS,2025-10-01,4.854238e+10,5.899095e+10,0.82
10,kam_2,VentaFacturadaGrupoClientesKAMS,2025-11-01,5.471074e+10,6.618304e+10,0.83
11,kam_2,VentaFacturadaGrupoClientesKAMS,2025-12-01,6.146638e+10,7.423050e+10,0.83

## 32. Venta Cobrada Grupo clientes (KAM) VentaCobradaGrupoClientesKAMSSub

In [225]:
venta_recaudo_kams_kam.head()

,TipoEmpleado,AreaCalculo,Consecutivo,Fecha,VentaReal,VentaPresupuesto,RecaudoReal,RecaudoPresupuesto
0,KAM,2,1,2025-01-01,4.840923e+08,6.371832e+08,7.544527e+08,1.033142e+09
1,KAM,2,1,2025-02-01,9.723599e+08,8.676537e+08,7.602080e+08,9.842100e+08
2,KAM,2,1,2025-03-01,1.176578e+09,1.287923e+09,1.318599e+09,1.028973e+09
3,KAM,2,1,2025-04-01,8.867300e+08,8.405395e+08,9.373446e+08,1.239575e+09
4,KAM,2,1,2025-05-01,1.230991e+09,1.138795e+09,1.107789e+09,1.215844e+09

In [226]:
main = venta_recaudo_kams_kam.drop(columns=['RecaudoReal', 'RecaudoPresupuesto'])
main.rename(columns={'VentaReal': 'Real', 'VentaPresupuesto':'Presupuesto'}, inplace=True)

main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)

main.reset_index(inplace=True)
main['Real'] = main.groupby(['TipoEmpleado', 'AreaCalculo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['TipoEmpleado', 'AreaCalculo'])['Presupuesto'].transform(pd.Series.cumsum)

main['Contexto'] = main['TipoEmpleado'].str.lower() + '_' +  main['AreaCalculo'].astype(int).astype('str')
main['Variable'] = 'VentaFacturadaGrupoClientesKAMS'
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

venta_facturada_grupo_clientes_kams = main
main = None
venta_facturada_grupo_clientes_kams

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\304267599.py:4: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,kam_2,VentaFacturadaGrupoClientesKAMS,2025-01-01,2.608490e+09,3.758721e+09,0.69
1,kam_2,VentaFacturadaGrupoClientesKAMS,2025-02-01,6.926967e+09,8.632438e+09,0.80
2,kam_2,VentaFacturadaGrupoClientesKAMS,2025-03-01,1.200932e+10,1.545205e+10,0.78
3,kam_2,VentaFacturadaGrupoClientesKAMS,2025-04-01,1.709590e+10,2.011921e+10,0.85
4,kam_2,VentaFacturadaGrupoClientesKAMS,2025-05-01,2.350354e+10,2.638348e+10,0.89
5,kam_2,VentaFacturadaGrupoClientesKAMS,2025-06-01,2.896717e+10,3.318396e+10,0.87
6,kam_2,VentaFacturadaGrupoClientesKAMS,2025-07-01,3.410439e+10,3.955976e+10,0.86
7,kam_2,VentaFacturadaGrupoClientesKAMS,2025-08-01,3.822938e+10,4.587415e+10,0.83
8,kam_2,VentaFacturadaGrupoClientesKAMS,2025-09-01,4.368561e+10,5.261838e+10,0.83
9,kam_2,VentaFacturadaGrupoClientesKAMS,2025-10-01,4.854238e+10,5.899095e+10,0.82
10,kam_2,VentaFacturadaGrupoClientesKAMS,2025-11-01,5.471074e+10,6.618304e+10,0.83
11,kam_2,VentaFacturadaGrupoClientesKAMS,2025-12-01,6.146638e+10,7.423050e+10,0.83
12,kam_3,VentaFacturadaGrupoClientesKAMS,2025-01-01,2.128682e+09,3.502935e+09,0.61
13,kam_3,VentaFacturadaGrupoClientesKAMS,2025-02-01,5.702855e+09,7.858002e+09,0.73
14,kam_3,VentaFacturadaGrupoClientesKAMS,2025-03-01,1.063537e+10,1.292239e+10,0.82
15,kam_3,VentaFacturadaGrupoClientesKAMS,2025-04-01,1.529728e+10,1.723703e+10,0.89
16,kam_3,VentaFacturadaGrupoClientesKAMS,2025-05-01,2.145701e+10,2.250296e+10,0.95
17,kam_3,VentaFacturadaGrupoClientesKAMS,2025-06-01,2.677100e+10,2.791884e+10,0.96
18,kam_3,VentaFacturadaGrupoClientesKAMS,2025-07-01,3.023909e+10,3.321014e+10,0.91
19,kam_3,VentaFacturadaGrupoClientesKAMS,2025-08-01,3.416108e+10,3.876942e+10,0.88
20,kam_3,VentaFacturadaGrupoClientesKAMS,2025-09-01,3.854188e+10,4.416768e+10,0.87
21,kam_3,VentaFacturadaGrupoClientesKAMS,2025-10-01,4.333491e+10,4.952238e+10,0.88
22,kam_3,VentaFacturadaGrupoClientesKAMS,2025-11-01,4.799311e+10,5.557908e+10,0.86
23,kam_3,VentaFacturadaGrupoClientesKAMS,2025-12-01,5.650614e+10,6.202371e+10,0.91

In [227]:
main = venta_recaudo_kams_kam.drop(columns=['VentaReal', 'VentaPresupuesto'])
main.rename(columns={'RecaudoReal': 'Real', 'RecaudoPresupuesto':'Presupuesto'}, inplace=True)
main

,TipoEmpleado,AreaCalculo,Consecutivo,Fecha,Real,Presupuesto
0,KAM,2,1,2025-01-01,7.544527e+08,1.033142e+09
1,KAM,2,1,2025-02-01,7.602080e+08,9.842100e+08
2,KAM,2,1,2025-03-01,1.318599e+09,1.028973e+09
3,KAM,2,1,2025-04-01,9.373446e+08,1.239575e+09
4,KAM,2,1,2025-05-01,1.107789e+09,1.215844e+09
...,...,...,...,...,...,...
67,KAM,3,3,2025-08-01,1.267355e+08,3.186406e+08
68,KAM,3,3,2025-09-01,3.217374e+08,3.444164e+08
69,KAM,3,3,2025-10-01,3.058855e+08,3.155831e+08
70,KAM,3,3,2025-11-01,1.344482e+08,3.362826e+08
71,KAM,3,3,2025-12-01,2.290615e+08,3.366020e+08

In [228]:
main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)
main['Real'] = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)

main['Contexto'] = main['TipoEmpleado'].str.lower() + '_' +  main['AreaCalculo'].astype(int).astype('str') + '_'+ main['Consecutivo'].astype(int).astype('str')
main['Variable'] = 'VentaCobradaGrupoClientesKAMSSub'
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

venta_cobrada_grupo_clientes_kams_sub = main
main = None
venta_cobrada_grupo_clientes_kams_sub

# Contexto: TipoEmpleado_AreaCalculo_Consecutivo

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2535537163.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,kam_2_1,VentaCobradaGrupoClientesKAMSSub,2025-01-01,7.544527e+08,1.033142e+09,0.73
1,kam_2_1,VentaCobradaGrupoClientesKAMSSub,2025-02-01,1.514661e+09,2.017352e+09,0.75
2,kam_2_1,VentaCobradaGrupoClientesKAMSSub,2025-03-01,2.833260e+09,3.046325e+09,0.93
3,kam_2_1,VentaCobradaGrupoClientesKAMSSub,2025-04-01,3.770605e+09,4.285900e+09,0.88
4,kam_2_1,VentaCobradaGrupoClientesKAMSSub,2025-05-01,4.878393e+09,5.501745e+09,0.89
...,...,...,...,...,...,...
67,kam_3_3,VentaCobradaGrupoClientesKAMSSub,2025-08-01,1.870009e+09,2.037554e+09,0.92
68,kam_3_3,VentaCobradaGrupoClientesKAMSSub,2025-09-01,2.191746e+09,2.381971e+09,0.92
69,kam_3_3,VentaCobradaGrupoClientesKAMSSub,2025-10-01,2.497631e+09,2.697554e+09,0.93
70,kam_3_3,VentaCobradaGrupoClientesKAMSSub,2025-11-01,2.632080e+09,3.033836e+09,0.87
71,kam_3_3,VentaCobradaGrupoClientesKAMSSub,2025-12-01,2.861141e+09,3.370438e+09,0.85

## 32.1 Venta Facturada Grupo clientes (KAM) VentaFacturadaGrupoClientesKAMSSub (2024)

In [229]:
venta_recaudo_kams_kam.head()

,TipoEmpleado,AreaCalculo,Consecutivo,Fecha,VentaReal,VentaPresupuesto,RecaudoReal,RecaudoPresupuesto
0,KAM,2,1,2025-01-01,4.840923e+08,6.371832e+08,7.544527e+08,1.033142e+09
1,KAM,2,1,2025-02-01,9.723599e+08,8.676537e+08,7.602080e+08,9.842100e+08
2,KAM,2,1,2025-03-01,1.176578e+09,1.287923e+09,1.318599e+09,1.028973e+09
3,KAM,2,1,2025-04-01,8.867300e+08,8.405395e+08,9.373446e+08,1.239575e+09
4,KAM,2,1,2025-05-01,1.230991e+09,1.138795e+09,1.107789e+09,1.215844e+09

In [230]:
main = venta_recaudo_kams_kam.drop(columns=['RecaudoReal', 'RecaudoPresupuesto'])
main.rename(columns={'VentaReal': 'Real', 'VentaPresupuesto':'Presupuesto'}, inplace=True)
main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main = main.merge(
    df_empleados
)
main.reset_index(inplace=True)
main['Contexto'] = main['CodigoEmpleado']
main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4100988929.py:3: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,index,TipoEmpleado,AreaCalculo,Consecutivo,Fecha,Real,Presupuesto,CodigoEmpleado,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,Contexto
0,0,KAM,2,1,2025-01-01,4.840923e+08,6.371832e+08,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293
1,1,KAM,2,1,2025-02-01,9.723599e+08,8.676537e+08,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293
2,2,KAM,2,1,2025-03-01,1.176578e+09,1.287923e+09,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293
3,3,KAM,2,1,2025-04-01,8.867300e+08,8.405395e+08,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293
4,4,KAM,2,1,2025-05-01,1.230991e+09,1.138795e+09,5004293,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,67,KAM,3,3,2025-08-01,2.430877e+08,3.218854e+08,5016988,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988
68,68,KAM,3,3,2025-09-01,1.171128e+08,3.413999e+08,5016988,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988
69,69,KAM,3,3,2025-10-01,2.677661e+08,3.697163e+08,5016988,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988
70,70,KAM,3,3,2025-11-01,2.434639e+08,3.473552e+08,5016988,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988
71,71,KAM,3,3,2025-12-01,4.575161e+08,3.416811e+08,5016988,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988

In [231]:
main_centro_costo = pd.merge(
    area_calculo_sba_completo,
    main,
    on=['AreaCalculo', 'Consecutivo', 'TipoEmpleado'],
    how='right'
).merge(
    df_empleados_centros_costos,
    on=['CodigoEmpleado'],
    how='left'
)
main_centro_costo

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,index,Fecha,Real,Presupuesto,...,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,Contexto,CodigoCentroCosto,PorcentajeAsignacion
0,2,1,HC,630,08,KAM,0,2025-01-01,4.840923e+08,6.371832e+08,...,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293,323015090,1.00
1,2,1,HC,630,08,KAM,1,2025-02-01,9.723599e+08,8.676537e+08,...,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293,323015090,1.00
2,2,1,HC,630,08,KAM,2,2025-03-01,1.176578e+09,1.287923e+09,...,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293,323015090,1.00
3,2,1,HC,630,08,KAM,3,2025-04-01,8.867300e+08,8.405395e+08,...,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293,323015090,1.00
4,2,1,HC,630,08,KAM,4,2025-05-01,1.230991e+09,1.138795e+09,...,1053784354,angela.serna@bbraun.com,ANGELA MARIA,SERNA CASTRILLON,2733000.0,2013-06-17,NaT,5004293,323015090,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,3,3,NaN,NaN,NaN,KAM,70,2025-11-01,2.434639e+08,3.473552e+08,...,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988,323010160,0.25
152,3,3,NaN,NaN,NaN,KAM,70,2025-11-01,2.434639e+08,3.473552e+08,...,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988,323015060,0.70
153,3,3,NaN,NaN,NaN,KAM,71,2025-12-01,4.575161e+08,3.416811e+08,...,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988,323007334,0.05
154,3,3,NaN,NaN,NaN,KAM,71,2025-12-01,4.575161e+08,3.416811e+08,...,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988,323010160,0.25
155,3,3,NaN,NaN,NaN,KAM,71,2025-12-01,4.575161e+08,3.416811e+08,...,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,5016988,323015060,0.70

In [232]:
venta_facturada_grupo_clientes_kam_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main_centro_costo, 'VentaFacturadaGrupoClientesKAMSSub')
venta_facturada_grupo_clientes_kam_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,5004293_1,2025-01-01,630,HC,323015090,4.840923e+08,6.371832e+08,VentaFacturadaGrupoClientesKAMSSub
1,5004293_1,2025-02-01,630,HC,323015090,1.456452e+09,1.504837e+09,VentaFacturadaGrupoClientesKAMSSub
2,5004293_1,2025-03-01,630,HC,323015090,2.633030e+09,2.792760e+09,VentaFacturadaGrupoClientesKAMSSub
3,5004293_1,2025-04-01,630,HC,323015090,3.519760e+09,3.633300e+09,VentaFacturadaGrupoClientesKAMSSub
4,5004293_1,2025-05-01,630,HC,323015090,4.750751e+09,4.772095e+09,VentaFacturadaGrupoClientesKAMSSub
5,5004293_1,2025-06-01,630,HC,323015090,5.941892e+09,6.046461e+09,VentaFacturadaGrupoClientesKAMSSub
6,5004293_1,2025-07-01,630,HC,323015090,7.377176e+09,7.239485e+09,VentaFacturadaGrupoClientesKAMSSub
7,5004293_1,2025-08-01,630,HC,323015090,8.207827e+09,8.418952e+09,VentaFacturadaGrupoClientesKAMSSub
8,5004293_1,2025-09-01,630,HC,323015090,9.118308e+09,9.679761e+09,VentaFacturadaGrupoClientesKAMSSub
9,5004293_1,2025-10-01,630,HC,323015090,9.915875e+09,1.083211e+10,VentaFacturadaGrupoClientesKAMSSub
10,5004293_1,2025-11-01,630,HC,323015090,1.107049e+10,1.213359e+10,VentaFacturadaGrupoClientesKAMSSub
11,5004293_1,2025-12-01,630,HC,323015090,1.243884e+10,1.355709e+10,VentaFacturadaGrupoClientesKAMSSub
12,5004293_2,2025-01-01,630,HC,323015090,1.388437e+09,2.126956e+09,VentaFacturadaGrupoClientesKAMSSub
13,5004293_2,2025-01-01,CDK,HC,323015090,1.388437e+09,2.126956e+09,VentaFacturadaGrupoClientesKAMSSub
14,5004293_2,2025-02-01,630,HC,323015090,3.838732e+09,5.014116e+09,VentaFacturadaGrupoClientesKAMSSub
15,5004293_2,2025-02-01,CDK,HC,323015090,3.838732e+09,5.014116e+09,VentaFacturadaGrupoClientesKAMSSub
16,5004293_2,2025-03-01,630,HC,323015090,6.315124e+09,9.302574e+09,VentaFacturadaGrupoClientesKAMSSub
17,5004293_2,2025-03-01,CDK,HC,323015090,6.315124e+09,9.302574e+09,VentaFacturadaGrupoClientesKAMSSub
18,5004293_2,2025-04-01,630,HC,323015090,9.453676e+09,1.210354e+10,VentaFacturadaGrupoClientesKAMSSub
19,5004293_2,2025-04-01,CDK,HC,323015090,9.453676e+09,1.210354e+10,VentaFacturadaGrupoClientesKAMSSub
20,5004293_2,2025-05-01,630,HC,323015090,1.330461e+10,1.589255e+10,VentaFacturadaGrupoClientesKAMSSub
21,5004293_2,2025-05-01,CDK,HC,323015090,1.330461e+10,1.589255e+10,VentaFacturadaGrupoClientesKAMSSub
22,5004293_2,2025-06-01,630,HC,323015090,1.640146e+10,2.012881e+10,VentaFacturadaGrupoClientesKAMSSub
23,5004293_2,2025-06-01,CDK,HC,323015090,1.640146e+10,2.012881e+10,VentaFacturadaGrupoClientesKAMSSub
24,5004293_2,2025-07-01,630,HC,323015090,1.933301e+10,2.409944e+10,VentaFacturadaGrupoClientesKAMSSub
25,5004293_2,2025-07-01,CDK,HC,323015090,1.933301e+10,2.409944e+10,VentaFacturadaGrupoClientesKAMSSub
26,5004293_2,2025-08-01,630,HC,323015090,2.170078e+10,2.802222e+10,VentaFacturadaGrupoClientesKAMSSub
27,5004293_2,2025-08-01,CDK,HC,323015090,2.170078e+10,2.802222e+10,VentaFacturadaGrupoClientesKAMSSub
28,5004293_2,2025-09-01,630,HC,323015090,2.503624e+10,3.221579e+10,VentaFacturadaGrupoClientesKAMSSub
29,5004293_2,2025-09-01,CDK,HC,323015090,2.503624e+10,3.221579e+10,VentaFacturadaGrupoClientesKAMSSub
30,5004293_2,2025-10-01,630,HC,323015090,2.788897e+10,3.605292e+10,VentaFacturadaGrupoClientesKAMSSub
31,5004293_2,2025-10-01,CDK,HC,323015090,2.788897e+10,3.605292e+10,VentaFacturadaGrupoClientesKAMSSub
32,5004293_2,2025-11-01,630,HC,323015090,3.155132e+10,4.038950e+10,VentaFacturadaGrupoClientesKAMSSub
33,5004293_2,2025-11-01,CDK,HC,323015090,3.155132e+10,4.038950e+10,VentaFacturadaGrupoClientesKAMSSub
34,5004293_2,2025-12-01,630,HC,323015090,3.531158e+10,4.513309e+10,VentaFacturadaGrupoClientesKAMSSub
35,5004293_2,2025-12-01,CDK,HC,323015090,3.531158e+10,4.513309e+10,VentaFacturadaGrupoClientesKAMSSub
36,5004293_3,2025-01-01,620,HC,323015090,7.359598e+08,9.945810e+08,VentaFacturadaGrupoClientesKAMSSub
37,5004293_3,2025-02-01,620,HC,323015090,1.631783e+09,2.113485e+09,VentaFacturadaGrupoClientesKAMSSub
38,5004293_3,2025-03-01,620,HC,323015090,3.061162e+09,3.356711e+09,VentaFacturadaGrupoClientesKAMSSub
39,5004293_3,2025-04-01,620,HC,323015090,4.122461e+09,4.382373e+09,VentaFacturadaGrupoClientesKAMSSub
40,5004293_3,2025-05-01,620,HC,323015090,5.448178e+09,5.718841e+09,VentaFacturadaGrupoClientesKAMSSub
41,5004293_3,2025-06-01,620,HC,323015090,6.623818e+09,7.008688e+09,VentaFacturadaGrupoClientesKAMSSub
42,5004293_3,2025-07-01,620,HC,323015090,7.394211e+09,8.220834e+09,VentaFacturadaGrupoClientesKAMSSub
43,5004293_3,2025-08-01,620,HC,323015090,8.320768e+09,9.432980e+09,VentaFacturadaGrupoClientesKAMSSub
44,5004293_3,2025-09-01,620,HC,323015090,9.531061e+09,1.072283e+10,VentaFacturadaGrupoClientesKAMSSub
45,5004293_3,2025-10-01,620,HC,323015090,1.073754e+10,1.210592e+10,VentaFacturadaGrupoClientesKAMSSub
46,5004293_3,2025-11-01,620,HC,323015090,1.208893e+10,1.365995e+10,VentaFacturadaGrupoClientesKAMSSub
47,5004293_3,2025-12-01,620,HC,323015090,1.371596e+10,1.554033e+10,VentaFacturadaGrupoClientesKAMSSub

In [233]:
df_empleados[
    (df_empleados['TipoEmpleado'] == 'KAM') &
    (df_empleados['AreaCalculo'] == 3)
]

,TipoEmpleado,CodigoEmpleado,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,AreaCalculo
78,KAM,5016988,42897142,silvia.marin@bbraun.com,SILVIA ELENA,MARIN ESCOBAR,5297000.0,2019-08-01,NaT,3

In [234]:
# main['Real'] = main.groupby(['Contexto', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
# main['Presupuesto'] = main.groupby(['Contexto', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)

# main['Contexto'] = main['Contexto'].str.lower() + '_'+ main['Consecutivo'].astype(int).astype('str')
# main['Variable'] = 'VentaFacturadaGrupoClientesKAMSSub'
# main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
# main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

# venta_facturada_grupo_clientes_kams_sub = main
# main = None
# venta_facturada_grupo_clientes_kams_sub

# Contexto: TipoEmpleado_AreaCalculo_Consecutivo

In [235]:
main['Real'] = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)

main['Contexto'] = main['TipoEmpleado'].str.lower() + '_' +  main['AreaCalculo'].astype(int).astype('str') + '_'+ main['Consecutivo'].astype(int).astype('str')
main['Variable'] = 'VentaFacturadaGrupoClientesKAMSSub'
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

venta_facturada_grupo_clientes_kams_sub = main
main = None
venta_facturada_grupo_clientes_kams_sub

# # Contexto: TipoEmpleado_AreaCalculo_Consecutivo

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,kam_2_1,VentaFacturadaGrupoClientesKAMSSub,2025-01-01,4.840923e+08,6.371832e+08,0.76
1,kam_2_1,VentaFacturadaGrupoClientesKAMSSub,2025-02-01,1.456452e+09,1.504837e+09,0.97
2,kam_2_1,VentaFacturadaGrupoClientesKAMSSub,2025-03-01,2.633030e+09,2.792760e+09,0.94
3,kam_2_1,VentaFacturadaGrupoClientesKAMSSub,2025-04-01,3.519760e+09,3.633300e+09,0.97
4,kam_2_1,VentaFacturadaGrupoClientesKAMSSub,2025-05-01,4.750751e+09,4.772095e+09,1.00
...,...,...,...,...,...,...
67,kam_3_3,VentaFacturadaGrupoClientesKAMSSub,2025-08-01,1.627837e+09,2.198713e+09,0.74
68,kam_3_3,VentaFacturadaGrupoClientesKAMSSub,2025-09-01,1.744950e+09,2.540113e+09,0.69
69,kam_3_3,VentaFacturadaGrupoClientesKAMSSub,2025-10-01,2.012716e+09,2.909829e+09,0.69
70,kam_3_3,VentaFacturadaGrupoClientesKAMSSub,2025-11-01,2.256180e+09,3.257184e+09,0.69
71,kam_3_3,VentaFacturadaGrupoClientesKAMSSub,2025-12-01,2.713696e+09,3.598865e+09,0.75

## 33. KPIs Surgical

In [236]:
df_resultados_variables_cualitativas

,Variable,CodigoEmpleado,TipoEmpleado,AreaCalculo,Consecutivo,PorcentajeCumplimiento,Fecha
0,KpisSurgical,20759929,AD2,1,2,1.12,2025-01-01
1,KpisSurgical,1113625698,AD2,1,2,1.12,2025-01-01
2,KpisSurgical,1073521514,AD2,1,2,1.12,2025-01-01
3,KpisSurgical,1026279360,AD2,1,2,1.12,2025-01-01
4,KpisSurgical,1026251149,AD2,1,2,1.12,2025-01-01
...,...,...,...,...,...,...,...
367,KpisSurgical,1018418655,AD2,1,3,1.00,2025-12-01
368,KpisSurgical,1032400978,AD2,2,2,1.00,2025-12-01
369,KpisSurgical,1026292468,AD2,2,2,1.00,2025-12-01
370,KpisSurgical,1026292468,AD2,2,3,1.00,2025-12-01
371,KpisSurgical,1032400978,AD2,2,3,1.00,2025-12-01

In [237]:
### Cálculo de resultados cualitativos precargados
main = df_resultados_variables_cualitativas[df_resultados_variables_cualitativas['Variable'] == 'KpisSurgical'].copy()
main['Contexto'] = main['CodigoEmpleado'].str.lower() + '_' + main['Consecutivo'].astype(int).astype('str')
main['Real'] = np.nan
main['Presupuesto'] = np.nan
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
###
kpis_surgical = main
main = None
kpis_surgical

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,20759929_2,KpisSurgical,2025-01-01,NaN,NaN,1.12
1,1113625698_2,KpisSurgical,2025-01-01,NaN,NaN,1.12
2,1073521514_2,KpisSurgical,2025-01-01,NaN,NaN,1.12
3,1026279360_2,KpisSurgical,2025-01-01,NaN,NaN,1.12
4,1026251149_2,KpisSurgical,2025-01-01,NaN,NaN,1.12
...,...,...,...,...,...,...
367,1018418655_3,KpisSurgical,2025-12-01,NaN,NaN,1.00
368,1032400978_2,KpisSurgical,2025-12-01,NaN,NaN,1.00
369,1026292468_2,KpisSurgical,2025-12-01,NaN,NaN,1.00
370,1026292468_3,KpisSurgical,2025-12-01,NaN,NaN,1.00
371,1032400978_3,KpisSurgical,2025-12-01,NaN,NaN,1.00

# Nuevos rubros 2023

## 34. VentaCobradaPortafolioZonaClusterSub

In [238]:
df_area_calculo_sba_centros_costos_ve = df_area_calculo_sba_centros_costos[
    df_area_calculo_sba_centros_costos['TipoEmpleado'] == 'VE'
]
df_area_calculo_sba_centros_costos_ve =  df_area_calculo_sba_centros_costos_ve.rename(columns={'ConsecutivoParrilla':'Consecutivo'})

df_area_calculo_sba_centros_costos_ve.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 416 to 450
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TipoEmpleado       35 non-null     object
 1   AreaCalculo        35 non-null     int32
 2   Consecutivo        35 non-null     int64
 3   Division           35 non-null     object
 4   GrupoProducto      35 non-null     object
 5   SBA                14 non-null     object
 6   CodigoCentroCosto  35 non-null     float64
dtypes: float64(1), int32(1), int64(1), object(4)
memory usage: 2.1+ KB

In [239]:
area_calculo_sba_completo_ve = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado'] == 'VE']
area_calculo_sba_completo_ve.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74 entries, 286 to 305
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AreaCalculo    74 non-null     int32
 1   Consecutivo    74 non-null     int32
 2   Division       74 non-null     object
 3   GrupoProducto  74 non-null     object
 4   SBA            74 non-null     object
 5   TipoEmpleado   74 non-null     object
dtypes: int32(2), object(4)
memory usage: 3.5+ KB

In [240]:
area_calculo_sba_completo_ve.merge(
    df_area_calculo_sba_centros_costos_ve.fillna(''),
    on=['AreaCalculo', 'Consecutivo', 'Division','GrupoProducto', 'SBA','TipoEmpleado'],
    how='left'
).head()

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,CodigoCentroCosto
0,1,1,AE,005,,VE,323010140.0
1,1,1,AE,M07,,VE,323010140.0
2,1,2,AE,M08,,VE,323010140.0
3,2,1,AE,003,,VE,323007260.0
4,2,1,AE,CEK,30,VE,323010140.0

In [241]:
df_area_calculo_sba_centros_costos_ve = area_calculo_sba_completo_ve.merge(
    df_centros_costos_grupos_productos_divisiones,
    on=['Division','GrupoProducto'],
    how='left'
)
df_area_calculo_sba_centros_costos_ve

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,CodigoCentroCosto
0,1,1,AE,005,,VE,323010140
1,1,1,AE,M07,,VE,323010140
2,1,2,AE,M08,,VE,323010140
3,2,1,AE,003,,VE,323007260
4,2,1,AE,CEK,30,VE,323010140
...,...,...,...,...,...,...,...
69,13,1,AE,003,35,VE,323007260
70,13,2,AE,801,32,VE,323007350
71,13,2,AE,801,30,VE,323007350
72,13,2,AE,801,33,VE,323007350
73,13,2,AE,801,31,VE,323007350

In [242]:
venta_recaudo_presupuesto_original_ve_real.head()

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,ZonaGeografica,Cluster,Canal,Fecha,Venta,Recaudo
0,2,1,AE,CEK,30,VE,Suroccidente,12,Distribuidor,2025-02-01,323000.0,0.0
1,2,1,AE,CEK,30,VE,Centro,5,Hospital Público,2025-01-01,0.0,0.0
2,2,1,AE,CEK,30,VE,Centro,5,Hospital Público,2025-02-01,0.0,0.0
3,2,1,AE,CEK,30,VE,Centro,5,Hospital Público,2025-03-01,0.0,0.0
4,2,1,AE,CEK,30,VE,Centro,5,Hospital Público,2025-04-01,0.0,0.0

### Merge entre area de cálculo SBA y Venta Recaudo Presupuesto

In [243]:
# Se remplaza lógica de área de cálculo SBA
# drop_cols = ['Canal', 'TipoEmpleado','Venta']
# venta_recaudo_presupuesto_original_ve_real_zona_cluster = pd.merge(
#     left=area_calculo_sba_completo_ve,
#     right=venta_recaudo_presupuesto_original_ve_real,
#     on=['AreaCalculo', 'Consecutivo', 'Division','GrupoProducto', 'SBA', 'TipoEmpleado'],
#     how='left'
# )

# venta_recaudo_presupuesto_original_ve_real_zona_cluster

In [244]:
drop_cols = ['Canal', 'TipoEmpleado','Venta']
venta_recaudo_presupuesto_original_ve_real_zona_cluster = pd.merge(
    left=df_area_calculo_sba_centros_costos_ve,
    right=venta_recaudo_presupuesto_original_ve_real,
    on=['AreaCalculo', 'Consecutivo', 'Division','GrupoProducto', 'SBA','TipoEmpleado'],
    how='left'
)

venta_recaudo_presupuesto_original_ve_real_zona_cluster

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,CodigoCentroCosto,ZonaGeografica,Cluster,Canal,Fecha,Venta,Recaudo
0,1,1,AE,005,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
1,1,1,AE,M07,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
2,1,2,AE,M08,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
3,2,1,AE,003,,VE,323007260,NaN,NaN,NaN,NaT,NaN,NaN
4,2,1,AE,CEK,30,VE,323010140,Suroccidente,12,Distribuidor,2025-02-01,323000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26165,13,2,AE,801,33,VE,323007350,Centro,7,Distribuidor,2025-11-01,0.0,0.0
26166,13,2,AE,801,33,VE,323007350,Centro,7,Distribuidor,2025-12-01,0.0,0.0
26167,13,2,AE,801,33,VE,323007350,Norte,15,HOSPITAL,2025-02-01,300000.0,0.0
26168,13,2,AE,801,33,VE,323007350,Norte,15,HOSPITAL,2025-03-01,-17850.0,282150.0
26169,13,2,AE,801,31,VE,323007350,Centro,0,Televentas Distribuidor,2025-12-01,11344000.0,11344000.0

### Merge entre area de cálculo SBA y Venta Recaudo Presupuesto y Empleado

In [245]:
# Se remplaza lógica de área de cálculo SBA
# venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster = pd.merge(
#     left=area_calculo_sba_completo_ve,
#     right=venta_recaudo_presupuesto_original_ve_presupuesto,
#     on=['AreaCalculo', 'Consecutivo', 'Division','GrupoProducto', 'SBA', 'TipoEmpleado'],
#     how='left'
# )
# venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster

In [246]:
df_area_calculo_sba_centros_costos_ve[df_area_calculo_sba_centros_costos_ve['AreaCalculo'] == 11]

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,CodigoCentroCosto
28,11,1,BA,A35,,VE,323007330
62,11,1,BA,A35,87,VE,323007330

In [247]:
venta_recaudo_presupuesto_original_ve_presupuesto[
    (venta_recaudo_presupuesto_original_ve_presupuesto['AreaCalculo']==11) &
    (venta_recaudo_presupuesto_original_ve_presupuesto['Fecha']=="2025-03-01") &
    (venta_recaudo_presupuesto_original_ve_presupuesto['ZonaGeografica']=="Centro")
]

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,ZonaGeografica,Cluster,Canal,Fecha,Venta,Recaudo
22682,11,1,BA,A35,87,VE,Centro,22,Asegurador,2025-03-01,2.068764e+07,2.537385e+07
22696,11,1,BA,A35,87,VE,Centro,22,Distribuidor,2025-03-01,2.084347e+07,2.556497e+07
22702,11,1,BA,A35,87,VE,Centro,22,HOSPITAL,2025-03-01,0.000000e+00,0.000000e+00
22709,11,1,BA,A35,87,VE,Centro,22,Hospital Privado,2025-03-01,2.100000e+06,2.575696e+06
22730,11,1,BA,A35,87,VE,Centro,22,No definido,2025-03-01,0.000000e+00,0.000000e+00
22733,11,1,BA,A35,87,VE,Centro,22,OPL,2025-03-01,1.003382e+08,1.230670e+08
22747,11,1,BA,A35,87,VE,Centro,22,Renal AMB,2025-03-01,1.142974e+07,1.401882e+07
22762,11,1,BA,A35,87,VE,Centro,22,Televentas Distribuidor,2025-03-01,3.268150e+06,4.008457e+06

In [248]:
venta_recaudo_presupuesto_original_ve_presupuesto[
    (venta_recaudo_presupuesto_original_ve_presupuesto['AreaCalculo']==11) &
    (venta_recaudo_presupuesto_original_ve_presupuesto['Fecha']=="2025-03-01") &
    (venta_recaudo_presupuesto_original_ve_presupuesto['ZonaGeografica']=="Centro")
]['Venta'].sum()

158667200.21181273

In [249]:
venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster = pd.merge(
    left=df_area_calculo_sba_centros_costos_ve, 
    right=venta_recaudo_presupuesto_original_ve_presupuesto,
    on=['AreaCalculo', 'Consecutivo', 'Division','GrupoProducto', 'SBA','TipoEmpleado'],
    how='left'
)
venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,CodigoCentroCosto,ZonaGeografica,Cluster,Canal,Fecha,Venta,Recaudo
0,1,1,AE,005,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
1,1,1,AE,M07,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
2,1,2,AE,M08,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
3,2,1,AE,003,,VE,323007260,NaN,NaN,NaN,NaT,NaN,NaN
4,2,1,AE,CEK,30,VE,323010140,Suroccidente,12,Distribuidor,2025-02-01,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27002,13,2,AE,801,33,VE,323007350,Centro,7,Distribuidor,2025-11-01,25233.667277,26065.334969
27003,13,2,AE,801,33,VE,323007350,Centro,7,Distribuidor,2025-12-01,24574.706212,28671.868465
27004,13,2,AE,801,33,VE,323007350,Norte,15,HOSPITAL,2025-02-01,0.000000,0.000000
27005,13,2,AE,801,33,VE,323007350,Norte,15,HOSPITAL,2025-03-01,0.000000,0.000000
27006,13,2,AE,801,31,VE,323007350,Centro,0,Televentas Distribuidor,2025-12-01,0.000000,0.000000

In [250]:
venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster[
    (venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster['AreaCalculo']==11) &
    (venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster['Fecha']=="2024-01-01") &
    (venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster['ZonaGeografica']=="Centro")
]

Empty DataFrame
Columns: [AreaCalculo, Consecutivo, Division, GrupoProducto, SBA, TipoEmpleado, CodigoCentroCosto, ZonaGeografica, Cluster, Canal, Fecha, Venta, Recaudo]
Index: []

In [251]:
venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster[
    (venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster['AreaCalculo']==11) &
    (venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster['Fecha']=="2024-01-01")
]['Venta'].sum()

0.0

In [252]:
venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster[
    (venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster['AreaCalculo']==11) &
    (venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster['Fecha']=="2024-01-01")
]['Recaudo'].sum()

0.0

In [253]:
venta_recaudo_presupuesto_original_ve_real_zona_cluster[
    (venta_recaudo_presupuesto_original_ve_real_zona_cluster['AreaCalculo']==11) &
    (venta_recaudo_presupuesto_original_ve_real_zona_cluster['Fecha']=="2024-01-01")
]

Empty DataFrame
Columns: [AreaCalculo, Consecutivo, Division, GrupoProducto, SBA, TipoEmpleado, CodigoCentroCosto, ZonaGeografica, Cluster, Canal, Fecha, Venta, Recaudo]
Index: []

In [254]:
venta_recaudo_presupuesto_original_ve_real_zona_cluster[
    (venta_recaudo_presupuesto_original_ve_real_zona_cluster['AreaCalculo']==11)
]['Recaudo'].sum()

2428016744.5200005

In [255]:
venta_recaudo_presupuesto_original_ve_real_zona_cluster[
    (venta_recaudo_presupuesto_original_ve_real_zona_cluster['AreaCalculo']==11) 
]['Venta'].sum()

2081712003.3999999

In [256]:
recaudo_real_zona_ve = venta_recaudo_presupuesto_original_ve_real_zona_cluster.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha','Cluster','Consecutivo', 'Division','GrupoProducto', 'SBA','CodigoCentroCosto'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_real_zona_ve.rename(columns={'Recaudo': 'Real'}, inplace=True)
recaudo_real_zona_ve

,AreaCalculo,ZonaGeografica,Fecha,Cluster,Consecutivo,Division,GrupoProducto,SBA,CodigoCentroCosto,Real
0,1,Centro,2025-01-01,1,1,AE,005,33,323010140,-39550.58
1,1,Centro,2025-01-01,1,1,AE,M07,33,323010140,92916138.85
2,1,Centro,2025-01-01,1,2,AE,M08,33,323010140,55385938.87
3,1,Centro,2025-01-01,2,1,AE,005,33,323010140,1305972.43
4,1,Centro,2025-01-01,2,1,AE,M07,33,323010140,12552102.07
...,...,...,...,...,...,...,...,...,...,...
8174,13,Venezuela,2025-08-01,0,1,AE,003,35,323007260,0.00
8175,13,Venezuela,2025-09-01,0,1,AE,003,35,323007260,0.00
8176,13,Venezuela,2025-10-01,0,1,AE,003,35,323007260,0.00
8177,13,Venezuela,2025-11-01,0,1,AE,003,35,323007260,0.00
8178,13,Venezuela,2025-12-01,0,1,AE,003,35,323007260,0.00

In [257]:
recaudo_real_zona_ve[
    (recaudo_real_zona_ve['AreaCalculo']==11) &
    (recaudo_real_zona_ve['Fecha']=="2024-01-01")
]

Empty DataFrame
Columns: [AreaCalculo, ZonaGeografica, Fecha, Cluster, Consecutivo, Division, GrupoProducto, SBA, CodigoCentroCosto, Real]
Index: []

In [258]:
recaudo_real_zona_ve[
    (recaudo_real_zona_ve['AreaCalculo']==11) &
    (recaudo_real_zona_ve['Fecha']=="2024-01-01")
]['Real'].sum()

0.0

In [259]:
venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster[
    (venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster['AreaCalculo']==11)
]['Venta'].sum()

2804999999.914276

In [260]:
venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster[
    (venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster['AreaCalculo']==11)
]['Recaudo'].sum()

2675861882.4482193

In [261]:
recaudo_presupuesto_zona_ve = venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha','Cluster','Consecutivo', 'Division','GrupoProducto', 'SBA', 'CodigoCentroCosto'], as_index=False).agg({'Recaudo': 'sum'})
recaudo_presupuesto_zona_ve.rename(columns={'Recaudo': 'Presupuesto'}, inplace=True)
recaudo_presupuesto_zona_ve

,AreaCalculo,ZonaGeografica,Fecha,Cluster,Consecutivo,Division,GrupoProducto,SBA,CodigoCentroCosto,Presupuesto
0,1,Centro,2025-01-01,1,1,AE,005,33,323010140,1.729066e+06
1,1,Centro,2025-01-01,1,1,AE,M07,33,323010140,1.373735e+08
2,1,Centro,2025-01-01,1,2,AE,M08,33,323010140,7.126454e+07
3,1,Centro,2025-01-01,2,1,AE,005,33,323010140,2.062267e+06
4,1,Centro,2025-01-01,2,1,AE,M07,33,323010140,2.358567e+07
...,...,...,...,...,...,...,...,...,...,...
8193,13,Venezuela,2025-08-01,0,1,AE,003,35,323007260,1.884346e+07
8194,13,Venezuela,2025-09-01,0,1,AE,003,35,323007260,1.880972e+07
8195,13,Venezuela,2025-10-01,0,1,AE,003,35,323007260,2.173343e+07
8196,13,Venezuela,2025-11-01,0,1,AE,003,35,323007260,1.750849e+07
8197,13,Venezuela,2025-12-01,0,1,AE,003,35,323007260,2.293400e+07

In [262]:
recaudo_presupuesto_zona_ve[
    (recaudo_presupuesto_zona_ve['AreaCalculo']==11) &
    (recaudo_presupuesto_zona_ve['Fecha']=="2024-01-01")
]['Presupuesto'].sum()

0.0

In [263]:
# recaudo_real_zona_ve = venta_recaudo_presupuesto_original_ve_real_zona_cluster.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha','Cluster', 'Consecutivo'], as_index=False).agg({'Recaudo': 'sum'})
# recaudo_real_zona_ve.rename(columns={'Recaudo': 'Real'}, inplace=True)

# recaudo_presupuesto_zona_ve = venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha','Cluster', 'Consecutivo'], as_index=False).agg({'Recaudo': 'sum'})
# recaudo_presupuesto_zona_ve.rename(columns={'Recaudo': 'Presupuesto'}, inplace=True)

main = pd.merge(
    left=recaudo_presupuesto_zona_ve,
    right=recaudo_real_zona_ve,
    on=['ZonaGeografica', 'AreaCalculo', 'Fecha', 'Cluster', 'Consecutivo', 'GrupoProducto', 'Division', 'SBA', 'CodigoCentroCosto'],
    how='left'
)

main['Real'].fillna(0.0, inplace=True)

main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4126891184.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)

,AreaCalculo,ZonaGeografica,Fecha,Cluster,Consecutivo,Division,GrupoProducto,SBA,CodigoCentroCosto,Presupuesto,Real
0,1,Centro,2025-01-01,1,1,AE,005,33,323010140,1.729066e+06,-39550.58
1,1,Centro,2025-01-01,1,1,AE,M07,33,323010140,1.373735e+08,92916138.85
2,1,Centro,2025-01-01,1,2,AE,M08,33,323010140,7.126454e+07,55385938.87
3,1,Centro,2025-01-01,2,1,AE,005,33,323010140,2.062267e+06,1305972.43
4,1,Centro,2025-01-01,2,1,AE,M07,33,323010140,2.358567e+07,12552102.07
...,...,...,...,...,...,...,...,...,...,...,...
8193,13,Venezuela,2025-08-01,0,1,AE,003,35,323007260,1.884346e+07,0.00
8194,13,Venezuela,2025-09-01,0,1,AE,003,35,323007260,1.880972e+07,0.00
8195,13,Venezuela,2025-10-01,0,1,AE,003,35,323007260,2.173343e+07,0.00
8196,13,Venezuela,2025-11-01,0,1,AE,003,35,323007260,1.750849e+07,0.00
8197,13,Venezuela,2025-12-01,0,1,AE,003,35,323007260,2.293400e+07,0.00

In [264]:
main[
    (main['Fecha'] == '2025-03-01') &
    (main['AreaCalculo'] == 11)
]['Presupuesto'].sum()

240827569.4203394

In [265]:
main[
    (main['Fecha'] == '2025-03-01') &
    (main['AreaCalculo'] == 11)
]['Real'].sum()

309436649.21000004

In [266]:
# df_zonas_clusters_empleado[
#     (df_zonas_clusters_empleado['CodigoEmpleado'] == '79625102') &
#     (df_zonas_clusters_empleado['TipoEmpleado'] == 'VE') &
#     (df_zonas_clusters_empleado['AreaCalculo'] == 11)
# ]

In [267]:
# main['Real'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha','Cluster', 'Consecutivo'])['Real'].transform(pd.Series.sum)
# main['Presupuesto'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha','Cluster', 'Consecutivo'])['Presupuesto'].transform(pd.Series.sum)
main['TipoEmpleado'] = 'VE'

### Agrupación a nivel de empleado por zonas

main = pd.merge(
    main,
    df_zonas_clusters_empleado[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Zona', 'Cluster']].rename(columns={'Zona': 'ZonaGeografica'}),
    on=['TipoEmpleado', 'AreaCalculo', 'ZonaGeografica', 'Cluster'],
    how='left'
)

main = pd.merge(
    main,
    df_empleados[['CodigoEmpleado', 'FechaIngreso']],
    on='CodigoEmpleado',
    how='left'
)

main = main[main['Fecha'] >= main['FechaIngreso']]
main

,AreaCalculo,ZonaGeografica,Fecha,Cluster,Consecutivo,Division,GrupoProducto,SBA,CodigoCentroCosto,Presupuesto,Real,TipoEmpleado,CodigoEmpleado,FechaIngreso
801,2,Centro,2025-01-01,0,1,AE,003,35,323007260,2.912491e+07,18494339.00,VE,70021443,2024-01-01
803,2,Centro,2025-01-01,0,1,AE,CEK,35,323010140,1.708104e+05,0.00,VE,70021443,2024-01-01
805,2,Centro,2025-01-01,0,2,AE,801,32,323007350,8.636373e+05,0.00,VE,70021443,2024-01-01
807,2,Centro,2025-01-01,0,3,AE,006,36,323007300,3.634276e+05,0.00,VE,70021443,2024-01-01
809,2,Centro,2025-01-01,1,1,AE,003,35,323007260,8.776566e+07,82635125.10,VE,70021443,2024-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9750,12,Suroccidente,2025-12-01,8,1,AE,805,30,323007290,8.216050e+07,71303714.68,VE,5039578,2024-11-01
9751,12,Suroccidente,2025-12-01,8,2,AE,M06,30,323007290,1.652868e+07,0.00,VE,5039578,2024-11-01
9752,12,Suroccidente,2025-12-01,8,2,AE,M06,31,323007290,6.726292e+06,25399800.00,VE,5039578,2024-11-01
9753,12,Suroccidente,2025-12-01,9,1,AE,805,30,323007290,2.561226e+07,0.00,VE,5039578,2024-11-01
9754,12,Suroccidente,2025-12-01,9,2,AE,M06,31,323007290,2.203846e+06,0.00,VE,5039578,2024-11-01

In [268]:
main[
    (main['TipoEmpleado'] == 'VE') &
    (main['Fecha'] == '2024-01-01') &
    (main['AreaCalculo'] == 11)
]

Empty DataFrame
Columns: [AreaCalculo, ZonaGeografica, Fecha, Cluster, Consecutivo, Division, GrupoProducto, SBA, CodigoCentroCosto, Presupuesto, Real, TipoEmpleado, CodigoEmpleado, FechaIngreso]
Index: []

In [269]:
main[
    (main['TipoEmpleado'] == 'VE') &
    (main['Fecha'] == '2024-01-01')&
    (main['AreaCalculo'] == 11)
]['Presupuesto'].sum()

0.0

In [270]:
main[
    (main['TipoEmpleado'] == 'VE') &
    (main['Fecha'] == '2024-01-01')&
    (main['AreaCalculo'] == 11)
]['Real'].sum()

0.0

In [271]:
venta_cobrada_portafolio_zona_cluster_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main, 'VentaCobradaPortafolioZonaClusterSub')
venta_cobrada_portafolio_zona_cluster_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,37270929_2,2025-09-01,680,HC,323015055,1.515251e+08,1.513846e+08,VentaCobradaPortafolioZonaClusterSub
1,37270929_2,2025-10-01,680,HC,323015055,2.840721e+08,3.429212e+08,VentaCobradaPortafolioZonaClusterSub
2,37270929_2,2025-11-01,680,HC,323015055,4.025508e+08,5.361033e+08,VentaCobradaPortafolioZonaClusterSub
3,37270929_2,2025-12-01,680,HC,323015055,5.625513e+08,7.424493e+08,VentaCobradaPortafolioZonaClusterSub
4,37270929_3,2025-09-01,610,HC,323015040,1.646508e+08,1.732026e+08,VentaCobradaPortafolioZonaClusterSub
...,...,...,...,...,...,...,...,...
865,70042060_5,2025-08-01,610,HC,323015040,8.998389e+08,7.095926e+08,VentaCobradaPortafolioZonaClusterSub
866,70042060_5,2025-09-01,610,HC,323015040,1.702112e+09,1.105032e+09,VentaCobradaPortafolioZonaClusterSub
867,70042060_5,2025-10-01,610,HC,323015040,2.338773e+09,1.472036e+09,VentaCobradaPortafolioZonaClusterSub
868,70042060_5,2025-11-01,610,HC,323015040,2.749961e+09,2.042130e+09,VentaCobradaPortafolioZonaClusterSub
869,70042060_5,2025-12-01,610,HC,323015040,3.471791e+09,2.374522e+09,VentaCobradaPortafolioZonaClusterSub

In [272]:
# main['Real'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha','Cluster', 'Consecutivo'])['Real'].transform(pd.Series.sum)
# main['Presupuesto'] = main.groupby(['AreaCalculo', 'ZonaGeografica', 'Fecha','Cluster', 'Consecutivo'])['Presupuesto'].transform(pd.Series.sum)
main_copy = main.copy()

main = main.groupby(['CodigoEmpleado', 'Fecha', 'Consecutivo'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Contexto'] = main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')

main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaPortafolioZonaClusterSub'
# main['Contexto'] = main['CodigoEmpleado']
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
###

venta_cobrada_portafolio_zona_cluster_sub = main.copy()
main = None

venta_cobrada_portafolio_zona_cluster_sub.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3672240460.py:5: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['CodigoEmpleado', 'Fecha', 'Consecutivo'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,37270929_2,VentaCobradaPortafolioZonaClusterSub,2025-09-01,1.515251e+08,1.513846e+08,1.00
1,37270929_3,VentaCobradaPortafolioZonaClusterSub,2025-09-01,1.646508e+08,1.732026e+08,0.95
2,37270929_2,VentaCobradaPortafolioZonaClusterSub,2025-10-01,2.840721e+08,3.429212e+08,0.83
3,37270929_3,VentaCobradaPortafolioZonaClusterSub,2025-10-01,3.261689e+08,3.347286e+08,0.97
4,37270929_2,VentaCobradaPortafolioZonaClusterSub,2025-11-01,4.025508e+08,5.361033e+08,0.75

In [273]:
venta_cobrada_portafolio_zona_cluster_sub[
    venta_cobrada_portafolio_zona_cluster_sub['Contexto'].str.contains('1060654227')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 34.1 VentaCobradaPortafolioZonaCluster

In [274]:
main = main_copy.copy()
main

,AreaCalculo,ZonaGeografica,Fecha,Cluster,Consecutivo,Division,GrupoProducto,SBA,CodigoCentroCosto,Presupuesto,Real,TipoEmpleado,CodigoEmpleado,FechaIngreso,Contexto
801,2,Centro,2025-01-01,0,1,AE,003,35,323007260,2.912491e+07,18494339.00,VE,70021443,2024-01-01,70021443_1
803,2,Centro,2025-01-01,0,1,AE,CEK,35,323010140,1.708104e+05,0.00,VE,70021443,2024-01-01,70021443_1
805,2,Centro,2025-01-01,0,2,AE,801,32,323007350,8.636373e+05,0.00,VE,70021443,2024-01-01,70021443_2
807,2,Centro,2025-01-01,0,3,AE,006,36,323007300,3.634276e+05,0.00,VE,70021443,2024-01-01,70021443_3
809,2,Centro,2025-01-01,1,1,AE,003,35,323007260,8.776566e+07,82635125.10,VE,70021443,2024-01-01,70021443_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9750,12,Suroccidente,2025-12-01,8,1,AE,805,30,323007290,8.216050e+07,71303714.68,VE,5039578,2024-11-01,5039578_1
9751,12,Suroccidente,2025-12-01,8,2,AE,M06,30,323007290,1.652868e+07,0.00,VE,5039578,2024-11-01,5039578_2
9752,12,Suroccidente,2025-12-01,8,2,AE,M06,31,323007290,6.726292e+06,25399800.00,VE,5039578,2024-11-01,5039578_2
9753,12,Suroccidente,2025-12-01,9,1,AE,805,30,323007290,2.561226e+07,0.00,VE,5039578,2024-11-01,5039578_1
9754,12,Suroccidente,2025-12-01,9,2,AE,M06,31,323007290,2.203846e+06,0.00,VE,5039578,2024-11-01,5039578_2

In [275]:

main = main.groupby(['CodigoEmpleado', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].sum()
main.reset_index(inplace=True)

# Variable solo de VCs y VEs #
if len(codigos_ve_vc) > 0 and fecha_liquidacion >= '2022-03-01' and fecha_liquidacion <= '2022-12-01':
    main = main[main['Fecha'] >= '2022-03-01']
###

main['Contexto'] = main['CodigoEmpleado']

main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaPortafolioZonaCluster'
# main['Contexto'] = main['CodigoEmpleado']
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
###

venta_cobrada_portafolio_zona_cluster = main.copy()
main = None

venta_cobrada_portafolio_zona_cluster.head()

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,37270929,VentaCobradaPortafolioZonaCluster,2025-09-01,3.161759e+08,3.245872e+08,0.97
1,37270929,VentaCobradaPortafolioZonaCluster,2025-10-01,6.102410e+08,6.776498e+08,0.90
2,37270929,VentaCobradaPortafolioZonaCluster,2025-11-01,9.318976e+08,1.123825e+09,0.83
3,37270929,VentaCobradaPortafolioZonaCluster,2025-12-01,1.212514e+09,1.474182e+09,0.82
4,5002697,VentaCobradaPortafolioZonaCluster,2025-01-01,1.278234e+09,1.390430e+09,0.92

In [276]:
venta_cobrada_portafolio_zona_cluster[venta_cobrada_portafolio_zona_cluster['Contexto'] == '79625102']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 35. VentaCobradaUnidadNegocioSub

In [277]:
# main = None

# venta_cobrada_portafolio_cluster_sub = main
# main = None
# venta_cobrada_portafolio_cluster_sub

# # Contexto:

## 36. VentaCobradaZonaPaisSub

In [278]:
area_calculo_sba_completo_gc = area_calculo_sba_completo[
    (area_calculo_sba_completo['TipoEmpleado'] == 'GC') |
    (area_calculo_sba_completo['TipoEmpleado'] == 'GD')
]

area_calculo_sba_completo_gc_without_dup = area_calculo_sba_completo_gc[['TipoEmpleado','Consecutivo', 'Division']].drop_duplicates()
area_calculo_sba_completo_gc_without_dup.head()

   TipoEmpleado  Consecutivo Division
20           GC            1       HC
21           GC            2       AE
22           GC            3       BA
29           GD            1       AE
40           GD            1       HC

### Se hace merge entre area de cálculo por GC y Venta Recaudo

In [279]:
drop_cols = ['Venta'] #'GrupoProducto', 'SBA'
recaudo_real_zona_gc = pd.merge(
    left=area_calculo_sba_completo_gc_without_dup,
    right=df_venta_recaudo_real,
    on=['Division'],
    how='left'
)
recaudo_real_zona_gc = recaudo_real_zona_gc.dropna(subset=['ZonaGeografica']).drop(columns=drop_cols)
recaudo_real_zona_gc.rename(columns={'Recaudo': 'Real'}, inplace=True)
recaudo_real_zona_gc

,TipoEmpleado,Consecutivo,Division,CodigoEmpleado,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Real
0,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,0.0
1,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-09-01,3316200.0
2,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-10-01,0.0
3,GC,1,HC,1111122,0,Suroccidente,620,Distribuidor,36,2025-11-01,32332950.0
4,GC,1,HC,1111122,0,Suroccidente,620,Distribuidor,36,2025-12-01,0.0
...,...,...,...,...,...,...,...,...,...,...,...
43719,GD,1,BA,9990014,14,Norte,A34,HOSPITAL,85,2025-08-01,273276.0
43720,GD,1,BA,9990014,14,Norte,A34,Hospital Privado,85,2025-07-01,0.0
43721,GD,1,BA,9990014,14,Norte,A34,Hospital Privado,85,2025-08-01,0.0
43722,GD,1,BA,9990014,14,Norte,A34,No Definido,85,2025-07-01,0.0
43723,GD,1,BA,9990014,14,Norte,A34,No Definido,85,2025-08-01,0.0

In [280]:
recaudo_presupuesto_zona_gc = pd.merge(
    left=area_calculo_sba_completo_gc_without_dup,
    right=df_venta_recaudo_presupuesto,
    on=['Division'],
    how='left'
)

recaudo_presupuesto_zona_gc = recaudo_presupuesto_zona_gc.drop(columns=drop_cols).dropna(subset=['ZonaGeografica'])
recaudo_presupuesto_zona_gc.rename(columns={'Recaudo': 'Presupuesto'}, inplace=True)
recaudo_presupuesto_zona_gc

,TipoEmpleado,Consecutivo,Division,CodigoEmpleado,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Presupuesto
0,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,0.000000e+00
1,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-09-01,0.000000e+00
2,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-10-01,0.000000e+00
3,GC,1,HC,1111122,0,Suroccidente,620,Distribuidor,36,2025-11-01,0.000000e+00
4,GC,1,HC,1111122,0,Suroccidente,620,Distribuidor,36,2025-12-01,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
45141,GD,1,BA,9990014,14,Norte,A34,HOSPITAL,85,2025-08-01,0.000000e+00
45142,GD,1,BA,9990014,14,Norte,A34,Hospital Privado,85,2025-07-01,4.428108e+06
45143,GD,1,BA,9990014,14,Norte,A34,Hospital Privado,85,2025-08-01,1.012139e+07
45144,GD,1,BA,9990014,14,Norte,A34,No Definido,85,2025-07-01,0.000000e+00
45145,GD,1,BA,9990014,14,Norte,A34,No Definido,85,2025-08-01,0.000000e+00

### Se hace merge entre recaudo presupuesto y recaudo real

In [281]:
main = pd.merge(
    left=recaudo_presupuesto_zona_gc,
    right=recaudo_real_zona_gc,
    on=['ZonaGeografica', 'Fecha', 'Consecutivo', 'Division', 'CodigoEmpleado', 'TipoEmpleado', 'Cluster', 'GrupoProducto', 'SBA', 'Canal'],
    how='outer'
)
main = main.dropna(subset=['ZonaGeografica']).drop(columns=['CodigoEmpleado'])
main

,TipoEmpleado,Consecutivo,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Presupuesto,Real
0,GD,1,AE,1,Centro,001,HOSPITAL,30,2025-01-01,0.000000e+00,48557000.0
1,GD,1,AE,1,Centro,001,Hospital Privado,30,2025-01-01,5.459983e+07,0.0
2,GD,1,AE,1,Centro,001,Hospital Público,30,2025-01-01,1.679995e+07,0.0
3,GD,1,AE,1,Centro,001,No definido,30,2025-01-01,1.121015e+07,0.0
4,GD,1,AE,1,Centro,001,Distribuidor,32,2025-01-01,5.206011e+04,0.0
...,...,...,...,...,...,...,...,...,...,...,...
45153,GC,2,AE,0,Venezuela,006,Distribuidor,36,2025-12-01,0.000000e+00,0.0
45154,GC,2,AE,0,Venezuela,003,Distribuidor,35,2025-12-01,2.293400e+07,0.0
45155,GC,2,AE,0,Venezuela,006,Distribuidor,36,2025-12-01,2.032319e+07,0.0
45156,GC,3,BA,0,Venezuela,A32,Distribuidor,84,2025-12-01,2.530143e+06,0.0
45157,GC,3,BA,0,Venezuela,A34,Distribuidor,85,2025-12-01,1.833949e+06,0.0

In [282]:
df_zonas_empleado_gc = df_zonas_empleado[
    (df_zonas_empleado['TipoEmpleado']== 'GC') |
    (df_zonas_empleado['TipoEmpleado']== 'GD')
]
df_zonas_empleado_gc

            Zona CodigoEmpleado TipoEmpleado  AreaCalculo
3         Centro        5016692           GD            2
5          Norte        5002711           GC            3
28         Norte        5041257           GD            1
34        Centro        5004298           GC            1
59  Suroccidente        5005980           GC            2
63  Suroccidente        5036358           GD            3

## Se hace merge entre el dataframe anterior y zonas empleados para obtener los código de los GC

In [283]:
main = main.merge(
    df_zonas_empleado_gc.rename(columns={'Zona': 'ZonaGeografica'}),
    on=['ZonaGeografica', 'TipoEmpleado'],
    how='left'
)
main['Real'].fillna(0.0, inplace=True)
main.dropna(subset=['CodigoEmpleado'])

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1486749291.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)

,TipoEmpleado,Consecutivo,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Presupuesto,Real,CodigoEmpleado,AreaCalculo
0,GD,1,AE,1,Centro,001,HOSPITAL,30,2025-01-01,0.000000e+00,48557000.0,5016692,2.0
1,GD,1,AE,1,Centro,001,Hospital Privado,30,2025-01-01,5.459983e+07,0.0,5016692,2.0
2,GD,1,AE,1,Centro,001,Hospital Público,30,2025-01-01,1.679995e+07,0.0,5016692,2.0
3,GD,1,AE,1,Centro,001,No definido,30,2025-01-01,1.121015e+07,0.0,5016692,2.0
4,GD,1,AE,1,Centro,001,Distribuidor,32,2025-01-01,5.206011e+04,0.0,5016692,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44957,GC,3,BA,11,Suroccidente,A34,HOSPITAL,85,2025-12-01,0.000000e+00,0.0,5005980,2.0
44958,GC,3,BA,11,Suroccidente,A34,No Definido,85,2025-12-01,7.080812e+06,0.0,5005980,2.0
44959,GC,3,BA,9,Suroccidente,660,No Definido,81,2025-12-01,7.129837e+05,0.0,5005980,2.0
44960,GC,3,BA,9,Suroccidente,A45,No Definido,80,2025-12-01,5.752500e+06,0.0,5005980,2.0
44961,GC,3,BA,9,Suroccidente,A45,No Definido,81,2025-12-01,3.526859e+06,0.0,5005980,2.0

In [284]:
# main[
#     (main['CodigoEmpleado'] == '5002711') &
#     (main['Consecutivo'] == 1)
# ].to_excel("VentaCobradaZonaPaisSub.xlsx")

In [285]:
venta_cobrada_zona_pais_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main=main, variable='VentaCobradaZonaPaisSub').copy()
venta_cobrada_zona_pais_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub
...,...,...,...,...,...,...,...,...
1631,nan_3,2025-10-01,A34,BA,323007332,0.000000e+00,1.453185e+07,VentaCobradaZonaPaisSub
1632,nan_3,2025-11-01,A32,BA,323007333,0.000000e+00,2.361370e+07,VentaCobradaZonaPaisSub
1633,nan_3,2025-11-01,A34,BA,323007332,0.000000e+00,1.636580e+07,VentaCobradaZonaPaisSub
1634,nan_3,2025-12-01,A32,BA,323007333,0.000000e+00,2.614385e+07,VentaCobradaZonaPaisSub
1635,nan_3,2025-12-01,A34,BA,323007332,0.000000e+00,1.819975e+07,VentaCobradaZonaPaisSub

In [286]:
main_copy = main.copy()
# Calcular
main['Contexto']= main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')

main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaZonaPaisSub'

#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real','Presupuesto','PorcentajeCumplimiento']]

venta_cobrada_zona_pais_sub = main
main = None
venta_cobrada_zona_pais_sub

# Contexto: Código de empleado, gerentes de canal.

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4197943351.py:5: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002711_1,VentaCobradaZonaPaisSub,2025-01-01,4.476423e+09,4.102103e+09,1.09
1,5002711_1,VentaCobradaZonaPaisSub,2025-02-01,6.900072e+09,7.932480e+09,0.87
2,5002711_1,VentaCobradaZonaPaisSub,2025-03-01,1.044979e+10,1.270034e+10,0.82
3,5002711_1,VentaCobradaZonaPaisSub,2025-04-01,1.391989e+10,1.665851e+10,0.84
4,5002711_1,VentaCobradaZonaPaisSub,2025-05-01,1.855924e+10,2.093226e+10,0.89
...,...,...,...,...,...,...
139,5041257_1,VentaCobradaZonaPaisSub,2025-08-01,4.051912e+10,4.626385e+10,0.88
140,5041257_1,VentaCobradaZonaPaisSub,2025-09-01,4.703381e+10,5.277081e+10,0.89
141,5041257_1,VentaCobradaZonaPaisSub,2025-10-01,5.230065e+10,5.909688e+10,0.88
142,5041257_1,VentaCobradaZonaPaisSub,2025-11-01,5.666496e+10,6.554675e+10,0.86
143,5041257_1,VentaCobradaZonaPaisSub,2025-12-01,6.439399e+10,7.208684e+10,0.89

In [287]:
venta_cobrada_zona_pais_sub[venta_cobrada_zona_pais_sub['Contexto'] == '6474959_1']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [288]:
venta_cobrada_zona_pais_sub[venta_cobrada_zona_pais_sub['Contexto'] == '6474959_2']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [289]:
venta_cobrada_zona_pais_sub[venta_cobrada_zona_pais_sub['Contexto'] == '5002711_3']

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
24,5002711_3,VentaCobradaZonaPaisSub,2025-01-01,2.204146e+09,2.499210e+09,0.88
25,5002711_3,VentaCobradaZonaPaisSub,2025-02-01,2.482664e+09,2.702631e+09,0.92
26,5002711_3,VentaCobradaZonaPaisSub,2025-03-01,2.944306e+09,2.893857e+09,1.02
27,5002711_3,VentaCobradaZonaPaisSub,2025-04-01,2.784601e+09,3.101129e+09,0.90
28,5002711_3,VentaCobradaZonaPaisSub,2025-05-01,2.892440e+09,3.316306e+09,0.87
29,5002711_3,VentaCobradaZonaPaisSub,2025-06-01,3.002045e+09,3.581374e+09,0.84
30,5002711_3,VentaCobradaZonaPaisSub,2025-07-01,3.155090e+09,3.818534e+09,0.83
31,5002711_3,VentaCobradaZonaPaisSub,2025-08-01,3.304163e+09,4.073927e+09,0.81
32,5002711_3,VentaCobradaZonaPaisSub,2025-09-01,4.291585e+09,4.349361e+09,0.99
33,5002711_3,VentaCobradaZonaPaisSub,2025-10-01,4.553275e+09,4.654171e+09,0.98
34,5002711_3,VentaCobradaZonaPaisSub,2025-11-01,4.686926e+09,5.043853e+09,0.93
35,5002711_3,VentaCobradaZonaPaisSub,2025-12-01,7.387144e+09,5.447922e+09,1.36

## 36.1 VentaCobradaZonaPais

In [290]:
main = main_copy
# Calcular
main['Contexto']= main['CodigoEmpleado']

main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main.reset_index(inplace=True)

main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaZonaPais'

#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real','Presupuesto','PorcentajeCumplimiento']]

venta_cobrada_zona_pais = main
main = None
venta_cobrada_zona_pais

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\687187662.py:5: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002711,VentaCobradaZonaPais,2025-01-01,7.452850e+09,7.434975e+09,1.00
1,5002711,VentaCobradaZonaPais,2025-02-01,1.075797e+10,1.218892e+10,0.88
2,5002711,VentaCobradaZonaPais,2025-03-01,1.596409e+10,1.795314e+10,0.89
3,5002711,VentaCobradaZonaPais,2025-04-01,1.990232e+10,2.300097e+10,0.87
4,5002711,VentaCobradaZonaPais,2025-05-01,2.554891e+10,2.847900e+10,0.90
...,...,...,...,...,...,...
67,5041257,VentaCobradaZonaPais,2025-08-01,4.051912e+10,4.626385e+10,0.88
68,5041257,VentaCobradaZonaPais,2025-09-01,4.703381e+10,5.277081e+10,0.89
69,5041257,VentaCobradaZonaPais,2025-10-01,5.230065e+10,5.909688e+10,0.88
70,5041257,VentaCobradaZonaPais,2025-11-01,5.666496e+10,6.554675e+10,0.86
71,5041257,VentaCobradaZonaPais,2025-12-01,6.439399e+10,7.208684e+10,0.89

## 36. VentaFacturadaPortafolioRenal

In [291]:
# Aplica VC5

In [292]:
area_calculo_sba_completo.head()

   AreaCalculo  Consecutivo Division GrupoProducto    SBA TipoEmpleado
0            1            1    BBMCO         BBMCO  BBMCO           AD
1            2            1    BBMCO         BBMCO  BBMCO           AD
2            3            1    BBMCO         BBMCO  BBMCO           AD
3            4            1    BBMCO         BBMCO  BBMCO           AD
4            1            1    BBMCO         BBMCO  BBMCO          AD1

In [293]:
df_renal_ambulatorio.head()

,CodigoEmpleado,TipoEmpleado,Fecha,PlanVentaTotal,PlanVentaCobradaRenal,RealVentaTotal,RealVentaCobradaRenal
0,70020733,VC,2025-01-01,0.000000e+00,3.603004e+09,0.0,3.414838e+09
1,70020733,VC,2025-02-01,0.000000e+00,4.015092e+08,0.0,2.318170e+08
2,70020733,VC,2025-03-01,1.010107e+08,4.371081e+08,48981739.0,3.250664e+08
3,70020733,VC,2025-04-01,1.010107e+08,4.114996e+08,116809058.0,6.926579e+08
4,70020733,VC,2025-05-01,1.443010e+07,4.588223e+08,29004736.0,3.876283e+08

In [294]:
7.384809+1044514+8.649572

1044530.034381

In [295]:
# Calcular

main = df_renal_ambulatorio.rename(columns={'PlanVentaTotal': 'Presupuesto', 'RealVentaTotal': 'Real'})

main['Contexto'] = main['CodigoEmpleado']

main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaPortafolioRenal'


#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real','Presupuesto', 'PorcentajeCumplimiento']]


venta_facturada_portafolio_renal = main.copy()
main = None
venta_facturada_portafolio_renal

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\2342841213.py:7: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,70020733,VentaFacturadaPortafolioRenal,2025-01-01,0.000000e+00,0.000000e+00,NaN
1,70020733,VentaFacturadaPortafolioRenal,2025-02-01,0.000000e+00,0.000000e+00,NaN
2,70020733,VentaFacturadaPortafolioRenal,2025-03-01,4.898174e+07,1.010107e+08,0.48
3,70020733,VentaFacturadaPortafolioRenal,2025-04-01,1.657908e+08,2.020214e+08,0.82
4,70020733,VentaFacturadaPortafolioRenal,2025-05-01,1.947955e+08,2.164515e+08,0.90
5,70020733,VentaFacturadaPortafolioRenal,2025-06-01,1.042674e+09,3.318923e+08,3.14
6,70020733,VentaFacturadaPortafolioRenal,2025-07-01,1.207981e+09,5.916341e+08,2.04
7,70020733,VentaFacturadaPortafolioRenal,2025-08-01,1.511885e+09,8.617008e+08,1.75
8,70020733,VentaFacturadaPortafolioRenal,2025-09-01,1.631805e+09,1.058887e+09,1.54
9,70020733,VentaFacturadaPortafolioRenal,2025-10-01,1.697115e+09,2.350944e+09,0.72
10,70020733,VentaFacturadaPortafolioRenal,2025-11-01,1.712784e+09,2.558109e+09,0.67
11,70020733,VentaFacturadaPortafolioRenal,2025-12-01,4.477497e+09,2.718873e+09,1.65
12,70034174,VentaFacturadaPortafolioRenal,2025-01-01,2.454276e+07,1.213789e+08,0.20
13,70034174,VentaFacturadaPortafolioRenal,2025-02-01,7.129116e+07,2.427579e+08,0.29
14,70034174,VentaFacturadaPortafolioRenal,2025-03-01,1.357002e+08,3.843667e+08,0.35
15,70034174,VentaFacturadaPortafolioRenal,2025-04-01,2.080647e+08,5.259754e+08,0.40
16,70034174,VentaFacturadaPortafolioRenal,2025-05-01,2.921723e+08,6.878140e+08,0.42
17,70034174,VentaFacturadaPortafolioRenal,2025-06-01,3.371065e+08,8.496526e+08,0.40
18,70034174,VentaFacturadaPortafolioRenal,2025-07-01,4.574365e+08,1.213789e+09,0.38
19,70034174,VentaFacturadaPortafolioRenal,2025-08-01,1.737962e+09,2.316636e+09,0.75
20,70034174,VentaFacturadaPortafolioRenal,2025-09-01,2.014585e+09,2.676300e+09,0.75
21,70034174,VentaFacturadaPortafolioRenal,2025-10-01,2.259203e+09,4.145091e+09,0.55
22,70034174,VentaFacturadaPortafolioRenal,2025-11-01,4.381517e+09,4.520276e+09,0.97
23,70034174,VentaFacturadaPortafolioRenal,2025-12-01,5.772389e+09,4.706111e+09,1.23

## 36.1 VentaCobradaPortafolioRenal

In [296]:
# Calcular

main = df_renal_ambulatorio.rename(columns={'PlanVentaCobradaRenal': 'Presupuesto', 'RealVentaCobradaRenal': 'Real'})

main['Contexto'] = main['CodigoEmpleado']

main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaCobradaPortafolioRenal'


#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real','Presupuesto', 'PorcentajeCumplimiento']]


venta_cobrada_portafolio_renal = main.copy()
main = None
venta_cobrada_portafolio_renal

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\4136071898.py:7: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,70020733,VentaCobradaPortafolioRenal,2025-01-01,3.414838e+09,3.603004e+09,0.95
1,70020733,VentaCobradaPortafolioRenal,2025-02-01,3.646655e+09,4.004513e+09,0.91
2,70020733,VentaCobradaPortafolioRenal,2025-03-01,3.971722e+09,4.441621e+09,0.89
3,70020733,VentaCobradaPortafolioRenal,2025-04-01,4.664379e+09,4.853121e+09,0.96
4,70020733,VentaCobradaPortafolioRenal,2025-05-01,5.052008e+09,5.311943e+09,0.95
5,70020733,VentaCobradaPortafolioRenal,2025-06-01,5.254993e+09,5.796016e+09,0.91
6,70020733,VentaCobradaPortafolioRenal,2025-07-01,5.566527e+09,6.256557e+09,0.89
7,70020733,VentaCobradaPortafolioRenal,2025-08-01,5.890852e+09,6.755404e+09,0.87
8,70020733,VentaCobradaPortafolioRenal,2025-09-01,7.067381e+09,7.296411e+09,0.97
9,70020733,VentaCobradaPortafolioRenal,2025-10-01,7.406524e+09,7.901396e+09,0.94
10,70020733,VentaCobradaPortafolioRenal,2025-11-01,7.648289e+09,8.647083e+09,0.88
11,70020733,VentaCobradaPortafolioRenal,2025-12-01,1.363875e+10,9.429269e+09,1.45
12,70034174,VentaCobradaPortafolioRenal,2025-01-01,3.414838e+09,3.603004e+09,0.95
13,70034174,VentaCobradaPortafolioRenal,2025-02-01,3.646655e+09,4.004513e+09,0.91
14,70034174,VentaCobradaPortafolioRenal,2025-03-01,3.971722e+09,4.441621e+09,0.89
15,70034174,VentaCobradaPortafolioRenal,2025-04-01,4.664379e+09,4.853121e+09,0.96
16,70034174,VentaCobradaPortafolioRenal,2025-05-01,5.052008e+09,5.311943e+09,0.95
17,70034174,VentaCobradaPortafolioRenal,2025-06-01,5.254993e+09,5.796016e+09,0.91
18,70034174,VentaCobradaPortafolioRenal,2025-07-01,5.566527e+09,6.256557e+09,0.89
19,70034174,VentaCobradaPortafolioRenal,2025-08-01,5.890852e+09,6.755404e+09,0.87
20,70034174,VentaCobradaPortafolioRenal,2025-09-01,7.067381e+09,7.296411e+09,0.97
21,70034174,VentaCobradaPortafolioRenal,2025-10-01,7.406524e+09,7.901396e+09,0.94
22,70034174,VentaCobradaPortafolioRenal,2025-11-01,7.648289e+09,8.647083e+09,0.88
23,70034174,VentaCobradaPortafolioRenal,2025-12-01,1.363875e+10,9.429269e+09,1.45

## 36.2 VentaFacturadaPortafolioRenalSub

In [297]:
renal_ambulatorio = df_renal_ambulatorio.copy()
renal_ambulatorio['Consecutivo'] = '1'
renal_ambulatorio

,CodigoEmpleado,TipoEmpleado,Fecha,PlanVentaTotal,PlanVentaCobradaRenal,RealVentaTotal,RealVentaCobradaRenal,Consecutivo
0,70020733,VC,2025-01-01,0.000000e+00,3.603004e+09,0.000000e+00,3.414838e+09,1
1,70020733,VC,2025-02-01,0.000000e+00,4.015092e+08,0.000000e+00,2.318170e+08,1
2,70020733,VC,2025-03-01,1.010107e+08,4.371081e+08,4.898174e+07,3.250664e+08,1
3,70020733,VC,2025-04-01,1.010107e+08,4.114996e+08,1.168091e+08,6.926579e+08,1
4,70020733,VC,2025-05-01,1.443010e+07,4.588223e+08,2.900474e+07,3.876283e+08,1
5,70020733,VC,2025-06-01,1.154408e+08,4.840730e+08,8.478787e+08,2.029854e+08,1
6,70020733,VC,2025-07-01,2.597418e+08,4.605407e+08,1.653069e+08,3.115334e+08,1
7,70020733,VC,2025-08-01,2.700667e+08,4.988475e+08,3.039041e+08,3.243254e+08,1
8,70020733,VC,2025-09-01,1.971858e+08,5.410063e+08,1.199201e+08,1.176529e+09,1
9,70020733,VC,2025-10-01,1.292057e+09,6.049855e+08,6.530957e+07,3.391433e+08,1
10,70020733,VC,2025-11-01,2.071648e+08,7.456874e+08,1.566934e+07,2.417650e+08,1
11,70020733,VC,2025-12-01,1.607648e+08,7.821859e+08,2.764713e+09,5.990458e+09,1
12,70034174,VC,2025-01-01,1.213789e+08,3.603004e+09,2.454276e+07,3.414838e+09,1
13,70034174,VC,2025-02-01,1.213789e+08,4.015092e+08,4.674840e+07,2.318170e+08,1
14,70034174,VC,2025-03-01,1.416088e+08,4.371081e+08,6.440906e+07,3.250664e+08,1
15,70034174,VC,2025-04-01,1.416088e+08,4.114996e+08,7.236450e+07,6.926579e+08,1
16,70034174,VC,2025-05-01,1.618386e+08,4.588223e+08,8.410756e+07,3.876283e+08,1
17,70034174,VC,2025-06-01,1.618386e+08,4.840730e+08,4.493425e+07,2.029854e+08,1
18,70034174,VC,2025-07-01,3.641368e+08,4.605407e+08,1.203300e+08,3.115334e+08,1
19,70034174,VC,2025-08-01,1.102847e+09,4.988475e+08,1.280526e+09,3.243254e+08,1
20,70034174,VC,2025-09-01,3.596640e+08,5.410063e+08,2.766229e+08,1.176529e+09,1
21,70034174,VC,2025-10-01,1.468791e+09,6.049855e+08,2.446175e+08,3.391433e+08,1
22,70034174,VC,2025-11-01,3.751859e+08,7.456874e+08,2.122314e+09,2.417650e+08,1
23,70034174,VC,2025-12-01,1.858344e+08,7.821859e+08,1.390872e+09,5.990458e+09,1

In [298]:
# Calcular

main = renal_ambulatorio.rename(columns={'PlanVentaTotal': 'Presupuesto', 'RealVentaTotal': 'Real'})

main['Contexto'] = main['CodigoEmpleado'].str.cat(main['Consecutivo'],sep="_")

main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaPortafolioRenalSub'


#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real','Presupuesto', 'PorcentajeCumplimiento']]


venta_facturada_portafolio_renal_sub = main.copy()
main = None
venta_facturada_portafolio_renal_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\718524215.py:7: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,70020733_1,VentaFacturadaPortafolioRenalSub,2025-01-01,0.000000e+00,0.000000e+00,NaN
1,70020733_1,VentaFacturadaPortafolioRenalSub,2025-02-01,0.000000e+00,0.000000e+00,NaN
2,70020733_1,VentaFacturadaPortafolioRenalSub,2025-03-01,4.898174e+07,1.010107e+08,0.48
3,70020733_1,VentaFacturadaPortafolioRenalSub,2025-04-01,1.657908e+08,2.020214e+08,0.82
4,70020733_1,VentaFacturadaPortafolioRenalSub,2025-05-01,1.947955e+08,2.164515e+08,0.90
5,70020733_1,VentaFacturadaPortafolioRenalSub,2025-06-01,1.042674e+09,3.318923e+08,3.14
6,70020733_1,VentaFacturadaPortafolioRenalSub,2025-07-01,1.207981e+09,5.916341e+08,2.04
7,70020733_1,VentaFacturadaPortafolioRenalSub,2025-08-01,1.511885e+09,8.617008e+08,1.75
8,70020733_1,VentaFacturadaPortafolioRenalSub,2025-09-01,1.631805e+09,1.058887e+09,1.54
9,70020733_1,VentaFacturadaPortafolioRenalSub,2025-10-01,1.697115e+09,2.350944e+09,0.72
10,70020733_1,VentaFacturadaPortafolioRenalSub,2025-11-01,1.712784e+09,2.558109e+09,0.67
11,70020733_1,VentaFacturadaPortafolioRenalSub,2025-12-01,4.477497e+09,2.718873e+09,1.65
12,70034174_1,VentaFacturadaPortafolioRenalSub,2025-01-01,2.454276e+07,1.213789e+08,0.20
13,70034174_1,VentaFacturadaPortafolioRenalSub,2025-02-01,7.129116e+07,2.427579e+08,0.29
14,70034174_1,VentaFacturadaPortafolioRenalSub,2025-03-01,1.357002e+08,3.843667e+08,0.35
15,70034174_1,VentaFacturadaPortafolioRenalSub,2025-04-01,2.080647e+08,5.259754e+08,0.40
16,70034174_1,VentaFacturadaPortafolioRenalSub,2025-05-01,2.921723e+08,6.878140e+08,0.42
17,70034174_1,VentaFacturadaPortafolioRenalSub,2025-06-01,3.371065e+08,8.496526e+08,0.40
18,70034174_1,VentaFacturadaPortafolioRenalSub,2025-07-01,4.574365e+08,1.213789e+09,0.38
19,70034174_1,VentaFacturadaPortafolioRenalSub,2025-08-01,1.737962e+09,2.316636e+09,0.75
20,70034174_1,VentaFacturadaPortafolioRenalSub,2025-09-01,2.014585e+09,2.676300e+09,0.75
21,70034174_1,VentaFacturadaPortafolioRenalSub,2025-10-01,2.259203e+09,4.145091e+09,0.55
22,70034174_1,VentaFacturadaPortafolioRenalSub,2025-11-01,4.381517e+09,4.520276e+09,0.97
23,70034174_1,VentaFacturadaPortafolioRenalSub,2025-12-01,5.772389e+09,4.706111e+09,1.23

## 37. VentaFacturadaPortafolioZonaCluster

In [299]:
venta_recaudo_presupuesto_original_ve_real_zona_cluster.head()

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,CodigoCentroCosto,ZonaGeografica,Cluster,Canal,Fecha,Venta,Recaudo
0,1,1,AE,005,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
1,1,1,AE,M07,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
2,1,2,AE,M08,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
3,2,1,AE,003,,VE,323007260,NaN,NaN,NaN,NaT,NaN,NaN
4,2,1,AE,CEK,30,VE,323010140,Suroccidente,12,Distribuidor,2025-02-01,323000.0,0.0

In [300]:
venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster.head()

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,CodigoCentroCosto,ZonaGeografica,Cluster,Canal,Fecha,Venta,Recaudo
0,1,1,AE,005,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
1,1,1,AE,M07,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
2,1,2,AE,M08,,VE,323010140,NaN,NaN,NaN,NaT,NaN,NaN
3,2,1,AE,003,,VE,323007260,NaN,NaN,NaN,NaT,NaN,NaN
4,2,1,AE,CEK,30,VE,323010140,Suroccidente,12,Distribuidor,2025-02-01,0.0,0.0

In [301]:
# VentaRecaudoReal (venta)
# VentaRecaudoPresupuesto (venta)

# Preparar
# drop_cols = ['Recaudo', 'Division','CodigoEmpleado','GrupoProducto', 'Canal', 'SBA']
real = venta_recaudo_presupuesto_original_ve_real_zona_cluster.copy()
ppto = venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster.copy()

# Sumamos los registros que tienen el mismo conexto para que exista un solo registro
ppto = ppto.groupby(['AreaCalculo','Fecha', 'ZonaGeografica', 'Cluster'], as_index=True)[['Venta']].apply(sum)
real = real.groupby(['AreaCalculo', 'Fecha', 'ZonaGeografica', 'Cluster'], as_index=True)[['Venta']].apply(sum)
ppto.reset_index(inplace=True)
real.reset_index(inplace=True)

main = ppto.rename(columns={'Venta': 'Presupuesto'}).merge(
    real.rename(columns={'Venta': 'Real'}),
    on=['Fecha', 'ZonaGeografica', 'Cluster','AreaCalculo'],
    how='left'
)
main = main.merge(
    df_zonas_clusters_empleado.rename(columns={'Zona': 'ZonaGeografica'}),
    on=['ZonaGeografica', 'Cluster','AreaCalculo'],
    how='left'
)

# Traer áreas de cálculo y tipo de empleado de la maestra de empleados
empleados = df_empleados[['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo', 'FechaIngreso']].copy()
main = main.merge(empleados, on=['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo'], how='left')

main = main[main['Fecha'] >= main['FechaIngreso']]
main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3302712680.py:10: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ppto = ppto.groupby(['AreaCalculo','Fecha', 'ZonaGeografica', 'Cluster'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3302712680.py:11: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  real = real.groupby(['AreaCalculo', 'Fecha', 'ZonaGeografica', 'Cluster'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,AreaCalculo,Fecha,ZonaGeografica,Cluster,Presupuesto,Real,TipoEmpleado,CodigoEmpleado,FechaIngreso
208,2,2025-01-01,Centro,0,2.565151e+07,2.561190e+07,VE,70021443,2024-01-01
210,2,2025-01-01,Centro,1,1.336953e+08,1.375694e+08,VE,70021443,2024-01-01
212,2,2025-01-01,Centro,2,3.070989e+07,1.903023e+06,VE,70021443,2024-01-01
214,2,2025-01-01,Centro,21,7.459215e+06,8.305128e+06,VE,70021443,2024-01-01
216,2,2025-01-01,Centro,3,6.044649e+07,2.538176e+07,VE,70021443,2024-01-01
...,...,...,...,...,...,...,...,...,...
4011,12,2025-12-01,Suroccidente,11,2.249970e+07,6.956061e+06,VE,5039578,2024-11-01
4012,12,2025-12-01,Suroccidente,12,1.855335e+07,3.178359e+07,VE,5039578,2024-11-01
4013,12,2025-12-01,Suroccidente,21,0.000000e+00,2.403800e+06,VE,5039578,2024-11-01
4014,12,2025-12-01,Suroccidente,8,1.135238e+08,4.411477e+08,VE,5039578,2024-11-01
4015,12,2025-12-01,Suroccidente,9,2.999254e+07,3.037723e+07,VE,5039578,2024-11-01

In [302]:
main['Real'].fillna(0, inplace=True)

# Calcular

main['Contexto'] = main['CodigoEmpleado']
# + '_' +  main['ZonaGeografica'].astype('str')
main
# main['Contexto']= 'VFPZ'

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1756086119.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)

,AreaCalculo,Fecha,ZonaGeografica,Cluster,Presupuesto,Real,TipoEmpleado,CodigoEmpleado,FechaIngreso,Contexto
208,2,2025-01-01,Centro,0,2.565151e+07,2.561190e+07,VE,70021443,2024-01-01,70021443
210,2,2025-01-01,Centro,1,1.336953e+08,1.375694e+08,VE,70021443,2024-01-01,70021443
212,2,2025-01-01,Centro,2,3.070989e+07,1.903023e+06,VE,70021443,2024-01-01,70021443
214,2,2025-01-01,Centro,21,7.459215e+06,8.305128e+06,VE,70021443,2024-01-01,70021443
216,2,2025-01-01,Centro,3,6.044649e+07,2.538176e+07,VE,70021443,2024-01-01,70021443
...,...,...,...,...,...,...,...,...,...,...
4011,12,2025-12-01,Suroccidente,11,2.249970e+07,6.956061e+06,VE,5039578,2024-11-01,5039578
4012,12,2025-12-01,Suroccidente,12,1.855335e+07,3.178359e+07,VE,5039578,2024-11-01,5039578
4013,12,2025-12-01,Suroccidente,21,0.000000e+00,2.403800e+06,VE,5039578,2024-11-01,5039578
4014,12,2025-12-01,Suroccidente,8,1.135238e+08,4.411477e+08,VE,5039578,2024-11-01,5039578
4015,12,2025-12-01,Suroccidente,9,2.999254e+07,3.037723e+07,VE,5039578,2024-11-01,5039578

In [303]:
# Calcular

# main['Contexto'] = main['CodigoEmpleado'] + '_' +  main['ZonaGeografica'].astype(int).astype('str')
# main['Contexto']= 'VFPZ'
main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaPortafolioZonaCluster'


#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real','Presupuesto', 'PorcentajeCumplimiento']]


venta_facturada_portafolio_zona_cluster = main.copy()
main = None
venta_facturada_portafolio_zona_cluster

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\735453504.py:5: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,37270929,VentaFacturadaPortafolioZonaCluster,2025-09-01,3.483698e+08,3.405651e+08,1.02
1,37270929,VentaFacturadaPortafolioZonaCluster,2025-10-01,6.223198e+08,6.283422e+08,0.99
2,37270929,VentaFacturadaPortafolioZonaCluster,2025-11-01,9.667845e+08,9.967679e+08,0.97
3,37270929,VentaFacturadaPortafolioZonaCluster,2025-12-01,1.687361e+09,1.331048e+09,1.27
4,5002697,VentaFacturadaPortafolioZonaCluster,2025-01-01,8.758655e+08,1.165904e+09,0.75
...,...,...,...,...,...,...
298,70042060,VentaFacturadaPortafolioZonaCluster,2025-08-01,3.343003e+09,3.100466e+09,1.08
299,70042060,VentaFacturadaPortafolioZonaCluster,2025-09-01,4.740891e+09,4.584391e+09,1.03
300,70042060,VentaFacturadaPortafolioZonaCluster,2025-10-01,6.246565e+09,6.174722e+09,1.01
301,70042060,VentaFacturadaPortafolioZonaCluster,2025-11-01,8.273485e+09,8.034668e+09,1.03
302,70042060,VentaFacturadaPortafolioZonaCluster,2025-12-01,1.096934e+10,1.004647e+10,1.09

In [304]:
venta_facturada_portafolio_zona_cluster[venta_facturada_portafolio_zona_cluster['Contexto'].str.contains('1060654227') ]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [305]:
venta_facturada_portafolio_zona_cluster[venta_facturada_portafolio_zona_cluster['Contexto'].str.contains('5041369') ]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 37.1 VentaFacturadaPortafolioZonaClusterSub

In [306]:
# VentaRecaudoReal (venta)
# VentaRecaudoPresupuesto (venta)

# Preparar
# drop_cols = ['Recaudo', 'Division','CodigoEmpleado','GrupoProducto', 'Canal', 'SBA']

ppto = venta_recaudo_presupuesto_original_ve_presupuesto_zona_cluster.copy()
real = venta_recaudo_presupuesto_original_ve_real_zona_cluster.copy()

# Sumamos los registros que tienen el mismo conexto para que exista un solo registro
ppto = ppto.groupby(['AreaCalculo','Fecha', 'ZonaGeografica', 'Cluster', 'Consecutivo', 'GrupoProducto', 'Division'], as_index=True)[['Venta']].apply(sum)
real = real.groupby(['AreaCalculo', 'Fecha', 'ZonaGeografica', 'Cluster', 'Consecutivo', 'GrupoProducto', 'Division'], as_index=True)[['Venta']].apply(sum)
ppto.reset_index(inplace=True)
real.reset_index(inplace=True)

main = ppto.rename(columns={'Venta': 'Presupuesto'}).merge(
    real.rename(columns={'Venta': 'Real'}),
    on=['Fecha', 'ZonaGeografica', 'Cluster','AreaCalculo', 'Consecutivo', 'GrupoProducto', 'Division'],
    how='outer'
)

main = main.merge(
    df_zonas_clusters_empleado.rename(columns={'Zona': 'ZonaGeografica'}),
    on=['ZonaGeografica', 'Cluster','AreaCalculo'],
    how='left'
)

# Traer áreas de cálculo y tipo de empleado de la maestra de empleados
empleados = df_empleados[['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo', 'FechaIngreso']].copy()
main = main.merge(empleados, on=['TipoEmpleado', 'CodigoEmpleado', 'AreaCalculo'], how='left')

# main = main[main['Fecha'] >= main['FechaIngreso']]
main['Real'].fillna(0, inplace=True)
main['Contexto']= main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')
main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\378623446.py:11: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ppto = ppto.groupby(['AreaCalculo','Fecha', 'ZonaGeografica', 'Cluster', 'Consecutivo', 'GrupoProducto', 'Division'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\378623446.py:12: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  real = real.groupby(['AreaCalculo', 'Fecha', 'ZonaGeografica', 'Cluster', 'Consecutivo', 'GrupoProducto', 'Division'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\378623446.py:33: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)

,AreaCalculo,Fecha,ZonaGeografica,Cluster,Consecutivo,GrupoProducto,Division,Presupuesto,Real,TipoEmpleado,CodigoEmpleado,FechaIngreso,Contexto
0,2,2025-01-01,Centro,0,1,003,AE,2.438295e+07,25611896.0,VE,5003527,NaT,5003527_1
1,2,2025-01-01,Centro,0,1,003,AE,2.438295e+07,25611896.0,VE,70021443,2024-01-01,70021443_1
2,2,2025-01-01,Centro,0,1,CEK,AE,1.430000e+05,0.0,VE,5003527,NaT,5003527_1
3,2,2025-01-01,Centro,0,1,CEK,AE,1.430000e+05,0.0,VE,70021443,2024-01-01,70021443_1
4,2,2025-01-01,Centro,0,2,801,AE,8.043821e+05,0.0,VE,5003527,NaT,5003527_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9594,7,2025-12-01,Venezuela,0,2,680,HC,5.552074e+07,0.0,NaN,NaN,NaT,NaN
9595,7,2025-12-01,Venezuela,0,3,610,HC,1.500749e+07,116060000.0,NaN,NaN,NaT,NaN
9596,8,2025-12-01,Venezuela,0,1,A34,BA,1.567423e+06,0.0,NaN,NaN,NaT,NaN
9597,10,2025-12-01,Venezuela,0,1,A32,BA,2.848796e+06,0.0,NaN,NaN,NaT,NaN
9598,13,2025-12-01,Venezuela,0,1,003,AE,2.185384e+07,0.0,NaN,NaN,NaT,NaN

### TODO ( Remplazar lógica provisional para VE9)

In [307]:
main = main[(main['AreaCalculo'] != 9) & ((main['TipoEmpleado'] == 'VE') |(main['TipoEmpleado'] != 'VE'))]
main

,AreaCalculo,Fecha,ZonaGeografica,Cluster,Consecutivo,GrupoProducto,Division,Presupuesto,Real,TipoEmpleado,CodigoEmpleado,FechaIngreso,Contexto
0,2,2025-01-01,Centro,0,1,003,AE,2.438295e+07,25611896.0,VE,5003527,NaT,5003527_1
1,2,2025-01-01,Centro,0,1,003,AE,2.438295e+07,25611896.0,VE,70021443,2024-01-01,70021443_1
2,2,2025-01-01,Centro,0,1,CEK,AE,1.430000e+05,0.0,VE,5003527,NaT,5003527_1
3,2,2025-01-01,Centro,0,1,CEK,AE,1.430000e+05,0.0,VE,70021443,2024-01-01,70021443_1
4,2,2025-01-01,Centro,0,2,801,AE,8.043821e+05,0.0,VE,5003527,NaT,5003527_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9594,7,2025-12-01,Venezuela,0,2,680,HC,5.552074e+07,0.0,NaN,NaN,NaT,NaN
9595,7,2025-12-01,Venezuela,0,3,610,HC,1.500749e+07,116060000.0,NaN,NaN,NaT,NaN
9596,8,2025-12-01,Venezuela,0,1,A34,BA,1.567423e+06,0.0,NaN,NaN,NaT,NaN
9597,10,2025-12-01,Venezuela,0,1,A32,BA,2.848796e+06,0.0,NaN,NaN,NaT,NaN
9598,13,2025-12-01,Venezuela,0,1,003,AE,2.185384e+07,0.0,NaN,NaN,NaT,NaN

In [308]:
_main =main[
    (main['TipoEmpleado'] == 'VE') & (main['AreaCalculo'] == 9)
]
_main

Empty DataFrame
Columns: [AreaCalculo, Fecha, ZonaGeografica, Cluster, Consecutivo, GrupoProducto, Division, Presupuesto, Real, TipoEmpleado, CodigoEmpleado, FechaIngreso, Contexto]
Index: []

In [309]:
main_centro_costo = pd.merge(
    df_empleados_centros_costos,
    main,
    on=['CodigoEmpleado'],
    how='right'
)
main_centro_costo

,CodigoEmpleado,CodigoCentroCosto,PorcentajeAsignacion,AreaCalculo,Fecha,ZonaGeografica,Cluster,Consecutivo,GrupoProducto,Division,Presupuesto,Real,TipoEmpleado,FechaIngreso,Contexto
0,5003527,323007260,0.50,2,2025-01-01,Centro,0,1,003,AE,2.438295e+07,25611896.0,VE,NaT,5003527_1
1,5003527,323007300,0.05,2,2025-01-01,Centro,0,1,003,AE,2.438295e+07,25611896.0,VE,NaT,5003527_1
2,5003527,323007350,0.45,2,2025-01-01,Centro,0,1,003,AE,2.438295e+07,25611896.0,VE,NaT,5003527_1
3,70021443,323007260,0.50,2,2025-01-01,Centro,0,1,003,AE,2.438295e+07,25611896.0,VE,2024-01-01,70021443_1
4,70021443,323007300,0.05,2,2025-01-01,Centro,0,1,003,AE,2.438295e+07,25611896.0,VE,2024-01-01,70021443_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15111,NaN,NaN,NaN,7,2025-12-01,Venezuela,0,2,680,HC,5.552074e+07,0.0,NaN,NaT,NaN
15112,NaN,NaN,NaN,7,2025-12-01,Venezuela,0,3,610,HC,1.500749e+07,116060000.0,NaN,NaT,NaN
15113,NaN,NaN,NaN,8,2025-12-01,Venezuela,0,1,A34,BA,1.567423e+06,0.0,NaN,NaT,NaN
15114,NaN,NaN,NaN,10,2025-12-01,Venezuela,0,1,A32,BA,2.848796e+06,0.0,NaN,NaT,NaN
15115,NaN,NaN,NaN,13,2025-12-01,Venezuela,0,1,003,AE,2.185384e+07,0.0,NaN,NaT,NaN

In [310]:
venta_facturada_portafolio_zona_cluster_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main_centro_costo, 'VentaFacturadaPortafolioZonaClusterSub')
venta_facturada_portafolio_zona_cluster_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,37270929_2,2025-01-01,680,HC,323007260,1.068878e+08,6.913865e+07,VentaFacturadaPortafolioZonaClusterSub
1,37270929_2,2025-01-01,680,HC,323007300,1.068878e+08,6.913865e+07,VentaFacturadaPortafolioZonaClusterSub
2,37270929_2,2025-01-01,680,HC,323007350,1.068878e+08,6.913865e+07,VentaFacturadaPortafolioZonaClusterSub
3,37270929_2,2025-02-01,680,HC,323007260,2.970155e+08,1.539906e+08,VentaFacturadaPortafolioZonaClusterSub
4,37270929_2,2025-02-01,680,HC,323007300,2.970155e+08,1.539906e+08,VentaFacturadaPortafolioZonaClusterSub
...,...,...,...,...,...,...,...,...
1951,70042060_5,2025-08-01,610,HC,323015045,3.852451e+09,2.880013e+09,VentaFacturadaPortafolioZonaClusterSub
1952,70042060_5,2025-09-01,610,HC,323015045,4.225075e+09,3.210932e+09,VentaFacturadaPortafolioZonaClusterSub
1953,70042060_5,2025-10-01,610,HC,323015045,4.774622e+09,3.564909e+09,VentaFacturadaPortafolioZonaClusterSub
1954,70042060_5,2025-11-01,610,HC,323015045,5.646501e+09,4.035692e+09,VentaFacturadaPortafolioZonaClusterSub
1955,70042060_5,2025-12-01,610,HC,323015045,6.535348e+09,4.366612e+09,VentaFacturadaPortafolioZonaClusterSub

In [311]:
main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaPortafolioZonaClusterSub'


#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real','Presupuesto', 'PorcentajeCumplimiento']]


venta_facturada_portafolio_zona_cluster_sub = main.copy()
main = None
venta_facturada_portafolio_zona_cluster_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1155003239.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,37270929_2,VentaFacturadaPortafolioZonaClusterSub,2025-01-01,1.068878e+08,6.913865e+07,1.55
1,37270929_2,VentaFacturadaPortafolioZonaClusterSub,2025-02-01,2.970155e+08,1.539906e+08,1.93
2,37270929_2,VentaFacturadaPortafolioZonaClusterSub,2025-03-01,3.997710e+08,2.938392e+08,1.36
3,37270929_2,VentaFacturadaPortafolioZonaClusterSub,2025-04-01,6.233319e+08,4.164032e+08,1.50
4,37270929_2,VentaFacturadaPortafolioZonaClusterSub,2025-05-01,7.638768e+08,5.326818e+08,1.43
...,...,...,...,...,...,...
1165,70042060_5,VentaFacturadaPortafolioZonaClusterSub,2025-08-01,3.852451e+09,2.880013e+09,1.34
1166,70042060_5,VentaFacturadaPortafolioZonaClusterSub,2025-09-01,4.225075e+09,3.210932e+09,1.32
1167,70042060_5,VentaFacturadaPortafolioZonaClusterSub,2025-10-01,4.774622e+09,3.564909e+09,1.34
1168,70042060_5,VentaFacturadaPortafolioZonaClusterSub,2025-11-01,5.646501e+09,4.035692e+09,1.40
1169,70042060_5,VentaFacturadaPortafolioZonaClusterSub,2025-12-01,6.535348e+09,4.366612e+09,1.50

In [312]:
venta_facturada_portafolio_zona_cluster_sub[venta_facturada_portafolio_zona_cluster_sub['Contexto'] == '79625102_1']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 37.2 VentaFacturadaPortafolioZonaClusterSub (VE)

In [313]:
df_empleados.columns

Index(['TipoEmpleado', 'CodigoEmpleado', 'Identificacion', 'CorreoElectronico',
       'Nombre', 'Apellidos', 'SalarioVariable', 'FechaIngreso', 'FechaRetiro',
       'AreaCalculo'],
      dtype='object')

In [314]:
venta_recaudo_kams_ve = df_venta_recaudo_kams[df_venta_recaudo_kams['TipoEmpleado'] == 'VE']
venta_recaudo_kams_ve

Empty DataFrame
Columns: [TipoEmpleado, AreaCalculo, Consecutivo, Fecha, VentaReal, VentaPresupuesto, RecaudoReal, RecaudoPresupuesto]
Index: []

In [315]:
# VentaRecaudoReal (venta)
# VentaRecaudoPresupuesto (venta)

# Preparar

main = venta_recaudo_kams_ve.drop(columns=['RecaudoReal', 'RecaudoPresupuesto'])
main.rename(columns={'VentaReal': 'Real', 'VentaPresupuesto':'Presupuesto'}, inplace=True)
main = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].sum()
main = main.merge(
    df_empleados,
    on=['TipoEmpleado', 'AreaCalculo'],
    how='left'
)
main.reset_index(inplace=True)

main['Real'] = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['TipoEmpleado', 'AreaCalculo', 'Consecutivo'])['Presupuesto'].transform(pd.Series.cumsum)
main['Contexto']= main['CodigoEmpleado'] + '_' +  main['Consecutivo'].astype(int).astype('str')
main['Variable'] = 'VentaFacturadaPortafolioZonaClusterSub'
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

venta_facturada_portafolio_zona_cluster_sub_ve = main
main = None
venta_facturada_portafolio_zona_cluster_sub_ve

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 38. VentaFacturadaZonaPais

In [316]:
# VentaRecaudoReal (venta)
# VentaRecaudoPresupuesto (venta)

# Preparar
drop_cols = ['Recaudo', 'Division', 'Cluster','GrupoProducto', 'Canal', 'SBA']
real = df_venta_recaudo_real.copy().drop(columns=drop_cols)
ppto = df_venta_recaudo_presupuesto.copy().drop(columns=drop_cols)

# Sumamos los registros que tienen el mismo conexto para que exista un solo registro
ppto = ppto.groupby(['Fecha', 'ZonaGeografica'], as_index=True)[['Venta']].apply(sum)
ppto.reset_index(inplace=True)
real = real.groupby(['Fecha', 'ZonaGeografica'], as_index=True)[['Venta']].apply(sum)
real.reset_index(inplace=True)

main = ppto.rename(columns={'Venta': 'Presupuesto'}).merge(
    real.rename(columns={'Venta': 'Real'}),
    on=['Fecha', 'ZonaGeografica'],
    how='left'
)    

main = main.merge(
    df_zonas_empleado.rename(columns={'Zona': 'ZonaGeografica'}),
    on=['ZonaGeografica'],
    how='left'
)
main['Real'].fillna(0, inplace=True)

# Calcular
main['Contexto']= main['CodigoEmpleado']

main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaZonaPais'


#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha','Real','Presupuesto','PorcentajeCumplimiento']]

venta_facturada_zona_pais = main.copy()
main = None
venta_facturada_zona_pais

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1527312124.py:10: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ppto = ppto.groupby(['Fecha', 'ZonaGeografica'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1527312124.py:12: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  real = real.groupby(['Fecha', 'ZonaGeografica'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1527312124.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1527312124.py:31: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002697,VentaFacturadaZonaPais,2025-01-01,4.136082e+09,6.238970e+09,0.66
1,5002697,VentaFacturadaZonaPais,2025-02-01,1.098998e+10,1.443128e+10,0.76
2,5002697,VentaFacturadaZonaPais,2025-03-01,1.863439e+10,2.286825e+10,0.81
3,5002697,VentaFacturadaZonaPais,2025-04-01,2.632239e+10,3.030257e+10,0.87
4,5002697,VentaFacturadaZonaPais,2025-05-01,3.579979e+10,3.944917e+10,0.91
...,...,...,...,...,...,...
679,70055621,VentaFacturadaZonaPais,2025-08-01,4.112837e+10,4.541429e+10,0.91
680,70055621,VentaFacturadaZonaPais,2025-09-01,4.642055e+10,5.151707e+10,0.90
681,70055621,VentaFacturadaZonaPais,2025-10-01,5.214261e+10,5.840725e+10,0.89
682,70055621,VentaFacturadaZonaPais,2025-11-01,5.742474e+10,6.531975e+10,0.88
683,70055621,VentaFacturadaZonaPais,2025-12-01,6.841486e+10,7.276037e+10,0.94

In [317]:
venta_facturada_zona_pais[venta_facturada_zona_pais['Contexto'] == '1111115']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [318]:
venta_facturada_zona_pais[venta_facturada_zona_pais['Contexto'] == '1111124']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

# Nuevos Rubros 2024

## 38.1 VentaFacturadaZonaPaisSub

In [319]:
df_venta_recaudo_real

,CodigoEmpleado,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Venta,Recaudo
0,1111117,BA,0,Norte,A45,Renal AMB,80,2025-12-01,6.526043e+08,6.526043e+08
1,1111117,BA,0,Suroccidente,A45,RENAL AMB,80,2025-08-01,2.173649e+05,2.957838e+05
2,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-11-01,1.478919e+05,0.000000e+00
3,1111117,BA,0,Suroccidente,A45,Renal AMB,80,2025-12-01,0.000000e+00,2.173649e+05
4,1111122,HC,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,2.818770e+07,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
21857,9990014,BA,14,Norte,A34,HOSPITAL,85,2025-08-01,1.022240e+07,2.732760e+05
21858,9990014,BA,14,Norte,A34,Hospital Privado,85,2025-07-01,0.000000e+00,0.000000e+00
21859,9990014,BA,14,Norte,A34,Hospital Privado,85,2025-08-01,0.000000e+00,0.000000e+00
21860,9990014,BA,14,Norte,A34,No Definido,85,2025-07-01,0.000000e+00,0.000000e+00
21861,9990014,BA,14,Norte,A34,No Definido,85,2025-08-01,0.000000e+00,0.000000e+00

In [320]:
area_calculo_sba_completo_gc = area_calculo_sba_completo[area_calculo_sba_completo['TipoEmpleado'] == 'GC']
area_calculo_sba_completo_gc_without_dup = area_calculo_sba_completo_gc[['TipoEmpleado','Consecutivo', 'Division']].drop_duplicates()
area_calculo_sba_completo_gc_without_dup.head()

   TipoEmpleado  Consecutivo Division
20           GC            1       HC
21           GC            2       AE
22           GC            3       BA

In [321]:
drop_cols = ['Recaudo'] #'GrupoProducto', 'SBA'
facturado_real_zona_gc = pd.merge(
    left=area_calculo_sba_completo_gc_without_dup,
    right=df_venta_recaudo_real,
    on=['Division'],
    how='left'
)
facturado_real_zona_gc = facturado_real_zona_gc.dropna(subset=['ZonaGeografica']).drop(columns=drop_cols)
facturado_real_zona_gc.rename(columns={'Venta': 'Real'}, inplace=True)
facturado_real_zona_gc

,TipoEmpleado,Consecutivo,Division,CodigoEmpleado,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Real
0,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,28187700.00
1,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-09-01,4145250.00
2,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-10-01,19897200.00
3,GC,1,HC,1111122,0,Suroccidente,620,Distribuidor,36,2025-11-01,26529600.00
4,GC,1,HC,1111122,0,Suroccidente,620,Distribuidor,36,2025-12-01,3316200.00
...,...,...,...,...,...,...,...,...,...,...,...
21857,GC,3,BA,9990014,14,Norte,A34,HOSPITAL,85,2025-08-01,10222402.28
21858,GC,3,BA,9990014,14,Norte,A34,Hospital Privado,85,2025-07-01,0.00
21859,GC,3,BA,9990014,14,Norte,A34,Hospital Privado,85,2025-08-01,0.00
21860,GC,3,BA,9990014,14,Norte,A34,No Definido,85,2025-07-01,0.00
21861,GC,3,BA,9990014,14,Norte,A34,No Definido,85,2025-08-01,0.00

In [322]:
facturado_real_zona_gc[
    (facturado_real_zona_gc['ZonaGeografica'] == 'Centro') &
    (facturado_real_zona_gc['Fecha'] == '2023-12-01') &
    (facturado_real_zona_gc['Consecutivo'] == 1)
]['Real'].sum()

0.0

In [323]:
facturado_presupuesto_zona_gc = pd.merge(
    left=area_calculo_sba_completo_gc_without_dup,
    right=df_venta_recaudo_presupuesto,
    on=['Division'],
    how='left'
)

facturado_presupuesto_zona_gc = facturado_presupuesto_zona_gc.drop(columns=drop_cols).dropna(subset=['ZonaGeografica'])
facturado_presupuesto_zona_gc.rename(columns={'Venta': 'Presupuesto'}, inplace=True)
facturado_presupuesto_zona_gc

,TipoEmpleado,Consecutivo,Division,CodigoEmpleado,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Presupuesto
0,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-08-01,0.000000e+00
1,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-09-01,0.000000e+00
2,GC,1,HC,1111122,0,Suroccidente,620,DISTRIBUIDOR,36,2025-10-01,0.000000e+00
3,GC,1,HC,1111122,0,Suroccidente,620,Distribuidor,36,2025-11-01,0.000000e+00
4,GC,1,HC,1111122,0,Suroccidente,620,Distribuidor,36,2025-12-01,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
22568,GC,3,BA,9990014,14,Norte,A34,HOSPITAL,85,2025-08-01,0.000000e+00
22569,GC,3,BA,9990014,14,Norte,A34,Hospital Privado,85,2025-07-01,5.474118e+06
22570,GC,3,BA,9990014,14,Norte,A34,Hospital Privado,85,2025-08-01,1.094824e+07
22571,GC,3,BA,9990014,14,Norte,A34,No Definido,85,2025-07-01,0.000000e+00
22572,GC,3,BA,9990014,14,Norte,A34,No Definido,85,2025-08-01,0.000000e+00

In [324]:
facturado_presupuesto_zona_gc[
    (facturado_presupuesto_zona_gc['ZonaGeografica'] == 'Centro') &
    (facturado_presupuesto_zona_gc['Fecha'] == '2023 -12-01') &
    (facturado_presupuesto_zona_gc['Consecutivo'] == 1)
]['Presupuesto'].sum()

0.0

In [325]:
main = pd.merge(
    left=facturado_presupuesto_zona_gc,
    right=facturado_real_zona_gc,
    on=['ZonaGeografica', 'Fecha', 'Consecutivo', 'Division', 'CodigoEmpleado', 'TipoEmpleado', 'Cluster', 'GrupoProducto', 'SBA', 'Canal'],
    how='outer'
)
main = main.dropna(subset=['ZonaGeografica']).drop(columns=['CodigoEmpleado'])
main

,TipoEmpleado,Consecutivo,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Presupuesto,Real
0,GC,1,HC,6,Centro,610,Distribuidor,01,2025-01-01,9.281736e+06,10871226.58
1,GC,1,HC,6,Centro,610,HOSPITAL,01,2025-01-01,0.000000e+00,9300596.00
2,GC,1,HC,6,Centro,610,Hospital Privado,01,2025-01-01,4.838948e+06,0.00
3,GC,1,HC,6,Centro,610,Hospital Público,01,2025-01-01,2.100362e+06,0.00
4,GC,1,HC,6,Centro,610,Distribuidor,02,2025-01-01,3.026904e+06,125024.40
...,...,...,...,...,...,...,...,...,...,...,...
22574,GC,2,AE,0,Venezuela,006,Distribuidor,36,2025-12-01,0.000000e+00,-677031.04
22575,GC,2,AE,0,Venezuela,003,Distribuidor,35,2025-12-01,2.185384e+07,0.00
22576,GC,2,AE,0,Venezuela,006,Distribuidor,36,2025-12-01,1.956096e+07,0.00
22577,GC,3,BA,0,Venezuela,A32,Distribuidor,84,2025-12-01,2.848796e+06,0.00
22578,GC,3,BA,0,Venezuela,A34,Distribuidor,85,2025-12-01,1.567423e+06,0.00

In [326]:
df_zonas_empleado_gc = df_zonas_empleado[
    (df_zonas_empleado['TipoEmpleado']== 'GC')
]
df_zonas_empleado_gc

            Zona CodigoEmpleado TipoEmpleado  AreaCalculo
5          Norte        5002711           GC            3
34        Centro        5004298           GC            1
59  Suroccidente        5005980           GC            2

In [327]:
df_parrillas[df_parrillas['Variable'] == 'VentaFacturadaZonaPaisSub']

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
103,5002711,VentaFacturadaZonaPaisSub,5002711_1,0.26,1,VentaFacturadaZonaPaisSub,Hospital Care
104,5002711,VentaFacturadaZonaPaisSub,5002711_2,0.10,2,VentaFacturadaZonaPaisSub,Aesculap
105,5002711,VentaFacturadaZonaPaisSub,5002711_3,0.04,3,VentaFacturadaZonaPaisSub,Avitum
889,5004298,VentaFacturadaZonaPaisSub,5004298_1,0.26,1,VentaFacturadaZonaPaisSub,Hospital Care
890,5004298,VentaFacturadaZonaPaisSub,5004298_2,0.10,2,VentaFacturadaZonaPaisSub,Aesculap
891,5004298,VentaFacturadaZonaPaisSub,5004298_3,0.04,3,VentaFacturadaZonaPaisSub,Avitum
1482,5005980,VentaFacturadaZonaPaisSub,5005980_1,0.26,1,VentaFacturadaZonaPaisSub,Hospital Care
1483,5005980,VentaFacturadaZonaPaisSub,5005980_2,0.10,2,VentaFacturadaZonaPaisSub,Aesculap
1484,5005980,VentaFacturadaZonaPaisSub,5005980_3,0.04,3,VentaFacturadaZonaPaisSub,Avitum

In [328]:
main = main.merge(
    df_zonas_empleado_gc.rename(columns={'Zona': 'ZonaGeografica'}),
    on=['ZonaGeografica', 'TipoEmpleado'],
    how='left'
)
main['Real'].fillna(0.0, inplace=True)
main.dropna(subset=['CodigoEmpleado'])

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1486749291.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0.0, inplace=True)

,TipoEmpleado,Consecutivo,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Presupuesto,Real,CodigoEmpleado,AreaCalculo
0,GC,1,HC,6,Centro,610,Distribuidor,01,2025-01-01,9.281736e+06,10871226.58,5004298,1.0
1,GC,1,HC,6,Centro,610,HOSPITAL,01,2025-01-01,0.000000e+00,9300596.00,5004298,1.0
2,GC,1,HC,6,Centro,610,Hospital Privado,01,2025-01-01,4.838948e+06,0.00,5004298,1.0
3,GC,1,HC,6,Centro,610,Hospital Público,01,2025-01-01,2.100362e+06,0.00,5004298,1.0
4,GC,1,HC,6,Centro,610,Distribuidor,02,2025-01-01,3.026904e+06,125024.40,5004298,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22476,GC,3,BA,11,Suroccidente,A34,HOSPITAL,85,2025-12-01,0.000000e+00,1462400.00,5005980,2.0
22477,GC,3,BA,11,Suroccidente,A34,No Definido,85,2025-12-01,6.051765e+06,0.00,5005980,2.0
22478,GC,3,BA,9,Suroccidente,660,No Definido,81,2025-12-01,7.426914e+05,0.00,5005980,2.0
22479,GC,3,BA,9,Suroccidente,A45,No Definido,80,2025-12-01,3.215373e+06,0.00,5005980,2.0
22480,GC,3,BA,9,Suroccidente,A45,No Definido,81,2025-12-01,3.673811e+06,0.00,5005980,2.0

In [329]:
main[
    (main['ZonaGeografica'] == 'Centro') &
    (main['Fecha'] == '2023-12-01') &
    (main['Consecutivo'] == 1)
]['Real'].sum()

0.0

In [330]:
main[
    (main['ZonaGeografica'] == 'Centro') &
    (main['Fecha'] == '2023-12-01') &
    (main['Consecutivo'] == 1)
]['Presupuesto'].sum()

0.0

In [331]:
# venta_cobrada_zona_pais_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main=main, variable='VentaFacturadaZonaPaisSub').copy()
# venta_cobrada_zona_pais_sub_centro_costo

In [332]:
venta_facturada_zona_pais_sub = main.copy()
venta_facturada_zona_pais_sub['Consecutivo'] = venta_facturada_zona_pais_sub['Consecutivo'].astype(int).astype('str')
venta_facturada_zona_pais_sub['Contexto'] = venta_facturada_zona_pais_sub['CodigoEmpleado'].str.cat(venta_facturada_zona_pais_sub['Consecutivo'],sep="_")
venta_facturada_zona_pais_sub

,TipoEmpleado,Consecutivo,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Presupuesto,Real,CodigoEmpleado,AreaCalculo,Contexto
0,GC,1,HC,6,Centro,610,Distribuidor,01,2025-01-01,9.281736e+06,10871226.58,5004298,1.0,5004298_1
1,GC,1,HC,6,Centro,610,HOSPITAL,01,2025-01-01,0.000000e+00,9300596.00,5004298,1.0,5004298_1
2,GC,1,HC,6,Centro,610,Hospital Privado,01,2025-01-01,4.838948e+06,0.00,5004298,1.0,5004298_1
3,GC,1,HC,6,Centro,610,Hospital Público,01,2025-01-01,2.100362e+06,0.00,5004298,1.0,5004298_1
4,GC,1,HC,6,Centro,610,Distribuidor,02,2025-01-01,3.026904e+06,125024.40,5004298,1.0,5004298_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22574,GC,2,AE,0,Venezuela,006,Distribuidor,36,2025-12-01,0.000000e+00,-677031.04,NaN,NaN,NaN
22575,GC,2,AE,0,Venezuela,003,Distribuidor,35,2025-12-01,2.185384e+07,0.00,NaN,NaN,NaN
22576,GC,2,AE,0,Venezuela,006,Distribuidor,36,2025-12-01,1.956096e+07,0.00,NaN,NaN,NaN
22577,GC,3,BA,0,Venezuela,A32,Distribuidor,84,2025-12-01,2.848796e+06,0.00,NaN,NaN,NaN
22578,GC,3,BA,0,Venezuela,A34,Distribuidor,85,2025-12-01,1.567423e+06,0.00,NaN,NaN,NaN

In [333]:
venta_facturada_zona_pais_sub[venta_facturada_zona_pais_sub['Fecha'] == '2025-03-01	']

,TipoEmpleado,Consecutivo,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Presupuesto,Real,CodigoEmpleado,AreaCalculo,Contexto
1759,GC,1,HC,0,Centro,680,Televentas Distribuidor,03,2025-03-01,0.000000e+00,0.0,5004298,1.0,5004298_1
1760,GC,1,HC,6,Centro,610,Distribuidor,01,2025-03-01,-1.120210e+07,-4758971.2,5004298,1.0,5004298_1
1761,GC,1,HC,6,Centro,610,HOSPITAL,01,2025-03-01,0.000000e+00,0.0,5004298,1.0,5004298_1
1762,GC,1,HC,6,Centro,610,Hospital Privado,01,2025-03-01,-5.840110e+06,0.0,5004298,1.0,5004298_1
1763,GC,1,HC,6,Centro,610,Hospital Público,01,2025-03-01,-2.534919e+06,0.0,5004298,1.0,5004298_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22500,GC,1,HC,0,Venezuela,680,Distribuidor,03,2025-03-01,4.070255e+07,0.0,NaN,NaN,NaN
22501,GC,2,AE,0,Venezuela,003,Distribuidor,35,2025-03-01,2.334387e+07,0.0,NaN,NaN,NaN
22502,GC,2,AE,0,Venezuela,006,Distribuidor,36,2025-03-01,2.078352e+07,0.0,NaN,NaN,NaN
22503,GC,3,BA,0,Venezuela,A32,Distribuidor,84,2025-03-01,1.994157e+06,0.0,NaN,NaN,NaN
22504,GC,3,BA,0,Venezuela,A34,Distribuidor,85,2025-03-01,1.959278e+06,0.0,NaN,NaN,NaN

In [334]:
venta_facturada_zona_pais_sub[venta_facturada_zona_pais_sub['Contexto'] == '5002711_2']['Real'].sum()

12685784953.7

In [335]:
venta_facturada_zona_pais_sub[venta_facturada_zona_pais_sub['Contexto'] == '5002711_3']['Real'].sum()

5915612137.949999

In [336]:
venta_facturada_zona_pais_sub[venta_facturada_zona_pais_sub['ZonaGeografica'] == 'Norte']['Presupuesto'].sum()

72760373382.48558

In [337]:
main_centro_costo = pd.merge(
    df_empleados_centros_costos,
    venta_facturada_zona_pais_sub.copy(),
    on=['CodigoEmpleado'],
    how='right'
)
main_centro_costo

,CodigoEmpleado,CodigoCentroCosto,PorcentajeAsignacion,TipoEmpleado,Consecutivo,Division,Cluster,ZonaGeografica,GrupoProducto,Canal,SBA,Fecha,Presupuesto,Real,AreaCalculo,Contexto
0,5004298,323007335,0.05,GC,1,HC,6,Centro,610,Distribuidor,01,2025-01-01,9.281736e+06,10871226.58,1.0,5004298_1
1,5004298,323010165,0.25,GC,1,HC,6,Centro,610,Distribuidor,01,2025-01-01,9.281736e+06,10871226.58,1.0,5004298_1
2,5004298,323015065,0.70,GC,1,HC,6,Centro,610,Distribuidor,01,2025-01-01,9.281736e+06,10871226.58,1.0,5004298_1
3,5004298,323007335,0.05,GC,1,HC,6,Centro,610,HOSPITAL,01,2025-01-01,0.000000e+00,9300596.00,1.0,5004298_1
4,5004298,323010165,0.25,GC,1,HC,6,Centro,610,HOSPITAL,01,2025-01-01,0.000000e+00,9300596.00,1.0,5004298_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67536,NaN,NaN,NaN,GC,2,AE,0,Venezuela,006,Distribuidor,36,2025-12-01,0.000000e+00,-677031.04,NaN,NaN
67537,NaN,NaN,NaN,GC,2,AE,0,Venezuela,003,Distribuidor,35,2025-12-01,2.185384e+07,0.00,NaN,NaN
67538,NaN,NaN,NaN,GC,2,AE,0,Venezuela,006,Distribuidor,36,2025-12-01,1.956096e+07,0.00,NaN,NaN
67539,NaN,NaN,NaN,GC,3,BA,0,Venezuela,A32,Distribuidor,84,2025-12-01,2.848796e+06,0.00,NaN,NaN
67540,NaN,NaN,NaN,GC,3,BA,0,Venezuela,A34,Distribuidor,85,2025-12-01,1.567423e+06,0.00,NaN,NaN

In [338]:
venta_facturada_zona_pais_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main_centro_costo, 'VentaFacturadaZonaPaisSub')
venta_facturada_zona_pais_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,5002711_1,2025-01-01,610,HC,323007336,8.564414e+07,3.820224e+08,VentaFacturadaZonaPaisSub
1,5002711_1,2025-01-01,610,HC,323010170,8.564414e+07,3.820224e+08,VentaFacturadaZonaPaisSub
2,5002711_1,2025-01-01,610,HC,323015070,8.564414e+07,3.820224e+08,VentaFacturadaZonaPaisSub
3,5002711_1,2025-01-01,620,HC,323007336,7.339065e+08,1.779295e+09,VentaFacturadaZonaPaisSub
4,5002711_1,2025-01-01,620,HC,323010170,7.339065e+08,1.779295e+09,VentaFacturadaZonaPaisSub
...,...,...,...,...,...,...,...,...
2251,5005980_3,2025-12-01,A35,BA,323010175,9.686927e+07,2.693385e+08,VentaFacturadaZonaPaisSub
2252,5005980_3,2025-12-01,A35,BA,323015075,9.686927e+07,2.693385e+08,VentaFacturadaZonaPaisSub
2253,5005980_3,2025-12-01,A45,BA,323007345,1.092696e+08,1.228245e+09,VentaFacturadaZonaPaisSub
2254,5005980_3,2025-12-01,A45,BA,323010175,1.092696e+08,1.228245e+09,VentaFacturadaZonaPaisSub
2255,5005980_3,2025-12-01,A45,BA,323015075,1.092696e+08,1.228245e+09,VentaFacturadaZonaPaisSub

In [339]:
venta_facturada_zona_pais_sub = venta_facturada_zona_pais_sub.groupby(['Fecha', 'Contexto', 'ZonaGeografica'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
venta_facturada_zona_pais_sub.reset_index(inplace=True)
venta_facturada_zona_pais_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1564536508.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  venta_facturada_zona_pais_sub = venta_facturada_zona_pais_sub.groupby(['Fecha', 'Contexto', 'ZonaGeografica'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

     index      Fecha   Contexto ZonaGeografica          Real   Presupuesto
0        0 2025-01-01  5002711_1          Norte  1.695854e+09  3.095003e+09
1        1 2025-01-01  5002711_2          Norte  3.680744e+08  7.309924e+08
2        2 2025-01-01  5002711_3          Norte  4.456426e+07  1.812266e+08
3        3 2025-01-01  5004298_1         Centro  2.927281e+09  4.307229e+09
4        4 2025-01-01  5004298_2         Centro  1.022173e+09  1.544872e+09
..     ...        ...        ...            ...           ...           ...
103    103 2025-12-01  5004298_2         Centro  3.871084e+09  2.373972e+09
104    104 2025-12-01  5004298_3         Centro  2.161144e+09  7.175288e+08
105    105 2025-12-01  5005980_1   Suroccidente  4.558872e+09  5.995505e+09
106    106 2025-12-01  5005980_2   Suroccidente  3.335743e+09  1.709230e+09
107    107 2025-12-01  5005980_3   Suroccidente  2.808104e+08  3.294859e+08

[108 rows x 6 columns]

In [340]:
venta_facturada_zona_pais_sub[
    (venta_facturada_zona_pais_sub['ZonaGeografica'] == 'Norte')
]

     index      Fecha   Contexto ZonaGeografica          Real   Presupuesto
0        0 2025-01-01  5002711_1          Norte  1.695854e+09  3.095003e+09
1        1 2025-01-01  5002711_2          Norte  3.680744e+08  7.309924e+08
2        2 2025-01-01  5002711_3          Norte  4.456426e+07  1.812266e+08
9        9 2025-02-01  5002711_1          Norte  3.484026e+09  3.713033e+09
10      10 2025-02-01  5002711_2          Norte  1.190524e+09  9.559852e+08
11      11 2025-02-01  5002711_3          Norte  3.349316e+08  1.866064e+08
18      18 2025-03-01  5002711_1          Norte  3.347262e+09  4.600058e+09
19      19 2025-03-01  5002711_2          Norte  7.518671e+08  1.006700e+09
20      20 2025-03-01  5002711_3          Norte  2.361502e+08  2.437144e+08
27      27 2025-04-01  5002711_1          Norte  4.481795e+09  3.586017e+09
28      28 2025-04-01  5002711_2          Norte  1.117712e+09  9.293139e+08
29      29 2025-04-01  5002711_3          Norte -1.266672e+08  2.170972e+08
36      36 2025-05-01  5002711_1          Norte  4.733499e+09  4.636418e+09
37      37 2025-05-01  5002711_2          Norte  7.823257e+08  1.044638e+09
38      38 2025-05-01  5002711_3          Norte  1.882208e+08  2.465142e+08
45      45 2025-06-01  5002711_1          Norte  4.309993e+09  4.766540e+09
46      46 2025-06-01  5002711_2          Norte  8.715384e+08  1.056035e+09
47      47 2025-06-01  5002711_3          Norte  9.666770e+08  2.535101e+08
54      54 2025-07-01  5002711_1          Norte  4.326741e+09  4.554788e+09
55      55 2025-07-01  5002711_2          Norte  2.635158e+09  2.890017e+09
56      56 2025-07-01  5002711_3          Norte  3.461122e+08  2.722982e+08
63      63 2025-08-01  5002711_1          Norte  4.097716e+09  4.849704e+09
64      64 2025-08-01  5002711_2          Norte  7.274628e+08  1.124841e+09
65      65 2025-08-01  5002711_3          Norte  2.168318e+08  2.732413e+08
72      72 2025-09-01  5002711_1          Norte  4.144675e+09  4.747412e+09
73      73 2025-09-01  5002711_2          Norte  8.646070e+08  1.068037e+09
74      74 2025-09-01  5002711_3          Norte  2.829011e+08  2.873259e+08
81      81 2025-10-01  5002711_1          Norte  4.305500e+09  4.702142e+09
82      82 2025-10-01  5002711_2          Norte  1.218127e+09  1.050820e+09
83      83 2025-10-01  5002711_3          Norte  1.984338e+08  1.137219e+09
90      90 2025-11-01  5002711_1          Norte  4.270425e+09  5.427396e+09
91      91 2025-11-01  5002711_2          Norte  7.875027e+08  1.172178e+09
92      92 2025-11-01  5002711_3          Norte  2.242008e+08  3.129299e+08
99      99 2025-12-01  5002711_1          Norte  6.615976e+09  6.002774e+09
100    100 2025-12-01  5002711_2          Norte  1.370886e+09  1.139836e+09
101    101 2025-12-01  5002711_3          Norte  3.003256e+09  2.980122e+08

In [341]:
# venta_facturada_zona_pais_sub = venta_facturada_zona_pais_sub1.copy()

In [342]:
# venta_facturada_zona_pais_sub1 = venta_facturada_zona_pais_sub
# venta_facturada_zona_pais_sub1.head()

In [343]:
venta_facturada_zona_pais_sub['Real'].fillna(0.0, inplace=True)
venta_facturada_zona_pais_sub['Presupuesto'].fillna(0.0, inplace=True)

venta_facturada_zona_pais_sub['Presupuesto'] = venta_facturada_zona_pais_sub.groupby(['Contexto', 'ZonaGeografica'])['Presupuesto'].transform(pd.Series.cumsum)
venta_facturada_zona_pais_sub['Real'] = venta_facturada_zona_pais_sub.groupby(['Contexto', 'ZonaGeografica'])['Real'].transform(pd.Series.cumsum)

venta_facturada_zona_pais_sub.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1614170882.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  venta_facturada_zona_pais_sub['Real'].fillna(0.0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1614170882.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  venta_facturada_zona_pais_sub['Presupuesto'].fillna(0.0, inplace=True)

   index      Fecha   Contexto ZonaGeografica          Real   Presupuesto
0      0 2025-01-01  5002711_1          Norte  1.695854e+09  3.095003e+09
1      1 2025-01-01  5002711_2          Norte  3.680744e+08  7.309924e+08
2      2 2025-01-01  5002711_3          Norte  4.456426e+07  1.812266e+08
3      3 2025-01-01  5004298_1         Centro  2.927281e+09  4.307229e+09
4      4 2025-01-01  5004298_2         Centro  1.022173e+09  1.544872e+09

In [344]:
venta_facturada_zona_pais_sub[
    (venta_facturada_zona_pais_sub['ZonaGeografica'] == 'Norte') 
]

     index      Fecha   Contexto ZonaGeografica          Real   Presupuesto
0        0 2025-01-01  5002711_1          Norte  1.695854e+09  3.095003e+09
1        1 2025-01-01  5002711_2          Norte  3.680744e+08  7.309924e+08
2        2 2025-01-01  5002711_3          Norte  4.456426e+07  1.812266e+08
9        9 2025-02-01  5002711_1          Norte  5.179880e+09  6.808036e+09
10      10 2025-02-01  5002711_2          Norte  1.558598e+09  1.686978e+09
11      11 2025-02-01  5002711_3          Norte  3.794959e+08  3.678330e+08
18      18 2025-03-01  5002711_1          Norte  8.527142e+09  1.140809e+10
19      19 2025-03-01  5002711_2          Norte  2.310465e+09  2.693677e+09
20      20 2025-03-01  5002711_3          Norte  6.156460e+08  6.115474e+08
27      27 2025-04-01  5002711_1          Norte  1.300894e+10  1.499411e+10
28      28 2025-04-01  5002711_2          Norte  3.428177e+09  3.622991e+09
29      29 2025-04-01  5002711_3          Norte  4.889788e+08  8.286446e+08
36      36 2025-05-01  5002711_1          Norte  1.774244e+10  1.963053e+10
37      37 2025-05-01  5002711_2          Norte  4.210503e+09  4.667629e+09
38      38 2025-05-01  5002711_3          Norte  6.771996e+08  1.075159e+09
45      45 2025-06-01  5002711_1          Norte  2.205243e+10  2.439707e+10
46      46 2025-06-01  5002711_2          Norte  5.082041e+09  5.723665e+09
47      47 2025-06-01  5002711_3          Norte  1.643877e+09  1.328669e+09
54      54 2025-07-01  5002711_1          Norte  2.637917e+10  2.895186e+10
55      55 2025-07-01  5002711_2          Norte  7.717199e+09  8.613682e+09
56      56 2025-07-01  5002711_3          Norte  1.989989e+09  1.600967e+09
63      63 2025-08-01  5002711_1          Norte  3.047689e+10  3.380156e+10
64      64 2025-08-01  5002711_2          Norte  8.444662e+09  9.738523e+09
65      65 2025-08-01  5002711_3          Norte  2.206821e+09  1.874208e+09
72      72 2025-09-01  5002711_1          Norte  3.462156e+10  3.854897e+10
73      73 2025-09-01  5002711_2          Norte  9.309269e+09  1.080656e+10
74      74 2025-09-01  5002711_3          Norte  2.489722e+09  2.161534e+09
81      81 2025-10-01  5002711_1          Norte  3.892706e+10  4.325112e+10
82      82 2025-10-01  5002711_2          Norte  1.052740e+10  1.185738e+10
83      83 2025-10-01  5002711_3          Norte  2.688156e+09  3.298753e+09
90      90 2025-11-01  5002711_1          Norte  4.319749e+10  4.867851e+10
91      91 2025-11-01  5002711_2          Norte  1.131490e+10  1.302956e+10
92      92 2025-11-01  5002711_3          Norte  2.912356e+09  3.611683e+09
99      99 2025-12-01  5002711_1          Norte  4.981346e+10  5.468129e+10
100    100 2025-12-01  5002711_2          Norte  1.268578e+10  1.416939e+10
101    101 2025-12-01  5002711_3          Norte  5.915612e+09  3.909696e+09

In [345]:
venta_facturada_zona_pais_sub['PorcentajeCumplimiento'] = venta_facturada_zona_pais_sub['Real'] / venta_facturada_zona_pais_sub['Presupuesto']
venta_facturada_zona_pais_sub['PorcentajeCumplimiento'] = venta_facturada_zona_pais_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
venta_facturada_zona_pais_sub['PorcentajeCumplimiento'].fillna(0.0, inplace=True)

# venta_facturada_zona_pais_sub = convertir_a_euros(venta_facturada_zona_pais_sub)

venta_facturada_zona_pais_sub['Variable'] = 'VentaFacturadaZonaPaisSub'

# venta_facturada_zona_pais_sub = venta_facturada_zona_pais_sub[colums_name]

venta_facturada_zona_pais_sub = venta_facturada_zona_pais_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

venta_facturada_zona_pais_sub

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\1961533061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  venta_facturada_zona_pais_sub['PorcentajeCumplimiento'].fillna(0.0, inplace=True)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5002711_1,VentaFacturadaZonaPaisSub,2025-01-01,1.695854e+09,3.095003e+09,0.55
1,5002711_2,VentaFacturadaZonaPaisSub,2025-01-01,3.680744e+08,7.309924e+08,0.50
2,5002711_3,VentaFacturadaZonaPaisSub,2025-01-01,4.456426e+07,1.812266e+08,0.25
3,5004298_1,VentaFacturadaZonaPaisSub,2025-01-01,2.927281e+09,4.307229e+09,0.68
4,5004298_2,VentaFacturadaZonaPaisSub,2025-01-01,1.022173e+09,1.544872e+09,0.66
...,...,...,...,...,...,...
103,5004298_2,VentaFacturadaZonaPaisSub,2025-12-01,2.525827e+10,2.581636e+10,0.98
104,5004298_3,VentaFacturadaZonaPaisSub,2025-12-01,9.636387e+09,8.173752e+09,1.18
105,5005980_1,VentaFacturadaZonaPaisSub,2025-12-01,4.921658e+10,5.419335e+10,0.91
106,5005980_2,VentaFacturadaZonaPaisSub,2025-12-01,2.055618e+10,1.839065e+10,1.12
107,5005980_3,VentaFacturadaZonaPaisSub,2025-12-01,2.953306e+09,4.494896e+09,0.66

In [346]:
venta_facturada_zona_pais_sub[
    (venta_facturada_zona_pais_sub['Fecha'] == '2024-03-01')
]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## 39 VentaFacturadaBraunPaisSub

In [347]:
len(df_parrillas[df_parrillas['Nombre variable'] == 'VentaFacturadaBraunPaisSUB'])

51

In [348]:
# df_parrillas[df_parrillas['Nombre variable'] == 'VentaFacturadaBraunPaisSUB'].merge(
#     df_empleados,
#     how='left'
# )

In [349]:
df_venta_otras_companias

   Compania      Fecha          Real   Presupuesto
0     BBMCO 2025-03-01  9.930397e+06  1.113375e+07
1     BBMCO 2025-04-01  1.364901e+07  1.472580e+07
2     BBMCO 2025-05-01  1.837213e+07  1.917960e+07
3     BBMCO 2025-06-01  2.268349e+07  2.375437e+07
4     BBMCO 2025-07-01  2.724003e+07  2.860037e+07
5     BBMCO 2025-08-01  3.173319e+07  3.328414e+07
6     BBMCO 2025-09-01  3.592647e+07  3.791272e+07
7     BBMCO 2025-10-01  4.031099e+07  4.294345e+07
8     BBMCO 2025-11-01  4.560969e+07  4.812728e+07
9     BBMCO 2025-12-01  4.560969e+07  4.812728e+07
10    BBMEC 2025-03-01  7.273623e+06  6.310266e+06
11    BBMEC 2025-04-01  9.789502e+06  8.602565e+06
12    BBMEC 2025-05-01  1.227876e+07  1.090002e+07
13    BBMEC 2025-06-01  1.490971e+07  1.320263e+07
14    BBMEC 2025-07-01  1.695826e+07  1.572467e+07
15    BBMEC 2025-08-01  1.924409e+07  1.830544e+07
16    BBMEC 2025-09-01  2.149565e+07  2.083780e+07
17    BBMEC 2025-10-01  2.426012e+07  2.336764e+07
18    BBMEC 2025-11-01  2.637021e+07  2.601364e+07
19    BBMEC 2025-12-01  2.637021e+07  2.601364e+07

In [350]:
df_recaudo_otras_companias

Empty DataFrame
Columns: [Compania, Fecha, Real, Presupuesto]
Index: []

In [351]:
area_calculo_sba_completo

     AreaCalculo  Consecutivo Division GrupoProducto    SBA TipoEmpleado
0              1            1    BBMCO         BBMCO  BBMCO           AD
1              2            1    BBMCO         BBMCO  BBMCO           AD
2              3            1    BBMCO         BBMCO  BBMCO           AD
3              4            1    BBMCO         BBMCO  BBMCO           AD
4              1            1    BBMCO         BBMCO  BBMCO          AD1
..           ...          ...      ...           ...    ...          ...
301           13            1       AE           003     35           VE
302           13            2       AE           801     32           VE
303           13            2       AE           801     30           VE
304           13            2       AE           801     33           VE
305           13            2       AE           801     31           VE

[858 rows x 6 columns]

In [352]:
# df_parrillas[df_parrillas['Nombre variable'] == 'VentaFacturadaBraunPaisSUB'].merge(
#     df_empleados,
#     how='left'
# ).merge(
#     area_calculo_sba_completo,
#     how='left'
# )

In [353]:
area_calculo_sba_completo_bbmco_bbmec = area_calculo_sba_completo[
    ((area_calculo_sba_completo['TipoEmpleado']=='AD4') | (area_calculo_sba_completo['TipoEmpleado']=='MK')) &
    ((area_calculo_sba_completo['Division']=='BBMCO') | (area_calculo_sba_completo['Division']=='BBMEC'))
]
area_calculo_sba_completo_bbmco_bbmec

    AreaCalculo  Consecutivo Division GrupoProducto    SBA TipoEmpleado
16            1            1    BBMCO         BBMCO  BBMCO          AD4
17            1            2    BBMEC         BBMEC  BBMEC          AD4
18            2            1    BBMCO         BBMCO  BBMCO          AD4

In [354]:
area_calculo_sba_completo_bbmco_bbmec = df_parrillas[df_parrillas['Nombre variable'] == 'VentaFacturadaBraunPaisSUB'].merge(
    df_empleados,
    how='left'
).merge(
    area_calculo_sba_completo,
    how='left'
)
area_calculo_sba_completo_bbmco_bbmec.head()

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,AreaCalculo,Division,GrupoProducto,SBA
0,53002714,VentaFacturadaBraunPaisSUB,53002714_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN
1,52417387,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,52417387,juliana.ayala@bbraun.com,JULIANA,AYALA ENCISO,7000000.0,2025-12-01,NaT,9.0,BBMCO,,
2,52417387,VentaFacturadaBraunPaisSUB,52417387_2,0.2,2,VentaFacturadaBraunPaisSUB,BBMEC,MK1,52417387,juliana.ayala@bbraun.com,JULIANA,AYALA ENCISO,7000000.0,2025-12-01,NaT,9.0,BBMEC,BBMEC,BBMEC
3,94526955,VentaFacturadaBraunPaisSUB,94526955_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,94526955,juan.barajas@bbraun.com,JUAN FELIPE,BARAJAS LOPEZ,4900000.0,2025-06-01,NaT,9.0,BBMCO,,
4,94526955,VentaFacturadaBraunPaisSUB,94526955_2,0.2,2,VentaFacturadaBraunPaisSUB,BBMEC,MK1,94526955,juan.barajas@bbraun.com,JUAN FELIPE,BARAJAS LOPEZ,4900000.0,2025-06-01,NaT,9.0,BBMEC,BBMEC,BBMEC

In [375]:
main = pd.merge(
    left=area_calculo_sba_completo_bbmco_bbmec,
    right=df_venta_otras_companias.rename(columns={'Compania': 'Division'}),
    on=['Division'],
    how='inner'
)
main

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,Identificacion,CorreoElectronico,...,SalarioVariable,FechaIngreso,FechaRetiro,AreaCalculo,Division,GrupoProducto,SBA,Fecha,Real,Presupuesto
0,52417387,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,52417387,juliana.ayala@bbraun.com,...,7000000.0,2025-12-01,NaT,9.0,BBMCO,,,2025-03-01,9.930397e+06,1.113375e+07
1,52417387,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,52417387,juliana.ayala@bbraun.com,...,7000000.0,2025-12-01,NaT,9.0,BBMCO,,,2025-04-01,1.364901e+07,1.472580e+07
2,52417387,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,52417387,juliana.ayala@bbraun.com,...,7000000.0,2025-12-01,NaT,9.0,BBMCO,,,2025-05-01,1.837213e+07,1.917960e+07
3,52417387,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,52417387,juliana.ayala@bbraun.com,...,7000000.0,2025-12-01,NaT,9.0,BBMCO,,,2025-06-01,2.268349e+07,2.375437e+07
4,52417387,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,52417387,juliana.ayala@bbraun.com,...,7000000.0,2025-12-01,NaT,9.0,BBMCO,,,2025-07-01,2.724003e+07,2.860037e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,1000000.0,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-08-01,3.173319e+07,3.328414e+07
326,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,1000000.0,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-09-01,3.592647e+07,3.791272e+07
327,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,1000000.0,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-10-01,4.031099e+07,4.294345e+07
328,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,1000000.0,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-11-01,4.560969e+07,4.812728e+07
329,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,1000000.0,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-12-01,4.560969e+07,4.812728e+07

In [376]:
main = main[main['Fecha'] >= main['FechaIngreso']]  ## Corrección Fecha Ingreso

In [377]:
# main = main.merge(df_empleados)
main['PorcentajeCumplimiento'] = main['Real'] / main['Presupuesto']
main['PorcentajeCumplimiento'] = main['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaBraunPaisSUB'
main['Contexto'] = main['CodigoEmpleado'].astype(str).str.cat(main['Consecutivo'].astype(str), sep="_")
main

C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3143645042.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main['PorcentajeCumplimiento'] = main['Real'] / main['Presupuesto']
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3143645042.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main['PorcentajeCumplimiento'] = main['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3143645042.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main['Variable'] = 'VentaFacturadaBraunPaisSUB'
C:\Users\HP\AppData\Local\Temp\ipykernel_53368\3143645042.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main['Contexto'] = main['CodigoEmpleado'].astype(str).str.cat(main['Consecutivo'].astype(str), sep="_")

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,Identificacion,CorreoElectronico,...,FechaIngreso,FechaRetiro,AreaCalculo,Division,GrupoProducto,SBA,Fecha,Real,Presupuesto,PorcentajeCumplimiento
9,52417387,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,52417387,juliana.ayala@bbraun.com,...,2025-12-01,NaT,9.0,BBMCO,,,2025-12-01,4.560969e+07,4.812728e+07,0.95
19,52417387,VentaFacturadaBraunPaisSUB,52417387_2,0.2,2,VentaFacturadaBraunPaisSUB,BBMEC,MK1,52417387,juliana.ayala@bbraun.com,...,2025-12-01,NaT,9.0,BBMEC,BBMEC,BBMEC,2025-12-01,2.637021e+07,2.601364e+07,1.01
23,94526955,VentaFacturadaBraunPaisSUB,94526955_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,94526955,juan.barajas@bbraun.com,...,2025-06-01,NaT,9.0,BBMCO,,,2025-06-01,2.268349e+07,2.375437e+07,0.95
24,94526955,VentaFacturadaBraunPaisSUB,94526955_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,94526955,juan.barajas@bbraun.com,...,2025-06-01,NaT,9.0,BBMCO,,,2025-07-01,2.724003e+07,2.860037e+07,0.95
25,94526955,VentaFacturadaBraunPaisSUB,94526955_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,94526955,juan.barajas@bbraun.com,...,2025-06-01,NaT,9.0,BBMCO,,,2025-08-01,3.173319e+07,3.328414e+07,0.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-08-01,3.173319e+07,3.328414e+07,0.95
326,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-09-01,3.592647e+07,3.791272e+07,0.95
327,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-10-01,4.031099e+07,4.294345e+07,0.94
328,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-11-01,4.560969e+07,4.812728e+07,0.95
329,70014725,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,1019140853,ana.silva3@bbraun.com,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-12-01,4.560969e+07,4.812728e+07,0.95

In [378]:
main_centro_costo = pd.merge(
    df_empleados_centros_costos,
    main,
    on=['CodigoEmpleado'],
    how='right'
)
main_centro_costo

,CodigoEmpleado,CodigoCentroCosto,PorcentajeAsignacion,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,...,FechaIngreso,FechaRetiro,AreaCalculo,Division,GrupoProducto,SBA,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,52417387,323007334,0.05,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,...,2025-12-01,NaT,9.0,BBMCO,,,2025-12-01,4.560969e+07,4.812728e+07,0.95
1,52417387,323010160,0.25,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,...,2025-12-01,NaT,9.0,BBMCO,,,2025-12-01,4.560969e+07,4.812728e+07,0.95
2,52417387,323015060,0.70,VentaFacturadaBraunPaisSUB,52417387_1,0.2,1,VentaFacturadaBraunPaisSUB,BBMCO,MK1,...,2025-12-01,NaT,9.0,BBMCO,,,2025-12-01,4.560969e+07,4.812728e+07,0.95
3,52417387,323007334,0.05,VentaFacturadaBraunPaisSUB,52417387_2,0.2,2,VentaFacturadaBraunPaisSUB,BBMEC,MK1,...,2025-12-01,NaT,9.0,BBMEC,BBMEC,BBMEC,2025-12-01,2.637021e+07,2.601364e+07,1.01
4,52417387,323010160,0.25,VentaFacturadaBraunPaisSUB,52417387_2,0.2,2,VentaFacturadaBraunPaisSUB,BBMEC,MK1,...,2025-12-01,NaT,9.0,BBMEC,BBMEC,BBMEC,2025-12-01,2.637021e+07,2.601364e+07,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,70014725,323004010,1.00,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-08-01,3.173319e+07,3.328414e+07,0.95
466,70014725,323004010,1.00,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-09-01,3.592647e+07,3.791272e+07,0.95
467,70014725,323004010,1.00,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-10-01,4.031099e+07,4.294345e+07,0.94
468,70014725,323004010,1.00,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-11-01,4.560969e+07,4.812728e+07,0.95
469,70014725,323004010,1.00,VentaFacturadaBraunPaisSUB,70014725_1,0.4,1,VentaFacturadaBraunPaisSUB,BBMCO,AD,...,2024-07-01,NaT,2.0,BBMCO,BBMCO,BBMCO,2025-12-01,4.560969e+07,4.812728e+07,0.95

In [379]:
venta_facturada_braun_pais_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main_centro_costo, 'VentaFacturadaBraunPaisSUB')
venta_facturada_braun_pais_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,1013630697_1,2025-06-01,BBMCO,BBMCO,323004035,2.268349e+07,2.375437e+07,VentaFacturadaBraunPaisSUB
1,1013630697_1,2025-07-01,BBMCO,BBMCO,323004035,4.992352e+07,5.235474e+07,VentaFacturadaBraunPaisSUB
2,1013630697_1,2025-08-01,BBMCO,BBMCO,323004035,8.165671e+07,8.563888e+07,VentaFacturadaBraunPaisSUB
3,1013630697_1,2025-09-01,BBMCO,BBMCO,323004035,1.175832e+08,1.235516e+08,VentaFacturadaBraunPaisSUB
4,1013630697_1,2025-10-01,BBMCO,BBMCO,323004035,1.578942e+08,1.664951e+08,VentaFacturadaBraunPaisSUB
...,...,...,...,...,...,...,...,...
465,94526955_2,2025-08-01,BBMEC,BBMEC,323004050,5.111206e+07,4.723275e+07,VentaFacturadaBraunPaisSUB
466,94526955_2,2025-09-01,BBMEC,BBMEC,323004050,7.260771e+07,6.807054e+07,VentaFacturadaBraunPaisSUB
467,94526955_2,2025-10-01,BBMEC,BBMEC,323004050,9.686783e+07,9.143819e+07,VentaFacturadaBraunPaisSUB
468,94526955_2,2025-11-01,BBMEC,BBMEC,323004050,1.232380e+08,1.174518e+08,VentaFacturadaBraunPaisSUB
469,94526955_2,2025-12-01,BBMEC,BBMEC,323004050,1.496083e+08,1.434655e+08,VentaFacturadaBraunPaisSUB

In [372]:
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
venta_facturada_braun_pais_sub = main.copy()
main = None
venta_facturada_braun_pais_sub

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,52417387_1,VentaFacturadaBraunPaisSUB,2025-03-01,9.930397e+06,1.113375e+07,0.89
1,52417387_1,VentaFacturadaBraunPaisSUB,2025-04-01,1.364901e+07,1.472580e+07,0.93
2,52417387_1,VentaFacturadaBraunPaisSUB,2025-05-01,1.837213e+07,1.917960e+07,0.96
3,52417387_1,VentaFacturadaBraunPaisSUB,2025-06-01,2.268349e+07,2.375437e+07,0.95
4,52417387_1,VentaFacturadaBraunPaisSUB,2025-07-01,2.724003e+07,2.860037e+07,0.95
...,...,...,...,...,...,...
325,70014725_1,VentaFacturadaBraunPaisSUB,2025-08-01,3.173319e+07,3.328414e+07,0.95
326,70014725_1,VentaFacturadaBraunPaisSUB,2025-09-01,3.592647e+07,3.791272e+07,0.95
327,70014725_1,VentaFacturadaBraunPaisSUB,2025-10-01,4.031099e+07,4.294345e+07,0.94
328,70014725_1,VentaFacturadaBraunPaisSUB,2025-11-01,4.560969e+07,4.812728e+07,0.95
329,70014725_1,VentaFacturadaBraunPaisSUB,2025-12-01,4.560969e+07,4.812728e+07,0.95

In [380]:
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
venta_facturada_braun_pais_sub = main.copy()
main = None
venta_facturada_braun_pais_sub

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
9,52417387_1,VentaFacturadaBraunPaisSUB,2025-12-01,4.560969e+07,4.812728e+07,0.95
19,52417387_2,VentaFacturadaBraunPaisSUB,2025-12-01,2.637021e+07,2.601364e+07,1.01
23,94526955_1,VentaFacturadaBraunPaisSUB,2025-06-01,2.268349e+07,2.375437e+07,0.95
24,94526955_1,VentaFacturadaBraunPaisSUB,2025-07-01,2.724003e+07,2.860037e+07,0.95
25,94526955_1,VentaFacturadaBraunPaisSUB,2025-08-01,3.173319e+07,3.328414e+07,0.95
...,...,...,...,...,...,...
325,70014725_1,VentaFacturadaBraunPaisSUB,2025-08-01,3.173319e+07,3.328414e+07,0.95
326,70014725_1,VentaFacturadaBraunPaisSUB,2025-09-01,3.592647e+07,3.791272e+07,0.95
327,70014725_1,VentaFacturadaBraunPaisSUB,2025-10-01,4.031099e+07,4.294345e+07,0.94
328,70014725_1,VentaFacturadaBraunPaisSUB,2025-11-01,4.560969e+07,4.812728e+07,0.95
329,70014725_1,VentaFacturadaBraunPaisSUB,2025-12-01,4.560969e+07,4.812728e+07,0.95

In [381]:
venta_facturada_braun_pais_sub.to_excel("venta_facturada_braun_pais_sub_corregido.xlsx")

## 40 VentaFacturadaBraunPais

In [352]:
# VentaRecaudoReal (venta)
# VentaRecaudoPresupuesto (venta)

# Preparar
drop_cols = ['Recaudo', 'Division', 'Cluster','CodigoEmpleado', 'ZonaGeografica','GrupoProducto', 'Canal', 'SBA']
real = df_venta_recaudo_real.copy().drop(columns=drop_cols)
ppto = df_venta_recaudo_presupuesto.copy().drop(columns=drop_cols)

# Sumamos los registros que tienen el mismo conexto para que exista un solo registro
ppto = ppto.groupby(['Fecha'], as_index=True)[['Venta']].apply(sum)
real = real.groupby(['Fecha'], as_index=True)[['Venta']].apply(sum)
ppto.reset_index(inplace=True)
real.reset_index(inplace=True)

main = ppto.rename(columns={'Venta': 'Presupuesto'}).merge(
    real.rename(columns={'Venta': 'Real'}),
    on=['Fecha'],
    how='left'
)
main['Real'].fillna(0, inplace=True)


# Calcular
main['Contexto']= 'BBMCO'
main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main['PorcentajeCumplimiento'] = (main['Real']/main['Presupuesto']).apply(lambda x: round(x, 2))
main['Variable'] = 'VentaFacturadaBraunPais'


#Formatear
main.reset_index(inplace=True)
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]


venta_facturada_braun_pais = main.copy()
main = None
venta_facturada_braun_pais

C:\Users\HP\AppData\Local\Temp\ipykernel_30012\2692634173.py:10: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ppto = ppto.groupby(['Fecha'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_30012\2692634173.py:11: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  real = real.groupby(['Fecha'], as_index=True)[['Venta']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\HP\AppData\Local\Temp\ipykernel_30012\2692634173.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Real'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_30012\2692634173.py:25: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,BBMCO,VentaFacturadaBraunPais,2025-01-01,8.576640e+09,1.476750e+10,0.58
1,BBMCO,VentaFacturadaBraunPais,2025-02-01,2.579232e+10,3.332374e+10,0.77
2,BBMCO,VentaFacturadaBraunPais,2025-03-01,4.373744e+10,5.425397e+10,0.81
3,BBMCO,VentaFacturadaBraunPais,2025-04-01,6.141645e+10,7.175773e+10,0.86
4,BBMCO,VentaFacturadaBraunPais,2025-05-01,8.356181e+10,9.346076e+10,0.89
5,BBMCO,VentaFacturadaBraunPais,2025-06-01,1.039058e+11,1.157533e+11,0.90
6,BBMCO,VentaFacturadaBraunPais,2025-07-01,1.253698e+11,1.393675e+11,0.90
7,BBMCO,VentaFacturadaBraunPais,2025-08-01,1.464831e+11,1.621911e+11,0.90
8,BBMCO,VentaFacturadaBraunPais,2025-09-01,1.657880e+11,1.847459e+11,0.90
9,BBMCO,VentaFacturadaBraunPais,2025-10-01,1.856280e+11,2.092603e+11,0.89
10,BBMCO,VentaFacturadaBraunPais,2025-11-01,2.090261e+11,2.345207e+11,0.89
11,BBMCO,VentaFacturadaBraunPais,2025-12-01,2.424165e+11,2.617346e+11,0.93

## 41 RentabilidadUnidadNegocioCM2COGsSUB

In [353]:
df_rentabilidad.copy()

,Compania,GrupoProducto,SBA,ClaseRentabilidad,Fecha,Real,Presupuesto
0,BBMCO,001,30,CM2COGSP,2025-03-01,2.466612e+05,2.619855e+05
1,BBMCO,001,30,CM2COGSP,2025-04-01,3.105949e+05,3.572529e+05
2,BBMCO,001,30,CM2COGSP,2025-05-01,3.359584e+05,4.525204e+05
3,BBMCO,001,30,CM2COGSP,2025-06-01,4.053510e+05,5.477878e+05
4,BBMCO,001,30,CM2COGSP,2025-07-01,5.318528e+05,6.430553e+05
...,...,...,...,...,...,...,...
473,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-08-01,3.049280e+06,2.347009e+06
474,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-09-01,2.453488e+06,2.763416e+06
475,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-10-01,3.299142e+06,3.188239e+06
476,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-11-01,3.819836e+06,3.654547e+06
477,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-12-01,3.819836e+06,3.654547e+06

In [354]:
rentabilidad_gu = df_rentabilidad.copy()
rentabilidad_gu

,Compania,GrupoProducto,SBA,ClaseRentabilidad,Fecha,Real,Presupuesto
0,BBMCO,001,30,CM2COGSP,2025-03-01,2.466612e+05,2.619855e+05
1,BBMCO,001,30,CM2COGSP,2025-04-01,3.105949e+05,3.572529e+05
2,BBMCO,001,30,CM2COGSP,2025-05-01,3.359584e+05,4.525204e+05
3,BBMCO,001,30,CM2COGSP,2025-06-01,4.053510e+05,5.477878e+05
4,BBMCO,001,30,CM2COGSP,2025-07-01,5.318528e+05,6.430553e+05
...,...,...,...,...,...,...,...
473,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-08-01,3.049280e+06,2.347009e+06
474,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-09-01,2.453488e+06,2.763416e+06
475,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-10-01,3.299142e+06,3.188239e+06
476,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-11-01,3.819836e+06,3.654547e+06
477,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-12-01,3.819836e+06,3.654547e+06

In [355]:
rentabilidad_gu = df_rentabilidad.copy()
rentabilidad_gu['TipoEmpleado'] = 'GU'

area_calculo_sba_completo_gu_consecutivo_10 = area_calculo_sba_completo_gu[area_calculo_sba_completo_gu['Consecutivo'] == 10]

rentabilidad_gu = rentabilidad_gu.merge(
    area_calculo_sba_completo_gu_consecutivo_10[['TipoEmpleado', 'AreaCalculo', 'GrupoProducto', 'SBA', 'Division', 'Consecutivo']],
    on=['TipoEmpleado', 'GrupoProducto', 'SBA'],
    how='left'
)
rentabilidad_gu

,Compania,GrupoProducto,SBA,ClaseRentabilidad,Fecha,Real,Presupuesto,TipoEmpleado,AreaCalculo,Division,Consecutivo
0,BBMCO,001,30,CM2COGSP,2025-03-01,2.466612e+05,2.619855e+05,GU,3.0,AE,10.0
1,BBMCO,001,30,CM2COGSP,2025-04-01,3.105949e+05,3.572529e+05,GU,3.0,AE,10.0
2,BBMCO,001,30,CM2COGSP,2025-05-01,3.359584e+05,4.525204e+05,GU,3.0,AE,10.0
3,BBMCO,001,30,CM2COGSP,2025-06-01,4.053510e+05,5.477878e+05,GU,3.0,AE,10.0
4,BBMCO,001,30,CM2COGSP,2025-07-01,5.318528e+05,6.430553e+05,GU,3.0,AE,10.0
...,...,...,...,...,...,...,...,...,...,...,...
493,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-08-01,3.049280e+06,2.347009e+06,GU,NaN,NaN,NaN
494,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-09-01,2.453488e+06,2.763416e+06,GU,NaN,NaN,NaN
495,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-10-01,3.299142e+06,3.188239e+06,GU,NaN,NaN,NaN
496,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-11-01,3.819836e+06,3.654547e+06,GU,NaN,NaN,NaN
497,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-12-01,3.819836e+06,3.654547e+06,GU,NaN,NaN,NaN

In [356]:
area_calculo_sba_completo_gu

     AreaCalculo  Consecutivo Division GrupoProducto SBA TipoEmpleado
55             1            1       AE           M07               GU
56             1            2       AE           005               GU
57             1            2       AE           M08               GU
58             1           10       AE           005               GU
59             1           10       AE           M07               GU
..           ...          ...      ...           ...  ..          ...
100            8           10       BA           A33  86           GU
101            8           10       BA           A34  85           GU
102            8           10       BA           A35  87           GU
103           10            1       AE           805  30           GU
104           10           10       AE           805  30           GU

[132 rows x 6 columns]

In [357]:
area_calculo_sba_completo_gu_consecutivo_10 = area_calculo_sba_completo_gu[area_calculo_sba_completo_gu['Consecutivo'] == 10]
area_calculo_sba_completo_gu_consecutivo_10.head()

    AreaCalculo  Consecutivo Division GrupoProducto SBA TipoEmpleado
58            1           10       AE           005               GU
59            1           10       AE           M07               GU
60            1           10       AE           M08               GU
66            2           10       AE           003               GU
67            2           10       AE           006               GU

In [358]:
main_rentabilidad = rentabilidad_gu[
    rentabilidad_gu['ClaseRentabilidad'] == 'CM2COGSP'
]
main_rentabilidad.drop(columns='ClaseRentabilidad', inplace=True)

main = main_rentabilidad.merge(
    df_empleados,
    how='left'
)
main.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_30012\1634249067.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_rentabilidad.drop(columns='ClaseRentabilidad', inplace=True)

,Compania,GrupoProducto,SBA,Fecha,Real,Presupuesto,TipoEmpleado,AreaCalculo,Division,Consecutivo,CodigoEmpleado,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro
0,BBMCO,001,30,2025-03-01,246661.238307,261985.490606,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT
1,BBMCO,001,30,2025-04-01,310594.903202,357252.941735,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT
2,BBMCO,001,30,2025-05-01,335958.391518,452520.392865,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT
3,BBMCO,001,30,2025-06-01,405351.002087,547787.843994,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT
4,BBMCO,001,30,2025-07-01,531852.769026,643055.295124,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT

In [359]:
main['Consecutivo'].fillna(0.0, inplace=True)
main['Contexto'] = main['CodigoEmpleado'].str.lower().str.cat(main['Consecutivo'].astype(int).astype(str), sep="_")
main

C:\Users\HP\AppData\Local\Temp\ipykernel_30012\1150396536.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Consecutivo'].fillna(0.0, inplace=True)

,Compania,GrupoProducto,SBA,Fecha,Real,Presupuesto,TipoEmpleado,AreaCalculo,Division,Consecutivo,CodigoEmpleado,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,Contexto
0,BBMCO,001,30,2025-03-01,246661.238307,261985.490606,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
1,BBMCO,001,30,2025-04-01,310594.903202,357252.941735,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
2,BBMCO,001,30,2025-05-01,335958.391518,452520.392865,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
3,BBMCO,001,30,2025-06-01,405351.002087,547787.843994,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
4,BBMCO,001,30,2025-07-01,531852.769026,643055.295124,GU,3.0,AE,10.0,1047393705,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,BBMCO,M08,33,2025-08-01,638711.544725,468923.481211,GU,1.0,AE,10.0,5004302,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10
474,BBMCO,M08,33,2025-09-01,711574.758669,527065.792935,GU,1.0,AE,10.0,5004302,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10
475,BBMCO,M08,33,2025-10-01,786359.539517,585896.135960,GU,1.0,AE,10.0,5004302,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10
476,BBMCO,M08,33,2025-11-01,863205.316850,651784.215066,GU,1.0,AE,10.0,5004302,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10
477,BBMCO,M08,33,2025-12-01,924363.305449,715951.669169,GU,1.0,AE,10.0,5004302,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10

In [360]:
main_centro_costo = pd.merge(
    df_empleados_centros_costos,
    main,
    on=['CodigoEmpleado'],
    how='right'
)
main_centro_costo

,CodigoEmpleado,CodigoCentroCosto,PorcentajeAsignacion,Compania,GrupoProducto,SBA,Fecha,Real,Presupuesto,TipoEmpleado,...,Division,Consecutivo,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,Contexto
0,1047393705,323007270,1.0,BBMCO,001,30,2025-03-01,246661.238307,261985.490606,GU,...,AE,10.0,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
1,1047393705,323007270,1.0,BBMCO,001,30,2025-04-01,310594.903202,357252.941735,GU,...,AE,10.0,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
2,1047393705,323007270,1.0,BBMCO,001,30,2025-05-01,335958.391518,452520.392865,GU,...,AE,10.0,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
3,1047393705,323007270,1.0,BBMCO,001,30,2025-06-01,405351.002087,547787.843994,GU,...,AE,10.0,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
4,1047393705,323007270,1.0,BBMCO,001,30,2025-07-01,531852.769026,643055.295124,GU,...,AE,10.0,1047393705,lina_maria.mendoza@bbraun.com,LINA MARIA,MENDOZA PEÑA,3941000.0,2025-08-01,NaT,1047393705_10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663,5004302,323010140,0.9,BBMCO,M08,33,2025-10-01,786359.539517,585896.135960,GU,...,AE,10.0,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10
664,5004302,323007290,0.1,BBMCO,M08,33,2025-11-01,863205.316850,651784.215066,GU,...,AE,10.0,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10
665,5004302,323010140,0.9,BBMCO,M08,33,2025-11-01,863205.316850,651784.215066,GU,...,AE,10.0,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10
666,5004302,323007290,0.1,BBMCO,M08,33,2025-12-01,924363.305449,715951.669169,GU,...,AE,10.0,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10
667,5004302,323010140,0.9,BBMCO,M08,33,2025-12-01,924363.305449,715951.669169,GU,...,AE,10.0,52507812,martha.vargas@bbraun.com,MARTHA LUCIA,VARGAS MARTINEZ,3941000.0,2011-12-14,NaT,5004302_10

In [361]:
rentabilidad_unidad_negocio_cm2cogs_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main_centro_costo, 'RentabilidadUnidadNegocioCM2COGSSUB')
rentabilidad_unidad_negocio_cm2cogs_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,1047393705_10,2025-03-01,001,AE,323007270,2.719890e+05,2.623649e+05,RentabilidadUnidadNegocioCM2COGSSUB
1,1047393705_10,2025-04-01,001,AE,323007270,6.031436e+05,6.201085e+05,RentabilidadUnidadNegocioCM2COGSSUB
2,1047393705_10,2025-05-01,001,AE,323007270,9.590569e+05,1.073238e+06,RentabilidadUnidadNegocioCM2COGSSUB
3,1047393705_10,2025-06-01,001,AE,323007270,1.383960e+06,1.621772e+06,RentabilidadUnidadNegocioCM2COGSSUB
4,1047393705_10,2025-07-01,001,AE,323007270,1.935237e+06,2.265712e+06,RentabilidadUnidadNegocioCM2COGSSUB
...,...,...,...,...,...,...,...,...
315,70029960_10,2025-10-01,620,HC,323015045,4.911737e+07,4.991699e+07,RentabilidadUnidadNegocioCM2COGSSUB
316,70029960_10,2025-11-01,610,HC,323015045,9.855450e+06,8.003441e+06,RentabilidadUnidadNegocioCM2COGSSUB
317,70029960_10,2025-11-01,620,HC,323015045,5.992686e+07,6.110440e+07,RentabilidadUnidadNegocioCM2COGSSUB
318,70029960_10,2025-12-01,610,HC,323015045,1.220026e+07,9.612173e+06,RentabilidadUnidadNegocioCM2COGSSUB
319,70029960_10,2025-12-01,620,HC,323015045,7.221587e+07,7.383183e+07,RentabilidadUnidadNegocioCM2COGSSUB

In [362]:
main = main.groupby(
    ['Fecha', 'Contexto'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})

main['Variable'] = 'RentabilidadUnidadNegocioCM2COGSSUB'
main['PorcentajeCumplimiento'] = main['Real'] / main['Presupuesto']
main['PorcentajeCumplimiento'] = main['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
main.head()

,Fecha,Contexto,Real,Presupuesto,Variable,PorcentajeCumplimiento
0,2025-03-01,1047393705_10,271989.022341,2.623649e+05,RentabilidadUnidadNegocioCM2COGSSUB,1.04
1,2025-03-01,5004300_10,909941.075969,1.503814e+06,RentabilidadUnidadNegocioCM2COGSSUB,0.61
2,2025-03-01,5004302_10,431872.121288,3.940323e+05,RentabilidadUnidadNegocioCM2COGSSUB,1.10
3,2025-03-01,5005299_10,288371.527336,2.123206e+05,RentabilidadUnidadNegocioCM2COGSSUB,1.36
4,2025-03-01,5032456_10,21483.981246,9.442666e+03,RentabilidadUnidadNegocioCM2COGSSUB,2.28

In [363]:
# ### Cálculo de resultados cualitativos precargados
# main = dataframe_loader.sobreescribir_resultados_cualitativos(
#     main=main,
#     variable='RentabilidadUnidadNegocioCM2COGSSUB',
#     columnas_extra=['CodigoEmpleado', 'Consecutivo'],
#     columnas_extra_merge=['CodigoEmpleado', 'Consecutivo']
# )
# ###

# main

In [364]:
rentabilidad_unidad_negocio_cm2_cogs_sub = main.copy()

rentabilidad_unidad_negocio_cm2_cogs_sub = rentabilidad_unidad_negocio_cm2_cogs_sub[
    ['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]
rentabilidad_unidad_negocio_cm2_cogs_sub = rentabilidad_unidad_negocio_cm2_cogs_sub.drop_duplicates()
rentabilidad_unidad_negocio_cm2_cogs_sub.head()

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,1047393705_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,271989.022341,2.623649e+05,1.04
1,5004300_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,909941.075969,1.503814e+06,0.61
2,5004302_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,431872.121288,3.940323e+05,1.10
3,5005299_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,288371.527336,2.123206e+05,1.36
4,5032456_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,21483.981246,9.442666e+03,2.28

In [365]:
rentabilidad_unidad_negocio_cm2_cogs_sub

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,1047393705_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,2.719890e+05,2.623649e+05,1.04
1,5004300_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,9.099411e+05,1.503814e+06,0.61
2,5004302_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,4.318721e+05,3.940323e+05,1.10
3,5005299_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,2.883715e+05,2.123206e+05,1.36
4,5032456_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,2.148398e+04,9.442666e+03,2.28
...,...,...,...,...,...,...
75,5005299_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,1.746690e+06,1.161338e+06,1.50
76,5032456_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,3.437576e+05,6.564180e+04,5.24
77,70002060_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,1.490017e+06,1.555361e+06,0.96
78,70002068_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,2.157412e+06,1.649519e+06,1.31
79,70029960_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,1.463382e+07,1.433616e+07,1.02

In [366]:
rentabilidad_unidad_negocio_cm2_cogs_sub

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,1047393705_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,2.719890e+05,2.623649e+05,1.04
1,5004300_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,9.099411e+05,1.503814e+06,0.61
2,5004302_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,4.318721e+05,3.940323e+05,1.10
3,5005299_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,2.883715e+05,2.123206e+05,1.36
4,5032456_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-03-01,2.148398e+04,9.442666e+03,2.28
...,...,...,...,...,...,...
75,5005299_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,1.746690e+06,1.161338e+06,1.50
76,5032456_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,3.437576e+05,6.564180e+04,5.24
77,70002060_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,1.490017e+06,1.555361e+06,0.96
78,70002068_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,2.157412e+06,1.649519e+06,1.31
79,70029960_10,RentabilidadUnidadNegocioCM2COGSSUB,2025-12-01,1.463382e+07,1.433616e+07,1.02

In [367]:
df_parrillas[df_parrillas['Variable'] == 'RentabilidadUnidadNegocioCM2COGSSUB']

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
20,5045060,RentabilidadUnidadNegocioCM2COGSSUB,5045060_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Nutrition & Drugs.
228,5032456,RentabilidadUnidadNegocioCM2COGSSUB,5032456_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Renal
312,5004297,RentabilidadUnidadNegocioCM2COGSSUB,5004297_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Operating Room Solutions.
353,91285756,RentabilidadUnidadNegocioCM2COGSSUB,91285756_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.
362,70029960,RentabilidadUnidadNegocioCM2COGSSUB,70029960_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Vascular Access & Reg Anest.
390,70002060,RentabilidadUnidadNegocioCM2COGSSUB,70002060_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Patient Care
493,5004306,RentabilidadUnidadNegocioCM2COGSSUB,5004306_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Operating Room Solutions.
523,70029961,RentabilidadUnidadNegocioCM2COGSSUB,70029961_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Surgical Assets.
530,94460154,RentabilidadUnidadNegocioCM2COGSSUB,94460154_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Patient Care
573,29116947,RentabilidadUnidadNegocioCM2COGSSUB,29116947_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Vascular Access & Reg Anest.
785,5004300,RentabilidadUnidadNegocioCM2COGSSUB,5004300_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.
921,1047393705,RentabilidadUnidadNegocioCM2COGSSUB,1047393705_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Surgical Assets.
954,52900453,RentabilidadUnidadNegocioCM2COGSSUB,52900453_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Surgical Assets.
1054,5005071,RentabilidadUnidadNegocioCM2COGSSUB,5005071_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.
1089,5003954,RentabilidadUnidadNegocioCM2COGSSUB,5003954_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Patient Care
1162,1113621770,RentabilidadUnidadNegocioCM2COGSSUB,1113621770_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Patient Care
1240,5005299,RentabilidadUnidadNegocioCM2COGSSUB,5005299_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Neurosurgery.
1505,5004293,RentabilidadUnidadNegocioCM2COGSSUB,5004293_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,SBA08 12 36
1638,5004302,RentabilidadUnidadNegocioCM2COGSSUB,5004302_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Orthopaedics.
1645,70002068,RentabilidadUnidadNegocioCM2COGSSUB,70002068_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Operating Room Solutions.

## 42 RentabilidadDivisionCM2COGsSub

In [368]:
df_rentabilidad.rename(columns={'Compania': 'Division'})

,Division,GrupoProducto,SBA,ClaseRentabilidad,Fecha,Real,Presupuesto
0,BBMCO,001,30,CM2COGSP,2025-03-01,2.466612e+05,2.619855e+05
1,BBMCO,001,30,CM2COGSP,2025-04-01,3.105949e+05,3.572529e+05
2,BBMCO,001,30,CM2COGSP,2025-05-01,3.359584e+05,4.525204e+05
3,BBMCO,001,30,CM2COGSP,2025-06-01,4.053510e+05,5.477878e+05
4,BBMCO,001,30,CM2COGSP,2025-07-01,5.318528e+05,6.430553e+05
...,...,...,...,...,...,...,...
473,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-08-01,3.049280e+06,2.347009e+06
474,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-09-01,2.453488e+06,2.763416e+06
475,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-10-01,3.299142e+06,3.188239e+06
476,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-11-01,3.819836e+06,3.654547e+06
477,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-12-01,3.819836e+06,3.654547e+06

In [369]:
df_rentabilidad[
    (df_rentabilidad['Compania'] == 'BBMCO') &
    (df_rentabilidad['Fecha'] == '2025-05-01') &
    (df_rentabilidad['ClaseRentabilidad'] == 'CM2COGSP')
]

,Compania,GrupoProducto,SBA,ClaseRentabilidad,Fecha,Real,Presupuesto
2,BBMCO,001,30,CM2COGSP,2025-05-01,3.359584e+05,4.525204e+05
12,BBMCO,001,31,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
22,BBMCO,001,32,CM2COGSP,2025-05-01,1.602219e+04,3.498639e+02
32,BBMCO,001,33,CM2COGSP,2025-05-01,3.932781e+03,2.591228e+02
42,BBMCO,003,35,CM2COGSP,2025-05-01,4.564380e+05,3.144168e+05
52,BBMCO,005,33,CM2COGSP,2025-05-01,5.494462e+03,2.244651e+04
62,BBMCO,005,35,CM2COGSP,2025-05-01,2.099242e+03,3.747284e+03
72,BBMCO,006,36,CM2COGSP,2025-05-01,2.907164e+04,4.537064e+04
82,BBMCO,610,01,CM2COGSP,2025-05-01,1.079931e+05,8.303646e+04
92,BBMCO,610,02,CM2COGSP,2025-05-01,7.196114e+05,5.839697e+05
102,BBMCO,620,13,CM2COGSP,2025-05-01,1.859375e+06,2.055520e+06
112,BBMCO,620,15,CM2COGSP,2025-05-01,1.675980e+06,1.401358e+06
122,BBMCO,620,16,CM2COGSP,2025-05-01,3.323428e+05,2.953253e+05
132,BBMCO,620,36,CM2COGSP,2025-05-01,9.650457e+05,9.314914e+05
142,BBMCO,620,89,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
152,BBMCO,630,03,CM2COGSP,2025-05-01,6.991161e+03,7.171548e+03
162,BBMCO,630,08,CM2COGSP,2025-05-01,7.292850e+05,6.492449e+05
172,BBMCO,630,12,CM2COGSP,2025-05-01,6.520578e+05,1.346282e+06
182,BBMCO,640,03,CM2COGSP,2025-05-01,8.043552e+03,6.207877e+03
192,BBMCO,660,80,CM2COGSP,2025-05-01,1.296374e+03,5.329599e+02
202,BBMCO,660,81,CM2COGSP,2025-05-01,4.883407e+03,-4.089887e+02
212,BBMCO,680,03,CM2COGSP,2025-05-01,3.539412e+05,3.192126e+05
222,BBMCO,801,30,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
232,BBMCO,801,32,CM2COGSP,2025-05-01,1.432506e+05,2.545890e+05
242,BBMCO,801,33,CM2COGSP,2025-05-01,8.323564e+00,8.881223e+00
252,BBMCO,805,30,CM2COGSP,2025-05-01,2.671434e+05,2.442255e+05
262,BBMCO,902,80,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
278,BBMCO,A32,84,CM2COGSP,2025-05-01,1.507881e+05,1.356636e+05
288,BBMCO,A33,86,CM2COGSP,2025-05-01,7.965055e+03,1.249762e+04
298,BBMCO,A34,85,CM2COGSP,2025-05-01,2.028763e+05,2.772709e+05
308,BBMCO,A35,87,CM2COGSP,2025-05-01,1.312725e+05,1.278019e+05
318,BBMCO,A45,80,CM2COGSP,2025-05-01,7.168183e+03,5.959533e+03
328,BBMCO,A45,81,CM2COGSP,2025-05-01,9.288215e+03,-2.819101e+03
338,BBMCO,A45,89,CM2COGSP,2025-05-01,1.674047e+04,1.363300e+04
358,BBMCO,CDK,03,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
368,BBMCO,CDK,12,CM2COGSP,2025-05-01,-1.289919e+02,8.633349e+03
378,BBMCO,CEK,30,CM2COGSP,2025-05-01,2.543338e+02,6.306172e+02
388,BBMCO,CEK,35,CM2COGSP,2025-05-01,0.000000e+00,5.765052e+01
398,BBMCO,M06,30,CM2COGSP,2025-05-01,0.000000e+00,1.432762e+04
408,BBMCO,M06,31,CM2COGSP,2025-05-01,1.454440e+05,1.217844e+05
430,BBMCO,M06,38,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
440,BBMCO,M07,30,CM2COGSP,2025-05-01,-6.645182e+02,2.572918e+03
450,BBMCO,M07,33,CM2COGSP,2025-05-01,3.585572e+05,3.982029e+05
460,BBMCO,M08,33,CM2COGSP,2025-05-01,4.150507e+05,2.756165e+05

In [370]:
df_rentabilidad['Compania'].drop_duplicates()

0      BBMCO
468    BBMEC
Name: Compania, dtype: object

In [371]:
# df_recaudo_otras_companias.rename(columns={'Compania': 'Division'})

In [372]:
# df_area_calculo_sba[df_area_calculo_sba['TipoEmpleado'] == 'GD']

In [373]:
# area_calculo_sba_completo_gd.copy()

In [374]:
area_calculo_sba_completo_gd_copy = area_calculo_sba_completo_gd.copy()
area_calculo_sba_completo_gd_copy['ClaseRentabilidad'] = 'CM2COGSP'
area_calculo_sba_completo_gd_copy

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,ClaseRentabilidad
29,1,1,AE,001,,GD,CM2COGSP
30,1,1,AE,003,,GD,CM2COGSP
31,1,1,AE,005,,GD,CM2COGSP
32,1,1,AE,006,,GD,CM2COGSP
33,1,1,AE,801,,GD,CM2COGSP
...,...,...,...,...,...,...,...
50,3,1,BA,A34,85,GD,CM2COGSP
51,3,1,BA,A35,87,GD,CM2COGSP
52,3,1,BA,A45,80,GD,CM2COGSP
53,3,1,BA,A45,81,GD,CM2COGSP
54,3,1,BA,A45,89,GD,CM2COGSP

In [375]:
df_parrillas[df_parrillas['Variable'] == 'RentabilidadDivisionCM2COGsSub']

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
65,5016692,RentabilidadDivisionCM2COGsSub,5016692_1,0.2,1,RentabilidadDivisionCM2COGsSub,Hospital Care
605,5041257,RentabilidadDivisionCM2COGsSub,5041257_1,0.2,1,RentabilidadDivisionCM2COGsSub,Aesculap
813,6474959,RentabilidadDivisionCM2COGsSub,6474959_1,0.2,1,RentabilidadDivisionCM2COGsSub,Aesculap
972,5004470,RentabilidadDivisionCM2COGsSub,5004470_1,0.2,1,RentabilidadDivisionCM2COGsSub,Hospital Care
1656,5036358,RentabilidadDivisionCM2COGsSub,5036358_1,0.2,1,RentabilidadDivisionCM2COGsSub,Avitum

In [376]:
main = pd.merge(
    left=area_calculo_sba_completo_gd_copy.copy(),
    right=df_rentabilidad[df_rentabilidad['ClaseRentabilidad'] == 'CM2COGSP'].drop(columns=['Compania']),
    on=['GrupoProducto', 'ClaseRentabilidad', 'SBA'],
    how = 'right'
)
main

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,ClaseRentabilidad,Fecha,Real,Presupuesto
0,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-03-01,246661.238307,261985.490606
1,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-04-01,310594.903202,357252.941735
2,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-05-01,335958.391518,452520.392865
3,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-06-01,405351.002087,547787.843994
4,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-07-01,531852.769026,643055.295124
...,...,...,...,...,...,...,...,...,...,...
453,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-08-01,638711.544725,468923.481211
454,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-09-01,711574.758669,527065.792935
455,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-10-01,786359.539517,585896.135960
456,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-11-01,863205.316850,651784.215066
457,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-12-01,924363.305449,715951.669169

In [377]:
main[main['Fecha'] == '2025-05-01']

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,ClaseRentabilidad,Fecha,Real,Presupuesto
2,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-05-01,3.359584e+05,4.525204e+05
12,1.0,1.0,AE,001,31,GD,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
22,1.0,1.0,AE,001,32,GD,CM2COGSP,2025-05-01,1.602219e+04,3.498639e+02
32,1.0,1.0,AE,001,33,GD,CM2COGSP,2025-05-01,3.932781e+03,2.591228e+02
42,1.0,1.0,AE,003,35,GD,CM2COGSP,2025-05-01,4.564380e+05,3.144168e+05
52,1.0,1.0,AE,005,33,GD,CM2COGSP,2025-05-01,5.494462e+03,2.244651e+04
62,1.0,1.0,AE,005,35,GD,CM2COGSP,2025-05-01,2.099242e+03,3.747284e+03
72,1.0,1.0,AE,006,36,GD,CM2COGSP,2025-05-01,2.907164e+04,4.537064e+04
82,2.0,1.0,HC,610,01,GD,CM2COGSP,2025-05-01,1.079931e+05,8.303646e+04
92,2.0,1.0,HC,610,02,GD,CM2COGSP,2025-05-01,7.196114e+05,5.839697e+05
102,2.0,1.0,HC,620,13,GD,CM2COGSP,2025-05-01,1.859375e+06,2.055520e+06
112,2.0,1.0,HC,620,15,GD,CM2COGSP,2025-05-01,1.675980e+06,1.401358e+06
122,2.0,1.0,HC,620,16,GD,CM2COGSP,2025-05-01,3.323428e+05,2.953253e+05
132,2.0,1.0,HC,620,36,GD,CM2COGSP,2025-05-01,9.650457e+05,9.314914e+05
142,NaN,NaN,NaN,620,89,NaN,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
152,2.0,1.0,HC,630,03,GD,CM2COGSP,2025-05-01,6.991161e+03,7.171548e+03
162,2.0,1.0,HC,630,08,GD,CM2COGSP,2025-05-01,7.292850e+05,6.492449e+05
172,2.0,1.0,HC,630,12,GD,CM2COGSP,2025-05-01,6.520578e+05,1.346282e+06
182,2.0,1.0,HC,640,03,GD,CM2COGSP,2025-05-01,8.043552e+03,6.207877e+03
192,3.0,1.0,BA,660,80,GD,CM2COGSP,2025-05-01,1.296374e+03,5.329599e+02
202,3.0,1.0,BA,660,81,GD,CM2COGSP,2025-05-01,4.883407e+03,-4.089887e+02
212,2.0,1.0,HC,680,03,GD,CM2COGSP,2025-05-01,3.539412e+05,3.192126e+05
222,1.0,1.0,AE,801,30,GD,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
232,1.0,1.0,AE,801,32,GD,CM2COGSP,2025-05-01,1.432506e+05,2.545890e+05
242,1.0,1.0,AE,801,33,GD,CM2COGSP,2025-05-01,8.323564e+00,8.881223e+00
252,1.0,1.0,AE,805,30,GD,CM2COGSP,2025-05-01,2.671434e+05,2.442255e+05
262,NaN,NaN,NaN,902,80,NaN,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
278,3.0,1.0,BA,A32,84,GD,CM2COGSP,2025-05-01,1.507881e+05,1.356636e+05
288,3.0,1.0,BA,A33,86,GD,CM2COGSP,2025-05-01,7.965055e+03,1.249762e+04
298,3.0,1.0,BA,A34,85,GD,CM2COGSP,2025-05-01,2.028763e+05,2.772709e+05
308,3.0,1.0,BA,A35,87,GD,CM2COGSP,2025-05-01,1.312725e+05,1.278019e+05
318,3.0,1.0,BA,A45,80,GD,CM2COGSP,2025-05-01,7.168183e+03,5.959533e+03
328,3.0,1.0,BA,A45,81,GD,CM2COGSP,2025-05-01,9.288215e+03,-2.819101e+03
338,3.0,1.0,BA,A45,89,GD,CM2COGSP,2025-05-01,1.674047e+04,1.363300e+04
348,2.0,1.0,HC,CDK,03,GD,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
358,2.0,1.0,HC,CDK,12,GD,CM2COGSP,2025-05-01,-1.289919e+02,8.633349e+03
368,1.0,1.0,AE,CEK,30,GD,CM2COGSP,2025-05-01,2.543338e+02,6.306172e+02
378,1.0,1.0,AE,CEK,35,GD,CM2COGSP,2025-05-01,0.000000e+00,5.765052e+01
388,1.0,1.0,AE,M06,30,GD,CM2COGSP,2025-05-01,0.000000e+00,1.432762e+04
398,1.0,1.0,AE,M06,31,GD,CM2COGSP,2025-05-01,1.454440e+05,1.217844e+05
420,1.0,1.0,AE,M06,38,GD,CM2COGSP,2025-05-01,0.000000e+00,0.000000e+00
430,1.0,1.0,AE,M07,30,GD,CM2COGSP,2025-05-01,-6.645182e+02,2.572918e+03
440,1.0,1.0,AE,M07,33,GD,CM2COGSP,2025-05-01,3.585572e+05,3.982029e+05
450,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-05-01,4.150507e+05,2.756165e+05

In [378]:
main[main['Fecha'] == '2025-05-01']['Real'].sum()

10120876.627262428

In [379]:
main[main['Fecha'] == '2025-05-01']['Presupuesto'].sum()

10408711.476886513

In [380]:
# main = pd.merge(
#     left=area_calculo_sba_completo_gd.copy().drop(columns=['SBA']),
#     right=df_rentabilidad.copy().drop(columns=['ClaseRentabilidad', 'Compania']),
#     on=['GrupoProducto'],
#     how = 'left'
# )
# main

In [381]:
main = main.merge(
    df_empleados,
    how='left'
)
main

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,ClaseRentabilidad,Fecha,Real,Presupuesto,CodigoEmpleado,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro
0,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-03-01,246661.238307,261985.490606,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT
1,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-04-01,310594.903202,357252.941735,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT
2,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-05-01,335958.391518,452520.392865,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT
3,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-06-01,405351.002087,547787.843994,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT
4,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-07-01,531852.769026,643055.295124,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-08-01,638711.544725,468923.481211,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT
454,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-09-01,711574.758669,527065.792935,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT
455,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-10-01,786359.539517,585896.135960,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT
456,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-11-01,863205.316850,651784.215066,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT
457,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-12-01,924363.305449,715951.669169,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT

In [382]:
main['CodigoEmpleado'].fillna(0, inplace=True)
main['Consecutivo'].fillna(0, inplace=True)

main['Contexto'] = main['CodigoEmpleado'].str.lower() + '_'+ main['Consecutivo'].astype(int).astype('str')
main

C:\Users\HP\AppData\Local\Temp\ipykernel_30012\2419955517.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['CodigoEmpleado'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_30012\2419955517.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  main['Consecutivo'].fillna(0, inplace=True)

,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,ClaseRentabilidad,Fecha,Real,Presupuesto,CodigoEmpleado,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,Contexto
0,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-03-01,246661.238307,261985.490606,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
1,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-04-01,310594.903202,357252.941735,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
2,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-05-01,335958.391518,452520.392865,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
3,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-06-01,405351.002087,547787.843994,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
4,1.0,1.0,AE,001,30,GD,CM2COGSP,2025-07-01,531852.769026,643055.295124,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-08-01,638711.544725,468923.481211,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
454,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-09-01,711574.758669,527065.792935,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
455,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-10-01,786359.539517,585896.135960,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
456,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-11-01,863205.316850,651784.215066,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
457,1.0,1.0,AE,M08,33,GD,CM2COGSP,2025-12-01,924363.305449,715951.669169,5041257,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1

In [383]:
main_centro_costo = pd.merge(
    df_empleados_centros_costos,
    main,
    on=['CodigoEmpleado'],
    how='right'
)
main_centro_costo

,CodigoEmpleado,CodigoCentroCosto,PorcentajeAsignacion,AreaCalculo,Consecutivo,Division,GrupoProducto,SBA,TipoEmpleado,ClaseRentabilidad,...,Real,Presupuesto,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro,Contexto
0,5041257,323010165,0.33,1.0,1.0,AE,001,30,GD,CM2COGSP,...,246661.238307,261985.490606,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
1,5041257,323010170,0.34,1.0,1.0,AE,001,30,GD,CM2COGSP,...,246661.238307,261985.490606,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
2,5041257,323010175,0.33,1.0,1.0,AE,001,30,GD,CM2COGSP,...,246661.238307,261985.490606,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
3,5041257,323010165,0.33,1.0,1.0,AE,001,30,GD,CM2COGSP,...,310594.903202,357252.941735,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
4,5041257,323010170,0.34,1.0,1.0,AE,001,30,GD,CM2COGSP,...,310594.903202,357252.941735,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1317,5041257,323010170,0.34,1.0,1.0,AE,M08,33,GD,CM2COGSP,...,863205.316850,651784.215066,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
1318,5041257,323010175,0.33,1.0,1.0,AE,M08,33,GD,CM2COGSP,...,863205.316850,651784.215066,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
1319,5041257,323010165,0.33,1.0,1.0,AE,M08,33,GD,CM2COGSP,...,924363.305449,715951.669169,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
1320,5041257,323010170,0.34,1.0,1.0,AE,M08,33,GD,CM2COGSP,...,924363.305449,715951.669169,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1
1321,5041257,323010175,0.33,1.0,1.0,AE,M08,33,GD,CM2COGSP,...,924363.305449,715951.669169,29116947,karina.fuenmayor@bbraun.com,Karina,Fuenmayor,6000000.0,2024-05-01,NaT,5041257_1

In [384]:
main_centro_costo['Consecutivo'] = main_centro_costo['Consecutivo'].astype(int).astype('str')

In [385]:
main[main['Fecha'] == '2024-05-01']['Real'].sum()

0.0

In [386]:
rentabilidad_division_cm2cogs_sub_centro_costo = dataframe_loader.f_calculo_centro_costo_variable(main_centro_costo, 'RentabilidadDivisionCM2COGsSub')
rentabilidad_division_cm2cogs_sub_centro_costo

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\shared_functions.py:777: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  ['Contexto', 'Fecha', 'GrupoProducto', 'Division', 'CodigoCentroCosto'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,5016692_1,2025-03-01,610,HC,323015065,3.519094e+05,3.730089e+05,RentabilidadDivisionCM2COGsSub
1,5016692_1,2025-03-01,610,HC,323015070,3.519094e+05,3.730089e+05,RentabilidadDivisionCM2COGsSub
2,5016692_1,2025-03-01,610,HC,323015075,3.519094e+05,3.730089e+05,RentabilidadDivisionCM2COGsSub
3,5016692_1,2025-03-01,620,HC,323015065,2.543467e+06,2.749125e+06,RentabilidadDivisionCM2COGsSub
4,5016692_1,2025-03-01,620,HC,323015070,2.543467e+06,2.749125e+06,RentabilidadDivisionCM2COGsSub
...,...,...,...,...,...,...,...,...
655,5041257_1,2025-12-01,M07,AE,323010170,5.445153e+06,6.304113e+06,RentabilidadDivisionCM2COGsSub
656,5041257_1,2025-12-01,M07,AE,323010175,5.445153e+06,6.304113e+06,RentabilidadDivisionCM2COGsSub
657,5041257_1,2025-12-01,M08,AE,323010165,5.947786e+06,4.335607e+06,RentabilidadDivisionCM2COGsSub
658,5041257_1,2025-12-01,M08,AE,323010170,5.947786e+06,4.335607e+06,RentabilidadDivisionCM2COGsSub
659,5041257_1,2025-12-01,M08,AE,323010175,5.947786e+06,4.335607e+06,RentabilidadDivisionCM2COGsSub

In [387]:
# main['Contexto'] = main['Division']
main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
# main['Real'] = main.groupby(['Contexto'])['Real'].transform(pd.Series.cumsum)
# main['Presupuesto'] = main.groupby(['Contexto'])['Presupuesto'].transform(pd.Series.cumsum)
main

C:\Users\HP\AppData\Local\Temp\ipykernel_30012\3120034045.py:2: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  main = main.groupby(['Contexto', 'Fecha'], as_index=False)[['Real', 'Presupuesto']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

     Contexto      Fecha          Real   Presupuesto
0   5016692_1 2025-03-01  3.694599e+06  4.478371e+06
1   5016692_1 2025-04-01  5.342992e+06  5.876419e+06
2   5016692_1 2025-05-01  7.410538e+06  7.687453e+06
3   5016692_1 2025-06-01  9.102684e+06  9.532391e+06
4   5016692_1 2025-07-01  1.081179e+07  1.129142e+07
5   5016692_1 2025-08-01  1.213924e+07  1.313200e+07
6   5016692_1 2025-09-01  1.379006e+07  1.497552e+07
7   5016692_1 2025-10-01  1.547491e+07  1.682212e+07
8   5016692_1 2025-11-01  1.757710e+07  1.893858e+07
9   5016692_1 2025-12-01  2.004174e+07  2.133124e+07
10  5036358_1 2025-03-01  2.943177e+05  3.204922e+05
11  5036358_1 2025-04-01  3.920898e+05  4.374353e+05
12  5036358_1 2025-05-01  5.322785e+05  5.701314e+05
13  5036358_1 2025-06-01  7.244535e+05  7.102922e+05
14  5036358_1 2025-07-01  8.594523e+05  8.544500e+05
15  5036358_1 2025-08-01  1.010269e+06  9.989054e+05
16  5036358_1 2025-09-01  1.124285e+06  1.147852e+06
17  5036358_1 2025-10-01  1.281932e+06  1.319937e+06
18  5036358_1 2025-11-01  1.487801e+06  1.476080e+06
19  5036358_1 2025-12-01  1.833774e+06  1.621003e+06
20  5041257_1 2025-03-01  1.396697e+06  1.252296e+06
21  5041257_1 2025-04-01  1.753945e+06  1.682041e+06
22  5041257_1 2025-05-01  2.178061e+06  2.151127e+06
23  5041257_1 2025-06-01  2.643253e+06  2.627904e+06
24  5041257_1 2025-07-01  3.243239e+06  3.251168e+06
25  5041257_1 2025-08-01  4.217050e+06  3.759755e+06
26  5041257_1 2025-09-01  4.786708e+06  4.259937e+06
27  5041257_1 2025-10-01  5.463198e+06  4.753418e+06
28  5041257_1 2025-11-01  5.987910e+06  5.297300e+06
29  5041257_1 2025-12-01  7.144604e+06  5.828748e+06

In [388]:
main['PorcentajeCumplimiento'] = main['Real']/main['Presupuesto']
main['PorcentajeCumplimiento'] = main['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
main['Variable'] = 'RentabilidadDivisionCM2COGsSub'

# main['Contexto'] = main['Division']
main = main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

rentabilidad_division_cm2_cogs_sub = main.copy()

main = None
rentabilidad_division_cm2_cogs_sub

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5016692_1,RentabilidadDivisionCM2COGsSub,2025-03-01,3.694599e+06,4.478371e+06,0.82
1,5016692_1,RentabilidadDivisionCM2COGsSub,2025-04-01,5.342992e+06,5.876419e+06,0.91
2,5016692_1,RentabilidadDivisionCM2COGsSub,2025-05-01,7.410538e+06,7.687453e+06,0.96
3,5016692_1,RentabilidadDivisionCM2COGsSub,2025-06-01,9.102684e+06,9.532391e+06,0.95
4,5016692_1,RentabilidadDivisionCM2COGsSub,2025-07-01,1.081179e+07,1.129142e+07,0.96
5,5016692_1,RentabilidadDivisionCM2COGsSub,2025-08-01,1.213924e+07,1.313200e+07,0.92
6,5016692_1,RentabilidadDivisionCM2COGsSub,2025-09-01,1.379006e+07,1.497552e+07,0.92
7,5016692_1,RentabilidadDivisionCM2COGsSub,2025-10-01,1.547491e+07,1.682212e+07,0.92
8,5016692_1,RentabilidadDivisionCM2COGsSub,2025-11-01,1.757710e+07,1.893858e+07,0.93
9,5016692_1,RentabilidadDivisionCM2COGsSub,2025-12-01,2.004174e+07,2.133124e+07,0.94
10,5036358_1,RentabilidadDivisionCM2COGsSub,2025-03-01,2.943177e+05,3.204922e+05,0.92
11,5036358_1,RentabilidadDivisionCM2COGsSub,2025-04-01,3.920898e+05,4.374353e+05,0.90
12,5036358_1,RentabilidadDivisionCM2COGsSub,2025-05-01,5.322785e+05,5.701314e+05,0.93
13,5036358_1,RentabilidadDivisionCM2COGsSub,2025-06-01,7.244535e+05,7.102922e+05,1.02
14,5036358_1,RentabilidadDivisionCM2COGsSub,2025-07-01,8.594523e+05,8.544500e+05,1.01
15,5036358_1,RentabilidadDivisionCM2COGsSub,2025-08-01,1.010269e+06,9.989054e+05,1.01
16,5036358_1,RentabilidadDivisionCM2COGsSub,2025-09-01,1.124285e+06,1.147852e+06,0.98
17,5036358_1,RentabilidadDivisionCM2COGsSub,2025-10-01,1.281932e+06,1.319937e+06,0.97
18,5036358_1,RentabilidadDivisionCM2COGsSub,2025-11-01,1.487801e+06,1.476080e+06,1.01
19,5036358_1,RentabilidadDivisionCM2COGsSub,2025-12-01,1.833774e+06,1.621003e+06,1.13
20,5041257_1,RentabilidadDivisionCM2COGsSub,2025-03-01,1.396697e+06,1.252296e+06,1.12
21,5041257_1,RentabilidadDivisionCM2COGsSub,2025-04-01,1.753945e+06,1.682041e+06,1.04
22,5041257_1,RentabilidadDivisionCM2COGsSub,2025-05-01,2.178061e+06,2.151127e+06,1.01
23,5041257_1,RentabilidadDivisionCM2COGsSub,2025-06-01,2.643253e+06,2.627904e+06,1.01
24,5041257_1,RentabilidadDivisionCM2COGsSub,2025-07-01,3.243239e+06,3.251168e+06,1.00
25,5041257_1,RentabilidadDivisionCM2COGsSub,2025-08-01,4.217050e+06,3.759755e+06,1.12
26,5041257_1,RentabilidadDivisionCM2COGsSub,2025-09-01,4.786708e+06,4.259937e+06,1.12
27,5041257_1,RentabilidadDivisionCM2COGsSub,2025-10-01,5.463198e+06,4.753418e+06,1.15
28,5041257_1,RentabilidadDivisionCM2COGsSub,2025-11-01,5.987910e+06,5.297300e+06,1.13
29,5041257_1,RentabilidadDivisionCM2COGsSub,2025-12-01,7.144604e+06,5.828748e+06,1.23

In [389]:
rentabilidad_division_cm2_cogs_sub[rentabilidad_division_cm2_cogs_sub['Fecha'] == '2023-12-01']

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

In [390]:
df_parrillas[df_parrillas['Variable'] =='RentabilidadDivisionCM2COGsSub']

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
65,5016692,RentabilidadDivisionCM2COGsSub,5016692_1,0.2,1,RentabilidadDivisionCM2COGsSub,Hospital Care
605,5041257,RentabilidadDivisionCM2COGsSub,5041257_1,0.2,1,RentabilidadDivisionCM2COGsSub,Aesculap
813,6474959,RentabilidadDivisionCM2COGsSub,6474959_1,0.2,1,RentabilidadDivisionCM2COGsSub,Aesculap
972,5004470,RentabilidadDivisionCM2COGsSub,5004470_1,0.2,1,RentabilidadDivisionCM2COGsSub,Hospital Care
1656,5036358,RentabilidadDivisionCM2COGsSub,5036358_1,0.2,1,RentabilidadDivisionCM2COGsSub,Avitum

In [391]:
df_empleados[df_empleados['CodigoEmpleado'] == '6474959']

Empty DataFrame
Columns: [TipoEmpleado, CodigoEmpleado, Identificacion, CorreoElectronico, Nombre, Apellidos, SalarioVariable, FechaIngreso, FechaRetiro, AreaCalculo]
Index: []

In [392]:
df_empleados[df_empleados['CodigoEmpleado'] == '5004470']

Empty DataFrame
Columns: [TipoEmpleado, CodigoEmpleado, Identificacion, CorreoElectronico, Nombre, Apellidos, SalarioVariable, FechaIngreso, FechaRetiro, AreaCalculo]
Index: []

In [393]:
# rentabilidad_division_cm2cogs_gd = pd.merge(
#     left=df_rentabilidad[(df_rentabilidad['ClaseRentabilidad']=='CM2COGSP')],
#     right=area_calculo_sba_completo_gd,
#     on=['GrupoProducto', 'SBA'],
#     how='left'
# )
# rentabilidad_division_cm2_cogs_sub = rentabilidad_division_cm2cogs_gd.groupby(
#     ['Division', 'Consecutivo', 'Fecha'],
#     as_index=False
# ).agg({'Real': 'sum', 'Presupuesto': 'sum'})
# rentabilidad_division_cm2_cogs_sub['PorcentajeCumplimiento'] = rentabilidad_division_cm2_cogs_sub['Real']/cumplimiento_rentabilidad_cm3_grupo_clientes_sub['Presupuesto']
# rentabilidad_division_cm2_cogs_sub['PorcentajeCumplimiento'] = rentabilidad_division_cm2_cogs_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
# rentabilidad_division_cm2_cogs_sub

In [394]:
# rentabilidad_division_cm2_cogs_sub['Contexto'] = 'gd_' + rentabilidad_division_cm2_cogs_sub['Division'].astype('str').str.cat(rentabilidad_division_cm2_cogs_sub['Consecutivo'].astype('str'), sep="_")
# rentabilidad_division_cm2_cogs_sub['Variable'] = 'RentabilidadDivisionCM2COGsSub'
# rentabilidad_division_cm2_cogs_sub = rentabilidad_division_cm2_cogs_sub[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

# rentabilidad_division_cm2_cogs_sub

## 43 EBITCOGSPais

In [395]:
df_parrillas[df_parrillas['Contexto'] == 'EBITCOGSP']

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
13,5016740,EBITCOGSPais,EBITCOGSP,0.4,0,EBITCOGSPais,NaN
19,5045060,EBITCOGSPais,EBITCOGSP,0.2,0,EBITCOGSPais,NaN
63,5016692,EBITCOGSPais,EBITCOGSP,0.2,0,EBITCOGSPais,NaN
83,70010670,EBITCOGSPais,EBITCOGSP,0.4,0,EBITCOGSPais,NaN
93,1019004590,EBITCOGSPais,EBITCOGSP,0.4,0,EBITCOGSPais,NaN
...,...,...,...,...,...,...,...
1617,5016755,EBITCOGSPais,EBITCOGSP,0.4,0,EBITCOGSPais,NaN
1637,5004302,EBITCOGSPais,EBITCOGSP,0.2,0,EBITCOGSPais,NaN
1644,70002068,EBITCOGSPais,EBITCOGSP,0.2,0,EBITCOGSPais,NaN
1654,5036358,EBITCOGSPais,EBITCOGSP,0.2,0,EBITCOGSPais,NaN
1695,5016700,EBITCOGSPais,EBITCOGSP,0.4,0,EBITCOGSPais,NaN

In [491]:
df_rentabilidad

,Compania,GrupoProducto,SBA,ClaseRentabilidad,Fecha,Real,Presupuesto
0,BBMCO,001,30,CM2COGSP,2025-03-01,2.466612e+05,2.619855e+05
1,BBMCO,001,30,CM2COGSP,2025-04-01,3.105949e+05,3.572529e+05
2,BBMCO,001,30,CM2COGSP,2025-05-01,3.359584e+05,4.525204e+05
3,BBMCO,001,30,CM2COGSP,2025-06-01,4.053510e+05,5.477878e+05
4,BBMCO,001,30,CM2COGSP,2025-07-01,5.318528e+05,6.430553e+05
...,...,...,...,...,...,...,...
473,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-08-01,3.049280e+06,2.347009e+06
474,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-09-01,2.453488e+06,2.763416e+06
475,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-10-01,3.299142e+06,3.188239e+06
476,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-11-01,3.819836e+06,3.654547e+06
477,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-12-01,3.819836e+06,3.654547e+06

In [396]:
ebit_cogs_pais = df_rentabilidad[(df_rentabilidad['Compania']=='BBMCO')&(df_rentabilidad['ClaseRentabilidad']=='EBITCOGSP')]

ebit_cogs_pais = ebit_cogs_pais.groupby(
    ['Fecha'],
    as_index=False
).agg({'Real': 'sum', 'Presupuesto': 'sum'})

# cumplimiento_rentabilidad_cm5_nivel_pais['Presupuesto'] = cumplimiento_rentabilidad_cm5_nivel_pais['Presupuesto'].transform(pd.Series.cumsum)
# cumplimiento_rentabilidad_cm5_nivel_pais['Real'] = cumplimiento_rentabilidad_cm5_nivel_pais['Real'].transform(pd.Series.cumsum)

ebit_cogs_pais['PorcentajeCumplimiento'] = ebit_cogs_pais['Real'] / ebit_cogs_pais['Presupuesto']
ebit_cogs_pais['PorcentajeCumplimiento'] = ebit_cogs_pais['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))
ebit_cogs_pais['Contexto'] = 'EBITCOGSP'
ebit_cogs_pais['Variable'] = 'EBITCOGSPais'

ebit_cogs_pais.head()

,Fecha,Real,Presupuesto,PorcentajeCumplimiento,Contexto,Variable
0,2025-03-01,1.964337e+06,2.648294e+06,0.74,EBITCOGSP,EBITCOGSPais
1,2025-04-01,2.688269e+06,2.555665e+06,1.05,EBITCOGSP,EBITCOGSPais
2,2025-05-01,4.082599e+06,3.608436e+06,1.13,EBITCOGSP,EBITCOGSPais
3,2025-06-01,5.084537e+06,4.726031e+06,1.08,EBITCOGSP,EBITCOGSPais
4,2025-07-01,6.237653e+06,5.988958e+06,1.04,EBITCOGSP,EBITCOGSPais

## 44 EBITCOGSPaisSUB

In [398]:
area_calculo_sba_completo[area_calculo_sba_completo['Division'] == 'BBMCO']

     AreaCalculo  Consecutivo Division GrupoProducto    SBA TipoEmpleado
0              1            1    BBMCO         BBMCO  BBMCO           AD
1              2            1    BBMCO         BBMCO  BBMCO           AD
2              3            1    BBMCO         BBMCO  BBMCO           AD
3              4            1    BBMCO         BBMCO  BBMCO           AD
4              1            1    BBMCO         BBMCO  BBMCO          AD1
5              2            1    BBMCO         BBMCO  BBMCO          AD1
6              3            1    BBMCO         BBMCO  BBMCO          AD1
7              4            1    BBMCO         BBMCO  BBMCO          AD1
8              5            1    BBMCO         BBMCO  BBMCO          AD1
9             10            1    BBMCO         BBMCO  BBMCO          AD1
10            11            1    BBMCO         BBMCO  BBMCO          AD1
13             1            1    BBMCO         BBMCO  BBMCO          AD3
14             2            1    BBMCO         BBMCO  BBMCO          AD3
15             3            1    BBMCO         BBMCO  BBMCO          AD3
16             1            1    BBMCO         BBMCO  BBMCO          AD4
18             2            1    BBMCO         BBMCO  BBMCO          AD4
19             1            1    BBMCO         BBMCO  BBMCO          AD5
230            7            1    BBMCO         BBMCO  BBMCO          MK1
232            8            1    BBMCO         BBMCO  BBMCO          MK1
234            9            1    BBMCO                               MK1

In [399]:
area_calculo_sba_completo[area_calculo_sba_completo['Division'] == 'BBMEC']

     AreaCalculo  Consecutivo Division GrupoProducto    SBA TipoEmpleado
17             1            2    BBMEC         BBMEC  BBMEC          AD4
231            7            2    BBMEC         BBMEC  BBMEC          MK1
233            8            2    BBMEC         BBMEC  BBMEC          MK1
235            9            2    BBMEC         BBMEC  BBMEC          MK1

In [400]:
df_rentabilidad[df_rentabilidad['ClaseRentabilidad'] == 'EBITCOGSP']

,Compania,GrupoProducto,SBA,ClaseRentabilidad,Fecha,Real,Presupuesto
346,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-03-01,1.964337e+06,2.648294e+06
347,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-04-01,2.688269e+06,2.555665e+06
348,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-05-01,4.082599e+06,3.608436e+06
349,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-06-01,5.084537e+06,4.726031e+06
350,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-07-01,6.237653e+06,5.988958e+06
351,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-08-01,8.939530e+06,7.164954e+06
352,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-09-01,7.895472e+06,8.311383e+06
353,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-10-01,8.891097e+06,9.673296e+06
354,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-11-01,1.053161e+07,1.111725e+07
355,BBMCO,BBMCO,BBMCO,EBITCOGSP,2025-12-01,1.053161e+07,1.277603e+07
468,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-03-01,1.414337e+06,3.509360e+05
469,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-04-01,1.776928e+06,5.663647e+05
470,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-05-01,2.101947e+06,7.823852e+05
471,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-06-01,2.435536e+06,1.486792e+06
472,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-07-01,2.556678e+06,2.568360e+06
473,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-08-01,3.049280e+06,2.347009e+06
474,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-09-01,2.453488e+06,2.763416e+06
475,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-10-01,3.299142e+06,3.188239e+06
476,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-11-01,3.819836e+06,3.654547e+06
477,BBMEC,BBMEC,BBMEC,EBITCOGSP,2025-12-01,3.819836e+06,3.654547e+06

In [382]:
ebit_cogs_pais_sub = df_rentabilidad[df_rentabilidad['ClaseRentabilidad'] == 'EBITCOGSP'].rename(columns={'Compania':'Division'}).merge(
    area_calculo_sba_completo.drop(columns=['GrupoProducto', 'SBA']),
    on=['Division']
)
ebit_cogs_pais_sub.drop(columns='ClaseRentabilidad', inplace=True)
ebit_cogs_pais_sub

,Division,GrupoProducto,SBA,Fecha,Real,Presupuesto,AreaCalculo,Consecutivo,TipoEmpleado
0,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,1,1,AD
1,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD
2,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,3,1,AD
3,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,4,1,AD
4,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,1,1,AD1
...,...,...,...,...,...,...,...,...,...
235,BBMEC,BBMEC,BBMEC,2025-11-01,3.819836e+06,3.654547e+06,9,2,MK1
236,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,1,2,AD4
237,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,7,2,MK1
238,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,8,2,MK1
239,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,9,2,MK1

In [383]:
ebit_cogs_pais_sub = ebit_cogs_pais_sub.merge(
        df_parrillas[df_parrillas['Variable'] == 'EBITCOGSPaisSUB'].merge(
        df_empleados
    )
)
ebit_cogs_pais_sub

,Division,GrupoProducto,SBA,Fecha,Real,Presupuesto,AreaCalculo,Consecutivo,TipoEmpleado,CodigoEmpleado,...,Porcentaje,Nombre variable,Nombre consecutivo,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro
0,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD,5016686,...,0.4,EBITCOGSPaisSUB,BBMCO,79641686,ricardo.benavides@bbraun.com,RICARDO,BENAVIDES,1000000.0,2018-06-01,NaT
1,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD,70038889,...,0.4,EBITCOGSPaisSUB,BBMCO,52282753,sandra.canon@bbraun.com,SANDRA JANNETH,CAÑON HERNANDEZ,1000000.0,2025-05-01,NaT
2,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD,5003668,...,0.4,EBITCOGSPaisSUB,BBMCO,52057371,nubia.jimenez@bbraun.com,NUBIA YANNETH,JIMENEZ MOLINA,1083000.0,2004-02-23,NaT
3,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD,5043078,...,0.4,EBITCOGSPaisSUB,BBMCO,1018451704,diana.mateus@bbraun.com,Diana,Mateus,1000000.0,2024-05-01,NaT
4,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD,70014725,...,0.4,EBITCOGSPaisSUB,BBMCO,1019140853,ana.silva3@bbraun.com,Ana,Silva Bermudez,1000000.0,2024-07-01,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,8,2,MK1,5016776,...,0.2,EBITCOGSPaisSUB,BBMEC,1121863542,daniela.coral@bbraun.com,DANIELA,CORAL,2208000.0,2019-07-01,NaT
326,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,8,2,MK1,70055714,...,0.2,EBITCOGSPaisSUB,BBMEC,1031156262,lina.galindo@bbraun.com,LINA MARIA,GALINDO CORTES,1600000.0,2026-03-02,NaT
327,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,9,2,MK1,52417387,...,0.2,EBITCOGSPaisSUB,BBMEC,52417387,juliana.ayala@bbraun.com,JULIANA,AYALA ENCISO,7000000.0,2025-12-01,NaT
328,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,9,2,MK1,94526955,...,0.2,EBITCOGSPaisSUB,BBMEC,94526955,juan.barajas@bbraun.com,JUAN FELIPE,BARAJAS LOPEZ,4900000.0,2025-06-01,NaT
329,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,9,2,MK1,70021302,...,0.2,EBITCOGSPaisSUB,BBMEC,1022428619,fernanda.gomez@bbraun.com,Maria Fernanda,Gomez,2000000.0,2024-01-01,NaT

In [388]:
ebit_cogs_pais_sub = ebit_cogs_pais_sub[ebit_cogs_pais_sub['Fecha'] >= ebit_cogs_pais_sub['FechaIngreso']]
ebit_cogs_pais_sub

,Division,GrupoProducto,SBA,Fecha,Real,Presupuesto,AreaCalculo,Consecutivo,TipoEmpleado,CodigoEmpleado,...,Porcentaje,Nombre variable,Nombre consecutivo,Identificacion,CorreoElectronico,Nombre,Apellidos,SalarioVariable,FechaIngreso,FechaRetiro
0,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD,5016686,...,0.4,EBITCOGSPaisSUB,BBMCO,79641686,ricardo.benavides@bbraun.com,RICARDO,BENAVIDES,1000000.0,2018-06-01,NaT
2,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD,5003668,...,0.4,EBITCOGSPaisSUB,BBMCO,52057371,nubia.jimenez@bbraun.com,NUBIA YANNETH,JIMENEZ MOLINA,1083000.0,2004-02-23,NaT
3,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD,5043078,...,0.4,EBITCOGSPaisSUB,BBMCO,1018451704,diana.mateus@bbraun.com,Diana,Mateus,1000000.0,2024-05-01,NaT
4,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD,70014725,...,0.4,EBITCOGSPaisSUB,BBMCO,1019140853,ana.silva3@bbraun.com,Ana,Silva Bermudez,1000000.0,2024-07-01,NaT
5,BBMCO,BBMCO,BBMCO,2025-03-01,1.964337e+06,2.648294e+06,2,1,AD1,5019930,...,0.4,EBITCOGSPaisSUB,BBMCO,30405433,mariacarolina.rave@bbraun.com,MARIA CAROLINA,RAVE LARA,1964000.0,2018-09-01,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,7,2,MK1,5016688,...,0.2,EBITCOGSPaisSUB,BBMEC,79758250,javier.ramos@bbraun.com,Javier,Ramos,2000000.0,2024-06-01,NaT
325,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,8,2,MK1,5016776,...,0.2,EBITCOGSPaisSUB,BBMEC,1121863542,daniela.coral@bbraun.com,DANIELA,CORAL,2208000.0,2019-07-01,NaT
327,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,9,2,MK1,52417387,...,0.2,EBITCOGSPaisSUB,BBMEC,52417387,juliana.ayala@bbraun.com,JULIANA,AYALA ENCISO,7000000.0,2025-12-01,NaT
328,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,9,2,MK1,94526955,...,0.2,EBITCOGSPaisSUB,BBMEC,94526955,juan.barajas@bbraun.com,JUAN FELIPE,BARAJAS LOPEZ,4900000.0,2025-06-01,NaT
329,BBMEC,BBMEC,BBMEC,2025-12-01,3.819836e+06,3.654547e+06,9,2,MK1,70021302,...,0.2,EBITCOGSPaisSUB,BBMEC,1022428619,fernanda.gomez@bbraun.com,Maria Fernanda,Gomez,2000000.0,2024-01-01,NaT

In [389]:
ebit_cogs_pais_sub['Variable'] = 'EBITCOGSPaisSUB'
### Cálculo de resultados cualitativos precargados

ebit_cogs_pais_sub['PorcentajeCumplimiento'] = ebit_cogs_pais_sub['Real'] / ebit_cogs_pais_sub['Presupuesto']
ebit_cogs_pais_sub['PorcentajeCumplimiento'] = ebit_cogs_pais_sub['PorcentajeCumplimiento'].apply(lambda x: round(x, 2))

# ebit_cogs_pais_sub = dataframe_loader.sobreescribir_resultados_cualitativos(
#     main=ebit_cogs_pais_sub,
#     variable='EBITCOGSPaisSUB',
#     columnas_extra=['TipoEmpleado', 'Consecutivo'],
#     columnas_extra_merge=['TipoEmpleado', 'Consecutivo'],
#     pre_merge_lambda=lambda x: x[x['TipoEmpleado'] == 'AD4']
# )
# ###

ebit_cogs_pais_sub['Consecutivo'] = ebit_cogs_pais_sub['Consecutivo'].astype(int).astype('str')
ebit_cogs_pais_sub['Contexto'] = ebit_cogs_pais_sub['CodigoEmpleado'] + '_'+ ebit_cogs_pais_sub['Consecutivo']

ebit_cogs_pais_sub = ebit_cogs_pais_sub[
    ['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento']]

ebit_cogs_pais_sub.head()

,Contexto,Variable,Fecha,Real,Presupuesto,PorcentajeCumplimiento
0,5016686_1,EBITCOGSPaisSUB,2025-03-01,1.964337e+06,2.648294e+06,0.74
2,5003668_1,EBITCOGSPaisSUB,2025-03-01,1.964337e+06,2.648294e+06,0.74
3,5043078_1,EBITCOGSPaisSUB,2025-03-01,1.964337e+06,2.648294e+06,0.74
4,70014725_1,EBITCOGSPaisSUB,2025-03-01,1.964337e+06,2.648294e+06,0.74
5,5019930_1,EBITCOGSPaisSUB,2025-03-01,1.964337e+06,2.648294e+06,0.74

In [404]:
ebit_cogs_pais_sub[ebit_cogs_pais_sub['Contexto'] == '1098612757_1' ]

Empty DataFrame
Columns: [Contexto, Variable, Fecha, Real, Presupuesto, PorcentajeCumplimiento]
Index: []

## Cálculo de Maestra de Resultados

In [405]:
maestra_resultados = pd.concat([
    cumplimiento_objetivos_cualitativos_por_empleado, # cumplimiento_cualitativos,
    cumplimiento_recaudo_por_zona, # cumplimiento_cobro_por_zona,
    cumplimiento_venta_individual,
    cumplimiento_venta_individual_sub,
    cumplimiento_recaudo_individual,
    cumplimiento_recaudo_individual_sub, # cumplimiento_cobro_empleado_consecutivo,
    cumplimiento_venta_por_area_calculo, # cumplimiento_venta_por_area_calculo,
    cumplimiento_venta_por_area_calculo_sub,
    cumplimiento_recaudo_por_area_calculo, # cumplimiento_cobro_por_area_calculo,
    cumplimiento_recaudo_por_area_calculo_sub,
    cumplimiento_recaudo_nivel_pais, # cumplimiento_cobro_pais,
    cumplimiento_venta_por_unidad_negocio_gu,
    cumplimiento_venta_por_unidad_negocio_gu_sub,
    cumplimiento_recaudo_por_unidad_negocio_gu, # cumplimiento_cobro_area_calculo_gu,
    cumplimiento_recaudo_por_unidad_negocio_gu_sub,
    cumplimiento_venta_por_unidad_negocio_mk,
    cumplimiento_venta_por_unidad_negocio_mk_sub,
    cumplimiento_recaudo_por_unidad_negocio_mk, # cumplimiento_cobro_area_calculo_mk,
    cumplimiento_recaudo_por_unidad_negocio_mk_sub, # cumplimiento_cobro_area_calculo_mk,
    cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu,
    cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu,
    cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk,
    cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk,
    cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_sub,
    cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu_sub,
    cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk_sub,
    cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk_sub,
    cumplimiento_recaudo_por_division, # cumplimiento_cobro_division,
    cumplimiento_recaudo_por_division_sub_mk, # cumplimiento_cobro_division_sub,
    cumplimiento_recaudo_otras_companias_mk, # cumplimiento_cobro_compañias_mk,
    cumplimiento_recaudo_por_division_sub_gd, # cumplimiento_recaudo_otras_companias_gd, # cumplimiento_cobro_division_sub_gd,
    cumplimiento_recaudo_por_division_sub_ad, # cumplimiento_cobro_division_sub_ad,
    cumplimiento_recaudo_otras_companias_ad, # cumplimiento_cobro_compañias_ad,
    cumplimiento_recaudo_por_division_sub_ad1, # cumplimiento_cobro_division_sub_ad1,
    cumplimiento_recaudo_otras_companias_ad1, # cumplimiento_cobro_compañias_ad1,
    cumplimiento_recaudo_por_division_sub_ad3, # cumplimiento_cobro_division_sub_ad3,
    cumplimiento_recaudo_otras_companias_ad3, # cumplimiento_cobro_compañias_ad3,
    cumplimiento_recaudo_por_division_sub_ad4, cumplimiento_recaudo_otras_companias_ad4, # cumplimiento_cobro_compañias_ad4,
    cumplimiento_recaudo_por_division_sub_ad5, cumplimiento_recaudo_otras_companias_ad5, # cumplimiento_cobro_compañias_ad5,
    cumplimiento_rentabilidad_cm5_nivel_pais, # rentabilidad_antes_de_impuestos,
    cumplimiento_rentabilidad_cm3_grupo_clientes_sub,  # rentabilidad_division_consecutivo,
    cumplimiento_rentabilidad_cm3_grupo_clientes, # rentabilidad_division,
    cumplimiento_rentabilidad_cm2_grupo_clientes, # rentabilidad_kam,
    cumplimiento_rentabilidad_cm5_ad, # rentabilidad_antes_de_impuestos_ad,
    cumplimiento_rentabilidad_cm5_ad1, # rentabilidad_antes_de_impuestos_ad1,
    cumplimiento_rentabilidad_cm5_ad2, # rentabilidad_antes_de_impuestos_ad2,
    cumplimiento_rentabilidad_cm5_ad3, # rentabilidad_antes_de_impuestos_ad3,
    cumplimiento_rentabilidad_cm5_ad4, # rentabilidad_antes_de_impuestos_ad4,
    cumplimiento_rentabilidad_cm5_ad5, # rentabilidad_antes_de_impuestos_ad5,
    cumplimiento_venta_previo_notas_credito_tp, # venta_credito_tp,
    cumplimiento_venta_servicios_mtto,
    # 2022
    venta_cobrada_braun_cluster,
    venta_cobrada_portafolio_cluster_sub, 
    venta_facturada_portafolio_cluster, 
    venta_cobrada_portafolio_pais_ve,
    venta_facturada_portafolio_zona_sub_ve,
    venta_cobrada_portafolio_zona_ve,
    venta_cobrada_portafolio_cluster_ve,
    venta_facturada_portafolio_cluster_sub_ve,
    venta_cobrada_zona_hospitalario_sub_gc,
    venta_cobrada_zona_hospitalario_sub_gd,
    venta_facturada_pais_ch,
    venta_facturada_zona_ch,
    rentabilidad_zona_hospitalario_cm2,
    venta_facturada_braun_pais,
    rentabilidad_compania_cm3,
    venta_cobrada_grupo_clientes_kams_sub,
    venta_facturada_grupo_clientes_kams,
    kpis_surgical,
    #2023
    venta_cobrada_portafolio_zona_cluster_sub,
    venta_facturada_portafolio_zona_cluster,
    venta_facturada_zona_pais,
    venta_cobrada_zona_pais_sub,
    venta_facturada_portafolio_renal,
    #2024
    venta_facturada_portafolio_renal_sub,
    venta_facturada_portafolio_zona_cluster_sub,
    venta_facturada_zona_pais_sub,
    venta_facturada_grupo_clientes_kams_sub,
    cumplimiento_rentabilidad_grupo_clientes_cm2_sub,
    venta_cobrada_portafolio_cluster,    #2024  VentaCobradaPortafolioClusterSub -> VentaCobradaPortafolioCluster
    venta_facturada_portafolio_cluster_sub, #2024 VentaFacturadaPortafolioCluster -> VentaFacturadaPortafolioClusterSub
    venta_cobrada_portafolio_zona_cluster,
    cumplimiento_facturada_por_division_sub_gd,
    venta_facturada_braun_pais_sub,
    rentabilidad_unidad_negocio_cm2_cogs_sub,
    ebit_cogs_pais,
    ebit_cogs_pais_sub,
    rentabilidad_division_cm2_cogs_sub,
    venta_cobrada_portafolio_renal,
    venta_facturada_portafolio_zona_cluster_sub_ve,
    #2025
    cumplimiento_kpi_calidad
])
maestra_resultados['Contexto'] = maestra_resultados['Contexto'].astype('str')
maestra_resultados.drop_duplicates(['Contexto', 'Fecha', 'Variable'], inplace=True)
maestra_resultados.head()

,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto
0,5004523,2025-12-01,1.0,ObjetivosCualitativos,NaN,NaN
1,5004523,2025-08-01,0.8,ObjetivosCualitativos,NaN,NaN
2,5004523,2025-11-01,0.8,ObjetivosCualitativos,NaN,NaN
3,5004523,2025-09-01,0.8,ObjetivosCualitativos,NaN,NaN
4,5004523,2025-10-01,0.8,ObjetivosCualitativos,NaN,NaN

In [406]:
maestra_resultados[
    (maestra_resultados['Contexto'].str.contains('1111117')) &
    (maestra_resultados['Fecha'] == '2024-05-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto]
Index: []

In [407]:
maestra_resultados.to_excel('maestra_resultados_.xlsx')

In [408]:
maestra_resultados[maestra_resultados['Variable'] == "RentabilidadUnidadNegocioCM2COGSSUB"]

,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto
0,5004293_1,2025-03-01,1.14,RentabilidadUnidadNegocioCM2COGSSUB,4.337511e+05,3.799558e+05
1,5004293_1,2025-04-01,1.12,RentabilidadUnidadNegocioCM2COGSSUB,5.535802e+05,4.943114e+05
2,5004293_1,2025-05-01,1.12,RentabilidadUnidadNegocioCM2COGSSUB,7.292850e+05,6.492449e+05
3,5004293_1,2025-06-01,1.07,RentabilidadUnidadNegocioCM2COGSSUB,8.825227e+05,8.226227e+05
4,5004293_1,2025-07-01,1.10,RentabilidadUnidadNegocioCM2COGSSUB,1.084673e+06,9.849340e+05
...,...,...,...,...,...,...
75,5005299_10,2025-12-01,1.50,RentabilidadUnidadNegocioCM2COGSSUB,1.746690e+06,1.161338e+06
76,5032456_10,2025-12-01,5.24,RentabilidadUnidadNegocioCM2COGSSUB,3.437576e+05,6.564180e+04
77,70002060_10,2025-12-01,0.96,RentabilidadUnidadNegocioCM2COGSSUB,1.490017e+06,1.555361e+06
78,70002068_10,2025-12-01,1.31,RentabilidadUnidadNegocioCM2COGSSUB,2.157412e+06,1.649519e+06
79,70029960_10,2025-12-01,1.02,RentabilidadUnidadNegocioCM2COGSSUB,1.463382e+07,1.433616e+07

In [409]:
maestra_resultados[ maestra_resultados['Contexto'].str.contains('1111117')]

Empty DataFrame
Columns: [Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto]
Index: []

In [410]:
maestra_resultados[ maestra_resultados['Contexto'].str.contains('gd_3_5')]

Empty DataFrame
Columns: [Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto]
Index: []

In [411]:
maestra_resultados[
    (maestra_resultados['Contexto'] == '1111128')
].head()

Empty DataFrame
Columns: [Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto]
Index: []

### Cálculo de Maestra de Resultados Centro Costo

In [412]:
venta_cobrada_zona_pais_sub_centro_costo.head()

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub

In [413]:
venta_cobrada_portafolio_cluster_sub_centro_costo.head()

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,5002790_1,2025-01-01,805,AE,323007290,4503000.00,6.135271e+06,VentaCobradaPortafolioClusterSub
1,5002790_1,2025-01-01,M06,AE,323007290,1132589.97,3.495176e+06,VentaCobradaPortafolioClusterSub
2,5002790_1,2025-02-01,805,AE,323007290,6754500.00,1.022545e+07,VentaCobradaPortafolioClusterSub
3,5002790_1,2025-02-01,M06,AE,323007290,1847155.49,6.037123e+06,VentaCobradaPortafolioClusterSub
4,5002790_1,2025-03-01,805,AE,323007290,14534581.70,1.431563e+07,VentaCobradaPortafolioClusterSub

In [414]:
venta_cobrada_portafolio_zona_cluster_sub_centro_costo.head()

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable
0,37270929_2,2025-09-01,680,HC,323015055,1.515251e+08,1.513846e+08,VentaCobradaPortafolioZonaClusterSub
1,37270929_2,2025-10-01,680,HC,323015055,2.840721e+08,3.429212e+08,VentaCobradaPortafolioZonaClusterSub
2,37270929_2,2025-11-01,680,HC,323015055,4.025508e+08,5.361033e+08,VentaCobradaPortafolioZonaClusterSub
3,37270929_2,2025-12-01,680,HC,323015055,5.625513e+08,7.424493e+08,VentaCobradaPortafolioZonaClusterSub
4,37270929_3,2025-09-01,610,HC,323015040,1.646508e+08,1.732026e+08,VentaCobradaPortafolioZonaClusterSub

In [415]:
cumplimiento_recaudo_por_division_sub_mk_centro_costo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1308 entries, 0 to 1307
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AreaCalculo        1308 non-null   object
 1   Division           1308 non-null   object
 2   GrupoProducto      1308 non-null   object
 3   Consecutivo        1308 non-null   object
 4   Fecha              1308 non-null   datetime64[ns]
 5   Presupuesto        1308 non-null   float64
 6   Real               1308 non-null   float64
 7   CodigoCentroCosto  1308 non-null   object
 8   Contexto           1308 non-null   object
 9   Variable           1308 non-null   object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 102.3+ KB

In [416]:
maestra_resultados_centro_costo = pd.concat([
    #2023
    venta_cobrada_zona_pais_sub_centro_costo,
    cumplimiento_recaudo_por_division_sub_mk_centro_costo, 
    cumplimiento_recaudo_por_division_sub_gd_centro_costo,
    cumplimiento_recaudo_por_unidad_negocio_gu_sub_centro_costo, 
    cumplimiento_recaudo_por_unidad_negocio_mk_sub_centro_costo,
    cumplimiento_venta_por_unidad_negocio_gu_sub_centro_costo, 
    cumplimiento_venta_por_unidad_negocio_mk_sub_centro_costo,
    cumplimiento_rentabilidad_por_unidad_negocio_cm3_gu_centro_costo, 
    cumplimiento_rentabilidad_por_unidad_negocio_cm3_mk_centro_costo,
    cumplimiento_rentabilidad_por_unidad_negocio_cm2_gu_centro_costo, 
    cumplimiento_rentabilidad_por_unidad_negocio_cm2_mk_centro_costo,
    venta_cobrada_portafolio_cluster_sub_centro_costo,
    venta_cobrada_portafolio_zona_cluster_sub_centro_costo,
    #2024
    venta_facturada_portafolio_cluster_sub_centro_costo,
    venta_facturada_braun_pais_sub_centro_costo,
    venta_facturada_zona_pais_sub_centro_costo,
    cumplimiento_facturada_por_division_sub_gd_centro_costo,
    rentabilidad_division_cm2cogs_sub_centro_costo,
    rentabilidad_unidad_negocio_cm2cogs_sub_centro_costo,
    venta_facturada_portafolio_zona_cluster_sub,
    venta_facturada_portafolio_zona_cluster_sub_centro_costo,
    venta_facturada_grupo_clientes_kam_sub_centro_costo
])

maestra_resultados_centro_costo['PorcentajeCumplimiento'] = maestra_resultados_centro_costo['Real']/maestra_resultados_centro_costo['Presupuesto']
# maestra_resultados['Contexto'] = maestra_resultados['Contexto'].astype('str')
# maestra_resultados.drop_duplicates(['Contexto', 'Fecha', 'Variable'], inplace=True)
# maestra_resultados.head()

In [417]:
maestra_resultados_centro_costo[maestra_resultados_centro_costo['Variable'] == 'RentabilidadUnidadNegocioCM2COGSSUB']

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,AreaCalculo,Consecutivo,TipoEmpleado,PorcentajeCumplimiento
0,1047393705_10,2025-03-01,001,AE,323007270,2.719890e+05,2.623649e+05,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,1.036682
1,1047393705_10,2025-04-01,001,AE,323007270,6.031436e+05,6.201085e+05,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,0.972642
2,1047393705_10,2025-05-01,001,AE,323007270,9.590569e+05,1.073238e+06,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,0.893611
3,1047393705_10,2025-06-01,001,AE,323007270,1.383960e+06,1.621772e+06,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,0.853363
4,1047393705_10,2025-07-01,001,AE,323007270,1.935237e+06,2.265712e+06,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,0.854141
...,...,...,...,...,...,...,...,...,...,...,...,...
315,70029960_10,2025-10-01,620,HC,323015045,4.911737e+07,4.991699e+07,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,0.983981
316,70029960_10,2025-11-01,610,HC,323015045,9.855450e+06,8.003441e+06,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,1.231402
317,70029960_10,2025-11-01,620,HC,323015045,5.992686e+07,6.110440e+07,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,0.980729
318,70029960_10,2025-12-01,610,HC,323015045,1.220026e+07,9.612173e+06,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,1.269251
319,70029960_10,2025-12-01,620,HC,323015045,7.221587e+07,7.383183e+07,RentabilidadUnidadNegocioCM2COGSSUB,NaN,NaN,NaN,0.978113

In [418]:
maestra_resultados_centro_costo[maestra_resultados_centro_costo['Contexto'].str.contains('mk_9_3')]

Empty DataFrame
Columns: [Contexto, Fecha, GrupoProducto, Division, CodigoCentroCosto, Real, Presupuesto, Variable, AreaCalculo, Consecutivo, TipoEmpleado, PorcentajeCumplimiento]
Index: []

In [419]:
maestra_resultados_centro_costo.to_excel('maestra_resultados_centro_costo_.xlsx')

In [420]:
maestra_resultados_centro_costo[
    
    pd.notna(maestra_resultados_centro_costo['AreaCalculo'])
]

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,AreaCalculo,Consecutivo,TipoEmpleado,PorcentajeCumplimiento
0,mk_1_2,2025-01-01,001,AE,323007270,3.574246e+08,7.543752e+08,VentaCobradaDivisionSub,1,2,NaN,0.473802
1,mk_1_2,2025-02-01,001,AE,323007270,9.199187e+08,1.257597e+09,VentaCobradaDivisionSub,1,2,NaN,0.731489
2,mk_1_2,2025-03-01,001,AE,323007270,1.241040e+09,1.760895e+09,VentaCobradaDivisionSub,1,2,NaN,0.704778
3,mk_1_2,2025-04-01,001,AE,323007270,1.681027e+09,2.515575e+09,VentaCobradaDivisionSub,1,2,NaN,0.668248
4,mk_1_2,2025-05-01,001,AE,323007270,2.031147e+09,3.102971e+09,VentaCobradaDivisionSub,1,2,NaN,0.654581
...,...,...,...,...,...,...,...,...,...,...,...,...
259,gd_3_1,2025-08-01,A45,BA,323007337,1.452145e+09,1.902193e+09,VentaFacturadaDivisionSub,3,1,NaN,0.763406
260,gd_3_1,2025-09-01,A45,BA,323007337,1.560039e+09,2.219225e+09,VentaFacturadaDivisionSub,3,1,NaN,0.702966
261,gd_3_1,2025-10-01,A45,BA,323007337,1.629872e+09,4.564748e+09,VentaFacturadaDivisionSub,3,1,NaN,0.357056
262,gd_3_1,2025-11-01,A45,BA,323007337,3.565287e+09,4.881780e+09,VentaFacturadaDivisionSub,3,1,NaN,0.730325
263,gd_3_1,2025-12-01,A45,BA,323007337,7.681721e+09,5.198813e+09,VentaFacturadaDivisionSub,3,1,NaN,1.477592

In [421]:
maestra_resultados_centro_costo[maestra_resultados_centro_costo['Contexto'].str.contains('5004293')]

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,AreaCalculo,Consecutivo,TipoEmpleado,PorcentajeCumplimiento
0,5004293_1,2025-01-01,630,HC,323015090,4.840923e+08,6.371832e+08,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.759738
1,5004293_1,2025-02-01,630,HC,323015090,1.456452e+09,1.504837e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.967847
2,5004293_1,2025-03-01,630,HC,323015090,2.633030e+09,2.792760e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.942806
3,5004293_1,2025-04-01,630,HC,323015090,3.519760e+09,3.633300e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.968750
4,5004293_1,2025-05-01,630,HC,323015090,4.750751e+09,4.772095e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.995527
5,5004293_1,2025-06-01,630,HC,323015090,5.941892e+09,6.046461e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.982706
6,5004293_1,2025-07-01,630,HC,323015090,7.377176e+09,7.239485e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,1.019019
7,5004293_1,2025-08-01,630,HC,323015090,8.207827e+09,8.418952e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.974923
8,5004293_1,2025-09-01,630,HC,323015090,9.118308e+09,9.679761e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.941997
9,5004293_1,2025-10-01,630,HC,323015090,9.915875e+09,1.083211e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.915415
10,5004293_1,2025-11-01,630,HC,323015090,1.107049e+10,1.213359e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.912384
11,5004293_1,2025-12-01,630,HC,323015090,1.243884e+10,1.355709e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.917516
12,5004293_2,2025-01-01,630,HC,323015090,1.388437e+09,2.126956e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.652781
13,5004293_2,2025-01-01,CDK,HC,323015090,1.388437e+09,2.126956e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.652781
14,5004293_2,2025-02-01,630,HC,323015090,3.838732e+09,5.014116e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.765585
15,5004293_2,2025-02-01,CDK,HC,323015090,3.838732e+09,5.014116e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.765585
16,5004293_2,2025-03-01,630,HC,323015090,6.315124e+09,9.302574e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.678858
17,5004293_2,2025-03-01,CDK,HC,323015090,6.315124e+09,9.302574e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.678858
18,5004293_2,2025-04-01,630,HC,323015090,9.453676e+09,1.210354e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.781067
19,5004293_2,2025-04-01,CDK,HC,323015090,9.453676e+09,1.210354e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.781067
20,5004293_2,2025-05-01,630,HC,323015090,1.330461e+10,1.589255e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.837160
21,5004293_2,2025-05-01,CDK,HC,323015090,1.330461e+10,1.589255e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.837160
22,5004293_2,2025-06-01,630,HC,323015090,1.640146e+10,2.012881e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.814825
23,5004293_2,2025-06-01,CDK,HC,323015090,1.640146e+10,2.012881e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.814825
24,5004293_2,2025-07-01,630,HC,323015090,1.933301e+10,2.409944e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.802218
25,5004293_2,2025-07-01,CDK,HC,323015090,1.933301e+10,2.409944e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.802218
26,5004293_2,2025-08-01,630,HC,323015090,2.170078e+10,2.802222e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.774413
27,5004293_2,2025-08-01,CDK,HC,323015090,2.170078e+10,2.802222e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.774413
28,5004293_2,2025-09-01,630,HC,323015090,2.503624e+10,3.221579e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.777142
29,5004293_2,2025-09-01,CDK,HC,323015090,2.503624e+10,3.221579e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.777142
30,5004293_2,2025-10-01,630,HC,323015090,2.788897e+10,3.605292e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.773556
31,5004293_2,2025-10-01,CDK,HC,323015090,2.788897e+10,3.605292e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.773556
32,5004293_2,2025-11-01,630,HC,323015090,3.155132e+10,4.038950e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.781176
33,5004293_2,2025-11-01,CDK,HC,323015090,3.155132e+10,4.038950e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.781176
34,5004293_2,2025-12-01,630,HC,323015090,3.531158e+10,4.513309e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.782388
35,5004293_2,2025-12-01,CDK,HC,323015090,3.531158e+10,4.513309e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.782388
36,5004293_3,2025-01-01,620,HC,323015090,7.359598e+08,9.945810e+08,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.739970
37,5004293_3,2025-02-01,620,HC,323015090,1.631783e+09,2.113485e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.772082
38,5004293_3,2025-03-01,620,HC,323015090,3.061162e+09,3.356711e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.911953
39,5004293_3,2025-04-01,620,HC,323015090,4.122461e+09,4.382373e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.940691
40,5004293_3,2025-05-01,620,HC,323015090,5.448178e+09,5.718841e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.952672
41,5004293_3,2025-06-01,620,HC,323015090,6.623818e+09,7.008688e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.945087
42,5004293_3,2025-07-01,620,HC,323015090,7.394211e+09,8.220834e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.899448
43,5004293_3,2025-08-01,620,HC,323015090,8.320768e+09,9.432980e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.882093
44,5004293_3,2025-09-01,620,HC,323015090,9.531061e+09,1.072283e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.888857
45,5004293_3,2025-10-01,620,HC,323015090,1.073754e+10,1.210592e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.886966
46,5004293_3,2025-11-01,620,HC,323015090,1.208893e+10,1.365995e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.884991
47,5004293_3,2025-12-01,620,HC,323015090,1.371596e+10,1.554033e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.882604

In [422]:
maestra_resultados[maestra_resultados['Variable'] == 'EBITCOGSPaisSUB']

,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto
0,5016686_1,2025-03-01,0.74,EBITCOGSPaisSUB,1.964337e+06,2.648294e+06
1,70038889_1,2025-03-01,0.74,EBITCOGSPaisSUB,1.964337e+06,2.648294e+06
2,5003668_1,2025-03-01,0.74,EBITCOGSPaisSUB,1.964337e+06,2.648294e+06
3,5043078_1,2025-03-01,0.74,EBITCOGSPaisSUB,1.964337e+06,2.648294e+06
4,70014725_1,2025-03-01,0.74,EBITCOGSPaisSUB,1.964337e+06,2.648294e+06
...,...,...,...,...,...,...
325,5016776_2,2025-12-01,1.05,EBITCOGSPaisSUB,3.819836e+06,3.654547e+06
326,70055714_2,2025-12-01,1.05,EBITCOGSPaisSUB,3.819836e+06,3.654547e+06
327,52417387_2,2025-12-01,1.05,EBITCOGSPaisSUB,3.819836e+06,3.654547e+06
328,94526955_2,2025-12-01,1.05,EBITCOGSPaisSUB,3.819836e+06,3.654547e+06
329,70021302_2,2025-12-01,1.05,EBITCOGSPaisSUB,3.819836e+06,3.654547e+06

In [423]:
df_parrillas[df_parrillas['Variable'] == 'EBITCOGSPaisSUB']

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
86,53002714,EBITCOGSPaisSUB,53002714_1,0.4,1,EBITCOGSPaisSUB,BBMCO
110,52417387,EBITCOGSPaisSUB,52417387_1,0.2,1,EBITCOGSPaisSUB,BBMCO
111,52417387,EBITCOGSPaisSUB,52417387_2,0.2,2,EBITCOGSPaisSUB,BBMEC
160,94526955,EBITCOGSPaisSUB,94526955_1,0.2,1,EBITCOGSPaisSUB,BBMCO
161,94526955,EBITCOGSPaisSUB,94526955_2,0.2,2,EBITCOGSPaisSUB,BBMEC
174,80133890,EBITCOGSPaisSUB,80133890_1,0.2,1,EBITCOGSPaisSUB,BBMCO
175,80133890,EBITCOGSPaisSUB,80133890_2,0.2,2,EBITCOGSPaisSUB,BBMEC
178,5016686,EBITCOGSPaisSUB,5016686_1,0.4,1,EBITCOGSPaisSUB,BBMCO
337,70038889,EBITCOGSPaisSUB,70038889_1,0.4,1,EBITCOGSPaisSUB,BBMCO
374,5016776,EBITCOGSPaisSUB,5016776_1,0.2,1,EBITCOGSPaisSUB,BBMCO
375,5016776,EBITCOGSPaisSUB,5016776_2,0.2,2,EBITCOGSPaisSUB,BBMEC
393,70010478,EBITCOGSPaisSUB,70010478_1,0.4,1,EBITCOGSPaisSUB,BBMCO
500,52193204,EBITCOGSPaisSUB,52193204_1,0.4,1,EBITCOGSPaisSUB,BBMCO
600,70014232,EBITCOGSPaisSUB,70014232_1,0.4,1,EBITCOGSPaisSUB,BBMCO
614,70055714,EBITCOGSPaisSUB,70055714_1,0.2,1,EBITCOGSPaisSUB,BBMCO
615,70055714,EBITCOGSPaisSUB,70055714_2,0.2,2,EBITCOGSPaisSUB,BBMEC
626,5016665,EBITCOGSPaisSUB,5016665_1,0.4,1,EBITCOGSPaisSUB,BBMCO
695,84086164,EBITCOGSPaisSUB,84086164_1,0.4,1,EBITCOGSPaisSUB,BBMCO
713,70021302,EBITCOGSPaisSUB,70021302_1,0.2,1,EBITCOGSPaisSUB,BBMCO
714,70021302,EBITCOGSPaisSUB,70021302_2,0.2,2,EBITCOGSPaisSUB,BBMEC
778,70015881,EBITCOGSPaisSUB,70015881_1,0.4,1,EBITCOGSPaisSUB,BBMCO
804,5003668,EBITCOGSPaisSUB,5003668_1,0.4,1,EBITCOGSPaisSUB,BBMCO
870,51789567,EBITCOGSPaisSUB,51789567_1,0.4,1,EBITCOGSPaisSUB,BBMCO
873,5003791,EBITCOGSPaisSUB,5003791_1,0.4,1,EBITCOGSPaisSUB,BBMCO
992,5043078,EBITCOGSPaisSUB,5043078_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1013,70002054,EBITCOGSPaisSUB,70002054_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1030,80201251,EBITCOGSPaisSUB,80201251_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1047,1013630697,EBITCOGSPaisSUB,1013630697_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1197,5004472,EBITCOGSPaisSUB,5004472_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1200,5016635,EBITCOGSPaisSUB,5016635_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1264,1032487044,EBITCOGSPaisSUB,1032487044_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1281,70002047,EBITCOGSPaisSUB,70002047_1,0.2,1,EBITCOGSPaisSUB,BBMCO
1282,70002047,EBITCOGSPaisSUB,70002047_2,0.2,2,EBITCOGSPaisSUB,BBMEC
1302,70002073,EBITCOGSPaisSUB,70002073_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1305,79758250,EBITCOGSPaisSUB,79758250_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1308,52733955,EBITCOGSPaisSUB,52733955_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1311,5016772,EBITCOGSPaisSUB,5016772_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1314,5019930,EBITCOGSPaisSUB,5019930_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1317,70039305,EBITCOGSPaisSUB,70039305_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1320,35410002,EBITCOGSPaisSUB,35410002_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1323,5004286,EBITCOGSPaisSUB,5004286_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1414,5016628,EBITCOGSPaisSUB,5016628_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1449,70032756,EBITCOGSPaisSUB,70032756_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1453,5016688,EBITCOGSPaisSUB,5016688_1,0.2,1,EBITCOGSPaisSUB,BBMCO
1454,5016688,EBITCOGSPaisSUB,5016688_2,0.2,2,EBITCOGSPaisSUB,BBMEC
1493,8520024,EBITCOGSPaisSUB,8520024_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1541,5037350,EBITCOGSPaisSUB,5037350_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1575,70015570,EBITCOGSPaisSUB,70015570_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1578,70014725,EBITCOGSPaisSUB,70014725_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1628,1032449509,EBITCOGSPaisSUB,1032449509_1,0.4,1,EBITCOGSPaisSUB,BBMCO
1682,13874027,EBITCOGSPaisSUB,13874027_1,0.4,1,EBITCOGSPaisSUB,BBMCO

In [424]:
maestra_resultados.reset_index(drop=True, inplace=True)
maestra_resultados_centro_costo.reset_index(drop=True, inplace=True)

In [425]:
maestra_resultados.reset_index(drop=True, inplace=True)
maestra_resultados_centro_costo.reset_index(drop=True, inplace=True)

calculo_daraframe = CalculoDataframes()

variables_convertir_euros = ['VentaFacturadaBraunPais', 'VentaFacturadaZonaPaisSub', 'VentaFacturadaDivisionSub', 'VentaFacturadaUnidadNegocioSub', 'VentaFacturadaGrupoClientesKAMSSub']
# Convertir las variables a euros en 'maestra_resultados'
maestra_resultados = calculo_daraframe.convertir_valores_a_euros(maestra_resultados, variables_convertir_euros, df_TRM)

# Convertir las variables a euros en 'maestra_resultados_centro_costo'
maestra_resultados_centro_costo = calculo_daraframe.convertir_valores_a_euros(maestra_resultados_centro_costo, variables_convertir_euros, df_TRM)

# ## Se recalculan los porcentajes de cumplimiento para darle manejo a negativos

<string>:70: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0. 0. 0. ... 0. 0. 0.]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
<string>:70: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0. 0. 0. ... 0. 0. 0.]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
C:\Users\HP\anaconda3\Lib\site-packages\pandas\core\dtypes\cast.py:378: RuntimeWarning: invalid value encountered in cast
  new_result = trans(result).astype(dtype)
<string>:70: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0. 0. 0. ... 0. 0. 0.]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
<string>:70: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.07375367e+10
 1.20889316e+10 1.37159634e+10]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
<string>:70: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.21059161e+10
 1.36599490e+10 1.55403288e+10]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
C:\Users\HP\anaconda3\Lib\site-packages\pandas\core\dtypes\cast.py:378: RuntimeWarning: invalid value encountered in cast
  new_result = trans(result).astype(dtype)
<string>:70: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.         0.         0.         ... 0.88696606 0.88499098 0.88260445]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

In [426]:
# # Filtrar maestra_resultados para los registros no nulos en la columna 'TipoEmpleado'
# registros_no_nulos = maestra_resultados[maestra_resultados['TipoEmpleado'].notnull()]

# # Imprimir los registros no nulos
# print(registros_no_nulos)

In [427]:
maestra_resultados[maestra_resultados['Variable'] == 'VentaFacturadaUnidadNegocioSub']

,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP
7220,gu_1_1,2025-01-01,0.76,VentaFacturadaUnidadNegocioSub,1.142026e+05,1.505171e+05,4.828488e+08,7.334591e+08,0.66
7221,gu_1_1,2025-02-01,0.88,VentaFacturadaUnidadNegocioSub,3.127644e+05,3.567003e+05,1.322368e+09,1.738176e+09,0.76
7222,gu_1_1,2025-03-01,0.97,VentaFacturadaUnidadNegocioSub,5.286289e+05,5.467545e+05,2.235043e+09,2.664297e+09,0.84
7223,gu_1_1,2025-04-01,0.99,VentaFacturadaUnidadNegocioSub,7.412710e+05,7.478088e+05,3.134094e+09,3.644020e+09,0.86
7224,gu_1_1,2025-05-01,0.99,VentaFacturadaUnidadNegocioSub,9.702016e+05,9.752030e+05,4.102012e+09,4.752096e+09,0.86
...,...,...,...,...,...,...,...,...,...
8619,mk_13_3,2025-08-01,1.08,VentaFacturadaUnidadNegocioSub,4.608359e+05,4.267649e+05,1.948414e+09,2.079595e+09,0.94
8620,mk_13_3,2025-09-01,1.01,VentaFacturadaUnidadNegocioSub,5.016912e+05,4.978924e+05,2.121150e+09,2.426195e+09,0.87
8621,mk_13_3,2025-10-01,0.51,VentaFacturadaUnidadNegocioSub,5.235261e+05,1.022525e+06,2.213468e+09,4.982693e+09,0.44
8622,mk_13_3,2025-11-01,0.91,VentaFacturadaUnidadNegocioSub,9.990298e+05,1.093653e+06,4.223898e+09,5.329292e+09,0.79
8623,mk_13_3,2025-12-01,1.70,VentaFacturadaUnidadNegocioSub,1.981902e+06,1.164780e+06,8.379483e+09,5.675892e+09,1.48