In [170]:
import os
import sys
import pandas as pd
import numpy as np
from datetime import datetime
import import_ipynb
from shared_functions import DataframeLoader, Shared
from libraries.DataframesUtils import CalculoDataframes
base_dir = 'C:\\Users\\HP\\Documents\\Proyectos\\Liquidations-Incentives-Jupyter'
sub_direct = 'archivos-fuente-128 (1)'
folder_bbraun_source = os.path.join(base_dir, 'source', sub_direct)

In [171]:
dataframe_loader = DataframeLoader(
    base_dir=base_dir,
    sub_direct=sub_direct
)
shared = Shared()
print(dataframe_loader.cargar_dataframes)

<bound method DataframeLoader.cargar_dataframes of <shared_functions.DataframeLoader object at 0x0000020CD07FEB40>>

In [172]:
(
        df_resultado_detallado_previo,
        df_resultado_liquidaciones_previo,
        df_empleados,
        df_empleados_inactivos,
        df_tipos_empleados,
        df_clusters_empleado,
        df_zonas_empleado,
        df_salarios_variables,
        df_parrillas,
        df_venta_recaudo_real,
        df_venta_recaudo_presupuesto,
        df_venta_por_zona,
        df_recaudo_por_zona,
        df_rentabilidad,
        df_venta_otras_companias,
        df_recaudo_otras_companias,
        df_venta_recaudo_kams,
        df_rentabilidad_kam,
        df_venta_servicios_mtto,
        df_objetivos_cualitativos,
        df_kpi_calidad,
        df_incentivos_por_empleado,
        df_area_calculo_sba,
        df_factores_liquidacion,
        df_cluster_plan_real_recaudo,
        df_zona_plan_real_venta_ch,
        df_rentabilidad_zona,
        df_resultados_variables_cualitativas,
        df_zonas_clusters_empleado,
        df_centros_costos,
        df_empleados_centros_costos,
        df_centros_costos_grupos_productos_divisiones,
        df_parrillas_tipos_calculos,
        df_area_calculo_sba_centros_costos,
        df_renal_ambulatorio,
        df_TRM,
        codigos_ve_vc,
        _dataframes_entrada,
        fecha_liquidacion,
        meses_incentivos,
        OUTPUT_FOLDER
    ) = dataframe_loader.cargar_dataframes(base_dir, folder_bbraun_source)

In [173]:
fecha_liquidacion

'2025-12-01'

In [174]:
# maestra_resultados.to_excel('maestra_resultados_.xlsx')

In [175]:
maestra_resultados = pd.read_excel(
        io=os.path.join('maestra_resultados_.xlsx'),
        dtype={
            'Contexto': str,
            'Fecha': 'datetime64[ns]',
            'PorcentajeCumplimiento':float ,
            'Variable': str,
            'Real': float,
            'Presupuesto': float
        }
    )
maestra_resultados

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto
0,0,5004523,2025-12-01,1.00,ObjetivosCualitativos,NaN,NaN
1,1,5004523,2025-08-01,0.80,ObjetivosCualitativos,NaN,NaN
2,2,5004523,2025-11-01,0.80,ObjetivosCualitativos,NaN,NaN
3,3,5004523,2025-09-01,0.80,ObjetivosCualitativos,NaN,NaN
4,4,5004523,2025-10-01,0.80,ObjetivosCualitativos,NaN,NaN
...,...,...,...,...,...,...,...
22303,1831,5016782,2025-07-01,0.94,KpiCalidad,NaN,NaN
22304,1832,5016782,2025-03-01,0.94,KpiCalidad,NaN,NaN
22305,1833,5016782,2025-02-01,0.94,KpiCalidad,NaN,NaN
22306,1834,5016782,2025-01-01,0.94,KpiCalidad,NaN,NaN
22307,1835,5016782,2025-06-01,0.94,KpiCalidad,NaN,NaN

In [176]:
# maestra_resultados_centro_costo.to_excel('maestra_resultados_centro_costo.xlsx')

In [177]:
maestra_resultados_centro_costo = pd.read_excel(
        io=os.path.join('maestra_resultados_centro_costo_.xlsx'),
        dtype={
            'Fecha': 'datetime64[ns]',
            'GrupoProducto': str,
            'Division': str,
            'CodigoCentroCosto': str,
            'Real': float,
            'Presupuesto': float ,
            'Variable': str,
            'AreaCalculo': str,
            'Consecutivo': str,            
            'TipoEmpleado': str
        }
    )

maestra_resultados_centro_costo

,Unnamed: 0,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,AreaCalculo,Consecutivo,TipoEmpleado,PorcentajeCumplimiento
0,0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,NaN,NaN,NaN,0.564144
1,1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,NaN,NaN,NaN,1.074117
2,2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,NaN,NaN,NaN,1.279127
3,3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,NaN,NaN,NaN,0.226946
4,4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,NaN,NaN,NaN,1.675083
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26707,43,5004293_3,2025-08-01,620,HC,323015090,8.320768e+09,9.432980e+09,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.882093
26708,44,5004293_3,2025-09-01,620,HC,323015090,9.531061e+09,1.072283e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.888857
26709,45,5004293_3,2025-10-01,620,HC,323015090,1.073754e+10,1.210592e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.886966
26710,46,5004293_3,2025-11-01,620,HC,323015090,1.208893e+10,1.365995e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.884991
26711,47,5004293_3,2025-12-01,620,HC,323015090,1.371596e+10,1.554033e+10,VentaFacturadaGrupoClientesKAMSSub,NaN,NaN,NaN,0.882604

In [178]:
maestra_resultados_centro_costo['AreaCalculo'].fillna(0, inplace=True)
maestra_resultados_centro_costo['AreaCalculo'] = maestra_resultados_centro_costo['AreaCalculo'].astype(int)
maestra_resultados_centro_costo

,Unnamed: 0,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,AreaCalculo,Consecutivo,TipoEmpleado,PorcentajeCumplimiento
0,0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0,NaN,NaN,0.564144
1,1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,0,NaN,NaN,1.074117
2,2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,0,NaN,NaN,1.279127
3,3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0,NaN,NaN,0.226946
4,4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,0,NaN,NaN,1.675083
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26707,43,5004293_3,2025-08-01,620,HC,323015090,8.320768e+09,9.432980e+09,VentaFacturadaGrupoClientesKAMSSub,0,NaN,NaN,0.882093
26708,44,5004293_3,2025-09-01,620,HC,323015090,9.531061e+09,1.072283e+10,VentaFacturadaGrupoClientesKAMSSub,0,NaN,NaN,0.888857
26709,45,5004293_3,2025-10-01,620,HC,323015090,1.073754e+10,1.210592e+10,VentaFacturadaGrupoClientesKAMSSub,0,NaN,NaN,0.886966
26710,46,5004293_3,2025-11-01,620,HC,323015090,1.208893e+10,1.365995e+10,VentaFacturadaGrupoClientesKAMSSub,0,NaN,NaN,0.884991
26711,47,5004293_3,2025-12-01,620,HC,323015090,1.371596e+10,1.554033e+10,VentaFacturadaGrupoClientesKAMSSub,0,NaN,NaN,0.882604

In [179]:
maestra_resultados_centro_costo[maestra_resultados_centro_costo['Variable'] == 'RentabilidadUnidadNegocioCM2COGSSUB']

,Unnamed: 0,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,AreaCalculo,Consecutivo,TipoEmpleado,PorcentajeCumplimiento
23218,0,1047393705_10,2025-03-01,001,AE,323007270,2.719890e+05,2.623649e+05,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,1.036682
23219,1,1047393705_10,2025-04-01,001,AE,323007270,6.031436e+05,6.201085e+05,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,0.972642
23220,2,1047393705_10,2025-05-01,001,AE,323007270,9.590569e+05,1.073238e+06,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,0.893611
23221,3,1047393705_10,2025-06-01,001,AE,323007270,1.383960e+06,1.621772e+06,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,0.853363
23222,4,1047393705_10,2025-07-01,001,AE,323007270,1.935237e+06,2.265712e+06,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,0.854141
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23533,315,70029960_10,2025-10-01,620,HC,323015045,4.911737e+07,4.991699e+07,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,0.983981
23534,316,70029960_10,2025-11-01,610,HC,323015045,9.855450e+06,8.003441e+06,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,1.231402
23535,317,70029960_10,2025-11-01,620,HC,323015045,5.992686e+07,6.110440e+07,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,0.980729
23536,318,70029960_10,2025-12-01,610,HC,323015045,1.220026e+07,9.612173e+06,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,1.269251
23537,319,70029960_10,2025-12-01,620,HC,323015045,7.221587e+07,7.383183e+07,RentabilidadUnidadNegocioCM2COGSSUB,0,NaN,NaN,0.978113

## Euros

In [180]:
def convertir_a_euros(main):
    # Definir las tasas de cambio
    trm_marzo_2024 = 4253.92
    trm_abril_2024 = 4226.47
    trm_mayo_2024 = 4217.04
    trm_promedio_2024 = 4652.35

    # Crear una copia del DataFrame para evitar el SettingWithCopyWarning
    main = main.copy()

    # Convertir los valores de 'Real' y 'Presupuesto' a euros
    main['RealEuros'] = main['Real'] / trm_mayo_2024
    main['PresupuestoEuros'] = main['Presupuesto'] / trm_promedio_2024
    main['PorcentajeCumplimientoEuros'] = (main['RealEuros']/main['PresupuestoEuros']).apply(lambda x: round(x, 2))

    # Renombrar las columnas originales 'Real' y 'Presupuesto'
    main = main.rename(columns={
        'Real': 'RealCOP', 'Presupuesto': 'PresupuestoCOP', 
        'PorcentajeCumplimiento': 'PorcentajeCumplimientoCOP',
        'PorcentajeCumplimientoEuros': 'PorcentajeCumplimiento'
    })

    # Renombrar las nuevas columnas para reflejar que están en euros
    main = main.rename(columns={'RealEuros': 'Real', 'PresupuestoEuros': 'Presupuesto'})
    return main[['Contexto', 'Variable', 'Fecha', 'Real', 'Presupuesto', 'PorcentajeCumplimiento', 'RealCOP', 'PresupuestoCOP', 'PorcentajeCumplimientoCOP']]

In [181]:
def unir_dataframes_por_columnas_comunes(df1, df2, how='inner'):
    """
    Une dos DataFrames basándose en sus columnas comunes con un tipo de unión especificado.
    
    Parámetros:
    - df1: Primer DataFrame.
    - df2: Segundo DataFrame.
    - how: Tipo de unión ('left', 'right', 'outer', 'inner'). Por defecto es 'inner'.
    
    Retorna:
    - DataFrame resultante de la unión.
    """
    # Encuentra las columnas comunes entre ambos DataFrames
    columnas_comunes = df1.columns.intersection(df2.columns)
    print(columnas_comunes)
    # Une los DataFrames basándose en las columnas comunes y el tipo de unión especificado
    df_unido = pd.merge(df1, df2, on=columnas_comunes.tolist(), how=how)
    
    return df_unido

In [182]:
# variables_convertir_euros = ['VentaFacturadaBraunPais', 'VentaFacturadaZonaPaisSub', 'VentaFacturadaDivisionSub', 'VentaFacturadaUnidadNegocioSub', 'VentaFacturadaGrupoClientesKAMSSub']
# variables_convertir_euros

In [183]:
# maestra_resultados_aplicar_euros = maestra_resultados[maestra_resultados['Variable'].isin(variables_convertir_euros)]
# maestra_resultados_aplicar_euros

In [184]:
# maestra_resultados[maestra_resultados['Variable'] == 'VentaFacturadaBraunPais']

In [185]:
# maestra_resultados_convertido_euros = maestra_resultados.copy()

# maestra_resultados_convertido_euros['RealCOP'] = 0
# maestra_resultados_convertido_euros['PresupuestoCOP'] = 0
# maestra_resultados_convertido_euros['PorcentajeCumplimientoCOP'] = 0

# maestra_resultados_convertido_euros.update(convertir_a_euros(maestra_resultados_aplicar_euros))
# maestra_resultados_convertido_euros

In [186]:
# maestra_resultados_convertido_euros[maestra_resultados_convertido_euros['Variable'] == 'VentaFacturadaBraunPais']

In [187]:
# # Renombrar las nuevas columnas para reflejar que están en euros
# main = main.rename(columns={'RealEuros': 'Real', 'PresupuestoEuros': 'Presupuesto'})

In [188]:
# # Renombrar las columnas originales 'Real' y 'Presupuesto'
# main = main.rename(columns={
#     'Real': 'RealCOP', 'Presupuesto': 'PresupuestoCOP', 
#     'PorcentajeCumplimiento': 'PorcentajeCumplimientoCOP',
#     'PorcentajeCumplimientoEuros': 'PorcentajeCumplimiento'
# })

In [189]:
# maestra_resultados_convertidos = maestra_resultados.drop(columns=['Unnamed: 0']).merge(
#     maestra_resultados_convertido_euros,
#     on = ['Contexto', 'Variable', 'Fecha'],
#     how='left'
# )
# maestra_resultados_convertidos

In [190]:
# maestra_resultados_convertidos[maestra_resultados_convertidos['Variable'] == 'VentaFacturadaBraunPais']

In [191]:
# maestra_resultados = maestra_resultados_convertido_euros.copy()
# maestra_resultados

## Se recalculan los porcentajes de cumplimiento para darle manejo a negativos

In [192]:
df_parrillas[df_parrillas['Variable'] == 'VentaCobradaBraunPais']

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
0,5004523,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN
21,5004589,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN
27,5032450,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN
35,5004287,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN
41,5002705,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN
...,...,...,...,...,...,...,...
1696,5005917,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN
1701,5041312,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN
1709,5036653,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN
1716,5016782,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN
1724,9990009,VentaCobradaBraunPais,Pais,0.25,0,Venta cobrada país,NaN

In [193]:
calculo_dataframe = CalculoDataframes()

if not df_TRM.empty:
    print("Entró")
    variables_convertir_euros = ['VentaFacturadaBraunPais', 'VentaFacturadaZonaPaisSub', 'VentaFacturadaDivisionSub', 'VentaFacturadaUnidadNegocioSub', 'VentaFacturadaGrupoClientesKAMSSub']
    # # Convertir las variables a euros en 'maestra_resultados'
    maestra_resultados = calculo_dataframe.convertir_valores_a_euros(maestra_resultados, variables_convertir_euros, df_TRM)
    
    # # Convertir las variables a euros en 'maestra_resultados_centro_costo'
    maestra_resultados_centro_costo = calculo_dataframe.convertir_valores_a_euros(maestra_resultados_centro_costo, variables_convertir_euros, df_TRM)
    
    # # ## Se recalculan los porcentajes de cumplimiento para darle manejo a negativos

Entró

C:\Users\HP\anaconda3\Lib\site-packages\pandas\core\dtypes\cast.py:378: RuntimeWarning: invalid value encountered in cast
  new_result = trans(result).astype(dtype)
C:\Users\HP\anaconda3\Lib\site-packages\pandas\core\dtypes\cast.py:378: RuntimeWarning: invalid value encountered in cast
  new_result = trans(result).astype(dtype)

In [194]:
def recalcular_porcentajes_cumplimiento(row):
    response = row['PorcentajeCumplimiento']
    if not pd.isnull(row['Real']) and not pd.isnull(row['Presupuesto']):
        if row['Presupuesto'] == 0:
            response = 0
        elif row['Real'] - row['Presupuesto'] < 0:
            response = 1 + ((row['Real'] - row['Presupuesto']) / abs(row['Presupuesto']))
        elif row['Real'] - row['Presupuesto'] > 0:
            response = 1 + abs((row['Real'] - row['Presupuesto']) / abs(row['Presupuesto']))
    return round(response, 2)

maestra_resultados['PorcentajeCumplimiento'] = maestra_resultados.apply(recalcular_porcentajes_cumplimiento, axis=1)
maestra_resultados

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP
0,0,5004523,2025-12-01,1.00,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0
1,1,5004523,2025-08-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0
2,2,5004523,2025-11-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0
3,3,5004523,2025-09-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0
4,4,5004523,2025-10-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
22303,1831,5016782,2025-07-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0
22304,1832,5016782,2025-03-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0
22305,1833,5016782,2025-02-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0
22306,1834,5016782,2025-01-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0
22307,1835,5016782,2025-06-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0

### Se calculan los porcentajes de cumplimiento para Maestra de Centro de Costos

In [195]:
# maestra_resultados_centro_costo['PorcentajeCumplimiento'] = 0
maestra_resultados_centro_costo['PorcentajeCumplimiento'] = maestra_resultados_centro_costo.apply(recalcular_porcentajes_cumplimiento, axis=1)
# maestra_resultados_centro_costo.drop(columns={'AreaCalculo', 'Consecutivo', 'TipoEmpleado'})

## Se une la maestra de resultados con la parrilla

In [196]:
maestra_resultados[
     (maestra_resultados['Fecha']=='2024-05-01') &
    (maestra_resultados['Contexto']=='1111117')
]

Empty DataFrame
Columns: [Unnamed: 0, Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP]
Index: []

In [197]:
# df_parrillas[df_parrillas['Variable'] == 'RentabilidadDivisionCM2COGsSub']

In [198]:
df_parrillas_tipos_calculos.head()

,TipoEmpleado,AreaCalculo,CodigoRubro,NombreRubro,TipoCalculo
0,AD,1,2,EBITCOGSPaisSUB,F
1,AD,1,3,ObjetivosCualitativos,F
2,AD,1,1,VentaFacturadaBraunPaisSUB,F
3,AD,2,2,EBITCOGSPaisSUB,F
4,AD,2,3,ObjetivosCualitativos,F

In [199]:
df_parrillas[df_parrillas['CodigoEmpleado'] == '5004523']

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
0,5004523,VentaCobradaBraunPais,Pais,0.2500,0,Venta cobrada país,NaN
1,5004523,ObjetivosCualitativos,5004523,0.1500,0,Objetivos cualitativos,NaN
2,5004523,VentaFacturadaPortafolioClusterSub,5004523_1,0.0700,1,VentaFacturadaPortafolioClusterSub,Surgery & Interventions (Neuro)
3,5004523,VentaFacturadaPortafolioClusterSub,5004523_2,0.0525,2,VentaFacturadaPortafolioClusterSub,Surgery & Interventions (Ortho)
4,5004523,VentaFacturadaPortafolioClusterSub,5004523_3,0.0700,3,VentaFacturadaPortafolioClusterSub,Surgery & Interventions (Surgical Assets)
5,5004523,VentaFacturadaPortafolioClusterSub,5004523_4,0.0875,4,VentaFacturadaPortafolioClusterSub,Surgery & Interventions (Operating Room Soluti...
6,5004523,VentaFacturadaPortafolioClusterSub,5004523_5,0.0350,5,VentaFacturadaPortafolioClusterSub,Patient Care (Desinfeccion)
7,5004523,VentaFacturadaPortafolioClusterSub,5004523_6,0.0350,6,VentaFacturadaPortafolioClusterSub,Patient Care (Heridas+Ostomia)
8,5004523,VentaCobradaBraunCluster,5004523,0.2500,0,Venta Cobrada presupuesto asignado total B. Br...,NaN

In [200]:
maestra_resultados[maestra_resultados['Variable'] == 'VentaCobradaBraunPais']

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP
7100,0,Pais,2025-01-01,0.92,VentaCobradaBraunPais,2.002784e+10,2.188562e+10,0.0,0.0,0.0
7101,1,Pais,2025-02-01,0.92,VentaCobradaBraunPais,3.674236e+10,3.977720e+10,0.0,0.0,0.0
7102,2,Pais,2025-03-01,0.90,VentaCobradaBraunPais,5.413943e+10,6.006973e+10,0.0,0.0,0.0
7103,3,Pais,2025-04-01,0.95,VentaCobradaBraunPais,7.504289e+10,7.873086e+10,0.0,0.0,0.0
7104,4,Pais,2025-05-01,0.95,VentaCobradaBraunPais,9.356855e+10,9.882735e+10,0.0,0.0,0.0
7105,5,Pais,2025-06-01,0.92,VentaCobradaBraunPais,1.103678e+11,1.199058e+11,0.0,0.0,0.0
7106,6,Pais,2025-07-01,0.94,VentaCobradaBraunPais,1.310502e+11,1.390078e+11,0.0,0.0,0.0
7107,7,Pais,2025-08-01,0.91,VentaCobradaBraunPais,1.470151e+11,1.620531e+11,0.0,0.0,0.0
7108,8,Pais,2025-09-01,0.93,VentaCobradaBraunPais,1.729828e+11,1.853898e+11,0.0,0.0,0.0
7109,9,Pais,2025-10-01,0.92,VentaCobradaBraunPais,1.921230e+11,2.080055e+11,0.0,0.0,0.0
7110,10,Pais,2025-11-01,0.90,VentaCobradaBraunPais,2.083401e+11,2.306054e+11,0.0,0.0,0.0
7111,11,Pais,2025-12-01,0.93,VentaCobradaBraunPais,2.358407e+11,2.539475e+11,0.0,0.0,0.0

In [201]:
maestra_resultados_centro_costo[maestra_resultados_centro_costo['Variable'] == 'VentaFacturadaPortafolioClusterSub']

,Unnamed: 0,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,AreaCalculo,Consecutivo,TipoEmpleado,PorcentajeCumplimiento,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP
10844,0,5002699_2,2025-03-01,680,HC,323015095,0.00,0.000000e+00,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.0,0.0,0.0,0.0
10845,1,5002699_2,2025-03-01,680,HC,323015100,0.00,0.000000e+00,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.0,0.0,0.0,0.0
10846,2,5002699_2,2025-04-01,680,HC,323015095,46758900.00,0.000000e+00,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.0,0.0,0.0,0.0
10847,3,5002699_2,2025-04-01,680,HC,323015100,46758900.00,0.000000e+00,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.0,0.0,0.0,0.0
10848,4,5002699_2,2025-05-01,680,HC,323015095,45386300.00,0.000000e+00,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19463,8619,70053308_4,2025-12-01,610,HC,323015075,64354603.55,1.065996e+08,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.6,0.0,0.0,0.0
19464,8620,70053308_5,2025-12-01,660,BA,323007337,0.00,7.426914e+05,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.0,0.0,0.0,0.0
19465,8621,70053308_5,2025-12-01,660,BA,323015075,0.00,7.426914e+05,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.0,0.0,0.0,0.0
19466,8622,70053308_5,2025-12-01,A45,BA,323007337,0.00,6.889184e+06,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.0,0.0,0.0,0.0
19467,8623,70053308_5,2025-12-01,A45,BA,323015075,0.00,6.889184e+06,VentaFacturadaPortafolioClusterSub,0,NaN,NaN,0.0,0.0,0.0,0.0

In [202]:
df_parrillas[
     (df_parrillas['Variable'] == 'RentabilidadUnidadNegocioCM2COGSSUB') 
#     (df_parrillas['CodigoEmpleado'] == '5036358')
]

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
20,5045060,RentabilidadUnidadNegocioCM2COGSSUB,5045060_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Nutrition & Drugs.
228,5032456,RentabilidadUnidadNegocioCM2COGSSUB,5032456_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Renal
312,5004297,RentabilidadUnidadNegocioCM2COGSSUB,5004297_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Operating Room Solutions.
353,91285756,RentabilidadUnidadNegocioCM2COGSSUB,91285756_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.
362,70029960,RentabilidadUnidadNegocioCM2COGSSUB,70029960_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Vascular Access & Reg Anest.
390,70002060,RentabilidadUnidadNegocioCM2COGSSUB,70002060_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Patient Care
493,5004306,RentabilidadUnidadNegocioCM2COGSSUB,5004306_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Operating Room Solutions.
523,70029961,RentabilidadUnidadNegocioCM2COGSSUB,70029961_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Surgical Assets.
530,94460154,RentabilidadUnidadNegocioCM2COGSSUB,94460154_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Patient Care
573,29116947,RentabilidadUnidadNegocioCM2COGSSUB,29116947_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Vascular Access & Reg Anest.
785,5004300,RentabilidadUnidadNegocioCM2COGSSUB,5004300_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.
921,1047393705,RentabilidadUnidadNegocioCM2COGSSUB,1047393705_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Surgical Assets.
954,52900453,RentabilidadUnidadNegocioCM2COGSSUB,52900453_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Surgical Assets.
1054,5005071,RentabilidadUnidadNegocioCM2COGSSUB,5005071_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.
1089,5003954,RentabilidadUnidadNegocioCM2COGSSUB,5003954_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Patient Care
1162,1113621770,RentabilidadUnidadNegocioCM2COGSSUB,1113621770_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Patient Care
1240,5005299,RentabilidadUnidadNegocioCM2COGSSUB,5005299_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Neurosurgery.
1505,5004293,RentabilidadUnidadNegocioCM2COGSSUB,5004293_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,SBA08 12 36
1638,5004302,RentabilidadUnidadNegocioCM2COGSSUB,5004302_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Orthopaedics.
1645,70002068,RentabilidadUnidadNegocioCM2COGSSUB,70002068_10,0.2,10,RentabilidadUnidadNegocioCM2COGSSUB,Operating Room Solutions.

In [203]:
maestra_resultados[maestra_resultados['Contexto'] == '5002711_1'].merge(
    df_parrillas[df_parrillas['Contexto'] == '5002711_1'],
    on=['Variable', 'Contexto'],
    how='left'
)

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,CodigoEmpleado,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
0,0,5002711_1,2025-01-01,1.41,VentaCobradaZonaHospitalarioSub,2.728419e+09,1.933902e+09,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
1,1,5002711_1,2025-02-01,1.06,VentaCobradaZonaHospitalarioSub,3.967417e+09,3.725453e+09,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
2,2,5002711_1,2025-03-01,0.95,VentaCobradaZonaHospitalarioSub,5.739001e+09,6.022608e+09,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
3,3,5002711_1,2025-04-01,0.93,VentaCobradaZonaHospitalarioSub,7.330999e+09,7.864786e+09,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
4,4,5002711_1,2025-07-01,0.92,VentaCobradaZonaHospitalarioSub,8.874322e+09,9.647957e+09,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
5,5,5002711_1,2025-11-01,0.90,VentaCobradaZonaHospitalarioSub,1.068605e+10,1.186403e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
6,6,5002711_1,2025-12-01,0.90,VentaCobradaZonaHospitalarioSub,1.270673e+10,1.409195e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
7,0,5002711_1,2025-01-01,1.09,VentaCobradaZonaPaisSub,4.476423e+09,4.102103e+09,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
8,1,5002711_1,2025-02-01,0.87,VentaCobradaZonaPaisSub,6.900072e+09,7.932480e+09,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
9,2,5002711_1,2025-03-01,0.82,VentaCobradaZonaPaisSub,1.044979e+10,1.270034e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
10,3,5002711_1,2025-04-01,0.84,VentaCobradaZonaPaisSub,1.391989e+10,1.665851e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
11,4,5002711_1,2025-05-01,0.89,VentaCobradaZonaPaisSub,1.855924e+10,2.093226e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
12,5,5002711_1,2025-06-01,0.86,VentaCobradaZonaPaisSub,2.177782e+10,2.531239e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
13,6,5002711_1,2025-07-01,0.89,VentaCobradaZonaPaisSub,2.586478e+10,2.907387e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
14,7,5002711_1,2025-08-01,0.86,VentaCobradaZonaPaisSub,2.943922e+10,3.412630e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
15,8,5002711_1,2025-09-01,0.87,VentaCobradaZonaPaisSub,3.403759e+10,3.900879e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
16,9,5002711_1,2025-10-01,0.88,VentaCobradaZonaPaisSub,3.829914e+10,4.367067e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
17,10,5002711_1,2025-11-01,0.86,VentaCobradaZonaPaisSub,4.184857e+10,4.843852e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
18,11,5002711_1,2025-12-01,0.87,VentaCobradaZonaPaisSub,4.600114e+10,5.313254e+10,0.000000e+00,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN
19,0,5002711_1,2025-01-01,0.63,VentaFacturadaZonaPaisSub,4.011008e+05,6.351421e+05,1.695854e+09,3.095003e+09,0.55,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
20,9,5002711_1,2025-02-01,0.88,VentaFacturadaZonaPaisSub,1.225137e+06,1.397113e+06,5.179880e+09,6.808036e+09,0.76,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
21,18,5002711_1,2025-03-01,0.86,VentaFacturadaZonaPaisSub,2.016826e+06,2.341116e+06,8.527142e+09,1.140809e+10,0.75,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
22,27,5002711_1,2025-04-01,1.00,VentaFacturadaZonaPaisSub,3.076853e+06,3.077021e+06,1.300894e+10,1.499411e+10,0.87,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
23,36,5002711_1,2025-05-01,1.04,VentaFacturadaZonaPaisSub,4.196413e+06,4.028486e+06,1.774244e+10,1.963053e+10,0.90,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
24,45,5002711_1,2025-06-01,1.04,VentaFacturadaZonaPaisSub,5.215806e+06,5.006653e+06,2.205243e+10,2.439707e+10,0.90,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
25,54,5002711_1,2025-07-01,1.05,VentaFacturadaZonaPaisSub,6.239160e+06,5.941365e+06,2.637917e+10,2.895186e+10,0.91,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
26,63,5002711_1,2025-08-01,1.04,VentaFacturadaZonaPaisSub,7.208346e+06,6.936599e+06,3.047689e+10,3.380156e+10,0.90,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
27,72,5002711_1,2025-09-01,1.04,VentaFacturadaZonaPaisSub,8.188638e+06,7.910841e+06,3.462156e+10,3.854897e+10,0.90,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
28,81,5002711_1,2025-10-01,1.04,VentaFacturadaZonaPaisSub,9.206968e+06,8.875792e+06,3.892706e+10,4.325112e+10,0.90,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
29,90,5002711_1,2025-11-01,1.02,VentaFacturadaZonaPaisSub,1.021700e+07,9.989577e+06,4.319749e+10,4.867851e+10,0.89,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care
30,99,5002711_1,2025-12-01,1.05,VentaFacturadaZonaPaisSub,1.178180e+07,1.122144e+07,4.981346e+10,5.468129e+10,0.91,5002711,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care

### Maestra de Resultados por Empleado

In [204]:
maestra_resultados_por_empleado = maestra_resultados.merge(
    df_parrillas,
    how='left',
    indicator=True
)
maestra_resultados_por_empleado

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,CodigoEmpleado,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,_merge
0,0,5004523,2025-12-01,1.00,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,5004523,0.15,0.0,Objetivos cualitativos,NaN,both
1,1,5004523,2025-08-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,5004523,0.15,0.0,Objetivos cualitativos,NaN,both
2,2,5004523,2025-11-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,5004523,0.15,0.0,Objetivos cualitativos,NaN,both
3,3,5004523,2025-09-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,5004523,0.15,0.0,Objetivos cualitativos,NaN,both
4,4,5004523,2025-10-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,5004523,0.15,0.0,Objetivos cualitativos,NaN,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27045,1831,5016782,2025-07-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,left_only
27046,1832,5016782,2025-03-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,left_only
27047,1833,5016782,2025-02-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,left_only
27048,1834,5016782,2025-01-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,left_only
27049,1835,5016782,2025-06-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,left_only

In [205]:
maestra_resultados_por_empleado[
     (maestra_resultados_por_empleado['Fecha']=='2024-05-01') &
    (maestra_resultados_por_empleado['Contexto']=='1111117')
]

Empty DataFrame
Columns: [Unnamed: 0, Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, _merge]
Index: []

In [206]:
df_empleados[df_empleados['CodigoEmpleado'] == '1111117']

Empty DataFrame
Columns: [TipoEmpleado, CodigoEmpleado, Identificacion, CorreoElectronico, Nombre, Apellidos, SalarioVariable, FechaIngreso, FechaRetiro, AreaCalculo]
Index: []

In [207]:
maestra_resultados_por_empleado[maestra_resultados_por_empleado['Variable'] == 'VentaFacturadaGrupoClientesKAMSSub']

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,CodigoEmpleado,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,_merge
21080,0,kam_2_1,2025-01-01,0.88,VentaFacturadaGrupoClientesKAMSSub,1.144968e+05,130759.760350,4.840923e+08,6.371832e+08,0.76,5004293,0.09,1.0,VentaFacturadaGrupoClientesKAMSSub,SBA 08 IV Systems & Drainage,both
21081,1,kam_2_1,2025-02-01,1.12,VentaFacturadaGrupoClientesKAMSSub,3.444778e+05,308815.604369,1.456452e+09,1.504837e+09,0.97,5004293,0.09,1.0,VentaFacturadaGrupoClientesKAMSSub,SBA 08 IV Systems & Drainage,both
21082,2,kam_2_1,2025-03-01,1.09,VentaFacturadaGrupoClientesKAMSSub,6.227601e+05,573117.247734,2.633030e+09,2.792760e+09,0.94,5004293,0.09,1.0,VentaFacturadaGrupoClientesKAMSSub,SBA 08 IV Systems & Drainage,both
21083,3,kam_2_1,2025-04-01,1.12,VentaFacturadaGrupoClientesKAMSSub,8.324881e+05,745608.846578,3.519760e+09,3.633300e+09,0.97,5004293,0.09,1.0,VentaFacturadaGrupoClientesKAMSSub,SBA 08 IV Systems & Drainage,both
21084,4,kam_2_1,2025-05-01,1.15,VentaFacturadaGrupoClientesKAMSSub,1.123640e+06,979307.141785,4.750751e+09,4.772095e+09,1.00,5004293,0.09,1.0,VentaFacturadaGrupoClientesKAMSSub,SBA 08 IV Systems & Drainage,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21147,67,kam_3_3,2025-08-01,0.85,VentaFacturadaGrupoClientesKAMSSub,3.850135e+05,451209.568781,1.627837e+09,2.198713e+09,0.74,5016988,0.08,3.0,VentaFacturadaGrupoClientesKAMSSub,Patient Care,both
21148,68,kam_3_3,2025-09-01,0.79,VentaFacturadaGrupoClientesKAMSSub,4.127128e+05,521270.069342,1.744950e+09,2.540113e+09,0.69,5016988,0.08,3.0,VentaFacturadaGrupoClientesKAMSSub,Patient Care,both
21149,69,kam_3_3,2025-10-01,0.80,VentaFacturadaGrupoClientesKAMSSub,4.760444e+05,597141.525735,2.012716e+09,2.909829e+09,0.69,5016988,0.08,3.0,VentaFacturadaGrupoClientesKAMSSub,Patient Care,both
21150,70,kam_3_3,2025-11-01,0.80,VentaFacturadaGrupoClientesKAMSSub,5.336281e+05,668424.149947,2.256180e+09,3.257184e+09,0.69,5016988,0.08,3.0,VentaFacturadaGrupoClientesKAMSSub,Patient Care,both
21151,71,kam_3_3,2025-12-01,0.87,VentaFacturadaGrupoClientesKAMSSub,6.418391e+05,738542.344339,2.713696e+09,3.598865e+09,0.75,5016988,0.08,3.0,VentaFacturadaGrupoClientesKAMSSub,Patient Care,both

In [208]:
maestra_resultados_por_empleado.columns

Index(['Unnamed: 0', 'Contexto', 'Fecha', 'PorcentajeCumplimiento', 'Variable',
       'Real', 'Presupuesto', 'RealCOP', 'PresupuestoCOP',
       'PorcentajeCumplimientoCOP', 'CodigoEmpleado', 'Porcentaje',
       'Consecutivo', 'Nombre variable', 'Nombre consecutivo', '_merge'],
      dtype='object')

In [209]:
maestra_resultados_por_empleado = maestra_resultados_por_empleado.merge(
    df_empleados[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Apellidos', 'Nombre', 'FechaIngreso']],
    on='CodigoEmpleado',
    how='left'
)
maestra_resultados_por_empleado

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,...,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,_merge,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso
0,0,5004523,2025-12-01,1.00,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
1,1,5004523,2025-08-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
2,2,5004523,2025-11-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
3,3,5004523,2025-09-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
4,4,5004523,2025-10-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27045,1831,5016782,2025-07-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT
27046,1832,5016782,2025-03-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT
27047,1833,5016782,2025-02-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT
27048,1834,5016782,2025-01-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT
27049,1835,5016782,2025-06-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT

In [210]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['Variable'] == 'ObjetivosCualitativos') &
    (maestra_resultados_por_empleado['Contexto'] == '5004293')
]

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,...,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,_merge,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso
1632,1632,5004293,2025-12-01,1.00,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1633,1633,5004293,2025-08-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1634,1634,5004293,2025-11-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1635,1635,5004293,2025-09-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1636,1636,5004293,2025-10-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1637,1637,5004293,2025-05-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1638,1638,5004293,2025-04-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1639,1639,5004293,2025-07-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1640,1640,5004293,2025-03-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1641,1641,5004293,2025-02-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1642,1642,5004293,2025-01-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17
1643,1643,5004293,2025-06-01,0.88,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,KAM,2.0,SERNA CASTRILLON,ANGELA MARIA,2013-06-17

In [211]:
# Se añaden líneas para filtrar registros vacíos ('Fecha' y 'CodigoEmpleado')
maestra_resultados_por_empleado.dropna(subset=[
        'Fecha'
    ], inplace=True)
maestra_resultados_por_empleado['CodigoEmpleado'] = maestra_resultados_por_empleado['CodigoEmpleado'].astype(str)
maestra_resultados_por_empleado

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,...,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,_merge,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso
0,0,5004523,2025-12-01,1.00,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
1,1,5004523,2025-08-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
2,2,5004523,2025-11-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
3,3,5004523,2025-09-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
4,4,5004523,2025-10-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.15,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27045,1831,5016782,2025-07-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT
27046,1832,5016782,2025-03-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT
27047,1833,5016782,2025-02-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT
27048,1834,5016782,2025-01-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT
27049,1835,5016782,2025-06-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT

In [212]:
df_salarios_variables[df_salarios_variables['CodigoEmpleado'] == '16659046']

Empty DataFrame
Columns: [CodigoEmpleado, Fecha, SalarioVariable, PromedioSalarioVariable]
Index: []

In [213]:
maestra_resultados_por_empleado[maestra_resultados_por_empleado['CodigoEmpleado'] == '16659046']

Empty DataFrame
Columns: [Unnamed: 0, Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, _merge, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso]
Index: []

[0 rows x 21 columns]

In [214]:
maestra_resultados_por_empleado.columns

Index(['Unnamed: 0', 'Contexto', 'Fecha', 'PorcentajeCumplimiento', 'Variable',
       'Real', 'Presupuesto', 'RealCOP', 'PresupuestoCOP',
       'PorcentajeCumplimientoCOP', 'CodigoEmpleado', 'Porcentaje',
       'Consecutivo', 'Nombre variable', 'Nombre consecutivo', '_merge',
       'TipoEmpleado', 'AreaCalculo', 'Apellidos', 'Nombre', 'FechaIngreso'],
      dtype='object')

In [215]:
# TODO Hacer el merge con la tabla de promedio variable
maestra_resultados_por_empleado = maestra_resultados_por_empleado.merge(
    df_salarios_variables[['CodigoEmpleado', 'Fecha', 'PromedioSalarioVariable']].rename(
        columns={'PromedioSalarioVariable': 'SalarioVariable'}
    ),
    on=['CodigoEmpleado', 'Fecha'],
    how='left'
)
maestra_resultados_por_empleado

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,...,Consecutivo,Nombre variable,Nombre consecutivo,_merge,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable
0,0,5004523,2025-12-01,1.00,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.545833e+06
1,1,5004523,2025-08-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.543750e+06
2,2,5004523,2025-11-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.545455e+06
3,3,5004523,2025-09-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.544444e+06
4,4,5004523,2025-10-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.0,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.545000e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27018,1831,5016782,2025-07-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN
27019,1832,5016782,2025-03-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN
27020,1833,5016782,2025-02-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN
27021,1834,5016782,2025-01-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN
27022,1835,5016782,2025-06-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN

In [216]:
maestra_resultados_por_empleado[
     (maestra_resultados_por_empleado['Fecha']=='2024-05-01') &
    (maestra_resultados_por_empleado['Contexto']=='1111117')
]

Empty DataFrame
Columns: [Unnamed: 0, Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, _merge, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, SalarioVariable]
Index: []

[0 rows x 22 columns]

### Maestra de Resultados por Empleado y Centro de Costos

In [217]:
maestra_resultados_centro_costo.head()

,Unnamed: 0,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,AreaCalculo,Consecutivo,TipoEmpleado,PorcentajeCumplimiento,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP
0,0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0,NaN,NaN,0.56,0.0,0.0,0.0
1,1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,0,NaN,NaN,1.07,0.0,0.0,0.0
2,2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,0,NaN,NaN,1.28,0.0,0.0,0.0
3,3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0,NaN,NaN,0.23,0.0,0.0,0.0
4,4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,0,NaN,NaN,1.68,0.0,0.0,0.0

In [218]:
df_parrillas

,CodigoEmpleado,Variable,Contexto,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
0,5004523,VentaCobradaBraunPais,Pais,0.2500,0,Venta cobrada país,NaN
1,5004523,ObjetivosCualitativos,5004523,0.1500,0,Objetivos cualitativos,NaN
2,5004523,VentaFacturadaPortafolioClusterSub,5004523_1,0.0700,1,VentaFacturadaPortafolioClusterSub,Surgery & Interventions (Neuro)
3,5004523,VentaFacturadaPortafolioClusterSub,5004523_2,0.0525,2,VentaFacturadaPortafolioClusterSub,Surgery & Interventions (Ortho)
4,5004523,VentaFacturadaPortafolioClusterSub,5004523_3,0.0700,3,VentaFacturadaPortafolioClusterSub,Surgery & Interventions (Surgical Assets)
...,...,...,...,...,...,...,...
1727,9990009,VentaFacturadaPortafolioClusterSub,9990009_2,0.1050,2,VentaFacturadaPortafolioClusterSub,Medical Care (Negocios:Reg Anest & Vas Acc)
1728,9990009,VentaFacturadaPortafolioClusterSub,9990009_3,0.0700,3,VentaFacturadaPortafolioClusterSub,Medical Care (Negocios: Nutrition)
1729,9990009,VentaFacturadaPortafolioClusterSub,9990009_4,0.0525,4,VentaFacturadaPortafolioClusterSub,Medical Care (Negocios: Drugs)
1730,9990009,VentaFacturadaPortafolioClusterSub,9990009_5,0.0175,5,VentaFacturadaPortafolioClusterSub,Renal
1731,9990009,VentaCobradaBraunCluster,9990009,0.2500,0,Venta Cobrada presupuesto asignado total B. Br...,NaN

In [219]:
maestra_resultados_por_empleado_centro_costo = maestra_resultados_centro_costo.drop(columns={'AreaCalculo', 'Consecutivo', 'TipoEmpleado', 'Unnamed: 0'})

In [220]:
maestra_resultados_por_empleado_centro_costo = maestra_resultados_por_empleado_centro_costo.merge(
    df_parrillas,
    on=['Contexto', 'Variable'],
    how='left'
)
maestra_resultados_por_empleado_centro_costo.head()

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,CodigoEmpleado,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0.56,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,1.07,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,1.28,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0.23,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,1.68,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [221]:
maestra_resultados_por_empleado_centro_costo[
    (maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] == '5002899')
]

Empty DataFrame
Columns: [Contexto, Fecha, GrupoProducto, Division, CodigoCentroCosto, Real, Presupuesto, Variable, PorcentajeCumplimiento, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo]
Index: []

In [222]:
maestra_resultados_por_empleado_centro_costo[
    (maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] == '1032450706') &
    (maestra_resultados_por_empleado_centro_costo['Fecha'] == '2023-01-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, GrupoProducto, Division, CodigoCentroCosto, Real, Presupuesto, Variable, PorcentajeCumplimiento, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo]
Index: []

In [223]:
# maestra_resultados_por_empleado_centro_costo = maestra_resultados_centro_costo.drop(columns=['Unnamed: 0' , 'Consecutivo']).merge(
#     df_parrillas_tipos_calculos,
#     on=['TipoEmpleado', 'AreaCalculo'],
#     how='left'
# )
# maestra_resultados_por_empleado_centro_costo.head()

In [224]:
# maestra_resultados_por_empleado_centro_costo = maestra_resultados_por_empleado_centro_costo.merge(
#     df_empleados_centros_costos.rename(columns={'PorcentajeAsignacion': 'Porcentaje'})
# )

In [225]:
# maestra_resultados_por_empleado_centro_costo[maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] == '1032450706']

In [226]:
df_empleados[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Apellidos', 'Nombre', 'FechaIngreso', 'FechaRetiro']][df_empleados['CodigoEmpleado'] == '5005463']

Empty DataFrame
Columns: [CodigoEmpleado, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, FechaRetiro]
Index: []

In [227]:
df_empleados[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Apellidos', 'Nombre', 'FechaIngreso', 'FechaRetiro']][df_empleados['CodigoEmpleado'] == '1098612757']

Empty DataFrame
Columns: [CodigoEmpleado, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, FechaRetiro]
Index: []

In [228]:
df_empleados_inactivos[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Apellidos', 'Nombre', 'FechaIngreso', 'FechaRetiro']][df_empleados_inactivos['CodigoEmpleado'] == '1032450706']

,CodigoEmpleado,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,FechaRetiro
124,1032450706,MK,9,RODRIGUEZ CASTELLANOS,LAURA CAMILA,2022-07-01,2023-10-01

In [229]:
df_empleados_inactivos[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Apellidos', 'Nombre', 'FechaIngreso', 'FechaRetiro']][df_empleados_inactivos['CodigoEmpleado'] == '5005463']

,CodigoEmpleado,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,FechaRetiro
27,5005463,GU,6,CHAVES,DIANA,2016-07-01,2023-09-01

In [230]:
df_empleados_totales = pd.concat([df_empleados, df_empleados_inactivos])

In [231]:
maestra_resultados_por_empleado_centro_costo = maestra_resultados_por_empleado_centro_costo.merge(
    df_empleados_totales[['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Apellidos', 'Nombre', 'FechaIngreso']],
    on=['CodigoEmpleado'],
    how='left'
)
maestra_resultados_por_empleado_centro_costo.head()

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,...,CodigoEmpleado,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0.56,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,1.07,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,1.28,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0.23,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,1.68,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [232]:
# Se añaden líneas para filtrar registros vacíos ('Fecha' y 'CodigoEmpleado')
maestra_resultados_por_empleado_centro_costo.dropna(subset=[
        'Fecha'
    ], inplace=True)
maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] = maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'].astype(str)
maestra_resultados_por_empleado_centro_costo.head()

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,...,CodigoEmpleado,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0.56,0.0,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,1.07,0.0,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,1.28,0.0,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0.23,0.0,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,1.68,0.0,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [233]:
# TODO Hacer el merge con la tabla de promedio variable
maestra_resultados_por_empleado_centro_costo = maestra_resultados_por_empleado_centro_costo.merge(
    df_salarios_variables[['CodigoEmpleado', 'Fecha', 'PromedioSalarioVariable']].rename(
        columns={'PromedioSalarioVariable': 'SalarioVariable'}
    ),
    on=['CodigoEmpleado', 'Fecha'],
    how='left'
)
maestra_resultados_por_empleado_centro_costo.head()

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,...,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0.56,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,1.07,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,1.28,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0.23,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,1.68,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [234]:
maestra_resultados_por_empleado[
     (maestra_resultados_por_empleado['Fecha']=='2025-12-01') &
    (maestra_resultados_por_empleado['Contexto']=='79539822') &
    (maestra_resultados_por_empleado['Variable']=='ObjetivosCualitativos')
]

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,...,Consecutivo,Nombre variable,Nombre consecutivo,_merge,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable
684,684,79539822,2025-12-01,1.2,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,0.0,Objetivos cualitativos,NaN,both,AD2,1.0,GONZALEZ FRANCO,OMAR,2019-03-01,3.495833e+06

In [235]:
maestra_resultados_por_empleado_centro_costo[maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] == '1032450706']

Empty DataFrame
Columns: [Contexto, Fecha, GrupoProducto, Division, CodigoCentroCosto, Real, Presupuesto, Variable, PorcentajeCumplimiento, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, SalarioVariable]
Index: []

[0 rows x 23 columns]

In [236]:
df_factores_liquidacion[df_factores_liquidacion["TipoEmpleado"] == "GU"]

    TipoEmpleado  PorcentajeCumplimiento  FactorIncentivo
149           GU                    0.88            0.500
150           GU                    0.89            0.542
151           GU                    0.90            0.583
152           GU                    0.91            0.625
153           GU                    0.92            0.667
154           GU                    0.93            0.708
155           GU                    0.94            0.750
156           GU                    0.95            0.792
157           GU                    0.96            0.833
158           GU                    0.97            0.875
159           GU                    0.98            0.917
160           GU                    0.99            0.958
161           GU                    1.00            1.000
162           GU                    1.01            1.375
163           GU                    1.02            1.750
164           GU                    1.03            2.125
165           GU                    1.04            2.500
166           GU                    1.05            2.500
167           GU                    1.06            2.500

### Calculo sobre maestra resultados por empleado

In [237]:
maestra_resultados_por_empleado.columns

Index(['Unnamed: 0', 'Contexto', 'Fecha', 'PorcentajeCumplimiento', 'Variable',
       'Real', 'Presupuesto', 'RealCOP', 'PresupuestoCOP',
       'PorcentajeCumplimientoCOP', 'CodigoEmpleado', 'Porcentaje',
       'Consecutivo', 'Nombre variable', 'Nombre consecutivo', '_merge',
       'TipoEmpleado', 'AreaCalculo', 'Apellidos', 'Nombre', 'FechaIngreso',
       'SalarioVariable'],
      dtype='object')

In [238]:
maestra_resultados_por_empleado = maestra_resultados_por_empleado.merge(
    df_factores_liquidacion,
    on=['TipoEmpleado', 'PorcentajeCumplimiento'],
    how='left'
)

In [239]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['Fecha']== '2025-03-01') &
    (maestra_resultados_por_empleado['CodigoEmpleado']== '70002060') &
    (maestra_resultados_por_empleado['Variable']== 'VentaFacturadaUnidadNegocioSub')
]

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,...,Nombre variable,Nombre consecutivo,_merge,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable,FactorIncentivo
9484,278,gu_8_1,2025-03-01,1.10,VentaFacturadaUnidadNegocioSub,167882.135795,152344.327612,7.098057e+08,7.423632e+08,0.96,...,Venta Facturada Portafolio a cargo,Desinfección,both,GU,8.0,CRUZ TAVERA,CESAR ALBERTO,2024-09-01,3000000.0,NaN
9532,290,gu_8_2,2025-03-01,0.69,VentaFacturadaUnidadNegocioSub,144854.676675,209135.646050,6.124456e+08,1.019103e+09,0.60,...,Venta Facturada Portafolio a cargo,Heridas + Osto,both,GU,8.0,CRUZ TAVERA,CESAR ALBERTO,2024-09-01,3000000.0,NaN
9580,302,gu_8_3,2025-03-01,1.07,VentaFacturadaUnidadNegocioSub,92399.656076,86344.355447,3.906657e+08,4.207500e+08,0.93,...,Venta Facturada Portafolio a cargo,Uro,both,GU,8.0,CRUZ TAVERA,CESAR ALBERTO,2024-09-01,3000000.0,NaN

In [240]:
maestra_resultados_por_empleado['FactorIncentivo'] = np.where(
    ((maestra_resultados_por_empleado['Fecha'] >= '2022-08-01') & 
     (maestra_resultados_por_empleado['PorcentajeCumplimiento'] == 0) & 
     (maestra_resultados_por_empleado['Presupuesto'] == 0) & 
     (maestra_resultados_por_empleado['Real'] == 0)),
    0.25,
    maestra_resultados_por_empleado['FactorIncentivo']
)
maestra_resultados_por_empleado['FactorIncentivo'] = np.where(
    ((maestra_resultados_por_empleado['Fecha'] >= '2022-08-01') & 
     (maestra_resultados_por_empleado['PorcentajeCumplimiento'] == 0) & 
     (maestra_resultados_por_empleado['Presupuesto'] == 0) & 
     (maestra_resultados_por_empleado['Real'] > 0)),
    0.5,
    maestra_resultados_por_empleado['FactorIncentivo']
)

##
_excepciones_porcentaje_cumplimiento = [
    # {
    #     'TipoEmpleado': 'VC',
    #     'AreaCalculo': 7,
    #     'Variable': 'VentaFacturadaZonaCargoIndividualSub',
    #     'Consecutivo': 4,
    #     'FechaInicial': '2021-02-01',
    #     'FechaFinal': '2021-06-01',
    #     'PorcentajeCumplimiento': 1,
    #     'FactorIncentivo': 1,
    #     'Codigos': ['5003527']
    # }
]

for excepcion in _excepciones_porcentaje_cumplimiento:
    maestra_resultados_por_empleado['PorcentajeCumplimiento'] = np.where(
        (
            (maestra_resultados_por_empleado['CodigoEmpleado'].isin(excepcion['Codigos'])) &
            (maestra_resultados_por_empleado['Consecutivo'] == excepcion['Consecutivo']) &
            (maestra_resultados_por_empleado['Variable'] == excepcion['Variable']) &
            (maestra_resultados_por_empleado['Fecha'] >= excepcion['FechaInicial']) &
            (maestra_resultados_por_empleado['Fecha'] <= excepcion['FechaFinal'])
        ),
        excepcion['PorcentajeCumplimiento'],
        maestra_resultados_por_empleado['PorcentajeCumplimiento']
    )
    maestra_resultados_por_empleado['FactorIncentivo'] = np.where(
        (
            (maestra_resultados_por_empleado['CodigoEmpleado'].isin(excepcion['Codigos'])) &
            (maestra_resultados_por_empleado['Consecutivo'] == excepcion['Consecutivo']) &
            (maestra_resultados_por_empleado['Variable'] == excepcion['Variable']) &
            (maestra_resultados_por_empleado['Fecha'] >= excepcion['FechaInicial']) &
            (maestra_resultados_por_empleado['Fecha'] <= excepcion['FechaFinal'])
        ),
        excepcion['FactorIncentivo'],
        maestra_resultados_por_empleado['FactorIncentivo']
    )
##

maestra_resultados_por_empleado['FactorIncentivo'] = np.where(
    (maestra_resultados_por_empleado['PorcentajeCumplimiento']<0.9) & (maestra_resultados_por_empleado['FactorIncentivo'].isnull()),
    0,
    maestra_resultados_por_empleado['FactorIncentivo']
)
maestra_resultados_por_empleado['FactorIncentivo'] = np.where(
    (maestra_resultados_por_empleado['PorcentajeCumplimiento']>1.06) & (maestra_resultados_por_empleado['FactorIncentivo'].isnull()),
    2.5,
    maestra_resultados_por_empleado['FactorIncentivo']
)

In [241]:
maestra_resultados_por_empleado_copy = maestra_resultados_por_empleado.copy()
maestra_resultados_por_empleado = maestra_resultados_por_empleado_copy.copy()

In [242]:
maestra_resultados_por_empleado[
     (maestra_resultados_por_empleado['Fecha']=='2025-12-01') &
    (maestra_resultados_por_empleado['Contexto']=='79539822') &
    (maestra_resultados_por_empleado['Variable']=='ObjetivosCualitativos')
]

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,...,Nombre variable,Nombre consecutivo,_merge,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable,FactorIncentivo
684,684,79539822,2025-12-01,1.2,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,Objetivos cualitativos,NaN,both,AD2,1.0,GONZALEZ FRANCO,OMAR,2019-03-01,3.495833e+06,2.5

In [243]:
maestra_resultados_por_empleado

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,...,Nombre variable,Nombre consecutivo,_merge,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable,FactorIncentivo
0,0,5004523,2025-12-01,1.00,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.545833e+06,1.0
1,1,5004523,2025-08-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.543750e+06,0.5
2,2,5004523,2025-11-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.545455e+06,0.5
3,3,5004523,2025-09-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.544444e+06,0.5
4,4,5004523,2025-10-01,0.80,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,Objetivos cualitativos,NaN,both,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.545000e+06,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27018,1831,5016782,2025-07-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN,NaN
27019,1832,5016782,2025-03-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN,NaN
27020,1833,5016782,2025-02-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN,NaN
27021,1834,5016782,2025-01-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN,NaN
27022,1835,5016782,2025-06-01,0.94,KpiCalidad,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,left_only,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [244]:
maestra_resultados_por_empleado = maestra_resultados_por_empleado[maestra_resultados_por_empleado['Fecha'].notnull()]
maestra_resultados_por_empleado['FactorMes'] = pd.DatetimeIndex(maestra_resultados_por_empleado['Fecha']).month
maestra_resultados_por_empleado['FactorMes'] = maestra_resultados_por_empleado['FactorMes'].astype('int')

maestra_resultados_por_empleado['Liquidado'] = np.where(
    (maestra_resultados_por_empleado['Real'] == 0) | (maestra_resultados_por_empleado['Presupuesto'] == 0),
    0,
    maestra_resultados_por_empleado['SalarioVariable'] *
    maestra_resultados_por_empleado['Porcentaje'] *
    maestra_resultados_por_empleado['FactorIncentivo']
)

In [ ]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '79539822')
    (maestra_resultados_por_empleado['Fecha'] == '2025-12-01')
][["Fecha", "Variable", "FechaIngreso", "FactorMes", "CodigoEmpleado", "Liquidado"]]

In [76]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '5032456')
   ## (maestra_resultados_por_empleado['Fecha'] == '2025-03-01')
][["Fecha", "Variable", "FechaIngreso", "FactorMes", "CodigoEmpleado", "Liquidado"]]

           Fecha               Variable FechaIngreso  FactorMes CodigoEmpleado
240   2025-12-01  ObjetivosCualitativos   2025-04-01         12        5032456
241   2025-08-01  ObjetivosCualitativos   2025-04-01          8        5032456
242   2025-11-01  ObjetivosCualitativos   2025-04-01         11        5032456
243   2025-09-01  ObjetivosCualitativos   2025-04-01          9        5032456
244   2025-10-01  ObjetivosCualitativos   2025-04-01         10        5032456
...          ...                    ...          ...        ...            ...
24422 2025-08-01           EBITCOGSPais   2025-04-01          8        5032456
24500 2025-09-01           EBITCOGSPais   2025-04-01          9        5032456
24578 2025-10-01           EBITCOGSPais   2025-04-01         10        5032456
24656 2025-11-01           EBITCOGSPais   2025-04-01         11        5032456
24734 2025-12-01           EBITCOGSPais   2025-04-01         12        5032456

[68 rows x 5 columns]

In [77]:
try:
    maestra_resultados_por_empleado['DifMonths'] = ((maestra_resultados_por_empleado.Fecha - maestra_resultados_por_empleado.FechaIngreso)/np.timedelta64(1, 'M'))
except:
    maestra_resultados_por_empleado['DifMonths'] = 0
maestra_resultados_por_empleado.head()

,Unnamed: 0,Contexto,Fecha,PorcentajeCumplimiento,Variable,Real,Presupuesto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,...,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable,FactorIncentivo,FactorMes,Liquidado,DifMonths
0,0,5004523,2025-12-01,1.0,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.545833e+06,1.0,12,381875.000000,0
1,1,5004523,2025-08-01,0.8,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.543750e+06,0.5,8,190781.250000,0
2,2,5004523,2025-11-01,0.8,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.545455e+06,0.5,11,190909.090909,0
3,3,5004523,2025-09-01,0.8,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.544444e+06,0.5,9,190833.333333,0
4,4,5004523,2025-10-01,0.8,ObjetivosCualitativos,NaN,NaN,0.0,0.0,0.0,...,VC,3.0,ACOSTA PORTILLO,SOBEYDA DEL SOCORRO,2023-10-01,2.545000e+06,0.5,10,190875.000000,0

In [78]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '5032456')
   ## (maestra_resultados_por_empleado['Fecha'] == '2025-03-01')
][["Fecha", "Variable", "FechaIngreso", "FactorMes", "DifMonths", "CodigoEmpleado"]]

,Fecha,Variable,FechaIngreso,FactorMes,DifMonths,CodigoEmpleado
240,2025-12-01,ObjetivosCualitativos,2025-04-01,12,0,5032456
241,2025-08-01,ObjetivosCualitativos,2025-04-01,8,0,5032456
242,2025-11-01,ObjetivosCualitativos,2025-04-01,11,0,5032456
243,2025-09-01,ObjetivosCualitativos,2025-04-01,9,0,5032456
244,2025-10-01,ObjetivosCualitativos,2025-04-01,10,0,5032456
...,...,...,...,...,...,...
24422,2025-08-01,EBITCOGSPais,2025-04-01,8,0,5032456
24500,2025-09-01,EBITCOGSPais,2025-04-01,9,0,5032456
24578,2025-10-01,EBITCOGSPais,2025-04-01,10,0,5032456
24656,2025-11-01,EBITCOGSPais,2025-04-01,11,0,5032456
24734,2025-12-01,EBITCOGSPais,2025-04-01,12,0,5032456

In [79]:

try:
    maestra_resultados_por_empleado['DifMonths'] = ((maestra_resultados_por_empleado.Fecha - maestra_resultados_por_empleado.FechaIngreso)/np.timedelta64(1, 'M'))
except:
    maestra_resultados_por_empleado['DifMonths'] = 0
maestra_resultados_por_empleado['DifMonths'].fillna(0, inplace=True)
maestra_resultados_por_empleado['DifMonths'] = maestra_resultados_por_empleado['DifMonths'].apply(lambda x: round(x, 0))
maestra_resultados_por_empleado['DifMonths'] = maestra_resultados_por_empleado['DifMonths'].astype('int')

maestra_resultados_por_empleado['DifMonths'] = maestra_resultados_por_empleado.groupby(['CodigoEmpleado'])['DifMonths'].transform(min)
maestra_resultados_por_empleado['DifMonths'] = np.where(
    maestra_resultados_por_empleado['DifMonths']>0, 0, maestra_resultados_por_empleado['DifMonths']
)
maestra_resultados_por_empleado['NuevoFactor'] = maestra_resultados_por_empleado['FactorMes'] + maestra_resultados_por_empleado['DifMonths']
maestra_resultados_por_empleado['NuevoFactor'] = maestra_resultados_por_empleado['NuevoFactor'].apply(lambda x: 0 if x<0 else x)

###
_excepciones_factor_mes = [
    # Garantizados para VEs y VCs
    {
        'TipoEmpleado': ['VC', 'VE'],
        'FechaInicial': '2022-03-01',
        'FechaFinal': '2022-12-01',
        'SumFactorMes': -2
    }
]
for excepcion in _excepciones_factor_mes:
    maestra_resultados_por_empleado['NuevoFactor'] = np.where(
        (
            (maestra_resultados_por_empleado['TipoEmpleado'].isin(excepcion['TipoEmpleado'])) &
            (maestra_resultados_por_empleado['Fecha'] >= excepcion['FechaInicial']) &
            (maestra_resultados_por_empleado['Fecha'] <= excepcion['FechaFinal'])
        ),
        maestra_resultados_por_empleado['NuevoFactor'] + excepcion['SumFactorMes'],
        maestra_resultados_por_empleado['NuevoFactor']
    )

maestra_resultados_por_empleado['NuevoFactor'] = np.where(
    maestra_resultados_por_empleado['NuevoFactor'] < 1,
    1,
    maestra_resultados_por_empleado['NuevoFactor']
)
maestra_resultados_por_empleado['NuevoFactorBK'] = maestra_resultados_por_empleado['NuevoFactor']
###

maestra_resultados_por_empleado['Liquidado'] = maestra_resultados_por_empleado['Liquidado']*maestra_resultados_por_empleado['NuevoFactor']

maestra_resultados_por_empleado = maestra_resultados_por_empleado[maestra_resultados_por_empleado['CodigoEmpleado'].notnull()]

C:\Users\HP\AppData\Local\Temp\ipykernel_39284\2967837714.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  maestra_resultados_por_empleado['DifMonths'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\2967837714.py:9: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  maestra_resultados_por_empleado['DifMonths'] = maestra_resultados_por_empleado.groupby(['CodigoEmpleado'])['DifMonths'].transform(min)

In [80]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '5032456')
   ## (maestra_resultados_por_empleado['Fecha'] == '2025-03-01')
][["Fecha", "Variable", "FechaIngreso", "FactorMes", "DifMonths", "CodigoEmpleado"]]

,Fecha,Variable,FechaIngreso,FactorMes,DifMonths,CodigoEmpleado
240,2025-12-01,ObjetivosCualitativos,2025-04-01,12,0,5032456
241,2025-08-01,ObjetivosCualitativos,2025-04-01,8,0,5032456
242,2025-11-01,ObjetivosCualitativos,2025-04-01,11,0,5032456
243,2025-09-01,ObjetivosCualitativos,2025-04-01,9,0,5032456
244,2025-10-01,ObjetivosCualitativos,2025-04-01,10,0,5032456
...,...,...,...,...,...,...
24422,2025-08-01,EBITCOGSPais,2025-04-01,8,0,5032456
24500,2025-09-01,EBITCOGSPais,2025-04-01,9,0,5032456
24578,2025-10-01,EBITCOGSPais,2025-04-01,10,0,5032456
24656,2025-11-01,EBITCOGSPais,2025-04-01,11,0,5032456
24734,2025-12-01,EBITCOGSPais,2025-04-01,12,0,5032456

In [81]:
maestra_resultados_por_empleado[
     (maestra_resultados_por_empleado['Fecha']=='2024-05-01') &
    (maestra_resultados_por_empleado['Contexto']=='291169471')
]['Liquidado']

Series([], Name: Liquidado, dtype: float64)

### Calculo sobre maestra resultados por empleado centro costo

In [82]:
maestra_resultados_por_empleado_centro_costo_final = maestra_resultados_por_empleado_centro_costo.merge(
    df_factores_liquidacion,
    on=['TipoEmpleado', 'PorcentajeCumplimiento'],
    how='left'
)

maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo'] = np.where(
    ((maestra_resultados_por_empleado_centro_costo_final['Fecha'] >= '2022-08-01') & 
     (maestra_resultados_por_empleado_centro_costo_final['PorcentajeCumplimiento'] == 0) & 
     (maestra_resultados_por_empleado_centro_costo_final['Presupuesto'] == 0) & 
     (maestra_resultados_por_empleado_centro_costo_final['Real'] == 0)),
    0.25,
    maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo']
)
maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo'] = np.where(
    ((maestra_resultados_por_empleado_centro_costo_final['Fecha'] >= '2022-08-01') & 
     (maestra_resultados_por_empleado_centro_costo_final['PorcentajeCumplimiento'] == 0) & 
     (maestra_resultados_por_empleado_centro_costo_final['Presupuesto'] == 0) & 
     (maestra_resultados_por_empleado_centro_costo_final['Real'] > 0)),
    0.5,
    maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo']
)

##
_excepciones_porcentaje_cumplimiento = [
    # {
    #     'TipoEmpleado': 'VC',
    #     'AreaCalculo': 7,
    #     'Variable': 'VentaFacturadaZonaCargoIndividualSub',
    #     'Consecutivo': 4,
    #     'FechaInicial': '2021-02-01',
    #     'FechaFinal': '2021-06-01',
    #     'PorcentajeCumplimiento': 1,
    #     'FactorIncentivo': 1,
    #     'Codigos': ['5003527']
    # }
]

for excepcion in _excepciones_porcentaje_cumplimiento:
    maestra_resultados_por_empleado_centro_costo_final['PorcentajeCumplimiento'] = np.where(
        (
            (maestra_resultados_por_empleado_centro_costo_final['CodigoEmpleado'].isin(excepcion['Codigos'])) &
            (maestra_resultados_por_empleado_centro_costo_final['Consecutivo'] == excepcion['Consecutivo']) &
            (maestra_resultados_por_empleado_centro_costo_final['Variable'] == excepcion['Variable']) &
            (maestra_resultados_por_empleado_centro_costo_final['Fecha'] >= excepcion['FechaInicial']) &
            (maestra_resultados_por_empleado_centro_costo_final['Fecha'] <= excepcion['FechaFinal'])
        ),
        excepcion['PorcentajeCumplimiento'],
        maestra_resultados_por_empleado_centro_costo_final['PorcentajeCumplimiento']
    )
    maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo'] = np.where(
        (
            (maestra_resultados_por_empleado_centro_costo_final['CodigoEmpleado'].isin(excepcion['Codigos'])) &
            (maestra_resultados_por_empleado_centro_costo_final['Consecutivo'] == excepcion['Consecutivo']) &
            (maestra_resultados_por_empleado_centro_costo_final['Variable'] == excepcion['Variable']) &
            (maestra_resultados_por_empleado_centro_costo_final['Fecha'] >= excepcion['FechaInicial']) &
            (maestra_resultados_por_empleado_centro_costo_final['Fecha'] <= excepcion['FechaFinal'])
        ),
        excepcion['FactorIncentivo'],
        maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo']
    )
##

maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo'] = np.where(
    (maestra_resultados_por_empleado_centro_costo_final['PorcentajeCumplimiento']<0.9) & (maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo'].isnull()),
    0,
    maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo']
)
maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo'] = np.where(
    (maestra_resultados_por_empleado_centro_costo_final['PorcentajeCumplimiento']>1.06) & (maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo'].isnull()),
    2.5,
    maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo']
)
maestra_resultados_por_empleado_centro_costo_final = maestra_resultados_por_empleado_centro_costo_final[maestra_resultados_por_empleado_centro_costo_final['Fecha'].notnull()]
maestra_resultados_por_empleado_centro_costo_final['FactorMes'] = pd.DatetimeIndex(maestra_resultados_por_empleado_centro_costo_final['Fecha']).month
maestra_resultados_por_empleado_centro_costo_final['FactorMes'] = maestra_resultados_por_empleado_centro_costo_final['FactorMes'].astype('int')
maestra_resultados_por_empleado_centro_costo_final['Liquidado'] = maestra_resultados_por_empleado_centro_costo_final['SalarioVariable']*maestra_resultados_por_empleado_centro_costo_final['Porcentaje']
maestra_resultados_por_empleado_centro_costo_final['Liquidado'] = maestra_resultados_por_empleado_centro_costo_final['Liquidado']*maestra_resultados_por_empleado_centro_costo_final['FactorIncentivo']

try:
    maestra_resultados_por_empleado_centro_costo_final['DifMonths'] = ((maestra_resultados_por_empleado_centro_costo_final.Fecha - maestra_resultados_por_empleado_centro_costo_final.FechaIngreso)/np.timedelta64(1, 'M'))
except:
    maestra_resultados_por_empleado_centro_costo_final['DifMonths'] = 0
maestra_resultados_por_empleado_centro_costo_final['DifMonths'].fillna(0, inplace=True)
maestra_resultados_por_empleado_centro_costo_final['DifMonths'] = maestra_resultados_por_empleado_centro_costo_final['DifMonths'].apply(lambda x: round(x, 0))
maestra_resultados_por_empleado_centro_costo_final['DifMonths'] = maestra_resultados_por_empleado_centro_costo_final['DifMonths'].astype('int')

maestra_resultados_por_empleado_centro_costo_final['DifMonths'] = maestra_resultados_por_empleado_centro_costo_final.groupby(['CodigoEmpleado'])['DifMonths'].transform(min)
maestra_resultados_por_empleado_centro_costo_final['DifMonths'] = np.where(
    maestra_resultados_por_empleado_centro_costo_final['DifMonths']>0, 0, maestra_resultados_por_empleado_centro_costo_final['DifMonths']
)
maestra_resultados_por_empleado_centro_costo_final['NuevoFactor'] = maestra_resultados_por_empleado_centro_costo_final['FactorMes'] + maestra_resultados_por_empleado_centro_costo_final['DifMonths']
maestra_resultados_por_empleado_centro_costo_final['NuevoFactor'] = maestra_resultados_por_empleado_centro_costo_final['NuevoFactor'].apply(lambda x: 0 if x<0 else x)

###
_excepciones_factor_mes = [
    # Garantizados para VEs y VCs
    {
        'TipoEmpleado': ['VC', 'VE'],
        'FechaInicial': '2022-03-01',
        'FechaFinal': '2022-12-01',
        'SumFactorMes': -2
    }
]
for excepcion in _excepciones_factor_mes:
    maestra_resultados_por_empleado_centro_costo_final['NuevoFactor'] = np.where(
        (
            (maestra_resultados_por_empleado_centro_costo_final['TipoEmpleado'].isin(excepcion['TipoEmpleado'])) &
            (maestra_resultados_por_empleado_centro_costo_final['Fecha'] >= excepcion['FechaInicial']) &
            (maestra_resultados_por_empleado_centro_costo_final['Fecha'] <= excepcion['FechaFinal'])
        ),
        maestra_resultados_por_empleado_centro_costo_final['NuevoFactor'] + excepcion['SumFactorMes'],
        maestra_resultados_por_empleado_centro_costo_final['NuevoFactor']
    )

maestra_resultados_por_empleado_centro_costo_final['NuevoFactor'] = np.where(
    maestra_resultados_por_empleado_centro_costo_final['NuevoFactor'] < 1,
    1,
    maestra_resultados_por_empleado_centro_costo_final['NuevoFactor']
)
maestra_resultados_por_empleado_centro_costo_final['NuevoFactorBK'] = maestra_resultados_por_empleado_centro_costo_final['NuevoFactor']
###

maestra_resultados_por_empleado_centro_costo_final['Liquidado'] = maestra_resultados_por_empleado_centro_costo_final['Liquidado']*maestra_resultados_por_empleado_centro_costo_final['NuevoFactor']

maestra_resultados_por_empleado_centro_costo_final = maestra_resultados_por_empleado_centro_costo_final[maestra_resultados_por_empleado_centro_costo_final['CodigoEmpleado'].notnull()]

C:\Users\HP\AppData\Local\Temp\ipykernel_39284\1614624925.py:84: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  maestra_resultados_por_empleado_centro_costo_final['DifMonths'].fillna(0, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\1614624925.py:88: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  maestra_resultados_por_empleado_centro_costo_final['DifMonths'] = maestra_resultados_por_empleado_centro_costo_final.groupby(['CodigoEmpleado'])['DifMonths'].transform(min)

In [83]:
maestra_resultados_por_empleado_centro_costo_final.head()

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,...,Apellidos,Nombre,FechaIngreso,SalarioVariable,FactorIncentivo,FactorMes,Liquidado,DifMonths,NuevoFactor,NuevoFactorBK
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0.56,0.0,...,NaN,NaN,NaT,NaN,0.0,1,NaN,0,1,1
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,1.07,0.0,...,NaN,NaN,NaT,NaN,2.5,1,NaN,0,1,1
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,1.28,0.0,...,NaN,NaN,NaT,NaN,2.5,1,NaN,0,1,1
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0.23,0.0,...,NaN,NaN,NaT,NaN,0.0,1,NaN,0,1,1
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,1.68,0.0,...,NaN,NaN,NaT,NaN,2.5,1,NaN,0,1,1

In [84]:
maestra_resultados_por_empleado_centro_costo_final[maestra_resultados_por_empleado_centro_costo_final['CodigoEmpleado'] == '1098612757']

Empty DataFrame
Columns: [Contexto, Fecha, GrupoProducto, Division, CodigoCentroCosto, Real, Presupuesto, Variable, PorcentajeCumplimiento, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, SalarioVariable, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, NuevoFactorBK]
Index: []

[0 rows x 29 columns]

## Se calculan los resultados por mes

In [85]:
lista_variables_rentabilidad_acumuladas = [
    'RentabilidadBbraunPaisAntesDeImpuestos',
    'RentabilidadDivisionGrupoClientesCM3',
    'RentabilidadDivisionGrupoClientesCM3Sub',
    'RentabilidadUnidadNegocioCM2',
    'RentabilidadUnidadNegocioCM2Sub',
    'RentabilidadUnidadNegocioCM3',
    'RentabilidadUnidadNegocioCM3Sub',
    'TotalRentabilidadBraunAntesDeImpuestosCM5',
    'VentaFacturadaPrevioNotasCreditoTP',
    # 2022
    'RentabilidadCompaniaCM3',
    'RentabilidadZonaHospitalarioCM2',
    # 2024
    'RentabilidadUnidadNegocioCM2COGSSUB',
    'RentabilidadDivisionCM2COGsSub',
    'EBITCOGSPais',
    'EBITCOGSPaisSUB'
]

def calcular_resultado_mes(group):
    valor_previo_real = 0
    valor_previo_presupuesto = 0
    for index, item in group.iterrows():
        if item['Variable'] in lista_variables_rentabilidad_acumuladas:
            resultado_real_mes = item['Real']
            resultado_presupuesto_mes = item['Presupuesto']
        else:
            resultado_real_mes = item['Real'] - valor_previo_real
            resultado_presupuesto_mes = item['Presupuesto'] - valor_previo_presupuesto
        
        group.at[index, 'ResultadoRealMes'] = resultado_real_mes
        group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes

        porcentaje_cumplimiento_mes = 0
        if resultado_presupuesto_mes == 0:
            porcentaje_cumplimiento_mes = 0
        elif resultado_real_mes - resultado_presupuesto_mes < 0:
            porcentaje_cumplimiento_mes = 1 + ((resultado_real_mes - resultado_presupuesto_mes) / abs(resultado_presupuesto_mes))
        elif resultado_real_mes - resultado_presupuesto_mes > 0:
            porcentaje_cumplimiento_mes = 1 + abs((resultado_real_mes - resultado_presupuesto_mes) / abs(resultado_presupuesto_mes))
        else:
            porcentaje_cumplimiento_mes = resultado_real_mes / resultado_presupuesto_mes

        group.at[index, 'PorcentajeCumplimientoMes'] = round(porcentaje_cumplimiento_mes, 2)
        
        valor_previo_real = item['Real']
        valor_previo_presupuesto = item['Presupuesto']
    return group

### Maestra Resultados por Empleado vs Resultado Detallado Histórico

In [86]:
maestra_resultados_por_empleado['Real'].fillna(0,inplace=True)
maestra_resultados_por_empleado['Presupuesto'].fillna(0,inplace=True)
maestra_resultados_por_empleado['ResultadoPresupuesto'] = 0
maestra_resultados_por_empleado['ResultadoRealMes'] = 0
maestra_resultados_por_empleado['PorcentajeCumplimientoMes'] = 0
maestra_resultados_por_empleado['PorcentajeCumplimientoMes'] = maestra_resultados_por_empleado['PorcentajeCumplimientoMes'].astype('float')
maestra_resultados_por_empleado = maestra_resultados_por_empleado.groupby(['CodigoEmpleado', 'Variable', 'Contexto'], group_keys=False).apply(calcular_resultado_mes)

maestra_resultados_por_empleado

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

C:\Users\HP\AppData\Local\Temp\ipykernel_39284\583539735.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  maestra_resultados_por_empleado['Real'].fillna(0,inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\583539735.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  maestra_resultados_por_empleado['Presupuesto'].fillna(0,inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1964336.53623359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2648293.92045043' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1494836.7005250708' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2160922.078280833' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '470848.6298131504' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '701114.8124496826' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '8773.891182592242' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '42676.48996297359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '20027835921.21' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '21885622149.03167' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1964336.53623359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2648293.92045043' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '9930397.33266733' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '11133754.5334147' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1964336.53623359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2648293.92045043' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1494836.7005250708' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2160922.078280833' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '470848.6298131504' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '701114.8124496826' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '8773.891182592242' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '42676.48996297359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1964336.53623359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2648293.92045043' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1494836.7005250708' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2160922.078280833' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '470848.6298131504' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '701114.8124496826' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '8773.891182592242' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '42676.48996297359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1964336.53623359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2648293.92045043' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '328391.0605037843' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '436484.0782768876' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '63027.172466887416' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '94236.783978088' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '206133.05754966888' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '355025.96750911605' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '145606.36240066227' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '241763.0381907411' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '42137.058753547775' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '110644.0737319188' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1964336.53623359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2648293.92045043' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1494836.7005250708' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2160922.078280833' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '470848.6298131504' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '701114.8124496826' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '8773.891182592242' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '42676.48996297359' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoPresupuesto'] = resultado_presupuesto_mes
C:\Users\HP\AppData\Local\Temp\ipykernel_39284\3155329719.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '20027835921.21' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  group.at[index, 'ResultadoRealMes'] = resultado_real_mes

In [87]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['Contexto']=='52875549')
]

Empty DataFrame
Columns: [Unnamed: 0, Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, _merge, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, SalarioVariable, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, NuevoFactorBK, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes]
Index: []

[0 rows x 31 columns]

In [88]:
df_resultado_detallado_previo[df_resultado_detallado_previo['CodigoEmpleado'] == '52875549.0']

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, Real, Presupuesto, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, SalarioVariable, AreaCalculo, Apellidos, Nombre, FechaIngreso, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes]
Index: []

[0 rows x 23 columns]

In [89]:
df_resultado_detallado_previo[
    (df_resultado_detallado_previo['Contexto']=='1111117') &
    (df_resultado_detallado_previo['Variable']=='ObjetivosCualitativos')
]

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, Real, Presupuesto, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, SalarioVariable, AreaCalculo, Apellidos, Nombre, FechaIngreso, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes]
Index: []

[0 rows x 23 columns]

In [90]:
# Se une el resultadio histórico con el actual, de tal forma que al histórico se le agregan únicamenet 
# los resultados correspondientes al mes que se está liquidando
resultado_detallado_historico = df_resultado_detallado_previo.copy()
# Filtrar el DataFrame para encontrar las filas donde 'CodigoEmpleado' termina con '.0'
resultado_detallado_historico[resultado_detallado_historico['CodigoEmpleado'].astype(str).str.endswith('.0')].head()
resultado_detallado_historico['CodigoEmpleado'] = resultado_detallado_historico['CodigoEmpleado'].astype(str).str.replace(r'(\d+)\.0$', r'\1', regex=True)
resultado_detallado_historico

,Contexto,Fecha,Variable,PorcentajeCumplimiento,Real,Presupuesto,CodigoEmpleado,Porcentaje,Consecutivo,TipoEmpleado,...,Nombre,FechaIngreso,FactorIncentivo,FactorMes,Liquidado,DifMonths,NuevoFactor,ResultadoPresupuesto,ResultadoRealMes,PorcentajeCumplimientoMes
0,1013587064,2025-01-01,ObjetivosCualitativos,0.90,0.000000e+00,0.000000e+00,1013587064,0.4,0,AD2,...,FABIAN DAVID,2021-01-01,0.500,1,100000.0,0,1,0.0,0.0,0.00
1,1013587064_2,2025-01-01,KpisSurgical,1.12,0.000000e+00,0.000000e+00,1013587064,0.2,2,AD2,...,FABIAN DAVID,2021-01-01,2.500,1,250000.0,0,1,0.0,0.0,0.00
2,1013587064_3,2025-01-01,KpisSurgical,1.01,0.000000e+00,0.000000e+00,1013587064,0.2,3,AD2,...,FABIAN DAVID,2021-01-01,1.200,1,120000.0,0,1,0.0,0.0,0.00
3,1020792924,2025-01-01,ObjetivosCualitativos,0.90,0.000000e+00,0.000000e+00,1020792924,0.4,0,AD2,...,YEFFER ALEXANDER,2024-07-01,0.500,1,100000.0,0,1,0.0,0.0,0.00
4,1020792924_2,2025-01-01,KpisSurgical,1.12,0.000000e+00,0.000000e+00,1020792924,0.2,2,AD2,...,YEFFER ALEXANDER,2024-07-01,2.500,1,250000.0,0,1,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8265,94526955,2025-11-01,ObjetivosCualitativos,0.88,0.000000e+00,0.000000e+00,94526955,0.2,0,MK1,...,JUAN FELIPE,2025-06-01,0.500,11,2940000.0,-5,6,0.0,0.0,0.00
8266,94526955_1,2025-11-01,VentaFacturadaBraunPaisSUB,0.95,4.560969e+07,4.812728e+07,94526955,0.2,1,MK1,...,JUAN FELIPE,2025-06-01,0.792,11,4656960.0,-5,6,5183831.0,5298694.0,1.02
8267,94526955_2,2025-11-01,VentaFacturadaBraunPaisSUB,1.01,2.637021e+07,2.601364e+07,94526955,0.2,2,MK1,...,JUAN FELIPE,2025-06-01,1.375,11,8085000.0,-5,6,2646001.0,2110090.0,0.80
8268,94526955_1,2025-11-01,EBITCOGSPaisSUB,0.95,1.053161e+07,1.111725e+07,94526955,0.2,1,MK1,...,JUAN FELIPE,2025-06-01,0.792,11,4656960.0,-5,6,1443950.0,1640513.0,1.14
8269,94526955_2,2025-11-01,EBITCOGSPaisSUB,1.05,3.819836e+06,3.654547e+06,94526955,0.2,2,MK1,...,JUAN FELIPE,2025-06-01,2.500,11,14700000.0,-5,6,466308.0,520693.0,1.12

In [91]:
# resultado_detallado_historico.info()
# resultado_detallado_historico.to_excel('resultado_detallado_historico.xlsx')

In [92]:
resultado_detallado_historico[
    (resultado_detallado_historico['CodigoEmpleado']== '1111135.0')
]

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, Real, Presupuesto, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, SalarioVariable, AreaCalculo, Apellidos, Nombre, FechaIngreso, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes]
Index: []

[0 rows x 23 columns]

In [93]:
last_date_historico = resultado_detallado_historico['Fecha'].max()
last_date_historico = None if pd.isnull(last_date_historico) else last_date_historico

try:
    maestra_resultados_por_empleado = maestra_resultados_por_empleado[
        (maestra_resultados_por_empleado['Fecha']<=fecha_liquidacion)
    ]
    if last_date_historico:
        maestra_resultados_por_empleado = maestra_resultados_por_empleado[
            maestra_resultados_por_empleado['Fecha']>last_date_historico
        ]
except:
    raise

In [94]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['Contexto']=='1111117') &
    (maestra_resultados_por_empleado['Variable']=='ObjetivosCualitativos')
]

Empty DataFrame
Columns: [Unnamed: 0, Contexto, Fecha, PorcentajeCumplimiento, Variable, Real, Presupuesto, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, _merge, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, SalarioVariable, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, NuevoFactorBK, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes]
Index: []

[0 rows x 31 columns]

In [95]:
maestra_resultados_por_empleado = pd.concat([resultado_detallado_historico, maestra_resultados_por_empleado])
maestra_resultados_por_empleado = maestra_resultados_por_empleado.sort_values(by=['CodigoEmpleado', 'Fecha'])
maestra_resultados_por_empleado

,Contexto,Fecha,Variable,PorcentajeCumplimiento,Real,Presupuesto,CodigoEmpleado,Porcentaje,Consecutivo,TipoEmpleado,...,ResultadoRealMes,PorcentajeCumplimientoMes,Unnamed: 0,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,Nombre variable,Nombre consecutivo,_merge,NuevoFactorBK
6683,1004206367,2025-10-01,ObjetivosCualitativos,0.80,0.000000e+00,0.000000e+00,1004206367,0.20,0.0,MK,...,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6684,mk_13_1,2025-10-01,VentaFacturadaUnidadNegocioSub,0.93,2.817834e+07,3.020653e+07,1004206367,0.24,1.0,MK,...,2964885.0,0.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6685,mk_13_2,2025-10-01,VentaFacturadaUnidadNegocioSub,1.01,9.965766e+06,9.889429e+06,1004206367,0.14,2.0,MK,...,1113630.0,1.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6686,mk_13_3,2025-10-01,VentaFacturadaUnidadNegocioSub,0.47,4.806767e+05,1.022525e+06,1004206367,0.02,3.0,MK,...,20047.0,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6687,EBITCOGSP,2025-10-01,EBITCOGSPais,0.92,8.891097e+06,9.673296e+06,1004206367,0.40,0.0,MK,...,995624.0,0.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26963,70038624,2025-12-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,nan,NaN,NaN,NaN,...,0.0,0.00,1776.0,0.0,0.0,0.0,NaN,NaN,left_only,12.0
26975,70051944,2025-12-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,nan,NaN,NaN,NaN,...,0.0,0.00,1788.0,0.0,0.0,0.0,NaN,NaN,left_only,12.0
26987,5016700,2025-12-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,nan,NaN,NaN,NaN,...,0.0,0.00,1800.0,0.0,0.0,0.0,NaN,NaN,left_only,12.0
26999,5041312,2025-12-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,nan,NaN,NaN,NaN,...,0.0,0.00,1812.0,0.0,0.0,0.0,NaN,NaN,left_only,12.0
27011,5016782,2025-12-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,nan,NaN,NaN,NaN,...,0.0,0.00,1824.0,0.0,0.0,0.0,NaN,NaN,left_only,12.0

### Maestra Resultados por Empleado Centro Costo vs Resultado Detallado Histórico

In [96]:
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)
# Código que genera el FutureWarning

maestra_resultados_por_empleado_centro_costo_final['Real'].fillna(0,inplace=True)
maestra_resultados_por_empleado_centro_costo_final['Presupuesto'].fillna(0,inplace=True)
maestra_resultados_por_empleado_centro_costo_final['ResultadoPresupuesto'] = 0
maestra_resultados_por_empleado_centro_costo_final['ResultadoRealMes'] = 0
maestra_resultados_por_empleado_centro_costo_final['PorcentajeCumplimientoMes'] = 0
maestra_resultados_por_empleado_centro_costo_final['PorcentajeCumplimientoMes'] = maestra_resultados_por_empleado_centro_costo_final['PorcentajeCumplimientoMes'].astype('float')
maestra_resultados_por_empleado_centro_costo_final = maestra_resultados_por_empleado_centro_costo_final.groupby(['CodigoEmpleado', 'Variable', 'Contexto'], group_keys=False).apply(calcular_resultado_mes)

maestra_resultados_por_empleado_centro_costo_final.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_39284\2949112875.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  maestra_resultados_por_empleado_centro_costo_final = maestra_resultados_por_empleado_centro_costo_final.groupby(['CodigoEmpleado', 'Variable', 'Contexto'], group_keys=False).apply(calcular_resultado_mes)

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,...,SalarioVariable,FactorIncentivo,FactorMes,Liquidado,DifMonths,NuevoFactor,NuevoFactorBK,ResultadoPresupuesto,ResultadoRealMes,PorcentajeCumplimientoMes
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0.56,0.0,...,NaN,0.0,1,NaN,0,1,1,5.425101e+08,3.060539e+08,0.56
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,1.07,0.0,...,NaN,2.5,1,NaN,0,1,1,1.523606e+09,1.913197e+09,1.26
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,1.28,0.0,...,NaN,2.5,1,NaN,0,1,1,-7.778677e+08,-5.714170e+08,1.27
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0.23,0.0,...,NaN,0.0,1,NaN,0,1,1,-1.278737e+09,-1.645675e+09,0.71
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,1.68,0.0,...,NaN,2.5,1,NaN,0,1,1,1.702568e+08,2.989678e+08,1.76

In [97]:
df_resultado_detallado_previo.copy().merge(
    df_area_calculo_sba_centros_costos.rename(columns={'ConsecutivoParrilla':'Consecutivo'}),
    on=['AreaCalculo', 'Consecutivo','TipoEmpleado'],
    how='left'    
)

# Se une el resultadio histórico con el actual, de tal forma que al histórico se le agregan únicamenet 
# los resultados correspondientes al mes que se está liquidando
resultado_detallado_historico = df_resultado_detallado_previo.copy()
last_date_historico = resultado_detallado_historico['Fecha'].max()
last_date_historico = None if pd.isnull(last_date_historico) else last_date_historico

try:
    maestra_resultados_por_empleado_centro_costo_final = maestra_resultados_por_empleado_centro_costo_final[
        (maestra_resultados_por_empleado_centro_costo_final['Fecha']<=fecha_liquidacion)
    ]
    if last_date_historico:
        maestra_resultados_por_empleado_centro_costo_final = maestra_resultados_por_empleado_centro_costo_final[
            maestra_resultados_por_empleado_centro_costo_final['Fecha']>last_date_historico
        ]
except:
    raise

maestra_resultados_por_empleado_centro_costo_final = pd.concat([resultado_detallado_historico, maestra_resultados_por_empleado_centro_costo_final])
maestra_resultados_por_empleado_centro_costo_final = maestra_resultados_por_empleado_centro_costo_final.sort_values(by=['CodigoEmpleado', 'Fecha'])
maestra_resultados_por_empleado_centro_costo_final

,Contexto,Fecha,Variable,PorcentajeCumplimiento,Real,Presupuesto,CodigoEmpleado,Porcentaje,Consecutivo,TipoEmpleado,...,PorcentajeCumplimientoMes,GrupoProducto,Division,CodigoCentroCosto,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,Nombre variable,Nombre consecutivo,NuevoFactorBK
6683,1004206367,2025-10-01,ObjetivosCualitativos,0.80,0.000000e+00,0.000000e+00,1004206367,0.20,0.0,MK,...,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6684,mk_13_1,2025-10-01,VentaFacturadaUnidadNegocioSub,0.93,2.817834e+07,3.020653e+07,1004206367,0.24,1.0,MK,...,0.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6685,mk_13_2,2025-10-01,VentaFacturadaUnidadNegocioSub,1.01,9.965766e+06,9.889429e+06,1004206367,0.14,2.0,MK,...,1.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6686,mk_13_3,2025-10-01,VentaFacturadaUnidadNegocioSub,0.47,4.806767e+05,1.022525e+06,1004206367,0.02,3.0,MK,...,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6687,EBITCOGSP,2025-10-01,EBITCOGSPais,0.92,8.891097e+06,9.673296e+06,1004206367,0.40,0.0,MK,...,0.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35133,70002068_3,2025-12-01,VentaFacturadaPortafolioZonaClusterSub,0.36,9.752944e+06,2.680000e+07,nan,NaN,NaN,NaN,...,0.00,006,AE,323007350,0.000000e+00,0.000000e+00,0.000000,NaN,NaN,12.0
35927,5004293_1,2025-12-01,VentaFacturadaGrupoClientesKAMSSub,1.06,2.942015e+06,2.782123e+06,nan,NaN,NaN,NaN,...,1.11,630,HC,323015090,1.243884e+10,1.355709e+10,0.917516,NaN,NaN,12.0
35950,5004293_2,2025-12-01,VentaFacturadaGrupoClientesKAMSSub,0.90,8.351840e+06,9.262002e+06,nan,NaN,NaN,NaN,...,0.91,630,HC,323015090,3.531158e+10,4.513309e+10,0.782388,NaN,NaN,12.0
35951,5004293_2,2025-12-01,VentaFacturadaGrupoClientesKAMSSub,0.90,8.351840e+06,9.262002e+06,nan,NaN,NaN,NaN,...,0.00,CDK,HC,323015090,3.531158e+10,4.513309e+10,0.782388,NaN,NaN,12.0
35963,5004293_3,2025-12-01,VentaFacturadaGrupoClientesKAMSSub,1.02,3.244078e+06,3.189114e+06,nan,NaN,NaN,NaN,...,1.00,620,HC,323015090,1.371596e+10,1.554033e+10,0.882604,NaN,NaN,12.0

In [98]:
maestra_resultados_por_empleado_centro_costo_final[maestra_resultados_por_empleado_centro_costo_final['CodigoEmpleado'] == '1098612757']

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, Real, Presupuesto, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, SalarioVariable, AreaCalculo, Apellidos, Nombre, FechaIngreso, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes, GrupoProducto, Division, CodigoCentroCosto, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, Nombre variable, Nombre consecutivo, NuevoFactorBK]
Index: []

[0 rows x 32 columns]

In [99]:
maestra_resultados_por_empleado[maestra_resultados_por_empleado['Variable'] == 'VentaFacturadaGrupoClientesKAMSSub']

,Contexto,Fecha,Variable,PorcentajeCumplimiento,Real,Presupuesto,CodigoEmpleado,Porcentaje,Consecutivo,TipoEmpleado,...,ResultadoRealMes,PorcentajeCumplimientoMes,Unnamed: 0,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,Nombre variable,Nombre consecutivo,_merge,NuevoFactorBK
85,kam_2_1,2025-01-01,VentaFacturadaGrupoClientesKAMSSub,0.80,1.098323e+05,1.369594e+05,5004293,0.09,1.0,KAM,...,1.098320e+05,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,kam_2_2,2025-01-01,VentaFacturadaGrupoClientesKAMSSub,0.69,3.150127e+05,4.571789e+05,5004293,0.15,2.0,KAM,...,3.150120e+05,0.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,kam_2_3,2025-01-01,VentaFacturadaGrupoClientesKAMSSub,0.78,1.669767e+05,2.137804e+05,5004293,0.06,3.0,KAM,...,1.669760e+05,0.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
631,kam_2_1,2025-02-01,VentaFacturadaGrupoClientesKAMSSub,0.97,1.456452e+09,1.504837e+09,5004293,0.09,1.0,KAM,...,9.723599e+08,1.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
632,kam_2_2,2025-02-01,VentaFacturadaGrupoClientesKAMSSub,0.77,3.838732e+09,5.014116e+09,5004293,0.15,2.0,KAM,...,2.450294e+09,0.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7821,kam_3_2,2025-11-01,VentaFacturadaGrupoClientesKAMSSub,0.97,3.031510e+06,3.114197e+06,5016988,0.16,2.0,KAM,...,3.235410e+05,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7822,kam_3_3,2025-11-01,VentaFacturadaGrupoClientesKAMSSub,0.74,4.923007e+05,6.684241e+05,5016988,0.08,3.0,KAM,...,5.312400e+04,0.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21100,kam_3_1,2025-12-01,VentaFacturadaGrupoClientesKAMSSub,1.03,8.811909e+06,8.560562e+06,5016988,0.16,1.0,KAM,...,1.280279e+06,1.37,47.0,3.725675e+10,4.171502e+10,0.89,VentaFacturadaGrupoClientesKAMSSub,Medical Care,both,12.0
21112,kam_3_2,2025-12-01,VentaFacturadaGrupoClientesKAMSSub,1.14,3.910997e+06,3.429113e+06,5016988,0.16,2.0,KAM,...,6.249988e+05,1.98,59.0,1.653569e+10,1.670983e+10,0.99,VentaFacturadaGrupoClientesKAMSSub,Surgery & Interventions,both,12.0
21124,kam_3_3,2025-12-01,VentaFacturadaGrupoClientesKAMSSub,0.87,6.418391e+05,7.385423e+05,5016988,0.08,3.0,KAM,...,1.082110e+05,1.54,71.0,2.713696e+09,3.598865e+09,0.75,VentaFacturadaGrupoClientesKAMSSub,Patient Care,both,12.0

In [100]:
maestra_resultados_por_empleado.to_excel('resultados_detallados.xlsx')

In [101]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '1111117') &
     (maestra_resultados_por_empleado['Variable'] == 'ObjetivosCualitativos')
]

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, Real, Presupuesto, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, SalarioVariable, AreaCalculo, Apellidos, Nombre, FechaIngreso, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes, Unnamed: 0, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, Nombre variable, Nombre consecutivo, _merge, NuevoFactorBK]
Index: []

[0 rows x 31 columns]

In [102]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['TipoEmpleado'] == 'VC') |
    (maestra_resultados_por_empleado['TipoEmpleado'] == 'VE')
]['Variable'].drop_duplicates()

5935                     ObjetivosCualitativos
5936                     VentaCobradaBraunPais
5937    VentaFacturadaPortafolioZonaClusterSub
5939         VentaCobradaPortafolioZonaCluster
27                    VentaCobradaBraunCluster
28          VentaFacturadaPortafolioClusterSub
1764          VentaFacturadaPortafolioRenalSub
1765               VentaCobradaPortafolioRenal
Name: Variable, dtype: object

In [103]:
maestra_resultados_por_empleado[maestra_resultados_por_empleado['Variable'] == 'RentabilidadUnidadNegocioCM2COGS']

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, Real, Presupuesto, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, SalarioVariable, AreaCalculo, Apellidos, Nombre, FechaIngreso, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes, Unnamed: 0, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, Nombre variable, Nombre consecutivo, _merge, NuevoFactorBK]
Index: []

[0 rows x 31 columns]

In [104]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['Variable'] == 'VentaFacturadaPortafolioRenalSub')
]

,Contexto,Fecha,Variable,PorcentajeCumplimiento,Real,Presupuesto,CodigoEmpleado,Porcentaje,Consecutivo,TipoEmpleado,...,ResultadoRealMes,PorcentajeCumplimientoMes,Unnamed: 0,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,Nombre variable,Nombre consecutivo,_merge,NuevoFactorBK
1764,70020733_1,2025-03-01,VentaFacturadaPortafolioRenalSub,0.48,4.898174e+07,1.010107e+08,70020733,0.175,1.0,VC,...,4.898174e+07,0.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2552,70020733_1,2025-04-01,VentaFacturadaPortafolioRenalSub,0.82,1.657908e+08,2.020214e+08,70020733,0.175,1.0,VC,...,1.168091e+08,1.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3336,70020733_1,2025-05-01,VentaFacturadaPortafolioRenalSub,0.90,1.947955e+08,2.164515e+08,70020733,0.175,1.0,VC,...,2.900474e+07,2.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4106,70020733_1,2025-06-01,VentaFacturadaPortafolioRenalSub,3.14,1.042674e+09,3.318923e+08,70020733,0.175,1.0,VC,...,8.478787e+08,7.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4875,70020733_1,2025-07-01,VentaFacturadaPortafolioRenalSub,2.04,1.207981e+09,5.916341e+08,70020733,0.175,1.0,VC,...,1.653069e+08,0.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5677,70020733_1,2025-08-01,VentaFacturadaPortafolioRenalSub,1.75,1.511885e+09,8.617008e+08,70020733,0.175,1.0,VC,...,3.039041e+08,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6481,70020733_1,2025-09-01,VentaFacturadaPortafolioRenalSub,1.54,1.631805e+09,1.058887e+09,70020733,0.175,1.0,VC,...,1.199201e+08,0.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7276,70020733_1,2025-10-01,VentaFacturadaPortafolioRenalSub,0.72,1.697115e+09,2.350944e+09,70020733,0.175,1.0,VC,...,6.530957e+07,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8064,70020733_1,2025-11-01,VentaFacturadaPortafolioRenalSub,0.67,1.712784e+09,2.558109e+09,70020733,0.175,1.0,VC,...,1.566934e+07,0.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19762,70020733_1,2025-12-01,VentaFacturadaPortafolioRenalSub,1.65,4.477497e+09,2.718873e+09,70020733,0.175,1.0,VC,...,2.764713e+09,17.20,11.0,0.0,0.0,0.0,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...,both,12.0
1877,70034174_1,2025-03-01,VentaFacturadaPortafolioRenalSub,0.35,1.357002e+08,3.843667e+08,70034174,0.175,1.0,VC,...,6.440906e+07,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2665,70034174_1,2025-04-01,VentaFacturadaPortafolioRenalSub,0.40,2.080647e+08,5.259754e+08,70034174,0.175,1.0,VC,...,7.236450e+07,0.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3444,70034174_1,2025-05-01,VentaFacturadaPortafolioRenalSub,0.42,2.921723e+08,6.878140e+08,70034174,0.175,1.0,VC,...,8.410756e+07,0.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4211,70034174_1,2025-06-01,VentaFacturadaPortafolioRenalSub,0.40,3.371065e+08,8.496526e+08,70034174,0.175,1.0,VC,...,4.493425e+07,0.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4980,70034174_1,2025-07-01,VentaFacturadaPortafolioRenalSub,0.38,4.574365e+08,1.213789e+09,70034174,0.175,1.0,VC,...,1.203300e+08,0.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5782,70034174_1,2025-08-01,VentaFacturadaPortafolioRenalSub,0.75,1.737962e+09,2.316636e+09,70034174,0.175,1.0,VC,...,1.280526e+09,1.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6588,70034174_1,2025-09-01,VentaFacturadaPortafolioRenalSub,0.75,2.014585e+09,2.676300e+09,70034174,0.175,1.0,VC,...,2.766229e+08,0.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7383,70034174_1,2025-10-01,VentaFacturadaPortafolioRenalSub,0.55,2.259203e+09,4.145091e+09,70034174,0.175,1.0,VC,...,2.446175e+08,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8171,70034174_1,2025-11-01,VentaFacturadaPortafolioRenalSub,0.97,4.381517e+09,4.520276e+09,70034174,0.175,1.0,VC,...,2.122314e+09,5.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19774,70034174_1,2025-12-01,VentaFacturadaPortafolioRenalSub,1.23,5.772389e+09,4.706111e+09,70034174,0.175,1.0,VC,...,1.390872e+09,7.48,23.0,0.0,0.0,0.0,VentaFacturadaPortafolioRenalSub,Renal Total Nacional (hospitalio + ambulatorio...,both,12.0

## Se obtienen las liquidaciones

### Creación de resultado_liquidaciones por maestra_resultados_por_empleado

In [105]:
excepciones_pagos_acumulados = {}

excepciones_diferencias = {}

In [106]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '1111135') &
    (maestra_resultados_por_empleado['Fecha'] == '2024-05-01')
][['Contexto', 'CodigoEmpleado', 'SalarioVariable', 'Fecha', 'NuevoFactorBK', 'Liquidado']]

Empty DataFrame
Columns: [Contexto, CodigoEmpleado, SalarioVariable, Fecha, NuevoFactorBK, Liquidado]
Index: []

In [107]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '5032456') &
    (maestra_resultados_por_empleado['Fecha'] == '2025-07-01')
][['Contexto', 'CodigoEmpleado', 'SalarioVariable', 'Fecha', 'NuevoFactorBK', 'Liquidado']]

,Contexto,CodigoEmpleado,SalarioVariable,Fecha,NuevoFactorBK,Liquidado
4612,5032456,5032456,3000000.0,2025-07-01,NaN,900000.0
4613,gu_11_1,5032456,3000000.0,2025-07-01,NaN,5400000.0
4614,gu_11_2,5032456,3000000.0,2025-07-01,NaN,0.0
4615,BBMCO,5032456,3000000.0,2025-07-01,NaN,1425600.0
4616,5032456_10,5032456,3000000.0,2025-07-01,NaN,6000000.0
4617,EBITCOGSP,5032456,3000000.0,2025-07-01,NaN,6000000.0

In [108]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '5032456') &
    (maestra_resultados_por_empleado['Fecha'] == '2025-07-01')
][['Contexto', 'CodigoEmpleado', 'SalarioVariable', 'Fecha', 'NuevoFactorBK', 'Liquidado']]['Liquidado'].sum()

19725600.0

In [109]:
df_incentivos_por_empleado[df_incentivos_por_empleado['CodigoEmpleado'] == '16659046']

Empty DataFrame
Columns: [CodigoEmpleado, Fecha, Valor]
Index: []

In [110]:
df_incentivos_por_empleado[df_incentivos_por_empleado['CodigoEmpleado'] == '1111135']

Empty DataFrame
Columns: [CodigoEmpleado, Fecha, Valor]
Index: []

In [111]:
df_incentivos_por_empleado[df_incentivos_por_empleado['CodigoEmpleado'] == '1111134']

Empty DataFrame
Columns: [CodigoEmpleado, Fecha, Valor]
Index: []

In [112]:
df_incentivos_por_empleado[df_incentivos_por_empleado['CodigoEmpleado'] == '5032456']

    CodigoEmpleado      Fecha      Valor
860        5032456 2025-01-01        0.0
861        5032456 2025-02-01        0.0
862        5032456 2025-03-01  1968900.0
863        5032456 2025-04-01  5118300.0
864        5032456 2025-05-01  5230800.0
865        5032456 2025-06-01  4445100.0
866        5032456 2025-07-01  4931400.0
867        5032456 2025-08-01  4931400.0
868        5032456 2025-09-01        0.0
869        5032456 2025-10-01        0.0
870        5032456 2025-11-01        0.0
871        5032456 2025-12-01        0.0

In [113]:
resultado_liquidaciones = maestra_resultados_por_empleado.groupby(
    ['CodigoEmpleado', 'SalarioVariable', 'Fecha', 'NuevoFactorBK'],
    as_index=False
).Liquidado.agg({'Liquidado': 'sum'})
resultado_liquidaciones.rename(columns={'NuevoFactorBK': 'NuevoFactor'}, inplace=True)
resultado_liquidaciones.head()
resultado_liquidaciones = resultado_liquidaciones.merge(
    df_incentivos_por_empleado.rename(columns={'Valor': 'PagoReal'}),
    on = ['CodigoEmpleado', 'Fecha'],
    how = 'right'
)
resultado_liquidaciones.head()

  CodigoEmpleado  SalarioVariable      Fecha  NuevoFactor  Liquidado  PagoReal
0     1004206367              NaN 2025-01-01          NaN        NaN       0.0
1     1004206367              NaN 2025-02-01          NaN        NaN       0.0
2     1004206367              NaN 2025-07-01          NaN        NaN  900000.0
3     1004206367              NaN 2025-08-01          NaN        NaN  900000.0
4     1004206367              NaN 2025-09-01          NaN        NaN  900000.0

In [114]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '5032456']

,CodigoEmpleado,SalarioVariable,Fecha,NuevoFactor,Liquidado,PagoReal
860,5032456,NaN,2025-01-01,NaN,NaN,0.0
861,5032456,NaN,2025-02-01,NaN,NaN,0.0
862,5032456,NaN,2025-03-01,NaN,NaN,1968900.0
863,5032456,NaN,2025-04-01,NaN,NaN,5118300.0
864,5032456,NaN,2025-05-01,NaN,NaN,5230800.0
865,5032456,NaN,2025-06-01,NaN,NaN,4445100.0
866,5032456,NaN,2025-07-01,NaN,NaN,4931400.0
867,5032456,NaN,2025-08-01,NaN,NaN,4931400.0
868,5032456,NaN,2025-09-01,NaN,NaN,0.0
869,5032456,NaN,2025-10-01,NaN,NaN,0.0
870,5032456,NaN,2025-11-01,NaN,NaN,0.0
871,5032456,3000000.0,2025-12-01,12.0,53100000.0,0.0

In [115]:
resultado_liquidaciones[
    (resultado_liquidaciones['CodigoEmpleado'] == '70014244')
]

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, NuevoFactor, Liquidado, PagoReal]
Index: []

In [116]:
resultado_liquidaciones = pd.merge(
    left=resultado_liquidaciones,
    right=df_empleados[['CodigoEmpleado', 'FechaIngreso']].drop_duplicates(['CodigoEmpleado']),
    how='left',
    on=['CodigoEmpleado']
)

# Filtro resultado liquidaciones SIN GARANTIZADO
resultado_liquidaciones = resultado_liquidaciones[resultado_liquidaciones['Fecha'] >= resultado_liquidaciones['FechaIngreso']]
resultado_liquidaciones.drop(columns=['FechaIngreso'], inplace=True)
resultado_liquidaciones.head()

# Cálculo de garantizado (100%) para VEs y VCs, Anticipos (85%) para el resto de empleados
resultado_liquidaciones = resultado_liquidaciones.merge(
    df_empleados[['CodigoEmpleado', 'TipoEmpleado']],
    on='CodigoEmpleado',
    how='left'
)

def calcular_liquidacion_mes(g):
    pago_acumulado = 0
    
    # Convertir la columna 'PagadoFecha' a float64 para evitar problemas con los decimales
    g['PagadoFecha'] = g['PagadoFecha'].astype('float64')
    
    for i, row in g.iterrows():
        # print("mes actual:", row['Fecha'].month)
        if row['Fecha'].month in meses_incentivos:
            # print("Pago Real", g.at[i, 'PagoReal'])
            if g.at[i, 'PagoReal'] == 0:
                # print("Pago Real es 0", g.at[i, 'PagoReal'])
                if i == 0:
                    # print("i es igual a 0")
                    g.at[i, 'PagoReal'] = g.at[i, 'Liquidado']
                else:
                    # print("i no es igual a 0")
                    g.at[i, 'PagoReal'] = g.at[i, 'Liquidado'] - pago_acumulado
                # print("Pago Real actualizado", g.at[i, 'PagoReal'])
            if g.at[i, 'PagoReal'] < 0:
                g.at[i, 'PagoReal'] = 0.0

        if g.at[i, 'PagoGarantizado'] == "NO":
            pago_acumulado += g.at[i, 'PagoReal']
        #print("pago_acumuladol_antes:", pago_acumulado)
        # pago_acumulado += g.at[i, 'PagoReal']
        g.at[i, 'PagadoFecha'] = pago_acumulado
        # print("pago_acumuladol_después:", pago_acumulado)
        
        excepcion = excepciones_pagos_acumulados.get(row['CodigoEmpleado'], None)
        if excepcion and row['Fecha'] == excepcion['Fecha']:
            pago_acumulado = excepcion['ValorPagoAcumulado']
        
        excepcion_diferencia = excepciones_diferencias.get(row['CodigoEmpleado'], None)
        if excepcion_diferencia and row['Fecha'] == excepcion_diferencia['Fecha']:
            pago_acumulado = pago_acumulado + excepcion_diferencia['ValorDiferencia']
        
    return g
resultado_liquidaciones = resultado_liquidaciones.sort_values(by=['CodigoEmpleado', 'Fecha'])
resultado_liquidaciones.reset_index(inplace=True, drop=True)
resultado_liquidaciones['PagoReal'].fillna(0.0, inplace=True)
resultado_liquidaciones['Liquidado'].fillna(0.0, inplace=True)
resultado_liquidaciones

,CodigoEmpleado,SalarioVariable,Fecha,NuevoFactor,Liquidado,PagoReal,TipoEmpleado
0,1004206367,NaN,2025-10-01,NaN,0.0,713700.0,MK
1,1004206367,NaN,2025-11-01,NaN,0.0,730800.0,MK
2,1004206367,900000.0,2025-12-01,12.0,11664000.0,0.0,MK
3,1013587064,NaN,2025-01-01,NaN,0.0,250000.0,AD2
4,1013587064,NaN,2025-02-01,NaN,0.0,250000.0,AD2
...,...,...,...,...,...,...,...
1688,94526955,NaN,2025-08-01,NaN,0.0,11556160.0,MK1
1689,94526955,NaN,2025-09-01,NaN,0.0,0.0,MK1
1690,94526955,NaN,2025-10-01,NaN,0.0,6207320.0,MK1
1691,94526955,NaN,2025-11-01,NaN,0.0,2983120.0,MK1
1692,94526955,4900000.0,2025-12-01,12.0,66643920.0,0.0,MK1

In [117]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '70014244']

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, NuevoFactor, Liquidado, PagoReal, TipoEmpleado]
Index: []

In [118]:
resultado_liquidaciones[
    (resultado_liquidaciones['CodigoEmpleado'] == '70014244')
]

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, NuevoFactor, Liquidado, PagoReal, TipoEmpleado]
Index: []

In [119]:
# resultado_liquidaciones_copy = resultado_liquidaciones[
#     (resultado_liquidaciones['CodigoEmpleado'] == '16659046')
# ].groupby(['CodigoEmpleado'], group_keys=False).apply(calcular_liquidacion_mes)
# resultado_liquidaciones_copy[resultado_liquidaciones_copy['CodigoEmpleado'] == '16659046']

In [120]:
# resultado_liquidaciones_copy = resultado_liquidaciones[
#     (resultado_liquidaciones['CodigoEmpleado'] == '1111135') &  (resultado_liquidaciones['PagoGarantizado'] == 'NO')
# ].groupby(['CodigoEmpleado'], group_keys=False).apply(calcular_liquidacion_mes)
# resultado_liquidaciones_copy[resultado_liquidaciones_copy['CodigoEmpleado'] == '1111135']

In [121]:
# resultado_liquidaciones = resultado_liquidaciones.groupby(['CodigoEmpleado'], group_keys=False).apply(calcular_liquidacion_mes)
resultado_liquidaciones.rename(columns={'NuevoFactor': 'FactorMes'}, inplace=True)
resultado_liquidaciones['PagoGarantizado'] = 'NO'

resultado_liquidaciones['PagoReal'] = np.where(
    (
        (resultado_liquidaciones['Fecha'] >= '2022-01-01') &
        (resultado_liquidaciones['Fecha'] <= '2022-02-01') &
        (resultado_liquidaciones['TipoEmpleado'].isin(['VE', 'VC']))
    ),
    resultado_liquidaciones['SalarioVariable'],
    resultado_liquidaciones['PagoReal']
)
resultado_liquidaciones['PagoReal'] = np.where(
    (
        (resultado_liquidaciones['Fecha'] >= '2022-01-01') &
        (resultado_liquidaciones['Fecha'] <= '2022-02-01') &
        (resultado_liquidaciones['TipoEmpleado'].isin(['AD', 'AD1', 'AD2', 'AD3', 'AD4', 'AD5', 'GC', 'GD', 'GU', 'KAM', 'MK']))
    ),
    resultado_liquidaciones['SalarioVariable'] * 0.85,
    resultado_liquidaciones['PagoReal']
)
resultado_liquidaciones.drop(columns=['TipoEmpleado'], inplace=True)

resultado_liquidaciones.head(12)

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,Liquidado,PagoReal,PagoGarantizado
0,1004206367,NaN,2025-10-01,NaN,0.0,713700.0,NO
1,1004206367,NaN,2025-11-01,NaN,0.0,730800.0,NO
2,1004206367,900000.0,2025-12-01,12.0,11664000.0,0.0,NO
3,1013587064,NaN,2025-01-01,NaN,0.0,250000.0,NO
4,1013587064,NaN,2025-02-01,NaN,0.0,250000.0,NO
5,1013587064,NaN,2025-03-01,NaN,0.0,785000.0,NO
6,1013587064,NaN,2025-03-01,NaN,0.0,0.0,NO
7,1013587064,NaN,2025-03-01,NaN,0.0,0.0,NO
8,1013587064,NaN,2025-04-01,NaN,0.0,1115000.0,NO
9,1013587064,NaN,2025-05-01,NaN,0.0,475000.0,NO
10,1013587064,NaN,2025-06-01,NaN,0.0,385000.0,NO
11,1013587064,NaN,2025-07-01,NaN,0.0,565000.0,NO

In [122]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '16659046']

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, FactorMes, Liquidado, PagoReal, PagoGarantizado]
Index: []

In [123]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '1111135']

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, FactorMes, Liquidado, PagoReal, PagoGarantizado]
Index: []

In [124]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '79539822']

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,Liquidado,PagoReal,PagoGarantizado
1665,79539822,NaN,2025-01-01,NaN,0.0,1642500.00,NO
1666,79539822,NaN,2025-02-01,NaN,0.0,1642500.00,NO
1667,79539822,NaN,2025-03-01,NaN,0.0,5398183.33,NO
1668,79539822,NaN,2025-03-01,NaN,0.0,0.00,NO
1669,79539822,NaN,2025-03-01,NaN,0.0,0.00,NO
1670,79539822,NaN,2025-04-01,NaN,0.0,7740316.67,NO
1671,79539822,NaN,2025-05-01,NaN,0.0,3339250.00,NO
1672,79539822,NaN,2025-06-01,NaN,0.0,2713450.00,NO
1673,79539822,NaN,2025-07-01,NaN,0.0,3965050.00,NO
1674,79539822,NaN,2025-08-01,NaN,0.0,2502550.00,NO
1675,79539822,NaN,2025-09-01,NaN,0.0,3233800.00,NO
1676,79539822,NaN,2025-10-01,NaN,0.0,3233800.00,NO
1677,79539822,NaN,2025-11-01,NaN,0.0,3233800.00,NO
1678,79539822,3.495833e+06,2025-12-01,12.0,79705000.0,0.00,NO

### Creación de resultado_liquidaciones por maestra_resultados_por_empleado_centro_costo

In [125]:
# resultado_liquidaciones_centro_costo = maestra_resultados_por_empleado_centro_costo_final.groupby(
#     ['CodigoEmpleado', 'CodigoCentroCosto','SalarioVariable', 'Fecha', 'NuevoFactorBK'],
#     as_index=False
# ).Liquidado.agg({'Liquidado': 'sum'})
# resultado_liquidaciones_centro_costo.rename(columns={'NuevoFactorBK': 'NuevoFactor'}, inplace=True)
# resultado_liquidaciones_centro_costo.head()
# resultado_liquidaciones_centro_costo = resultado_liquidaciones_centro_costo.merge(
#     df_incentivos_por_empleado.rename(columns={'Valor': 'PagoReal'}),
#     on = ['CodigoEmpleado', 'Fecha'],
#     how = 'right'
# )

# resultado_liquidaciones_centro_costo = pd.merge(
#     left=resultado_liquidaciones_centro_costo,
#     right=df_empleados[['CodigoEmpleado', 'FechaIngreso']].drop_duplicates(['CodigoEmpleado']),
#     how='left',
#     on=['CodigoEmpleado']
# )

# resultado_liquidaciones_centro_costo.head()

In [126]:
# resultado_liquidaciones_centro_costo = resultado_liquidaciones_centro_costo[resultado_liquidaciones_centro_costo['Fecha'] >= resultado_liquidaciones_centro_costo['FechaIngreso']]
# resultado_liquidaciones_centro_costo.drop(columns=['FechaIngreso'], inplace=True)
# resultado_liquidaciones_centro_costo.head()

# # Cálculo de garantizado (100%) para VEs y VCs, Anticipos (85%) para el resto de empleados
# resultado_liquidaciones_centro_costo = resultado_liquidaciones_centro_costo.merge(
#     df_empleados[['CodigoEmpleado', 'TipoEmpleado']],
#     on='CodigoEmpleado',
#     how='left'
# )

# def calcular_liquidacion_mes(g):
#     pago_acumulado = 0
#     for i, row in g.iterrows():
#         if row['Fecha'].month in meses_incentivos:
#             if g.at[i, 'PagoReal'] == 0:
#                 if i == 0:
#                     g.at[i, 'PagoReal'] = g.at[i, 'Liquidado']
#                 else:
#                     g.at[i, 'PagoReal'] = g.at[i, 'Liquidado'] - pago_acumulado
            
#             if g.at[i, 'PagoReal'] < 0:
#                 g.at[i, 'PagoReal'] = 0.0
#         pago_acumulado += g.at[i, 'PagoReal']
        
#         excepcion = excepciones_pagos_acumulados.get(row['CodigoEmpleado'], None)
#         if excepcion and row['Fecha'] == excepcion['Fecha']:
#             pago_acumulado = excepcion['ValorPagoAcumulado']
        
#         excepcion_diferencia = excepciones_diferencias.get(row['CodigoEmpleado'], None)
#         if excepcion_diferencia and row['Fecha'] == excepcion_diferencia['Fecha']:
#             pago_acumulado = pago_acumulado + excepcion_diferencia['ValorDiferencia']
        
#     return g
# resultado_liquidaciones_centro_costo = resultado_liquidaciones_centro_costo.sort_values(by=['CodigoEmpleado', 'Fecha'])
# resultado_liquidaciones_centro_costo.reset_index(inplace=True, drop=True)
# resultado_liquidaciones_centro_costo[a'PagoReal'].fillna(0.0, inplace=True)
# resultado_liquidaciones_centro_costo['Liquidado'].fillna(0.0, inplace=True)
# resultado_liquidaciones_centro_costo['PagoGarantizado'] = 'NO'
# resultado_liquidaciones_centro_costo

In [127]:
# resultado_liquidaciones_centro_costo = resultado_liquidaciones_centro_costo.groupby(['CodigoEmpleado'], group_keys=False).apply(calcular_liquidacion_mes)
# resultado_liquidaciones_centro_costo.rename(columns={'NuevoFactor': 'FactorMes'}, inplace=True)
# resultado_liquidaciones_centro_costo['PagoGarantizado'] = 'NO'

# resultado_liquidaciones_centro_costo['PagoReal'] = np.where(
#     (
#         (resultado_liquidaciones_centro_costo['Fecha'] >= '2022-01-01') &
#         (resultado_liquidaciones_centro_costo['Fecha'] <= '2022-02-01') &
#         (resultado_liquidaciones_centro_costo['TipoEmpleado'].isin(['VE', 'VC']))
#     ),
#     resultado_liquidaciones_centro_costo['SalarioVariable'],
#     resultado_liquidaciones_centro_costo['PagoReal']
# )
# resultado_liquidaciones_centro_costo['PagoReal'] = np.where(
#     (
#         (resultado_liquidaciones_centro_costo['Fecha'] >= '2022-01-01') &
#         (resultado_liquidaciones_centro_costo['Fecha'] <= '2022-02-01') &
#         (resultado_liquidaciones_centro_costo['TipoEmpleado'].isin(['AD', 'AD1', 'AD2', 'AD3', 'AD4', 'AD5', 'GC', 'GD', 'GU', 'KAM', 'MK']))
#     ),
#     resultado_liquidaciones_centro_costo['SalarioVariable'] * 0.85,
#     resultado_liquidaciones_centro_costo['PagoReal']
# )
# resultado_liquidaciones_centro_costo.drop(columns=['TipoEmpleado'], inplace=True)

# resultado_liquidaciones_centro_costo.head(12)

## Se obtienen los garantizados

### Sin centro de costo

In [128]:
empleados_garantizado = df_empleados[df_empleados['FechaIngreso'] > fecha_liquidacion][['CodigoEmpleado', 'SalarioVariable', 'FechaIngreso']]
empleados_garantizado

    CodigoEmpleado  SalarioVariable FechaIngreso
30        70055033        1000000.0   2026-02-01
37        70002044        2933900.0   2026-02-01
49        70055621        2500000.0   2026-03-02
53        70055714        1600000.0   2026-03-02
56        70055375        1000000.0   2026-02-01
85        70055726        1000000.0   2026-03-02
105       70056026        2500000.0   2026-03-02
108       70054038        2500000.0   2026-01-01
109       70055713        1000000.0   2026-03-02
123       70055419        3000000.0   2026-03-02
129       70054456        2500000.0   2026-02-01
133       70054037        2500000.0   2026-01-01

In [129]:
fechas_resultado_liquidaciones = resultado_liquidaciones[['Fecha']].drop_duplicates()

In [130]:
empleados_garantizado = df_empleados[df_empleados['FechaIngreso'] > fecha_liquidacion][['CodigoEmpleado', 'SalarioVariable', 'FechaIngreso']]
fechas_resultado_liquidaciones = resultado_liquidaciones[['Fecha']].drop_duplicates()

empleados_garantizado['Key'] = 1
fechas_resultado_liquidaciones['Key'] = 1

liquidaciones_garantizados = pd.merge(
    left=fechas_resultado_liquidaciones.sort_values(['Fecha']),
    right=empleados_garantizado,
    how='outer',
    on=['Key']
).drop(columns=['Key'])

liquidaciones_garantizados = liquidaciones_garantizados[liquidaciones_garantizados['CodigoEmpleado'].notnull()]

liquidaciones_garantizados['DifMonths'] = (
    (liquidaciones_garantizados['FechaIngreso'].dt.year - liquidaciones_garantizados['Fecha'].dt.year) * 12 +
    (liquidaciones_garantizados['FechaIngreso'].dt.month - liquidaciones_garantizados['Fecha'].dt.month)
)
liquidaciones_garantizados['DifMonths'] = liquidaciones_garantizados['DifMonths'].apply(lambda x: round(x, 0))
liquidaciones_garantizados['DifMonths'] = liquidaciones_garantizados['DifMonths'].astype('int')
liquidaciones_garantizados = liquidaciones_garantizados[liquidaciones_garantizados['DifMonths'] <= 4]

liquidaciones_garantizados['FactorMes'] = 0
liquidaciones_garantizados['Liquidado'] = liquidaciones_garantizados['SalarioVariable']
liquidaciones_garantizados['PagoReal'] = liquidaciones_garantizados['SalarioVariable']
liquidaciones_garantizados['PagoGarantizado'] = 'SI'

liquidaciones_garantizados.drop(columns=['DifMonths', 'FechaIngreso'], inplace=True)

liquidaciones_garantizados.head()

,Fecha,CodigoEmpleado,SalarioVariable,FactorMes,Liquidado,PagoReal,PagoGarantizado
103,2025-09-01,70054038,2500000.0,0,2500000.0,2500000.0,SI
107,2025-09-01,70054037,2500000.0,0,2500000.0,2500000.0,SI
108,2025-10-01,70055033,1000000.0,0,1000000.0,1000000.0,SI
109,2025-10-01,70002044,2933900.0,0,2933900.0,2933900.0,SI
112,2025-10-01,70055375,1000000.0,0,1000000.0,1000000.0,SI

In [131]:
liquidaciones_garantizados[liquidaciones_garantizados['CodigoEmpleado'] == '16659046']

Empty DataFrame
Columns: [Fecha, CodigoEmpleado, SalarioVariable, FactorMes, Liquidado, PagoReal, PagoGarantizado]
Index: []

In [132]:
liquidaciones_garantizados[liquidaciones_garantizados['CodigoEmpleado'] == '1111135']

Empty DataFrame
Columns: [Fecha, CodigoEmpleado, SalarioVariable, FactorMes, Liquidado, PagoReal, PagoGarantizado]
Index: []

### Con centro de costo

In [133]:
# empleados_garantizado = df_empleados[df_empleados['FechaIngreso'] > fecha_liquidacion][['CodigoEmpleado', 'SalarioVariable', 'FechaIngreso']]
# fechas_resultado_liquidaciones_centro_costo = resultado_liquidaciones_centro_costo[['Fecha']].drop_duplicates()

# empleados_garantizado['Key'] = 1
# fechas_resultado_liquidaciones_centro_costo['Key'] = 1

# liquidaciones_garantizados_centro_costo = pd.merge(
#     left=fechas_resultado_liquidaciones_centro_costo.sort_values(['Fecha']),
#     right=empleados_garantizado,
#     how='outer',
#     on=['Key']
# ).drop(columns=['Key'])

# liquidaciones_garantizados_centro_costo = liquidaciones_garantizados_centro_costo[liquidaciones_garantizados_centro_costo['CodigoEmpleado'].notnull()]

# liquidaciones_garantizados_centro_costo['DifMonths'] = ((liquidaciones_garantizados_centro_costo.FechaIngreso - liquidaciones_garantizados_centro_costo.Fecha)/np.timedelta64(1, 'M'))
# liquidaciones_garantizados_centro_costo['DifMonths'] = liquidaciones_garantizados_centro_costo['DifMonths'].apply(lambda x: round(x, 0))
# liquidaciones_garantizados_centro_costo['DifMonths'] = liquidaciones_garantizados_centro_costo['DifMonths'].astype('int')
# liquidaciones_garantizados_centro_costo = liquidaciones_garantizados_centro_costo[liquidaciones_garantizados_centro_costo['DifMonths'] <= 4]

# liquidaciones_garantizados_centro_costo['FactorMes'] = 0
# liquidaciones_garantizados_centro_costo['Liquidado'] = liquidaciones_garantizados_centro_costo['SalarioVariable']
# liquidaciones_garantizados_centro_costo['PagoReal'] = liquidaciones_garantizados_centro_costo['SalarioVariable']
# liquidaciones_garantizados_centro_costo['PagoGarantizado'] = 'SI'

# liquidaciones_garantizados_centro_costo.drop(columns=['DifMonths', 'FechaIngreso'], inplace=True)

# liquidaciones_garantizados_centro_costo.head()

## Se unen las liquidaciones de garantizados con las demás

### Sin centro de costo

In [134]:
resultado_liquidaciones = pd.concat([resultado_liquidaciones, liquidaciones_garantizados])
resultado_liquidaciones.reset_index(drop=True, inplace=True)
resultado_liquidaciones

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,Liquidado,PagoReal,PagoGarantizado
0,1004206367,NaN,2025-10-01,NaN,0.0,713700.0,NO
1,1004206367,NaN,2025-11-01,NaN,0.0,730800.0,NO
2,1004206367,900000.0,2025-12-01,12.0,11664000.0,0.0,NO
3,1013587064,NaN,2025-01-01,NaN,0.0,250000.0,NO
4,1013587064,NaN,2025-02-01,NaN,0.0,250000.0,NO
...,...,...,...,...,...,...,...
1720,70054038,2500000.0,2025-12-01,0.0,2500000.0,2500000.0,SI
1721,70055713,1000000.0,2025-12-01,0.0,1000000.0,1000000.0,SI
1722,70055419,3000000.0,2025-12-01,0.0,3000000.0,3000000.0,SI
1723,70054456,2500000.0,2025-12-01,0.0,2500000.0,2500000.0,SI
1724,70054037,2500000.0,2025-12-01,0.0,2500000.0,2500000.0,SI

In [135]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '1111135']

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, FactorMes, Liquidado, PagoReal, PagoGarantizado]
Index: []

In [136]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '16659046']

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, FactorMes, Liquidado, PagoReal, PagoGarantizado]
Index: []

### Con centro de costo

In [137]:
# resultado_liquidaciones_centro_costo = pd.concat([resultado_liquidaciones_centro_costo, liquidaciones_garantizados_centro_costo])
# resultado_liquidaciones_centro_costo.reset_index(drop=True, inplace=True)
# resultado_liquidaciones_centro_costo

## Se conserva la información del histórico y se le añade la nueva información hasta la fecha de liquidación

### Sin centro de costo

In [138]:
df_resultado_liquidaciones_previo[df_resultado_liquidaciones_previo['CodigoEmpleado'] == '79539822']

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal
15,79539822,3285000.0,2025-01-01,1,NO,3087900.00,1642500.00
159,79539822,3285000.0,2025-02-01,2,NO,3400000.00,1757500.00
309,79539822,3285000.0,2025-03-01,3,NO,5398183.33,1998183.33
455,79539822,3285000.0,2025-04-01,4,NO,13138500.00,7740316.67
597,79539822,3285000.0,2025-05-01,5,NO,16477750.00,3339250.00
739,79539822,3285000.0,2025-06-01,6,NO,19191200.00,2713450.00
885,79539822,3285000.0,2025-07-01,7,NO,23156250.00,3965050.00
1029,79539822,3285000.0,2025-08-01,8,NO,25658800.00,2502550.00
1177,79539822,3285000.0,2025-09-01,9,NO,28892600.00,3233800.00
1325,79539822,3285000.0,2025-10-01,10,NO,32126400.00,3233800.00
1473,79539822,3285000.0,2025-11-01,11,NO,35360200.00,3233800.00

In [139]:
df_resultado_liquidaciones_previo[df_resultado_liquidaciones_previo['CodigoEmpleado'] == '16659046']

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, FactorMes, PagoGarantizado, Liquidado, PagoReal]
Index: []

In [140]:
df_resultado_liquidaciones_previo[df_resultado_liquidaciones_previo['CodigoEmpleado'] == '5005980']

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal
31,5005980,3000000.0,2025-01-01,1,NO,300000.0,1500000.0
178,5005980,3000000.0,2025-02-01,2,NO,3150000.0,1650000.0
328,5005980,3000000.0,2025-03-01,3,NO,5233152.0,2083152.0
474,5005980,3000000.0,2025-04-01,4,NO,15145890.0,9912738.0
616,5005980,3000000.0,2025-05-01,5,NO,23300460.0,8154570.0
757,5005980,3000000.0,2025-06-01,6,NO,24069240.0,768780.0
904,5005980,3000000.0,2025-07-01,7,NO,27761736.0,3692496.0
1048,5005980,3000000.0,2025-08-01,8,NO,36429858.0,8668122.0
1493,5005980,3000000.0,2025-11-01,11,NO,32971680.0,0.0

In [141]:
meses_incentivos

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [142]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '1111135']

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, FactorMes, Liquidado, PagoReal, PagoGarantizado]
Index: []

In [143]:
# # Función para combinar valores de columnas _x y _y
# def combinar_valores(row, columna_base):
#     valor_x = row[f'{columna_base}_x']
#     valor_y = row[f'{columna_base}_y']
    
#     if valor_x != 0.0:
#         return valor_x
#     elif valor_y != 0.0:
#         return valor_y
#     else:
#         return 0

In [144]:
# resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '1111135'].merge(
#     resultado_liquidaciones_historico[resultado_liquidaciones_historico['CodigoEmpleado'] == '1111135'],
#     on=['CodigoEmpleado', 'Fecha'],
#     how='outer'
# ).fillna(0)

In [145]:
resultado_liquidaciones.columns

Index(['CodigoEmpleado', 'SalarioVariable', 'Fecha', 'FactorMes', 'Liquidado',
       'PagoReal', 'PagoGarantizado'],
      dtype='object')

In [146]:
# prueba = resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '1111135'].merge(
#     resultado_liquidaciones_historico[resultado_liquidaciones_historico['CodigoEmpleado'] == '1111135'],
#     on=['CodigoEmpleado', 'Fecha'],
#     how='outer'
# ).fillna(0).sort_values(by=['CodigoEmpleado', 'Fecha'])

# prueba['SalarioVariable'] = prueba.apply(lambda row: combinar_valores(row, 'SalarioVariable'), axis=1)
# prueba['Liquidado'] = prueba.apply(lambda row: combinar_valores(row, 'Liquidado'), axis=1)
# prueba['FactorMes'] = prueba.apply(lambda row: combinar_valores(row, 'FactorMes'), axis=1)
# prueba['PagoReal'] = prueba.apply(lambda row: combinar_valores(row, 'PagoReal'), axis=1)
# prueba['PagoGarantizado'] = prueba.apply(lambda row: combinar_valores(row, 'PagoGarantizado'), axis=1)
# prueba = prueba[resultado_liquidaciones.columns]
# prueba

In [147]:
# prueba = resultado_liquidaciones.merge(
#     resultado_liquidaciones_historico,
#     on=['CodigoEmpleado', 'Fecha'],
#     how='outer'
# ).fillna(0).sort_values(by=['CodigoEmpleado', 'Fecha'])

# prueba['SalarioVariable'] = prueba.apply(lambda row: combinar_valores(row, 'SalarioVariable'), axis=1)
# prueba['Liquidado'] = prueba.apply(lambda row: combinar_valores(row, 'Liquidado'), axis=1)
# prueba['FactorMes'] = prueba.apply(lambda row: combinar_valores(row, 'FactorMes'), axis=1)
# prueba['PagoReal'] = prueba.apply(lambda row: combinar_valores(row, 'PagoReal'), axis=1)
# prueba['PagoGarantizado'] = prueba.apply(lambda row: combinar_valores(row, 'PagoGarantizado'), axis=1)
# prueba = prueba[resultado_liquidaciones.columns]

# resultado_liquidaciones = prueba.copy()
# resultado_liquidaciones

In [148]:
# def calcular_liquidacion_mes(g):
#     pago_acumulado = 0
#     suma_anticipos = 0
#     for i, row in g.iterrows():
# #         print(row)
# #         print(f"Liquidado: {row['Liquidado']} PagoReal: {row['PagoReal']} PagadoFecha:{row['PagadoFecha']}")
# #         print("mes actual:", row['Fecha'].month)
#         if row['Fecha'].month in meses_incentivos:
# #             print("Pago Real", g.at[i, 'PagoReal'])
#             if g.at[i, 'PagoReal'] == 0:
# #                 print("Pago Real es 0", g.at[i, 'PagoReal'])
#                 if i == 0:
# #                     print("i es igual a 0")
#                     g.at[i, 'PagoReal'] = g.at[i, 'Liquidado']
# #                     print(f"Pago Real {g.at[i, 'PagoReal']} igual a liquidado = {g.at[i, 'Liquidado']}")
#                 else:
# #                     print("i no es igual a 0")
#                     g.at[i, 'PagoReal'] = g.at[i, 'Liquidado'] - pago_acumulado
# #                     print(f"Pago Real {g.at[i, 'PagoReal']} igual a liquidado = {g.at[i, 'Liquidado']} - pago acumulado {pago_acumulado}")
# #                 print("Pago Real actualizado", g.at[i, 'PagoReal'])
#             if g.at[i, 'PagoReal'] < 0:
#                 g.at[i, 'PagoReal'] = 0.0
                
# #         print(row['Fecha'].month, type(row['Fecha'].month), g.at[i, 'PagoReal'])
#         if row['Fecha'].month not in meses_incentivos:
#             if g.at[i, 'PagoGarantizado'] == "NO":
# #                 print("Pago Real", g.at[i, 'PagoReal'])
#                 suma_anticipos += g.at[i, 'PagoReal']
        
#         if row['Fecha'].month == 4:
# #             print("Abril", suma_anticipos)
#             g.at[i, 'PagoReal'] = suma_anticipos + g.at[i, 'PagoReal']
        
# #         print("pago_acumuladol_antes:", pago_acumulado)
#         pago_acumulado += g.at[i, 'PagoReal']
# #         print("pago_acumuladol_después:", pago_acumulado)
        
#         g.at[i, 'PagadoFecha'] = pago_acumulado
        
#         excepcion = excepciones_pagos_acumulados.get(row['CodigoEmpleado'], None)
#         if excepcion and row['Fecha'] == excepcion['Fecha']:
#             pago_acumulado = excepcion['ValorPagoAcumulado']
        
#         excepcion_diferencia = excepciones_diferencias.get(row['CodigoEmpleado'], None)
#         if excepcion_diferencia and row['Fecha'] == excepcion_diferencia['Fecha']:
#             pago_acumulado = pago_acumulado + excepcion_diferencia['ValorDiferencia']
# #         print("----+++++++++++++++++++++++++++++-----")
#     return g

In [149]:
def calcular_liquidacion_mes_corregido(g):
    pago_acumulado = 0
    suma_anticipos = 0
    for i, row in g.iterrows():
        if row['Fecha'].month in meses_incentivos:
            if g.at[i, 'PagoReal'] == 0:
                if i == 0:

                    g.at[i, 'PagoReal'] = g.at[i, 'Liquidado']
                else:
                    g.at[i, 'PagoReal'] = g.at[i, 'Liquidado'] - pago_acumulado
            if g.at[i, 'PagoReal'] < 0:
                g.at[i, 'PagoReal'] = 0.0
                    
#         if row['Fecha'].month not in meses_incentivos:
#             if g.at[i, 'PagoGarantizado'] == "NO":
#                 suma_anticipos = suma_anticipos + g.at[i, 'PagoReal']

#         if row['Fecha'].month == 4:
#             g.at[i, 'PagoReal'] = suma_anticipos + g.at[i, 'PagoReal']
        

        
        try:
            if g.at[i, 'PagoGarantizado'] == "NO":
                pago_acumulado += g.at[i, 'PagoReal']
        except Exception as e:
            print(row)
            print("+++++++++++++++++++++++")
            print(g.at[i, 'PagoGarantizado'])
            print("-----------")
            print(type(g.at[i, 'PagoGarantizado']))
            print(e)
        g.at[i, 'PagadoFecha'] = pago_acumulado
        excepcion = excepciones_pagos_acumulados.get(row['CodigoEmpleado'], None)
        if excepcion and row['Fecha'] == excepcion['Fecha']:
            pago_acumulado = excepcion['ValorPagoAcumulado']
        
        excepcion_diferencia = excepciones_diferencias.get(row['CodigoEmpleado'], None)
        if excepcion_diferencia and row['Fecha'] == excepcion_diferencia['Fecha']:
            pago_acumulado = pago_acumulado + excepcion_diferencia['ValorDiferencia']
    return g

In [150]:
resultado_liquidaciones_copy = resultado_liquidaciones.copy()
resultado_liquidaciones = resultado_liquidaciones_copy
resultado_liquidaciones

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,Liquidado,PagoReal,PagoGarantizado
0,1004206367,NaN,2025-10-01,NaN,0.0,713700.0,NO
1,1004206367,NaN,2025-11-01,NaN,0.0,730800.0,NO
2,1004206367,900000.0,2025-12-01,12.0,11664000.0,0.0,NO
3,1013587064,NaN,2025-01-01,NaN,0.0,250000.0,NO
4,1013587064,NaN,2025-02-01,NaN,0.0,250000.0,NO
...,...,...,...,...,...,...,...
1720,70054038,2500000.0,2025-12-01,0.0,2500000.0,2500000.0,SI
1721,70055713,1000000.0,2025-12-01,0.0,1000000.0,1000000.0,SI
1722,70055419,3000000.0,2025-12-01,0.0,3000000.0,3000000.0,SI
1723,70054456,2500000.0,2025-12-01,0.0,2500000.0,2500000.0,SI
1724,70054037,2500000.0,2025-12-01,0.0,2500000.0,2500000.0,SI

In [151]:
df_resultado_liquidaciones_previo[df_resultado_liquidaciones_previo['CodigoEmpleado'] == '5032456']

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal
44,5032456,3000000.0,2025-01-01,0,SI,3000000.0,3000000.0
191,5032456,3000000.0,2025-02-01,0,SI,3000000.0,3000000.0
629,5032456,3000000.0,2025-05-01,2,NO,7199700.0,5230800.0
865,5032456,3000000.0,2025-03-01,0,SI,1968900.0,1968900.0
866,5032456,3000000.0,2025-04-01,1,NO,7087200.0,5118300.0
869,5032456,3000000.0,2025-06-01,3,NO,14794200.0,4445100.0
917,5032456,3000000.0,2025-07-01,4,NO,19725600.0,4931400.0
1061,5032456,3000000.0,2025-08-01,5,NO,24657000.0,4931400.0
1209,5032456,3000000.0,2025-09-01,6,NO,18038520.0,0.0
1356,5032456,3000000.0,2025-10-01,7,NO,17238900.0,0.0
1505,5032456,3000000.0,2025-11-01,8,NO,20452800.0,0.0

In [152]:
df_resultado_liquidaciones_previo[df_resultado_liquidaciones_previo['CodigoEmpleado'] == '70020733']

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal
111,70020733,2500000.0,2025-01-01,0,SI,2.500000e+06,2.500000e+06
259,70020733,2662500.0,2025-02-01,0,SI,2.662500e+06,2.662500e+06
695,70020733,2662500.0,2025-05-01,2,NO,3.870609e+06,1.723969e+06
867,70020733,2662500.0,2025-06-01,3,NO,7.623070e+06,4.770867e+06
868,70020733,2662500.0,2025-04-01,1,NO,3.274875e+06,1.128234e+06
870,70020733,2662500.0,2025-03-01,0,SI,2.146641e+06,2.146641e+06
985,70020733,2662500.0,2025-07-01,4,NO,9.651562e+06,2.028492e+06
1133,70020733,2662500.0,2025-08-01,5,NO,1.203284e+07,2.381273e+06
1281,70020733,2662500.0,2025-09-01,6,NO,1.517625e+07,3.143414e+06
1430,70020733,2662500.0,2025-10-01,7,NO,1.006425e+07,0.000000e+00
1579,70020733,2662500.0,2025-11-01,8,NO,1.048359e+07,0.000000e+00

In [153]:
codigos_empleados = ['5032456', '70020733']  # Lista de códigos que quieres corregir
fecha_objetivo = pd.to_datetime("2025-03-01")

resultado_liquidaciones_historico = df_resultado_liquidaciones_previo.copy()

resultado_liquidaciones_historico.loc[
    (resultado_liquidaciones_historico['Fecha'] == fecha_objetivo) & (resultado_liquidaciones_historico['CodigoEmpleado'].isin(codigos_empleados)),
    'PagoGarantizado'
] = 'SI'

In [154]:
resultado_liquidaciones_historico[resultado_liquidaciones_historico['CodigoEmpleado'] == '5032456']

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal
44,5032456,3000000.0,2025-01-01,0,SI,3000000.0,3000000.0
191,5032456,3000000.0,2025-02-01,0,SI,3000000.0,3000000.0
629,5032456,3000000.0,2025-05-01,2,NO,7199700.0,5230800.0
865,5032456,3000000.0,2025-03-01,0,SI,1968900.0,1968900.0
866,5032456,3000000.0,2025-04-01,1,NO,7087200.0,5118300.0
869,5032456,3000000.0,2025-06-01,3,NO,14794200.0,4445100.0
917,5032456,3000000.0,2025-07-01,4,NO,19725600.0,4931400.0
1061,5032456,3000000.0,2025-08-01,5,NO,24657000.0,4931400.0
1209,5032456,3000000.0,2025-09-01,6,NO,18038520.0,0.0
1356,5032456,3000000.0,2025-10-01,7,NO,17238900.0,0.0
1505,5032456,3000000.0,2025-11-01,8,NO,20452800.0,0.0

In [155]:
resultado_liquidaciones_historico[resultado_liquidaciones_historico['CodigoEmpleado'] == '70020733']

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal
111,70020733,2500000.0,2025-01-01,0,SI,2.500000e+06,2.500000e+06
259,70020733,2662500.0,2025-02-01,0,SI,2.662500e+06,2.662500e+06
695,70020733,2662500.0,2025-05-01,2,NO,3.870609e+06,1.723969e+06
867,70020733,2662500.0,2025-06-01,3,NO,7.623070e+06,4.770867e+06
868,70020733,2662500.0,2025-04-01,1,NO,3.274875e+06,1.128234e+06
870,70020733,2662500.0,2025-03-01,0,SI,2.146641e+06,2.146641e+06
985,70020733,2662500.0,2025-07-01,4,NO,9.651562e+06,2.028492e+06
1133,70020733,2662500.0,2025-08-01,5,NO,1.203284e+07,2.381273e+06
1281,70020733,2662500.0,2025-09-01,6,NO,1.517625e+07,3.143414e+06
1430,70020733,2662500.0,2025-10-01,7,NO,1.006425e+07,0.000000e+00
1579,70020733,2662500.0,2025-11-01,8,NO,1.048359e+07,0.000000e+00

In [156]:
# resultado_liquidaciones_historico = df_corregido_resultado_liquidaciones_previo.copy()

resultado_liquidaciones_historico['PagoGarantizado'] = resultado_liquidaciones_historico['PagoGarantizado'].fillna('NO')
last_date_historico = resultado_liquidaciones_historico['Fecha'].max()
last_date_historico = None if pd.isnull(last_date_historico) else last_date_historico

try:
    resultado_liquidaciones = resultado_liquidaciones[
        resultado_liquidaciones['Fecha']<=fecha_liquidacion
    ]
    if last_date_historico:
        resultado_liquidaciones = resultado_liquidaciones[
            resultado_liquidaciones['Fecha']>last_date_historico
        ]
except:
    pass

resultado_liquidaciones = pd.concat([resultado_liquidaciones_historico, resultado_liquidaciones]).reset_index(drop=True)
resultado_liquidaciones = resultado_liquidaciones.sort_values(by=['CodigoEmpleado', 'Fecha'])

for codigo_empleado_excepcion in excepciones_pagos_acumulados:
    excepcion = excepciones_pagos_acumulados[codigo_empleado_excepcion]
    resultado_liquidaciones['PagoReal'] = np.where(
        (
            (resultado_liquidaciones['CodigoEmpleado'] == codigo_empleado_excepcion) &
            (resultado_liquidaciones['Fecha'] <= excepcion['Fecha'])
        ),
        excepcion['ValorPagoAcumulado'],
        resultado_liquidaciones['PagoReal']
    )

for codigo_empleado_excepcion in excepciones_diferencias:
    excepcion = excepciones_diferencias[codigo_empleado_excepcion]
    resultado_liquidaciones['PagoReal'] = np.where(
        (
            (resultado_liquidaciones['CodigoEmpleado'] == codigo_empleado_excepcion) &
            (resultado_liquidaciones['Fecha'] == excepcion['Fecha'])
        ),
        resultado_liquidaciones['PagoReal'] + excepcion['ValorDiferencia'],
        resultado_liquidaciones['PagoReal']
    )
    
resultado_liquidaciones['PagadoFecha'] = 0

resultado_liquidaciones = resultado_liquidaciones.groupby(['CodigoEmpleado'], group_keys=False).apply(calcular_liquidacion_mes)
resultado_liquidaciones.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_39284\1983757146.py:45: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  resultado_liquidaciones = resultado_liquidaciones.groupby(['CodigoEmpleado'], group_keys=False).apply(calcular_liquidacion_mes)

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal,PagadoFecha
938,1004206367,900000.0,2025-07-01,0.0,SI,900000.0,900000.0,0.0
1083,1004206367,900000.0,2025-08-01,0.0,SI,900000.0,900000.0,0.0
1231,1004206367,900000.0,2025-09-01,0.0,SI,900000.0,900000.0,0.0
1379,1004206367,900000.0,2025-10-01,1.0,NO,713700.0,713700.0,713700.0
1528,1004206367,900000.0,2025-11-01,2.0,NO,1444500.0,730800.0,1444500.0

In [157]:
resultado_liquidaciones[
    (resultado_liquidaciones['CodigoEmpleado'] == '5032456')
]

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal,PagadoFecha
44,5032456,3000000.0,2025-01-01,0.0,SI,3000000.0,3000000.0,0.0
191,5032456,3000000.0,2025-02-01,0.0,SI,3000000.0,3000000.0,0.0
865,5032456,3000000.0,2025-03-01,0.0,SI,1968900.0,1968900.0,0.0
866,5032456,3000000.0,2025-04-01,1.0,NO,7087200.0,5118300.0,5118300.0
629,5032456,3000000.0,2025-05-01,2.0,NO,7199700.0,5230800.0,10349100.0
869,5032456,3000000.0,2025-06-01,3.0,NO,14794200.0,4445100.0,14794200.0
917,5032456,3000000.0,2025-07-01,4.0,NO,19725600.0,4931400.0,19725600.0
1061,5032456,3000000.0,2025-08-01,5.0,NO,24657000.0,4931400.0,24657000.0
1209,5032456,3000000.0,2025-09-01,6.0,NO,18038520.0,0.0,24657000.0
1356,5032456,3000000.0,2025-10-01,7.0,NO,17238900.0,0.0,24657000.0
1505,5032456,3000000.0,2025-11-01,8.0,NO,20452800.0,0.0,24657000.0
1673,5032456,3000000.0,2025-12-01,12.0,NO,53100000.0,28443000.0,53100000.0

In [158]:
resultado_liquidaciones['PagadoFecha'] = resultado_liquidaciones.apply(
    lambda row: row['PagadoFecha'] - row['PagoReal'] if row['PagoGarantizado'] == 'NO' else row['PagadoFecha'], axis=1
)

In [159]:
resultado_liquidaciones[
#     (resultado_liquidaciones['CodigoEmpleado'] == '16659046') | 
    (resultado_liquidaciones['CodigoEmpleado'] == '1111135') |
#     (resultado_liquidaciones['CodigoEmpleado'] == '1018451704') |
    (resultado_liquidaciones['CodigoEmpleado'] == '79539822')
]

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal,PagadoFecha
15,79539822,3.285000e+06,2025-01-01,1.0,NO,3087900.00,1642500.00,0.00
159,79539822,3.285000e+06,2025-02-01,2.0,NO,3400000.00,1757500.00,1642500.00
309,79539822,3.285000e+06,2025-03-01,3.0,NO,5398183.33,1998183.33,3400000.00
455,79539822,3.285000e+06,2025-04-01,4.0,NO,13138500.00,7740316.67,5398183.33
597,79539822,3.285000e+06,2025-05-01,5.0,NO,16477750.00,3339250.00,13138500.00
739,79539822,3.285000e+06,2025-06-01,6.0,NO,19191200.00,2713450.00,16477750.00
885,79539822,3.285000e+06,2025-07-01,7.0,NO,23156250.00,3965050.00,19191200.00
1029,79539822,3.285000e+06,2025-08-01,8.0,NO,25658800.00,2502550.00,23156250.00
1177,79539822,3.285000e+06,2025-09-01,9.0,NO,28892600.00,3233800.00,25658800.00
1325,79539822,3.285000e+06,2025-10-01,10.0,NO,32126400.00,3233800.00,28892600.00
1473,79539822,3.285000e+06,2025-11-01,11.0,NO,35360200.00,3233800.00,32126400.00
1745,79539822,3.495833e+06,2025-12-01,12.0,NO,79705000.00,44344800.00,35360200.00

In [160]:
resultado_liquidaciones.drop_duplicates(['CodigoEmpleado', 'Fecha'], inplace=True)

resultado_final = pd.merge(
    left=resultado_liquidaciones[['CodigoEmpleado', 'Fecha', 'PagoGarantizado', 'Liquidado', 'PagoReal', 'PagadoFecha', 'FactorMes']],
    right=df_empleados,
    on=['CodigoEmpleado'],
    how='left'
)
resultado_final = resultado_final[['Identificacion', 'Nombre', 'Apellidos', 'CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Fecha', 'SalarioVariable', 'PagoGarantizado', 'FactorMes', 'Liquidado', 'PagoReal', 'PagadoFecha']]
resultado_final = resultado_final.sort_values(by=['TipoEmpleado', 'AreaCalculo', 'CodigoEmpleado', 'Fecha'])

resultado_final.rename(columns={
    'Identificacion': 'Cédula',
    'CodigoEmpleado': 'Código',
    'TipoEmpleado': 'Tipo Empleado',
    'AreaCalculo': 'Área de cálculo',
    'Liquidado': 'Valor liquidado',
    'PagoReal': 'Valor neto a pagar',
    'PagadoFecha': 'Pagado a la fecha',
    'SalarioVariable': 'Salario variable',
    'FactorMes': 'Factor mes',
    'PagoGarantizado': '¿Pago garantizado?'
}, inplace=True)
resultado_final.head()

,Cédula,Nombre,Apellidos,Código,Tipo Empleado,Área de cálculo,Fecha,Salario variable,¿Pago garantizado?,Factor mes,Valor liquidado,Valor neto a pagar,Pagado a la fecha
282,52057371,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-01-01,1083000.0,NO,1.0,108300.00,541500.00,0.00
283,52057371,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-02-01,1083000.0,NO,2.0,1137150.00,595650.00,541500.00
284,52057371,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-03-01,1083000.0,NO,3.0,1097902.08,0.00,1137150.00
285,52057371,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-04-01,1083000.0,NO,4.0,6441424.08,5304274.08,1137150.00
286,52057371,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-05-01,1083000.0,NO,5.0,8381640.24,1940216.16,6441424.08

### Con centro de costo

In [161]:
# resultado_liquidaciones_historico_centro_costo = df_resultado_liquidaciones_previo.copy()
# resultado_liquidaciones_historico_centro_costo['PagoGarantizado'] = resultado_liquidaciones_historico_centro_costo['PagoGarantizado'].fillna('NO')
# last_date_historico = resultado_liquidaciones_historico_centro_costo['Fecha'].max()
# last_date_historico = None if pd.isnull(last_date_historico) else last_date_historico

# try:
#     resultado_liquidaciones_centro_costo = resultado_liquidaciones_centro_costo[
#         resultado_liquidaciones['Fecha']<=fecha_liquidacion
#     ]
#     if last_date_historico:
#         resultado_liquidaciones_centro_costo = resultado_liquidaciones_centro_costo[
#             resultado_liquidaciones_centro_costo['Fecha']>last_date_historico
#         ]
# except:
#     pass

# resultado_liquidaciones_centro_costo = pd.concat([resultado_liquidaciones_historico_centro_costo, resultado_liquidaciones_centro_costo])
# resultado_liquidaciones_centro_costo = resultado_liquidaciones_centro_costo.sort_values(by=['CodigoEmpleado', 'Fecha'])

# for codigo_empleado_excepcion in excepciones_pagos_acumulados:
#     excepcion = excepciones_pagos_acumulados[codigo_empleado_excepcion]
#     resultado_liquidaciones_centro_costo['PagoReal'] = np.where(
#         (
#             (resultado_liquidaciones_centro_costo['CodigoEmpleado'] == codigo_empleado_excepcion) &
#             (resultado_liquidaciones_centro_costo['Fecha'] <= excepcion['Fecha'])
#         ),
#         excepcion['ValorPagoAcumulado'],
#         resultado_liquidaciones_centro_costo['PagoReal']
#     )

# for codigo_empleado_excepcion in excepciones_diferencias:
#     excepcion = excepciones_diferencias[codigo_empleado_excepcion]
#     resultado_liquidaciones_centro_costo['PagoReal'] = np.where(
#         (
#             (resultado_liquidaciones_centro_costo['CodigoEmpleado'] == codigo_empleado_excepcion) &
#             (resultado_liquidaciones_centro_costo['Fecha'] == excepcion['Fecha'])
#         ),
#         resultado_liquidaciones_centro_costo['PagoReal'] + excepcion['ValorDiferencia'],
#         resultado_liquidaciones_centro_costo['PagoReal']
#     )

# resultado_liquidaciones_centro_costo['PagadoFecha'] = resultado_liquidaciones_centro_costo.groupby(['CodigoEmpleado'])['PagoReal'].transform(pd.Series.cumsum)
# resultado_liquidaciones_centro_costo['PagadoFecha'] = resultado_liquidaciones_centro_costo['PagadoFecha'] - resultado_liquidaciones_centro_costo['PagoReal']
# resultado_liquidaciones_centro_costo

In [162]:
# resultado_liquidaciones_centro_costo.drop_duplicates(['CodigoEmpleado', 'Fecha'], inplace=True)

# resultado_final_centro_costo = pd.merge(
#     left=resultado_liquidaciones_centro_costo[['CodigoEmpleado', 'Fecha', 'PagoGarantizado', 'Liquidado', 'PagoReal','PagadoFecha', 'FactorMes', 'CodigoCentroCosto']],
#     right=df_empleados,
#     on=['CodigoEmpleado'],
#     how='left'
# )
# resultado_final_centro_costo = resultado_final_centro_costo[['Identificacion', 'Nombre', 'Apellidos', 'CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Fecha', 'SalarioVariable', 'PagoGarantizado', 'FactorMes', 'Liquidado', 'PagoReal', 'PagadoFecha', 'CodigoCentroCosto']]
# resultado_final_centro_costo = resultado_final_centro_costo.sort_values(by=['TipoEmpleado', 'AreaCalculo', 'CodigoEmpleado', 'Fecha', 'CodigoCentroCosto'])

# resultado_final_centro_costo.rename(columns={
#     'Identificacion': 'Cédula',
#     'CodigoEmpleado': 'Código',
#     'TipoEmpleado': 'Tipo Empleado',
#     'AreaCalculo': 'Área de cálculo',
#     'Liquidado': 'Valor liquidado',
#     'PagoReal': 'Valor neto a pagar',
#     'PagadoFecha': 'Pagado a la fecha',
#     'SalarioVariable': 'Salario variable',
#     'FactorMes': 'Factor mes',
#     'PagoGarantizado': '¿Pago garantizado?'
# }, inplace=True)
# resultado_final_centro_costo.head()

In [163]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '16659046']

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, FactorMes, PagoGarantizado, Liquidado, PagoReal, PagadoFecha]
Index: []

In [164]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '1111135']

Empty DataFrame
Columns: [CodigoEmpleado, SalarioVariable, Fecha, FactorMes, PagoGarantizado, Liquidado, PagoReal, PagadoFecha]
Index: []

In [165]:
resultado_liquidaciones[resultado_liquidaciones['CodigoEmpleado'] == '79539822']

,CodigoEmpleado,SalarioVariable,Fecha,FactorMes,PagoGarantizado,Liquidado,PagoReal,PagadoFecha
15,79539822,3.285000e+06,2025-01-01,1.0,NO,3087900.00,1642500.00,0.00
159,79539822,3.285000e+06,2025-02-01,2.0,NO,3400000.00,1757500.00,1642500.00
309,79539822,3.285000e+06,2025-03-01,3.0,NO,5398183.33,1998183.33,3400000.00
455,79539822,3.285000e+06,2025-04-01,4.0,NO,13138500.00,7740316.67,5398183.33
597,79539822,3.285000e+06,2025-05-01,5.0,NO,16477750.00,3339250.00,13138500.00
739,79539822,3.285000e+06,2025-06-01,6.0,NO,19191200.00,2713450.00,16477750.00
885,79539822,3.285000e+06,2025-07-01,7.0,NO,23156250.00,3965050.00,19191200.00
1029,79539822,3.285000e+06,2025-08-01,8.0,NO,25658800.00,2502550.00,23156250.00
1177,79539822,3.285000e+06,2025-09-01,9.0,NO,28892600.00,3233800.00,25658800.00
1325,79539822,3.285000e+06,2025-10-01,10.0,NO,32126400.00,3233800.00,28892600.00
1473,79539822,3.285000e+06,2025-11-01,11.0,NO,35360200.00,3233800.00,32126400.00
1745,79539822,3.495833e+06,2025-12-01,12.0,NO,79705000.00,44344800.00,35360200.00

In [166]:
resultado_liquidaciones_mayo = resultado_liquidaciones[resultado_liquidaciones['Fecha'] == '2024-05-01']

In [167]:
# resultado_final_centro_costo.to_excel(os.path.join(OUTPUT_FOLDER, 'resultado_final_centro_costo.xlsx'))
maestra_resultados_por_empleado.to_excel(os.path.join(OUTPUT_FOLDER, 'maestra_resultados_por_empleado.xlsx'))
maestra_resultados_por_empleado_centro_costo.to_excel(os.path.join(OUTPUT_FOLDER, 'maestra_resultados_por_empleado_centro_costo.xlsx'))
resultado_liquidaciones.to_excel(os.path.join(OUTPUT_FOLDER, 'resultado_liquidaciones.xlsx'))
resultado_final.to_excel(os.path.join(OUTPUT_FOLDER, 'resultado_final.xlsx'))
maestra_resultados.to_excel(os.path.join(OUTPUT_FOLDER, 'maestra_resultados.xlsx'))

In [168]:
# resultado_liquidaciones = resultado_liquidaciones.reset_index()
# resultados_comparacion_nomina = resultados_comparacion_nomina.reset_index()

In [169]:
resultados_comparacion_nomina = pd.read_excel(
        io=os.path.join('C:\\Users\\Crisp\\Documents\\QualitySoftGroup\\Empresas\\Complemento360\\NR - Cambio de Parrillas','Relacion Compara datos de liquidacion 29jun2024 vs reportados a Nomina.xlsx'),
        dtype={
            'Código': str,
            'Fecha': 'datetime64[ns]',
            '¿Pago garantizado?': str,
            'Valor liquidado reportado a Nomina':float ,
            'Valor Neto a Pagar Reportado a Nomina': float,
            'Pagado a la fecha Reportado a Nomina': float,
        }
    )
resultados_comparacion_nomina.rename(columns={'Código':'CodigoEmpleado'}, inplace=True)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Crisp\\Documents\\QualitySoftGroup\\Empresas\\Complemento360\\NR - Cambio de Parrillas\\Relacion Compara datos de liquidacion 29jun2024 vs reportados a Nomina.xlsx'

In [ ]:
resultados_comparacion_nomina = resultados_comparacion_nomina.merge(
    resultado_liquidaciones_mayo,
    on=['CodigoEmpleado', 'Fecha'],
    how='left'
)

In [ ]:
resultados_comparacion_nomina.columns

In [ ]:
# resultados_comparacion_nomina['Valor liquidado'] = resultados_comparacion_nomina['Liquidado']
# resultados_comparacion_nomina['Valor neto a pagar'] = resultados_comparacion_nomina['PagoReal']
# resultados_comparacion_nomina['Pagado a la fecha'] = resultados_comparacion_nomina['PagadoFecha']

In [ ]:
resultados_comparacion_nomina['Nueva Diferencia Valor Liquidado'] = resultados_comparacion_nomina['Valor liquidado reportado a Nomina'] - resultados_comparacion_nomina['Liquidado']
resultados_comparacion_nomina['Nueva Diferencia Valor Neto a Pagar'] = resultados_comparacion_nomina['Valor Neto a Pagar Reportado a Nomina'] - resultados_comparacion_nomina['PagoReal']
resultados_comparacion_nomina['Nueva Diferencia Pagado a la fecha'] = resultados_comparacion_nomina['Pagado a la fecha Reportado a Nomina'] - resultados_comparacion_nomina['PagadoFecha']
resultados_comparacion_nomina

In [ ]:
resultados_comparacion_nomina[resultados_comparacion_nomina['CodigoEmpleado'] == '1111135']

In [ ]:
resultados_comparacion_nomina.to_excel(os.path.join(OUTPUT_FOLDER, 'resultados_comparacion_nomina.xlsx'))

In [ ]:
resultados_comparacion_nomina[resultados_comparacion_nomina['Nueva Diferencia Valor Liquidado'] > 1]

In [ ]:
resultados_comparacion_nomina[resultados_comparacion_nomina['Nueva Diferencia Valor Liquidado'] < -1]

## Generación de PDFs

In [ ]:
def get_dataframes(
        df_resultado_detallado,
        df_resultado_liquidaciones
):
    resultado_liquidaciones = df_resultado_liquidaciones.set_index(['CodigoEmpleado', 'Fecha'])
    resultado_liquidaciones.fillna(value={
        'PagoReal': 0,
        'Liquidacion': 0
    }, inplace=True)

    resultado_detallado = df_resultado_detallado.fillna(value={
        'FactorIncentivo': 0,
        'PorcentajeCumplimiento': 0,
        'Presupuesto': 0,
        'Real': 0,
        'Liquidado': 0,
        'ResultadoPresupuesto': 0,
        'ResultadoRealMes': 0,
        'PorcentajeCumplimientoMes': 0
    })

    return resultado_detallado, resultado_liquidaciones

In [ ]:
df_detalles_para_pdf, df_liquidaciones_para_pdf = get_dataframes(
    df_resultado_detallado=maestra_resultados_por_empleado,
    df_resultado_liquidaciones=resultado_liquidaciones
)