In [1]:
import os
import sys
import pandas as pd
import numpy as np
from datetime import datetime
import import_ipynb
from shared_functions import DataframeLoader, Shared
base_dir = 'C:\\Users\\HP\\Documents\\Proyectos\\Liquidations-Incentives-Jupyter'
sub_direct = 'archivos-fuente-128 (1)'
folder_bbraun_source = os.path.join(base_dir, 'source', sub_direct)
folder_bbraun_output = os.path.join(base_dir, 'output')
print(folder_bbraun_source)

C:\Users\HP\Documents\Proyectos\Liquidations-Incentives-Jupyter\source\archivos-fuente-117

In [2]:
dataframe_loader = DataframeLoader(
    base_dir=base_dir,
    sub_direct=sub_direct
)
shared = Shared()
print(dataframe_loader.cargar_dataframes)

<bound method DataframeLoader.cargar_dataframes of <shared_functions.DataframeLoader object at 0x000002567879F740>>

In [3]:
(
        df_resultado_detallado_previo,
        df_resultado_liquidaciones_previo,
        df_empleados,
        df_empleados_inactivos,
        df_tipos_empleados,
        df_clusters_empleado,
        df_zonas_empleado,
        df_salarios_variables,
        df_parrillas,
        df_venta_recaudo_real,
        df_venta_recaudo_presupuesto,
        df_venta_por_zona,
        df_recaudo_por_zona,
        df_rentabilidad,
        df_venta_otras_companias,
        df_recaudo_otras_companias,
        df_venta_recaudo_kams,
        df_rentabilidad_kam,
        df_venta_servicios_mtto,
        df_objetivos_cualitativos,
        df_kpi_calidad,
        df_incentivos_por_empleado,
        df_area_calculo_sba,
        df_factores_liquidacion,
        df_cluster_plan_real_recaudo,
        df_zona_plan_real_venta_ch,
        df_rentabilidad_zona,
        df_resultados_variables_cualitativas,
        df_zonas_clusters_empleado,
        df_centros_costos,
        df_empleados_centros_costos,
        df_centros_costos_grupos_productos_divisiones,
        df_parrillas_tipos_calculos,
        df_area_calculo_sba_centros_costos,
        df_renal_ambulatorio,
        df_TRM,
        codigos_ve_vc,
        _dataframes_entrada,
        fecha_liquidacion,
        meses_incentivos,
        OUTPUT_FOLDER
    ) = dataframe_loader.cargar_dataframes(base_dir, folder_bbraun_source)

In [4]:
maestra_resultados_por_empleado = pd.read_excel(
        io=os.path.join(folder_bbraun_output, 'maestra_resultados_por_empleado.xlsx'),
        dtype={
            'Contexto': str,
            'Fecha': 'datetime64[ns]',
            'Variable': str,
            'PorcentajeCumplimiento':float ,
            'Real': float,
            'Presupuesto': float,
            'CodigoEmpleado': str
        }
    )
maestra_resultados_por_empleado

,Unnamed: 0.1,Contexto,Fecha,Variable,PorcentajeCumplimiento,Real,Presupuesto,CodigoEmpleado,Porcentaje,Consecutivo,...,ResultadoRealMes,PorcentajeCumplimientoMes,Unnamed: 0,RealCOP,PresupuestoCOP,PorcentajeCumplimientoCOP,Nombre variable,Nombre consecutivo,_merge,NuevoFactorBK
0,4247,Pais,2025-04-01,VentaCobradaBraunPais,0.95,7.504289e+10,7.873086e+10,1010180302,0.25,0.0,...,2.090346e+10,1.12,3.0,0.0,0.0,0.0,Venta cobrada país,NaN,both,4.0
1,0,1013587064,2025-01-01,ObjetivosCualitativos,0.90,0.000000e+00,0.000000e+00,1013587064,0.40,0.0,...,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1013587064_2,2025-01-01,KpisSurgical,1.12,0.000000e+00,0.000000e+00,1013587064,0.20,2.0,...,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,1013587064_3,2025-01-01,KpisSurgical,1.01,0.000000e+00,0.000000e+00,1013587064,0.20,3.0,...,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,546,1013587064,2025-02-01,ObjetivosCualitativos,0.90,0.000000e+00,0.000000e+00,1013587064,0.40,0.0,...,0.000000e+00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4212,13368,5036358,2025-04-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,NaN,NaN,NaN,...,0.000000e+00,0.00,829.0,0.0,0.0,0.0,NaN,NaN,left_only,4.0
4213,13374,70038624,2025-04-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,NaN,NaN,NaN,...,0.000000e+00,0.00,835.0,0.0,0.0,0.0,NaN,NaN,left_only,4.0
4214,13380,5016700,2025-04-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,NaN,NaN,NaN,...,0.000000e+00,0.00,841.0,0.0,0.0,0.0,NaN,NaN,left_only,4.0
4215,13386,5041312,2025-04-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,NaN,NaN,NaN,...,0.000000e+00,0.00,847.0,0.0,0.0,0.0,NaN,NaN,left_only,4.0
4216,13392,5016782,2025-04-01,KpiCalidad,0.94,0.000000e+00,0.000000e+00,NaN,NaN,NaN,...,0.000000e+00,0.00,853.0,0.0,0.0,0.0,NaN,NaN,left_only,4.0

In [5]:
# maestra_resultados_por_empleado = pd.read_excel(io=os.path.join(folder_bbraun_output, 'maestra_resultados_por_empleado.xlsx'))
# maestra_resultados_por_empleado['CodigoEmpleado'] = maestra_resultados_por_empleado['CodigoEmpleado'].astype(str)
# maestra_resultados_por_empleado

In [6]:
maestra_resultados_por_empleado_centro_costo = pd.read_excel(
        io=os.path.join(folder_bbraun_output, 'maestra_resultados_por_empleado_centro_costo.xlsx'),
        dtype={
            'Contexto': str,
            'Fecha': 'datetime64[ns]',
            'Variable': str,
            'PorcentajeCumplimiento':float ,
            'Real': float,
            'Presupuesto': float,
            'CodigoEmpleado': str,
            'CodigoCentroCosto': str
        }
    )
maestra_resultados_por_empleado_centro_costo.drop(columns=['Unnamed: 0'], inplace=True)
maestra_resultados_por_empleado_centro_costo

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,...,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0.56,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,1.07,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,1.28,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0.23,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,1.68,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16957,5004293_3,2025-02-01,620,HC,323015090,3.626427e+05,4.337195e+05,VentaFacturadaGrupoClientesKAMSSub,0.84,1.631783e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
16958,5004293_3,2025-03-01,620,HC,323015090,6.803036e+05,6.888486e+05,VentaFacturadaGrupoClientesKAMSSub,0.99,3.061162e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
16959,5004293_3,2025-04-01,620,HC,323015090,9.161635e+05,8.993301e+05,VentaFacturadaGrupoClientesKAMSSub,1.02,4.122461e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
16960,5004293_3,2025-05-01,620,HC,323015090,1.210787e+06,1.173594e+06,VentaFacturadaGrupoClientesKAMSSub,1.03,5.448178e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
16961,5004293_3,2025-06-01,620,HC,323015090,1.472058e+06,1.438290e+06,VentaFacturadaGrupoClientesKAMSSub,1.02,6.623818e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [7]:
maestra_resultados_por_empleado_centro_costo[maestra_resultados_por_empleado_centro_costo['Variable'] == 'RentabilidadUnidadNegocioCM2COGSSUB']

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,...,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable
15322,5004300_10,2025-03-01,610,HC,323015050,2.856651e+05,3.265726e+05,RentabilidadUnidadNegocioCM2COGSSUB,0.87,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.,GU,4.0,IBAÑEZ,WILSON,2023-09-01,5174400.0
15323,5004300_10,2025-03-01,630,HC,323015050,6.205437e+05,1.172034e+06,RentabilidadUnidadNegocioCM2COGSSUB,0.53,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.,GU,4.0,IBAÑEZ,WILSON,2023-09-01,5174400.0
15324,5004300_10,2025-03-01,CDK,HC,323015050,3.732267e+03,5.207784e+03,RentabilidadUnidadNegocioCM2COGSSUB,0.72,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.,GU,4.0,IBAÑEZ,WILSON,2023-09-01,5174400.0
15325,5004300_10,2025-04-01,610,HC,323015050,7.758064e+05,7.657564e+05,RentabilidadUnidadNegocioCM2COGSSUB,1.01,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.,GU,4.0,IBAÑEZ,WILSON,2023-09-01,5233200.0
15326,5004300_10,2025-04-01,630,HC,323015050,1.629590e+06,2.696816e+06,RentabilidadUnidadNegocioCM2COGSSUB,0.60,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Infusion Systems & Disposables.,GU,4.0,IBAÑEZ,WILSON,2023-09-01,5233200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15465,70029960_10,2025-04-01,620,HC,323015045,6.060368e+06,6.338261e+06,RentabilidadUnidadNegocioCM2COGSSUB,0.96,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Vascular Access & Reg Anest.,GU,5.0,CHAPARRO CARDENAS,MARIA ALEJANDRA,2024-10-01,4840000.0
15466,70029960_10,2025-05-01,610,HC,323015045,1.495418e+06,1.349726e+06,RentabilidadUnidadNegocioCM2COGSSUB,1.11,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Vascular Access & Reg Anest.,GU,5.0,CHAPARRO CARDENAS,MARIA ALEJANDRA,2024-10-01,NaN
15467,70029960_10,2025-05-01,620,HC,323015045,1.089311e+07,1.102196e+07,RentabilidadUnidadNegocioCM2COGSSUB,0.99,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Vascular Access & Reg Anest.,GU,5.0,CHAPARRO CARDENAS,MARIA ALEJANDRA,2024-10-01,NaN
15468,70029960_10,2025-06-01,610,HC,323015045,2.402138e+06,2.076873e+06,RentabilidadUnidadNegocioCM2COGSSUB,1.16,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Vascular Access & Reg Anest.,GU,5.0,CHAPARRO CARDENAS,MARIA ALEJANDRA,2024-10-01,NaN
15469,70029960_10,2025-06-01,620,HC,323015045,1.673265e+07,1.676203e+07,RentabilidadUnidadNegocioCM2COGSSUB,1.00,0.0,...,0.2,10.0,RentabilidadUnidadNegocioCM2COGSSUB,Vascular Access & Reg Anest.,GU,5.0,CHAPARRO CARDENAS,MARIA ALEJANDRA,2024-10-01,NaN

In [8]:
maestra_resultados_por_empleado_centro_costo[
    (maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] == '1032450706') &
    (maestra_resultados_por_empleado_centro_costo['Fecha'] == '2023-01-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, GrupoProducto, Division, CodigoCentroCosto, Real, Presupuesto, Variable, PorcentajeCumplimiento, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, SalarioVariable]
Index: []

[0 rows x 23 columns]

In [9]:
# maestra_resultados_por_empleado_centro_costo = pd.read_excel(io=os.path.join(folder_bbraun_output, 'maestra_resultados_por_empleado_centro_costo.xlsx'))
# maestra_resultados_por_empleado_centro_costo

In [10]:
resultado_final = pd.read_excel(io=os.path.join(folder_bbraun_output, 'resultado_final.xlsx'))
resultado_final

,Unnamed: 0,Cédula,Nombre,Apellidos,Código,Tipo Empleado,Área de cálculo,Fecha,Salario variable,¿Pago garantizado?,Factor mes,Valor liquidado,Valor neto a pagar,Pagado a la fecha
0,74,52057371.0,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-01-01,1083000.0,NO,1,108300.00,541500.00,0.0
1,75,52057371.0,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-02-01,1083000.0,NO,2,1137150.00,595650.00,541500.0
2,76,52057371.0,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-03-01,1083000.0,NO,3,1097902.08,0.00,1137150.0
3,77,52057371.0,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-04-01,1083000.0,NO,4,6441424.08,5304274.08,1137150.0
4,176,79641686.0,RICARDO,BENAVIDES,5016686,AD,2.0,2025-01-01,1000000.0,NO,1,100000.00,500000.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,525,NaN,NaN,NaN,70032756,NaN,NaN,2025-01-01,NaN,NO,1,400000.00,2000000.00,0.0
574,526,NaN,NaN,NaN,70032756,NaN,NaN,2025-02-01,NaN,NO,2,4000000.00,2000000.00,2000000.0
575,527,NaN,NaN,NaN,70032756,NaN,NaN,2025-03-01,NaN,NO,3,3801600.00,0.00,4000000.0
576,573,NaN,NaN,NaN,9990010,NaN,NaN,2025-01-01,NaN,NO,1,0.00,0.00,0.0
577,574,NaN,NaN,NaN,9990010,NaN,NaN,2025-02-01,NaN,NO,2,0.00,0.00,0.0

## Casos Liquidación Centro de Costo

In [11]:
# Convertir las columnas a str
resultado_final['Código'] = resultado_final['Código'].astype(str)
df_empleados_centros_costos['CodigoEmpleado'] = df_empleados_centros_costos['CodigoEmpleado'].astype(str)

In [12]:
resultado_final_liquidacion_centro_costo = resultado_final.rename(columns={'Código': 'CodigoEmpleado'}).merge(
    df_empleados_centros_costos,
    on=['CodigoEmpleado'],
    how='left'
).rename(columns={
    'Fecha': 'Fecha Proceso',
    'PorcentajeAsignacion': 'Porcentaje Aplicado'
})
resultado_final_liquidacion_centro_costo.fillna(0, inplace=True)
resultado_final_liquidacion_centro_costo

,Unnamed: 0,Cédula,Nombre,Apellidos,CodigoEmpleado,Tipo Empleado,Área de cálculo,Fecha Proceso,Salario variable,¿Pago garantizado?,Factor mes,Valor liquidado,Valor neto a pagar,Pagado a la fecha,CodigoCentroCosto,Porcentaje Aplicado
0,74,52057371.0,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-01-01,1083000.0,NO,1,108300.00,541500.00,0.0,323004010,1.0
1,75,52057371.0,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-02-01,1083000.0,NO,2,1137150.00,595650.00,541500.0,323004010,1.0
2,76,52057371.0,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-03-01,1083000.0,NO,3,1097902.08,0.00,1137150.0,323004010,1.0
3,77,52057371.0,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-04-01,1083000.0,NO,4,6441424.08,5304274.08,1137150.0,323004010,1.0
4,176,79641686.0,RICARDO,BENAVIDES,5016686,AD,2.0,2025-01-01,1000000.0,NO,1,100000.00,500000.00,0.0,323004010,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,525,0.0,0,0,70032756,0,0.0,2025-01-01,0.0,NO,1,400000.00,2000000.00,0.0,323004040,1.0
981,526,0.0,0,0,70032756,0,0.0,2025-02-01,0.0,NO,2,4000000.00,2000000.00,2000000.0,323004040,1.0
982,527,0.0,0,0,70032756,0,0.0,2025-03-01,0.0,NO,3,3801600.00,0.00,4000000.0,323004040,1.0
983,573,0.0,0,0,9990010,0,0.0,2025-01-01,0.0,NO,1,0.00,0.00,0.0,0,0.0
984,574,0.0,0,0,9990010,0,0.0,2025-02-01,0.0,NO,2,0.00,0.00,0.0,0,0.0

In [13]:
resultado_final_liquidacion_centro_costo[resultado_final_liquidacion_centro_costo['CodigoEmpleado'] == '80220240']

Empty DataFrame
Columns: [Unnamed: 0, Cédula, Nombre, Apellidos, CodigoEmpleado, Tipo Empleado, Área de cálculo, Fecha Proceso, Salario variable, ¿Pago garantizado?, Factor mes, Valor liquidado, Valor neto a pagar, Pagado a la fecha, CodigoCentroCosto, Porcentaje Aplicado]
Index: []

In [14]:
resultado_final_liquidacion_centro_costo.to_excel('resultado_final_liquidacion_centro_costo.xlsx')

In [15]:
# resultado_final_liquidacion_centro_costo['CodigoEmpleado'] = resultado_final_liquidacion_centro_costo['CodigoEmpleado'].astype(str)

### Caso 1 - Liquidación Centro de Costo

In [16]:
liquidacion_centro_costo_caso1 = resultado_final_liquidacion_centro_costo[
    (resultado_final_liquidacion_centro_costo['Valor liquidado'] < resultado_final_liquidacion_centro_costo['Pagado a la fecha']) &
    (resultado_final_liquidacion_centro_costo['¿Pago garantizado?'] == 'NO')
].copy()

# Asignar nuevos valores usando .loc para evitar SettingWithCopyWarning
liquidacion_centro_costo_caso1.loc[:, 'Consecutivo'] = 0.0
liquidacion_centro_costo_caso1.loc[:, 'TipoCalculo'] = 'F'

liquidacion_centro_costo_caso1

,Unnamed: 0,Cédula,Nombre,Apellidos,CodigoEmpleado,Tipo Empleado,Área de cálculo,Fecha Proceso,Salario variable,¿Pago garantizado?,Factor mes,Valor liquidado,Valor neto a pagar,Pagado a la fecha,CodigoCentroCosto,Porcentaje Aplicado,Consecutivo,TipoCalculo
2,76,5.205737e+07,NUBIA YANNETH,JIMENEZ MOLINA,5003668,AD,2.0,2025-03-01,1083000.0,NO,3,1.097902e+06,0.0,1137150.0,323004010,1.00,0.0,F
6,178,7.964169e+07,RICARDO,BENAVIDES,5016686,AD,2.0,2025-03-01,1000000.0,NO,3,9.504000e+05,0.0,1000000.0,323004010,1.00,0.0,F
10,326,1.018452e+09,Diana,Mateus,5043078,AD,2.0,2025-03-01,1000000.0,NO,3,9.504000e+05,0.0,1000000.0,323004010,1.00,0.0,F
14,436,1.019141e+09,Ana,Silva Bermudez,70014725,AD,2.0,2025-03-01,1000000.0,NO,3,9.947520e+05,0.0,1035000.0,323004010,1.00,0.0,F
21,83,1.665905e+07,ADOLFO MARIO,REYES MONROY,5004286,AD,3.0,2025-03-01,3149000.0,NO,3,3.192330e+06,0.0,3306450.0,323004050,1.00,0.0,F
25,261,3.040543e+07,MARIA CAROLINA,RAVE LARA,5019930,AD1,2.0,2025-03-01,1964000.0,NO,3,1.891486e+06,0.0,1983650.0,323004024,1.00,0.0,F
29,291,8.003719e+07,Gabriel,Salamanca,5037350,AD1,2.0,2025-03-01,600000.0,NO,3,5.702400e+05,0.0,600000.0,323004024,1.00,0.0,F
33,440,1.098613e+09,Andres,Serrano,70015570,AD1,3.0,2025-03-01,600000.0,NO,3,5.930496e+05,0.0,618000.0,323004021,1.00,0.0,F
41,424,7.995043e+07,Juan David,Forero,70014232,AD1,4.0,2025-03-01,1090000.0,NO,3,1.035936e+06,0.0,1090000.0,323004033,0.03,0.0,F
42,424,7.995043e+07,Juan David,Forero,70014232,AD1,4.0,2025-03-01,1090000.0,NO,3,1.035936e+06,0.0,1090000.0,323004034,0.75,0.0,F
43,424,7.995043e+07,Juan David,Forero,70014232,AD1,4.0,2025-03-01,1090000.0,NO,3,1.035936e+06,0.0,1090000.0,323004036,0.22,0.0,F
53,448,1.037583e+09,Aleja ndra,Hincapie,70015881,AD1,4.0,2025-03-01,1500000.0,NO,3,1.520640e+06,0.0,1575000.0,323004033,0.03,0.0,F
54,448,1.037583e+09,Aleja ndra,Hincapie,70015881,AD1,4.0,2025-03-01,1500000.0,NO,3,1.520640e+06,0.0,1575000.0,323004034,0.75,0.0,F
55,448,1.037583e+09,Aleja ndra,Hincapie,70015881,AD1,4.0,2025-03-01,1500000.0,NO,3,1.520640e+06,0.0,1575000.0,323004036,0.22,0.0,F
74,408,5.315446e+07,Yeimy Andrea,Calderon Martinez,70010478,AD1,5.0,2025-03-01,1195000.0,NO,3,1.135728e+06,0.0,1195000.0,323004033,0.03,0.0,F
75,408,5.315446e+07,Yeimy Andrea,Calderon Martinez,70010478,AD1,5.0,2025-03-01,1195000.0,NO,3,1.135728e+06,0.0,1195000.0,323004034,0.75,0.0,F
76,408,5.315446e+07,Yeimy Andrea,Calderon Martinez,70010478,AD1,5.0,2025-03-01,1195000.0,NO,3,1.135728e+06,0.0,1195000.0,323004036,0.22,0.0,F
82,233,1.098619e+09,MAYERLIS,RANGEL PEINADO,5016772,AD1,10.0,2025-03-01,600000.0,NO,3,6.082560e+05,0.0,630000.0,323004021,1.00,0.0,F
136,151,5.219700e+07,ANA MARIA,ROJAS,5016628,AD3,2.0,2025-03-01,3115000.0,NO,3,2.960496e+06,0.0,3115000.0,323011150,0.22,0.0,F
137,151,5.219700e+07,ANA MARIA,ROJAS,5016628,AD3,2.0,2025-03-01,3115000.0,NO,3,2.960496e+06,0.0,3115000.0,323016400,0.75,0.0,F
138,151,5.219700e+07,ANA MARIA,ROJAS,5016628,AD3,2.0,2025-03-01,3115000.0,NO,3,2.960496e+06,0.0,3115000.0,323017030,0.03,0.0,F
153,155,5.235318e+07,ALEXANDRA,PARRADO,5016635,AD5,1.0,2025-03-01,4468000.0,NO,3,4.529480e+06,0.0,4691400.0,323004072,1.00,0.0,F
209,190,7.994686e+07,JORGE,AREVALO,5016692,GD,2.0,2025-03-01,9241000.0,NO,3,6.124126e+06,0.0,9656850.0,323015065,0.34,0.0,F
210,190,7.994686e+07,JORGE,AREVALO,5016692,GD,2.0,2025-03-01,9241000.0,NO,3,6.124126e+06,0.0,9656850.0,323015070,0.33,0.0,F
211,190,7.994686e+07,JORGE,AREVALO,5016692,GD,2.0,2025-03-01,9241000.0,NO,3,6.124126e+06,0.0,9656850.0,323015075,0.33,0.0,F
302,318,8.091294e+07,YEFERSON ASDRUVAL,GORDILLO BELTRAN,5041774,MK,5.0,2025-03-01,2552000.0,NO,3,1.982434e+06,0.0,2632400.0,323015045,0.25,0.0,F
303,318,8.091294e+07,YEFERSON ASDRUVAL,GORDILLO BELTRAN,5041774,MK,5.0,2025-03-01,2552000.0,NO,3,1.982434e+06,0.0,2632400.0,323015050,0.60,0.0,F
304,318,8.091294e+07,YEFERSON ASDRUVAL,GORDILLO BELTRAN,5041774,MK,5.0,2025-03-01,2552000.0,NO,3,1.982434e+06,0.0,2632400.0,323015095,0.15,0.0,F
314,64,8.041050e+07,MARIO ALBERTO,RINCON RIVERA,5002773,MK,6.0,2025-03-01,3630000.0,NO,3,2.779238e+06,0.0,3726200.0,323007270,0.05,0.0,F
315,64,8.041050e+07,MARIO ALBERTO,RINCON RIVERA,5002773,MK,6.0,2025-03-01,3630000.0,NO,3,2.779238e+06,0.0,3726200.0,323007350,0.05,0.0,F
316,64,8.041050e+07,MARIO ALBERTO,RINCON RIVERA,5002773,MK,6.0,2025-03-01,3630000.0,NO,3,2.779238e+06,0.0,3726200.0,323015050,0.90,0.0,F
487,117,3.695233e+07,SOBEYDA DEL SOCORRO,ACOSTA PORTILLO,5004523,VC,3.0,2025-04-01,2500000.0,NO,4,6.473162e+06,0.0,7371525.0,323007332,0.10,0.0,F
488,117,3.695233e+07,SOBEYDA DEL SOCORRO,ACOSTA PORTILLO,5004523,VC,3.0,2025-04-01,2500000.0,NO,4,6.473162e+06,0.0,7371525.0,323007333,0.10,0.0,F
489,117,3.695233e+07,SOBEYDA DEL SOCORRO,ACOSTA PORTILLO,5004523,VC,3.0,2025-04-01,2500000.0,NO,4,6.473162e+06,0.0,7371525.0,323010165,0.80,0.0,F
750,128,6.344968e+07,ADRIANA,PABON,5005355,VE,2.0,2025-04-01,2500000.0,NO,4,6.705234e+06,0.0,6757500.0,323007260,0.50,0.0,F
751,128,6.344968e+07,ADRIANA,PABON,5005355,VE,2.0,2025-04-01,2500000.0,NO,4,6.705234e+06,0.0,6757500.0,323007300,0.05,0.0,F
752,128,6.344968e+07,ADRIANA,PABON,5005355,VE,2.0,2025-04-01,2500000.0,NO,4,6.705234e+06,0.0,6757500.0,323007350,0.45,0.0,F
768,288,1.020799e+09,JENNIFER CAMILA,RIVERA PACHON,5037259,VE,3.0,2025-04-01,2500000.0,NO,4,3.047656e+06,0.0,4000937.5,323007270,1.00,0.0,F
792,351,1.429675e+07,John Eder,Carrera Canizales,70002044,VE,4.0,2025-04-01,2760000.0,NO,4,6.191290e+06,0.0,7657172.5,323015050,1.00,0.0,F
807,52,4.278492e+07,PAMELA MARIA,ROLDAN VASQUEZ,5002721,VE,5.0,2025-03-01,2963000.0,NO,3,2.899915e+06,0.0,3051900.0,323015045,1.00,0.0,F
881,481,7.962510e+07,Carlos Eduardo,Amaya Forero,70021970,VE,11.0,2025-04-01,2500000.0,NO,4,1.147070e+07,0.0,11737500.0,323007330,0.80,0.0,F
882,481,7.962510e+07,Carlos Eduardo,Amaya Forero,70021970,VE,11.0,2025-04-01,2500000.0,NO,4,1.147070e+07,0.0,11737500.0,323007331,0.20,0.0,F
885,500,7.951913e+07,RICARDO,POSADA PALACIO,70029614,VE,11.0,2025-03-01,2500000.0,NO,3,2.054062e+06,0.0,2581250.0,323007330,1.00,0.0,F
919,80,0.000000e+00,0,0,5003791,0,0.0,2025-03-01,0.0,NO,3,6.038208e+06,0.0,6292250.0,323004010,1.00,0.0,F
940,113,0.000000e+00,0,0,5004472,0,0.0,2025-03-01,0.0,NO,3,5.127915e+06,0.0,5272900.0,323004024,1.00,0.0,F
953,206,0.000000e+00,0,0,5016714,0,0.0,2025-03-01,0.0,NO,3,1.863644e+06,0.0,2687700.0,323007270,0.05,0.0,F
954,206,0.000000e+00,0,0,5016714,0,0.0,2025-03-01,0.0,NO,3,1.863644e+06,0.0,2687700.0,323007350,0.05,0.0,F
955,206,0.000000e+00,0,0,5016714,0,0.0,2025-03-01,0.0,NO,3,1.863644e+06,0.0,2687700.0,323015050,0.90,0.0,F
970,386,0.000000e+00,0,0,70002073,0,0.0,2025-03-01,0.0,NO,3,4.752000e+05,0.0,500000.0,323004010,1.00,0.0,F
982,527,0.000000e+00,0,0,70032756,0,0.0,2025-03-01,0.0,NO,3,3.801600e+06,0.0,4000000.0,323004040,1.00,0.0,F

In [17]:
liquidacion_centro_costo_caso1['Diferencia'] = liquidacion_centro_costo_caso1['Pagado a la fecha'] - liquidacion_centro_costo_caso1['Valor liquidado']
liquidacion_centro_costo_caso1 = liquidacion_centro_costo_caso1.rename(columns={'Diferencia': 'Valor Base Cálculo'})[
    ['Fecha Proceso', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo', 'Valor Base Cálculo', 'CodigoCentroCosto', 'Porcentaje Aplicado']
].copy()
liquidacion_centro_costo_caso1['Caso'] = 1 
liquidacion_centro_costo_caso1.head()

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
2,2025-03-01,5003668,F,0.0,39247.92,323004010,1.0,1
6,2025-03-01,5016686,F,0.0,49600.00,323004010,1.0,1
10,2025-03-01,5043078,F,0.0,49600.00,323004010,1.0,1
14,2025-03-01,70014725,F,0.0,40248.00,323004010,1.0,1
21,2025-03-01,5004286,F,0.0,114119.76,323004050,1.0,1

In [18]:
liquidacion_centro_costo_caso1[liquidacion_centro_costo_caso1['CodigoEmpleado'] == '80220240']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso]
Index: []

## Caso 3 - Liquidación Centro de Costo

In [19]:
resultado_final_liquidacion_centro_costo[resultado_final_liquidacion_centro_costo['CodigoEmpleado'] == '1010166177']

Empty DataFrame
Columns: [Unnamed: 0, Cédula, Nombre, Apellidos, CodigoEmpleado, Tipo Empleado, Área de cálculo, Fecha Proceso, Salario variable, ¿Pago garantizado?, Factor mes, Valor liquidado, Valor neto a pagar, Pagado a la fecha, CodigoCentroCosto, Porcentaje Aplicado]
Index: []

In [20]:
liquidacion_centro_costo_garantizado = resultado_final_liquidacion_centro_costo[
    resultado_final_liquidacion_centro_costo['¿Pago garantizado?'] == 'SI'
].copy()
# liquidacion_centro_costo_garantizado = liquidacion_centro_costo_garantizado.rename(columns={'Valor liquidado': 'Valor Base Cálculo'})
liquidacion_centro_costo_garantizado['Valor Base Cálculo'] = liquidacion_centro_costo_garantizado.groupby(['CodigoEmpleado', 'CodigoCentroCosto'])[['Valor liquidado']].transform('sum')
liquidacion_centro_costo_garantizado['Total Meses Garantizado'] = liquidacion_centro_costo_garantizado.groupby(['CodigoEmpleado', 'CodigoCentroCosto'])[['Valor liquidado']].transform('count')
liquidacion_centro_costo_garantizado

,Unnamed: 0,Cédula,Nombre,Apellidos,CodigoEmpleado,Tipo Empleado,Área de cálculo,Fecha Proceso,Salario variable,¿Pago garantizado?,Factor mes,Valor liquidado,Valor neto a pagar,Pagado a la fecha,CodigoCentroCosto,Porcentaje Aplicado,Valor Base Cálculo,Total Meses Garantizado
16,555,5.228275e+07,SANDRA JANNETH,CAÑON HERNANDEZ,70038889,AD,2.0,2025-02-01,1000000.0,SI,0,1000000.0,1000000.0,0.0,323004010,1.00,3000000.0,3
17,556,5.228275e+07,SANDRA JANNETH,CAÑON HERNANDEZ,70038889,AD,2.0,2025-03-01,1000000.0,SI,0,1000000.0,1000000.0,0.0,323004010,1.00,3000000.0,3
18,557,5.228275e+07,SANDRA JANNETH,CAÑON HERNANDEZ,70038889,AD,2.0,2025-04-01,1000000.0,SI,0,1000000.0,1000000.0,0.0,323004010,1.00,3000000.0,3
59,558,8.014532e+07,EDIMER,RENDON LEIVA,70039305,AD1,4.0,2025-02-01,1090000.0,SI,0,1090000.0,1090000.0,0.0,323004033,0.03,3270000.0,3
60,558,8.014532e+07,EDIMER,RENDON LEIVA,70039305,AD1,4.0,2025-02-01,1090000.0,SI,0,1090000.0,1090000.0,0.0,323004034,0.75,3270000.0,3
61,558,8.014532e+07,EDIMER,RENDON LEIVA,70039305,AD1,4.0,2025-02-01,1090000.0,SI,0,1090000.0,1090000.0,0.0,323004036,0.22,3270000.0,3
62,559,8.014532e+07,EDIMER,RENDON LEIVA,70039305,AD1,4.0,2025-03-01,1090000.0,SI,0,1090000.0,1090000.0,0.0,323004033,0.03,3270000.0,3
63,559,8.014532e+07,EDIMER,RENDON LEIVA,70039305,AD1,4.0,2025-03-01,1090000.0,SI,0,1090000.0,1090000.0,0.0,323004034,0.75,3270000.0,3
64,559,8.014532e+07,EDIMER,RENDON LEIVA,70039305,AD1,4.0,2025-03-01,1090000.0,SI,0,1090000.0,1090000.0,0.0,323004036,0.22,3270000.0,3
65,560,8.014532e+07,EDIMER,RENDON LEIVA,70039305,AD1,4.0,2025-04-01,1090000.0,SI,0,1090000.0,1090000.0,0.0,323004033,0.03,3270000.0,3
66,560,8.014532e+07,EDIMER,RENDON LEIVA,70039305,AD1,4.0,2025-04-01,1090000.0,SI,0,1090000.0,1090000.0,0.0,323004034,0.75,3270000.0,3
67,560,8.014532e+07,EDIMER,RENDON LEIVA,70039305,AD1,4.0,2025-04-01,1090000.0,SI,0,1090000.0,1090000.0,0.0,323004036,0.22,3270000.0,3
92,6,1.018419e+09,DIEGO CELIANO,DIAZ,1018418655,AD2,2.0,2025-02-01,348075.0,SI,0,348075.0,348075.0,0.0,0,0.00,1044225.0,3
93,7,1.018419e+09,DIEGO CELIANO,DIAZ,1018418655,AD2,2.0,2025-03-01,348075.0,SI,0,348075.0,348075.0,0.0,0,0.00,1044225.0,3
94,8,1.018419e+09,DIEGO CELIANO,DIAZ,1018418655,AD2,2.0,2025-04-01,348075.0,SI,0,348075.0,348075.0,0.0,0,0.00,1044225.0,3
127,568,7.991416e+07,IVAN,CAMPOS FANDIÑO,79914159,AD2,2.0,2025-02-01,1800000.0,SI,0,1800000.0,1800000.0,0.0,0,0.00,5400000.0,3
128,569,7.991416e+07,IVAN,CAMPOS FANDIÑO,79914159,AD2,2.0,2025-03-01,1800000.0,SI,0,1800000.0,1800000.0,0.0,0,0.00,5400000.0,3
129,570,7.991416e+07,IVAN,CAMPOS FANDIÑO,79914159,AD2,2.0,2025-04-01,1800000.0,SI,0,1800000.0,1800000.0,0.0,0,0.00,5400000.0,3
142,4,1.013631e+09,MARIA CAMILA,NIÑO MORALES,1013630697,AD3,3.0,2025-03-01,1380000.0,SI,0,1380000.0,1380000.0,0.0,323004035,1.00,2760000.0,2
143,5,1.013631e+09,MARIA CAMILA,NIÑO MORALES,1013630697,AD3,3.0,2025-04-01,1380000.0,SI,0,1380000.0,1380000.0,0.0,323004035,1.00,2760000.0,2
148,165,5.300924e+07,YURY MARIEN,GARCIA FORERO,5016665,AD4,2.0,2025-02-01,1500000.0,SI,0,1500000.0,1500000.0,0.0,323004040,1.00,4500000.0,3
149,166,5.300924e+07,YURY MARIEN,GARCIA FORERO,5016665,AD4,2.0,2025-03-01,1500000.0,SI,0,1500000.0,1500000.0,0.0,323004040,1.00,4500000.0,3
150,167,5.300924e+07,YURY MARIEN,GARCIA FORERO,5016665,AD4,2.0,2025-04-01,1500000.0,SI,0,1500000.0,1500000.0,0.0,323004040,1.00,4500000.0,3
241,374,1.140817e+09,ANGELICA MARIA,VARGAS PEREA,70002068,GU,2.0,2025-03-01,3941000.0,SI,0,3941000.0,3941000.0,3236250.0,323007260,0.50,7882000.0,2
242,374,1.140817e+09,ANGELICA MARIA,VARGAS PEREA,70002068,GU,2.0,2025-03-01,3941000.0,SI,0,3941000.0,3941000.0,3236250.0,323007300,0.05,7882000.0,2
243,374,1.140817e+09,ANGELICA MARIA,VARGAS PEREA,70002068,GU,2.0,2025-03-01,3941000.0,SI,0,3941000.0,3941000.0,3236250.0,323007350,0.45,7882000.0,2
244,375,1.140817e+09,ANGELICA MARIA,VARGAS PEREA,70002068,GU,2.0,2025-04-01,3941000.0,SI,0,3941000.0,3941000.0,3236250.0,323007260,0.50,7882000.0,2
245,375,1.140817e+09,ANGELICA MARIA,VARGAS PEREA,70002068,GU,2.0,2025-04-01,3941000.0,SI,0,3941000.0,3941000.0,3236250.0,323007300,0.05,7882000.0,2
246,375,1.140817e+09,ANGELICA MARIA,VARGAS PEREA,70002068,GU,2.0,2025-04-01,3941000.0,SI,0,3941000.0,3941000.0,3236250.0,323007350,0.45,7882000.0,2
247,21,1.047394e+09,LINA MARIA,MENDOZA PEÑA,1047393705,GU,3.0,2025-04-01,3941000.0,SI,0,3941000.0,3941000.0,0.0,0,0.00,3941000.0,1
272,266,1.030522e+09,Diana Andrea,Barona Duque,5032456,GU,11.0,2025-01-01,3000000.0,SI,0,3000000.0,3000000.0,0.0,323007337,1.00,6000000.0,2
273,267,1.030522e+09,Diana Andrea,Barona Duque,5032456,GU,11.0,2025-02-01,3000000.0,SI,0,3000000.0,3000000.0,0.0,323007337,1.00,6000000.0,2
408,540,1.019036e+09,ANDRES FELIPE,LOSADA GUZMAN,70034730,MK,13.0,2025-01-01,476000.0,SI,0,476000.0,476000.0,0.0,323007320,1.00,476000.0,1
452,571,9.452696e+07,JUAN FELIPE,BARAJAS LOPEZ,94526955,MK1,9.0,2025-03-01,4900000.0,SI,0,4900000.0,4900000.0,0.0,323004050,1.00,9800000.0,2
453,572,9.452696e+07,JUAN FELIPE,BARAJAS LOPEZ,94526955,MK1,9.0,2025-04-01,4900000.0,SI,0,4900000.0,4900000.0,0.0,323004050,1.00,9800000.0,2
714,544,5.300007e+07,DERLY CAROLINA,CACERES VELASCO,70036120,VC,4.0,2025-01-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323007337,0.05,2500000.0,1
715,544,5.300007e+07,DERLY CAROLINA,CACERES VELASCO,70036120,VC,4.0,2025-01-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323015065,0.95,2500000.0,1
722,552,1.038414e+09,DAHIANA ANDREA,VELEZ CASTAÑO,70038624,VC,4.0,2025-02-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323007337,0.05,7500000.0,3
723,552,1.038414e+09,DAHIANA ANDREA,VELEZ CASTAÑO,70038624,VC,4.0,2025-02-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323015065,0.95,7500000.0,3
724,553,1.038414e+09,DAHIANA ANDREA,VELEZ CASTAÑO,70038624,VC,4.0,2025-03-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323007337,0.05,7500000.0,3
725,553,1.038414e+09,DAHIANA ANDREA,VELEZ CASTAÑO,70038624,VC,4.0,2025-03-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323015065,0.95,7500000.0,3
726,554,1.038414e+09,DAHIANA ANDREA,VELEZ CASTAÑO,70038624,VC,4.0,2025-04-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323007337,0.05,7500000.0,3
727,554,1.038414e+09,DAHIANA ANDREA,VELEZ CASTAÑO,70038624,VC,4.0,2025-04-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323015065,0.95,7500000.0,3
728,561,2.527882e+07,KATHERINE,RUBIO WILSON,70040806,VC,4.0,2025-04-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323007337,0.05,2500000.0,1
729,561,2.527882e+07,KATHERINE,RUBIO WILSON,70040806,VC,4.0,2025-04-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323015070,0.95,2500000.0,1
733,458,1.010166e+09,William Andres,Castiblanco Martinez,70020733,VC,5.0,2025-01-01,2662500.0,SI,0,2500000.0,2500000.0,0.0,323007337,1.00,5162500.0,2
734,459,1.010166e+09,William Andres,Castiblanco Martinez,70020733,VC,5.0,2025-02-01,2662500.0,SI,0,2662500.0,2662500.0,0.0,323007337,1.00,5162500.0,2
797,532,1.110512e+09,CRISTHIAN DANIEL,RODRIGUEZ,70034526,VE,4.0,2025-01-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323015050,1.00,2500000.0,1
821,536,2.434892e+07,ISABEL CRISTINA,BETANCOURT,70034529,VE,5.0,2025-01-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323015045,1.00,2500000.0,1
857,562,5.530433e+07,Kelly Johanna,Barrios,70042060,VE,7.0,2025-03-01,2820000.0,SI,0,2820000.0,2820000.0,0.0,323015045,1.00,5640000.0,2
858,563,5.530433e+07,Kelly Johanna,Barrios,70042060,VE,7.0,2025-04-01,2820000.0,SI,0,2820000.0,2820000.0,0.0,323015045,1.00,5640000.0,2
895,548,1.022980e+09,DAVID OSWALDO,HIBLA CIPRIAN,70036160,VE,13.0,2025-01-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323007260,0.50,2500000.0,1
896,548,1.022980e+09,DAVID OSWALDO,HIBLA CIPRIAN,70036160,VE,13.0,2025-01-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323007300,0.05,2500000.0,1
897,548,1.022980e+09,DAVID OSWALDO,HIBLA CIPRIAN,70036160,VE,13.0,2025-01-01,2500000.0,SI,0,2500000.0,2500000.0,0.0,323007350,0.45,2500000.0,1
907,30,0.000000e+00,0,0,25278820,0,0.0,2025-03-01,0.0,SI,0,2500000.0,2500000.0,0.0,0,0.00,2500000.0,1

In [21]:
liquidacion_centro_costo_garantizado = liquidacion_centro_costo_garantizado[
    [
        'Fecha Proceso', 'CodigoEmpleado', 'Valor Base Cálculo', 'CodigoCentroCosto', 'Porcentaje Aplicado'
    ]
]
liquidacion_centro_costo_garantizado

,Fecha Proceso,CodigoEmpleado,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado
16,2025-02-01,70038889,3000000.0,323004010,1.00
17,2025-03-01,70038889,3000000.0,323004010,1.00
18,2025-04-01,70038889,3000000.0,323004010,1.00
59,2025-02-01,70039305,3270000.0,323004033,0.03
60,2025-02-01,70039305,3270000.0,323004034,0.75
61,2025-02-01,70039305,3270000.0,323004036,0.22
62,2025-03-01,70039305,3270000.0,323004033,0.03
63,2025-03-01,70039305,3270000.0,323004034,0.75
64,2025-03-01,70039305,3270000.0,323004036,0.22
65,2025-04-01,70039305,3270000.0,323004033,0.03
66,2025-04-01,70039305,3270000.0,323004034,0.75
67,2025-04-01,70039305,3270000.0,323004036,0.22
92,2025-02-01,1018418655,1044225.0,0,0.00
93,2025-03-01,1018418655,1044225.0,0,0.00
94,2025-04-01,1018418655,1044225.0,0,0.00
127,2025-02-01,79914159,5400000.0,0,0.00
128,2025-03-01,79914159,5400000.0,0,0.00
129,2025-04-01,79914159,5400000.0,0,0.00
142,2025-03-01,1013630697,2760000.0,323004035,1.00
143,2025-04-01,1013630697,2760000.0,323004035,1.00
148,2025-02-01,5016665,4500000.0,323004040,1.00
149,2025-03-01,5016665,4500000.0,323004040,1.00
150,2025-04-01,5016665,4500000.0,323004040,1.00
241,2025-03-01,70002068,7882000.0,323007260,0.50
242,2025-03-01,70002068,7882000.0,323007300,0.05
243,2025-03-01,70002068,7882000.0,323007350,0.45
244,2025-04-01,70002068,7882000.0,323007260,0.50
245,2025-04-01,70002068,7882000.0,323007300,0.05
246,2025-04-01,70002068,7882000.0,323007350,0.45
247,2025-04-01,1047393705,3941000.0,0,0.00
272,2025-01-01,5032456,6000000.0,323007337,1.00
273,2025-02-01,5032456,6000000.0,323007337,1.00
408,2025-01-01,70034730,476000.0,323007320,1.00
452,2025-03-01,94526955,9800000.0,323004050,1.00
453,2025-04-01,94526955,9800000.0,323004050,1.00
714,2025-01-01,70036120,2500000.0,323007337,0.05
715,2025-01-01,70036120,2500000.0,323015065,0.95
722,2025-02-01,70038624,7500000.0,323007337,0.05
723,2025-02-01,70038624,7500000.0,323015065,0.95
724,2025-03-01,70038624,7500000.0,323007337,0.05
725,2025-03-01,70038624,7500000.0,323015065,0.95
726,2025-04-01,70038624,7500000.0,323007337,0.05
727,2025-04-01,70038624,7500000.0,323015065,0.95
728,2025-04-01,70040806,2500000.0,323007337,0.05
729,2025-04-01,70040806,2500000.0,323015070,0.95
733,2025-01-01,70020733,5162500.0,323007337,1.00
734,2025-02-01,70020733,5162500.0,323007337,1.00
797,2025-01-01,70034526,2500000.0,323015050,1.00
821,2025-01-01,70034529,2500000.0,323015045,1.00
857,2025-03-01,70042060,5640000.0,323015045,1.00
858,2025-04-01,70042060,5640000.0,323015045,1.00
895,2025-01-01,70036160,2500000.0,323007260,0.50
896,2025-01-01,70036160,2500000.0,323007300,0.05
897,2025-01-01,70036160,2500000.0,323007350,0.45
907,2025-03-01,25278820,2500000.0,0,0.00

In [22]:
liquidacion_centro_costo_garantizado[liquidacion_centro_costo_garantizado['CodigoEmpleado'] == '32298388']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado]
Index: []

In [23]:
# Agrupar por las columnas específicas y luego seleccionar el último registro de cada grupo
ultimos_registros_liquidacion_centro_costo_garantizado = liquidacion_centro_costo_garantizado.copy().fillna(0).groupby(['CodigoEmpleado', 'Valor Base Cálculo', 'CodigoCentroCosto', 'Porcentaje Aplicado']).apply(lambda x: x.nlargest(1, 'Fecha Proceso')).reset_index(drop=True)
ultimos_registros_liquidacion_centro_costo_garantizado.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_32488\1824660805.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ultimos_registros_liquidacion_centro_costo_garantizado = liquidacion_centro_costo_garantizado.copy().fillna(0).groupby(['CodigoEmpleado', 'Valor Base Cálculo', 'CodigoCentroCosto', 'Porcentaje Aplicado']).apply(lambda x: x.nlargest(1, 'Fecha Proceso')).reset_index(drop=True)

,Fecha Proceso,CodigoEmpleado,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado
0,2025-04-01,1013630697,2760000.0,323004035,1.0
1,2025-04-01,1018418655,1044225.0,0,0.0
2,2025-04-01,1047393705,3941000.0,0,0.0
3,2025-03-01,25278820,2500000.0,0,0.0
4,2025-04-01,5016665,4500000.0,323004040,1.0

In [24]:
# Reiniciar el índice si lo deseas
ultimos_registros_liquidacion_centro_costo_garantizado[ultimos_registros_liquidacion_centro_costo_garantizado['CodigoEmpleado'] == '1032449509']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado]
Index: []

In [25]:
# Asignar nuevos valores usando .loc para evitar SettingWithCopyWarning
ultimos_registros_liquidacion_centro_costo_garantizado.loc[:, 'Consecutivo'] = 0.0
ultimos_registros_liquidacion_centro_costo_garantizado.loc[:, 'TipoCalculo'] = 'F'

ultimos_registros_liquidacion_centro_costo_garantizado[
    (ultimos_registros_liquidacion_centro_costo_garantizado['CodigoEmpleado'] == '1014204375')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Consecutivo, TipoCalculo]
Index: []

In [26]:
liquidacion_centro_costo_caso3 = ultimos_registros_liquidacion_centro_costo_garantizado[
    ultimos_registros_liquidacion_centro_costo_garantizado['Fecha Proceso'] < fecha_liquidacion
]
liquidacion_centro_costo_caso3.head()

,Fecha Proceso,CodigoEmpleado,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Consecutivo,TipoCalculo
3,2025-03-01,25278820,2500000.0,0,0.0,0.0,F
5,2025-02-01,5032456,6000000.0,323007337,1.0,0.0,F
9,2025-02-01,70020733,5162500.0,323007337,1.0,0.0,F
10,2025-01-01,70034526,2500000.0,323015050,1.0,0.0,F
11,2025-01-01,70034529,2500000.0,323015045,1.0,0.0,F

In [27]:
liquidacion_centro_costo_caso3['Fecha Proceso'] = pd.to_datetime(fecha_liquidacion)
liquidacion_centro_costo_caso3['Caso'] = 3

C:\Users\HP\AppData\Local\Temp\ipykernel_32488\1026176324.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liquidacion_centro_costo_caso3['Fecha Proceso'] = pd.to_datetime(fecha_liquidacion)
C:\Users\HP\AppData\Local\Temp\ipykernel_32488\1026176324.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liquidacion_centro_costo_caso3['Caso'] = 3

In [28]:
liquidacion_centro_costo_caso3[liquidacion_centro_costo_caso3['CodigoEmpleado'] == '1111117']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Consecutivo, TipoCalculo, Caso]
Index: []

## Caso 4 - Liquidación Centro de Costo

In [29]:
empleados_inactivos = df_empleados_inactivos[df_empleados_inactivos['FechaRetiro'].notnull()][['CodigoEmpleado', 'FechaRetiro']]
fecha_liquidacion_actual = datetime.strptime(fecha_liquidacion, '%Y-%m-%d')
año_liquidacion_actual = fecha_liquidacion_actual.year
print(año_liquidacion_actual)
empleados_inactivos

2025

    CodigoEmpleado FechaRetiro
13      1026279360  2023-10-01
22         5005463  2023-09-01
41        29116947  2024-03-31
51        53099837  2023-09-01
55         5041772  2023-09-15
98         5036652  2023-09-15
111     1032450706  2023-10-01
120        1111127  2023-08-31
124        8520024  2023-10-01
125        5016583  2023-09-20
134     1032449509  2023-10-01
138       13874027  2023-09-26

In [30]:
empleados_con_fecha_retiro_ano_actual = empleados_inactivos[empleados_inactivos['FechaRetiro'].dt.year == año_liquidacion_actual]
empleados_con_fecha_retiro_ano_actual

Empty DataFrame
Columns: [CodigoEmpleado, FechaRetiro]
Index: []

In [31]:
df_A = resultado_final_liquidacion_centro_costo.rename(columns={
    'Tipo Empleado': 'TipoEmpleado',
    'Área de cálculo': 'AreaCalculo',
    'Salario variable': 'SalarioVariable'
 #   'Valor liquidado': 'Valor Base Cálculo'
})[    [
    'Fecha Proceso', 'CodigoEmpleado', 'CodigoCentroCosto', 'Valor liquidado',
    'Porcentaje Aplicado']]
df_A

,Fecha Proceso,CodigoEmpleado,CodigoCentroCosto,Valor liquidado,Porcentaje Aplicado
0,2025-01-01,5003668,323004010,108300.00,1.0
1,2025-02-01,5003668,323004010,1137150.00,1.0
2,2025-03-01,5003668,323004010,1097902.08,1.0
3,2025-04-01,5003668,323004010,6441424.08,1.0
4,2025-01-01,5016686,323004010,100000.00,1.0
...,...,...,...,...,...
980,2025-01-01,70032756,323004040,400000.00,1.0
981,2025-02-01,70032756,323004040,4000000.00,1.0
982,2025-03-01,70032756,323004040,3801600.00,1.0
983,2025-01-01,9990010,0,0.00,0.0
984,2025-02-01,9990010,0,0.00,0.0

In [32]:
df_A[df_A['CodigoEmpleado'] == '1098612757']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, CodigoCentroCosto, Valor liquidado, Porcentaje Aplicado]
Index: []

In [33]:
df_A[df_A['CodigoEmpleado'] == '1032450706']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, CodigoCentroCosto, Valor liquidado, Porcentaje Aplicado]
Index: []

In [34]:
maestra_resultados_por_empleado_centro_costo.head()

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,...,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable
0,5002711_1,2025-01-01,610,HC,323015040,3.060539e+08,5.425101e+08,VentaCobradaZonaPaisSub,0.56,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,5002711_1,2025-01-01,620,HC,323015045,2.219251e+09,2.066116e+09,VentaCobradaZonaPaisSub,1.07,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,5002711_1,2025-01-01,630,HC,323015050,1.647834e+09,1.288249e+09,VentaCobradaZonaPaisSub,1.28,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,5002711_1,2025-01-01,640,HC,323015055,2.158530e+06,9.511210e+06,VentaCobradaZonaPaisSub,0.23,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,5002711_1,2025-01-01,680,HC,323015055,3.011264e+08,1.797680e+08,VentaCobradaZonaPaisSub,1.68,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [35]:
len(maestra_resultados_por_empleado.copy())

4217

### Caso 4 - Maestro Resultados Por Empleado

In [36]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '1032450706') &
    (maestra_resultados_por_empleado['Fecha'] == '2023-09-01')
]

Empty DataFrame
Columns: [Unnamed: 0.1, Contexto, Fecha, Variable, PorcentajeCumplimiento, Real, Presupuesto, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, SalarioVariable, AreaCalculo, Apellidos, Nombre, FechaIngreso, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes, Unnamed: 0, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, Nombre variable, Nombre consecutivo, _merge, NuevoFactorBK]
Index: []

[0 rows x 32 columns]

In [37]:
maestra_resultados_por_empleado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4217 entries, 0 to 4216
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0.1               4217 non-null   int64
 1   Contexto                   4217 non-null   object
 2   Fecha                      4217 non-null   datetime64[ns]
 3   Variable                   4217 non-null   object
 4   PorcentajeCumplimiento     4217 non-null   float64
 5   Real                       4217 non-null   float64
 6   Presupuesto                4217 non-null   float64
 7   CodigoEmpleado             2919 non-null   object
 8   Porcentaje                 2919 non-null   float64
 9   Consecutivo                2919 non-null   float64
 10  TipoEmpleado               2719 non-null   object
 11  SalarioVariable            2719 non-null   float64
 12  AreaCalculo                2719 non-null   float64
 13  Apellidos                  2719 non-null   object
 14  Nombre                     2719 non-null   object
 15  FechaIngreso               2719 non-null   datetime64[ns]
 16  FactorIncentivo            3593 non-null   float64
 17  FactorMes                  4217 non-null   int64
 18  Liquidado                  2794 non-null   float64
 19  DifMonths                  4217 non-null   int64
 20  NuevoFactor                4217 non-null   int64
 21  ResultadoPresupuesto       4217 non-null   float64
 22  ResultadoRealMes           4217 non-null   float64
 23  PorcentajeCumplimientoMes  4217 non-null   float64
 24  Unnamed: 0                 2296 non-null   float64
 25  RealCOP                    2296 non-null   float64
 26  PresupuestoCOP             2296 non-null   float64
 27  PorcentajeCumplimientoCOP  2296 non-null   float64
 28  Nombre variable            998 non-null    object
 29  Nombre consecutivo         550 non-null    object
 30  _merge                     2296 non-null   object
 31  NuevoFactorBK              2296 non-null   float64
dtypes: datetime64[ns](2), float64(17), int64(4), object(9)
memory usage: 1.0+ MB

In [38]:
df_B = maestra_resultados_por_empleado.copy().rename(columns={
    'Fecha': 'Fecha Proceso' #, 'Liquidado': 'Valor Base Cálculo'
}).merge(df_empleados,
    on=['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Nombre', 'Apellidos', 'FechaIngreso', 'SalarioVariable'],
    how='left',
    indicator=False
)[
        ['Fecha Proceso', 'CodigoEmpleado', 'FechaRetiro', 'AreaCalculo', 'Consecutivo','Variable', 'TipoEmpleado', 'Liquidado']
]
df_B = df_B.dropna(subset=['CodigoEmpleado']).drop_duplicates()
df_B

,Fecha Proceso,CodigoEmpleado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado
0,2025-04-01,1010180302,NaT,NaN,0.0,VentaCobradaBraunPais,NaN,NaN
1,2025-01-01,1013587064,NaT,2.0,0.0,ObjetivosCualitativos,AD2,100000.0
2,2025-01-01,1013587064,NaT,2.0,2.0,KpisSurgical,AD2,250000.0
3,2025-01-01,1013587064,NaT,2.0,3.0,KpisSurgical,AD2,120000.0
4,2025-02-01,1013587064,NaT,2.0,0.0,ObjetivosCualitativos,AD2,200000.0
...,...,...,...,...,...,...,...,...
2914,2025-04-01,9990011,NaT,4.0,1.0,VentaFacturadaPortafolioClusterSub,VC,0.0
2915,2025-04-01,9990011,NaT,4.0,2.0,VentaFacturadaPortafolioClusterSub,VC,0.0
2916,2025-04-01,9990011,NaT,4.0,3.0,VentaFacturadaPortafolioClusterSub,VC,0.0
2917,2025-04-01,9990011,NaT,4.0,4.0,VentaFacturadaPortafolioClusterSub,VC,0.0
2918,2025-04-01,9990011,NaT,4.0,5.0,VentaFacturadaPortafolioClusterSub,VC,0.0

In [39]:
df_B[
    (df_B['CodigoEmpleado'] == '1032450706') & (df_B['Fecha Proceso'] == '2023-09-01')]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado]
Index: []

In [40]:
df_B = df_B.merge(
    df_empleados_centros_costos,
    on=['CodigoEmpleado'],
    how='left',
    indicator=False
)
df_B = df_B.dropna(subset=['CodigoCentroCosto'])
df_B

,Fecha Proceso,CodigoEmpleado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado,CodigoCentroCosto,PorcentajeAsignacion
15,2025-04-01,1013630697,NaT,3.0,0.0,ObjetivosCualitativos,AD3,552000.0,323004035,1.00
16,2025-04-01,1013630697,NaT,3.0,1.0,VentaFacturadaBraunPaisSUB,AD3,1563264.0,323004035,1.00
17,2025-04-01,1013630697,NaT,3.0,1.0,EBITCOGSPaisSUB,AD3,5520000.0,323004035,1.00
25,2025-04-01,1020784302,NaT,NaN,0.0,VentaCobradaBraunPais,NaN,NaN,323007300,0.05
26,2025-04-01,1020784302,NaT,NaN,0.0,VentaCobradaBraunPais,NaN,NaN,323007350,0.45
...,...,...,...,...,...,...,...,...,...,...
5345,2025-04-01,94526955,NaT,9.0,0.0,ObjetivosCualitativos,MK1,1960000.0,323004050,1.00
5346,2025-04-01,94526955,NaT,9.0,1.0,VentaFacturadaBraunPaisSUB,MK1,2775360.0,323004050,1.00
5347,2025-04-01,94526955,NaT,9.0,2.0,VentaFacturadaBraunPaisSUB,MK1,9800000.0,323004050,1.00
5348,2025-04-01,94526955,NaT,9.0,1.0,EBITCOGSPaisSUB,MK1,9800000.0,323004050,1.00
5349,2025-04-01,94526955,NaT,9.0,2.0,EBITCOGSPaisSUB,MK1,9800000.0,323004050,1.00

In [41]:
df_B[(df_B['CodigoEmpleado'] == '1032450706') & (df_B['Fecha Proceso'] == '2023-09-01')]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado, CodigoCentroCosto, PorcentajeAsignacion]
Index: []

In [42]:
df_parrillas_tipos_calculos

,TipoEmpleado,AreaCalculo,CodigoRubro,NombreRubro,TipoCalculo
0,AD,1,2,EBITCOGSPaisSUB,F
1,AD,1,3,ObjetivosCualitativos,F
2,AD,1,1,VentaFacturadaBraunPaisSUB,F
3,AD,2,2,EBITCOGSPaisSUB,F
4,AD,2,3,ObjetivosCualitativos,F
...,...,...,...,...,...
248,VE,13,4,ObjetivosCualitativos,F
249,VE,13,1,VentaCobradaBraunPais,F
250,VE,13,1,VentaCobradaPortafolioPais,F
251,VE,13,3,VentaCobradaPortafolioZonaCluster,F
252,VE,13,2,VentaFacturadaPortafolioZonaClusterSub,V

In [43]:
df_B = df_B.merge( 
    right=df_parrillas_tipos_calculos.rename(columns={'NombreRubro': 'Variable'}), 
    on=['TipoEmpleado', 'AreaCalculo', 'Variable'],
    how='left' 
) 

df_B[[
    'Fecha Proceso', 'CodigoEmpleado', 'FechaRetiro', 'Variable', 'AreaCalculo', 'PorcentajeAsignacion', 'TipoEmpleado', 
    'CodigoRubro', 'TipoCalculo', 'CodigoCentroCosto', 'Liquidado' 
]]

,Fecha Proceso,CodigoEmpleado,FechaRetiro,Variable,AreaCalculo,PorcentajeAsignacion,TipoEmpleado,CodigoRubro,TipoCalculo,CodigoCentroCosto,Liquidado
0,2025-04-01,1013630697,NaT,ObjetivosCualitativos,3.0,1.00,AD3,3,F,323004035,552000.0
1,2025-04-01,1013630697,NaT,VentaFacturadaBraunPaisSUB,3.0,1.00,AD3,1,F,323004035,1563264.0
2,2025-04-01,1013630697,NaT,EBITCOGSPaisSUB,3.0,1.00,AD3,2,F,323004035,5520000.0
3,2025-04-01,1020784302,NaT,VentaCobradaBraunPais,NaN,0.05,NaN,NaN,NaN,323007300,NaN
4,2025-04-01,1020784302,NaT,VentaCobradaBraunPais,NaN,0.45,NaN,NaN,NaN,323007350,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5071,2025-04-01,94526955,NaT,ObjetivosCualitativos,9.0,1.00,MK1,3,F,323004050,1960000.0
5072,2025-04-01,94526955,NaT,VentaFacturadaBraunPaisSUB,9.0,1.00,MK1,1,F,323004050,2775360.0
5073,2025-04-01,94526955,NaT,VentaFacturadaBraunPaisSUB,9.0,1.00,MK1,1,F,323004050,9800000.0
5074,2025-04-01,94526955,NaT,EBITCOGSPaisSUB,9.0,1.00,MK1,2,F,323004050,9800000.0
5075,2025-04-01,94526955,NaT,EBITCOGSPaisSUB,9.0,1.00,MK1,2,F,323004050,9800000.0

In [44]:
df_B[df_B['CodigoEmpleado'] == '5002899']

,Fecha Proceso,CodigoEmpleado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado,CodigoCentroCosto,PorcentajeAsignacion,CodigoRubro,TipoCalculo
690,2025-04-01,5002899,NaT,NaN,0.0,VentaCobradaBraunPais,NaN,NaN,323007332,0.1,NaN,NaN
691,2025-04-01,5002899,NaT,NaN,0.0,VentaCobradaBraunPais,NaN,NaN,323007333,0.1,NaN,NaN
692,2025-04-01,5002899,NaT,NaN,0.0,VentaCobradaBraunPais,NaN,NaN,323010165,0.8,NaN,NaN

### Caso 4 - Maestro Resultados Por Empleado Centro de Costo

In [45]:
maestra_resultados_por_empleado_centro_costo[
    (maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] == '1032450706') &
    (maestra_resultados_por_empleado_centro_costo['Fecha'] == '2023-09-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, GrupoProducto, Division, CodigoCentroCosto, Real, Presupuesto, Variable, PorcentajeCumplimiento, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, SalarioVariable]
Index: []

[0 rows x 23 columns]

In [46]:
maestra_resultados_por_empleado_centro_costo[maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] == '5002711']

,Contexto,Fecha,GrupoProducto,Division,CodigoCentroCosto,Real,Presupuesto,Variable,PorcentajeCumplimiento,RealCOP,...,Porcentaje,Consecutivo,Nombre variable,Nombre consecutivo,TipoEmpleado,AreaCalculo,Apellidos,Nombre,FechaIngreso,SalarioVariable
13693,5002711_1,2025-01-01,610,HC,323007336,19033.299729,78396.854844,VentaFacturadaZonaPaisSub,0.24,8.564414e+07,...,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,3000000.0
13694,5002711_1,2025-01-01,610,HC,323010170,19033.299729,78396.854844,VentaFacturadaZonaPaisSub,0.24,8.564414e+07,...,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,3000000.0
13695,5002711_1,2025-01-01,610,HC,323015070,19033.299729,78396.854844,VentaFacturadaZonaPaisSub,0.24,8.564414e+07,...,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,3000000.0
13696,5002711_1,2025-01-01,620,HC,323007336,163101.210190,365138.663775,VentaFacturadaZonaPaisSub,0.45,7.339065e+08,...,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,3000000.0
13697,5002711_1,2025-01-01,620,HC,323010170,163101.210190,365138.663775,VentaFacturadaZonaPaisSub,0.45,7.339065e+08,...,0.26,1.0,VentaFacturadaZonaPaisSub,Hospital Care,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14072,5002711_3,2025-06-01,A35,BA,323010170,12245.255117,23184.131374,VentaFacturadaZonaPaisSub,0.53,5.509997e+07,...,0.04,3.0,VentaFacturadaZonaPaisSub,Avitum,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,NaN
14073,5002711_3,2025-06-01,A35,BA,323015070,12245.255117,23184.131374,VentaFacturadaZonaPaisSub,0.53,5.509997e+07,...,0.04,3.0,VentaFacturadaZonaPaisSub,Avitum,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,NaN
14074,5002711_3,2025-06-01,A45,BA,323007336,196298.981710,86272.623591,VentaFacturadaZonaPaisSub,2.28,8.832865e+08,...,0.04,3.0,VentaFacturadaZonaPaisSub,Avitum,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,NaN
14075,5002711_3,2025-06-01,A45,BA,323010170,196298.981710,86272.623591,VentaFacturadaZonaPaisSub,2.28,8.832865e+08,...,0.04,3.0,VentaFacturadaZonaPaisSub,Avitum,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,NaN
14076,5002711_3,2025-06-01,A45,BA,323015070,196298.981710,86272.623591,VentaFacturadaZonaPaisSub,2.28,8.832865e+08,...,0.04,3.0,VentaFacturadaZonaPaisSub,Avitum,GC,3.0,AVILA MORALES,JEYMY,2008-10-27,NaN

In [47]:
# df_B = maestra_resultados_por_empleado_centro_costo.copy().rename(columns={
#     'Fecha': 'Fecha Proceso' #, 'Liquidado': 'Valor Base Cálculo'
# }).merge(df_empleados,
#     on=['CodigoEmpleado', 'TipoEmpleado', 'AreaCalculo', 'Nombre', 'Apellidos', 'FechaIngreso', 'SalarioVariable'],
#     how='left',
#     indicator=False
# )[
#         ['Fecha Proceso', 'CodigoEmpleado', 'CodigoCentroCosto', 'FechaRetiro']
# ]
# df_B = df_B.dropna(subset=['CodigoEmpleado']).drop_duplicates()
# df_B

In [48]:
df_B[df_B['CodigoEmpleado'] == '5002711']

,Fecha Proceso,CodigoEmpleado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado,CodigoCentroCosto,PorcentajeAsignacion,CodigoRubro,TipoCalculo
198,2025-01-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,300000.0,323007336,0.05,5,F
199,2025-01-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,300000.0,323010170,0.25,5,F
200,2025-01-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,300000.0,323015070,0.70,5,F
201,2025-01-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,0.0,323007336,0.05,1,F
202,2025-01-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,0.0,323010170,0.25,1,F
203,2025-01-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,0.0,323015070,0.70,1,F
204,2025-02-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,630000.0,323007336,0.05,5,F
205,2025-02-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,630000.0,323010170,0.25,5,F
206,2025-02-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,630000.0,323015070,0.70,5,F
207,2025-02-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,0.0,323007336,0.05,1,F
208,2025-02-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,0.0,323010170,0.25,1,F
209,2025-02-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,0.0,323015070,0.70,1,F
210,2025-03-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,960000.0,323007336,0.05,5,F
211,2025-03-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,960000.0,323010170,0.25,5,F
212,2025-03-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,960000.0,323015070,0.70,5,F
213,2025-03-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,520320.0,323007336,0.05,1,F
214,2025-03-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,520320.0,323010170,0.25,1,F
215,2025-03-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,520320.0,323015070,0.70,1,F
216,2025-03-01,5002711,NaT,3.0,1.0,VentaFacturadaZonaPaisSub,GC,0.0,323007336,0.05,2,V
217,2025-03-01,5002711,NaT,3.0,1.0,VentaFacturadaZonaPaisSub,GC,0.0,323010170,0.25,2,V
218,2025-03-01,5002711,NaT,3.0,1.0,VentaFacturadaZonaPaisSub,GC,0.0,323015070,0.70,2,V
219,2025-03-01,5002711,NaT,3.0,2.0,VentaFacturadaZonaPaisSub,GC,760320.0,323007336,0.05,2,V
220,2025-03-01,5002711,NaT,3.0,2.0,VentaFacturadaZonaPaisSub,GC,760320.0,323010170,0.25,2,V
221,2025-03-01,5002711,NaT,3.0,2.0,VentaFacturadaZonaPaisSub,GC,760320.0,323015070,0.70,2,V
222,2025-03-01,5002711,NaT,3.0,3.0,VentaFacturadaZonaPaisSub,GC,960000.0,323007336,0.05,2,V
223,2025-03-01,5002711,NaT,3.0,3.0,VentaFacturadaZonaPaisSub,GC,960000.0,323010170,0.25,2,V
224,2025-03-01,5002711,NaT,3.0,3.0,VentaFacturadaZonaPaisSub,GC,960000.0,323015070,0.70,2,V
225,2025-03-01,5002711,NaT,3.0,0.0,EBITCOGSPais,GC,0.0,323007336,0.05,4,F
226,2025-03-01,5002711,NaT,3.0,0.0,EBITCOGSPais,GC,0.0,323010170,0.25,4,F
227,2025-03-01,5002711,NaT,3.0,0.0,EBITCOGSPais,GC,0.0,323015070,0.70,4,F
228,2025-04-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,1290000.0,323007336,0.05,5,F
229,2025-04-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,1290000.0,323010170,0.25,5,F
230,2025-04-01,5002711,NaT,3.0,0.0,ObjetivosCualitativos,GC,1290000.0,323015070,0.70,5,F
231,2025-04-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,913320.0,323007336,0.05,1,F
232,2025-04-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,913320.0,323010170,0.25,1,F
233,2025-04-01,5002711,NaT,3.0,0.0,VentaFacturadaBraunPais,GC,913320.0,323015070,0.70,1,F
234,2025-04-01,5002711,NaT,3.0,1.0,VentaFacturadaZonaPaisSub,GC,2515500.0,323007336,0.05,2,V
235,2025-04-01,5002711,NaT,3.0,1.0,VentaFacturadaZonaPaisSub,GC,2515500.0,323010170,0.25,2,V
236,2025-04-01,5002711,NaT,3.0,1.0,VentaFacturadaZonaPaisSub,GC,2515500.0,323015070,0.70,2,V
237,2025-04-01,5002711,NaT,3.0,2.0,VentaFacturadaZonaPaisSub,GC,2257500.0,323007336,0.05,2,V
238,2025-04-01,5002711,NaT,3.0,2.0,VentaFacturadaZonaPaisSub,GC,2257500.0,323010170,0.25,2,V
239,2025-04-01,5002711,NaT,3.0,2.0,VentaFacturadaZonaPaisSub,GC,2257500.0,323015070,0.70,2,V
240,2025-04-01,5002711,NaT,3.0,3.0,VentaFacturadaZonaPaisSub,GC,0.0,323007336,0.05,2,V
241,2025-04-01,5002711,NaT,3.0,3.0,VentaFacturadaZonaPaisSub,GC,0.0,323010170,0.25,2,V
242,2025-04-01,5002711,NaT,3.0,3.0,VentaFacturadaZonaPaisSub,GC,0.0,323015070,0.70,2,V
243,2025-04-01,5002711,NaT,3.0,0.0,EBITCOGSPais,GC,9675000.0,323007336,0.05,4,F
244,2025-04-01,5002711,NaT,3.0,0.0,EBITCOGSPais,GC,9675000.0,323010170,0.25,4,F
245,2025-04-01,5002711,NaT,3.0,0.0,EBITCOGSPais,GC,9675000.0,323015070,0.70,4,F

In [49]:
df_empleados_centros_costos[df_empleados_centros_costos['CodigoEmpleado'] == '5002711']

  CodigoEmpleado CodigoCentroCosto  PorcentajeAsignacion
6        5002711         323007336                  0.05
7        5002711         323010170                  0.25
8        5002711         323015070                  0.70

In [50]:
# df_B = df_B.merge(
#     df_empleados_centros_costos,
#     on=['CodigoEmpleado', 'CodigoCentroCosto'],
#     how='left',
#     indicator=False
# )
# df_B = df_B.dropna(subset=['CodigoCentroCosto'])
# df_B

In [51]:
df_B[
    (df_B['CodigoEmpleado'] == '1032450706') & 
    (df_B['Fecha Proceso'] == '2023-09-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado, CodigoCentroCosto, PorcentajeAsignacion, CodigoRubro, TipoCalculo]
Index: []

In [52]:
df_B[
    (df_B['CodigoEmpleado'] == '1032450706') & 
    (df_B['Fecha Proceso'] == '2023-09-01') &
    (df_B['TipoCalculo'] == 'F')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado, CodigoCentroCosto, PorcentajeAsignacion, CodigoRubro, TipoCalculo]
Index: []

In [53]:
3780000+6300000

10080000

In [54]:
df_B[
    (df_B['CodigoEmpleado'] == '1032450706') & 
    (df_B['Fecha Proceso'] == '2023-09-01') &
    (df_B['TipoCalculo'] == 'V')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado, CodigoCentroCosto, PorcentajeAsignacion, CodigoRubro, TipoCalculo]
Index: []

In [55]:
6048000+2340000+198000

8586000

In [56]:
df_B[
    (df_B['CodigoEmpleado'] == '1032450706') & 
    (df_B['Fecha Proceso'] == '2023-09-01') &
    (df_B['TipoCalculo'] == 'F')
]['Liquidado'].sum()

0.0

In [57]:
df_B[
    (df_B['CodigoEmpleado'] == '1032450706') & 
    (df_B['Fecha Proceso'] == '2023-09-01') &
    (df_B['TipoCalculo'] == 'V')
]['Liquidado'].sum()

0.0

In [58]:
# Haciendo un merge entre df_A y df_B con un indicador
merged_df = df_A.merge(df_B, on=[
    'CodigoEmpleado', 'Fecha Proceso', 'CodigoCentroCosto'], how='right', indicator=True
)
merged_df

,Fecha Proceso,CodigoEmpleado,CodigoCentroCosto,Valor liquidado,Porcentaje Aplicado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado,PorcentajeAsignacion,CodigoRubro,TipoCalculo,_merge
0,2025-04-01,1013630697,323004035,1380000.0,1.0,NaT,3.0,0.0,ObjetivosCualitativos,AD3,552000.0,1.00,3,F,both
1,2025-04-01,1013630697,323004035,1380000.0,1.0,NaT,3.0,1.0,VentaFacturadaBraunPaisSUB,AD3,1563264.0,1.00,1,F,both
2,2025-04-01,1013630697,323004035,1380000.0,1.0,NaT,3.0,1.0,EBITCOGSPaisSUB,AD3,5520000.0,1.00,2,F,both
3,2025-04-01,1020784302,323007300,NaN,NaN,NaT,NaN,0.0,VentaCobradaBraunPais,NaN,NaN,0.05,NaN,NaN,right_only
4,2025-04-01,1020784302,323007350,NaN,NaN,NaT,NaN,0.0,VentaCobradaBraunPais,NaN,NaN,0.45,NaN,NaN,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5071,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,0.0,ObjetivosCualitativos,MK1,1960000.0,1.00,3,F,both
5072,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,1.0,VentaFacturadaBraunPaisSUB,MK1,2775360.0,1.00,1,F,both
5073,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,2.0,VentaFacturadaBraunPaisSUB,MK1,9800000.0,1.00,1,F,both
5074,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,1.0,EBITCOGSPaisSUB,MK1,9800000.0,1.00,2,F,both
5075,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,2.0,EBITCOGSPaisSUB,MK1,9800000.0,1.00,2,F,both

In [59]:
df_A[df_A['CodigoEmpleado'] == '1032450706']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, CodigoCentroCosto, Valor liquidado, Porcentaje Aplicado]
Index: []

In [60]:
df_B[
        (df_B['CodigoEmpleado'] == '1032450706') &
        (df_B['Fecha Proceso'] == '2023-09-01')
    ]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado, CodigoCentroCosto, PorcentajeAsignacion, CodigoRubro, TipoCalculo]
Index: []

In [61]:
merged_df[
    (merged_df['CodigoEmpleado']=='1032450706') &
    (merged_df['Fecha Proceso']=='2023-09-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, CodigoCentroCosto, Valor liquidado, Porcentaje Aplicado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado, PorcentajeAsignacion, CodigoRubro, TipoCalculo, _merge]
Index: []

In [62]:
# Filtrando aquellos registros que están en ambos dataframes (es decir, df_A, df_B)

# Registros que están dentro de resultado final liquidación por centro de costo y además aparecen en la maestra de resultados por empleado.

# liquidacion_centro_costo_caso4_both = merged_df[merged_df['_merge'] == 'both']
# resultado_final_liquidacion_centro_costo
# empleados_centro_costo_con_valor_liquidado

empleados_centro_costo_con_valor_liquidado = merged_df.dropna(subset=['Valor liquidado'])
empleados_centro_costo_con_valor_liquidado

,Fecha Proceso,CodigoEmpleado,CodigoCentroCosto,Valor liquidado,Porcentaje Aplicado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado,PorcentajeAsignacion,CodigoRubro,TipoCalculo,_merge
0,2025-04-01,1013630697,323004035,1380000.0,1.0,NaT,3.0,0.0,ObjetivosCualitativos,AD3,552000.0,1.0,3,F,both
1,2025-04-01,1013630697,323004035,1380000.0,1.0,NaT,3.0,1.0,VentaFacturadaBraunPaisSUB,AD3,1563264.0,1.0,1,F,both
2,2025-04-01,1013630697,323004035,1380000.0,1.0,NaT,3.0,1.0,EBITCOGSPaisSUB,AD3,5520000.0,1.0,2,F,both
60,2025-01-01,5002697,323015045,1068720.0,1.0,NaT,5.0,0.0,ObjetivosCualitativos,VE,367920.0,1.0,4,F,both
61,2025-01-01,5002697,323015045,1068720.0,1.0,NaT,5.0,0.0,VentaCobradaBraunPais,VE,700800.0,1.0,1,F,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5071,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,0.0,ObjetivosCualitativos,MK1,1960000.0,1.0,3,F,both
5072,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,1.0,VentaFacturadaBraunPaisSUB,MK1,2775360.0,1.0,1,F,both
5073,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,2.0,VentaFacturadaBraunPaisSUB,MK1,9800000.0,1.0,1,F,both
5074,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,1.0,EBITCOGSPaisSUB,MK1,9800000.0,1.0,2,F,both
5075,2025-04-01,94526955,323004050,4900000.0,1.0,NaT,9.0,2.0,EBITCOGSPaisSUB,MK1,9800000.0,1.0,2,F,both

In [63]:
empleados_centro_costo_con_valor_liquidado[
    (empleados_centro_costo_con_valor_liquidado['CodigoEmpleado'] == '1032450706') &
    (empleados_centro_costo_con_valor_liquidado['Fecha Proceso'] == '2023-09-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, CodigoCentroCosto, Valor liquidado, Porcentaje Aplicado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado, PorcentajeAsignacion, CodigoRubro, TipoCalculo, _merge]
Index: []

In [64]:
# # Agrupar por las columnas específicas y luego seleccionar el último registro de cada grupo
# ultimos_registros_empleados_centro_costo_con_valor_liquidado = empleados_centro_costo_con_valor_liquidado.groupby(['CodigoEmpleado', 'CodigoCentroCosto']).apply(lambda x: x.nlargest(1, 'Fecha Proceso'))

# # Reiniciar el índice si lo deseas
# ultimos_registros_empleados_centro_costo_con_valor_liquidado = ultimos_registros_empleados_centro_costo_con_valor_liquidado.reset_index(drop=True)
# ultimos_registros_empleados_centro_costo_con_valor_liquidado = ultimos_registros_empleados_centro_costo_con_valor_liquidado.drop(columns=['_merge'])

ultimos_registros_empleados_centro_costo_con_valor_liquidado = empleados_centro_costo_con_valor_liquidado.groupby(['CodigoEmpleado', 'TipoCalculo', 'CodigoCentroCosto', 'Consecutivo','Variable']).apply(
    lambda x: x.nlargest(1, 'Fecha Proceso')
).reset_index(drop=True).drop(columns=['_merge'])
ultimos_registros_empleados_centro_costo_con_valor_liquidado

C:\Users\HP\AppData\Local\Temp\ipykernel_32488\4201685603.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ultimos_registros_empleados_centro_costo_con_valor_liquidado = empleados_centro_costo_con_valor_liquidado.groupby(['CodigoEmpleado', 'TipoCalculo', 'CodigoCentroCosto', 'Consecutivo','Variable']).apply(

,Fecha Proceso,CodigoEmpleado,CodigoCentroCosto,Valor liquidado,Porcentaje Aplicado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado,PorcentajeAsignacion,CodigoRubro,TipoCalculo
0,2025-04-01,1013630697,323004035,1.380000e+06,1.0,NaT,3.0,0.0,ObjetivosCualitativos,AD3,552000.00,1.0,3,F
1,2025-04-01,1013630697,323004035,1.380000e+06,1.0,NaT,3.0,1.0,EBITCOGSPaisSUB,AD3,5520000.00,1.0,2,F
2,2025-04-01,1013630697,323004035,1.380000e+06,1.0,NaT,3.0,1.0,VentaFacturadaBraunPaisSUB,AD3,1563264.00,1.0,1,F
3,2025-04-01,5002697,323015045,1.194247e+07,1.0,NaT,5.0,0.0,ObjetivosCualitativos,VE,1098495.00,1.0,4,F
4,2025-04-01,5002697,323015045,1.194247e+07,1.0,NaT,5.0,0.0,VentaCobradaBraunPais,VE,3203943.75,1.0,1,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1497,2025-04-01,94526955,323004050,4.900000e+06,1.0,NaT,9.0,0.0,ObjetivosCualitativos,MK1,1960000.00,1.0,3,F
1498,2025-04-01,94526955,323004050,4.900000e+06,1.0,NaT,9.0,1.0,EBITCOGSPaisSUB,MK1,9800000.00,1.0,2,F
1499,2025-04-01,94526955,323004050,4.900000e+06,1.0,NaT,9.0,1.0,VentaFacturadaBraunPaisSUB,MK1,2775360.00,1.0,1,F
1500,2025-04-01,94526955,323004050,4.900000e+06,1.0,NaT,9.0,2.0,EBITCOGSPaisSUB,MK1,9800000.00,1.0,2,F
1501,2025-04-01,94526955,323004050,4.900000e+06,1.0,NaT,9.0,2.0,VentaFacturadaBraunPaisSUB,MK1,9800000.00,1.0,1,F

In [65]:
ultimos_registros_empleados_centro_costo_con_valor_liquidado[
    (ultimos_registros_empleados_centro_costo_con_valor_liquidado['CodigoEmpleado'] == '5002899') 
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, CodigoCentroCosto, Valor liquidado, Porcentaje Aplicado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado, PorcentajeAsignacion, CodigoRubro, TipoCalculo]
Index: []

In [66]:
481140.0+2430000.0+5852925.0+3137167.8

11901232.8

In [67]:
1786860.0+7445250.0+3192523.2

12424633.2

In [68]:
# Registros que fueron excluídos dentro de resultado final liquidación por centro de costo, pero sí aparecen en la maestra de resultados por empleado.

# Filtrando aquellos registros que solo están en el lado izquierdo (es decir, df_A)
# empleados_exluidos_centro_costo_con_valor_liquidado = merged_df[merged_df['_merge'] == 'right_only']
# empleados_exluidos_centro_costo_con_valor_liquidado = empleados_exluidos_centro_costo_con_valor_liquidado.drop(columns=['Valor liquidado', 'Fecha Proceso', '_merge', 'Porcentaje Aplicado'])

empleados_exluidos_centro_costo_con_valor_liquidado =  merged_df[merged_df['Valor liquidado'].isna()].drop(columns=[
    'Valor liquidado', 'Porcentaje Aplicado', 'Fecha Proceso', '_merge', 'FechaRetiro', 'CodigoRubro', 'TipoCalculo', 'Liquidado'
]).drop_duplicates()
empleados_exluidos_centro_costo_con_valor_liquidado

,CodigoEmpleado,CodigoCentroCosto,AreaCalculo,Consecutivo,Variable,TipoEmpleado,PorcentajeAsignacion
3,1020784302,323007300,NaN,0.0,VentaCobradaBraunPais,NaN,0.05
4,1020784302,323007350,NaN,0.0,VentaCobradaBraunPais,NaN,0.45
5,1020784302,323007260,NaN,0.0,VentaCobradaBraunPais,NaN,0.50
6,1020815612,323015035,NaN,1.0,VentaFacturadaUnidadNegocioSub,NaN,0.50
7,1020815612,323007320,NaN,1.0,VentaFacturadaUnidadNegocioSub,NaN,0.50
...,...,...,...,...,...,...,...
5066,94460154,323007337,NaN,1.0,VentaFacturadaUnidadNegocioSub,NaN,1.00
5067,94460154,323007337,NaN,2.0,VentaFacturadaUnidadNegocioSub,NaN,1.00
5068,94460154,323007337,NaN,3.0,VentaFacturadaUnidadNegocioSub,NaN,1.00
5069,94460154,323007337,NaN,0.0,VentaFacturadaBraunPais,NaN,1.00
5070,94460154,323007337,NaN,0.0,EBITCOGSPais,NaN,1.00

In [69]:
empleados_exluidos_centro_costo_con_valor_liquidado[
    empleados_exluidos_centro_costo_con_valor_liquidado['CodigoEmpleado'] == '8520024'
]

Empty DataFrame
Columns: [CodigoEmpleado, CodigoCentroCosto, AreaCalculo, Consecutivo, Variable, TipoEmpleado, PorcentajeAsignacion]
Index: []

In [70]:
empleados_exluidos_centro_costo_con_valor_liquidado[
    empleados_exluidos_centro_costo_con_valor_liquidado['CodigoEmpleado'] == '1032450706'
]

Empty DataFrame
Columns: [CodigoEmpleado, CodigoCentroCosto, AreaCalculo, Consecutivo, Variable, TipoEmpleado, PorcentajeAsignacion]
Index: []

In [71]:
resultado_ultima_liquidacion_empleados_retirados_o_inactivos = ultimos_registros_empleados_centro_costo_con_valor_liquidado.merge(
    empleados_exluidos_centro_costo_con_valor_liquidado.drop(
        columns=['AreaCalculo', 'TipoEmpleado', 'Variable' , 'Consecutivo']
    ).copy(),
    how='right',
    on=['CodigoEmpleado', 'CodigoCentroCosto', 'PorcentajeAsignacion']
).drop_duplicates()
resultado_ultima_liquidacion_empleados_retirados_o_inactivos

,Fecha Proceso,CodigoEmpleado,CodigoCentroCosto,Valor liquidado,Porcentaje Aplicado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado,PorcentajeAsignacion,CodigoRubro,TipoCalculo
0,NaT,1020784302,323007300,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.05,NaN,NaN
1,NaT,1020784302,323007350,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.45,NaN,NaN
2,NaT,1020784302,323007260,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.50,NaN,NaN
3,NaT,1020815612,323015035,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.50,NaN,NaN
4,NaT,1020815612,323007320,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.50,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,2025-03-01,70029961,323007270,10998624.0,1.0,NaT,3.0,0.0,VentaFacturadaBraunPais,GU,1014624.0,1.00,1,F
668,2025-03-01,70029961,323007270,10998624.0,1.0,NaT,3.0,10.0,RentabilidadUnidadNegocioCM2COGSSUB,GU,6240000.0,1.00,4,F
669,2025-03-01,70029961,323007270,10998624.0,1.0,NaT,3.0,1.0,VentaFacturadaUnidadNegocioSub,GU,2808000.0,1.00,2,V
680,NaT,80895530,323007320,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN
684,NaT,94460154,323007337,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN

In [72]:
resultado_ultima_liquidacion_empleados_retirados_o_inactivos[
    resultado_ultima_liquidacion_empleados_retirados_o_inactivos['CodigoEmpleado'] == '5016583'
]

,Fecha Proceso,CodigoEmpleado,CodigoCentroCosto,Valor liquidado,Porcentaje Aplicado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado,PorcentajeAsignacion,CodigoRubro,TipoCalculo
405,NaT,5016583,323007337,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.05,NaN,NaN
406,NaT,5016583,323015075,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.95,NaN,NaN

In [73]:
resultado_ultima_liquidacion_empleados_retirados_o_inactivos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 216 entries, 0 to 684
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Fecha Proceso         143 non-null    datetime64[ns]
 1   CodigoEmpleado        216 non-null    object
 2   CodigoCentroCosto     216 non-null    object
 3   Valor liquidado       143 non-null    float64
 4   Porcentaje Aplicado   143 non-null    float64
 5   FechaRetiro           0 non-null      datetime64[ns]
 6   AreaCalculo           143 non-null    float64
 7   Consecutivo           143 non-null    float64
 8   Variable              143 non-null    object
 9   TipoEmpleado          143 non-null    object
 10  Liquidado             143 non-null    float64
 11  PorcentajeAsignacion  216 non-null    float64
 12  CodigoRubro           143 non-null    object
 13  TipoCalculo           143 non-null    object
dtypes: datetime64[ns](2), float64(6), object(6)
memory usage: 25.3+ KB

In [74]:
empleados_con_fecha_retiro_ano_actual

Empty DataFrame
Columns: [CodigoEmpleado, FechaRetiro]
Index: []

In [75]:
resultado_ultima_liquidacion_empleados_retirados_o_inactivos = resultado_ultima_liquidacion_empleados_retirados_o_inactivos.rename(
        columns={'Fecha Proceso': 'Fecha Proceso Última Liquidacion'}
    ).merge(
    empleados_con_fecha_retiro_ano_actual,
    how='outer',
    on=['CodigoEmpleado', 'FechaRetiro']
).drop_duplicates()
resultado_ultima_liquidacion_empleados_retirados_o_inactivos['Fecha Proceso'] = pd.to_datetime(fecha_liquidacion)
resultado_ultima_liquidacion_empleados_retirados_o_inactivos

,Fecha Proceso Última Liquidacion,CodigoEmpleado,CodigoCentroCosto,Valor liquidado,Porcentaje Aplicado,FechaRetiro,AreaCalculo,Consecutivo,Variable,TipoEmpleado,Liquidado,PorcentajeAsignacion,CodigoRubro,TipoCalculo,Fecha Proceso
0,NaT,1020784302,323007300,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.05,NaN,NaN,2025-04-01
1,NaT,1020784302,323007350,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.45,NaN,NaN,2025-04-01
2,NaT,1020784302,323007260,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.50,NaN,NaN,2025-04-01
3,NaT,1020815612,323015035,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.50,NaN,NaN,2025-04-01
4,NaT,1020815612,323007320,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.50,NaN,NaN,2025-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2025-03-01,70029961,323007270,10998624.0,1.0,NaT,3.0,0.0,VentaFacturadaBraunPais,GU,1014624.0,1.00,1,F,2025-04-01
212,2025-03-01,70029961,323007270,10998624.0,1.0,NaT,3.0,10.0,RentabilidadUnidadNegocioCM2COGSSUB,GU,6240000.0,1.00,4,F,2025-04-01
213,2025-03-01,70029961,323007270,10998624.0,1.0,NaT,3.0,1.0,VentaFacturadaUnidadNegocioSub,GU,2808000.0,1.00,2,V,2025-04-01
214,NaT,80895530,323007320,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2025-04-01
215,NaT,94460154,323007337,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2025-04-01

In [76]:
resultado_ultima_liquidacion_empleados_retirados_o_inactivos[
    resultado_ultima_liquidacion_empleados_retirados_o_inactivos['CodigoEmpleado'] == '8520024'
]

Empty DataFrame
Columns: [Fecha Proceso Última Liquidacion, CodigoEmpleado, CodigoCentroCosto, Valor liquidado, Porcentaje Aplicado, FechaRetiro, AreaCalculo, Consecutivo, Variable, TipoEmpleado, Liquidado, PorcentajeAsignacion, CodigoRubro, TipoCalculo, Fecha Proceso]
Index: []

In [77]:
    len(resultado_ultima_liquidacion_empleados_retirados_o_inactivos)

216

In [78]:
resultado_ultima_liquidacion_empleados_retirados_o_inactivos.to_excel('liquidacion_centro_costo_caso4_detallado.xlsx')

In [79]:
# Eliminando la columna del indicador para limpiar el resultado
liquidacion_centro_costo_caso4 = resultado_ultima_liquidacion_empleados_retirados_o_inactivos.copy().rename(columns={'Liquidado': 'Valor Base Cálculo'})[
    [
    'Fecha Proceso', 'CodigoEmpleado', 'CodigoCentroCosto', 'Valor Base Cálculo',
    'Porcentaje Aplicado', 'TipoCalculo', 'Variable', 'Consecutivo', 'Fecha Proceso Última Liquidacion']
]
liquidacion_centro_costo_caso4['Fecha Proceso'] = liquidacion_centro_costo_caso4['Fecha Proceso Última Liquidacion']
liquidacion_centro_costo_caso4['Caso'] = 4
liquidacion_centro_costo_caso4.drop(columns=['Fecha Proceso Última Liquidacion', 'Variable'], inplace=True)
# liquidacion_centro_costo_caso4.loc[:, 'Consecutivo'] = 0.0
liquidacion_centro_costo_caso4.drop_duplicates(inplace=True)
liquidacion_centro_costo_caso4

,Fecha Proceso,CodigoEmpleado,CodigoCentroCosto,Valor Base Cálculo,Porcentaje Aplicado,TipoCalculo,Consecutivo,Caso
0,NaT,1020784302,323007300,NaN,NaN,NaN,NaN,4
1,NaT,1020784302,323007350,NaN,NaN,NaN,NaN,4
2,NaT,1020784302,323007260,NaN,NaN,NaN,NaN,4
3,NaT,1020815612,323015035,NaN,NaN,NaN,NaN,4
4,NaT,1020815612,323007320,NaN,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...
211,2025-03-01,70029961,323007270,1014624.0,1.0,F,0.0,4
212,2025-03-01,70029961,323007270,6240000.0,1.0,F,10.0,4
213,2025-03-01,70029961,323007270,2808000.0,1.0,V,1.0,4
214,NaT,80895530,323007320,NaN,NaN,NaN,NaN,4
215,NaT,94460154,323007337,NaN,NaN,NaN,NaN,4

In [80]:
# liquidacion_centro_costo_caso4[liquidacion_centro_costo_caso4['TipoCalculo'] == 'F']

In [81]:
# liquidacion_centro_costo_caso4[liquidacion_centro_costo_caso4['TipoCalculo'] == 'V']

In [82]:
liquidacion_centro_costo_caso4[liquidacion_centro_costo_caso4['CodigoEmpleado'] == '8520024']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, CodigoCentroCosto, Valor Base Cálculo, Porcentaje Aplicado, TipoCalculo, Consecutivo, Caso]
Index: []

In [83]:
liquidacion_centro_costo_caso4[liquidacion_centro_costo_caso4['CodigoEmpleado'] == '1032450706']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, CodigoCentroCosto, Valor Base Cálculo, Porcentaje Aplicado, TipoCalculo, Consecutivo, Caso]
Index: []

In [84]:
df_empleados_inactivos['CodigoEmpleado'].unique()

array(['5004323', '5004589', '5032450', '5002705', '53002714', '5003490',
       '1144160710', '1111131', '5002712', '5005936', '80133890',
       '5033791', '1073170831', '1026279360', '50324561', '1030524223',
       '1144034062', '40927502', '5004297', '5002724', '5005356',
       '91285756', '5005463', '1016041063', '5033423', '5002708',
       '1111114', '67032190', '1111138', '9990010', '9990002',
       '1030524723', '5004306', '52193204', '70029961', '1027402807',
       '5039251', '94460154', '31308239', '70009004', '5006048',
       '29116947', '31655084', '5005371', '5004322', '5016689', '5002710',
       '5037260', '52816310', '80895530', '84086164', '53099837',
       '32893962', '1094935408', '1128448666', '5041772', '5003979',
       '34325556', '18957750', '50043001', '5003527', '6474959', '11111',
       '5016714', '51789567', '5003791', '1113625698', '5005372',
       '1144180718', '5004303', '5041314', '10301354', '5038324',
       '52900453', '1026251149', '5004470', '5005370', '1026292468',
       '1111112', '1111137', '1112463626', '80201251', '1120741903',
       '5036651', '5005071', '50395781', '5003954', '5004563',
       '1010180302', '5008363', '5032956', '5002713', '1113621770',
       '1049346441', '79868452', '5004472', '5033250', '50166552',
       '5036652', '1098760371', '5043401', '79747219', '1111117',
       '1014226605', '25692643', '70002073', '79758250', '52733955',
       '35410002', '52396266', '5034374', '1032450706', '5044110',
       '39760927', '5043875', '53014165', '5036655', '5036610',
       '1020815612', '70032756', '1111127', '80180731', '5019940',
       '5035551', '8520024', '5016583', '41960389', '5002899', '5002700',
       '39099258', '1111130', '5041307', '5041843', '5041387',
       '1032449509', '5004557', '1020784302', '5041369', '13874027',
       '700020681', '5005917', '5036653'], dtype=object)

In [85]:
resultado_ultima_liquidacion_empleados_retirados_o_inactivos['CodigoEmpleado'].unique()

array(['1020784302', '1020815612', '1073170831', '1098760371', '1111112',
       '1111117', '1111127', '1111130', '1111131', '1112463626',
       '1113621770', '1144180718', '31308239', '5002700', '5002708',
       '5002713', '5002899', '5003527', '5003954', '5004303', '5004306',
       '5004589', '5005071', '5005370', '5016583', '5016689', '5016714',
       '5019940', '5033791', '5036652', '5038324', '5041369', '5041387',
       '5041772', '5043875', '5044110', '52396266', '52900453', '6474959',
       '70009004', '70029961', '80895530', '94460154'], dtype=object)

In [86]:
empleados_con_fecha_retiro_ano_actual['CodigoEmpleado'].unique()

array([], dtype=object)

In [87]:
cruzados = df_empleados_inactivos[['CodigoEmpleado']].merge(
    resultado_ultima_liquidacion_empleados_retirados_o_inactivos[['CodigoEmpleado']],
    how='outer',
    indicator=True
)
cruzados = cruzados.drop_duplicates()
cruzados

    CodigoEmpleado     _merge
0       1010180302  left_only
1       1014226605  left_only
2       1016041063  left_only
3       1020784302       both
6       1020815612       both
..             ...        ...
310        8520024  left_only
311       91285756  left_only
312       94460154       both
313        9990002  left_only
314        9990010  left_only

[142 rows x 2 columns]

In [88]:
cruzados[cruzados['_merge'] == 'left_only']

    CodigoEmpleado     _merge
0       1010180302  left_only
1       1014226605  left_only
2       1016041063  left_only
8       1026251149  left_only
9       1026279360  left_only
..             ...        ...
309       84086164  left_only
310        8520024  left_only
311       91285756  left_only
313        9990002  left_only
314        9990010  left_only

[99 rows x 2 columns]

In [89]:
cruzados[cruzados['_merge'] == 'right_only']

Empty DataFrame
Columns: [CodigoEmpleado, _merge]
Index: []

In [90]:
cruzados[cruzados['_merge'] == 'both']

    CodigoEmpleado _merge
3       1020784302   both
6       1020815612   both
18      1073170831   both
20      1098760371   both
22         1111112   both
26         1111117   both
29         1111127   both
32         1111130   both
35         1111131   both
40      1112463626   both
42      1113621770   both
50      1144180718   both
55        31308239   both
65         5002700   both
93         5002708   both
97         5002713   both
100        5002899   both
104        5003527   both
108        5003954   both
114        5004303   both
135        5004306   both
162        5004589   both
174        5005071   both
176        5005370   both
186        5016583   both
189        5016689   both
192        5016714   both
213        5019940   both
223        5033791   both
232        5036652   both
238        5038324   both
244        5041369   both
245        5041387   both
261        5041772   both
265        5043875   both
268        5044110   both
273       52396266   both
276       52900453   both
280        6474959   both
286       70009004   both
296       70029961   both
308       80895530   both
312       94460154   both

In [91]:
liquidacion_centro_costo_caso4['CodigoEmpleado'].unique()

array(['1020784302', '1020815612', '1073170831', '1098760371', '1111112',
       '1111117', '1111127', '1111130', '1111131', '1112463626',
       '1113621770', '1144180718', '31308239', '5002700', '5002708',
       '5002713', '5002899', '5003527', '5003954', '5004303', '5004306',
       '5004589', '5005071', '5005370', '5016583', '5016689', '5016714',
       '5019940', '5033791', '5036652', '5038324', '5041369', '5041387',
       '5041772', '5043875', '5044110', '52396266', '52900453', '6474959',
       '70009004', '70029961', '80895530', '94460154'], dtype=object)

In [92]:
liquidacion_centro_costo_caso4.to_excel('liquidacion_centro_costo_caso4.xlsx')

## Caso 5 - Liquidación Centro de Costo

In [93]:
fecha_liquidacion

'2025-04-01'

In [94]:
liquidacion_centro_costo_caso5 = ultimos_registros_liquidacion_centro_costo_garantizado[
    ultimos_registros_liquidacion_centro_costo_garantizado['Fecha Proceso'] == fecha_liquidacion
]

liquidacion_centro_costo_caso5['Caso'] = 5

liquidacion_centro_costo_caso5

C:\Users\HP\AppData\Local\Temp\ipykernel_32488\1776886261.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liquidacion_centro_costo_caso5['Caso'] = 5

,Fecha Proceso,CodigoEmpleado,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Consecutivo,TipoCalculo,Caso
0,2025-04-01,1013630697,2760000.0,323004035,1.00,0.0,F,5
1,2025-04-01,1018418655,1044225.0,0,0.00,0.0,F,5
2,2025-04-01,1047393705,3941000.0,0,0.00,0.0,F,5
4,2025-04-01,5016665,4500000.0,323004040,1.00,0.0,F,5
6,2025-04-01,70002068,7882000.0,323007260,0.50,0.0,F,5
7,2025-04-01,70002068,7882000.0,323007300,0.05,0.0,F,5
8,2025-04-01,70002068,7882000.0,323007350,0.45,0.0,F,5
18,2025-04-01,70038624,7500000.0,323007337,0.05,0.0,F,5
19,2025-04-01,70038624,7500000.0,323015065,0.95,0.0,F,5
20,2025-04-01,70038889,3000000.0,323004010,1.00,0.0,F,5
21,2025-04-01,70039305,3270000.0,323004033,0.03,0.0,F,5
22,2025-04-01,70039305,3270000.0,323004034,0.75,0.0,F,5
23,2025-04-01,70039305,3270000.0,323004036,0.22,0.0,F,5
24,2025-04-01,70040806,2500000.0,323007337,0.05,0.0,F,5
25,2025-04-01,70040806,2500000.0,323015070,0.95,0.0,F,5
26,2025-04-01,70042060,5640000.0,323015045,1.00,0.0,F,5
27,2025-04-01,79914159,5400000.0,0,0.00,0.0,F,5
28,2025-04-01,94526955,9800000.0,323004050,1.00,0.0,F,5

## Corrección Caso 1

In [95]:
datos = {
    '1111117': 300000.0,
    '5032456': -300000.0
}

df_ajustes_liquidaciones = pd.DataFrame(list(datos.items()), columns=['CodigoEmpleado', 'AjusteValorLiquidado'])
df_ajustes_liquidaciones

  CodigoEmpleado  AjusteValorLiquidado
0        1111117              300000.0
1        5032456             -300000.0

In [96]:
df_ajustes_liquidaciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CodigoEmpleado        2 non-null      object
 1   AjusteValorLiquidado  2 non-null      float64
dtypes: float64(1), object(1)
memory usage: 164.0+ bytes

In [97]:
len(liquidacion_centro_costo_caso1)

50

In [98]:
len(liquidacion_centro_costo_caso1[liquidacion_centro_costo_caso1['Fecha Proceso'] < fecha_liquidacion])

40

In [99]:
len(liquidacion_centro_costo_caso1[liquidacion_centro_costo_caso1['Fecha Proceso'] == fecha_liquidacion])

10

In [100]:
ultimos_liquidacion_centro_costo_caso1 = liquidacion_centro_costo_caso1[liquidacion_centro_costo_caso1['Fecha Proceso'] == fecha_liquidacion]
ultimos_liquidacion_centro_costo_caso1

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
487,2025-04-01,5004523,F,0.0,898362.500,323007332,0.10,1
488,2025-04-01,5004523,F,0.0,898362.500,323007333,0.10,1
489,2025-04-01,5004523,F,0.0,898362.500,323010165,0.80,1
750,2025-04-01,5005355,F,0.0,52265.625,323007260,0.50,1
751,2025-04-01,5005355,F,0.0,52265.625,323007300,0.05,1
752,2025-04-01,5005355,F,0.0,52265.625,323007350,0.45,1
768,2025-04-01,5037259,F,0.0,953281.250,323007270,1.00,1
792,2025-04-01,70002044,F,0.0,1465882.150,323015050,1.00,1
881,2025-04-01,70021970,F,0.0,266796.875,323007330,0.80,1
882,2025-04-01,70021970,F,0.0,266796.875,323007331,0.20,1

In [101]:
_liquidacion_centro_costo_garantizado = pd.concat([
    liquidacion_centro_costo_caso3,
    liquidacion_centro_costo_caso5
])
_liquidacion_centro_costo_garantizado

,Fecha Proceso,CodigoEmpleado,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Consecutivo,TipoCalculo,Caso
3,2025-04-01,25278820,2500000.0,0,0.00,0.0,F,3
5,2025-04-01,5032456,6000000.0,323007337,1.00,0.0,F,3
9,2025-04-01,70020733,5162500.0,323007337,1.00,0.0,F,3
10,2025-04-01,70034526,2500000.0,323015050,1.00,0.0,F,3
11,2025-04-01,70034529,2500000.0,323015045,1.00,0.0,F,3
12,2025-04-01,70034730,476000.0,323007320,1.00,0.0,F,3
13,2025-04-01,70036120,2500000.0,323007337,0.05,0.0,F,3
14,2025-04-01,70036120,2500000.0,323015065,0.95,0.0,F,3
15,2025-04-01,70036160,2500000.0,323007260,0.50,0.0,F,3
16,2025-04-01,70036160,2500000.0,323007300,0.05,0.0,F,3
17,2025-04-01,70036160,2500000.0,323007350,0.45,0.0,F,3
0,2025-04-01,1013630697,2760000.0,323004035,1.00,0.0,F,5
1,2025-04-01,1018418655,1044225.0,0,0.00,0.0,F,5
2,2025-04-01,1047393705,3941000.0,0,0.00,0.0,F,5
4,2025-04-01,5016665,4500000.0,323004040,1.00,0.0,F,5
6,2025-04-01,70002068,7882000.0,323007260,0.50,0.0,F,5
7,2025-04-01,70002068,7882000.0,323007300,0.05,0.0,F,5
8,2025-04-01,70002068,7882000.0,323007350,0.45,0.0,F,5
18,2025-04-01,70038624,7500000.0,323007337,0.05,0.0,F,5
19,2025-04-01,70038624,7500000.0,323015065,0.95,0.0,F,5
20,2025-04-01,70038889,3000000.0,323004010,1.00,0.0,F,5
21,2025-04-01,70039305,3270000.0,323004033,0.03,0.0,F,5
22,2025-04-01,70039305,3270000.0,323004034,0.75,0.0,F,5
23,2025-04-01,70039305,3270000.0,323004036,0.22,0.0,F,5
24,2025-04-01,70040806,2500000.0,323007337,0.05,0.0,F,5
25,2025-04-01,70040806,2500000.0,323015070,0.95,0.0,F,5
26,2025-04-01,70042060,5640000.0,323015045,1.00,0.0,F,5
27,2025-04-01,79914159,5400000.0,0,0.00,0.0,F,5
28,2025-04-01,94526955,9800000.0,323004050,1.00,0.0,F,5

In [102]:
liquidacion_centro_costo_caso4

,Fecha Proceso,CodigoEmpleado,CodigoCentroCosto,Valor Base Cálculo,Porcentaje Aplicado,TipoCalculo,Consecutivo,Caso
0,NaT,1020784302,323007300,NaN,NaN,NaN,NaN,4
1,NaT,1020784302,323007350,NaN,NaN,NaN,NaN,4
2,NaT,1020784302,323007260,NaN,NaN,NaN,NaN,4
3,NaT,1020815612,323015035,NaN,NaN,NaN,NaN,4
4,NaT,1020815612,323007320,NaN,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...
211,2025-03-01,70029961,323007270,1014624.0,1.0,F,0.0,4
212,2025-03-01,70029961,323007270,6240000.0,1.0,F,10.0,4
213,2025-03-01,70029961,323007270,2808000.0,1.0,V,1.0,4
214,NaT,80895530,323007320,NaN,NaN,NaN,NaN,4
215,NaT,94460154,323007337,NaN,NaN,NaN,NaN,4

In [103]:
ajuste_liquidacion_centro_costo_caso1 = ultimos_liquidacion_centro_costo_caso1.copy().drop(columns=['Caso']).merge(
    _liquidacion_centro_costo_garantizado.copy().drop(columns=['Caso']).rename(columns={'Valor Base Cálculo': 'Valor Garantizado'}),
    how='left'
).merge(
    df_ajustes_liquidaciones,
    how='left',
    on=['CodigoEmpleado']
)
ajuste_liquidacion_centro_costo_caso1.fillna(0, inplace=True)
ajuste_liquidacion_centro_costo_caso1.head()

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Valor Garantizado,AjusteValorLiquidado
0,2025-04-01,5004523,F,0.0,898362.500,323007332,0.10,0.0,0.0
1,2025-04-01,5004523,F,0.0,898362.500,323007333,0.10,0.0,0.0
2,2025-04-01,5004523,F,0.0,898362.500,323010165,0.80,0.0,0.0
3,2025-04-01,5005355,F,0.0,52265.625,323007260,0.50,0.0,0.0
4,2025-04-01,5005355,F,0.0,52265.625,323007300,0.05,0.0,0.0

In [104]:
len(liquidacion_centro_costo_caso4)

213

In [105]:
liquidacion_centro_costo_caso4[liquidacion_centro_costo_caso4['CodigoEmpleado'] == '5016583']

,Fecha Proceso,CodigoEmpleado,CodigoCentroCosto,Valor Base Cálculo,Porcentaje Aplicado,TipoCalculo,Consecutivo,Caso
128,NaT,5016583,323007337,NaN,NaN,NaN,NaN,4
129,NaT,5016583,323015075,NaN,NaN,NaN,NaN,4

In [106]:
len(ajuste_liquidacion_centro_costo_caso1)

10

In [107]:
ajuste_liquidacion_centro_costo_caso1[ajuste_liquidacion_centro_costo_caso1['CodigoEmpleado'] == '5004523']

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Valor Garantizado,AjusteValorLiquidado
0,2025-04-01,5004523,F,0.0,898362.5,323007332,0.1,0.0,0.0
1,2025-04-01,5004523,F,0.0,898362.5,323007333,0.1,0.0,0.0
2,2025-04-01,5004523,F,0.0,898362.5,323010165,0.8,0.0,0.0

In [108]:
liquidacion_centro_costo_merge_casos_1_4 = ajuste_liquidacion_centro_costo_caso1.copy().merge(
    liquidacion_centro_costo_caso4.copy().drop(columns=['Caso', 'Valor Base Cálculo']),
    how='outer',
    indicator=True
)
liquidacion_centro_costo_merge_casos_1_4.head()

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Valor Garantizado,AjusteValorLiquidado,_merge
0,NaT,1020784302,NaN,NaN,NaN,323007260,NaN,NaN,NaN,right_only
1,NaT,1020784302,NaN,NaN,NaN,323007300,NaN,NaN,NaN,right_only
2,NaT,1020784302,NaN,NaN,NaN,323007350,NaN,NaN,NaN,right_only
3,NaT,1020815612,NaN,NaN,NaN,323007320,NaN,NaN,NaN,right_only
4,NaT,1020815612,NaN,NaN,NaN,323015035,NaN,NaN,NaN,right_only

In [109]:
liquidacion_centro_costo_merge_casos_1_4[liquidacion_centro_costo_merge_casos_1_4['CodigoEmpleado'] == '5004523']

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Valor Garantizado,AjusteValorLiquidado,_merge
213,2025-04-01,5004523,F,0.0,898362.5,323007332,0.1,0.0,0.0,left_only
214,2025-04-01,5004523,F,0.0,898362.5,323007333,0.1,0.0,0.0,left_only
215,2025-04-01,5004523,F,0.0,898362.5,323010165,0.8,0.0,0.0,left_only

In [110]:
len(liquidacion_centro_costo_merge_casos_1_4[
    liquidacion_centro_costo_merge_casos_1_4['_merge'] == 'left_only'
])

10

In [111]:
excluir_empleados_inactivos_liquidacion_centro_costo_caso1 = liquidacion_centro_costo_merge_casos_1_4[
    liquidacion_centro_costo_merge_casos_1_4['_merge'] == 'left_only'
]
excluir_empleados_inactivos_liquidacion_centro_costo_caso1

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Valor Garantizado,AjusteValorLiquidado,_merge
213,2025-04-01,5004523,F,0.0,898362.500,323007332,0.10,0.0,0.0,left_only
214,2025-04-01,5004523,F,0.0,898362.500,323007333,0.10,0.0,0.0,left_only
215,2025-04-01,5004523,F,0.0,898362.500,323010165,0.80,0.0,0.0,left_only
216,2025-04-01,5005355,F,0.0,52265.625,323007260,0.50,0.0,0.0,left_only
217,2025-04-01,5005355,F,0.0,52265.625,323007300,0.05,0.0,0.0,left_only
218,2025-04-01,5005355,F,0.0,52265.625,323007350,0.45,0.0,0.0,left_only
219,2025-04-01,5037259,F,0.0,953281.250,323007270,1.00,0.0,0.0,left_only
220,2025-04-01,70002044,F,0.0,1465882.150,323015050,1.00,0.0,0.0,left_only
221,2025-04-01,70021970,F,0.0,266796.875,323007330,0.80,0.0,0.0,left_only
222,2025-04-01,70021970,F,0.0,266796.875,323007331,0.20,0.0,0.0,left_only

In [112]:
len(liquidacion_centro_costo_merge_casos_1_4[
    liquidacion_centro_costo_merge_casos_1_4['_merge'] == 'both'
])

0

In [113]:
liquidacion_centro_costo_merge_casos_1_4[
    liquidacion_centro_costo_merge_casos_1_4['_merge'] == 'both'
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Valor Garantizado, AjusteValorLiquidado, _merge]
Index: []

In [114]:
excluir_empleados_inactivos_liquidacion_centro_costo_caso1.loc[:, 'Valor Final'] = (
    excluir_empleados_inactivos_liquidacion_centro_costo_caso1['Valor Base Cálculo']
    - excluir_empleados_inactivos_liquidacion_centro_costo_caso1['Valor Garantizado']
    - excluir_empleados_inactivos_liquidacion_centro_costo_caso1['AjusteValorLiquidado']
).abs()
excluir_empleados_inactivos_liquidacion_centro_costo_caso1

C:\Users\HP\AppData\Local\Temp\ipykernel_32488\2934893309.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  excluir_empleados_inactivos_liquidacion_centro_costo_caso1.loc[:, 'Valor Final'] = (

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Valor Garantizado,AjusteValorLiquidado,_merge,Valor Final
213,2025-04-01,5004523,F,0.0,898362.500,323007332,0.10,0.0,0.0,left_only,898362.500
214,2025-04-01,5004523,F,0.0,898362.500,323007333,0.10,0.0,0.0,left_only,898362.500
215,2025-04-01,5004523,F,0.0,898362.500,323010165,0.80,0.0,0.0,left_only,898362.500
216,2025-04-01,5005355,F,0.0,52265.625,323007260,0.50,0.0,0.0,left_only,52265.625
217,2025-04-01,5005355,F,0.0,52265.625,323007300,0.05,0.0,0.0,left_only,52265.625
218,2025-04-01,5005355,F,0.0,52265.625,323007350,0.45,0.0,0.0,left_only,52265.625
219,2025-04-01,5037259,F,0.0,953281.250,323007270,1.00,0.0,0.0,left_only,953281.250
220,2025-04-01,70002044,F,0.0,1465882.150,323015050,1.00,0.0,0.0,left_only,1465882.150
221,2025-04-01,70021970,F,0.0,266796.875,323007330,0.80,0.0,0.0,left_only,266796.875
222,2025-04-01,70021970,F,0.0,266796.875,323007331,0.20,0.0,0.0,left_only,266796.875

In [115]:
excluir_empleados_inactivos_liquidacion_centro_costo_caso1[excluir_empleados_inactivos_liquidacion_centro_costo_caso1['CodigoEmpleado'] == '5004523']

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Valor Garantizado,AjusteValorLiquidado,_merge,Valor Final
213,2025-04-01,5004523,F,0.0,898362.5,323007332,0.1,0.0,0.0,left_only,898362.5
214,2025-04-01,5004523,F,0.0,898362.5,323007333,0.1,0.0,0.0,left_only,898362.5
215,2025-04-01,5004523,F,0.0,898362.5,323010165,0.8,0.0,0.0,left_only,898362.5

In [116]:
liquidacion_centro_costo_caso1 = excluir_empleados_inactivos_liquidacion_centro_costo_caso1.copy().drop(
        columns=['Valor Base Cálculo']
    ).rename(
            columns={'Valor Final': 'Valor Base Cálculo'}
        )[
            ['Fecha Proceso', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo', 'Valor Base Cálculo', 'CodigoCentroCosto', 'Porcentaje Aplicado']
         ].copy()
liquidacion_centro_costo_caso1['Caso'] = 1 
liquidacion_centro_costo_caso1.head()

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
213,2025-04-01,5004523,F,0.0,898362.500,323007332,0.10,1
214,2025-04-01,5004523,F,0.0,898362.500,323007333,0.10,1
215,2025-04-01,5004523,F,0.0,898362.500,323010165,0.80,1
216,2025-04-01,5005355,F,0.0,52265.625,323007260,0.50,1
217,2025-04-01,5005355,F,0.0,52265.625,323007300,0.05,1

In [117]:
liquidacion_centro_costo_caso1[liquidacion_centro_costo_caso1['CodigoEmpleado'] == '5004523']

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
213,2025-04-01,5004523,F,0.0,898362.5,323007332,0.1,1
214,2025-04-01,5004523,F,0.0,898362.5,323007333,0.1,1
215,2025-04-01,5004523,F,0.0,898362.5,323010165,0.8,1

In [118]:
# liquidacion_centro_costo_caso1[liquidacion_centro_costo_caso1['Fecha Proceso'] == fecha_liquidacion].drop(
#         columns=['Caso']
#     ).rename(columns={'Valor Base Cálculo': 'Valor Total Liquidado'}).merge(
#             liquidacion_centro_costo_caso3.drop(columns=['Caso']).rename(columns={'Valor Base Cálculo': 'Valor Liquidado Garantizado'}),
#             how='left'
#         )

In [119]:
liquidacion_centro_costo_caso5

,Fecha Proceso,CodigoEmpleado,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Consecutivo,TipoCalculo,Caso
0,2025-04-01,1013630697,2760000.0,323004035,1.00,0.0,F,5
1,2025-04-01,1018418655,1044225.0,0,0.00,0.0,F,5
2,2025-04-01,1047393705,3941000.0,0,0.00,0.0,F,5
4,2025-04-01,5016665,4500000.0,323004040,1.00,0.0,F,5
6,2025-04-01,70002068,7882000.0,323007260,0.50,0.0,F,5
7,2025-04-01,70002068,7882000.0,323007300,0.05,0.0,F,5
8,2025-04-01,70002068,7882000.0,323007350,0.45,0.0,F,5
18,2025-04-01,70038624,7500000.0,323007337,0.05,0.0,F,5
19,2025-04-01,70038624,7500000.0,323015065,0.95,0.0,F,5
20,2025-04-01,70038889,3000000.0,323004010,1.00,0.0,F,5
21,2025-04-01,70039305,3270000.0,323004033,0.03,0.0,F,5
22,2025-04-01,70039305,3270000.0,323004034,0.75,0.0,F,5
23,2025-04-01,70039305,3270000.0,323004036,0.22,0.0,F,5
24,2025-04-01,70040806,2500000.0,323007337,0.05,0.0,F,5
25,2025-04-01,70040806,2500000.0,323015070,0.95,0.0,F,5
26,2025-04-01,70042060,5640000.0,323015045,1.00,0.0,F,5
27,2025-04-01,79914159,5400000.0,0,0.00,0.0,F,5
28,2025-04-01,94526955,9800000.0,323004050,1.00,0.0,F,5

## Concatenación Casos - Liquidación Centro de Costo

In [120]:
liquidaciones_centro_costo_casos = pd.concat([
    liquidacion_centro_costo_caso1,
    liquidacion_centro_costo_caso3,
    liquidacion_centro_costo_caso4,
    liquidacion_centro_costo_caso5
], ignore_index=True)
liquidaciones_centro_costo_casos

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
0,2025-04-01,5004523,F,0.0,898362.500,323007332,0.10,1
1,2025-04-01,5004523,F,0.0,898362.500,323007333,0.10,1
2,2025-04-01,5004523,F,0.0,898362.500,323010165,0.80,1
3,2025-04-01,5005355,F,0.0,52265.625,323007260,0.50,1
4,2025-04-01,5005355,F,0.0,52265.625,323007300,0.05,1
...,...,...,...,...,...,...,...,...
247,2025-04-01,70040806,F,0.0,2500000.000,323007337,0.05,5
248,2025-04-01,70040806,F,0.0,2500000.000,323015070,0.95,5
249,2025-04-01,70042060,F,0.0,5640000.000,323015045,1.00,5
250,2025-04-01,79914159,F,0.0,5400000.000,0,0.00,5
251,2025-04-01,94526955,F,0.0,9800000.000,323004050,1.00,5

In [121]:
# liquidaciones_centro_costo_casos['Valor Calculado'] = liquidaciones_centro_costo_casos['Valor Base Cálculo'] * liquidaciones_centro_costo_casos['Porcentaje Aplicado']
# liquidaciones_centro_costo_casos.head()

In [122]:
liquidaciones_centro_costo_casos.to_excel("liquidaciones_centro_costo_casos.xlsx")

## Se realizan las liquidaciones por Centros de Costos según el Tipo de Cálculo de las Variables

In [123]:
maestra_resultados_por_empleado[
    (maestra_resultados_por_empleado['CodigoEmpleado'] == '5016583') &
    (maestra_resultados_por_empleado['Fecha'] == '2023-08-01')
]

Empty DataFrame
Columns: [Unnamed: 0.1, Contexto, Fecha, Variable, PorcentajeCumplimiento, Real, Presupuesto, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, SalarioVariable, AreaCalculo, Apellidos, Nombre, FechaIngreso, FactorIncentivo, FactorMes, Liquidado, DifMonths, NuevoFactor, ResultadoPresupuesto, ResultadoRealMes, PorcentajeCumplimientoMes, Unnamed: 0, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, Nombre variable, Nombre consecutivo, _merge, NuevoFactorBK]
Index: []

[0 rows x 32 columns]

In [124]:
main = maestra_resultados_por_empleado.copy().merge(
    right=df_parrillas_tipos_calculos.rename(columns={'NombreRubro': 'Variable'}),
    on=['TipoEmpleado', 'AreaCalculo', 'Variable'],
    how='left'
)
main = main[['Contexto', 'Fecha', 'Variable', 'PorcentajeCumplimiento', 'CodigoEmpleado', 'Porcentaje', 'Consecutivo', 'TipoEmpleado', 'AreaCalculo', 'Liquidado','CodigoRubro', 'TipoCalculo']]
main

,Contexto,Fecha,Variable,PorcentajeCumplimiento,CodigoEmpleado,Porcentaje,Consecutivo,TipoEmpleado,AreaCalculo,Liquidado,CodigoRubro,TipoCalculo
0,Pais,2025-04-01,VentaCobradaBraunPais,0.95,1010180302,0.25,0.0,NaN,NaN,NaN,NaN,NaN
1,1013587064,2025-01-01,ObjetivosCualitativos,0.90,1013587064,0.40,0.0,AD2,2.0,100000.0,NaN,NaN
2,1013587064_2,2025-01-01,KpisSurgical,1.12,1013587064,0.20,2.0,AD2,2.0,250000.0,NaN,NaN
3,1013587064_3,2025-01-01,KpisSurgical,1.01,1013587064,0.20,3.0,AD2,2.0,120000.0,NaN,NaN
4,1013587064,2025-02-01,ObjetivosCualitativos,0.90,1013587064,0.40,0.0,AD2,2.0,200000.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4212,5036358,2025-04-01,KpiCalidad,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4213,70038624,2025-04-01,KpiCalidad,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4214,5016700,2025-04-01,KpiCalidad,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4215,5041312,2025-04-01,KpiCalidad,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4216,5016782,2025-04-01,KpiCalidad,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
main[
    (main['CodigoEmpleado'] == '5016583') &
    (main['Fecha'] == '2023-08-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, AreaCalculo, Liquidado, CodigoRubro, TipoCalculo]
Index: []

### Tipo de Cálculo Fijo

In [126]:
# final_calculo_fijo = pd.concat([
#     final_calculo_fijo,
#     liquidaciones_centro_costo_casos[liquidaciones_centro_costo_casos['TipoCalculo'] == 'F']
# ])

In [127]:
calculo_fijo = main[main['TipoCalculo']== 'F']
calculo_fijo

,Contexto,Fecha,Variable,PorcentajeCumplimiento,CodigoEmpleado,Porcentaje,Consecutivo,TipoEmpleado,AreaCalculo,Liquidado,CodigoRubro,TipoCalculo
15,1013630697,2025-04-01,ObjetivosCualitativos,0.88,1013630697,0.20,0.0,AD3,3.0,552000.0,3,F
16,1013630697_1,2025-04-01,VentaFacturadaBraunPaisSUB,0.93,1013630697,0.40,1.0,AD3,3.0,1563264.0,1,F
17,1013630697_1,2025-04-01,EBITCOGSPaisSUB,1.05,1013630697,0.40,1.0,AD3,3.0,5520000.0,2,F
18,1015417716,2025-04-01,ObjetivosCualitativos,0.80,1015417716,0.20,0.0,MK,11.0,1400000.0,4,F
22,EBITCOGSP,2025-04-01,EBITCOGSPais,1.05,1015417716,0.40,0.0,MK,11.0,12600000.0,3,F
...,...,...,...,...,...,...,...,...,...,...,...,...
2904,Pais,2025-03-01,VentaCobradaBraunPais,0.90,9990011,0.25,0.0,VC,4.0,0.0,1,F
2905,9990011,2025-03-01,VentaCobradaBraunCluster,0.99,9990011,0.25,0.0,VC,4.0,0.0,3,F
2911,9990011,2025-04-01,ObjetivosCualitativos,0.80,9990011,0.15,0.0,VC,4.0,0.0,4,F
2912,Pais,2025-04-01,VentaCobradaBraunPais,0.95,9990011,0.25,0.0,VC,4.0,0.0,1,F
2913,9990011,2025-04-01,VentaCobradaBraunCluster,1.01,9990011,0.25,0.0,VC,4.0,0.0,3,F

In [128]:
calculo_fijo = calculo_fijo.groupby(['Fecha', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo'], as_index=False)[['Liquidado']].apply(sum)
calculo_fijo

C:\Users\HP\AppData\Local\Temp\ipykernel_32488\1347366289.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  calculo_fijo = calculo_fijo.groupby(['Fecha', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo'], as_index=False)[['Liquidado']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

         Fecha CodigoEmpleado TipoCalculo  Consecutivo   Liquidado
0   2025-01-01        5002697           F          0.0   1068720.0
1   2025-01-01        5002699           F          0.0    762850.0
2   2025-01-01        5002700           F          0.0   1044775.0
3   2025-01-01        5002711           F          0.0    300000.0
4   2025-01-01        5002721           F          0.0    903715.0
..         ...            ...         ...          ...         ...
591 2025-04-01       70042060           F          0.0   3313500.0
592 2025-04-01       94526955           F          0.0   1960000.0
593 2025-04-01       94526955           F          1.0  12575360.0
594 2025-04-01       94526955           F          2.0  19600000.0
595 2025-04-01        9990011           F          0.0         0.0

[596 rows x 5 columns]

In [129]:
calculo_fijo[calculo_fijo['CodigoEmpleado'] == '5005463']

Empty DataFrame
Columns: [Fecha, CodigoEmpleado, TipoCalculo, Consecutivo, Liquidado]
Index: []

In [130]:
liquidaciones_centro_costo_casos[liquidaciones_centro_costo_casos['TipoCalculo'] == 'F']

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
0,2025-04-01,5004523,F,0.0,898362.500,323007332,0.10,1
1,2025-04-01,5004523,F,0.0,898362.500,323007333,0.10,1
2,2025-04-01,5004523,F,0.0,898362.500,323010165,0.80,1
3,2025-04-01,5005355,F,0.0,52265.625,323007260,0.50,1
4,2025-04-01,5005355,F,0.0,52265.625,323007300,0.05,1
...,...,...,...,...,...,...,...,...
247,2025-04-01,70040806,F,0.0,2500000.000,323007337,0.05,5
248,2025-04-01,70040806,F,0.0,2500000.000,323015070,0.95,5
249,2025-04-01,70042060,F,0.0,5640000.000,323015045,1.00,5
250,2025-04-01,79914159,F,0.0,5400000.000,0,0.00,5
251,2025-04-01,94526955,F,0.0,9800000.000,323004050,1.00,5

In [131]:
calculo_fijo.to_excel('calculo_fijo.xlsx')

In [132]:
final_calculo_fijo = calculo_fijo.merge(
    df_empleados_centros_costos,
    on=['CodigoEmpleado'],
    how='left'
).rename(columns={
    'Fecha': 'Fecha Proceso',
    'Liquidado':'Valor Base Cálculo',
    'PorcentajeAsignacion': 'Porcentaje Aplicado'
})
final_calculo_fijo['Caso'] = 0
final_calculo_fijo

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
0,2025-01-01,5002697,F,0.0,1068720.0,323015045,1.0,0
1,2025-01-01,5002699,F,0.0,762850.0,323015095,0.8,0
2,2025-01-01,5002699,F,0.0,762850.0,323015100,0.2,0
3,2025-01-01,5002700,F,0.0,1044775.0,323007332,0.1,0
4,2025-01-01,5002700,F,0.0,1044775.0,323007333,0.1,0
...,...,...,...,...,...,...,...,...
1037,2025-04-01,70042060,F,0.0,3313500.0,323015045,1.0,0
1038,2025-04-01,94526955,F,0.0,1960000.0,323004050,1.0,0
1039,2025-04-01,94526955,F,1.0,12575360.0,323004050,1.0,0
1040,2025-04-01,94526955,F,2.0,19600000.0,323004050,1.0,0
1041,2025-04-01,9990011,F,0.0,0.0,NaN,NaN,0

In [133]:
 liquidaciones_centro_costo_casos[liquidaciones_centro_costo_casos['TipoCalculo'] == 'F']

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
0,2025-04-01,5004523,F,0.0,898362.500,323007332,0.10,1
1,2025-04-01,5004523,F,0.0,898362.500,323007333,0.10,1
2,2025-04-01,5004523,F,0.0,898362.500,323010165,0.80,1
3,2025-04-01,5005355,F,0.0,52265.625,323007260,0.50,1
4,2025-04-01,5005355,F,0.0,52265.625,323007300,0.05,1
...,...,...,...,...,...,...,...,...
247,2025-04-01,70040806,F,0.0,2500000.000,323007337,0.05,5
248,2025-04-01,70040806,F,0.0,2500000.000,323015070,0.95,5
249,2025-04-01,70042060,F,0.0,5640000.000,323015045,1.00,5
250,2025-04-01,79914159,F,0.0,5400000.000,0,0.00,5
251,2025-04-01,94526955,F,0.0,9800000.000,323004050,1.00,5

In [134]:
#  liquidaciones_centro_costo_casos[
#      (liquidaciones_centro_costo_casos['TipoCalculo'] == 'F') &
#      (liquidaciones_centro_costo_casos['Fecha Proceso'] < '2023-12-01')
#  ]['Fecha Proceso'] = pd.to_datetime(fecha_liquidacion)

In [135]:
liquidaciones_centro_costo_casos.loc[
    (liquidaciones_centro_costo_casos['TipoCalculo'] == 'F') &
    (liquidaciones_centro_costo_casos['Fecha Proceso'] < fecha_liquidacion),
    'Fecha Proceso'
] = pd.to_datetime(fecha_liquidacion)

In [136]:
 liquidaciones_centro_costo_casos[
     (liquidaciones_centro_costo_casos['TipoCalculo'] == 'V') &
     (liquidaciones_centro_costo_casos['CodigoEmpleado'] == '5002899')
 ]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso]
Index: []

In [137]:
# liquidacion_centro_costo_caso4['Fecha Proceso'] = pd.to_datetime(fecha_liquidacion)

In [138]:
final_calculo_fijo = pd.concat([
    final_calculo_fijo,
    liquidaciones_centro_costo_casos[liquidaciones_centro_costo_casos['TipoCalculo'] == 'F']
])
final_calculo_fijo

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
0,2025-01-01,5002697,F,0.0,1068720.0,323015045,1.00,0
1,2025-01-01,5002699,F,0.0,762850.0,323015095,0.80,0
2,2025-01-01,5002699,F,0.0,762850.0,323015100,0.20,0
3,2025-01-01,5002700,F,0.0,1044775.0,323007332,0.10,0
4,2025-01-01,5002700,F,0.0,1044775.0,323007333,0.10,0
...,...,...,...,...,...,...,...,...
247,2025-04-01,70040806,F,0.0,2500000.0,323007337,0.05,5
248,2025-04-01,70040806,F,0.0,2500000.0,323015070,0.95,5
249,2025-04-01,70042060,F,0.0,5640000.0,323015045,1.00,5
250,2025-04-01,79914159,F,0.0,5400000.0,0,0.00,5
251,2025-04-01,94526955,F,0.0,9800000.0,323004050,1.00,5

In [139]:
final_calculo_fijo['Valor Calculado'] = final_calculo_fijo['Valor Base Cálculo'] * final_calculo_fijo['Porcentaje Aplicado']
final_calculo_fijo

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso,Valor Calculado
0,2025-01-01,5002697,F,0.0,1068720.0,323015045,1.00,0,1068720.0
1,2025-01-01,5002699,F,0.0,762850.0,323015095,0.80,0,610280.0
2,2025-01-01,5002699,F,0.0,762850.0,323015100,0.20,0,152570.0
3,2025-01-01,5002700,F,0.0,1044775.0,323007332,0.10,0,104477.5
4,2025-01-01,5002700,F,0.0,1044775.0,323007333,0.10,0,104477.5
...,...,...,...,...,...,...,...,...,...
247,2025-04-01,70040806,F,0.0,2500000.0,323007337,0.05,5,125000.0
248,2025-04-01,70040806,F,0.0,2500000.0,323015070,0.95,5,2375000.0
249,2025-04-01,70042060,F,0.0,5640000.0,323015045,1.00,5,5640000.0
250,2025-04-01,79914159,F,0.0,5400000.0,0,0.00,5,0.0
251,2025-04-01,94526955,F,0.0,9800000.0,323004050,1.00,5,9800000.0

In [140]:
final_calculo_fijo[
    (final_calculo_fijo['CodigoEmpleado'] == '5016583') &
     (final_calculo_fijo['Fecha Proceso'] == '2023-12-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso, Valor Calculado]
Index: []

In [141]:
 liquidaciones_centro_costo_casos[liquidaciones_centro_costo_casos['TipoCalculo'] == 'F'].head()

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso
0,2025-04-01,5004523,F,0.0,898362.500,323007332,0.10,1
1,2025-04-01,5004523,F,0.0,898362.500,323007333,0.10,1
2,2025-04-01,5004523,F,0.0,898362.500,323010165,0.80,1
3,2025-04-01,5005355,F,0.0,52265.625,323007260,0.50,1
4,2025-04-01,5005355,F,0.0,52265.625,323007300,0.05,1

In [142]:
final_calculo_fijo.to_excel('final_calculo_fijo.xlsx')

In [143]:
consolidado_final_calculo_fijo = final_calculo_fijo.copy()
consolidado_final_calculo_fijo[
    (consolidado_final_calculo_fijo['Fecha Proceso'] == '2023-02-01') &
    (consolidado_final_calculo_fijo['CodigoEmpleado'] == '1111117')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso, Valor Calculado]
Index: []

In [144]:
consolidado_final_calculo_fijo['Total Repetidos'] = consolidado_final_calculo_fijo.groupby(
    ['Fecha Proceso', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo', 'CodigoCentroCosto', 'Porcentaje Aplicado']
)['Valor Calculado'].transform('count')

In [145]:
consolidado_final_calculo_fijo['Valor Calculado'] = consolidado_final_calculo_fijo.groupby(
    ['Fecha Proceso', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo', 'CodigoCentroCosto', 'Porcentaje Aplicado']
)['Valor Calculado'].transform('sum')

In [146]:
consolidado_final_calculo_fijo

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso,Valor Calculado,Total Repetidos
0,2025-01-01,5002697,F,0.0,1068720.0,323015045,1.00,0,1068720.0,1.0
1,2025-01-01,5002699,F,0.0,762850.0,323015095,0.80,0,610280.0,1.0
2,2025-01-01,5002699,F,0.0,762850.0,323015100,0.20,0,152570.0,1.0
3,2025-01-01,5002700,F,0.0,1044775.0,323007332,0.10,0,104477.5,1.0
4,2025-01-01,5002700,F,0.0,1044775.0,323007333,0.10,0,104477.5,1.0
...,...,...,...,...,...,...,...,...,...,...
247,2025-04-01,70040806,F,0.0,2500000.0,323007337,0.05,5,584375.0,2.0
248,2025-04-01,70040806,F,0.0,2500000.0,323015070,0.95,5,11103125.0,2.0
249,2025-04-01,70042060,F,0.0,5640000.0,323015045,1.00,5,8953500.0,2.0
250,2025-04-01,79914159,F,0.0,5400000.0,0,0.00,5,0.0,1.0
251,2025-04-01,94526955,F,0.0,9800000.0,323004050,1.00,5,11760000.0,2.0

In [147]:
consolidado_final_calculo_fijo.to_excel('consolidado_final_calculo_fijo.xlsx')

In [148]:
consolidado_final_calculo_fijo['Valor Base Cálculo'] = consolidado_final_calculo_fijo.copy().groupby(
    ['Fecha Proceso', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo', 'CodigoCentroCosto', 'Porcentaje Aplicado']
)['Valor Base Cálculo'].transform('sum')

In [149]:
# Eliminar las columnas 'Caso' y 'Total Repetidos'
consolidado_final_calculo_fijo_sin_repetidos = consolidado_final_calculo_fijo.copy().drop(columns=['Total Repetidos'])

# Eliminar registros duplicados sin tener en cuenta las columnas 'Caso' y 'Total Repetidos'
consolidado_final_calculo_fijo_sin_repetidos = consolidado_final_calculo_fijo_sin_repetidos.drop_duplicates(
    subset=['Fecha Proceso', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo', 'Valor Base Cálculo', 'CodigoCentroCosto', 'Porcentaje Aplicado', 'Valor Calculado'],
    keep='first'
)
consolidado_final_calculo_fijo_sin_repetidos

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso,Valor Calculado
0,2025-01-01,5002697,F,0.0,1068720.0,323015045,1.0,0,1068720.0
1,2025-01-01,5002699,F,0.0,762850.0,323015095,0.8,0,610280.0
2,2025-01-01,5002699,F,0.0,762850.0,323015100,0.2,0,152570.0
3,2025-01-01,5002700,F,0.0,1044775.0,323007332,0.1,0,104477.5
4,2025-01-01,5002700,F,0.0,1044775.0,323007333,0.1,0,104477.5
...,...,...,...,...,...,...,...,...,...
227,2025-04-01,70029961,F,0.0,1950624.0,323007270,1.0,4,1950624.0
230,2025-04-01,70029961,F,10.0,6240000.0,323007270,1.0,4,6240000.0
235,2025-04-01,1018418655,F,0.0,1044225.0,0,0.0,5,0.0
236,2025-04-01,1047393705,F,0.0,3941000.0,0,0.0,5,0.0
250,2025-04-01,79914159,F,0.0,5400000.0,0,0.0,5,0.0

In [150]:
consolidado_final_calculo_fijo_sin_repetidos[consolidado_final_calculo_fijo_sin_repetidos['CodigoEmpleado'] == '1098612757']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso, Valor Calculado]
Index: []

In [151]:
consolidado_final_calculo_fijo_sin_repetidos.to_excel('consolidado_final_calculo_fijo_sin_repetidos.xlsx')

### Tipo de Cálculo Variable

In [152]:
main.head()

,Contexto,Fecha,Variable,PorcentajeCumplimiento,CodigoEmpleado,Porcentaje,Consecutivo,TipoEmpleado,AreaCalculo,Liquidado,CodigoRubro,TipoCalculo
0,Pais,2025-04-01,VentaCobradaBraunPais,0.95,1010180302,0.25,0.0,NaN,NaN,NaN,NaN,NaN
1,1013587064,2025-01-01,ObjetivosCualitativos,0.90,1013587064,0.40,0.0,AD2,2.0,100000.0,NaN,NaN
2,1013587064_2,2025-01-01,KpisSurgical,1.12,1013587064,0.20,2.0,AD2,2.0,250000.0,NaN,NaN
3,1013587064_3,2025-01-01,KpisSurgical,1.01,1013587064,0.20,3.0,AD2,2.0,120000.0,NaN,NaN
4,1013587064,2025-02-01,ObjetivosCualitativos,0.90,1013587064,0.40,0.0,AD2,2.0,200000.0,NaN,NaN

In [153]:
calculo_variable = main[main['TipoCalculo']== 'V']
calculo_variable['Caso'] = 0
calculo_variable.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_32488\2103521809.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  calculo_variable['Caso'] = 0

,Contexto,Fecha,Variable,PorcentajeCumplimiento,CodigoEmpleado,Porcentaje,Consecutivo,TipoEmpleado,AreaCalculo,Liquidado,CodigoRubro,TipoCalculo,Caso
19,mk_11_1,2025-04-01,VentaFacturadaUnidadNegocioSub,0.94,1015417716,0.24,1.0,MK,11.0,2856000.0,2,V,0
20,mk_11_2,2025-04-01,VentaFacturadaUnidadNegocioSub,0.93,1015417716,0.14,2.0,MK,11.0,1617000.0,2,V,0
21,mk_11_3,2025-04-01,VentaFacturadaUnidadNegocioSub,0.52,1015417716,0.02,3.0,MK,11.0,0.0,2,V,0
67,mk_3_1,2025-04-01,VentaFacturadaUnidadNegocioSub,0.85,1031152912,0.24,1.0,MK,3.0,960000.0,2,V,0
68,mk_3_2,2025-04-01,VentaFacturadaUnidadNegocioSub,0.93,1031152912,0.08,2.0,MK,3.0,422400.0,2,V,0

In [154]:
calculo_variable[
    (calculo_variable['CodigoEmpleado'] == '5002899') &
    (calculo_variable['Fecha'] == '2023-04-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, AreaCalculo, Liquidado, CodigoRubro, TipoCalculo, Caso]
Index: []

In [155]:
# maestra_resultados_por_empleado_centro_costo[
#     (maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] == '1032450706') &
#      (maestra_resultados_por_empleado_centro_costo['Fecha'] == '2023-09-01')
# ]

In [156]:
calculo_variable[
    (calculo_variable['TipoCalculo'] == 'V') &
    (calculo_variable['CodigoEmpleado'] == '5016583') &
    (calculo_variable['Fecha'] == '2023-09-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, AreaCalculo, Liquidado, CodigoRubro, TipoCalculo, Caso]
Index: []

In [157]:
liquidaciones_centro_costo_casos[
    (liquidaciones_centro_costo_casos['TipoCalculo'] == 'V') &
    (liquidaciones_centro_costo_casos['CodigoEmpleado'] == '5002899')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso]
Index: []

In [158]:
_calculo_variable_centro_costo_casos = calculo_variable.drop(columns=['Porcentaje', 'Caso', 'PorcentajeCumplimiento']).merge(
    liquidaciones_centro_costo_casos[liquidaciones_centro_costo_casos['TipoCalculo'] == 'V'].rename(
    columns={'Fecha Proceso':'Fecha'}).drop(columns=['Consecutivo', 'Porcentaje Aplicado', 'Valor Base Cálculo']),
    how='right',
    on=['CodigoEmpleado', 'Fecha', 'TipoCalculo']
).drop_duplicates()

_calculo_variable_centro_costo_casos['Fecha'] = pd.to_datetime(fecha_liquidacion)
_calculo_variable_centro_costo_casos

,Contexto,Fecha,Variable,CodigoEmpleado,Consecutivo,TipoEmpleado,AreaCalculo,Liquidado,CodigoRubro,TipoCalculo,CodigoCentroCosto,Caso
0,5002700_1,2025-04-01,VentaFacturadaPortafolioClusterSub,5002700,1.0,VC,3.0,1147930.0,2,V,323007332,4
1,5002700_2,2025-04-01,VentaFacturadaPortafolioClusterSub,5002700,2.0,VC,3.0,0.0,2,V,323007332,4
2,5002700_3,2025-04-01,VentaFacturadaPortafolioClusterSub,5002700,3.0,VC,3.0,1147930.0,2,V,323007332,4
3,5002700_4,2025-04-01,VentaFacturadaPortafolioClusterSub,5002700,4.0,VC,3.0,1434912.5,2,V,323007332,4
4,5002700_5,2025-04-01,VentaFacturadaPortafolioClusterSub,5002700,5.0,VC,3.0,573965.0,2,V,323007332,4
...,...,...,...,...,...,...,...,...,...,...,...,...
373,mk_11_3,2025-04-01,VentaFacturadaUnidadNegocioSub,70009004,3.0,MK,11.0,0.0,2,V,323007338,4
380,mk_11_1,2025-04-01,VentaFacturadaUnidadNegocioSub,70009004,1.0,MK,11.0,765385.2,2,V,323007320,4
381,mk_11_2,2025-04-01,VentaFacturadaUnidadNegocioSub,70009004,2.0,MK,11.0,644907.9,2,V,323007320,4
382,mk_11_3,2025-04-01,VentaFacturadaUnidadNegocioSub,70009004,3.0,MK,11.0,0.0,2,V,323007320,4
389,gu_3_1,2025-04-01,VentaFacturadaUnidadNegocioSub,70029961,1.0,GU,3.0,2808000.0,2,V,323007270,4

In [159]:
_calculo_variable_centro_costo_casos[_calculo_variable_centro_costo_casos['CodigoEmpleado'] == '5002899']

Empty DataFrame
Columns: [Contexto, Fecha, Variable, CodigoEmpleado, Consecutivo, TipoEmpleado, AreaCalculo, Liquidado, CodigoRubro, TipoCalculo, CodigoCentroCosto, Caso]
Index: []

In [160]:
_final_calculo_variable = pd.concat([
    calculo_variable.drop(columns=['Porcentaje']),
    _calculo_variable_centro_costo_casos
]).drop(columns=['PorcentajeCumplimiento', 'CodigoCentroCosto']).drop_duplicates()
_final_calculo_variable

,Contexto,Fecha,Variable,CodigoEmpleado,Consecutivo,TipoEmpleado,AreaCalculo,Liquidado,CodigoRubro,TipoCalculo,Caso
19,mk_11_1,2025-04-01,VentaFacturadaUnidadNegocioSub,1015417716,1.0,MK,11.0,2856000.0,2,V,0
20,mk_11_2,2025-04-01,VentaFacturadaUnidadNegocioSub,1015417716,2.0,MK,11.0,1617000.0,2,V,0
21,mk_11_3,2025-04-01,VentaFacturadaUnidadNegocioSub,1015417716,3.0,MK,11.0,0.0,2,V,0
67,mk_3_1,2025-04-01,VentaFacturadaUnidadNegocioSub,1031152912,1.0,MK,3.0,960000.0,2,V,0
68,mk_3_2,2025-04-01,VentaFacturadaUnidadNegocioSub,1031152912,2.0,MK,3.0,422400.0,2,V,0
...,...,...,...,...,...,...,...,...,...,...,...
325,5041387_5,2025-04-01,VentaFacturadaPortafolioClusterSub,5041387,5.0,VC,4.0,0.0,2,V,4
371,mk_11_1,2025-04-01,VentaFacturadaUnidadNegocioSub,70009004,1.0,MK,11.0,765385.2,2,V,4
372,mk_11_2,2025-04-01,VentaFacturadaUnidadNegocioSub,70009004,2.0,MK,11.0,644907.9,2,V,4
373,mk_11_3,2025-04-01,VentaFacturadaUnidadNegocioSub,70009004,3.0,MK,11.0,0.0,2,V,4
389,gu_3_1,2025-04-01,VentaFacturadaUnidadNegocioSub,70029961,1.0,GU,3.0,2808000.0,2,V,4

In [161]:
calculo_variable[
    (calculo_variable['TipoCalculo'] == 'V') & 
    (calculo_variable['CodigoEmpleado'] == '1032450706') &
     (calculo_variable['Fecha'] == '2023-09-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, Variable, PorcentajeCumplimiento, CodigoEmpleado, Porcentaje, Consecutivo, TipoEmpleado, AreaCalculo, Liquidado, CodigoRubro, TipoCalculo, Caso]
Index: []

In [162]:
liquidaciones_centro_costo_casos[
    (liquidaciones_centro_costo_casos['TipoCalculo'] == 'F') & 
    (liquidaciones_centro_costo_casos['CodigoEmpleado'] == '8520024')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso]
Index: []

In [163]:
_final_calculo_variable[
    (_final_calculo_variable['CodigoEmpleado'] == '5002899') &
     (_final_calculo_variable['Fecha'] == '2023-12-01')
]

Empty DataFrame
Columns: [Contexto, Fecha, Variable, CodigoEmpleado, Consecutivo, TipoEmpleado, AreaCalculo, Liquidado, CodigoRubro, TipoCalculo, Caso]
Index: []

In [164]:
maestra_resultados_por_empleado_centro_costo[
    (maestra_resultados_por_empleado_centro_costo['CodigoEmpleado'] == '5002899')
]

Empty DataFrame
Columns: [Contexto, Fecha, GrupoProducto, Division, CodigoCentroCosto, Real, Presupuesto, Variable, PorcentajeCumplimiento, RealCOP, PresupuestoCOP, PorcentajeCumplimientoCOP, CodigoEmpleado, Porcentaje, Consecutivo, Nombre variable, Nombre consecutivo, TipoEmpleado, AreaCalculo, Apellidos, Nombre, FechaIngreso, SalarioVariable]
Index: []

[0 rows x 23 columns]

In [165]:
final_calculo_variable = _final_calculo_variable.merge(
    right=maestra_resultados_por_empleado_centro_costo.rename(columns={'NombreRubro': 'Variable'}),
    on=['Fecha', 'Contexto', 'CodigoEmpleado', 'Variable', 'Consecutivo','TipoEmpleado', 'AreaCalculo'],
    how='left'
)[['Fecha', 'Contexto', 'CodigoEmpleado', 'TipoEmpleado','TipoCalculo', 'GrupoProducto', 'Division', 'Consecutivo', 'CodigoCentroCosto', 'Real','Variable', 'Liquidado', 'Caso']]
final_calculo_variable

,Fecha,Contexto,CodigoEmpleado,TipoEmpleado,TipoCalculo,GrupoProducto,Division,Consecutivo,CodigoCentroCosto,Real,Variable,Liquidado,Caso
0,2025-04-01,mk_11_1,1015417716,MK,V,610,HC,1.0,323015040,1.078784e+06,VentaFacturadaUnidadNegocioSub,2856000.0,0
1,2025-04-01,mk_11_1,1015417716,MK,V,620,HC,1.0,323015045,5.294477e+06,VentaFacturadaUnidadNegocioSub,2856000.0,0
2,2025-04-01,mk_11_1,1015417716,MK,V,630,HC,1.0,323015050,2.894142e+06,VentaFacturadaUnidadNegocioSub,2856000.0,0
3,2025-04-01,mk_11_1,1015417716,MK,V,640,HC,1.0,323015055,2.909605e+03,VentaFacturadaUnidadNegocioSub,2856000.0,0
4,2025-04-01,mk_11_1,1015417716,MK,V,680,HC,1.0,323015055,5.263154e+05,VentaFacturadaUnidadNegocioSub,2856000.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5876,2025-04-01,mk_11_2,70009004,MK,V,M07,AE,2.0,323010140,6.965117e+05,VentaFacturadaUnidadNegocioSub,644907.9,4
5877,2025-04-01,mk_11_2,70009004,MK,V,M08,AE,2.0,323010140,6.227095e+05,VentaFacturadaUnidadNegocioSub,644907.9,4
5878,2025-04-01,mk_11_3,70009004,MK,V,660,BA,3.0,323007337,4.961433e+04,VentaFacturadaUnidadNegocioSub,0.0,4
5879,2025-04-01,mk_11_3,70009004,MK,V,A45,BA,3.0,323007337,4.583982e+04,VentaFacturadaUnidadNegocioSub,0.0,4
5880,2025-04-01,gu_3_1,70029961,GU,V,001,AE,1.0,323007270,4.422712e+05,VentaFacturadaUnidadNegocioSub,2808000.0,4

In [166]:
final_calculo_variable[
    (final_calculo_variable['CodigoEmpleado'] == '5002899') &
     (final_calculo_variable['Fecha'] == '2023-12-01')
]

Empty DataFrame
Columns: [Fecha, Contexto, CodigoEmpleado, TipoEmpleado, TipoCalculo, GrupoProducto, Division, Consecutivo, CodigoCentroCosto, Real, Variable, Liquidado, Caso]
Index: []

In [167]:
final_calculo_variable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5881 entries, 0 to 5880
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Fecha              5881 non-null   datetime64[ns]
 1   Contexto           5881 non-null   object
 2   CodigoEmpleado     5881 non-null   object
 3   TipoEmpleado       5881 non-null   object
 4   TipoCalculo        5881 non-null   object
 5   GrupoProducto      5615 non-null   object
 6   Division           5615 non-null   object
 7   Consecutivo        5881 non-null   float64
 8   CodigoCentroCosto  5615 non-null   object
 9   Real               5778 non-null   float64
 10  Variable           5881 non-null   object
 11  Liquidado          5881 non-null   float64
 12  Caso               5881 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(8)
memory usage: 597.4+ KB

In [168]:
final_calculo_variable[
    (final_calculo_variable['CodigoEmpleado'] == '1032450706') &
     (final_calculo_variable['Fecha'] == '2023-09-01')
]

Empty DataFrame
Columns: [Fecha, Contexto, CodigoEmpleado, TipoEmpleado, TipoCalculo, GrupoProducto, Division, Consecutivo, CodigoCentroCosto, Real, Variable, Liquidado, Caso]
Index: []

In [169]:
final_calculo_variable = final_calculo_variable.groupby(['Fecha', 'CodigoEmpleado', 'TipoCalculo', 'CodigoCentroCosto', 'Consecutivo', 'Liquidado', 'Caso'], as_index=False)[['Real']].apply(sum)

final_calculo_variable.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_32488\2493841850.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  final_calculo_variable = final_calculo_variable.groupby(['Fecha', 'CodigoEmpleado', 'TipoCalculo', 'CodigoCentroCosto', 'Consecutivo', 'Liquidado', 'Caso'], as_index=False)[['Real']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

,Fecha,CodigoEmpleado,TipoCalculo,CodigoCentroCosto,Consecutivo,Liquidado,Caso,Real
0,2025-01-01,5002723,V,323007337,1.0,0.00,0,1.039187e+08
1,2025-01-01,5002723,V,323007337,2.0,0.00,0,1.052954e+08
2,2025-01-01,5002723,V,323007337,3.0,100584.75,0,3.047591e+06
3,2025-01-01,5002723,V,323007337,4.0,0.00,0,9.629012e+06
4,2025-01-01,5002723,V,323007337,5.0,0.00,0,3.090280e+06

In [170]:
final_calculo_variable['RealTotal'] = final_calculo_variable.groupby(
    ['Fecha', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo', 'Caso'], as_index=False
)['Real'].transform(pd.Series.sum)
final_calculo_variable

,Fecha,CodigoEmpleado,TipoCalculo,CodigoCentroCosto,Consecutivo,Liquidado,Caso,Real,RealTotal
0,2025-01-01,5002723,V,323007337,1.0,0.00,0,1.039187e+08,2.078373e+08
1,2025-01-01,5002723,V,323007337,2.0,0.00,0,1.052954e+08,2.105908e+08
2,2025-01-01,5002723,V,323007337,3.0,100584.75,0,3.047591e+06,6.095181e+06
3,2025-01-01,5002723,V,323007337,4.0,0.00,0,9.629012e+06,1.925802e+07
4,2025-01-01,5002723,V,323007337,5.0,0.00,0,3.090280e+06,6.180560e+06
...,...,...,...,...,...,...,...,...,...
3229,2025-04-01,70036160,V,323007260,2.0,0.00,0,1.157648e+09,3.472944e+09
3230,2025-04-01,70036160,V,323007300,1.0,472500.00,0,2.946602e+09,8.839806e+09
3231,2025-04-01,70036160,V,323007300,2.0,0.00,0,1.157648e+09,3.472944e+09
3232,2025-04-01,70036160,V,323007350,1.0,472500.00,0,2.946602e+09,8.839806e+09
3233,2025-04-01,70036160,V,323007350,2.0,0.00,0,1.157648e+09,3.472944e+09

In [171]:
final_calculo_variable['Valor Base Cálculo'] = final_calculo_variable.groupby(
    ['Fecha', 'CodigoEmpleado', 'TipoCalculo', 'CodigoCentroCosto', 'Consecutivo', 'Caso'], as_index=False
)['Liquidado'].transform(pd.Series.sum)
final_calculo_variable

,Fecha,CodigoEmpleado,TipoCalculo,CodigoCentroCosto,Consecutivo,Liquidado,Caso,Real,RealTotal,Valor Base Cálculo
0,2025-01-01,5002723,V,323007337,1.0,0.00,0,1.039187e+08,2.078373e+08,0.00
1,2025-01-01,5002723,V,323007337,2.0,0.00,0,1.052954e+08,2.105908e+08,0.00
2,2025-01-01,5002723,V,323007337,3.0,100584.75,0,3.047591e+06,6.095181e+06,100584.75
3,2025-01-01,5002723,V,323007337,4.0,0.00,0,9.629012e+06,1.925802e+07,0.00
4,2025-01-01,5002723,V,323007337,5.0,0.00,0,3.090280e+06,6.180560e+06,0.00
...,...,...,...,...,...,...,...,...,...,...
3229,2025-04-01,70036160,V,323007260,2.0,0.00,0,1.157648e+09,3.472944e+09,0.00
3230,2025-04-01,70036160,V,323007300,1.0,472500.00,0,2.946602e+09,8.839806e+09,472500.00
3231,2025-04-01,70036160,V,323007300,2.0,0.00,0,1.157648e+09,3.472944e+09,0.00
3232,2025-04-01,70036160,V,323007350,1.0,472500.00,0,2.946602e+09,8.839806e+09,472500.00
3233,2025-04-01,70036160,V,323007350,2.0,0.00,0,1.157648e+09,3.472944e+09,0.00

In [172]:
final_calculo_variable = final_calculo_variable.groupby(['Fecha', 'CodigoEmpleado', 'TipoCalculo', 'Caso', 'Consecutivo', 'CodigoCentroCosto', 'RealTotal', 'Valor Base Cálculo'], as_index=False)[['Real']].apply(sum)

C:\Users\HP\AppData\Local\Temp\ipykernel_32488\1680085628.py:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  final_calculo_variable = final_calculo_variable.groupby(['Fecha', 'CodigoEmpleado', 'TipoCalculo', 'Caso', 'Consecutivo', 'CodigoCentroCosto', 'RealTotal', 'Valor Base Cálculo'], as_index=False)[['Real']].apply(sum)
C:\Users\HP\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

In [173]:
final_calculo_variable['Porcentaje Aplicado'] = final_calculo_variable['Real']/final_calculo_variable['RealTotal']
final_calculo_variable = final_calculo_variable.rename(columns={
    'Fecha': 'Fecha Proceso'
})
final_calculo_variable['Valor Calculado'] = final_calculo_variable['Valor Base Cálculo'] * final_calculo_variable['Porcentaje Aplicado']
final_calculo_variable

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Caso,Consecutivo,CodigoCentroCosto,RealTotal,Valor Base Cálculo,Real,Porcentaje Aplicado,Valor Calculado
0,2025-01-01,5002723,V,0,1.0,323007337,2.078373e+08,0.00,1.039187e+08,0.500000,0.000
1,2025-01-01,5002723,V,0,1.0,323015065,2.078373e+08,0.00,1.039187e+08,0.500000,0.000
2,2025-01-01,5002723,V,0,2.0,323007337,2.105908e+08,0.00,1.052954e+08,0.500000,0.000
3,2025-01-01,5002723,V,0,2.0,323015065,2.105908e+08,0.00,1.052954e+08,0.500000,0.000
4,2025-01-01,5002723,V,0,3.0,323007337,6.095181e+06,100584.75,3.047591e+06,0.500000,50292.375
...,...,...,...,...,...,...,...,...,...,...,...
3229,2025-04-01,70036160,V,0,1.0,323007300,8.839806e+09,472500.00,2.946602e+09,0.333333,157500.000
3230,2025-04-01,70036160,V,0,1.0,323007350,8.839806e+09,472500.00,2.946602e+09,0.333333,157500.000
3231,2025-04-01,70036160,V,0,2.0,323007260,3.472944e+09,0.00,1.157648e+09,0.333333,0.000
3232,2025-04-01,70036160,V,0,2.0,323007300,3.472944e+09,0.00,1.157648e+09,0.333333,0.000
3233,2025-04-01,70036160,V,0,2.0,323007350,3.472944e+09,0.00,1.157648e+09,0.333333,0.000

In [174]:
final_calculo_variable = final_calculo_variable[
    ['Fecha Proceso', 'CodigoEmpleado', 'TipoCalculo', 'Consecutivo', 'CodigoCentroCosto', 'Valor Base Cálculo', 'Porcentaje Aplicado', 'Valor Calculado', 'Caso']
]
final_calculo_variable

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,CodigoCentroCosto,Valor Base Cálculo,Porcentaje Aplicado,Valor Calculado,Caso
0,2025-01-01,5002723,V,1.0,323007337,0.00,0.500000,0.000,0
1,2025-01-01,5002723,V,1.0,323015065,0.00,0.500000,0.000,0
2,2025-01-01,5002723,V,2.0,323007337,0.00,0.500000,0.000,0
3,2025-01-01,5002723,V,2.0,323015065,0.00,0.500000,0.000,0
4,2025-01-01,5002723,V,3.0,323007337,100584.75,0.500000,50292.375,0
...,...,...,...,...,...,...,...,...,...
3229,2025-04-01,70036160,V,1.0,323007300,472500.00,0.333333,157500.000,0
3230,2025-04-01,70036160,V,1.0,323007350,472500.00,0.333333,157500.000,0
3231,2025-04-01,70036160,V,2.0,323007260,0.00,0.333333,0.000,0
3232,2025-04-01,70036160,V,2.0,323007300,0.00,0.333333,0.000,0
3233,2025-04-01,70036160,V,2.0,323007350,0.00,0.333333,0.000,0

In [175]:
# final_calculo_variable = pd.concat([
#     final_calculo_variable,
#     liquidaciones_centro_costo_casos[liquidaciones_centro_costo_casos['TipoCalculo'] == 'V']
# ])
# final_calculo_variable

In [176]:
final_calculo_variable[
    (final_calculo_variable['CodigoEmpleado'] == '5002899') &
     (final_calculo_variable['Fecha Proceso'] == '2023-12-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, CodigoCentroCosto, Valor Base Cálculo, Porcentaje Aplicado, Valor Calculado, Caso]
Index: []

In [177]:
final_calculo_variable[
    (final_calculo_variable['CodigoEmpleado'] == '1032450706') &
     (final_calculo_variable['Fecha Proceso'] == '2023-12-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, CodigoCentroCosto, Valor Base Cálculo, Porcentaje Aplicado, Valor Calculado, Caso]
Index: []

In [178]:
final_calculo_variable.to_excel('final_calculo_variable.xlsx')

### Se unifican Tipo Cálculo Fijo y Variable

In [179]:
final_calculo_fijo.head()

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso,Valor Calculado
0,2025-01-01,5002697,F,0.0,1068720.0,323015045,1.0,0,1068720.0
1,2025-01-01,5002699,F,0.0,762850.0,323015095,0.8,0,610280.0
2,2025-01-01,5002699,F,0.0,762850.0,323015100,0.2,0,152570.0
3,2025-01-01,5002700,F,0.0,1044775.0,323007332,0.1,0,104477.5
4,2025-01-01,5002700,F,0.0,1044775.0,323007333,0.1,0,104477.5

In [180]:
final_calculo_fijo[final_calculo_fijo['CodigoEmpleado'] == '1098612757']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso, Valor Calculado]
Index: []

In [181]:
len(final_calculo_fijo[final_calculo_fijo['CodigoEmpleado'] == '1098612757'])

0

In [182]:
consolidado_final_calculo_fijo_sin_repetidos[consolidado_final_calculo_fijo_sin_repetidos['CodigoEmpleado'] == '1098612757']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso, Valor Calculado]
Index: []

In [183]:
len(consolidado_final_calculo_fijo_sin_repetidos[consolidado_final_calculo_fijo_sin_repetidos['CodigoEmpleado'] == '1098612757'])

0

In [184]:
final_calculo_variable.head()

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,CodigoCentroCosto,Valor Base Cálculo,Porcentaje Aplicado,Valor Calculado,Caso
0,2025-01-01,5002723,V,1.0,323007337,0.00,0.5,0.000,0
1,2025-01-01,5002723,V,1.0,323015065,0.00,0.5,0.000,0
2,2025-01-01,5002723,V,2.0,323007337,0.00,0.5,0.000,0
3,2025-01-01,5002723,V,2.0,323015065,0.00,0.5,0.000,0
4,2025-01-01,5002723,V,3.0,323007337,100584.75,0.5,50292.375,0

In [185]:
final_calculo_fijo[
    (final_calculo_fijo['CodigoEmpleado'] == '1032450706') &
     (final_calculo_fijo['Fecha Proceso'] == '2023-09-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso, Valor Calculado]
Index: []

In [186]:
final_calculo_variable[
    (final_calculo_variable['CodigoEmpleado'] == '1032450706') &
     (final_calculo_variable['Fecha Proceso'] == '2023-09-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, CodigoCentroCosto, Valor Base Cálculo, Porcentaje Aplicado, Valor Calculado, Caso]
Index: []

In [187]:
resultado_liquidaciones_centro_costo = pd.concat(
    [ final_calculo_fijo,
      final_calculo_variable,
#      consolidado_final_calculo_fijo_sin_repetidos
    ]
)
resultado_liquidaciones_centro_costo[
    (resultado_liquidaciones_centro_costo['CodigoEmpleado'] == '8520024') &
     (resultado_liquidaciones_centro_costo['Fecha Proceso'] == '2023-09-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso, Valor Calculado]
Index: []

In [188]:
resultado_liquidaciones_centro_costo[
    (resultado_liquidaciones_centro_costo['CodigoEmpleado'] == '8520024') &
     (resultado_liquidaciones_centro_costo['Fecha Proceso'] == '2023-09-01') &
    (resultado_liquidaciones_centro_costo['TipoCalculo'] == 'F')
]['Valor Calculado'].sum()

0.0

In [189]:
6048000.0+2340000.0+198000.0

8586000.0

In [190]:
len(resultado_liquidaciones_centro_costo[resultado_liquidaciones_centro_costo['CodigoEmpleado'] == '1098612757'])

0

In [191]:
resultado_liquidaciones_centro_costo[
    (resultado_liquidaciones_centro_costo['CodigoEmpleado'] == '5002899') &
    (resultado_liquidaciones_centro_costo['Fecha Proceso'] == '2023-12-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso, Valor Calculado]
Index: []

In [192]:
nombre_archivo_salida = "resultado_liquidaciones_centro_costo (" + fecha_liquidacion + ").xlsx"
nombre_archivo_salida

'resultado_liquidaciones_centro_costo (2025-04-01).xlsx'

In [193]:
resultado_liquidaciones_centro_costo.to_excel(nombre_archivo_salida)

In [194]:
resultado_liquidaciones_centro_costo[
    (resultado_liquidaciones_centro_costo['CodigoEmpleado'] == '8520024') &
    (resultado_liquidaciones_centro_costo['Fecha Proceso'] == '2023-12-01')
]

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, Valor Base Cálculo, CodigoCentroCosto, Porcentaje Aplicado, Caso, Valor Calculado]
Index: []

In [195]:
resultado_liquidaciones_centro_costo[resultado_liquidaciones_centro_costo['CodigoEmpleado'] == '5016692']

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso,Valor Calculado
72,2025-01-01,5016692,F,0.0,924100.00,323015065,0.340000,0,3.141940e+05
73,2025-01-01,5016692,F,0.0,924100.00,323015070,0.330000,0,3.049530e+05
74,2025-01-01,5016692,F,0.0,924100.00,323015075,0.330000,0,3.049530e+05
296,2025-02-01,5016692,F,0.0,1931370.00,323015065,0.340000,0,6.566658e+05
297,2025-02-01,5016692,F,0.0,1931370.00,323015070,0.330000,0,6.373521e+05
298,2025-02-01,5016692,F,0.0,1931370.00,323015075,0.330000,0,6.373521e+05
547,2025-03-01,5016692,F,0.0,6124125.76,323015065,0.340000,0,2.082203e+06
548,2025-03-01,5016692,F,0.0,6124125.76,323015070,0.330000,0,2.020962e+06
549,2025-03-01,5016692,F,0.0,6124125.76,323015075,0.330000,0,2.020962e+06
832,2025-04-01,5016692,F,0.0,29262868.56,323015065,0.340000,0,9.949375e+06
833,2025-04-01,5016692,F,0.0,29262868.56,323015070,0.330000,0,9.656747e+06
834,2025-04-01,5016692,F,0.0,29262868.56,323015075,0.330000,0,9.656747e+06
194,2025-01-01,5016692,V,1.0,0.00,323015040,0.119934,0,0.000000e+00
195,2025-01-01,5016692,V,1.0,0.00,323015045,0.540486,0,0.000000e+00
196,2025-01-01,5016692,V,1.0,0.00,323015050,0.297467,0,0.000000e+00
197,2025-01-01,5016692,V,1.0,0.00,323015055,0.042114,0,0.000000e+00
903,2025-02-01,5016692,V,1.0,0.00,323015040,0.104862,0,0.000000e+00
904,2025-02-01,5016692,V,1.0,0.00,323015045,0.553609,0,0.000000e+00
905,2025-02-01,5016692,V,1.0,0.00,323015050,0.290996,0,0.000000e+00
906,2025-02-01,5016692,V,1.0,0.00,323015055,0.050534,0,0.000000e+00
1688,2025-03-01,5016692,V,1.0,0.00,323015040,0.038064,0,0.000000e+00
1689,2025-03-01,5016692,V,1.0,0.00,323015045,0.209559,0,0.000000e+00
1690,2025-03-01,5016692,V,1.0,0.00,323015050,0.111678,0,0.000000e+00
1691,2025-03-01,5016692,V,1.0,0.00,323015055,0.020569,0,0.000000e+00
1692,2025-03-01,5016692,V,1.0,0.00,323015065,0.206710,0,0.000000e+00
1693,2025-03-01,5016692,V,1.0,0.00,323015070,0.206710,0,0.000000e+00
1694,2025-03-01,5016692,V,1.0,0.00,323015075,0.206710,0,0.000000e+00
2598,2025-04-01,5016692,V,1.0,5918865.00,323015040,0.029228,0,1.729959e+05
2599,2025-04-01,5016692,V,1.0,5918865.00,323015045,0.143445,0,8.490328e+05
2600,2025-04-01,5016692,V,1.0,5918865.00,323015050,0.078412,0,4.641103e+05
2601,2025-04-01,5016692,V,1.0,5918865.00,323015055,0.014338,0,8.486757e+04
2602,2025-04-01,5016692,V,1.0,4932387.50,323015065,0.244859,0,1.207738e+06
2603,2025-04-01,5016692,V,1.0,4932387.50,323015070,0.244859,0,1.207738e+06
2604,2025-04-01,5016692,V,1.0,4932387.50,323015075,0.244859,0,1.207738e+06

In [196]:
final_calculo_variable[final_calculo_variable['CodigoEmpleado'] == '1098612757']

Empty DataFrame
Columns: [Fecha Proceso, CodigoEmpleado, TipoCalculo, Consecutivo, CodigoCentroCosto, Valor Base Cálculo, Porcentaje Aplicado, Valor Calculado, Caso]
Index: []

In [197]:
resultado_liquidaciones_centro_costo[resultado_liquidaciones_centro_costo['CodigoEmpleado'] == '5004293']

,Fecha Proceso,CodigoEmpleado,TipoCalculo,Consecutivo,Valor Base Cálculo,CodigoCentroCosto,Porcentaje Aplicado,Caso,Valor Calculado
27,2025-01-01,5004293,F,0.0,204975.00,323015090,1.0,0,204975.00
251,2025-02-01,5004293,F,0.0,481695.00,323015090,1.0,0,481695.00
486,2025-03-01,5004293,F,0.0,1580536.86,323015090,1.0,0,1580536.86
487,2025-03-01,5004293,F,10.0,0.00,323015090,1.0,0,0.00
782,2025-04-01,5004293,F,0.0,9401786.16,323015090,1.0,0,9401786.16
783,2025-04-01,5004293,F,10.0,0.00,323015090,1.0,0,0.00